### ISSUE TITLE
Validation for `date` format allows invalid dates

### ISSUE THREAD

**Issue by maldimirov** [ajv-validator/ajv#1000]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.0

**Ajv options object**

```javascript
{
    allErrors: true,
},
```

**JSON Schema**

```json
{
   "type": "array",
    "items": {
        "type": "string",
        "format": "date",
    },
}
```

**Sample data**

```json
[
    "2018-02-29",
    "2018-02-35",
    "2018-15-01",
]
```

**Your code**

```javascript
const ajv = new Ajv(options);
const isValid = ajv.validate(schema, data);
const errors = ajv.errors;
```

Also in [RunKit](https://runkit.com/maldimirov/ajv-issue-1000).

**Validation result, data AFTER validation, error messages**

```
isValid = true;
errors = null;
```

**What results did you expect?**
The validation should fail for all values. You can check the same issue in the [`enjoi` project](https://github.com/tlivings/enjoi/issues/63). It refers to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The validation should restrict the max date number to the specific month, taking into account leap years.

**Are you going to resolve the issue?**
Atm I haven't dug into `ajv`'s codebase to see how to resolve this. I have already done it using Regex in [enjoi](https://github.com/tlivings/enjoi/pull/64/files). So I can try or at least help :)

**Comment by epoberezkin** [comment]
You need to use the option format: 'full'

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv/issues/996

**Comment by maldimirov** [comment]
You are correct. Sorry for wasting your time :) Thank you for a great library!

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you add it into doc's? @epoberezkin
