### ISSUE TITLE
Validate with #/.. does't work when used with custom keywords

### ISSUE THREAD

**Issue by ovx** [ajv-validator/ajv#1001]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.10

**Ajv options object**
**JSON Schema**
**Sample data**
**Your code**

https://runkit.com/embed/gfk2ixcd5gbp

**Validation result, data AFTER validation, error messages**

```
Error: no schema with key or ref "#/definitions/Data"
```

**What results did you expect?**

To find and validate the schema. __It works without the custom keyword__ (just remove addKeyword and it works as expected).

**Are you going to resolve the issue?**

I have no clue why is this happening and how to fix it.

**Comment by epoberezkin** [comment]
Weird. It does it even if the keyword is not used: https://runkit.com/esp/5cc168d8b741f4001afde85e

**Comment by epoberezkin** [comment]
Actually, a bigger question is why it works without addKeyword... You need to use $id with schemas that are added (rather than just compiled).

**Comment by ovx** [comment]
Yes, it works with `$id`. Thanks
