### ISSUE TITLE
Add docs on merging schemas into one file (use array)

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ajv-validator/ajv#1002]
Comment

**Comment by shelru** [comment]
How use refs with local/url path?

//
Faced with the problem that all schemes with the same parameters-it is difficult to keep track. I decided to allocate each common element in a separate scheme.

Structure:
```
schemas
    - parts
       login.json
       password.json
   
     auth.json
```

```{
    "type": "object",
    "minProperties":1,
    "maxProperties":1,
    "definitions": {
        "login": { "type": "string", "minLength": 4, "maxLength": 20}
    },
    "required": ["login"],
    "additionalProperties": false
}```

```{
    "type": "object",
    "minProperties":1,
    "maxProperties":1,
    "definitions": {
        "password": { "type": "string", "minLength": 4, "maxLength": 20}
    },
    "required": ["password"],
    "additionalProperties": false
}```

auth.json:
```
{
  "type": "object",
  "minProperties":2,
  "maxProperties":2,
  "properties": {
    "login": { "$ref": "parts/login.json#/definitions/login"},
    "password": { "$ref": "parts/login.json#/definitions/password"}
  },
  "required": ["login", "password"],
  "additionalProperties": false
}
```
![image](https://user-images.githubusercontent.com/9306996/57066971-c1b64c00-6cde-11e9-923d-1b396d8a59c6.png)


//
Почему подобное происходит - догадываюсь, но лучше переспросить. Выходит мне нужно каким-то методом загонять схему в память, затем уже обращаться к ней?
И еще если не сложно, подскажи, нужны ли в обоих случаях required и additionalProperties или же достаточно только в definition's схемах указать их? Или лучше не указывать в definition's, а указать в основных?

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/57067317-b4e62800-6cdf-11e9-82d6-ebc7d1a15207.png)
![image](https://user-images.githubusercontent.com/9306996/57067335-bfa0bd00-6cdf-11e9-99c6-9e665704b0d1.png)
![image](https://user-images.githubusercontent.com/9306996/57067351-caf3e880-6cdf-11e9-8c0a-32df2d292c5a.png)

Right?

**Comment by shelru** [comment]
Is there any type for unsigned int? (0xffffffff)
`"id": { "type": "integer", "minimum": 1,"maximum":4294967295}`
to avoid it

**Comment by shelru** [comment]
And one more:
How to make it work?
![image](https://user-images.githubusercontent.com/9306996/57068289-58383c80-6ce2-11e9-85e5-ce7292d8c008.png)
![image](https://user-images.githubusercontent.com/9306996/57068306-60907780-6ce2-11e9-9a75-11e778a2c0f7.png)
![image](https://user-images.githubusercontent.com/9306996/57068376-9f263200-6ce2-11e9-9d20-6f9ebcf2e27e.png)
```json
{
    "type": "object",
    "definitions": {
        "login": { "type": "string", "minLength": 4, "maxLength": 20},
        "password": { "type": "string", "minLength": 4, "maxLength": 64},
        "gid": { "type": "integer", "minimum": 1,"maximum":4294967295},
        "LastRowId": { "type": "integer", "minimum": 0,"maximum":4294967295},
        "perPage": { "type": "integer", "minimum": 5, "maximum": 20},
        "some":{
            "id": { "type": "integer", "minimum": 1,"maximum":123}
        }
    }
}
```

**Comment by shelru** [comment]
```json
{ "$ref": "params#/some/id"}

{
    "type": "object",
    "definitions": {
        "login": { "type": "string", "minLength": 4, "maxLength": 20},
        "password": { "type": "string", "minLength": 4, "maxLength": 64},
        "gid": { "type": "integer", "minimum": 1,"maximum":4294967295},
        "LastRowId": { "type": "integer", "minimum": 0,"maximum":4294967295},
        "perPage": { "type": "integer", "minimum": 5, "maximum": 20}
    },
    "some": {
        "id": { "type": "integer", "minimum": 1,"maximum":1234}
    }
}
```
same

**Comment by shelru** [comment]
{schemaId: 'auto'}
helped
but
is there anyway for 
![image](https://user-images.githubusercontent.com/9306996/57068898-17d9be00-6ce4-11e9-85f2-f3752a70b737.png)
![image](https://user-images.githubusercontent.com/9306996/57068907-1c05db80-6ce4-11e9-8513-8267bed3cbf1.png)

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/57068947-393aaa00-6ce4-11e9-90a2-b0802919b7ee.png)
![image](https://user-images.githubusercontent.com/9306996/57068953-4192e500-6ce4-11e9-80ea-45c99968a1ff.png)
![image](https://user-images.githubusercontent.com/9306996/57068968-46579900-6ce4-11e9-9d86-e8d388ecbe42.png)

**Comment by shelru** [comment]
var PREVENT_SCOPE_CHANGE = util.toHash(['properties', 'patternProperties', 'enum', 'dependencies', 'definitions']);
srsly)?

**Comment by epoberezkin** [comment]
I don’t understand what you are trying to achieve?

**Comment by shelru** [comment]
General schema to be edited in the future, and the other schemas (more detailed) that will use ref to access data(definitions) from this.
And unsigned int.

**Comment by epoberezkin** [comment]
Unsigned int is not a type in JSON, you can just use minimum: 0. The rest I still don’t understand. Normally, “definitions” is the object where each value is a schema. You are doing something different, not sure what.

**Comment by shelru** [comment]
Если уж совсем прямо, то у меня есть схемы, описывающие ограничения таблиц и типы колонок.
![image](https://user-images.githubusercontent.com/9306996/57132135-b0894000-6daf-11e9-91ea-2ff9975d993e.png)
![image](https://user-images.githubusercontent.com/9306996/57132183-d878a380-6daf-11e9-8276-dcc66f00f96e.png)

Которые в разных роутах используются как отдельные валидаторы, для проверки входных параметров:
![image](https://user-images.githubusercontent.com/9306996/57132207-ea5a4680-6daf-11e9-8fbc-3e1c5f630c00.png)

Я бы хотел вместо двух separate файлов (.json), сделать один общий, в котором бы все это описывалось, просто под разными ветками.

**Comment by shelru** [comment]
mainschema/definitions/group/id
mainschema/definitions/users/id

**Comment by shelru** [comment]
Видимо это ограничения ajv и здесь никак иначе не сделаешь?

**Comment by shelru** [comment]
> Each value is schema
So, i get u. Is there any way to implement 'each value can be object'?

**Comment by epoberezkin** [comment]
The best approach to merge multiple schemas into one JSON file is to use array of schemas referencing each other, rather than trying to merge them into one schema - it is non-trivial in general case.

**Comment by shelru** [comment]
Ok. Thank's. Add usage, question label and close.

**Comment by epoberezkin** [comment]
>> Each value is schema

> So, i get u. Is there any way to implement 'each value can be object'?

The spec requires them to be schemas - see meta-schema: https://github.com/epoberezkin/ajv/blob/master/lib/refs/json-schema-draft-07.json

**Comment by shelru** [comment]
@epoberezkin Is there anyway to check require min 2 args, where one is static(every time must be defined) and other's optional?
Like: id, password; id, login; id, name, password etc.
