### ISSUE TITLE
 multipleOf with decimals fails validation

### ISSUE THREAD

**Issue by satyavh** [ajv-validator/ajv#1005]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
latest version

** Issue **
The following schema fails validation (probably due to float calculations) for example:
value `0.94` fails,
value `0.93` passes

```
var schema = {
    "type": "number",
    "minimum": 0,
    "multipleOf": 0.01
};
```

Here's the Runkit
https://runkit.com/embed/5elnwf1fku5z

A possible solution could maybe be to use BigNumberJS internally.

**Comment by satyavh** [comment]
FYI, jsonschema library does this correctly, you might want to check the code here
https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L427-L452

**Comment by epoberezkin** [comment]
There is an option multipleOfPrecision to address it.

**Comment by satyavh** [comment]
I don't see `multipleOfPrecision` being part of jsonschema specs?

**Comment by satyavh** [comment]
OK got it, it's a setting :-)
Thanks
