### ISSUE TITLE
Validation fails for number field if no value

### ISSUE THREAD

**Issue by musa-pro** [ajv-validator/ajv#1007]
Hi,
 I'm using JSON schema draft version 4 using following codes - 
```
            let ajv = new Ajv({schemaId: 'id'});
            ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));
              let valid = ajv.validate(schema, data); 
              if (!valid) throw ajv.errors;
```

Few of the fields are defined as number and not required. Thus if I pass "" of those fields have no value, validation fails and it says - 
"should be a number"

How can I pass empty value then so validator wont through error for that?

Thanks
Musa

**Comment by epoberezkin** [comment]
An empty string is a value of type string, it is not a number. If the property is absent it would pass.

**Comment by musa-pro** [comment]
Thanks @epoberezkin

**Comment by fredtma** [comment]
Hi,
When I defined a schema with a number type & coerceTypes: true. 
Why does it not convert an empty string to `0`?
```
    const schema = {
      type: 'object',
      properties: {
        foo: {type: 'integer', default: 0},
        bar: {type: 'boolean'}
      },
      required: ['foo', 'bar']
    };

    const data1 = {foo: '', bar: 'false'}; // fails
    const data2 = {foo: ' ', bar: 'false'}; // passes -> foo = 0
    const data3 = {foo: null, bar: 'false'}; // passes -> foo = 0
    const data4 = {foo: undefined, bar: 'false'}; // passes -> foo = 0
````
if you type `+''` you get `0` so why does the validation fail on an empty string and passes on a blank string
