### ISSUE TITLE
Validation fails for integer field values starting with 0

### ISSUE THREAD

**Issue by guruvi** [ajv-validator/ajv#1008]
JSON schema validation fails for the integer fields starting with 0 or 00 or 0000....

AJV version **6.10.0**

```const schema = {
  type: "object",
 properties: {
value: {
type: "integer"
}
}
}
```

Schema validation for integer value fails when the value is 
```json
{
value: 0100
}

```

**Comment by epoberezkin** [comment]
It does work: https://runkit.com/esp/5cdeb9fae1bb3e001cbda3ed
What may be the problem is that if you try to use integers starting from 0 in JSON (commented code) - it is not allowed by JSON spec.

**Comment by GlenTiki** [comment]
Hey @epoberezkin, I've chatted with @guruvi directly and we discovered the problem to be that he was attempting to transmit invalid JSON as per the JSON spec with the leading zeros, and a `JSON.parse` call was failing before hitting AJV in an upstream module that depends on this one. I validated everything is working in AJV as expected. This issue can be closed.
