### ISSUE TITLE
question: Validating data against a portion of a schema

### ISSUE THREAD

**Issue by whitlockjc** [ajv-validator/ajv#1009]
Is there a way to validate data against a specific sub-schema within a JSON Schema document?  Let's say I have an object representing a person, and it's JSON Schema is located in my full schema at `#/models/Person`.  How can I ask `ajv` to validate my data against `#/models/Person`?  I could use [json-refs](https://github.com/whitlockjc/json-refs) to fully-resolve my large JSON Schema document _(to make sure all `$ref` under `#/definitions/Person` are resolved, resulting in a complete JSON Schema at `#/models/Person`)_, cherry-pick the sub-schema at `#/models/Person` and then use `ajv` but it would be slick if I could ask `ajv` to use a schema within an existing JSON Schema.

**Comment by whitlockjc** [comment]
Also, it would be slick if you had an issue template for questions.  Thanks for your hard work on `ajv`.

**Comment by epoberezkin** [comment]
You can use getSchema with JSON pointer to get subschema

**Comment by kentcb** [comment]
@epoberezkin Any chance you could provide a quick example? I'm not clear on how this should look. Currently I have:

```javascript
this.ajv.addSchema(schema, 'foo');

var schema = this.ajv.getSchema('foo');
var valid = schema(json);
```
This works as expected, but I now want to validate against a `#/something/bar` object in the schema. I've tried passing in `'#/something/bar` (as well as `/something/bar` and `something/bar`) to every other argument to the call, but that has not worked.

Any tips?

**Comment by kentcb** [comment]
OK, I figured it out. The solution looks like this:

```javascript
this.ajv.addSchema(schema);

var subSchema = this.ajv.getSchema('https://my-schema-id/foo.json#definitions/bar');
```
