### ISSUE TITLE
Add format to support ISO 8601 Duration

### ISSUE THREAD

**Issue by thibaltus** [ajv-validator/ajv#1011]
**What version of Ajv you are you using?**
6.5.3

**What problem do you want to solve?**
Add new format 'duration' as ISO 8601 Duration

**What do you think is the correct solution to problem?**
This improvement just need to update lib/compile/formats.js:
  - Add ISO Duration regex as constants
  - Add this regex to format.fast.duration and format.full.duration

**Will you be able to implement it?**
With pleasure

**Comment by epoberezkin** [comment]
It is not a format required by JSON Schema spec, it should be added by application or by a plugin using addFormat.
