### ISSUE TITLE
.DS_Store in installed lib

### ISSUE THREAD

**Issue by OrangeDog** [ajv-validator/ajv#1017]
`npm install ajv@6.10.0` creates the file `node_modules/avj/lib/.DS_Store`

I'm not using macOS so I'm pretty sure it's not at my end.

npm 6.4.1, node 10.15.3

**Comment by epoberezkin** [comment]
Should be removed and added to gitignore

**Comment by epoberezkin** [comment]
It's strange - https://docs.npmjs.com/files/package.json#files says it should be ignored...

**Comment by epoberezkin** [comment]
removed in 6.10.1
