### ISSUE TITLE
Array/enum of allowed strings/values

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ajv-validator/ajv#1024]
How i can make it?
for example:
type array
allowedStrings:['abcd','efgh','123','check','it','out'].
minElements: 1
Data:
['abcd','123'] -> valid
['abcd','kekc'] -> invalid
['abcd',123] -> invalid
[] -> invalid

**Comment by epoberezkin** [comment]
Use "enum" - see JSON Schema documentation or KEYWORDS.md
