### ISSUE TITLE
Add option to remove additional properties when additionalProperties is falsy

### ISSUE THREAD

**Issue by mitchellderijcke** [ajv-validator/ajv#1025]
**What version of Ajv you are you using?**
6.10.0

**What problem do you want to solve?**
Produce clean objects by removing unknown properties when `additionalProperities` is falsy. My use case is an OpenAPI client I'm building.

**What do you think is the correct solution to problem?**
Add a `"falsy"` value to the `removeAdditional` option.

**Will you be able to implement it?**
Yes. It's trivial. See first version: https://github.com/rijx/ajv/tree/add-falsy-option

**Comment by epoberezkin** [comment]
This idea is at odds with JSON Schema spec which says that absent additionalProperty and "additionalProperties: true" are equivalent.

If the problem this is solving is accidentally forgetting to add "additionalProperties: false", the correct answer is "linting" to require that additionalProperties is always defined (there should be some linters for JSON Schema out there) or pre-processing the schema and adding "additionalProperties: false" whenever it is absent.

Either way, even if this option is added, "falsy" seems the wrong name - it implies that additionalProperties can be anything other than true/false (and it would make the schema invalid).
