### ISSUE TITLE
Unicode support in pattern

### ISSUE THREAD

**Issue by JonathanWilbur** [ajv-validator/ajv#1026]
Ajv Version: 6.10.0

Ajv does not validate the `pattern` regex using the Unicode flag `u`, which means that Unicode groups, such as `\\p{L}` will not work. I believe this can be seen and fixed here: `ajv/lib/dot/pattern.jst`.

**Comment by epoberezkin** [comment]
TBC if it should be used: http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.3

You can use custom keyword - e.g. regex in ajv-keywords.

**Comment by JonathanWilbur** [comment]
I don't see where the linked specification, or the ECMAScript specification to which it links, says that the `u` flag cannot be used, but I see your point about the `custom` keyword. I will use that. Thank you!

**Comment by xDiezz** [comment]
https://github.com/yury-dymov/js-regex-pl use this
