### ISSUE TITLE
Errors created without stack

### ISSUE THREAD

**Issue by JonathanWilbur** [ajv-validator/ajv#1027]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.10.0 and yes.

It seems that `Ajv` creates subclasses of `Error` in an unusual way that leaves them without a `stack`. May I ask why a simple `extend` of the `Error` class was not used instead? It seems like there is a much better way of doing this that leaves the expected members intact.

This peculiarity adversely affected the Serverless Framework. I have opened an [issue](https://github.com/serverless/serverless/issues/6267) on their side to get them to check that the `stack` member exists before attempting to `split()` it, but this should still be remediated here, too, if possible.

https://github.com/epoberezkin/ajv/blob/ab841b462ec4baff37d2a7319cef13820b53d963/lib/compile/error_classes.js#L5-L15

Then further down:

https://github.com/epoberezkin/ajv/blob/ab841b462ec4baff37d2a7319cef13820b53d963/lib/compile/error_classes.js#L30-L34

**Comment by epoberezkin** [comment]
This is the only backward compatible way to create a subclass - ES5 does not have another class extension mechanism (and the new ES6 syntax produces exactly the same result internally - "extends" links prototypes in the same way as the code you reference).

I've never seen the issues with stack traces in node or browser - it may be that your environment has the issue that it does not work with Error subclasses, regardless how they are created.

I suggest updating the code with ES6 syntax and checking if the issue remains - I expect it will.

**Comment by silverwind** [comment]
I too noticed the absence of stack traces but only in ES6 environments. The code is transpiled using babel and I do see stack traces in IE11 (which I think counts as ES5) but not in Firefox or Chrome.

**Comment by epoberezkin** [comment]
@silverwind thanks for confirming. It would definitely help if the issue remains if you move the code to ES6 (class syntax). I expect that the issue would remain for the reasons above - same internal structures used for class syntax. But it’s definitely worth checking if you need it addressed.

**Comment by epoberezkin** [comment]
v7 uses ES6 classes
