### ISSUE TITLE
Any mechanism to clear the cache?

### ISSUE THREAD

**Issue by pictin** [ajv-validator/ajv#103]
Is there any mechanism to clear ajv's cache?

I'm using multiple schemas that depend on a common "definitions" schema. The code goes like:

ajv.addSchema(definitionsSchema, 'def');
ajv.validate(schema1, object1);
ajv.validate(schema2, object2);
ajv.validate(schema3, object3);

everything is great until I'm trying to hot-plug the definitions:

ajv.removeSchema('def');
ajv.addSchema(definitionsSchema2, 'def');

ajv.validate(schema1, object1_for_definitions2);    // VALIDATION FAILS!!!

Because schemas are getting cached along with $ref's that link to now-defunct definitions file.
My debugging was able to pinpoint the problem to stale cache.

I'm aware of three ways to get around this problem:
1. Explicitly remove all schemas that I was using. This is a little ugly, because I will need to keep track of all of them;
2. Reinitialize entire Ajv. This is what I'm doing now, but it feels like an overkill;
3. Provide my own cache that has this capability. Also a bit of an overkill;

IMHO it would be nice to provide a way just to clear the ajv's cache.

**Comment by epoberezkin** [comment]
Creating a new instance is the way to go I think...

**Comment by pictin** [comment]
Ok, fair enough.
I think adding a line or two to the documentation might help.
"Even if schema is referenced by other schemas it can be safely removed as dependent schemas have local references." - this should have given me a nice clue, but I still spent half a day poking around.

**Comment by epoberezkin** [comment]
The disadvantage of re-creating the instance is that it has compiled meta-schema(s) so if you are replacing dependencies often it's a waste to recompile meta-schemas every time.

Also if the instance has custom keywords / formats added than re-creating it may be a bit annoying.

It think the existing method `removeSchema` can be extended to accept RegExp that would allow to remove many/all schemas (`/.*/`) by iterating this._refs and this._schemas for matching refs and keys, excluding meta-schemas.

@pictin what do you think? you are welcome to implement of course if you have time for it (with docs and tests) - I would appreciate it.

**Comment by epoberezkin** [comment]
in 3.8.0
