### ISSUE TITLE
Custom. Overload (reuse) present handlers

### ISSUE THREAD

**Issue by askirmas** [ajv-validator/ajv#1032]
In example - I'd prefer to extend $ref for uri-reference in my project.
Something like
```javascript
const originalRef = ajv.getKeyword($ref)
ajv.addKeyword('$ref', Object.assign({}, originalRef, {
   inline: function (it, keyword, schema) {
     if (!it.startsWith('.'))
       return originalRef.inline(...arguments)
    // Custom scope
  }
}))
```

**What version of Ajv you are you using?**
ajv-cli latest
**What problem do you want to solve?**
Raise reuse, solve conflict with Microsoft VS Code validator
**What do you think is the correct solution to problem?**
Add method avj.getKeyword
**Will you be able to implement it?**
yes i hope

**Comment by epoberezkin** [comment]
I don't think that changing the behaviour of standard keywords is a good idea.

Particularly with $ref - its behaviour is quite complex, so providing api to change or extend it is non-trivial.

What's the conflict you are trying to avoid?

**Comment by epoberezkin** [comment]
Closing it. I do not support the idea of overloading standard keywords with a different logic.
