### ISSUE TITLE
{ "not": {}} schema validation

### ISSUE THREAD

**Issue by mehdid93** [ajv-validator/ajv#1034]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.0

**Ajv options object**

```javascript
{ allErrors: true }
```

**JSON Schema**

```json
{"not": {}}
```

**Sample data**

```json
undefined
```

**Your code**

```javascript
var Ajv = require('ajv');
var ajv = new Ajv({ allErrors: true }); // options can be passed, e.g. {allErrors: true}
var validate = ajv.compile({ "not": {} });
var valid = validate(undefined);
if (!valid) console.log(validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
[ { keyword: 'not',
        dataPath: '',
        schemaPath: '#/not',
        params: {},
        message: 'should NOT be valid' } ]
```

**What results did you expect?**
I expect that it's considered as correct.

**Are you going to resolve the issue?**
Not for now.

**Comment by epoberezkin** [comment]
`{"not": {}}` should fail validation with any data, because `{}` should pass with any data, and `"not": <schema>` just negates validation against the `<schema>`.

Why do you expect it to pass?
