### ISSUE TITLE
[question] Can `parentSchema` has `$ref` inside?

### ISSUE THREAD

**Issue by alexander-akait** [ajv-validator/ajv#1038]
Sorry for removed issue template. See code but can't find nothing. We have legacy code with strange line(s):
```
while (schemaPart.$ref) {  
  // Logic
}
```

Where `schemaPart` is `parentSchema` from error. 

And my question it is possible has `$ref` in `parentSchema` of `error`? Thanks for any feedback.

**Comment by epoberezkin** [comment]
I don’t understand the question.

**Comment by alexander-akait** [comment]
@epoberezkin example we have error:
```
  { keyword: 'required',
      dataPath: '.refTest',
      schemaPath: '#/anyOf/1/required',
      params: { missingProperty: 'data' },
      message: 'should have required property \'data\'',
      schema: { data: { required: [Array] } },
      parentSchema: { properties: { data: [Object] }, required: [ 'data' ] },
      data: { action: 'create' },
      children: undefined }

```
For ajv, so can `parentSchema` has `$ref` property?

**Comment by epoberezkin** [comment]
parenSchema is the schema that contains the keyword that failed. $ref can be in it.

**Comment by alexander-akait** [comment]
@epoberezkin hm, can you provide simple example when `parentSchema` contains $ref, thanks

**Comment by epoberezkin** [comment]
Please explain what problem you are trying to solve with the code sample.

**Comment by epoberezkin** [comment]
I am going to close this issue - please resubmit using correct issue template with all the info.

**Comment by alexander-akait** [comment]
@epoberezkin it is not bug, we have big code base where have `while (schemaPart.$ref) {  } ` in some places and no tests for this case, i try to find example when `parentSchema` can has `$ref` in tests, but unfortunately did not find so i ask question then ask provide example when it is happens

**Comment by alexander-akait** [comment]
It is possible:
```
{ 
     keyword: 'required', // not sure it is can happens for `required`, just for example
     // Other properties
     parentSchema: { $ref: { ... } },
}
```
?
