### ISSUE TITLE
model docs generates based on json schema

### ISSUE THREAD

**Issue by AVVS** [ajv-validator/ajv#104]
I've googled and there are plenty modules around for that, but I was wondering if you have any specific recommendations towards them. I love how http://apidocjs.com/ works for docs, was wondering if there is something similar you may know. 

Thanks for all the responses in advance!

**Comment by epoberezkin** [comment]
If that's api docs both raml and swagger seem ok to generate them.

**Comment by epoberezkin** [comment]
Maybe you meant generating sample data based on the schema? [JSON-Schema faker](https://github.com/json-schema-faker/json-schema-faker) does it.

There is also [the list of JSON-schema related software](http://json-schema.org/implementations.html).
