### ISSUE TITLE
Custom keyword does not resolve $data reference when it's inside an object.

### ISSUE THREAD

**Issue by FaizuddinEverest** [ajv-validator/ajv#1048]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.0

**Ajv options object**

```javascript
{
	$data: true
}

```

**JSON Schema**

```json
{
   "type": "object",
   "properties": {
      "someone": {
         "type": "string"
      },
      "something": {
         "type": "string",
         "dependsOnData": {
            "some": "keyword",
            "related": "things",
            "depends": {
               "$data": "/someone"
            }
         }
      }
   }
}
```

**Sample data**

```json
{
	"someone": "someone here",
	"something": "something here"
}

```

**Your code**

```javascript
ajv.addKeyword("dependsOnData", {
	$data: true,
	validate: (keywordSchema, value) => {
		console.log(keywordSchema.depends); // --> { $data: "/someone" }
		return true;
	}
});
```

**Validation result, data AFTER validation, error messages**

`keywordSchema.depends` is a `$data` pointer and is never resolved.

**What results did you expect?**
Expected `keywordSchema.depends` to resolve to the value: `someone here`

In the docs, there's a mention:
> If the keyword has meta-schema it would be extended to allow $data and it will be used to validate the resolved value.

So I also tried the giving metaSchema to keyword definition:

```javascript
ajv.addKeyword("dependsOnData", {
	$data: true,
	metaSchema: {
		type: "object",
		properties: {
			some: {
				type: "string"
			},
			related: {
				type: "string"
			},
			depends: {
				type: "string"
			},
		}
	},
	validate: (keywordSchema, value) => {
		console.log(keywordSchema.depends); // --> { $data: "/someone" }
		return true;
	}
});
```
But then the error is thrown:
> keyword schema is invalid: data.depends should be string, data should NOT have additional properties, data should match some schema in anyOf

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
$data option in keyword definition only supports $data as the whole keyword value, not as some element inside keyword scheme. I.e. if you had dependsOnData: {$data: “...”} it would work.

**Comment by shareef-nirman** [comment]
Is this going to be fixed in the upcoming release?

**Comment by shareef-sulopa** [comment]
Is this going to be fixed in the upcoming release?

**Comment by epoberezkin** [comment]
It’s unlikely. If the object inside keyword is a schema, the keyword implementation would be likely to compile it with $data option inherited from the Ajv instance (or using the same Ajv instance). In this case data reference will be resolved at the validation time.

If the data object is some other structure it’s down to the keyword definition to decide whether to give data reference as something special or to just treat it as data.

It’s the same as with standard “const” keyword - if you pass an object as value, it would be incorrect to replace all internal parts that look like data references - it can lead to ambiguity. Following this logic, you may expect that if $data ref is present inside data that was used to replace $data ref it should be replaced recursively...

$data ref is defined in a simple way, meant to be used for simple substitutions of scalar values from data into schema. It is not a part of JSON Schema spec. I don’t have any plans to extend this functionality.

**Comment by epoberezkin** [comment]
It is no longer an issue with the new code generation if the $data is inside some internal schema using `applySubschema` function. If data reference is used in some internal object that is not a schema, this is easy to get it into a value with the same code that is use in KeywordCxt.

**Comment by pkyeck** [comment]
was searching for the same thing and stumbled upon this old issue. Seems like this should work now – could one of you post a working example so that people know how to achieve this? thanks a lot!

***update***
ok, I think if I understand that correctly, this should work, right:

```
{
   "type": "object",
   "properties": {
      "someone": {
         "type": "string"
      },
      "something": {
         "type": "string",
         "dependsOnData": {
           "$data": "/someone"
         }
      }
   }
}

// 
ajv.addKeyword("dependsOnData", {
  $data: true,
  validate: (keywordSchema, value) => {
    console.log(keywordSchema); // "someone here"
    console.log(value); // "something here"   
    return true;
  }
});
```
