### ISSUE TITLE
[RFE]: Option to point to the error with line/column number

### ISSUE THREAD

**Issue by quilicicf** [ajv-validator/ajv#105]
Hi, 

First of all, thanks for the great work. I'm using AJV alot and it helps me a great deal. 

I was wondering if you could add an option to point to an error via its line/column numbers. I'd like to embed AJV checks in Atom like I did for [RAML files](https://atom.io/packages/linter-raml). 

I've tried to find a way to convert a JSON pointer to a line number for a given JSON. Unfortunately, I couldn't find a library that does that and parsing isn't my cup of tea :(. I thought maybe that could be a quick win on your part ? 

That'd be awesome.

**Comment by epoberezkin** [comment]
I don't think it's possible as ajv accepts objects, not JSON strings... So there is no way to map to the line - the same object can be represented in many ways (line-breaks are optional and the order of properties is not really defined). So you have to parse the original JSON file to have mappings from properties to line/column. That's not too difficult, but it's out of scope I am afraid.

It deserves a separate npm package I  think.

**Comment by quilicicf** [comment]
OK, I knew it was a long shot. 
It definitely deserves an npm package indeed. 
I'll do that thanks.

**Comment by epoberezkin** [comment]
Please post the package here when it's available

**Comment by marjan-georgiev** [comment]
@quilicicf did you ever get to implement this? If so, any pointers would be super helpful.

**Comment by quilicicf** [comment]
@marjan-georgiev @epoberezkin 
I've written a node module indeed, [jp2p](https://npmjs.org/package/jp2p) (JSON pointer to position). 
And I completely forgot to post it here, my bad. 

Tell me if that helps!

**Comment by addexm** [comment]
@quilicicf Just used jp2p and it's awesome. Thanks!

**Comment by epoberezkin** [comment]
There is also [json-source-map](https://github.com/epoberezkin/json-source-map).
