### ISSUE TITLE
any way to skip validation for a property of an object

### ISSUE THREAD

**Issue by videni** [ajv-validator/ajv#1050]
```
 {
"title": "product",
"type": "object",
"properties": {
    "name": {
        "type": "string",
        "title": "Name",
        "propertyOrder": 1
    },
    "images": {
        "type": "array",
        "title": "acme.form.product.images",
        "items": {
            "type": "string",
            "title": "prototype",
            "format": "data-url"
        },
        "propertyOrder": 3
    }
}
```

I'd like to skip validation of images.items.

**Comment by m-mohr** [comment]
Remove it from the schema.

I don't think this is a bug report, but a question.

**Comment by videni** [comment]
@m-mohr , the `images.items` schema has to be there, because my UI is based on the schema.

**Comment by m-mohr** [comment]
Then clone it, remove images.items and pass the modified object to ajv. I don't think there is and should be a way to ignore parts of the schema in ajv.

**Comment by videni** [comment]
I see, thank you.

**Comment by videni** [comment]
@m-mohr ,  it seems custom keyword  is another solution, check [here](https://stackoverflow.com/questions/42819408/ajv-custom-keyword-validation)
