### ISSUE TITLE
removeKeyword required and loopRequired option

### ISSUE THREAD

**Issue by nullxone** [ajv-validator/ajv#1051]
**What results did you expect?**

Observed
removeKeyword('required') does not work without a change to loopRequired option
Expected
removeKeyword('required') should work without setting additional options

Observed
loopRequired option cannot be set to 0 (it is falsy in Ajv constructor), it can however be set to -1
Expected
can set loopRequired to 0

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
    "ajv": "^6.10.0",
logic is same in HEAD

**Code Sections Combined Heading**

```javascript

// FAIL
it("remove keyword required", async () => {
  const validator = new Ajv().removeKeyword("required");
  const valid = validator.validate(
    {
      type: "object",
      properties: {
        name: { type: "string" }
      },
      required: ["name"]
    },
    {}
  );
  expect(valid).toBe(true); // <-- false
  expect(validator.errors).toBeNull(); // <-- should have required property 'name'
});

// PASS
it("remove keyword required on ajv validator", async () => {
  const validator = new Ajv({
    loopRequired: -1  // <-------------- THIS WAS ADDED
  }).removeKeyword("required");
  const valid = validator.validate(
    {
      type: "object",
      properties: {
        name: { type: "string" }
      },
      required: ["name"]
    },
    {}
  );
  expect(valid).toBe(true);
  expect(validator.errors).toBeNull();
});

```

```javascript
// PATCH
// lib/ajv.js:66
  opts.loopRequired = opts.loopRequired || Infinity;
// can be instead?
  if (opts.loopRequired === undefined) opts.loopRequired = Infinity;
```

**Are you going to resolve the issue?**

I can submit above patch as a pull request if it is correct.

I am unsure of the fix for making it work without loopRequired option, and will not be able to make this change. (Perhaps reassign Ajv.prototype.removeKeyword to a function that wraps its current definition?)

I am open to update the documentation once the expected behaviour is confirmed.

**Comment by epoberezkin** [comment]
Many pre-defined keywords that are implemented together with others and they cannot be redefined, really. It's worth documenting better or maybe it's worth restricting what can be removed, but these keywords definitely cannot be redefined:

- type
- properties, patternProperties, additionalProperties, required
- [exclusive]minimum/maximum
- items, additionalItems

**Comment by nullxone** [comment]
Can we redefine the removeKeyword flag to account for these combinations?

In this case, it would something like

```javascript
Ajv.prototype.removeKeyword = function(keyword) {
  if (keyword == 'required') this._opts.loopRequired = -1;
  return customKeyword.remove.call(this, keyword);
};
```

**Comment by epoberezkin** [comment]
I don't think it will work in all cases. The implementation of "required" depends on the presence of "properties" keyword, which properties are there, etc. - it simply cannot be removed cleanly.

I am going to either document that it's impossible or to make it throw error in the next major version, either way it is not recommended to redefine standard keywords.

**Comment by jlgouwyapizr** [comment]
It could be great to remove the required keyword before validation/compilation. 
I would like to add .removeKeyword('required') to be able to reuse my schema. 

Now, i'm obliged to duplicate my schema with the same rules, but without the required keys. 
There is a risk of side effects. (If a rule would change, and a developer forget to change it in both schema).

Do you have any solution to avoid duplicate schemas just because of required. ?

**Comment by nullxone** [comment]
The most excellent objectionjs library, a query builder / orm also relies on ajv for validation.

https://github.com/Vincit/objection.js/blob/master/lib/model/AjvValidator.js#L134

In this case also, the library is forced to duplicate the schema. As a user of objectionjs, I use the above patch in my project.

Please could you reconsider the 'required' keyword as a special case different from the other pre-defined keywords you listed, considering this particular use case? I am also open to other suggestions.

Thanks.

**Comment by epoberezkin** [comment]
"required" implementation is decoupled from "properties", so should no longer be an issue in v7 (atm v7-alpha branch)
