### ISSUE TITLE
Error: unknown format ""  is used in schema at path 

### ISSUE THREAD

**Issue by El-Coder** [ajv-validator/ajv#1057]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.0.0.

**JSON Schema**

https://github.com/F5Networks/f5-appsvcs-extension/blob/master/schema/latest/as3-schema.json

**Sample data**

```json
{
    "foo": 12345,
    "bar": "a"
}
```

**Code**
```javascript

const schema = require('./schema.json')
const payload = require('./test.json')
var ajv = new Ajv();
var validate = ajv.compile(schema);

test(payload);

function test(data) {
  var valid = validate(data);
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}


```
**Validation result, data AFTER validation, error messages**

```

Error: unknown format "f5bigip" is used in schema at path "#/definitions/Basic_Persist/else/properties/bigip"

```

**What results did you expect?**
For it to give an error for the sample data

**Comment by epoberezkin** [comment]
Schema uses unknown formats, e.g. https://github.com/F5Networks/f5-appsvcs-extension/blob/master/schema/latest/as3-schema.json#L811, so it fails during the schema compilation.
See the docs for format-related option - you can choose to either define or ignore unknown format.

**Comment by El-Coder** [comment]
I'm having trouble getting it ignored is it like this ``var validate = ajv.compile(f5,{unknownFormats: false});``

**Comment by BenjaminDobler** [comment]
> I'm having trouble getting it ignored is it like this `var validate = ajv.compile(f5,{unknownFormats: false});`

It should be var validate = ajv.compile(f5,{unknownFormats: 'ignore'});
