### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by UltimateCoding9** [ajv-validator/ajv#1060]
Hi guys, 

I would like to use this library to validate json schema from a response. 
My response is a JSON-string, which will be stored in an attribute. 

Is there an example of your library, how I can validate the schema? 

I just would wish to see at least one small example. 

Thanks

**Comment by epoberezkin** [comment]
Please refer to the docs, existing online tutorials and StackOverflow for specific questions (with "json-schema" and/or "ajv" tag(s))
