### ISSUE TITLE
date-time full format's

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ajv-validator/ajv#1067]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest

**Sample data**

```javascript
const Ajv = require("ajv");


var schema = { format: 'date-time' };
var _Date = '2019-08-19 08:41:27';


var ajv2 = new Ajv({ format: 'full' });
console.log(ajv2.validate(schema, _Date));
```

**What results did you expect?**
true

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/63252625-2fcc5200-c281-11e9-80e6-b34e56093c7e.png)


Что вообще делает эта регулярка?
Для каких вхождений она нужна? Как должна выглядеть строка для верной валидации в таком случае?

Просто для MYSQL и других СУБД date-time задается именно в таком виде, а создавать несколько копий, которые не знаешь когда gc почистит - такое себе решение.
Конечно можно сделать кастомный keyword и просто отдавать строку в объект даты и проверять валидность, но тоже, создание доп экземпляра на каждый запрос.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/epoberezkin/ajv/blob/master/spec/tests/rules/format.json#L536 ?

**Comment by epoberezkin** [comment]
Ajv implements date-time format according to the spec, the above is indeed invalid.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, can you show an example of using standart format lib for creating custom date format via addFormat?

**Comment by afwn90cj93201nixr2e1re** [comment]
https://ajv.js.org/custom.html here only bout keywords.

**Comment by afwn90cj93201nixr2e1re** [comment]
```javascript
ajvO.addFormat('isMysqlDateTime', {
    validate: (dateString) => {
        return _isMysqlDateTime(dateString);
    }
});

var DATE = /^(\d\d\d\d)-(\d\d)-(\d\d)$/;
var DAYS = [0,31,28,31,30,31,30,31,31,30,31,30,31];
var TIME = /^(\d\d):(\d\d):(\d\d)(\.\d+)?(z|[+-]\d\d:\d\d)?$/i;
function _isLeapYear(year) {return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);}
  
  
function _date(str) {
    var matches = str.match(DATE);if (!matches) return false;var year = +matches[1];var month = +matches[2];var day = +matches[3];
    return month >= 1 && month <= 12 && day >= 1 &&day <= (month == 2 && _isLeapYear(year) ? 29 : DAYS[month]);
}


function _time(str, full) {
    var matches = str.match(TIME);if (!matches) return false;
    var hour = matches[1];var minute = matches[2];var second = matches[3];
    return ((hour <= 23 && minute <= 59 && second <= 59) || (hour == 23 && minute == 59 && second == 60));
}


function _isMysqlDate(str) {var dateTime = str.split(" ");return dateTime.length == 2 && _date(dateTime[0]) && _time(dateTime[1], true);}
```

Is this normal way for creating custom format checker? 

@epoberezkin
