### ISSUE TITLE
proposal: Show titles in error messages for subschema of allOf/anyOf/oneOf

### ISSUE THREAD

**Issue by mlilback** [ajv-validator/ajv#1073]
**What version of Ajv you are you using?**
6.10.2 (dependency of ajv-cli)

**What problem do you want to solve?**
Make it easier to debug allOf/anyOf/oneOf with lots of subschema.

**What do you think is the correct solution to problem?**
If a subschema includes a title propery, include that in the error message.

**Will you be able to implement it?**
No. Looked at code, but have no idea where this would be implemented.

**Comment by epoberezkin** [comment]
`title` of the schema can be accessed via `schema` property of the error already (it is added with `verbose` option), so you just need `validate.errors[i].schema.title`
