### ISSUE TITLE
Let string type take Date instance

### ISSUE THREAD

**Issue by ghost** [ajv-validator/ajv#1077]
**What version of Ajv you are you using?**

6.10.2

**What problem do you want to solve?**

When I use `{ type: 'string', format: 'date-time' }` to validate a `Date` instance it throws an error. There is no choice but convert all `Date` instances manually before validation with current implementation.

**What do you think is the correct solution to problem?**

Allow string type to take `Date` instances.

**Will you be able to implement it?**

Yes: https://github.com/Elethom/ajv/tree/enhancement/date-as-string

**Comment by epoberezkin** [comment]
Date instance is an object, it will pass if you allow "object" type. You could also use "instanceof" from ajv-keyword to validate the class.

**Comment by ghost** [comment]
@epoberezkin 

Thank you! Changing `string` to `object` works. But I think it would be better to mention this in readme.

> The following formats are implemented for string validation with "format" keyword:

^ This line made me think the `format` keyword only works for `string` type.

**Comment by epoberezkin** [comment]
Yes, format keyword only works for strings. In this case it is simply ignored and the schema allows any objects.

**Comment by ghost** [comment]
@epoberezkin 
Nah. It still went through the `format` validation.
```javascript
ajv.validate({type:'object',format:'date-time'}, new Date())
// true
ajv.validate({type:'object',format:'date-time'}, Date('abc'))
// false
```

**Comment by epoberezkin** [comment]
Date('abc') returns the current date as a string.

**Comment by ghost** [comment]
Oops, my bad. It indeed doesn't verify the format. So we have to use ajv-keyword after all.

**Comment by caub** [comment]
You should use `new Date(..).toJSON()` or `.toISOString()` to get a standard format

or something like `.toJSON().slice(0, 10)` to get YYYY-MM-DD format when needed
