### ISSUE TITLE
coerceTypes coerces nulls

### ISSUE THREAD

**Issue by vitalif** [ajv-validator/ajv#1078]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Latest

**Test case**

```js
const ajv = require('ajv');

const v = new ajv({ removeAdditional: true, coerceTypes: true });

v.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

v.addSchema({
    "$id": "test-schema.json",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "test::Test": {
            "type": "object",
            "properties": {
                "id": {"type": "number"},
                "name": {"type": "string"},
                "num": {"type": "number"}
            },
            "required": ["id"]
        }
    }
});

const t = v.compile({ '$ref': 'test-schema.json#/definitions/test::Test' });

const obj = { id: "1", name: null, num: null };

t(obj);

console.log(obj);
```

**Validation result, data AFTER validation, error messages**

```
{ id: 1, name: '', num: 0 }
```

**What results did you expect?**

```
{ id: 1 } or { id: 1, name: null, num: null }
```

**Are you going to resolve the issue?**

Maybe

**Comment by vitalif** [comment]
It happens even if I add `null` option explicitly, like `"name": {"anyOf": [{"type": "string"}, {"enum": [null]}]},`

**Comment by vitalif** [comment]
I think the behaviour should depend on whether the field is optional. For optional fields it's OK to just remove nulls, for required fields it's probably more correct to coerce them

**Comment by epoberezkin** [comment]
This works as documented - see the docs. To avoid coercing null, you should either add “null” type (e.g. `"type": ["string", "null"]`) or use nullable.

**Comment by vitalif** [comment]
> This works as documented - see the docs. To avoid coercing null, you should either add “null” type (e.g. `"type": ["string", "null"]`) or use nullable.

Sorry, but what's "nullable"?

Also another funny thing is that if I modify the above example and change
`"name": {"type": "string"},`
to
`"name": { "oneOf": [ {"type": "string"}, {"type": "null"} ] },`

The result becomes

`{ id: 1, name: null, num: null }`

Not just

`{ id: 1, name: null, num: 0 }`

:)

**Comment by vitalif** [comment]
Even more: if, in the same example, I change `obj` to:
`const obj = { id: "1", name: null, num: "2zzz" };`
It becomes
`{ id: 1, name: null, num: "2zzz" }`
After the validation. This is definitely a bug, even though not the originally described one :)

**Comment by vitalif** [comment]
I re-posted this as #1107
About the original problem: don't you think it would be convenient to automatically handle optional fields as nullable, at least under the condition of `coerceTypes` enabled? Having to add `oneOf:[{type: null}]` everywhere pollutes the schema...

**Comment by epoberezkin** [comment]
That would be against the spec.

**Comment by vitalif** [comment]
Is there a spec for type coercion at all?

**Comment by epoberezkin** [comment]
“to automatically handle optional fields as nullable” would be against the spec. Coercion is not part of the spec.

**Comment by vitalif** [comment]
Ok I mean automatically handle optional fields as nullable, that is make null equivalent to a missing field, when coerceTypes is enabled

**Comment by epoberezkin** [comment]
Allowing "null" and coercing are two separate things, they should not be mixed together I believe.
