### ISSUE TITLE
Not able to validate properties not equal to another using keyword 'not'

### ISSUE THREAD

**Issue by ToughRover** [ajv-validator/ajv#1079]
Ajv version used: 6.10.2, this issue exists in the latest version.

I want to validate a property value not equal to another property's value of an object. I defined following two schemas, none of them works for me.

**Ajv options object**
{allErrors: true, verbose: true}

**JSON Schema**

{
    "type": "object",
    "properties": {
        "foo": { "type": "string" },
        "bar": { "type": "string" },
    },
    "not": {
    "properties": {"bar": {"const": {"$data": "/foo"}}}
    }
}

{
    "type": "object",
    "properties": {
        "foo": { "type": "string" },
        "bar": { "type": "string", not: {"const": {"$data": "/foo"}}},
    }
}
**Sample data**

{"foo": "foo", "bar": "foo"}

**Validation result, data AFTER validation, error messages**

Valid

**What results did you expect?**
Invalid

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Please submit a full code sample - as in the issue template or into runkit.com

**Comment by epoberezkin** [comment]
Actually I can see that you don’t use $data option - $data in schema wont work without it.

**Comment by ToughRover** [comment]
@epoberezkin Thanks for your quick response, got it worked by adding $data option.

**Comment by yashwanthkalva** [comment]
Can you please provide a working example on how to use $data option ? I have a requirement to fail the validation if 2 properties in the json are same. It is for integer type. I already use json draft schema, how can use even data schema.
