### ISSUE TITLE
support relative URIs per RFC1808 and RFC3986

### ISSUE THREAD

**Issue by coderextreme** [ajv-validator/ajv#108]
for "format": "uri"

**Comment by coderextreme** [comment]
Need to support leading . and ..

**Comment by coderextreme** [comment]
Or at least leading ../../ and so on

**Comment by coderextreme** [comment]
[CC.txt](https://github.com/epoberezkin/ajv/files/108437/CC.txt)
[Schema.txt](https://github.com/epoberezkin/ajv/files/108436/Schema.txt)

**Comment by epoberezkin** [comment]
You can replace URI format with any regex using [addFormat](https://github.com/epoberezkin/ajv#api-addformat).

Or you can change it in [formats.js](https://github.com/epoberezkin/ajv/blob/master/lib/compile/formats.js).

**Comment by coderextreme** [comment]
I see it in format.js now.  Is there someplace I can get  a URI regexp for JSON schema?

John

**Comment by epoberezkin** [comment]
I don't think there is such thing... All the standard says it should comply with RFC3986.

**Comment by coderextreme** [comment]
Ah, addFormat replaces the format, it doesn’t add to it.  I will try again.

John

**Comment by coderextreme** [comment]
Okay, here’s what I did to get the files to validate.  No changes to Ajv (nearly the latest master).

To my script, I took URI out of acv/lib/compile/formats.js and put in my script, thus:

ajv.addFormat("uri", /^(?:[a-z][a-z0-9+-.]_:)?(?:\/?\/(?:(?:[a-z0-9-._~!$&'()_+,;=:]|%[0-9a-f]{2})_@)?(?:[(?:(?:(?:(?:[0-9a-f]{1,4}:){6}|::(?:[0-9a-f]{1,4}:){5}|(?:[0-9a-f]{1,4})?::(?:[0-9a-f]{1,4}:){4}|(?:(?:[0-9a-f]{1,4}:){0,1}[0-9a-f]{1,4})?::(?:[0-9a-f]{1,4}:){3}|(?:(?:[0-9a-f]{1,4}:){0,2}[0-9a-f]{1,4})?::(?:[0-9a-f]{1,4}:){2}|(?:(?:[0-9a-f]{1,4}:){0,3}[0-9a-f]{1,4})?::[0-9a-f]{1,4}:|(?:(?:[0-9a-f]{1,4}:){0,4}[0-9a-f]{1,4})?::)(?:[0-9a-f]{1,4}:[0-9a-f]{1,4}|(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?).){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?))|(?:(?:[0-9a-f]{1,4}:){0,5}[0-9a-f]{1,4})?::[0-9a-f]{1,4}|(?:(?:[0-9a-f]{1,4}:){0,6}[0-9a-f]{1,4})?::)|[Vv][0-9a-f]+.[a-z0-9-._~!$&'()_+,;=:]+)]|(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?).){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)|(?:[a-z0-9-._~!$&'()_+,;=]|%[0-9a-f]{2})_)(?::\d*)?(?:\/(?:[a-z0-9-._~!$&'()_+,;=:@]|%[0-9a-f]{2})_)_|\/(?:(?:[a-z0-9-._~!$&'()_+,;=:@]|%[0-9a-f]{2})+(?:\/(?:[a-z0-9-._~!$&'()_+,;=:@]|%[0-9a-f]{2})_)*)?|(?:[a-z0-9-._~!$&'()_+,;=:@]|%[0-9a-f]{2})+(?:\/(?:[a-z0-9-._~!$&'()_+,;=:@]|%[0-9a-f]{2})_)_)(?:\?(?:[a-z0-9-._~!$&'()_+,;=:@\/?]|%[0-9a-f]{2})_)?(?:#(?:[a-z0-9-._~!$&'()_+,;=:@\/?]|%[0-9a-f]{2})_)?$/i);

I did not make any changes to the regular expression.

So either you changed the URI code recently, or  I don’t quite know what is going on.  There are other URI format issues that I will look into now.

John

**Comment by coderextreme** [comment]
> On Jan 28, 2016, at 12:46 PM, John Carlson yottzumm@gmail.com wrote:
> There are other URI format issues that I will look into now.
> 
> So far, it appears to be problems on our end.

John

**Comment by epoberezkin** [comment]
Does it work for you?

**Comment by coderextreme** [comment]
I was able to make one more thing optional in the uri format, which allowed
#hidewarning to pass as a uri.  Thanks.  There is also data with two ## but
I think that's illegal and it's being flagged as illegal.  Thanks.

**Comment by epoberezkin** [comment]
Thank you.
