### ISSUE TITLE
pattern and patternProperties not working properly when using backslashes

### ISSUE THREAD

**Issue by carterw485** [ajv-validator/ajv#1085]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.4.0 - Not sure about using latest.

**JSON Schema**

```javascript
             {
                 "type": "object",
                 "properties": {
                   "foo": {
                     "type": "string",
                     "pattern": '^[^\\"]+$',
                   }
                 },
             };

```

**What results did you expect?**
`{ "foo": "an invalid\\ string" }` should error (It does not)

`{ "foo": "an invalid\" string" }` should error (It does)

**Comment by carterw485** [comment]
The same issue applies to using patternProperties with the same pattern.

**Comment by epoberezkin** [comment]
Ajv uses RegExp constructor to convert string to regular expression, so it’s not exactly “Ajv question” - more general “regular expression usage” question.

I believe you need double slash in the actual JavaScript regexp syntax which means you need 4 slashes in the string. Please check with regexp reference(s) if I am wrong.

**Comment by Qix-** [comment]
Sorry to gravedig but this came up in a somewhat unrelated search:

If you're within modern Javascript when you define your schemas, you can use `String.raw`:

```javascript
{
    pattern: String.raw`foo\\bar`
}
```

In older version of Javascript, you can even use RegExp literals directly using `.source`:

```javascript
{
    pattern: /foo\\bar/.source
}
```

Just a tip.
