### ISSUE TITLE
Logo usage

### ISSUE THREAD

**Issue by torifat** [ajv-validator/ajv#1086]
Hi

Sorry, I couldn't find any other way to communicate this so created the issue.

Is it ok to use `ajv` logo as part of my project's logo?

<img width="737" alt="Screen Shot 2019-09-15 at 6 35 02 pm" src="https://user-images.githubusercontent.com/208544/64918882-99d80880-d7e7-11e9-90b8-f9740c33429e.png">

**Comment by epoberezkin** [comment]
Sure, as long as it’s used to mean this Ajv :)

**Comment by torifat** [comment]
Thank you :)
