### ISSUE TITLE
Question: getting dereferenced source schemas?

### ISSUE THREAD

**Issue by jsumners** [ajv-validator/ajv#1087]
I have "Schema A" which defines some properties and "Schema B" which uses some `$ref`s to Schema A. I add these schemas to an AJV instance such that when I do `ajv.validate('schema-b', obj)` the references are resolved and the schema does the validation. That's all working just fine. Now I have a use case where I need to use the source Schema B in another AJV instance that _does not_ include Schema A. So if I do `otherAjv.addSchema( originalAjv.getSchema('schema-b').schema )` the references will not be resolvable.

So, my question is: can I force a compile of all schemas in `originalAjv` such that when I get a source schema out of it all of the references will be de-referenced?

**Comment by epoberezkin** [comment]
Compiling all schemas would not resolve the references, $ref just delegates the validation to another schema that is compiled on demand - the original schema remains unchanged. FAQ covers why it is the case.

So when you compile schema B, schema A gets also compiled become B uses it. But when you simply add schema object B to another instance, it cannot compile as it cannot find A anymore.

So you need to separately add all dependencies into the second instance.

Alternatively you could use asynchronous compilation, loading from one instance to another on demand (whatever the use case may be).
