### ISSUE TITLE
More user friendly ErrorObject TypeScript type

### ISSUE THREAD

**Issue by torifat** [ajv-validator/ajv#1090]
**What problem do you want to solve?**
In its current state [`ErrorObject`](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts#L291) is not very user friendly in certain scenarios. For example:
```ts
function useError(ajvError: ErrorObject) {
  switch(ajvError.keyword) {
    case 'enum': {
      // ErrorParameters
      ajvError.params
    }
  }
}
```
It would be really useful if we could get `EnumParams` here, instead of `ErrorParameters`. It's possible to use type-guards to achieve something similar but the code gets a bit messier.

**What do you think is the correct solution to problem?**
IMO it can be improved by using _discriminated unions_. If we do something like:
```ts
interface IErrorObject<T, U> {
  keyword: T,
  params: U,
  ...
}

type EnumErrorObject = IErrorObject<'enum', EnumParams>;
type RequiredErrorObject = IErrorObject<'required', RequiredParams>;
...

export type ErrorObject = EnumErrorObject | RequiredErrorObject | ...;
```
Then we will get  `EnumParams` inside the `enum` case.
```ts
function useError(ajvError: ErrorObject) {
  switch(ajvError.keyword) {
    case 'enum': {
      // EnumParams
      ajvError.params
    }
  }
}
```
**Will you be able to implement it?**
Yes

**Comment by torifat** [comment]
@epoberezkin any thoughts?

**Comment by epoberezkin** [comment]
@torifat Sorry for ignoring it... Looking at it now - it is probably the right approach.

Now that it is re-written in typescript - probably error type should be defined by each keyword locally (although given that it is returned via generated code it won't be connected to the actual code, just visually)

**Comment by epoberezkin** [comment]
The only problem I see with this approach is that ErrorObject should be an open union, to allow users extending it when they define custom keywords without modifying Ajv code base  - trying to figure out  how to do it in typescript... @torifat any suggestion would be fantastic.

**Comment by epoberezkin** [comment]
in v7-alpha
