### ISSUE TITLE
Возможность ссылаться ref'ом лишь на определенное поле

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ajv-validator/ajv#1094]
Сейчас допишу в комментарии.

**Comment by afwn90cj93201nixr2e1re** [comment]
Есть некое определение:
definitions:{
"maxLengthA":{type:'integer', minimum:1, maximum: 2}
}

Ссылаюсь на него из другой схемы, но при этом нужно чтобы minimum был перезаписан, а все остальные свойства остались прежними, чтобы два раза не менять в обоих схемах maximum, пытался так:

properties:
abc: {"$ref":"test#/definition/maxLengthA", minimum: 0} и пытался ссылаться на реф максимума через
abc: {minimum: 0, maximum: {"$ref":"test#/definition/maxLengthA/maximum"}

Тоже не вышло, так как должно быть числом и резолв не реализован. Так вот. Вопрос. Можно ли в будущем добавить резолв в определенные поля?


И как вообще работает
"$ref":"test#/definition/maxLengthA", exclusiveMinimum: 0, разве exclusiveMinimum не должен быть старше? Почему при данных abc: 0 - невалидное?

Как вообще решить задачу эту сохранив при этом 1 определение и со второй схемы ссылаться на него перезаписывая, резолвя лишь нужные поля? Да и вообще возможно ли это? Если нет, что посоветуешь?

**Comment by epoberezkin** [comment]
Ref is simply the instruction to validate the current data against another schema. It doesn’t disable/overwrite any of the keywords in the current or in the target schema
