### ISSUE TITLE
Missing `dataPathArray` property in `CompilationContext` interface

### ISSUE THREAD

**Issue by fabiospampinato** [ajv-validator/ajv#1096]
The exposed `CompilationContext` interface doesn't define the `dataPathArr` property, so TypeScript throws an error where it shouldn't.

**Comment by leonardovillela** [comment]
Can i take this issue?

**Comment by epoberezkin** [comment]
@leonardovillela I assume you want to make a PR? Always welcome :)

**Comment by leonardovillela** [comment]
i think this issue now can be closed.
