### ISSUE TITLE
Add support for filtering other than just validating

### ISSUE THREAD

**Issue by fabiospampinato** [ajv-validator/ajv#1097]
**What version of Ajv you are you using?** 

v6.10.2

**What problem do you want to solve?**

Sometimes, like when writing a library for managing settings, which is my use case right now, you don't actually need the entire user-provided settings object to match a schema, or otherwise you'll discard perfectly valid settings as soon as an error is found.

**What do you think is the correct solution to problem?**

The correct solution here is to _filter_, rather than validate, some data, basically this will exclude everything that doesn't match the schema and preserve everything that does.

**Will you be able to implement it?**

Probably, I've actually implemented this as a standalone library: [ajv-filter](https://github.com/fabiospampinato/ajv-filter), but it's kind of hacky, it uses undocumented variables, and I'd prefer a built-in solution written by people who actually know `ajv`.

**Comment by epoberezkin** [comment]
It's in the docs: https://github.com/epoberezkin/ajv#filtering-data

**Comment by fabiospampinato** [comment]
@epoberezkin If `removeAdditional` is supposed to do this then it's broken. Check out [this](https://github.com/fabiospampinato/ajv-filter/blob/master/test%2Fmocks.js) to see what the expected output should be (whether or not to filter out empty objects is a bit of a personal decision though).

**Comment by epoberezkin** [comment]
removeAdditional is defined differently - it doesn't mean it's broken :) It behaves as specified.

> The correct solution here is to filter, rather than validate, some data, basically this will exclude everything that doesn't match the schema and preserve everything that does.

This is not how JSON Schema is defined - you cannot determine, in general case, what part of the object matches the schema, and what part does not. The whole object is either valid against the schema or it is invalid. There is no general solution to derive the requirements for the object part based on the schema for the whole object (ajv-inspector did it for some subset of JSON Schemas, but it is not possible in general case). Also there can be multiple possible ways to remove parts of the object so it becomes valid against the schema, so within the scope of JSON Schema, without applying additional restriction on the rules to construct the reduced object, the problem may either have multiple solutions or no solutions, in general case.

The whole conversation is well beyond the scope of validation against JSON Schema and out of scope for Ajv. Once your library matures a bit (automatic build/tests/code coverage/better docs) it may be mentioned in the related packages section.

Btw, it's not clear whether you need to patch both the instance AND the schema, or you can do one of those things? Possibly, the whole module could be the function that patches the instance - as described in "plugins" section.

Closing the issue.

**Comment by fabiospampinato** [comment]
> removeAdditional is defined differently - it doesn't mean it's broken :) It behaves as specified.

Fair enough, I'm just saying that's not what I want to do.

> The whole object is either valid against the schema or it is invalid. 

I feel like this is true only if all properties are marked as required, can you provide a sample schema + data pair that won't work with my approach?

> without applying additional restriction on the rules to construct the reduced object, the problem may either have multiple solutions or no solutions, in general case.

I can't picture an example schema + data object combination that would lead to this sorts of undecidability, after all the little library I wrote is based on top of AJV, and AJV always says if it found a validation error or not, right?

Anyway I think this doesn't really matter for me as I control the schema.

> The whole conversation is well beyond the scope of validation against JSON Schema and out of scope for Ajv.

How would you approach my use case then? Just curious.

> Btw, it's not clear whether you need to patch both the instance AND the schema, or you can do one of those things? Possibly, the whole module could be the function that patches the instance - as described in "plugins" section.

Yeah I think you can patch just the instance, but if you extend the schema at any point in time and need to re-compile it then you'll be traversing the whole schema again for adding the `__ajv_filter__` keyword, with my current approach instead I can patch the partial schema to merge individually which is (slightly) faster.

**Comment by epoberezkin** [comment]
> I can't picture an example schema + data object combination that would lead to this sorts of undecidability, after all the little library I wrote is based on top of AJV, and AJV always says if it found a validation error or not, right?

It’s easy to construct the schema where validity of one property is dependent on the value/validity/presence of another property - with the keywords oneOf/if/dependencies etc.

**Comment by epoberezkin** [comment]
And the dependencies can be mutual.

**Comment by epoberezkin** [comment]
JSON Schema is the source of a lot of confusion - it is called “schema”, so it is a reasonable expectation that it defines the shape of the data. 

But in reality JSON Schema is simply a DSL for data validation - it defines a collection of rules that define the validity of the data as validity against all rules individually. So, in a way, it is not a “schema”.

Various attempts to compile JSON schema to typescript types had limited success, instead many people do the opposite - compile types to JSON Schema to do runtime validation.

The fact that properties are not required by default, additional properties are defined in a shallow way, “properties” do not require that the data is an object, etc. - all that makes JSON Schema very confusing to the new users. It all goes down to the simple fact that JSON Schema is NOT a schema that defines the shape of the data.

One may use a subset of the specification - that’s what Open API chose to do (sideset to be precise). Ajv implements some OpenAPI extensions. But even Open API schema allows dependencies between properties. But defining the extensions that only work for a subset of spec is out of scope of this library.

**Comment by fabiospampinato** [comment]
> It’s easy to construct the schema where validity of one property is dependent on the value/validity/presence of another property - with the keywords oneOf/if/dependencies etc.

> And the dependencies can be mutual.

So I guess worst case scenario both properties would just get filtered out, no? 🤔
