### ISSUE TITLE
FYI: using ajv in jsoneditor, works like a charm :)

### ISSUE THREAD

**Issue by josdejong** [ajv-validator/ajv#110]
Just wanted to let you know that I implemented support for JSON schema in [jsoneditor](https://github.com/josdejong/jsoneditor), powered by ajv. ajv really works like a charm, thanks!

You can try it out in http://jsoneditoronline.org (menu -> settings -> add schema).

**Comment by epoberezkin** [comment]
That's very cool, thank you very much for the compliment.

Next release (out tomorrow) implements asynchronous validation, but you have to execute some javascript to define custom asynchronous formats/keywords.

To my shame I spent several minutes figuring out how I do the validation :) Kept looking for a button, until I realised it's automatic :)

I wanted a tool like this for quite some time. That would be cool to set some options, e.g. show all errors (I guess that's the default for jsoneditor) etc.

**Comment by josdejong** [comment]
It's indeed automatically doing validation. That can get expensive for large documents, so being able to run asynchronously in a web worker would be awesome! Was on my wishlist for some future release, but it sounds like you're about to make this a no-brainer too :)

**Comment by epoberezkin** [comment]
You can run it in webworker indeed, whether it's synchronous or not. By asynchronous I meant schemas with custom formats/keywords that make requests to remote services: https://github.com/epoberezkin/ajv/tree/async#asynchronous-validation (in the branch now)

**Comment by josdejong** [comment]
ah, ok, I misunderstood that. Makes sense.

**Comment by epoberezkin** [comment]
Added [Packages using ajv](https://github.com/epoberezkin/ajv#some-packages-using-ajv) to readme :)
