### ISSUE TITLE
Missing `children` property in `ErrorObject` interface

### ISSUE THREAD

**Issue by alexander-akait** [ajv-validator/ajv#1100]
The `ErrorObject` doesn't contain `children` property. An error contains `children` when you use `oneOf` or `anyOf`

**Comment by afwn90cj93201nixr2e1re** [comment]
Пример? В объекте указывается при отсутствии совпадений каким может быть вообще. Не совсем понятно что именно не так.

**Comment by alexander-akait** [comment]
@afwn90cj93201nixr2e1re What? Please use English

**Comment by afwn90cj93201nixr2e1re** [comment]
;(
Russia, Kirov

show an example, now it's works as expected.

**Comment by alexander-akait** [comment]
Create schema with `oneOf` or `anyOf` keyword and look on error, you have `error.children` property, but it is not defined in typescript definitions https://github.com/epoberezkin/ajv/blob/120d746154f1200d2c2a8c6c643b35691d01ea64/lib/ajv.d.ts#L291

**Comment by afwn90cj93201nixr2e1re** [comment]
@epoberezkin

**Comment by alexander-akait** [comment]
I was wrong, no problem, issue was on mu side
