### ISSUE TITLE
Validator always returns true with Typescript 3.5.3

### ISSUE THREAD

**Issue by evilstiefel** [ajv-validator/ajv#1101]
**The version of Ajv you are using**
6.10.2
**The environment you have the problem with**
Angular v8.2.7 in the browser, using Typescript 3.5.3

**Your code (please make it as small as possible to reproduce the issue)**
```js
import * as protokollSchema from '../../ngrx/protokoll/schema.json';
import * as Ajv from 'ajv';
import * as draft07 from 'ajv/lib/refs/json-schema-draft-07.json';

const state = JSON.parse(localStorage.getItem('someLocalStorageEntry'));
const validator = new Ajv({ allErrors: true, coerceTypes: true })
	.addMetaSchema(draft07);
const validate = validator.compile(protokollSchema);
const result = validate(state);
```

I have to enable resolveJsonModule in tsconfig.json to successfully import the schemas. They are generated using draft07-spec. Whatever I do, the call to `validate` always returns true (I can even switch schemas to some totally different file and it won't error out). Doesn't matter if I add the meta schema or not (since the default should now be draft07).

I've been using this exact setup with Angular v7 before and had no such issues. Is there anything regarding typescript module resolution that would make it not work as expected?

**Comment by epoberezkin** [comment]
Did you try plain JavaScript with the same data and schema? Maybe make a sample in runkit.com to see it failing validation when you expect - to make sure that the issue is with typescript.

**Comment by evilstiefel** [comment]
It errors out even before the validation. When using `.addMetaSchema(draft07)`, it crashes because a schema with that name is already present.

When 'fixing' those issues, I can however run the validation successfuly and get the expected errors.

This works in plain js (the schema and state object are the exact same):
```js
const schema = require('./schema.json');
const ajv = require('ajv');

const state = { ...someVeryLongObject };
const validator = new ajv({ allErrors: true, coerceTypes: true });
const result = validator.validate(schema, state);

console.log({ result, errors: validator.errors });
```

**Comment by evilstiefel** [comment]
Okay, I fixed it by switching from
```js
import * as inventarSchema from '../../ngrx/inventar/schema.json';
import * as protokollSchema from '../../ngrx/protokoll/schema.json';
```
to
```js
const inventarSchema = require('../../ngrx/inventar/schema.json');
const protokollSchema = require('../../ngrx/protokoll/schema.json');
```
Now, everything works as expected. It seems that importing "json-modules" with webpack somehow mangles the schema into a javascript module that ajv cannot process correctly.

**Comment by epoberezkin** [comment]
> It errors out even before the validation. When using .addMetaSchema(draft07), it crashes because a schema with that name is already present.

draft-7 meta-schema is pre-added - it should not be added explicitly.

**Comment by evilstiefel** [comment]
Noted, just let me reiterate though that the problem was in the way Typescript/webpack imported the modules from the linked schema file (JSON). `resolveJsonModule` seems to create special modules out of those files, whereas a pure `require()` works fine.
