### ISSUE TITLE
Error: no schema with key or ref "https://json-schema.org/draft-07/schema#"

### ISSUE THREAD

**Issue by cjolif** [ajv-validator/ajv#1104]
I can't reference the meta schema with HTTPS.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.2 (latest)

**Ajv options object**

```javascript
const ajv = new Ajv({ allErrors: true });
```

**JSON Schema**

```json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object"
}
```

**Validation result, data AFTER validation, error messages**

```
Error: no schema with key or ref "https://json-schema.org/draft-07/schema#"
```

**What results did you expect?**

No error.

**Are you going to resolve the issue?**

Don't know yet.

**Comment by epoberezkin** [comment]
It is consistent with the spec - you should not be able to reference it this way. Schema ID does not mean the network location where the schema can be retrieved, and Ajv by itself does not perform any IO - it simply maps the URI to a schema object (see asynchronous compilation for how Ajv can be extended to do IO). So different protocol shouldn’t map to meta schema. If needed (not sure what’s the use case) it can be made available using addMetaSchema method, but I recommend simply using correct meta-schema ID with http as in https://github.com/json-schema-org/json-schema-spec/blob/draft-07/schema.json

The next version of the spec that was recently published switched to using https in the schema ID.

**Comment by LvChengbin** [comment]
@epoberezkin Thank you for your explanation, but I found the usage in the spec from https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4, and an error message was thrown while trying to compile the schema with Ajv.

![image](https://user-images.githubusercontent.com/963223/88514465-b99da700-d01c-11ea-8dc5-8d2121eec29f.png)

**Comment by epoberezkin** [comment]
If you put `http://json-schema.org/draft-07/schema# ` into $schema it should compile.

**Comment by ssbarnea** [comment]
IMHO, use of http:// instead of https:// is a very bad idea. Http should be allowed, if not even enforced.

**Comment by epoberezkin** [comment]
It’s just an identifier used in the spec, no actual
IO is performed here.
