### ISSUE TITLE
default keyword ignored inside of anyOf/oneOf

### ISSUE THREAD

**Issue by cyberwombat** [ajv-validator/ajv#1112]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.10.2

**Ajv options object**

```javascript

new Ajv({ useDefaults: true, removeAdditional: true })

```

**JSON Schema**

```json
{
  type: 'object',
  additionalProperties: {
    oneOf: [
      {
        type: 'object',
        properties: {
          type: {
            type: 'string',
            enum: ['text', 'number']
          },
          required: {
            type: 'string',
            default: 'foo'
          }
        },
        required: ['type']
      }
    ]
  }
}

```

**Sample data**

```json
{
  foo: {
    type: 'text'
  }
}

```

**Your code**

https://runkit.com/cyberwombat/5db4c3a02daa560013eadbcb
```javascript
var Ajv = require('ajv')

ajv = new Ajv({
    useDefaults: true
});

var schema = {
  type: 'object',
  additionalProperties: {
    oneOf: [
      {
        type: 'object',
        properties: {
          type: {
            type: 'string',
            enum: ['text', 'number']
          },
          required: {
            type: 'string',
            default: 'foo'
          }
        },
        required: ['type']
      }
    ]
  }
}

var data  ={
  foo: {
    type: 'text'
  }
}

var validate = ajv.compile(schema);

console.log(validate(data));
console.log(data);
```

**What results did you expect?**

If I change `oneOf` to `allOf` then it works as expected and my result is 
```
{foo: {type: 'text', required: 'foo' }}
```

However with `oneOf` or `anyOf` the default is disregarded. It does however make use of the sun schema since it is correctly validating the `type` field.

**Comment by epoberezkin** [comment]
Ignoring defaults inside anyOf and oneOf is a documented behaviour - it is not a bug and not something that is easy to improve - it’s covered in other issues.

**Comment by cyberwombat** [comment]
Ah apologies I didn't find the docs.  Any workaround you suggest?
