### ISSUE TITLE
String integer converts to null if type is ['integer', 'null']

### ISSUE THREAD

**Issue by ziimakc** [ajv-validator/ajv#1117]
**What version of Ajv are you using? **
6.10.2

If schema is set to ['integer', 'null']:
```
var schema =  {
    $id: 'posIntNull',
    type: ['integer', 'null'],
    minimum: 1
},
```
And you have bigint integer with type of string '2312312', then string integer converts into null, instead of integer 2312312.

If schema is set to 'integer', than it's works fine.

**Comment by epoberezkin** [comment]
please post the full code sample to investigate
