### ISSUE TITLE
Support OpenAPI discriminator keyword together with oneOf

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1119]
**What problem do you want to solve?**

- [ ] Optimise oneOf validation in case discriminator keyword is present by only validating the matching branch (currently all branches are validated)
- [ ] Apply defaults inside of oneOf in the presence of discriminator keyword (currently defaults inside oneOf are ignored)

The second can be addressed separately

**The solution requirements?**

- [ ] requires an option "discriminator" to enable "discriminator" keyword
- [ ] discriminator without oneOf should throw exception at schema compilation in strictKeywords mode, log warning and be ignored otherwise
- [ ] validate that each oneOf branch can only be valid for one discriminator value - TBC, possibly depending on strictKeywords or another option (i.e. that from validation result point of view discriminator remains no-op)
- [ ] apply defaults from the chosen oneOf branch
- [ ] tests:
  - [ ] that the current behaviour is not affected (i.e. all oneOf branches are validated in case discrimintator keyword is absent or present without an option/with option false and that the defaults in oneOf are ignored)
  - [ ] all the new behaviours

**Will you be able to implement it?**

Yes, with the right incentive :) PR is welcome.

**Comment by thetumper** [comment]
Even without discriminator, couldn't/shouldn't it be possible to disambiguate between various schemas in a oneOf, and validate the sub-elements of the matching schema?  By definition, the oneOf should not be valid if there is no differentiating property(ies) between the schemas.

**Comment by epoberezkin** [comment]
oneOf by definition should fail if the data instance is valid against none or more than one sub-schema. In general case, it is not possible to determine by schema analysis (as you suggest) so ajv has to validate against ALL subschemas when oneOf is used.

**Comment by thetumper** [comment]
Gotcha.  What I was getting at was that if the property names all line up with one of the schemas, but a value violates a regex pattern, for example, then I would hope to have an error generated indicating that.  This actually does seem to be happening.  There are also other errors for not matching any of the other schemas.  Which is also expected.

I think my confusion was about oneOf matching a schema based solely on which properties exist, vs. whether the values also meet the criteria defined for those properties.

**Comment by epoberezkin** [comment]
That is correct, but such conclusion is only possible for a subset of possible schemas, but not for all schemas. So this approach would only work sometimes, not always.

Think about discriminator keyword as an equivalent of a compiler instruction that while does not change the outcome (validation result), helps to optimise and short-circuit the generated lower level code (Javascript) without the need for the compiler (ajv) to do the analysis of code (schema) - that may be complex in some cases and impossible in general case.

Hope it makes sense.

**Comment by epoberezkin** [comment]
released in v8.0.0-beta.2

**Comment by epoberezkin** [comment]
v8 now released as the main version: https://ajv.js.org/v6-to-v8-migration.html

**Comment by Bessonov** [comment]
Thank you!
