### ISSUE TITLE
$ref: keywords ignored in schema at path

### ISSUE THREAD

**Issue by mqliutie** [ajv-validator/ajv#1121]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
@6.10.2

**Ajv options object**

```javascript
{
  allErrors: true
}

```

**JSON Schema**

```json
{
    "type": "object",
    "properties": {
        "code": {
            "type": "number"
        },
        "data": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "number"
                },
                "pcList": {
                    "type": "array",
                    "$ref": "#/definitions/urlList"
                },
                "h5List": {
                    "type": "array",
                    "$ref": "#/definitions/urlList"
                }
            }
        }
    },
    "definitions": {
        "urlList": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    },
                    "linkTypes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "number"
                                },
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

```

**Sample data**

```json
{
    "code": 200,
    "data": {
        "total": 101,
        "pcList": [
            {
                "id": 1,
                "name": "name",
                "linkTypes": [
                    {
                        "id": 1,
                        "name": "YTMS"
                    },
                    {
                        "id": 2,
                        "name": "itemDetail"
                    }
                ]
            }
        ],
        "h5List": [
            {
                "id": 2,
                "name": "h5Name",
                "linkTypes": [
                    {
                        "id": 1,
                        "name": "YTMS"
                    },
                    {
                        "id": 2,
                        "name": "itemDetail"
                    }
                ]
            }
        ]
    }
}

```

**Your code**

```javascript

const Ajv = require('ajv');
const ajv = new Ajv({ allErrors: true });
const validate = ajv.compile(schema);
const valid = validate(data);
if (!valid) {
    validate.errors.map(error => {
        console.log(JSON.stringify(error, null, 4));
    });
}
```

**Validation result, data AFTER validation, error messages**

```
$ref: keywords ignored in schema at path "#/properties/data/properties/pcList"

```

**What results did you expect?**

It should not be printed. 

In schema, If I delete the property `type` which value is `array` of `pcList` and `h5List`, the message will be gone, otherwise the message will be printed.

When I saw the message, I think the schema I have created is wrong

but the value of the `valid` is `true`! 

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
This is the correct behaviour.

Any keywords used in the same subschema as $ref are supposed to be ignored, as per draft-07 of JSON Schema. There is an option extendRefs that allows to change this behaviour to either throw exception or to use the keywords alongside $ref - see the docs.

Your schema is syntactically valid, but it is not correct - there are situations when you would expect the validation to fail but it would pass (if the data type is wrong - the validation will pass because type keywords are ignored).

**Comment by earonesty** [comment]
probably it should ignore comments though.   it raises this error if a '$comment' is set in the parent.

**Comment by Aidenir** [comment]
This might be an old issue, but could you please elaborate on your answer @epoberezkin, I don't really understand what the issue is (and I've run into it now as well, and this is the only thread on google which mentions this)?

**Comment by epoberezkin** [comment]
This default is now changed in v7. In v6 any keywords alongside $ref are ignored by default (as per spec) - can be changed with an option

**Comment by noitsnotit** [comment]
> This default is now changed in v7. In v6 any keywords alongside $ref are ignored by default (as per spec) - can be changed with an option

Hi @epoberezkin  - Sorry to revisit on this since this is the only thread I can find on Google. I am using a v6 and you mentioned this can be changed with an option, do you mind shedding some lights on this? which option I should play around? thank you vm!

**Comment by liyofx** [comment]
extendRefs
@nathantian 

> > This default is now changed in v7. In v6 any keywords alongside $ref are ignored by default (as per spec) - can be changed with an option
> 
> Hi @epoberezkin - Sorry to revisit on this since this is the only thread I can find on Google. I am using a v6 and you mentioned this can be changed with an option, do you mind shedding some lights on this? which option I should play around? thank you vm!
