### ISSUE TITLE
'$comment' option is not described in ajv.d.ts

### ISSUE THREAD

**Issue by ghost** [ajv-validator/ajv#1124]
ajv v.6.10.2

In Typescript, it is impossible to use '$comment' option because it is not defined in ajv.d.ts:

const ajv = new Ajv({ '$comment': someFunction });

Typescript 3.6.3 compiler error:

Argument of type '{'$comment': (value: any, path: any, schema: any) => void; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and ''$comment'' does not exist in type 'Options'.

**Comment by epoberezkin** [comment]
resolved in v7-alpha but feel free to make PR if you need it in v6.
