### ISSUE TITLE
Reference remote schema id

### ISSUE THREAD

**Issue by emanuelef** [ajv-validator/ajv#113]
Hi,
This is more a question than an issue, please discard it if not appropriate.
I'm trying to validate a schema with $ref and I get:
Error: can't resolve reference link.schema from id http://api.reference/user.schema#

user.schema:
"id": "http://api.reference/user.schema",
....
"self":{
    "$ref":"link.schema"
}

link.schema:
{
  "id": "http://api.reference/link.schema",
  "type": "object",
  "properties": {
    "href": {
      "type": "string",
    },
  },
}

Are references defined with id fetched remotely ? Is there a way to test them with local files without changing the "id" ?
I would expect an http request to http://api.reference/link.schema when validating user.schema.

Thanks for any help

**Comment by emanuelef** [comment]
never mind I read the documentation better:
full support of remote refs (remote schemas have to be added with addSchema or compiled to be available)

**Comment by epoberezkin** [comment]
If you need asynchronous loading there is the method `compileAsync` (you need to define the loading mechanism yourself, it can be HTTP or whatever - there is an example). But in case you have a limited number of schemas `addSchema` is better probably.

**Comment by emanuelef** [comment]
Thanks, I'll try that too.
Great tool!
