### ISSUE TITLE
Support Schema and Data Files in YAML

### ISSUE THREAD

**Issue by rawkode** [ajv-validator/ajv#1132]
It's becoming increasingly common to use YAML to define/describe JSON Schema documents and payloads, with Gatsby's markdown frontmatter being a good example.

It would be really nice if ajv supported loading schema and data files with a YAML flag to allow validation of these use-cases too.

**Comment by epoberezkin** [comment]
Parsing YAML into internal JS object representation is out of scope of ajv, there are several other libraries on npm that can be used for this purpose, making Ajv depend on them is unnecessary as 1) not all users need it and 2) it’s very easy to use in the application code before the schema is passed to Ajv.
