### ISSUE TITLE
Missing dataPath attribute for required field

### ISSUE THREAD

**Issue by northern** [ajv-validator/ajv#1133]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`^6.10.2` which at this time seems to be the latest version.

**Ajv options object**

`{ allErrors: true }`

**JSON Schema**

```javascript
    {
      required: ['country'],
      properties: {
        country: {
          type: 'string',
        },
      },
      additionalProperties: false,
    }

```

**Sample data**

An empty object is being validated.

```javascript
{}
```

**Your code**

Basic schema validation. No specific code required.

**Validation result, data AFTER validation, error messages**

```
validationError {
    keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'country' },
    message: "should have required property 'country'"
}
```

**What results did you expect?**

I expect that the `dataPath` attribute in the validationError object to have the value `country`.

**Are you going to resolve the issue?**

Unknown.

**Comment by epoberezkin** [comment]
This is expected behaviour. The dataPath is not missing - it points to the top level in the object, as missing required property is an object-level error, not a property-level error.

The missing property itself is available in params of the error.
