### ISSUE TITLE
Plans to support JSON Schema 2019-09 version?

### ISSUE THREAD

**Issue by chaeron** [ajv-validator/ajv#1138]
Any plans/timeline to support the latest JSON Schema 2019-09 version?

**Comment by epoberezkin** [comment]
What particular features you are interested in?

**Comment by chaeron** [comment]
All of them, but most specifically support for unevaluatedProperties.

**Comment by epoberezkin** [comment]
Understood. At the moment I don’t have any timeline to support this version of the specification

**Comment by jmjpro** [comment]
I recommend to close this issue in favor of https://github.com/epoberezkin/ajv/issues/1082

**Comment by epoberezkin** [comment]
agreed - it's a duplicate indeed.
