### ISSUE TITLE
Coerce types in mixed arrays using anyOf takes the first one

### ISSUE THREAD

**Issue by gotenxds** [ajv-validator/ajv#1140]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

latest

**Ajv options object**

```javascript
{coerceTypes: 'array'}
```

**JSON Schema**

```json
{
    "type" : "object",
    "properties" : {
      "data": { 
        "type": "array", 
        	"items": { "anyOf": [{ "type": "integer" }, { "type": "string" }] }
        
       }
     }
  };
```

Repro link : https://jsfiddle.net/wdjz0u34/

for array
`["1", 2, "3"]`
I expect to get back
`["1", 2, "3"]`
But I get
`[1, 2, 3]`
or
`["1", "2", "3"]`
depends on the order of anyOf

**Comment by epoberezkin** [comment]
Coercion only takes into account type keyword in the current schema object, not globally, so it is not a bug.

 You have to use "type" keywords with multiple types in array: `"type": ["integer", "string"]` - using anyOf to define multiple types is the the same from the validation point of view, but produces different results when coercing types.

Related comment is here: https://github.com/epoberezkin/ajv/issues/1107#issuecomment-545791224
