### ISSUE TITLE
Unable to set custom validation message ?

### ISSUE THREAD

**Issue by drj1990** [ajv-validator/ajv#1141]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I am using with Loopback 4 which internally uses AJV.

**Ajv options object**

```javascript


```

**JSON Schema**

```json
 @property({
    type: 'string',
    required: true,
    jsonSchema: {
      required: true,
      minLength: 4,
      message: { minLength: "Custom validation message" }
    }
  })
  email: string;

```

**Sample data**

```json


```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**
I am trying to send a custom message whenever validation fails instead of it's own message. But it does not return any custom message. It keeps on sending the same message.

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Please check the specification (or KEYWORDS.md) - you are not using JSON Schema correctly.
