### ISSUE TITLE
loadSchema is called 2 times for the same refferenced schema

### ISSUE THREAD

**Issue by dimovpetar** [ajv-validator/ajv#1145]
**UPDATED**:

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Version 6.10.2

**Ajv options object**
{
    loadSchema: loadExternalSchema
}

```javascript
function loadExternalSchema (uri) {
	return jQuery.ajax(uri)
	     .then(function (res) {
                        ...
			return res;
	    });
}

```

**JSON Schema**
````json
"allOf": [
	{ "$ref": "http://adaptivecards.io/schemas/adaptive-card.json#/definitions/AdaptiveCard" }
]
````

When trying to create Ajv instance, **loadSchema** function is being called 2 times for adaptive cards' schema.  I cannot afford to make 2 ajax calls for the same refferenced schema. How can I avoid that?

**Comment by epoberezkin** [comment]
Please post a simple code sample that shows the issue, ideally to runkit.com (IO call can be mocked in the same way as the tests do it).

**Comment by dimovpetar** [comment]
@epoberezkin 
I found hard times when trying to isolate it in JSFiddle. In the JSFIddle, however I have used 
````js
Promise.resolve({...}) 
````
instead of 
````js
return jQuery.ajax(...)
````
inside the "loadExternalSchema" function. In the end I discovered that the problem is coming from `jQuery`. If I wrap `jQuery.ajax` with `Promise`,  then there is only 1 request made. I consider this as resolved, hence you can close the issue.

**Comment by epoberezkin** [comment]
It looks like some race condition - it would be good to replicate it anywhere and fix...

Wrapping it in promise changes timing, so the race condition doesn't occur, but it still means there is some bug/logical error somewhere that makes it happen.

If you could share any size code sample reproducing it - it would be great.
