### ISSUE TITLE
validateSchema() {"type": "incorrectType"}, Returns Multiple Errors

### ISSUE THREAD

**Issue by KentonParton** [ajv-validator/ajv#1146]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.2

**Ajv options object**

```javascript
const ajv = new Ajv({
  validateSchema: "log",
  allErrors: true,
  ownProperties: true
});
```

**JSON Schema**

```json
{"type": "someIncorrectType"}

```
or 
```json
{"type": 1}

```

**Your code**

```javascript
var Ajv = require('ajv');

ajv = new Ajv({
    validateSchema: "log",
    allErrors: true,
    jsonPointers: false,
    ownProperties: true
});

var schema = {
    "type": "someIncorrectType"
};

var validate = ajv.validateSchema(schema);

console.log(ajv.errors);

```
RunKit: [https://runkit.com/kentonparton/ajv-issue](https://runkit.com/kentonparton/ajv-issue)

**Validation result, data AFTER validation, error messages**

```
[
  {
    keyword: 'enum',
    dataPath: '.type',
    schemaPath: '#/definitions/simpleTypes/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  },
  {
    keyword: 'type',
    dataPath: '.type',
    schemaPath: '#/properties/type/anyOf/1/type',
    params: { type: 'array' },
    message: 'should be array'
  },
  {
    keyword: 'anyOf',
    dataPath: '.type',
    schemaPath: '#/properties/type/anyOf',
    params: {},
    message: 'should match some schema in anyOf'
  }
]

```

**What results did you expect?**
In the case of {"type": "someIncorrectType"} I expected a single error displaying the allowed values, "string", "number" etc. <br/>In the case of {"type": 1}, I expected a single error displaying the allowed types, String or Array.

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
@KentonParton this is not a bug - Ajv reports errors in this way when schema uses anyOf keyword (in this case meta-schema).

Type keyword can be either a single type, or array of allowed types - so the first two errors are reported for each option and then for anyOf (see meta-schema for draft-7)
