### ISSUE TITLE
Suggested improvements to enum error message.

### ISSUE THREAD

**Issue by muffinresearch** [ajv-validator/ajv#115]
The error message for enum is currently: `should be equal to one of values`.

It would be nice to add the data of what the permitted values are (though I can imagine some people might not want that if the allowed values are large strings). Though maybe that could be an option?

Could it be changed to: `should be equal to one of the permitted values` or something similar?

**Comment by epoberezkin** [comment]
Thanks for the suggestion, your version is probably clearer. Maybe "allowed"... Enum values can be anything - not just large strings, but also objects and arrays. So including them into the string is not practical indeed. With `verbose` option you will get the reference to the `schema` of enum keyword, which is the array of allowed values. If your values are strings/numbers you can add them to the message.

**Comment by muffinresearch** [comment]
@epoberezkin thanks for the super fast patch!
