### ISSUE TITLE
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files) node_modules/conf/node_modules/ajv/lib/refs/data.json (2:13)

### ISSUE THREAD

**Issue by pjebs** [ajv-validator/ajv#1150]
I'm not directly using this package. Some dependency is.

Rollup is giving me this error and I've got no idea what to do:

Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/conf/node_modules/ajv/lib/refs/data.json (2:13)

**Comment by epoberezkin** [comment]
@pjebs This should be reported to the package that uses ajv, this not ajv bug. Please investigate the error stack or step through the code - you should be able to see which dependency is using ajv.
