### ISSUE TITLE
Enum object validation regression in 6.11.0

### ISSUE THREAD

**Issue by treardon17** [ajv-validator/ajv#1157]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Version: `6.11.0`

**Ajv options object**

```javascript
  const ajv = new Ajv({
    jsonPointers: true,
    allErrors: true,
    formats: {
      color: '^#[0-9a-fA-F]{3,6}$',
      slug: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
      extension: '^\\.[a-zA-Z0-9*]+$',
      alphanumeric: '^[a-zA-Z0-9_\\-]+$',
    },
  });
```

**JSON Schema**

```json
{
  "$id": "ajv-test",
  "type": "object",
  "properties": {
    "object_enum": {
      "title": "Validate Object in Enum",
      "type": "object",
      "enum": [
        { "text": "Test 1", "value": "test1" }
      ]
    }
  }
}
```

**Sample data**

```json
{
  "object_enum": {
    "text": "Test 1",
    "value": "test1"
  }
}
```

**Validation result, data AFTER validation, error messages**

```
  {
    "keyword": "enum",
    "dataPath": "/object_enum",
    "schemaPath": "#/properties/object_enum/enum",
    "params": {
      "allowedValues": [
        {
          "text": "Test 1",
          "value": "test1"
        }
      ]
    },
    "message": "should be equal to one of the allowed values"
  }
```

**What results did you expect?**

Version `6.10.2` had no validation errors with the same schema and sample data.

**Comment by epoberezkin** [comment]
Please submit the full code sample, ideally into runkit.com. It is possible that your data is somehow modified by some other code - try logging it just before the validation.

**Comment by treardon17** [comment]
Thanks for the quick response. After digging a little deeper, it looks like there was a change in how object equality is determined. I was passing a proxied object to the validator, and the validator's new way of handling object equality didn't mesh with the deeply proxied data. Sorry for the spam bug report.

**Comment by epoberezkin** [comment]
I see - so the changes in fast-deep-equal caused it - it makes sense. Thanks.

It’s a non-obvious question what’s the best approach here to be honest and whether different classes with the same properties should be considered equal from JSON Schema validation point of view.
