### ISSUE TITLE
✨ Modify data when using .addKeyword

### ISSUE THREAD

**Issue by segersniels** [ajv-validator/ajv#1160]
**What version of Ajv you are you using?**
`6.11.0`

**What problem do you want to solve?**
Would love to be able to mutate the data during validation when using custom keywords. Coming from a different library `isValid` I wanted to start using something more performant but quickly noticed that `ajv` doesn't support a specific type of functionality I was using with `isValid`.

I have a use case where I want to validate if a number is parseable to a BigNumber. If it isn't valid return `false` (so validation fails) but if it meets the condition return the modified data (passes validation). + Would also love to access the validated data after validating.

```js
ajv.addKeyword('graceful', {
  type: 'boolean',
  validate: (value: any, data: any) => {
    if (data === undefined) {
      return null;
    }

    if (value) {
      const number = new BigNumber(data);
      return number.isNaN() ? false : number;
    }

    return true;
  },
});

const schema = {
  type: 'object',
  properties: {
    amount: {
      type: 'number',
      graceful: true,
    },
  },
};

const data = {
  amount: "0.648416281616",
};

const validate = ajv.compile(schema);
const valid = validate(data);

console.log(typeof valid.data.amount === 'object');
// $ true

console.log(valid.data.amount);
// $ 0.648416281616

console.log(valid.data.amount.toExponential());
// $ '6.48416281616e-1'
```

**What do you think is the correct solution to problem?**
Not entirely sure since I haven't gone through the codebase myself but would love to pass a global option to `ajv` like `allowMutation: true` which then allows users to mutate the data in some way and returns the mutated data after validation.

**Will you be able to implement it?**
No. I might have missed something important in the documentation and this might be already possible though!

**Comment by segersniels** [comment]
An update on this issue. 

I've temporarily made it work by keeping a global reference to the original data and then mutating that data with the 4th parameter (the one that shows the keys) used in the `validate` function in `addKeyword`. 

For the mutation I'm currently using lodash's `_.set`. Still thinking if it would be possible with using data coercion or compile instead of validate 🤔

**Comment by epoberezkin** [comment]
It is supported - there is an option to allow mutation - please check the docs or mutating keywords in ajv-keywords.

**Comment by ghost** [comment]
@epoberezkin How can we do that? I haven't found any documentation about this...

**Comment by epoberezkin** [comment]
See api.md (addKeyword method), keywords.md and keyword implementations in ajv-keywords - there are some mutating keywords.
