### ISSUE TITLE
addSchema() produces error when {nullable: true}

### ISSUE THREAD

**Issue by maldimirov** [ajv-validator/ajv#1171]
Using `nullable: true` option when calling `addSchema()` an error is thrown:
```
Error: schema with key or id "" already exists
```

**What version of Ajv are you using?**
Ajv version: 6.12.0 (atm latest)

**Example code to reproduce**
```javascript
const Ajv = require('ajv');

const schema = {
    type: 'string',
    nullable: true,
};
const value1 = 'string';
const value2 = null;

const ajv = new Ajv({nullable: true});
ajv.addSchema(schema, '#');
const valid1 = ajv.validate('#', value1);
const valid2 = ajv.validate('#', value2);

console.log(valid1);
console.log(valid2);
```

**A bit more details**
On the example code when you remove the `nullable` option everything works as expected and the console prints `true` and `false`. Setting the option to either `nullable: true` or `nullable: false` produces the error.

**What results did you expect?**
Not throwing error and console logging `true` 2 times.

**Are you going to resolve the issue?**
No, but I will provide a workaround in the comments.

**Comment by maldimirov** [comment]
**Workaround**
A workaround is using `compile()`. E.g.
```javascript
const ajv = new Ajv({nullable: true});
const validate = ajv.compile(schema);
const valid1 = validate(value1);
const valid2 = validate(value2);
```

**So why use `nullable` and `addSchema()`?**
We are using `Ajv` to validate API responses against an Open Api Schema definition and it's really convenient to do something like:
```javascript
const ajv = new Ajv({nullable: true});
ajv.addSchema(apiDoc, '#')
  .validate('#/components/schemas/Details', response.body)
```
In this case the workaround we found is to "trick" `compile()` using a `$ref` like this:
```javascript
const validate = ajv.compile({
   $ref: '#/components/schemas/Details',
   ...schema,
});
validate(response.body);
```

**Comment by epoberezkin** [comment]
A better approach would be to give schema some ID and then using getSchema or validate:

```javascript
ajv.addSchema(schema, 'foo')
validate = ajv.getSchema('foo#/components/schemas/Details')
validate(data)

// or
ajv.validate('foo#/components/schemas/Details', data)
```

**Comment by maldimirov** [comment]
I thought a `#` is a valid schema name. Guess not :)
Your example works, but it would be good to have that documented somewhere. I could not find in the documentation any reference on what is a valid schema name, and that passing `#` will actually result in a schema without id.

**Comment by epoberezkin** [comment]
schema id is URI with JSON pointer in hash fragment, so “foo” and “foo#” are treated as the same schema id. That’s why # on its own is an empty URI.

I am still not sure why it works without nullable and doesn’t work with it...

**Comment by maldimirov** [comment]
Well, I leave it to you to decide whether this is a bug and the issue should remain open.

**Comment by epoberezkin** [comment]
Yes, I want to investigate it at some point. It is definitely worth clarifying schema ID in docs, in line with the specification, in this section: https://github.com/epoberezkin/ajv#ref

All the examples there have full URI as schema IDs.

**Comment by jasoniangreen** [comment]
This works in the latest version.
