### ISSUE TITLE
strictKeywords option complains about keywords defined in meta-schema

### ISSUE THREAD

**Issue by myelsukov** [ajv-validator/ajv#1177]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.12.0

**Ajv options object**

```javascript
{
  allErrors: true,
  jsonPointers: true,
  strictDefaults: true,
  strictKeywords: true,
  useDefaults: "empty"
}
```

**JSON Meta Schema**

```javascript
const dataMetaSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'https://json-schema.mycompany.com/2019-12/data-meta-schema#',
    title: 'Data Meta-Schema',
    definitions: {
        schemaArray: {
            allOf: [
                { $ref: 'http://json-schema.org/draft-07/schema#/definitions/schemaArray' },
                {
                    items: { $ref: '#' }
                }
            ]
        },
        propertyName: {
            type: 'string',
            pattern: '^[A-Za-z_][A-Za-z0-9_]*[a-zA-Z0-9]$',
            minLength: 1,
            maxLength: 63
        },
        aUri: {
            type: 'string',
            format: 'uri'
        },
        ontology: {
            type: 'array',
            items: { $ref: '#/definitions/aUri' },
            minItems: 1,
            uniqueItems: true
        }
    },
    allOf: [{ $ref: 'http://json-schema.org/draft-07/schema#' }],
    properties: {
        properties: {
            type: 'object',
            additionalProperties: { $ref: '#' },
            propertyNames: {
                $ref: '#/definitions/propertyName'
            }
        },
        patternProperties: {
          type: 'object',
          additionalProperties: { $ref: 'http://json-schema.org/draft-07/schema#' },
          propertyNames: {
            format: 'regex'
          },
          default: {}
      },
      additionalProperties: { $ref: 'http://json-schema.org/draft-07/schema#' },
      dependencies: {
            additionalProperties: {
                anyOf: [
                    { $ref: '#' },
                    { type: 'array' }
                ]
            }
        },
        items: {
            anyOf: [
                { $ref: '#' },
                { $ref: '#/definitions/schemaArray' }
            ],
            default: true
        },
        if: { $ref: '#' },
        then: { $ref: '#' },
        else: { $ref: '#' },
        allOf: { $ref: '#/definitions/schemaArray' },
        anyOf: { $ref: '#/definitions/schemaArray' },
        oneOf: { $ref: '#/definitions/schemaArray' },
        not: { $ref: '#' },
        contains: { $ref: '#' },
        ontology: {
            $ref: '#/definitions/ontology'
        }
    }
};

```

**JSON Schema**

```javascript
const dataSchema = {
    $schema: 'https://json-schema.mycompany.com/2019-12/data-meta-schema#',
    $id: 'https://json-schema.mycompany.com/2019-12/sample-data-schema#',
    description: 'Data schema for describing a place',
    type: 'object',
    additionalProperties: true,
    required: ['name', 'address'],
    ontology: ['https://schema.org/Place'],
    properties: {
        name: {
            description: 'Name',
            type: 'string'
        },
        address: {
            description: 'Postal address',
            ontology: ['https://schema.org/PostalAddress'],
            type: 'object',
            required: ['streetAddress', 'locality', 'region', 'countryName'],
            properties: {
                streetAddress: {
                    description: 'Street address. E.g. 3315 Scott Blvd., Suite 250',
                    ontology: ['https://schema.org/streetAddress'],
                    type: 'string'
                },
                locality: {
                    description: 'The locality in which the street address is, and which is in the region. For example, Santa Clara',
                    ontology: ['https://schema.org/addressLocality'],
                    type: 'string'
                },
                region: {
                    description: 'The region in which the locality is, and which is in the country. For example, California',
                    ontology: ['https://schema.org/addressRegion'],
                    type: 'string'
                },
                postalCode: {
                    description: 'The postal code. For example, 95054',
                    ontology: ['https://schema.org/postalCode'],
                    type: 'string'
                },
                countryName: {
                    description: 'The country. For example, USA',
                    ontology: ['https://schema.org/addressCountry'],
                    type: 'string'
                }
            }
        }
    }
};


```

**Sample data**

```javascript
const data = {
    name: "White House",
    address: {
        streetAddress: '1600 Pennsylvania Ave NW',
        locality: 'Washington',
        region: 'DC',
        postalCode: '20500',
        countryName: 'USA'
    }
};


```

**Your code**

```javascript
const Ajv = require('ajv');
const ajv = new Ajv({
  allErrors: true,
  jsonPointers: true,
  strictDefaults: true,
  strictKeywords: true,
  useDefaults: "empty"
});

ajv.addMetaSchema(dataMetaSchema);

const dataValidator = ajv.compile(dataSchema);

console.log(dataValidator(data));


```

**Validation result, data AFTER validation, error messages**

```
/home/myelsukov/node_modules/ajv/lib/ajv.js:351
    throw e;
    ^

Error: unknown keyword: ontology
    at generate_validate (/home/melsukov/node_modules/ajv/lib/dotjs/validate.js:12:18)
    at localCompile (/home/melsukov/node_modules/ajv/lib/compile/index.js:88:22)
    at Ajv.compile (/home/melsukov/node_modules/ajv/lib/compile/index.js:55:13)
    at Ajv._compile (/home/melsukov/node_modules/ajv/lib/ajv.js:348:27)
    at Ajv.compile (/home/melsukov/node_modules/ajv/lib/ajv.js:114:37)
    at Object.<anonymous> (/home/melsukov/workspace-move/Profile/sample/schemas.js:149:27)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)


```

**What results did you expect?**

I would not expect this error to be thrown.

Note: `ajv` properly validates the schema against meta-schema. If one would define `ontology` property of the schema at any level as integer, `ajv` would properly complain.

**Are you going to resolve the issue?**
I assume you are asking if I am going to submit a patch. Unfortunately, my answer is no :(

**Comment by epoberezkin** [comment]
strictKeywords will flag all keywords not defined in Ajv instance (with addKeyword method) - adding to meta-schema is not affecting it.

**Comment by myelsukov** [comment]
What could be an alternative to that?
The `strictKeywords` option helped me to find several typos. It would be extremely powerful feature for the meta-schemas. It seems that it would not be so hard to implement it. May be it could be an option that would treat keywords defined in meta-schemas as manually defined keywords? Logically it is the same thing, right? You already treat keywords defined in the parent meta-schema that way.

**Comment by epoberezkin** [comment]
You can define keywords as noop without passing definition to addKeyword. Meta-schema doesn’t define keywords validation semantics, it only defines their syntax (schema for their values).

**Comment by epoberezkin** [comment]
> You already treat keywords defined in the parent meta-schema that way.

Not sure what you mean here. Keywords defined in any meta-schema do not affect strictKeywords behaviour.

**Comment by myelsukov** [comment]
> You can define keywords as noop without passing definition to addKeyword

I definitely could do it. It's not desired though because I am building a self-serve data-driven system.

>>You already treat keywords defined in the parent meta-schema that way.

> Not sure what you mean here. Keywords defined in any meta-schema do not affect strictKeywords behaviour.

I mean that `strictKeywords` does not complain about keywords defined in the `http://json-schema.org/draft-07/schema#` but it complains about keywords (`ontology`) defined in my meta-schema `https://json-schema.mycompany.com/2019-12/data-meta-schema#`

I understand that currently `strictKeywords` is implemented the way you describe it (_Keywords defined in any meta-schema do not affect strictKeywords behaviour_.). I am just trying to make a point that keywords defined in the meta-schemas are keywords too :)

**Comment by myelsukov** [comment]
I want to reiterate my need. May be you could suggest some good solution for that.

I extended the standard meta-schema `http://json-schema.org/draft-07/schema#` by allowing to specify ontology for a schema (actually, the extension is much bigger than that). Ontology (in my world) is an array of URIs.

`ajv` deals with this extension just fine. If I would try to define a schema based on my extended meta-schema) and define the ontology not as an array of URIs, the `ajv` would properly fail to compile that schema. Yay! (great work, BTW :) ) 

I would like to prevent errors in the schema though. For example, if somebody would incorrectly type `ontology`. I tried to use `additionalProperties: false` in my meta-schema, but I couldn't make it work. So I tried to use `strictKeywords` option. Unfortunately, `ajv` fails to compile schemas that define ontology: `Error: unknown keyword: ontology` (see above).

How would you deal with this problem. I want to keep validation of the ontology schema properties (it works) but I would also would like to protect against human errors in defining schema.
