### ISSUE TITLE
Node 12 support (documentation issue)

### ISSUE THREAD

**Issue by ChristopherChudzicki** [ajv-validator/ajv#1181]
This is an issue with the documentation.

**The version of Ajv you are using**
`6.12.0`

**The environment you have the problem with**
Node `12.16.1`

**Issue**:
The README says

> supports [browsers](#using-in-browser) and Node.js 0.10-8.x

As far as I can tell, AJV works fine in Node 12. (All tests are passing.)

The documentation gives the impression that AJV will not work in node versions above 8. If AJV does support versions of node beyond 8, the documentation should be clarified.

Thanks for the great looking library!

**Comment by epoberezkin** [comment]
Yes - it can be updated to "supports Node.js 8.0 or later, it should work in 0.10+ though as it is only uses ES5".
