### ISSUE TITLE
Default coercing of number from `null` should be NaN

### ISSUE THREAD

**Issue by bluenote10** [ajv-validator/ajv#1182]
**What version of Ajv you are you using?**

6.12.0

**What problem do you want to solve?**

Roundtrip numbers.

**What do you think is the correct solution to the problem?**

It is clear that roundtripping IEEE 754 floats is unfortunately not possible via JSON, because of the omission of the IEEE 754 literals for NaN, and +/-Infinity.

However, coercing `null` to `0` is an extremely unfortunate decision that aggravates this limitation in JSON. In my opinion coercing to `NaN` is the only sensible value.

Consider a typical roundtrip of NaN/Infs:

![image](https://user-images.githubusercontent.com/3620703/78252098-9b9eba80-74f2-11ea-8f40-5c93b4067352.png)

Because JSON supports only a subset if IEEE 754, `JSON.stringify` follows the convention of mapping NaN/Infs to `null`. In total the current coercing default leads to the extremely dangerous transition from NaN/Infs to `0`, which opens the door to all kinds of bugs. (We immediately ran into them after starting using ajv.)

The coerced value should be `NaN` because:
- `null` isn't a number, and IEEE 754 has a value for representing the "not a number case".
- Correct roundtrip of `NaN`: Coercing to 0 not only introduces bugs, it also misses the opportunity that at least one of the three non-representable numbers have a correct roundtrip path.

On second thought, I'd actually consider this a bug.

Minimal example:

```js
var ajv = new Ajv({ coerceTypes: true })

var schema = {
  "type": "object",
  "properties": {
    "foo": { "type": "number" },
  },
  "required": [ "foo" ]
}
var validate = ajv.compile(schema)

var data = JSON.parse(JSON.stringify({ foo: NaN }))
console.log(data)
var valid = validate(data)
console.log(data)
// ouch: foo has become a 0
```

**Will you be able to implement it?**

Probably.

**Comment by epoberezkin** [comment]
This is not Ajv issue - it is about how parsing/strigifying works in javascript. After JSON.parse(JSON.stringify({ foo: NaN })) the value is null already, so you just need to either stop using coerceTypes option to avoid coercion or use `type: [number, null]` or `nullable: true` (with option).

If the suggestion is to change the behaviour of coerceType option, then it would be a breaking change and it is not consistent with how the option is defined.

**Comment by bluenote10** [comment]
> This is not Ajv issue - it is about how parsing/strigifying works in javascript.

That is not true. Historically the motivation for coercing `null` to `0` in Javascript was to simplify the usage of binary operators, without having to check individual expressions for `null`. It is a decision that has often been questioned, but at least it is a sensible convention in some situations e.g. in an expression like `a + b + c`.

Ajv is a validation library though. It is a different use case, most commonly related to the JSON stringify => parse roundtrip I tried to visualize above. If a type is marked as `number` coercing should do the most sensible thing for the purpose of validation, which is making an attempt to avoid information loss in the roundtrip. Blindly applying the Javascript coercing rule is inappropriate in the validation context, and leads to severe bugs.

> either stop using coerceTypes option to avoid coercion or use type: [number, null] or nullable: true (with option).

I'm aware of these alternatives, but they have implications that are almost unbearable:
- Avoiding coercing: If we assume that NaN/Infs can occur in every number, we are left with a situation where `null` have crept in where we actually expect a number. To avoid bugs they must be mapped to NaN manually: We have to recursively walk over the received data and replace all `null` value appearing in the context of a number with `NaN`. Basically, we have to re-validate a second time manually, which indicates that the validation library is missing something.
- Using coercing with `number | null`. This implies having to resolve basically **every** number in any public interface with `number | null`, because you can never be 100% certain that NaN cannot creep in. I gave it a try in the API I'm working on and the result is an extremely ugly mess (using TypeScript implies that the nullability has to be dealt with explicitly everywhere). In the end it again lead to basically doing a second manual validation pass that applies the sensible coercion of `null` => `NaN` everywhere. The code bloat is enormous.

**Comment by bluenote10** [comment]
@epoberezkin I tried to better explain why this is not a solution [here](https://github.com/cdimascio/express-openapi-validator/issues/268#issuecomment-608991496). In short: Clients in other eco systems (e.g. Python) already follow this kind of coercing rule, and the discrepancy between the JS coercion and coercion in other clients has very ugly implications.

Even if you think the coercing pattern "missing number is represented by `NaN`" that is the standard in the data science community is not the right default, it would be nice if we could at least think about configuration options that would make ajv fit well into the data science context.
