### ISSUE TITLE
How to verify if a value is of format and/or type double?

### ISSUE THREAD

**Issue by PeterR89** [ajv-validator/ajv#1183]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Ajv version: 07

**Issue description**

I am trying to validate that a value returned by the JSON response body is of type and format double, using ajv validation, however, I'm not being able to do it.

I've tried typing the following:

    - "type" : "double",
    - "format": "double"

    - "type": "Double",
    - "format": "Double"

    - "type":"number"
    - "format":"double"

  All the above attempts were unsuccessful as they all come with an error message saying either:

     -  Error: unknown type "double" is used in schema
or 

     -  Error: unknown format "double" is used in schema

**Comment by epoberezkin** [comment]
@PeterR89 please see JSON schema specification that Ajv implements. You should use type: number without format in this case
