### ISSUE TITLE
when judge error instanceof ValidationError, expect true, but is false

### ISSUE THREAD

**Issue by bluescurry** [ajv-validator/ajv#1184]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv 6.12.0

我正在使用 egg-ajv 做格式校验，使用的 typescript 而不是 javascript，在 controller 中编写以下代码：
```javascript
import { ValidationError } from 'ajv';

try {
      await this.ctx.validate('schema.pagination', this.ctx.request.query);
    } catch (error) {
      console.log('error ---> ', error instanceof ValidationError);
    }
```
console.log 期望得到 true ，但是缺得到了 false。使用 JavaScript 没问题，但是在 typescript 中判断的是错误的，请问这是什么问题呢？

**Comment by bluescurry** [comment]
> 我正在使用 egg-ajv 做格式校验，使用的 typescript 而不是 javascript，在 controller 中编写以下代码：

I'm using egg-ajv for format validation, typescript instead of javascript, and writing the following code in the controller.
console.log expects to get true, but gets false instead. JavaScript is fine, but typescript is wrong. What's the problem?

**Comment by epoberezkin** [comment]
@bluescurry sorry, I do not understand the issue. Please re-submit answering all the questions from the issue template, with the working code sample and expected/actual results.
