### ISSUE TITLE
Pass schema to processCode

### ISSUE THREAD

**Issue by awlayton** [ajv-validator/ajv#1194]
**What version of Ajv you are you using?**

6.12.0

**What problem do you want to solve?**

I am using the `processCode` option to instrument my generated code and it would be useful for my instrumentation to have access to information from my schemas.

**What do you think is the correct solution to problem?**

I think the schema should be passed as a second parameter to the `processCode` function.

**Will you be able to implement it?**

Yes.

**Comment by epoberezkin** [comment]
It's ok - please do PR.
You may look at ajv-istanbul btw, I was experimenting with the code coverage there long time ago.

**Comment by awlayton** [comment]
Yes I actually was looking at that, it was very useful as a starting point for me.
