### ISSUE TITLE
Can't validate draft-04 and draft-03 schema

### ISSUE THREAD

**Issue by nishat-sayyed** [ajv-validator/ajv#1199]
I want to validate with the following schema.

Draft-03 schema => https://adfapi.adftest.rightmove.com/schema/AddUpdatePropertyRequestSchema.json

Draft-04 schema => https://realtime-listings.webservices.zpg.co.uk/docs/v1.2/schemas/listing/update.json

How do I validate? code snippet for node?

**Comment by epoberezkin** [comment]
draft-03 is not supported. Draft-04 is supported - see the docs: https://github.com/epoberezkin/ajv#using-version-6

**Comment by epoberezkin** [comment]
closing it.
