### ISSUE TITLE
Signed up for a mailing list without permission

### ISSUE THREAD

**Issue by jsumners** [ajv-validator/ajv#1202]
Okay, I understand you want to get some monetary support for your work, but this is not cool. You should not be signing people up for mailing lists without their permission; regardless if they have the option to unsubscribe or not.

There _were_ only two reasons I had not contributed:

1. I'd rather contribute via a one time payment method that I already have instead of via GitHub's recurring payment scheme. For example, the "sponsor" button on https://github.com/tonsky/FiraCode has a PayPal option. He has received money from me.

2. You are stating that any money I contribute will go toward rewriting this module in TypeScript. I cannot support that. First, rewriting something this complex in a new language is likely to introduce at least as many problems as it "solves". Second, it will make it impossible for people like me to ever contribute any PR; you'll be limiting your potential contributor base to a subset of potential contributors, thereby shrinking the possible contributor pool.

Now there is a third:

3. The subject of this issue 😞

**Comment by rosnovsky** [comment]
I'm not sure where did they get my email. I can't remember using this package, and I'm quite sure I've never subscribed to any inbound emails.

**Comment by lovasoa** [comment]
Just wanted to leave my 👍 . It's really not cool to subscribe people to a mailing list without their permission, @epoberezkin !

**Comment by TimonLukas** [comment]
Agreed, this is not okay. My email is associated with my packages so people can reach me if a problem arises, not so I can be asked for donations.

**Comment by epoberezkin** [comment]
Sorry for any disruption.

I do think it's better for all Ajv users (and millions of web developers who depend on it indirectly) if its development continues than if it remains in its current state. Given Ajv scope and complexity, and also validation paradigm changes in JSON Schema specification draft 2019-09, it is not sustainable to do it without sponsorship, whether by its users or commercial companies.

I am going to close this issue - there won't be any further emails, but please fell free to post any comments.

I really appreciate the support from all people who made the contributions, expressed their support in emails and shared Ajv sponsorship request on social media.

Thank you for using Ajv.

**Comment by aendra-rininsland** [comment]
+1 about this not being very cool. Scraping peoples' emails from GitHub is quite likely also a *massive* GDPR violation, just saying...

**Comment by bajtos** [comment]
Hi @epoberezkin, while I was not happy about the email either, I'd like to offer you some (hopefully useful) information.

Funding OSS is hard, but there are exceptions. One of them is Babel, maybe you can reach out to Henry (https://www.henryzoo.com) and get some advice on how to make your fund raising more successful?

Another option is to join TideLift's maintainers program, that could earn you about $500/month according to https://tidelift.com/lifter/search/npm/ajv.

We are happy users of AJV in https://loopback.io, I wish you best of luck in figuring out how to fund the maintenance and further development of your great module.

**Comment by epoberezkin** [comment]
Thanks @bajtos - I will follow up on that!
