### ISSUE TITLE
Consistent quote style in error messages

### ISSUE THREAD

**Issue by satazor** [ajv-validator/ajv#1204]
**What version of Ajv you are you using?**

v.6.12.2

**What problem do you want to solve?**

Consistent quotes around error messages. Currently, some messages use `"` while others use `'`.

**What do you think is the correct solution to problem?**

Use just one quote style in error messages, maybe `"`?

**Will you be able to implement it?**

Yes.

**Comment by epoberezkin** [comment]
Do you mean in the source code or in the output?

**Comment by satazor** [comment]
I mean in the output.

**Comment by satazor** [comment]
@epoberezkin let me know the quote style you prefer in the output and I can tackle this.

**Comment by epoberezkin** [comment]
@satazor Majority use double quotes, so it should stay, but I was wondering if there was some logic behind using single quotes? Not that I remember...

Tbh, I am reluctant to change the messages without major version change, as people may rely on them - but happy to kick-off beta branch for the future v7.

Also, in the next major version the error generation should be revisited anyway, both to support 2019-09 (or the next) and to reduce the generated code size...

Thank you

**Comment by jasoniangreen** [comment]
Assuming this is either out of date, fixed or no longer relevant. Closing but happy to reopen if needed.
