### ISSUE TITLE
Facing Issue in Rich snippet Validator

### ISSUE THREAD

**Issue by 430470** [ajv-validator/ajv#1205]
url- https://instituterank.com/tics-ias-kolkata-reviews/

It is Taking two URLs in Article
one is General - https://instituterank.com/tics-ias-kolkata-reviews/#article
Other is with 404 error - https://instituterank.com/tics-ias-kolkata-reviews/post-1827
I don't know from where this 404 error url it is taking. for every new url it makes neew article id with same 404 page

![image](https://user-images.githubusercontent.com/22886237/81380242-2a24de00-9128-11ea-91d4-dfe905cc1d10.png)

**Comment by epoberezkin** [comment]
It is not a specific Ajv issue - it’s should be reported to the website in question.
