### ISSUE TITLE
Thank you for sponsoring Ajv development

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1211]
Huge thank you to everybody who sponsored Ajv development on [Github](https://github.com/sponsors/epoberezkin) or [OpenCollective](https://opencollective.com/ajv):

@stoplightio, @nzakas and @eslint team, [Lantagarnas AB (svb)](https://opencollective.com/lantagarnas-ab-svb), @Dashron @djragsdale @eljefedelrodeodeljefe @evisong @Format-X22 @gajus @Igloczek @lmammino @imbstack @jwadhwani @josdejong @kibertoad @kjirou @koddsson @labriola @laurisvan @leomp12 @lirantal  @maumercado @mmiller42 @Mirobit @MrSander @nickcmaynard @ottomata  @pankaz @pubkey and [RxDB](https://github.com/pubkey/rxdb) @Snailmus @stefanpl @TimothyBJacobs @TwoAbove @Yagich93 and everybody else who I may have missed or could not find the profile of.

I've also been excited to learn about some very interesting non-profit projects that use Ajv and received some overwhelming support via email of further Ajv development. Thank you all!

The next steps:
1. I am preparing applications to several open-source funds that I hope can provide enough resources to bring additional maintainers to the project and to ensure Ajv continuity - if you know of any fund to which Ajv may be suitable, I'd appreciate if you could share with me.
2. Ajv may be attractive for the sponsors who want to support open-source development and to have more visibility in JavaScript developers community - any introduction you could make would be fantastic.
3. I've moved Ajv and related repos to @ajv-validator org, and @jessedc also moved the [CLI for Ajv](https://github.com/ajv-validator/ajv-cli). Ajv can greatly benefit from having people other than me maintaining and developing it, so if you are interested to get involved - please reach out to me.

Thank you

**Comment by TwoAbove** [comment]
Great news!

**Comment by josdejong** [comment]
Sounds good, thanks for the update 👍 . I really hope this will work out.

**Comment by ottomata** [comment]
>  if you know of any fund to which Ajv may be suitable
Maybe https://fossresponders.com/

?

**Comment by epoberezkin** [comment]
> Maybe https://fossresponders.com/

thanks @ottomata: https://fossresponders.discourse.group/t/foss-crowdfunding-campaigns-that-need-your-help/61

**Comment by laurisvan** [comment]
@epoberezkin Did you consider submitting AJV to Linux Foundation? If moment.js can make it there, I don't see why AJV couldn't - the both are the de-facto standards on their respective parts in JS land.

**Comment by epoberezkin** [comment]
Thank you for the support and suggestions - see the latest update about MOSS grant and OpenJS Foundation: https://github.com/ajv-validator/ajv#mozilla-moss-grant-and-openjs-foundation.

Closing this ticket!

**Comment by josdejong** [comment]
🎉

**Comment by Snailmus** [comment]
So happy to hear that!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
