### ISSUE TITLE
how to compare string values of two fileds and also compare value within array

### ISSUE THREAD

**Issue by sarincm** [ajv-validator/ajv#1214]
Hi
I searched for the solution for many hrs..but cant find any..
i have my json data below
```
{
  Name: test,
  type: 'product',
  category: 'product',
breadcrumbs: [ 'abcd', 'xyz', 'asd', 'test' ]
}
```
i want to validate 2 condition
1)  the value of **type** and **category** must be same
2) the last value of **breadcrumbs** array and the **Name** field must be same

Is there any way i can validate these two conditions..
please help me

Thank you

**Comment by epoberezkin** [comment]
Not with the standard JSON schema or available extensions - best to keep it in application code or you can create your own custom keyword.
