### ISSUE TITLE
Ajv website and documentation

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1227]
The number of Ajv features makes the documentation difficult to navigate.

Ajv would massively benefit from having a better structured web-site and documentation, and more user-friendly examples of features.

This issue can be done by somebody who has:
- an experience of technical writing and structured presentation of the information
- an interest to learn JSON Schema and Ajv
- web-design/development experience

It would probably take a week of work and there can be a [disproportionally] small incentive from Ajv open-collective (it has to be agreed in advance) - the main benefit would be from the opportunity to learn Ajv, so it can be a good project for somebody learning JSON Schema etc.

Please reach out to me if you are interested.

**Comment by ojas1** [comment]
I'm interested.  I found out about JSON schema from ajv.  It is proving to be very useful in my work.

**Comment by epoberezkin** [comment]
@ojas1 I am not sure what the best approach is, but the requirements off top of my head:
- built from github .md files (same as the current web-site) - maintaining elsewhere would be difficult - the files can be restructured if needed, but I think it's best if the docs stay readable from github.
- docs hierarchy visible all the time on the left
- search

Possibly, readthedocs.io can be used - it seems close to what is needed, allows custom themes, domains, etc. Lots of projects docs seem to be hosted there, but I am not sure how easy it is to have the same docs readable both in github and there.

Open for the ideas :)

**Comment by ojas1** [comment]
I haven't used readthedocs but as you said it seems close.  It supports sphinx and mkdocs.  Are you using any of those currently?  If not we can start with building the existing docs in one of these.

**Comment by epoberezkin** [comment]
Currently site generation is quite ad-hoc, it happens on travis when .md (and some other) files change - see the scripts.

I don't mind moving it to another generator as long as it updates the links correctly across multiple pages, so on github they link to each other, and on say readthedocs they also link to each other.

Possibly some custom code should still exist to generate the required data/files for readthedocs from .md files on github.

**Comment by epoberezkin** [comment]
another option to consider: https://www.gitbook.com/

**Comment by domnantas** [comment]
[Vuepress](https://vuepress.vuejs.org/) might also be a good option. Supports md out of the box, generates static site (PWA + Offline support), though I'm not sure if this would work:
> it updates the links correctly across multiple pages, so on github they link to each other, and on say readthedocs they also link to each other.

**Comment by epoberezkin** [comment]
Great - thanks - didn’t see it before. It looks good - I will check it out.

**Comment by epoberezkin** [comment]
@domnantas thanks again for suggesting vuepress - the website is not finished, but uses vuepress aready - definitely easier to navigate: https://ajv.js.org

**Comment by epoberezkin** [comment]
new site is released

**Comment by domnantas** [comment]
It looks amazing!
