### ISSUE TITLE
Document creating pre-compiled schemas for CSP with ajv-cli

### ISSUE THREAD

**Issue by GrahamLea** [ajv-validator/ajv#1228]
**What problem do you want to solve?**
Easily understanding how to use ajv with a Content Security Policy that doesn't include `unsafe-eval`.

**What do you think is the correct solution to problem?**
The README.md should contain a section on how to use `ajv-cli` to create and use pre-compiled schemas. I found how to do this eventually, but only after lots of googling.

**Will you be able to implement it?**
Nope.

**Comment by epoberezkin** [comment]
There is the part about  ajv-cli: https://github.com/ajv-validator/ajv/blob/master/README.md#command-line-interface

The structure definitely needs to be improved - there is a recent ticket about it.

It would be great if you could suggest the amendments based on your experience.
