### ISSUE TITLE
removeAdditional not work with allOf

### ISSUE THREAD

**Issue by zzswang** [ajv-validator/ajv#1231]
want to accomplish following requirements with ajv:

- validate data with schema
- drop additional properties not provided in schema

but it not work with allOf

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`"ajv": "^6.12.2",`

**Ajv options object**

```javascript

const ajv = new Ajv({
  coerceTypes: "array",
  removeAdditional: "all", // strip any property not in openapi.yml
});
```

**JSON Schema**

```javascript
const schema = {
  allOf: [
    {
      type: "object",
      required: ["name"],
      properties: {
        name: { type: "string", description: "pet's name" },
        age: { type: "integer" },
      },
    },
    {
      type: "object",
      required: ["id"],
      properties: {
        id: { type: "string" },
        createAt: { type: "string", format: "time" },
      },
    },
  ],
};

```

**Sample data**

```javascript
const data = {
  name: "tom",
  age: 1,
  add: "2020-06-14T08:41:56.872Z",
  createdAt: "2020-06-14T08:41:56.872Z",
  id: "5ee5b284e6e6e1e49c916bf2",
};

```

**Your code**

```javascript
const validator = ajv.compile(schema);

if (!validator(data)) {
  console.log(validator.errors);
}

console.log(data);
/*
{}
*/

```

**Validation result, data AFTER validation, error messages**

```
[
  {
    keyword: 'required',
    dataPath: '',
    schemaPath: '#/allOf/1/required',
    params: { missingProperty: 'id' },
    message: "should have required property 'id'"
  }
]

```

**What results did you expect?**

`console.log(data)` expected:

```
const data = {
  name: "tom",
  age: 1,
  createdAt: "2020-06-14T08:41:56.872Z",
  id: "5ee5b284e6e6e1e49c916bf2",
};
```

but we got:

```
{}
```

**Comment by zzswang** [comment]
the json schema is translated from openapi.yml

```
    Pet:
      allOf:
        - $ref: "#/components/schemas/PetDoc"
        - $ref: "#/components/schemas/MongoDefault"
```

**Comment by zzswang** [comment]
For oneOf/anyOf  https://github.com/ajv-validator/ajv#filtering-data tells about why it not work.

Is it the same reason that allOf not work?

but I think we should drop properties after all subschema validated, follow the strategy to merge or pick up one schema.

**Comment by epoberezkin** [comment]
Correct - removeAdditional removes properties that would be "additional" in the same sense as used by "additionalProperties" keyword. One of the solutions is to replicate properties on the top level. It is also covered here: https://github.com/ajv-validator/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc

**Comment by zzswang** [comment]
After reading above, I really think it is the code limitation, not the right way. 

```
The reason for that is that additionalProperties keyword ignores properties inside oneOf keyword subschemas. That's not the limitation of Ajv or any other validator, that's how it must work according to the standard
```

The real reason is the remove code not respect `oneOf/allOf` keyword.

**Comment by zzswang** [comment]
Is there anyway to stop removeAdditional Properties for `oneOf/allOf` keyword?

Any suggestion for quick hack?

**Comment by epoberezkin** [comment]
The new version of the specification introduced the new keyword "unevaluatedProperties" that has the meaning that you are looking for, but the meaning of "additionalProperties" remained - "additional to the properties defined in a sibling `properties` and `patterProperties` keywords". It means that if there is no sibling `properties` keyword, then all properties are additional.

Once support for "unevaluatedProperties" is added, there may be an option to "removeUnevaluated", but the meaning of "removeAdditional" should stay aligned with the meaning of "additionalProperties" properties in the specification.

The current workaround is to use removeAdditional: true (rather than "all") with one of the following:
- use conditionals 
- use custom keyword select (see ajv-keywords)
- define all properties on the top level

In all cases you would need to add additionalProperties: false in the schema where you want additional properties removed, rather than using "all" setting - it is usually too eager for any compound schema.

**Comment by magiccaptain** [comment]
> The new version of the specification introduced the new keyword "unevaluatedProperties" that has the meaning that you are looking for, but the meaning of "additionalProperties" remained - "additional to the properties defined in a sibling `properties` and `patterProperties` keywords". It means that if there is no sibling `properties` keyword, then all properties are additional.
> 
> Once support for "unevaluatedProperties" is added, there may be an option to "removeUnevaluated", but the meaning of "removeAdditional" should stay aligned with the meaning of "additionalProperties" properties in the specification.
> 
> The current workaround is to use removeAdditional: true (rather than "all") with one of the following:
> 
> * use conditionals
> * use custom keyword select (see ajv-keywords)
> * define all properties on the top level
> 
> In all cases you would need to add additionalProperties: false in the schema where you want additional properties removed, rather than using "all" setting - it is usually too eager for any compound schema.

Thanks to your workaround, I solved this issue with override offOf and allOf keywords, here is the code:

## oneOf

Use [compile](https://ajv.js.org/custom.html#define-keyword-with-compilation-function) function to validate subschemas one by one, if it passed, then remove additional.

```js
import Ajv from "ajv";
import { merge, cloneDeep } from "lodash";

/**
 * override oneOf keyword to support removeAdditional option
 * @param {import('ajv').Ajv} ajv
 */
function oneOfRA(ajv) {
  ajv.removeKeyword("oneOf");
  ajv.addKeyword("oneOf", {
    compile: function(schemas) {
      return function(data) {
        for (const schema of schemas) {
          const validator = ajv.compile(schema);

          // use clone data to prevent data modify
          const testData = cloneDeep(data);
          const ret = validator(testData);

          if (ret) {
            // modify data for removeAddtional
            validator(data);
            return ret;
          }
        }
        return false;
      };
    },
    modifying: true,
    metaSchema: {
      type: "array",
      items: [{ type: "object" }],
    },
    errors: false,
  });
};

//uses

const ajv = new Ajv({
   coerceTypes: "array",
   removeAdditional: "all",
});

oneOfRA(ajv);

const schema = {
  type: "object",
  required: ["content"],
  properties: {
    content: {
      oneOf: [
        {
          type: "string",
          description: "string",
        },
        {
          type: "object",
          description: "Foo",
          required: ["foo"],
          properties: {
            foo: { type: "string" },
          },
        },
        {
          type: "object",
          description: "Bar",
          required: ["bar"],
          properties: {
            bar: { type: "string" },
          },
        },
      ],
    },
  },
};

const validator = ajv.compile(schema);

// string
const data = { content: "test" };
validator(data); // true
console.log(data); // { content: "test" }

// foo object
const data = { content: { foo: "foo", additional: "additional" } };
validator(data); // true
console.log(data); // { content: { foo: 'foo' } } removed additional

// bar object
const data = { content: { bar: "bar", additional: "additional" } };
validator(data); // true
console.log(data); // { content: { bar: 'bar' } } removed additional

// object with foo & bar
const data = {
   content: { foo: "foo", bar: "bar", additional: "additional" },
};
validator(data); // true
console.log(data); // { content: { foo: 'foo' } }, match foo schema, so bar is considered as additional

// object invalid
const data = {
  content: { additional: "additional" },
};
validator(data); // false
console.log(data); //  { content: { additional: 'additional' } }
console.log(validator.errors);
/**
[ { keyword: 'oneOf',
          dataPath: '.content',
          schemaPath: '#/properties/content/oneOf',
          params: { keyword: 'oneOf' },
          message: 'should pass "oneOf" keyword validation' } ]
*/

```

## allOf

Use [macro](https://ajv.js.org/custom.html#define-keyword-with-macro-function) function to return merged schema of subschemas，and it will auto remove additional.

```js
import Ajv from "ajv";
import { merge, cloneDeep } from "lodash";

/**
 * override allOf keywords support removeAdditional option
 * @param {import('ajv').Ajv} ajv
 */
function allOfRA(ajv) {
  ajv.removeKeyword("allOf");
  ajv.addKeyword("allOf", {
    macro: function(schema) {
      return merge({}, ...schema);
    },
    metaSchema: {
      type: "array",
      items: [{ type: "object" }],
    },
    errors: true,
  });
}

const ajv = new Ajv({
  coerceTypes: "array",
  removeAdditional: "all", // strip any property not in openapi.yml
});

// uses
allOfRA(ajv);

const schema = {
  type: "object",
  required: ["body"],
  properties: {
    body: {
      description: "request body",
      allOf: [
        {
          type: "object",
          properties: {
            name: { type: "string" },
            age: { type: "number" },
          },
        },
        {
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updatedAt: { type: "string", format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
      ],
    },
  },
};

const validator = ajv.compile(schema);

// tests

// valid
const data = {
  body: {
    id: "1",
    name: "tom",
    age: 1,
    createdAt: "2020-06-14T08:41:56.872Z",
    additional: "additional",
  },
};
validator(data); // true
console.log(data); // {"body":{"id":"1","name":"tom","age":1,"createdAt":"2020-06-14T08:41:56.872Z"}}, remove additional

// invalid
const data = {
  body: {
    name: "tom",
    age: 1,
    createdAt: "2020-06-14T08:41:56.872Z",
    additional: "additional",
  },
};

validator(data); // false
console.log(data); // {"body":{"name":"tom","age":1,"createdAt":"2020-06-14T08:41:56.872Z"}}, remove additional
console.log(validator.errors);
/**
  [ { keyword: 'required',
          dataPath: '.body',
          schemaPath: '#/properties/body/required',
          params: { missingProperty: 'id' },
          message: 'should have required property \'id\'' },
        { keyword: 'allOf',
          dataPath: '.body',
          schemaPath: '#/properties/body/allOf',
          params: { keyword: 'allOf' },
          message: 'should pass "allOf" keyword validation' } ]
*/

```
