### ISSUE TITLE
Switch cache implementation to Map or WeakMap / Performance Best Practices

### ISSUE THREAD

**Issue by Uzlopak** [ajv-validator/ajv#1232]
Hi, 

what I currently miss is a Performance Best Practice Page or Chapter in the Readme.MD. 

While I was benchmarking, I realized, that we are wasting cycles in serialization so when I dug deeper I realized that we stringify the Schema for getting a cache key. So instead I added to every schema a unique title attribute and set serialize to use the title attribute or still do the stringify on the object.

```
function getCacheKeyBySchema(schema: JSONSchema7): string {
	return schema.title || JSON.stringify(schema);
}
```

So we avoid a stringify on every validation. 

Are there any other performance improvements, that i am unaware of?

**Comment by epoberezkin** [comment]
I am thinking to switch the default cache implementation to Map (or WeakMap) where the schema itself is used as a key.

The main thing re performance is to compile once, not for every validation.

The best way to identify schemas is by $id attribute - and retrieve using getSchema method. Ajv checks $id uniqueness.

**Comment by mattcollier** [comment]
Meanwhile, here's a Map cache implementation:
```
const ajv = new Ajv({cache: new Cache(), serialize: false, verbose: true});
```

```
module.exports = class Cache {
  constructor() {
    this._cache = new Map();
  }

  put(key, value) {
    this._cache.set(key, value);
  }

  get(key) {
    return this._cache.get(key);
  }

  del(key) {
    this._cache.delete(key);
  }

  clear() {
    this._cache.clear();
  }
};

```

**Comment by epoberezkin** [comment]
Sorry, I should have closed it.

In v7 compiled schema cache is just a Map - the options `cache` and `serialize` are removed.
