### ISSUE TITLE
required field Question

### ISSUE THREAD

**Issue by Duncan00** [ajv-validator/ajv#124]
For e.g., we have a schema as following

``` javascript
{
    "type": "object",
    "properties": {
        "user": {
             "$ref": "/another_schema"
        }
    },
    "required": [
        "user"
    ]
}
```

When validate against following payloads,

```
{
    "user": {
        "user_id": null
        "user_name": null
    }
}
```

```
{
    "user": {}
}
```

It would throw required `user is a required property`
Is there any setting to let the payload pass as it is keeping the required structure `"user"`?

**Comment by epoberezkin** [comment]
what is "/another schema"? Can you post the whole code please?

**Comment by epoberezkin** [comment]
The problem is either in "/another_schema" or in the incorrect usage. See https://tonicdev.com/esp/56bdbb503689090c00a52ed8

**Comment by Duncan00** [comment]
Thanks, will check our codes.

**Comment by epoberezkin** [comment]
No problem, let me know if there are any problems
