### ISSUE TITLE
Unknown keys in object properties 

### ISSUE THREAD

**Issue by miladezzat** [ajv-validator/ajv#1245]
## I want to create schema for object with unknown keys

```javascript
    let obj = {
           "unknownkey1":{from: 'any', to:'any'},
           "unknownkey2":{from: 'any', to:'any'},
           "unknownkey3":{from: 'any', to:'any'},
    }
```

**Comment by miladezzat** [comment]
@epoberezkin

**Comment by epoberezkin** [comment]
Please review JSON schema docs - you can do it with additionalProperties, patternProperties or propertyNames - probably additionalProperties in your case.

**Comment by miladezzat** [comment]
THanks @epoberezkin
