### ISSUE TITLE
Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"

### ISSUE THREAD

**Issue by psnehanshu** [ajv-validator/ajv#1254]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.12.3 (Latest, installed today)

**Ajv options object**

```javascript
{}
```

**JSON Schema**

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "HeartbeatRequest",
    "type": "object",
    "properties": {},
    "additionalProperties": false
}
```

**Sample data**

```json
{}
```

**Your code**

```javascript
const Ajv = require('ajv');
const ajv = new Ajv(options);
const validate = ajv.compile(schema);
```

**Validation result, data AFTER validation, error messages**

```
Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
```

**What results did you expect?**

A validator function should be returned

**Are you going to resolve the issue?**

No

**Comment by psnehanshu** [comment]
Figured out this isn't a bug, it can solved by doing this

```javascript
var ajv = new Ajv({schemaId: 'id'});
// If you want to use both draft-04 and draft-06/07 schemas:
// var ajv = new Ajv({schemaId: 'auto'});
ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));
```

**Comment by spaceEcho** [comment]
Exactly I did have the same error and change the schema-json from draft-04 to draft-07
Error generated by AJV 
NOT SUPPORTED: option schemaId. JSON Schema draft-04 is not supported in Ajv v7.

**Comment by mrnexeon** [comment]
Changing the value of `$schema` property to `"http://json-schema.org/draft-07/schema#"` in JSON Schema file also helped me!

For reference, I have `"ajv": "^8.11.0"`
