### ISSUE TITLE
Coercing data types should support "date/number" to "string"

### ISSUE THREAD

**Issue by zzswang** [ajv-validator/ajv#1257]
Currently `Coercing data types` only supports "string" to "date/number/boolean"

Could we consider to also support the opposite way? I think it really important, or we need to write some ugly code to match the schema.

For example, following code should be excepted working.

```js
var ajv = new Ajv({ coerceTypes: true });
var schema = {
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "string" }
  },
  "required": [ "foo", "bar" ]
};

var data = { "foo": 1, "bar": false };

var validate = ajv.compile(schema);

console.log(validate(data)); // true
console.log(data); // { "foo": "1", "bar": "false" }
```

**Comment by epoberezkin** [comment]
> Currently Coercing data types only supports "string" to "date/number/boolean"

It is symmetric and depends on "type" keyword - it coerces both ways to the required type. "date" is not a type though. Could you show the problem on some example? The code you posted coerces data to string:

https://runkit.com/esp/5f2d170fe6b202001b9d3cdd

**Comment by epoberezkin** [comment]
also see https://github.com/ajv-validator/ajv/blob/master/COERCION.md

**Comment by zzswang** [comment]
@epoberezkin  Thank you. Sorry for not testing enough. Actually in my code, the problem is：

https://runkit.com/zzswang/ajv-1257

So I once thought that it doesn't support `coerces` type  `Date/Number` to string.  The number typing is working, I haven't tested enough with the given example, it just failed with the following Date field.

So `coerces` types not supporting Date? Because it is an Object？ 

The use-case for me is try to validate the model from database before sending back to frontend, make sure it feats the `openapi` response definition.  But it has Date fields. And the coerces will be failed.

I think Date type should be stringify. why not? And once more, it would be great that it could format the date as the given `format`. like:

```
"foo": { "type": "string", format: "date-time" },
```

**Comment by epoberezkin** [comment]
No problem.

The problem with extending coerceTypes is that Date is not something special, and it is not a type (from JS point of view), it is a class that you could have defined yourself. So giving it a special treatment does not seem right.

If you want some special behaviour on the Data class instance it can be done with a custom keyword.

Possibly, there is something that could be contributed to ajv-keywords, but it should not be core part of the library.

For example you could, in your case, have this schema:

```javascript
{
  "allOf": [
    {"instanceof": "Date"}, // custom keyword already defined in ajv-keyword
    {"toString": true} // new custom keyword you could define
  ]
}
```

A general problem with this approach is that it makes a declarative schema into an imperative code. So I would prefer keeping these transformations in application code.

**Comment by zzswang** [comment]
Currently I put the transforming in application code like `plain(xxx)`:

```js
  /**
   * Create a project
   *
   * @param {API.CreateProjectRequest} req createProject request
   * @returns {Promise<API.CreateProjectResponse>} The project created
   */
  async createProject(req) {
    debug("create project with body %o", req.body);
    const project = await Project.create(req.body);
    return { content: plain(project) };  // ajv will check the response
  }
```

since every model object will have some Date fields, so we need to add it everywhere.

We have our schemas auto  compiled from openapi.yaml. And use ajv to validate the api input and output. maybe we could try with custom keyword.

**Comment by epoberezkin** [comment]
yes - you can use custom keywords in yaml files

**Comment by gfortaine** [comment]
> https://runkit.com/zzswang/ajv-1257



> No problem.
> 
> The problem with extending coerceTypes is that Date is not something special, and it is not a type (from JS point of view), it is a class that you could have defined yourself. So giving it a special treatment does not seem right.
> 
> If you want some special behaviour on the Data class instance it can be done with a custom keyword.
> 
> Possibly, there is something that could be contributed to ajv-keywords, but it should not be core part of the library.
> 
> For example you could, in your case, have this schema:
> 
> ```js
> {
>   "allOf": [
>     {"instanceof": "Date"}, // custom keyword already defined in ajv-keyword
>     {"toString": true} // new custom keyword you could define
>   ]
> }
> ```
> 
> A general problem with this approach is that it makes a declarative schema into an imperative code. So I would prefer keeping these transformations in application code.

@zzswang @epoberezkin (note: `toString` seems to be a already defined : `Error: Keyword toString is already defined`) :

```javascript
const Ajv = require("ajv");
const addKeywords = require("ajv-keywords");

const ajv = new Ajv({ coerceTypes: "array" });
addKeywords(ajv);

ajv.addKeyword({
  keyword: "toJSON",
  schemaType: "boolean",
  code(cxt) {
    const { gen, data, schema, it } = cxt;

    function assignParentData({ gen, parentData, parentDataProperty }, expr) {
      gen.if(Ajv._`${parentData} !== undefined`, () => {
        gen.assign(Ajv._`${parentData}[${parentDataProperty}]`, expr);
      });
    }

    if (schema) {
      const coerced = gen.const("coerced", Ajv._`${data}?.toJSON?.()`);

      gen.if(Ajv._`${coerced} !== undefined`, () => {
        gen.assign(data, coerced);
        assignParentData(it, coerced);
      });
    }
  },
  error: {
    message: "field must be JSON serializable",
  },
});

const schema = {
  type: "object",
  properties: {
    foo: {
      allOf: [
        { instanceof: "Date" }, // custom keyword already defined in ajv-keyword
        { toJSON: true }, // new custom keyword you could define
      ],
    },
    bar: { type: "string" },
  },
  required: ["foo", "bar"],
};

const data = { foo: new Date(), bar: 1 };

const validate = ajv.compile(schema);

console.log(validate(data)); // true
console.log(data); // { "foo": "2020-08-07T20:19:35.000z", "bar": "1" }
