### ISSUE TITLE
Remove bundled builds from NPM package

### ISSUE THREAD

**Issue by kklash** [ajv-validator/ajv#1261]
**AJV version?**

6.12.3

**What problem do you want to solve?**

Minified & webpacked builds should not be included in the NPM package `ajv` - They are unnecessary and create major security risks for downstream package consumers.

For a more thorough explanation, please see [Sven Slootweg's gist on the subject](https://gist.github.com/joepie91/04cc8329df231ea3e262dffe3d41f848) 

**What do you think is the correct solution to problem?**

Remove the `dist` folder from the `files` array in `package.json`. 

The webpacked bundles are probably still useful to certain developers. To make them available, i suggest two alternatives:
1. Publish the webpacked builds on a CDN host like `cdnjs.com`
2. Upload the webpacked builds as resources on each new git tag. ([can be automated](https://github.com/actions/upload-release-asset))

**Will you be able to implement it?**

Yes, to different extents depending on which option is chosen.

**Comment by epoberezkin** [comment]
@kklash I agree.

I think this is a duplicate of #940. It got stuck with cdnjs approval to take bundles from ajv-dist (or maybe I dropped the ball).

Ajv v7 definitely won't have this bundle - it's in active development:  https://github.com/ajv-validator/ajv/pull/1260

Any help with #940 would be very much appreciated :)

Closing it here.
