### ISSUE TITLE
Improve schema validation

### ISSUE THREAD

**Issue by medikoo** [ajv-validator/ajv#1263]
**What version of Ajv you are you using?**

6.12.4

**What problem do you want to solve?**

When defining schema I've put `requiredProperties` instead of `required` on object definition, and it went unnoticed as valid schema

**What do you think is the correct solution to problem?**

As I have `validateSchema: true` I'd expect _unexpected property_ error to  be thrown

**Will you be able to implement it?**

No

**Comment by epoberezkin** [comment]
From JSON schema point of view the schema is valid - unknown keywords are allowed. There is an option strictKeywords that would fail compilation on unknown keywords - it will be default in v7.

**Comment by alexanderankin** [comment]
`it will be default in v7.` what version is ajv by default? thanks

**Comment by epoberezkin** [comment]
I meant the version of ajv - it is version 6.x now
