### ISSUE TITLE
Make the ValidateFunction interface "$async": true/false aware

### ISSUE THREAD

**Issue by villasv** [ajv-validator/ajv#1279]
**What version of Ajv you are you using?** 6.12.4

**What problem do you want to solve?**
`compile({ "$async": true/false/undefined, ... }).validate()` could generate a type signature more specific than  `boolean | PromiseLike<any>`, if some type inference is allowed.

**What do you think is the correct solution to problem?**
- Create specific types for async true or false schemas
- Overload `compile` and `compileAsync` with two different signatures, one for each schema type

**Will you be able to implement it?**
Maybe? I'm going to try a bit, maybe draft a pull request.

**Comment by epoberezkin** [comment]
@villasv thanks for the suggestion. Given the coming release of v7 beta by the end of September, it may be better to consider including there. The first release should be on npm even sooner than that.

It's re-written in typescript, so maintaining types is easier there - it would benefit from some review though.

Also, having more precise types for the end users has risks of breaking existing code compilation, so it better if it is a major version change.

There is another popular request #736 with 55 upvotes that seems related - I think they should be considered together.

**Comment by villasv** [comment]
Oops, did not realize there as a rewrite coming. Will start experimenting with it and see how it goes.

Looks like this one is a requirement for #736, but I don't think they should be considered together. I am not particularly interested in using validation as a type guard, I just want to have my compiler stop complaining that validation results might be a promise (but never will because I don't use async validation).

Should I experiment with and target branch v7-alpha then?

**Comment by villasv** [comment]
Pull request updated. Had to compromise a little bit, though.

**Comment by epoberezkin** [comment]
> Should I experiment with and target branch v7-alpha then?

It would be great. The current latest is v7-alpha-resolve, just pushed the last commit - please have a look.

**Comment by villasv** [comment]
Ah, I was targeting v7-alpha. I changed the PR to track v7-alpha-resolve but now there are a few conflicts. Will resolve them tomorrow.

**Comment by epoberezkin** [comment]
No problem, I can resolve later.  v7-alpha-resolve can be changing too quickly
