### ISSUE TITLE
uri format fails for valid URI

### ISSUE THREAD

**Issue by j3e8** [ajv-validator/ajv#1281]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
version 6.12.0

**Ajv options object**
None

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "link_image_url": {
      "type": ["string", "null"],
      "format": "uri"
    }
  }
}
```

**Sample data**

Example URI: `https://d1v1e13ebw3o15.cloudfront.net/data/53673/pool_and_spa_master/..jpg`
Yes it's an unconventional URI, but it _is_ valid.

**Validation result, data AFTER validation, error messages**
Error message: should match format "uri"

**What results did you expect?**
I expect the aforementioned example URI to validate properly

**Comment by epoberezkin** [comment]
@j3e8 I cannot reproduce without your code and data sample - this string validates as valid against "uri" format:

https://runkit.com/esp/5f5e08e690ddf900137605c0

**Comment by ragaeeb** [comment]
@epoberezkin I can reproduce it too. It seems like you tested with `v6.12`, try with the latest `v7` beta. It seems to work fine on `v6.12.5`

**Comment by epoberezkin** [comment]
The ticket mentions v6.12. v7-beta needs adding formats from ajv-formats, are they added?

**Comment by ragaeeb** [comment]
Thanks, works fine when i added the `ajv-formats`.

**Comment by epoberezkin** [comment]
thank you!
