### ISSUE TITLE
if/then/else keywords not working as expected

### ISSUE THREAD

**Issue by carlos-moreira** [ajv-validator/ajv#1282]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.12.2

**Ajv options object**

```javascript
{ allErrors: true, removeAdditional: 'all', nullable: true }

```

**JSON Schema**

```json
{
    "title": "sendSms",
    "type": "object",
    "properties": {
        "clientIds": {
            "type": "array"
        },
        "smsId": {
            "type": "integer"
        },
        "content": {
            "type": "string"
        },
        "subject": {
            "type": "string"
        },
        "marketing": {
            "type": "boolean"
        }
    },
    "required": ["clientIds", "marketing"],
    "anyOf": [
        { "required": ["smsId"] },
        {
            "if": { "properties": { "marketing": { "const": true } } },
            "then": { "required": ["content", "subject"] },
            "else": { "required": ["content"] }
        }
    ]
}

```

**Sample data**

```json
{
  "clientIds": [
    12345
  ],
  "content": "test content",
  "marketing": false
}

```

**Validation result, data AFTER validation, error messages**

```
{
    "status": "failed",
    "errors": [
        {
            "path": "",
            "message": "should have required property 'smsId'",
            "params": {
                "missingProperty": "smsId"
            }
        },
        {
            "path": "",
            "message": "should have required property 'content'",
            "params": {
                "missingProperty": "content"
            }
        },
        {
            "path": "",
            "message": "should match \"else\" schema",
            "params": {
                "failingKeyword": "else"
            }
        },
        {
            "path": "",
            "message": "should match some schema in anyOf",
            "params": {}
        }
    ]
}

```

**What results did you expect?**

This data should be validated with success, as following this example: https://www.jsonschemavalidator.net/s/eydcldvd
I have no idea why jsonschemavalidator validates it but AJV doesn't.

**Comment by epoberezkin** [comment]
Before looking deeper, the issue is probably that removeAdditional: 'all' removes all properties not used in "if" schema - try switching to use removeAdditional: true. See the docs on how this option works

**Comment by epoberezkin** [comment]
Given how often this issue comes up, I think it may be best to deprecate `removeAdditional: all` in v7-alpha/beta release and to remove completely in v7/8. It is best to put additionalProperties: false into the schema and use removeAdditional: true instead.

The alternative change would be to differentiate to which schemas it applies, but while it MAY be a bit less confusing and as deterministic as it is now, it would be as unexpected for the end users - why additional properties are removed in some cases and not the others. So best if it is controlled explicitly with additionalProperties: false keyword on per-schema basis.

**Comment by carlos-moreira** [comment]
> Before looking deeper, the issue is probably that removeAdditional: 'all' removes all properties not used in "if" schema - try switching to use removeAdditional: true. See the docs on how this option works

Yes, it worked now, thank you.



> Given how often this issue comes up, I think it may be best to deprecate `removeAdditional: all` in v7-alpha/beta release and to remove completely in v7/8. It is best to put additionalProperties: false into the schema and use removeAdditional: true instead.
> 
> The alternative change would be to differentiate to which schemas it applies, but while it MAY be a bit less confusing and as deterministic as it is now, it would be as unexpected for the end users - why additional properties are removed in some cases and not the others. So best if it is controlled explicitly with additionalProperties: false keyword on per-schema basis.

I had no idea of the interaction between 'removeAdditional' AJV option and the if/then/else keywords.

**Comment by epoberezkin** [comment]
> I had no idea of the interaction between 'removeAdditional' AJV option and the if/then/else keywords.

It's not specific to If/then/else... Wherever there are properties, everything else becomes additional and with removeAdditional: all it is removed.

**Comment by carlos-moreira** [comment]
> > I had no idea of the interaction between 'removeAdditional' AJV option and the if/then/else keywords.
> 
> It's not specific to If/then/else... Wherever there are properties, everything else becomes additional and with removeAdditional: all it is removed.

Got it. Does the 'additionalProperties' property, when not used, has any default value? I mean, by default additionalProperties = false, right?

**Comment by epoberezkin** [comment]
Default value is true, that is to allow additional properties

**Comment by carlos-moreira** [comment]
> Default value is true, that is to allow additional properties

Ok, thank you for answering my doubts.
