### ISSUE TITLE
Error: unknown format "date-time" ignored in schema at path "#/properties/timestamp"

### ISSUE THREAD

**Issue by Gazoh** [ajv-validator/ajv#1295]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.12.5

**JSON Schema**

```
https://uniswap.org/tokenlist.schema.json

```

**Sample data**

```
"timestamp": "2018-11-13T20:20:39+00:00"

```

**Your code**

```
export const generateMyTokenList = (tokenList: TokenList) => {
    // Your list
    const myList = tokenList;
    // Creating a new Ajv object
    const validator = new Ajv();
    // Validating if the scheme is a valid scheme
    const validateScheme = validator.validateSchema(schema);
    console.log('validateScheme', validateScheme)
    // If the validateScheme returns true it is a valid scheme than validate my list
    if(validateScheme) {
        let validatedList = validator.validate(schema, myList); 
        console.log('validatedList', validatedList)
    }
}

```

**Validation result, data AFTER validation, error messages**

```
Error: unknown format "date-time" ignored in schema at path "#/properties/timestamp"

```

**What results did you expect?**
I am having this trouble also for 'URI'. My question is why is AJV ignoring all the formats? i am using

**Comment by epoberezkin** [comment]
Are you sure you are using version 6 and not 7? Try validating just date time string against schema {format: “date-time”}.

A side comment - you don’t need to validate the schema in a separate call to validateSchema, it happens by default.

**Comment by epoberezkin** [comment]
This is a working example: https://runkit.com/esp/5f6224b4256fbf001beeee11

Please try to reproduce your issue in runkit (you can clone this sample), but please keep the total code size under 20 lines - I cannot review or debug your application schema.

**Comment by BlackGlory** [comment]
I get this error on 7.0.0-beta.3: `Unknown format "uri" ignored in schema`.
Should I go back to Ajv v6?

**Comment by epoberezkin** [comment]
No, the formats are now in ajv-formats package - see its docs how to add them.

**Comment by mariano-aguero** [comment]
> **What version of Ajv are you using? Does the issue happen if you use the latest version?**
> 6.12.5
> 
> **JSON Schema**
> 
> ```
> https://uniswap.org/tokenlist.schema.json
> ```
> 
> **Sample data**
> 
> ```
> "timestamp": "2018-11-13T20:20:39+00:00"
> ```
> 
> **Your code**
> 
> ```
> export const generateMyTokenList = (tokenList: TokenList) => {
>     // Your list
>     const myList = tokenList;
>     // Creating a new Ajv object
>     const validator = new Ajv();
>     // Validating if the scheme is a valid scheme
>     const validateScheme = validator.validateSchema(schema);
>     console.log('validateScheme', validateScheme)
>     // If the validateScheme returns true it is a valid scheme than validate my list
>     if(validateScheme) {
>         let validatedList = validator.validate(schema, myList); 
>         console.log('validatedList', validatedList)
>     }
> }
> ```
> 
> **Validation result, data AFTER validation, error messages**
> 
> ```
> Error: unknown format "date-time" ignored in schema at path "#/properties/timestamp"
> ```
> 
> **What results did you expect?**
> I am having this trouble also for 'URI'. My question is why is AJV ignoring all the formats? i am using

I'm using the version 6.12.6 and seems to works fine, I'm trying to do exactly the same as you

**Comment by epoberezkin** [comment]
I am not sure what the issue is. If the issue is with Ajv v6.* please submit the full code sample to reproduce, what’s above is not enough to understand the problem. If it’s with Ajv v7.* it is because formats are now in a separate package ajv-formats that has to be added if you use them - seem release notes for v7.

**Comment by mattiekat** [comment]
I can confirm running into this error when migrating from v6 to v7 and it was solved by following the instructions here: https://ajv.js.org/docs/validation.html#formats

**Comment by sakthiiv** [comment]
Thanks for the awesome library.

For those who are using NodeJs require, the below snippet works

```javascript
	const AJV = require('ajv').default;
	const addFormats = require('ajv-formats').default;

  	const ajv = new AJV();
  	addFormats(ajv);
```

**Comment by epoberezkin** [comment]
closing here - thank you for the examples

**Comment by felixfbecker** [comment]
@epoberezkin is there a way to use string formats with `TypeCompiler` too? Especially since that's what [`@fastify/type-provider-typebox`](https://github.com/fastify/fastify-type-provider-typebox/blob/d7171a31170682925d7b4f734ae0b809e4baac08/index.ts#L24) uses – currently it throws at runtime when `format` is used somewhere, even though on the type level it's accepted and enumerates all the formats from JSONSchema.
