### ISSUE TITLE
Unable to enforce schema validity using `meta` schema option...

### ISSUE THREAD

**Issue by busticated** [ajv-validator/ajv#1305]
hi there :wave:

thanks to all the maintainers for the hard work you do :pray::heart:

i'm trying to figure out how to safely validate user-provided schemas. to that end, i thought i might be able to set a single, custom meta-schema which removes support for dangerous / unwanted formats and keywords. unfortunately, i can't seem to figure out how to get things working as i expect - specifically, `ajv.addSchema()` doesn't ever seem to throw.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`v6.12.6`, yes

**Ajv options object**

```javascript
{
	meta: false,
	allErrors: true,
	useDefaults: true,
	extendRefs: 'fail',
	missingRefs: 'fail',
	strictNumbers: true,
	strictDefaults: true,
	strictKeywords: true,
	unknownFormats: true,
	validateSchema: true,
	removeAdditional: 'all'
}

```

**JSON Meta Schema**

```json
{
    "$schema": "http://my.custom/schema#",
    "$id": "http://my.custom/schema#",
    "properties": {
        "myKeyword": { "type": "boolean" }
    }
}
```

**JSON Schema**

```json
{
    "properties": {
        "myUnknownKeyword": { "type": "boolean" }
    }
}
```

**Your code**

```javascript
const ajv = new AJV({
    meta: false,
    allErrors: true,
    useDefaults: true,
    extendRefs: 'fail',
    missingRefs: 'fail',
    strictNumbers: true,
    strictDefaults: true,
    strictKeywords: true,
    unknownFormats: true,
    validateSchema: true,
    removeAdditional: 'all',
});

ajv.addMetaSchema({
    $schema: 'http://my.custom/schema#',
    $id: 'http://my.custom/schema#',
    properties: {
        myKeyword: { type: 'boolean' }
    }
});

try {
    // i'd expect this to be considered `invalid` given my meta-schema
    ajv.addSchema({
        properties: {
            myUnknownKeyword: { type: 'boolean' }
        }
    });
} catch (error){
    console.log('this should throw');
    console.error(error);
}
```

**What results did you expect?**
i expected the call to `ajv.addSchema()` to throw an error due to my schema being invalid as defined by my meta-schema

**What were the actual results**
no error is thrown, message - `meta-schema not available` - is logged to the console

**Comment by epoberezkin** [comment]
meta:false is not needed, what seems to be messing is $schema in your schema - it should be the ID of the meta-schema that you want it to be validated against.

**Comment by busticated** [comment]
@epoberezkin thanks for chiming in 🙏 

>what seems to be messing is $schema in your schema - it should be the ID of the meta-schema

hm. sorry, i don't follow. looking at the canonical `json-schema-draft-07.json` ([source](https://github.com/ajv-validator/ajv/blob/11e997bda2f3eecb445c1e5a07d96ef7e81c5f5d/lib/refs/json-schema-draft-07.json#L2-L3)), i see that it defines both `$schema` and `$id`. 

so for any schema i want to validate against my meta-schema, do i set `$schema` to reference the `$id` of the meta-schema? the opposite - setting `$id` in my schema to the `$schema` value from my meta-schema causes `Error: no schema with key or ref http://my.custom/schema`

**Comment by epoberezkin** [comment]
$id identifies the schema itself, $schema - the meta-schema it should be validates against. In case of meta-schema they can be the same when it is its own meta-schema

**Comment by busticated** [comment]
💡💡💡 ah, ok of course 🤦‍♂️ 

with that in place and adding a top-level `additionalProperties: false` key to my meta-schema, i'm seeing validation failures as expected - thanks very much :pray::+1:
