### ISSUE TITLE
missing local definitions

### ISSUE THREAD

**Issue by mokone91** [ajv-validator/ajv#1307]
Hi!

im trying to reuse  same schemas for api validation and swagger doc, but i have faced with issue that references working differently in both environments.

in my case i have added definition for semver property type:
`
{
  "$id": "semver",
  "type": "string",
  "minLength": 5,
  "maxLength": 14,
  "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
}
`
so if i want to use it with AJV i can add it as scheme before compile and use $ref in main scheme:

`
 "version": {
      "$ref": "semver"
    },
`

but swagger cant use ref by $id... so in that case i can include it to definitions section like:

`
const definitions = require('./src/schemas/definitions');

module.exports = {
  openapi: '3.0.1',
  info: {
    title: pkg.name,
    version: pkg.version,
    description: pkg.description,
  },
  definitions: definitions,
`

but then i should change my validation scheme to: 

`
 "version": {
      "$ref": "#/definitions/semver"
    },
`

is there any chance to include definition to AJV module, so i can use the exactly same scheme in both cases - runtime validation and api documentation? 

`MissingRefError: can't resolve reference #/definitions/semver `

**Comment by epoberezkin** [comment]
@mokone91 this looks like a change proposal, not a bug. I do not understand it, sorry. It would help to submit short working full code sample together with the proposed change.

**Comment by mokone91** [comment]
@epoberezkin Hi!
thanks for your time!

so the problem is that i can't reuse scheme definitions by $ref from root of document using '#/definitions'.
not really sure is its a change proposal or a bug actually. Or i can miss something, it is very likely)

here is examples:

here is valid ajv code with reusable 'semver' scheme:
https://runkit.com/mokone91/ajv-definitions-ref/3.0.0

and here is working openapi scheme which used for swagger api documentation 
https://runkit.com/mokone91/openapi-scheme

so if i will do some changes in schemas for ajv i can reuse same json documents to build both of them from single source, but its not working:
https://runkit.com/mokone91/ajv-definitions-ref-openapi

maybe I adding semver scheme not correctly? (seems i should add it as object with key definitions?)

**Comment by epoberezkin** [comment]
It’s not clear how the open-api definition object from the last link is used, but in any case this object is not a schema. Depending on what you use to process this object, such references to the root of this object may or may not be recognised - most likely the schemas for api requests/responses are treated as root schemas, so #/definitions would point to the roots of these schemas and not to the root of the whole api definition.

If you need to reuse definitions across multiple schemas inside open-api object you could put them all into a separate schema, add to Ajv (as you did in some other links) and refer to them as $ref: defs#/definitions/semver (where defs is schema id - it can be anything)

Hope it makes sense.

**Comment by epoberezkin** [comment]
Some people also add the whole api object as if it were a schema and then access subschemas in it, but the problem is that there will be lots of “unknown keywords” that you’ll either have to define somehow or you won’t be able to use strictProperties (or strict mode in v7 that is now default).

**Comment by mokone91** [comment]
Thanks for helping me understand the point of my issue!
So schema is a separate document at the moment of validation, so if i will add definition to the schema root - this will work as expected.

https://runkit.com/mokone91/ajv-definitions-ref-openapi/2.0.0

in my exact case I can put definitions at the moment of validation, so it will have next view:

import definitions from './definitions';

```
function validate (schema, values) {
  const validator = ajv.compile({
    ...schema,
    definitions, 
  });
  const valid = validator(values);
  if (!valid) {
    throw new ValidationError(validator.errors);
  }
...
```
