### ISSUE TITLE
Different behaviour when using addKeyword and keywords in options

### ISSUE THREAD

**Issue by ttamminen** [ajv-validator/ajv#1308]
We are using `ajv`, for example, in the middleware, where we don't have access to the ajv instance. The preferred way to configure ajv is via options. There seem to be a difference between using `keywords` option and `ajv.addKeyword`. See the runnable examples below.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.12.6

**Ajv options object**

```javascript
const ajv = new Ajv({
  allErrors: true,
  keywords: { typeof: typeofKeyword }
})

OR

const ajv = new Ajv({
  allErrors: true,
})
```

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
      "minLength": 3,
      "maxLength": 255,
      "typeof": "number"
    }
  },
  "required": ["foo"]
}
```

**Sample data**

```json
{ "foo": "aAa" }
```

**Your code**

I copied the source of `typeof` keyword from the ajv-keywords project and used it as an example.

The version with `addKeyword`

https://runkit.com/ttamminen/ajv-issue

The version with `keywords` option.

https://runkit.com/ttamminen/ajv-example

**Validation result, data AFTER validation, error messages**

```
"meta-schema not available"
[Object {dataPath: ".foo", keyword: "typeof", message: "should pass \"typeof\" keyword validation", …}]
```

**What results did you expect?**

As the end results in both ways should be the same, I expected that there will be no "meta-schema not available" error.

**Comment by epoberezkin** [comment]
This is changed in v7 and won't log the warning. In v6 the default meta-schema is added after user-defined keywords, so their schema cannot be validated against meta-schema. I think the validation results are the same.

Possibly, the log can be removed by explicitly passing draft-7 meta-schema via options.

**Comment by ttamminen** [comment]
I see what you mean, in the source code the order is like you described:

```
if (opts.formats) addInitialFormats(this);
if (opts.keywords) addInitialKeywords(this);
addDefaultMetaSchema(this);
```

I think this can be closed, as this won't be an issue in the v7 and we can try passing the draft-7 meta-scheme via options.

**Comment by epoberezkin** [comment]
It may be worth trying to swap the order and see if anything breaks (tests and ajv-keywords). If nothing breaks it can be merged.

**Comment by epoberezkin** [comment]
In v6 I mean - as it will be around for quite some time
