### ISSUE TITLE
TypeScript interface for Schema

### ISSUE THREAD

**Issue by pkuczynski** [ajv-validator/ajv#1311]
Currently, ajv declares schema as plain `object`. I believe it would be worth having a fully typed interface, so one can declare schemas in TypeScript and validate them build time. It would also help when writing schemas in the IDE.

If there is an interest in this, I could fire up a PR...

**Comment by epoberezkin** [comment]
It’s already changed in v7 - please have a look at JSONSchemaType\<T\> - an opinionated type for schema for a given data type T (without union support though, only primitive values, arrays, records and tuples).

It would be great to add support for union types for T - I didn’t have much time to think how to do it.

**Comment by pkuczynski** [comment]
Amazing! Looks great and a nice rewrite to TypeScript. Must cost you a lot of work!

How far do you think from getting from Beta to actually release?

**Comment by epoberezkin** [comment]
Well, it wouldn't have happened without Mozilla grant...

**Comment by epoberezkin** [comment]
Re beta to release - it should happen before the end of the year, with partial draft 2019-09 support, with v8 by April. Beta should be stable - it can be used. I don't expect non-compatible releases, but better to fix the version.
