### ISSUE TITLE
No schema with key or ref draft-4

### ISSUE THREAD

**Issue by snakuzzo** [ajv-validator/ajv#1312]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I have 6.5.2 version.

**Ajv options object**

```javascript

const ajv = new Ajv({
    schemaId: 'id', // draft-04 support requirment.
}),
```

**JSON Schema**

```json

```

**JSON Data**

```json
{
  "properties": {
    "foo": { "type": "string" },
    "bar": { 
      "type": "number", 
      "exclusiveMaximum": true, 
      "maximum": 20,
      "exclusiveMaximum": true,
      "minimum": 1
    }
  }
}
```
**Your code**

```javascript
const Ajv = require('ajv');
const JSONSchemaDraft4Definition = require('ajv/lib/refs/json-schema-draft-04.json');

var data = {
  "properties": {
    "foo": { "type": "string" },
    "bar": { 
      "type": "number", 
      "exclusiveMaximum": true, 
      "maximum": 20,
      "exclusiveMaximum": true,
      "minimum": 1
    }
  }
};

const options = {schemaId: 'id'};
const ajv = new Ajv({options}).addMetaSchema(JSONSchemaDraft4Definition);
var validate = ajv.compile(data);

test(data);

function test(data) {
  var valid = validate(data);
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}


```

**Validation result, data AFTER validation, error messages**

```
/home/user/workspace/myproject/node_modules/ajv/lib/ajv.js:93
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
            ^

Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
    at Ajv.validate (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:93:19)
    at Ajv.validateSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:174:20)
    at Ajv._addSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.addSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:137:29)
    at Ajv.addMetaSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:152:8)
    at Object.<anonymous> (/home/snakuzzo/workspace/mockserver/prova.js:18:32)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```

**What results did you expect?**
Maybe I did'nt undestand, but I expect to validate a schema with exclusiveMaximum/exclusiveMinimum and boolean values using draft 04.

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
You have `new Ajv({options})` instead of `new Ajv(options)` so `schemaId` option is not set.

Also not clear why you validate schema against itself (`data` is used as both `schema` and as `data`), but it's unrelated to the error message.

**Comment by snakuzzo** [comment]
@epoberezkin I need to validate a spec file where there are exclusiveMinimum and exclusiveMaximum with boolean values and not number values...Is it correct to use draft-4 ?
Using your suggestion...

`Error: schema is invalid: data.properties['bar'].exclusiveMaximum should be number`

**Comment by epoberezkin** [comment]
You need to have explicit $schema pointing to draft-4 meta schema in your schemas. By default (if $schema is absent) it uses draft-7 meta-schema, that does not allow booleans for these keywords.

**Comment by epoberezkin** [comment]
If this is not possible (e.g. you don’t control your schemas and can’t change them) you can change default meta-schema - it is also covered in v6 release notes.

**Comment by snakuzzo** [comment]
are you talking about this ?
https://github.com/ajv-validator/ajv#advanced-options (meta option) ?

EDIT: 

I think I solved this way...

```javascript
const Ajv = require('ajv');
const JSONSchemaDraft4Definition = require('ajv/lib/refs/json-schema-draft-04.json');

var data = {
  "properties": {
    "foo": { "type": "string" },
    "bar": { 
      "type": "number", 
      "exclusiveMaximum": true, 
      "maximum": 20,
      "exclusiveMaximum": true,
      "minimum": 1
    }
  }
};

const options = {schemaId: 'id', meta: JSONSchemaDraft4Definition};
const ajv = new Ajv(options);
var validate = ajv.compile(data);

test(data);

function test(data) {
  var valid = validate(data);
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}
```

and this is the output....

```
schema $id ignored http://json-schema.org/draft-07/schema#
schema $id ignored http://json-schema.org/draft-07/schema#
schema $id ignored http://json-schema.org/draft-07/schema#
Valid!
```

Is it right ?

**Comment by epoberezkin** [comment]
Yes. Option `meta` changes the default but does not remove draft-7 meta-schema, that's why you see the warnings. You can either set schemaId to "auto" so it supports both the new and old IDs, or you can set meta to false and then add meta-schema with addMetaSchema and then set default by assigning draft-4 ID to `this._opts.defaultMeta` - it should be in the release notes.

**Comment by fedorov** [comment]
Is there a way around this issue for command line validation?
