### ISSUE TITLE
Optional property with format?

### ISSUE THREAD

**Issue by paul-uz** [ajv-validator/ajv#1316]
I have made a schema that defines a property needing type "string" and format "uri".

If the property is empty (simply `""`) then it fails the format check.

If I remove the format option, I can have a string, or empty string.

So how can I have a valid URI or empty string?

**Comment by epoberezkin** [comment]
With anyOf - one branch would have format, another const: “”

**Comment by paul-uz** [comment]
@epoberezkin thank you, that seems to be working!

Could I suggest you add examples to the v7 docs? And expand the code snippets for the keywords to show how they are situated in the whole schema, I found it a little bit tricky to understand where things should go!
