### ISSUE TITLE
Duplicate `$id`s within the same document passes schema validation...

### ISSUE THREAD

**Issue by busticated** [ajv-validator/ajv#1317]
hey there :wave:

i'm guessing i'm missing something 🤗 - the docs say:

>You cannot have the same $id (or the schema identifier) used for more than one schema - the exception will be thrown

([source](https://github.com/ajv-validator/ajv#combining-schemas-with-ref))

...but assigning the same `$id` to different schemas (within the same document) passes schema validation. 

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`v6.12.6`, yes

**Ajv options object**

```javascript
{
	allErrors: true,
	useDefaults: true,
	extendRefs: 'fail',
	missingRefs: 'fail',
	strictNumbers: true,
	strictDefaults: true,
	strictKeywords: true,
	unknownFormats: true,
	validateSchema: true,
	removeAdditional: 'all'
}
```

**JSON Schema**

```json
{
    "$schema": "https://particle.io/draft-07/schema#",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "Fake Custom Schema",
    "description": "A customized JSON schema for testing",
    "properties": {
        "foo": {
            "$id": "#/nope",
            "type": "integer"
        },
        "bar": {
            "$id": "#/nope",
            "type": "string"
        }
    }
}
```

**Sample data**

```json
{
    "foo": 1,
    "bar": "ok"
}
```

**Your code**

```javascript
const ajv = new AJV({
    allErrors: true,
    useDefaults: true,
    extendRefs: 'fail',
    missingRefs: 'fail',
    strictNumbers: true,
    strictDefaults: true,
    strictKeywords: true,
    unknownFormats: true,
    validateSchema: true
});

if (!ajv.validateSchema(schema)){
    throw new Error('Invalid schema!');
}
```

**What results did you expect?**

i expected my schema to be considered invalid and an error to be throw - `Error: Invalid schema!`

**Comment by epoberezkin** [comment]
`validateSchema` will not catch issues like that, as it only validates structure and syntax (by validating it against meta-schema as JSON document), but it does not do semantic validation - unknown keywords or formats, missing refs, or duplicate IDs. To catch issues like that you need to `compile`.

The current example though goes past the `compile` as well - it is not a common way to write schemas.

A more common approach would be to have `definitions` (or `$defs` in the next version of the spec) and only reference subschemas from there:

```javascript
{
  $id: "http://example.com/example.json",
  $defs: {
    foo: {
      $id: "#/nope",
      type: "integer",
    },
    bar: {
      $id: "#/nope",
      type: "string",
    },
  },
  type: "object",
  properties: {
    foo: {$ref: "#/foo"},
    bar: {$ref: "#/bar"},
  },
}
```

That schema throws error when compiled.

The issue won't be addressed in v6, but is likely to be addressed in v7.

**Comment by busticated** [comment]
ah, ok. thanks 🙏👍

**Comment by epoberezkin** [comment]
Let’s keep it open. I’ve only added a failed test for it, it would be good to resolve.

**Comment by busticated** [comment]
using your example, i get an error (`Schema http://example.com/example.json is loaded but http://example.com/example.json#/foo cannot be resolved`) but changing every `$id` and `$ref` to `"#/nope"`, i still don't get an error about duplication of `$id`s

```javascript
const ajv = new AJV({
    allErrors: true,
    useDefaults: true,
    extendRefs: 'fail',
    missingRefs: 'fail',
    strictNumbers: true,
    strictDefaults: true,
    strictKeywords: true,
    unknownFormats: true,
    validateSchema: true
});

try {
    ajv.compile({
        $id: "http://example.com/example.json",
            $defs: {
                foo: {
                    $id: "#/nope",
                    type: "integer",
                },
                bar: {
                    $id: "#/nope",
                    type: "string",
                },
        },
        type: "object",
        properties: {
            foo: {$ref: "#/nope"},
            bar: {$ref: "#/nope"},
        },
    });
} catch (error){
    console.log(error);
}

**Comment by epoberezkin** [comment]
I see - it was failing because refs should have been #/$defs/foo and not because of duplication

**Comment by Bgshanoams** [comment]
Hello,dear sendnsomecthiny coins.
Regards.

На нд, 8.11.2020 г., 11:21 ч. Evgeny Poberezkin <notifications@github.com>
написа:

**Comment by epoberezkin** [comment]
fix merged to v7-beta
