### ISSUE TITLE
Object with property named 'type' does not validate as required

### ISSUE THREAD

**Issue by powmedia** [ajv-validator/ajv#133]
Given the following, the 'type' property does not fail the 'required' validation.  Works as expected for 'foo' and 'percent'.

```
tax: {
  type: 'object',
  required: ['type', 'percent', 'foo'],
  additionalProperties: false,
  properties: {
    type: {
      type: 'string'
    },
    percent: {
      type: 'number',
      minimum: 0,
      maximum: 100
    },
    foo: {
      type: 'string'
    }
  }
}
```

**Comment by rom1504** [comment]
Apparently this is not valid.

Why ? I can't find it in the spec ?

Why can't we have a type property in json ?

**Comment by epoberezkin** [comment]
What exactly is not valid? See https://tonicdev.com/esp/56d84ef08757b50d0044442d

Seems to work correctly.

**Comment by powmedia** [comment]
Sorry it was a mistake; I closed the issue but should have commented too.

**Comment by rom1504** [comment]
Yes it's indeed valid, I was making a mistake in https://github.com/epoberezkin/ajv/issues/137
