### ISSUE TITLE
AdditionalItems is not factored in anyOf

### ISSUE THREAD

**Issue by ThomasAribart** [ajv-validator/ajv#1333]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Issue still happens in v6.12.6.

**Ajv options object**

```javascript
const ajv = new Ajv();
```

**JSON Schema**

```json
{
  "type": "array",
  "items": [{ "type": "number" }, { "type": "boolean" }],
  "anyOf": [
    { "additionalItems": { "type": "number" } },
    { "additionalItems": { "type": "boolean" } }
  ]
}
```

**Sample data**

```json
[42, true, "neither number or boolean"]
```

**Your code**

```javascript
ajv.validate(schema, instance);
```

**Validation result, data AFTER validation, error messages**

```
true
```

**What results did you expect?**

```
false
```

**Are you going to resolve the issue?**

I can if needed. I just want to make sure that the actual result is not expected first 🤔

**Comment by epoberezkin** [comment]
The problem is that your “items” keyword value is an array with one item, so the schema inside is only applied to the first item rather than to all. It has to be an object (schema) to apply to all items.

**Comment by ThomasAribart** [comment]
@epoberezkin Sorry, I don't understand your response.

There is two items in the "items" keyword (`{ "type": "number" }` and `{ "type": "boolean" }`).
Which shema is only applied to which item ?

Following the JSON schema specification, it seems like the above schema should be equivalent to:

```
{
  "anyOf": [
    {
      "type": "array",
      "items": [
        { "type": "number" },
        { "type": "boolean" }
      ],
      "additionalItems": { "type": "number" }
    },
    {
      "type": "array",
      "items": [
        { "type": "number" },
        { "type": "boolean" }
      ],
      "additionalItems": { "type": "number" }
    },
  ]
}
```

It seems like AJV applies this behavior to the `minItems` and `maxItems` keywords, for example.

Following this definition, `[42, true, "string"]` should not be valid as the third item, which is an additional item, is neither a number or a boolean.

**Comment by ThomasAribart** [comment]
It seems rather like the `additionalItems` keyword is omitted from the factorization. I've tested with `allOf` and `oneOf` and the pb seems the same:

- `oneOf: [ { additionalItems: "boolean" }, { additionalItems: "number" }]` will never validate as it is equivalent to `oneOf: [{}, {}]` and both schemas (once merged with the parent schema) are always matched.
- `allOf: [ { additionalItems: "boolean" }, { additionalItems: "number" }]` will always validate as it is equivalent to `allOf: [{}, {}]` and both schemas (once merged with the parent schema) are always matched.

**Comment by epoberezkin** [comment]
> There is two items in the "items" keyword ({ "type": "number" } and { "type": "boolean" }).
> Which shema is only applied to which item ?

The first to the first, and the second to the second - this is per spec. This schema is effectively for 2-tuple, not for an array. It seems like what you wanted, sorry, I misunderstood - this is a very common mistake

> Following the JSON schema specification, it seems like the above schema should be equivalent to:

No, it is not equivalent. "AdditionalItems" is only related to "items" in the same schema object, in this case "additionalItems" is simply ignored, as per spec. Ajv v7 would throw an error by default (see "strict mode"), but v6 quietly ignores "additionalItems".

> It seems rather like the additionalItems keyword is omitted from the factorization.

There is not such thing as factorisation in the spec. "additionalItems" should be in the same schema as "items" to be taken into account. draft-2019-09 introduced "unevaluatedItems" with the behaviour you expect - it is supported in v7 (as a separate Ajv class - `import Ajv2019 from "ajv/dist/2019"` - see the docs).

**Comment by epoberezkin** [comment]
Now I am thinking that in Ajv v7 for draft-2019-09 strict mode needs to be updated, it should take `unevaluatedItems` into account as well (the workaround is to use `strictTuples: false` option)

**Comment by ThomasAribart** [comment]
Ahh alright ! Thanks for the response, it's very clear 👍
