### ISSUE TITLE
unevaluatedProperties in subschema does not work correctly with allOf

### ISSUE THREAD

**Issue by DavidMhn** [ajv-validator/ajv#1350]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
7.0.0-rc2
**Ajv options object**

use the 2019 version of the validator

```javascript
var ajv2019 = require('ajv/dist/2019').default;
var ajv = new ajv2019();
```

**JSON Schema**

```json
{
  "properties": {
    "rootObject": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/subLevel"
        },
        {
          "properties": {
            "topLevelProp": { "type": "string" }
          },
          "required": ["topLevelProp"]
        }
      ],
      "unevaluatedProperties": false,
    }
  },
  "definitions": {
    "subLevel": {
      "type": "object",
      "properties": {
        "subLevelProp": { "type": "string" },
      },
      "required": ["subLevelProp"],
      "unevaluatedProperties": false,
    },
  },
}
```

**Sample data**

```json
{
  "rootObject": {
    "subLevelProp": "a",
    "topLevelProp": "a",
  }
}
```

**Your code**

link to code sample: https://runkit.com/bourbongit/5fd73f6aa58c7a001a4b01f1

```javascript
var ajv2019 = require('ajv/dist/2019').default;
var ajv = new ajv2019();
let validate = ajv.compile(schema);
console.log(validate(data));
console.log(validate.errors)
```

**Validation result, data AFTER validation, error messages**

```
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
false
[
  {
    keyword: 'unevaluatedProperties',
    dataPath: '/rootObject',
    schemaPath: '#/definitions/subLevel/unevaluatedProperties',
    params: { unevaluatedProperty: 'topLevelProp' },
    message: 'should NOT have unevaluated properties'
  }
]
```

**What results did you expect?**
The data should evaluate successfully against the schema. Indeed the unevaluatedProperties in the scope of a subLevel should not consider properties defined by its enclosing schema as "unevaluated" because they are evaluated by the parent schema.

  "rootObject": {
    "subLevelProp": "a", --> evaluated by the sub-schema "subLevel"
    "topLevelProp": "a", --> evaluated by the top-level schema "rootObject"
  }

Otherwise it's simply impossible to have a data matching this schema.
A workaround is to remove the unevaluatedProperties from the subschema subLevel, and it works. However this is a problem in large complex schemas where sub-schemas are used in different places, sometimes as top-level schemas, sometimes as sub-schemas, and we want to enforce unevaluatedProperties to true eveyrwhere.

**Are you going to resolve the issue?**
no

**Comment by epoberezkin** [comment]
I believe it is how it is specified in JSON Schema draft-2019-09. Inner unevaluatedProperties is supposed to only account for properties evaluated by adjacent/sibling keywords, it would know nothing about its parent schema.

See https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-9.3.2.4:

> The behavior of this keyword depends on the annotation results of
   adjacent keywords that apply to the instance location being
   validated.  Specifically, the annotations from "properties",
   "patternProperties", and "additionalProperties", which can come from
   those keywords when they are adjacent to the "unevaluatedProperties" keyword. 
   Those three annotations, as well as
   "unevaluatedProperties", can also result from any and all adjacent
   in-place applicator (Section 9.2) keywords.  This includes but is not
   limited to the in-place applicators defined in this document.

The key word in this paragraph is "adjacent".

Further, there is a test in JSON Schema Test Suite that shows that unevaluatedProperties also can't "see" inside cousins, not only parents:

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/unevaluatedProperties.json#L594

The idea of this keyword is that you would only use it in your top level schema that you actually use to validate data, while any components used by it won't have unevaluatedProperties.

If you need a schema that is used both as a component and as an independent schema you can always define it:

```json
{
  "$ref": "#/definitions/subLevel",
  "unevaluatedProperties": false
}
```
