### ISSUE TITLE
Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by mdantonio** [ajv-validator/ajv#1363]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`7.0.2`

**Ajv options object**

```javascript
const ajv = new Ajv.default({ code: { source: true } });
```

**JSON Schema**

-

**Sample data**

-

**Your code**

```javascript
import * as schemas from "validate.js";

const validator = schemas[MyRef];

const valid = validator(data);
```

**Validation result, data AFTER validation, error messages**

On Karma:
```
TypeError: Cannot read property 'test' of undefined
```

At Runtime:

```
TypeError: You provided 'null' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

Both errors are raised by `validator(data);`

**What results did you expect?**

On 7.0.1 I have no errors at runtime, so this is a regression introduced with the latest version. Karma fails also with 7.0.1 but due to a different error (duplicated functions fixed with 7.0.2)

**Are you going to resolve the issue?**

The runtime error is pretty obscure but I tried to work around the error provided by karma.

the only 'test' property that I found in the validation functions is:

`if(!(formats2.test(data0))`

where formats2 is:

`const formats2 = {"_items":["require(\"ajv-formats/dist/formats\").",{"str":"fullFormats"},""]}.email;`

I verified with a console.log that formats2 is undefined

On the 7.0.1 this part works well and I noticed that formats2 is created with a different syntax:

`const formats2 = require("ajv-formats/dist/formats").fullFormats.email;`

**Comment by epoberezkin** [comment]
@mdantonio could you please post an executable code sample that shows the issue?

**Comment by mdantonio** [comment]
Hope that this can be enough:

```
const Ajv = require("/app/node_modules/ajv");
const addFormats = require("/app/node_modules/ajv-formats");
const standaloneCode = require("/app/node_modules/ajv/dist/standalone");

const schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "User": {
      "additionalProperties": false,
      "properties": {
        "email": {
          "format": "email",
          "type": "string"
        }
      },
      "required": [
        "email"
      ],
      "type": "object"
    }
  }
}

const ajv = new Ajv.default({ code: { source: true } });
addFormats(ajv);

const validate = ajv.compile(schema);

for (let definition in schema["definitions"]) {
  const def = schema["definitions"][definition];
  const ref = "#/definitions/" + definition;

  ajv.addSchema(def, ref);
}

let moduleCode = standaloneCode.default(ajv);

console.log(moduleCode);
```

With 7.0.2 the output is:

```
"use strict";exports["#/definitions/User"] = validate11;const schema12 = {"additionalProperties":false,"properties":{"email":{"format":"email","type":"string"}},"required":["email"],"type":"object"};const formats0 = {"_items":["require(\"ajv-formats/dist/formats\").",{"str":"fullFormats"},""]}.email;function validate11(data, {dataPath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(data && typeof data == "object" && !Array.isArray(data)){let missing0;if(data.email === undefined && (missing0 = "email")){validate11.errors = [{keyword:"required",dataPath,schemaPath:"#/required",params:{missingProperty: missing0},message:"should have required property '"+missing0+"'"}];return false;}else {const _errs0 = errors;for(const key0 in data){if(!(key0 === "email")){validate11.errors = [{keyword:"additionalProperties",dataPath,schemaPath:"#/additionalProperties",params:{additionalProperty: key0},message:"should NOT have additional properties"}];return false;break;}}if(_errs0 === errors){if(data.email !== undefined){let data0 = data.email;const _errs1 = errors;if(errors === _errs1){if(typeof data0 === "string"){if(!(formats0.test(data0))){validate11.errors = [{keyword:"format",dataPath:dataPath+"/email",schemaPath:"#/properties/email/format",params:{format: "email"},message:"should match format \""+"email"+"\""}];return false;}}else {validate11.errors = [{keyword:"type",dataPath:dataPath+"/email",schemaPath:"#/properties/email/type",params:{type: "string"},message:"should be string"}];return false;}}}}}}else {validate11.errors = [{keyword:"type",dataPath,schemaPath:"#/type",params:{type: "object"},message:"should be object"}];return false;}validate11.errors = vErrors;return errors === 0;}

```

With 7.0.1 the output is:

```
"use strict";exports["#/definitions/User"] = validate11;const schema12 = {"additionalProperties":false,"properties":{"email":{"format":"email","type":"string"}},"required":["email"],"type":"object"};const formats0 = require("ajv-formats/dist/formats").fullFormats.email;function validate11(data, {dataPath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(data && typeof data == "object" && !Array.isArray(data)){let missing0;if(data.email === undefined && (missing0 = "email")){validate11.errors = [{keyword:"required",dataPath,schemaPath:"#/required",params:{missingProperty: missing0},message:"should have required property '"+missing0+"'"}];return false;}else {const _errs0 = errors;for(const key0 in data){if(!(key0 === "email")){validate11.errors = [{keyword:"additionalProperties",dataPath,schemaPath:"#/additionalProperties",params:{additionalProperty: key0},message:"should NOT have additional properties"}];return false;break;}}if(_errs0 === errors){if(data.email !== undefined){let data0 = data.email;const _errs1 = errors;if(errors === _errs1){if(typeof data0 === "string"){if(!(formats0.test(data0))){validate11.errors = [{keyword:"format",dataPath:dataPath+"/email",schemaPath:"#/properties/email/format",params:{format: "email"},message:"should match format \""+"email"+"\""}];return false;}}else {validate11.errors = [{keyword:"type",dataPath:dataPath+"/email",schemaPath:"#/properties/email/type",params:{type: "string"},message:"should be string"}];return false;}}}}}}else {validate11.errors = [{keyword:"type",dataPath,schemaPath:"#/type",params:{type: "object"},message:"should be object"}];return false;}validate11.errors = vErrors;return errors === 0;}
```

The difference is the formats0

7.0.2: `const formats0 = {"_items":["require(\"ajv-formats/dist/formats\").",{"str":"fullFormats"},""]}.email;`
7.0.1: `const formats0 = require("ajv-formats/dist/formats").fullFormats.email;`

If I edit the validation code by adding a console.log(formats0) I obtain an `undefined` with 7.0.2 and valid value with 7.0.1 (i.e. `/^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i`)

The  same happens with others validation formats, e.g. date-time

undefined on 7.0.2 and an Object with 7.0.1

```
{validate: ƒ, compare: ƒ}
compare: ƒ compareDateTime(dt1, dt2)
arguments: (...)
caller: (...)
length: 2
name: "compareDateTime"
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: formats.js:113
[[Scopes]]: Scopes[2]
validate: ƒ date_time(str)
arguments: (...)
caller: (...)
length: 1
name: "date_time"
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: formats.js:108
[[Scopes]]: Scopes[2]
0: Closure (XnP8) {DATE: /^(\d\d\d\d)-(\d\d)-(\d\d)$/, DAYS: Array(13), isLeapYear: ƒ, date: ƒ, compareDate: ƒ, …}
1: Global {window: Window, self: Window, document: document, name: "", location: Location, …}
__proto__: Object
```

**Comment by mdantonio** [comment]
Additional note: of course I'm using the latest ajv-formats (1.5.1)

**Comment by epoberezkin** [comment]
Thank you! Weird... No idea how this change could have caused that - seems unrelated :) Will be checking/fixing

**Comment by epoberezkin** [comment]
I am not sure why this code is needed at all:

```javascript
for (let definition in schema["definitions"]) {
  const def = schema["definitions"][definition];
  const ref = "#/definitions/" + definition;

  ajv.addSchema(def, ref);
}
```

These definitions are available when schema is compiled... I am probably missing something.

**Comment by epoberezkin** [comment]
I can't reproduce it - I've added the test (and actually all JSON Schema tests that use formats also run with standalone code). 

`format0` is assigned the same value in 7.0.2 as it was in 7.0.1

It may be some version conflict, or installation, or something is `npm link`ed not in the way you expect... Try doing clean installation and maybe check which versions are actually used.

**Comment by epoberezkin** [comment]
Also, if you look at the diff between 7.0.2 and 7.0.1 there is no reason for it would have changed the behaviour around format validation - although it's less important, I can see that it definitely didn't change without accounting for some outside factor.

It would help creating a fully separate repo with minimal number of dependencies that reproduce the issue - by bisecting the dependencies list, you may be able to find the culprit.

**Comment by mdantonio** [comment]
It is needed to be able to re-extract the validator functions by name at runtime by doing this:

```
# validate.js is produced by the snippet above, with fs.writeFileSync("validate.js", moduleCode);
import * as schemas from "validate.js";

export function validate(ref, data) {

  const def = "#/definitions/" + ref;
  if (!schemas[def]) {
    console.warn("Validation function " + ref + " not found");
    return null;
  }
  const validator = schemas[def];

  const valid = validator(data);
  if (valid) {
    console.info("Response validated against " + ref + " schema");
    return null;
  }

  console.warn("Response does not meet " + ref + " schema");

  return validator.errors
}
```

By using this I'm able to validate my APIs responses (more or less) this way :

```
resp = api.get(":..")
const errors = validate(resp, "MySchema")
if (errors != null) {
    ...
}
```

I guess that I need explicit ajv.addSchema(def, ref) because I don't have ids in my schema... And I haven't ids because I'm creating json schemas by converting typescript interfaces by using ts-json-schema-generator and I can't further manipulate the json

build time:
`typescript interfaces ->  ts-json-schema-generator -> json schema -> ajv standalone compilation -> validation functions`

runtime:
`validation functions -> validate`

If you can suggest me some simplifications would be of course grateful (I'm using Angular). However this mechanism always worked well both with ajv 6 (not standalone, but by compiling (i.e. ajv.addSchema) at runtime) and ajv 7.0.1 (with standalone compilation).

> I can't reproduce it - I've added the test (and actually all JSON Schema tests that use formats also run with standalone code).

:(

I'm obtaining the same results con github actions, i.e. on fresh installations...
Tomorrow morning I will cleanup my whole project and I will retry... I hope to be more lucky so

**Comment by mdantonio** [comment]
Hello,
this morning it is working as expected both on local deployment (after having deleted every single file, not only the node_modules folder) and github actions.
Somehow some file outside the node_modules folder conflicted the execution of ajv (I really don't know what... maybe the yarn cache?). What is much more unclear is the behavior of github actions. I don't have any cache configured that could share folders between different runs, so every new execution should be totally independent from the previous.
I'm sorry for the totally pointless issue :(
Really thank you for your prompt support, since this problem was not directly related to ajv I close the issue.

**Comment by epoberezkin** [comment]
No problem - it’s sometimes not clear, always better to check. Please let me known when/if you find out the root cause - it may be worth adding to docs or compatibility issue template.

**Comment by epoberezkin** [comment]
> I guess that I need explicit ajv.addSchema(def, ref) because I don't have ids in my schema...

you can still have one schema added per instance without ID - it is equivalent to having ID as empty string. If you add the whole schema (addSchema) you can access separate definitions with getSchema(“#/definitions/...”) without adding them in a loop one by one. Check the test I added in linked commit.

Also, if all you need is to add them to the module, you don’t need to getSchema them at all - you need to pass the map of refs you need to standaloneCode (also in the test).

hope it helps :)

**Comment by mdantonio** [comment]
Thank you for the suggestion, it works :)

I still need a loop to dynamically create the map for the standaloneCode, but a loop to create a map is greatly better than a loop to add single schemas


replaced this:
```
const validate = ajv.compile(schema);

for (let definition in schema["definitions"]) {
  const def = schema["definitions"][definition];
  const ref = "#/definitions/" + definition;

  console.log("    Adding " + ref);
  ajv.addSchema(def, ref);
}

let moduleCode = standaloneCode.default(ajv);

```

with this:

```
const mapping = {};
for (let definition in schema["definitions"]) {
  mapping[definition] = "#/definitions/" + definition;
  console.log("    Adding " + definition);
}

ajv.addSchema(schema);

let moduleCode = standaloneCode.default(ajv, mapping);
```

and changed my validation function access key
from `schemas["#/definitions/"MySchema"]` to `schemas["MySchema"]`

Now it is slightly faster: 430 msec vs 470 msec 

Thank you again

**Comment by epoberezkin** [comment]
It's interesting whether it actually affects generated code size, but I'd expect it to be the same...

I was thinking to support an array of refs one wants to export as the second arg in standaloneCode. In this case you'd simply needed to pass ```Object.keys(schema.definitions).map(d => `#/definitions/${d}`)```

**Comment by mdantonio** [comment]
The size is the same

> I was thinking to support an array of refs one wants to export as the second arg in standaloneCode. In this case you'd simply needed to pass Object.keys(schema.definitions).map(d => `#/definitions/${d}`)


That would be great, even simpler!

**Comment by mdantonio** [comment]
Hello and happy new year!

I reopen because the problem occurred again, it seems somehow related to the release of the new version of ajv but without any clear hint.

Now I have two yarn.lock files one working (produced before the release) and the other raising the error (produced after the release) even if all versions in my package.json are locked included ajv (locked to 7.0.2). My guess is that the problem raises from some unlocked version in some of the dependencies (or sub-dependencies) but I'm unable to understand what.

If you want I could share with you the two lock files, maybe you would be able to notice where the problem may raise from

I also try to describe the actual context where the problem occurred, I hope that the description will be clear enough:

1) my local deployment is working fine
2) on 2nd of January in the morning I pushed a commit and the test workflow on Github actions completed with success
3) the cron job on github action executed the 3rd of January in the early morning and failed with the same error reported in this issue (the cron executed the tests on the exact same commit that succeeded the day before, so the problem was not directly due to my code)
4) after that any other commit, cron or manual execution on github actions failed in the same way
5) my local deployment continued to work (also by executing the same karma job that was failing on github actions)
6) I created a fresh local deployment and this started to fail

The difference between (5) and (6) was the content of node_modules (some differences in versions of some sub-dependencies). I verified that to the content of the yarn.lock files was different and this can explain why my original local deployment was continuing to work, probably It was ignoring some new version of some sub-dependency)

I tried to copy the yarn.lock file from the working deployment into the fresh deployment and this started to work again... this confirm that the error is due to some difference / conflict in libs versions.

Then I noticed that the new version of ajv (7.0.3) was released exactly between my last working commit and the begin of the failures (i.e. the jobs started to failed after the release, even If I lock my version to 7.0.2 in my package.json)

Now i bumped my dependency from 7.0.2 to 7.0.3 and everything works again, both the fresh local deployment and the Gitub Actions job

Do you think that from the yarn.lock files you would be able to understand what is happening?

(And I apologize if my issues are always so confused...)

**Comment by epoberezkin** [comment]
No promises but happy to look - something weird is happening indeed with version change, there was another issue and also with yarn. It does look similar to some old npm issue with sub dependencies that they seem to have fixed, but maybe yarn didn't... Just a speculation.

Please submit as a separate issue using compatibility template

**Comment by epoberezkin** [comment]
See #1390 for solutions
