### ISSUE TITLE
Docs: using ajv v7 in ES5 environments

### ISSUE THREAD

**Issue by aladdin-add** [ajv-validator/ajv#1364]
We are using the package in a web app (supporting es5 env), and got erros after upgrading to ajv v7.0.1.

Do you still want to support pre-es6 env? Or just update the docs to clarify its requirement. 😄

**Comment by epoberezkin** [comment]
There is an option to generate es5 code (`new Ajv({code:{es5:true}})`), it's not a bug - the default is to generate ES6 code. Please see the release notes - there are some other breaking changes.

**Comment by epoberezkin** [comment]
And if you need to use Ajv itself in pre-ES6 env you need to recompile TypeScript to an earlier target - it's set to 2018 in the bundled compiled code.

**Comment by epoberezkin** [comment]
Probably it deserves the section in the docs :)

**Comment by aladdin-add** [comment]
I've got a new error when trying to compile the ts(using `@babel/preset-typescript`) code:

![image](https://user-images.githubusercontent.com/13050025/102851045-c4d2f280-4455-11eb-96c8-8189b0eb1ada.png)

is there a way to avoid using the `import =` syntax?

**Comment by epoberezkin** [comment]
The only way to avoid `import =` syntax is to use esModuleInterop option - in results in bigger code size and seems to be forcing dependencies to also use this option. You should  be importing from dist folder (that’s where main points to), so it shouldn’t really matter.

Or you can alway recompile typescript to older/newer JS version
