### ISSUE TITLE
OneOfError#passingSchemas can be null but not marked as such in types

### ISSUE THREAD

**Issue by G-Rath** [ajv-validator/ajv#1367]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Latest

**Your typescript code**

```typescript
const oneOfError = (): OneOfError => ({
  keyword: 'oneOf',
  dataPath: '',
  schemaPath: '#/oneOf',
  params: { passingSchemas: null },
  message: 'should match exactly one schema in oneOf'
});
```

**Typescript compiler error messages**

```
TS2322: Type 'null' is not assignable to type '[number, number]'.
```

However, this isn't true:

```
> var validator = new Ajv().compile({ oneOf: [{required: ['p']}]})
strict mode: missing type "object" for keyword "required" at "#/oneOf/0" (strictTypes)
undefined
> validator({}); validator.errors
[
  {
    keyword: 'required',
    dataPath: '',
    schemaPath: '#/oneOf/0/required',
    params: { missingProperty: 'p' },
    message: "should have required property 'p'"
  },
  {
    keyword: 'oneOf',
    dataPath: '',
    schemaPath: '#/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
>
```

**Describe the change that should be made to address the issue?**

I think that this is a bug with the types, as I'd expect the library to be throwing if it wasn't already expecting this to be null (or its not using the property itself, in which case still a bug in the types).

So I think it just needs to be marked as `| null`

**Are you going to resolve the issue?**

If I have the time and the issue is still around - got a lot on right now, but very excited about the new typescript-powered version 😍 

I'd hope this is just a matter of adding `| null` but have not opened a PR doing that yet as I've not had the time to dive further into the library and it could require new "not null" checks to be added in the codebase to make TS happy.

**Comment by epoberezkin** [comment]
Thank you - it needs `| null` indeed here: https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/applicator/oneOf.ts#L12

**Comment by epoberezkin** [comment]
The reason it’s not throwing is because this property is assigned in generated code and there is probably no test that checks properties of this particular error object.

**Comment by G-Rath** [comment]
Cool, I figured that's probably what it was - I'll make a PR if you're not already doing the change :)
