### ISSUE TITLE
Fails to compile schema when enum has too many values

### ISSUE THREAD

**Issue by willfarrell** [ajv-validator/ajv#1371]
"ajv": "7.0.2",

**Ajv options object**
Defaults

**JSON Schema**
```json
{
...
"type":"object",
"properties":{
  "large-enum":{
    "type":"string",
    "enum":[... > 1900 values ...]
  }
}

}
```
Real use case enum list can be found at https://github.com/gordonfn/schema/blob/main/src/values/CharacteristicName.legacy.json

**Sample data**
Error compiling schema, NA

**Your code**
```javascript
const schema = {...}
const Ajv = require('ajv').default
const ajv = new Ajv()
const validate = ajv.compile(schema)
```
Full failing example can be found at https://github.com/gordonfn/schema/blob/feature/draft-2019/bin/build.js

**Validation result, data AFTER validation, error messages**

```
Error compiling schema, function code: ...
(node:31228) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at Ajv.compileSchema (/Users/willfarrell/Development/gordonfn/schema/node_modules/ajv/dist/compile/index.js:88:30)
    at Ajv._compileSchemaEnv (/Users/willfarrell/Development/gordonfn/schema/node_modules/ajv/dist/core.js:441:37)
    at Ajv.compile (/Users/willfarrell/Development/gordonfn/schema/node_modules/ajv/dist/core.js:139:38)
    at process (/Users/willfarrell/Development/gordonfn/schema/bin/build.js:56:24)
```

**What results did you expect?**
I expected it to compile the schema. In ajv v6 compile work with enum length longer than 14000 strings without issue.

**Are you going to resolve the issue?**
I will continue to use ajv v6 for now. Upgrading to draft-2019-09 is not critical for us, but nice to have for the new standalone bundler functionality.

**Comment by epoberezkin** [comment]
enum is compiled to the expression by default, there is an option `loopEnum` that allows to restrict the size of the enum that would compile to the expression, and any bigger enum would compile to loop. It has changed in v7 - in v6 enum always compiled to loop which is not efficient in most cases.

**Comment by epoberezkin** [comment]
See this example https://runkit.com/esp/5fe8f01fc2fc2a001a114398

It fails without the option and works with the option.

**Comment by epoberezkin** [comment]
I thought nobody would ever need that option btw :)

**Comment by willfarrell** [comment]
Thanks for the fast reply. I'll test it out later today. Yeah ... I would have made the same assumptions. We're pretty edge case on how we're using json schema do define a new scientific data standard, most use xml in our industry. Sorry I wasn't able to find this new option in the docs at first. Hopefully this issue will help the few others that run into this issue.

Enjoy your holidays.

**Comment by willfarrell** [comment]
Confirmed, `loopEnum` worked like a charm. Thanks again.

**Comment by jviotti** [comment]
I spent a couple of hours trying to debug a similar problem. Another happy user of `loopEnum` :D
