### ISSUE TITLE
Broken links in changelog doc

### ISSUE THREAD

**Issue by medikoo** [ajv-validator/ajv#1374]
Most of the documentation links in https://github.com/ajv-validator/ajv/releases/tag/v7.0.0 release notes are broken, e.g.:

- https://github.com/ajv-validator/ajv/blob/v7.0.0/json-schema.md#unevaluatedproperties
- https://github.com/ajv-validator/ajv/blob/v7.0.0/json-schema.md#unevaluateditems
- https://github.com/ajv-validator/ajv/blob/v7-beta/docs/strict-mode.md

**Comment by epoberezkin** [comment]
I think I updated them all - thank you!
