### ISSUE TITLE
`undefined` treated as `null`able in JSONSchemaType

### ISSUE THREAD

**Issue by erikbrinkman** [ajv-validator/ajv#1375]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

7.0.2, yes

**Your typescript code**

```
const testSchema: JSONSchemaType<{ a?: string }> = {
    type: "object",
    properties: { a: { type: "string" } },
    required: [],
};
```
produces the following error, but
```
const testSchema: JSONSchemaType<{ a: string | null }> = {
  type: "object",
  properties: { a: { type: "string" } },
  required: ["a"],
};
```
type checks fine.

**Typescript compiler error messages**

```
error TS2322: Type '{ type: "string"; }' is not assignable to type '{ $ref: string; } | ({ type: "string"; minLength?: number | undefined; maxLength?: number | undefined; pattern?: string | undefined; format?: string | undefined; } & { [keyword: string]: any; ... 10 more ...; not?: Partial<...> | undefined; } & { ...; })'.
  Type '{ type: "string"; }' is not assignable to type '{ type: "string"; minLength?: number | undefined; maxLength?: number | undefined; pattern?: string | undefined; format?: string | undefined; } & { [keyword: string]: any; $id?: string | undefined; ... 9 more ...; not?: Partial<...> | undefined; } & { ...; }'.
    Property 'nullable' is missing in type '{ type: "string"; }' but required in type '{ nullable: true; const?: undefined; enum?: (string | null | undefined)[] | undefined; default?: string | null | undefined; }'.

     properties: { a: { type: "string" } },
                   ~

  node_modules/ajv/dist/types/json-schema.d.ts:95:5
    95     nullable: true;
           ~~~~~~~~
    'nullable' is declared here.
```

**Describe the change that should be made to address the issue?**

In essence the current type definition says that any non-required field should be nullable, but there is a distinction between null and undefined. I think the change should just be making [this line](https://github.com/ajv-validator/ajv/blob/master/lib/types/json-schema.ts#L109) `null extends T` instead of `undefined extends T`

I could also see another change that adds undefined to possible values in enum / default if `undefined extends T`, but maybe that's not necessary since in general json does not allow for undefined values.

This change would also be breaking since the second example will now error as it used to compile (although the error seems correct).

**Are you going to resolve the issue?**

I can, but I'm seeking guidance on the fix first. Javascript distinguishes between `undefined` and `null` but json doesn't, or more specifically `undefined` would imply an omitted field, where as `null` is a value. However, it's not that simple since in some cases it seems that undefined values are omitted (in the case of object values) whereas in other cases they're serialized as a null value (array elements). Therefore this change doesn't seem super straightforward.

**Comment by epoberezkin** [comment]
I agree, it is quite an opinionated choice of how an optional field should be represented in JSON.

The reason for this choice is that it is quite common to allow null for optional fields in JSON and most typescript apps would not normally distinguish how null and undefined are processed...

This choice is partially made because you could use something like `string | null` in typescript but JSONSchemaType<T> doesn't yet support unions so it would simply not work with it...

It is a relatively experimental new thing, but it's usage is completely optional, as the doc says.

I am considering what's the best way to evolve it - supporting unions would be a very valuable addition. Then we can possibly parameterise this choice via the second parameter of this type (and possibly change the current default to require nullable in v8)

**Comment by erikbrinkman** [comment]
Aren't unions supported by `oneOf`, e.g. couldn't a union be written as `oneOf([{type: "string"}, {type: "null"}])`, or are you saying that unions are supported in ajv, but the typescript checking of appropriate validation is not available for unions, e.g. `JSONSchemaType` does not accurately break a union down into a schema type like `oneOf`? It does seem like doing that would be tough given the variety of ways to potentially represent such a schema.

In the short term, would you support a PR that added options to the typescript checking? I'm imagining something like:
```
type JSONSchemaOptions = { optionalImpliesNullable?: boolean };

type JSONSchemaType<T,  options extends JSONSchemaOptions = {}, _partial extends boolean = false> = ...
```
where these options would be passed to `Nullable` and that would use something like `options["optionalImpliesNullable"] extends true ? ... : ...` to determine where to add the null clause. That would grant some user choice in the checking, while keeping mostly backwards compatible.

Optionally, partial could be rolled up in that, although maybe you specifically don't want partial to appear like that.

**Comment by Lyoko-Jeremie** [comment]
i got the same error in all case.

```ts

export interface SysInfo {
    vLib: string;
    // ......
}


const SysInfoSchema: JSONSchemaType<SysInfo> = {
    type: 'object',
    properties: {
        vLib: {type: 'string', minLength: 1},
    },
    required: [
        'vLib',
    ],
    additionalProperties: false,
};
```

 what ever the `vLib` in or not in the `required` list , the follow error also omit on webstorm.


```
TS2322: Type '{ type: "string"; minLength: number; }' is not assignable to type '{ $ref: string; } | ({ type: "string"; minLength?: number; maxLength?: number; pattern?: string; format?: string; } & { [keyword: string]: any; $id?: string; $ref?: string; $defs?: { [x: string]: JSONSchemaType<Known, true>; }; ... 7 more ...; not?: Partial<...>; } & { ...; })'.
   Type '{ type: "string"; minLength: number; }' is not assignable to type '{ type: "string"; minLength?: number; maxLength?: number; pattern?: string; format?: string; } & { [keyword: string]: any; $id?: string; $ref?: string; $defs?: { [x: string]: JSONSchemaType<Known, true>; }; ... 7 more ...; not?: Partial<...>; } & { ...; }'.
     Property 'nullable' is missing in type '{ type: "string"; minLength: number; }' but required in type '{ nullable: true; const?: never; enum?: string[]; default?: string; }'.  
json-schema.d.ts(95, 5): 'nullable' is declared here. 
SysInfo.ts(41, 5): The expected type comes from property 'vLib' which is declared here on type 'PropertiesSchema<SysInfo>'
```



![2021-01-13 15_31_51-Window](https://user-images.githubusercontent.com/6566869/104420560-05d1a900-55b5-11eb-930c-15fe522db7be.png)
![2021-01-13 15_32_17-Window](https://user-images.githubusercontent.com/6566869/104420572-08cc9980-55b5-11eb-8aa5-84b4b50a2c65.png)


and only can add `nullable: true` to avoid this error notice.

![2021-01-13 15_33_35-Window](https://user-images.githubusercontent.com/6566869/104420533-fb171400-55b4-11eb-8447-f909c2d8c84c.png)

or use `// @ts-ignore` line by line.

![2021-01-13 15_37_04-Window](https://user-images.githubusercontent.com/6566869/104420696-3c0f2880-55b5-11eb-8c0f-6f58457ac8ff.png)

so, now i cannot have a non-nullable field, if i dont want the error notice or the ts-ignore.

but in other siide, the code compile well, i think this is only a type check system error.

---

i seems that the code is follow :

```ts
declare type Nullable<T> = undefined extends T ? {
    nullable: true;                  //  <====== maybe this need be `nullable?: true;` ?
    const?: never;
    enum?: (T | null)[];
    default?: T | null;
} : {
    const?: T;
    enum?: T[];
    default?: T;
};
```

---

i'm using ajv 7.0.3 , and webstorm 2020.3.1/2020.3 .

**Comment by Lyoko-Jeremie** [comment]
Oh, seems like https://github.com/ajv-validator/ajv/issues/1331#issuecomment-733926638 can help me.
but i working on a angular project, i dont known the side effect about that.

---

update:  this way not work. :(   
the error not change .

**Comment by Lyoko-Jeremie** [comment]
now i make a copy of `JSONSchemaType` from Ajv , the new code in follow:

i fix two place, the `RequiredMembers` and the `Nullable` , now all are ok.

```ts
/* eslint-disable @typescript-eslint/no-empty-interface */
export type SomeJSONSchema = JSONSchemaType<Known, true>

export type PartialSchema<T> = Partial<JSONSchemaType<T, true>>

type JSONType<T extends string, _partial extends boolean> = _partial extends true
    ? T | undefined
    : T

export type JSONSchemaType<T, _partial extends boolean = false> = (T extends number
    ? {
        type: JSONType<'number' | 'integer', _partial>
        minimum?: number
        maximum?: number
        exclusiveMinimum?: number
        exclusiveMaximum?: number
        multipleOf?: number
        format?: string
    }
    : T extends string
        ? {
            type: JSONType<'string', _partial>
            minLength?: number
            maxLength?: number
            pattern?: string
            format?: string
        }
        : T extends boolean
            ? {
                type: 'boolean'
            }
            : T extends [any, ...any[]]
                ? {
                // JSON AnySchema for tuple
                type: JSONType<'array', _partial>
                items: {
                    [K in keyof T]-?: JSONSchemaType<T[K]> & Nullable<T[K]>
                } & { length: T['length'] }
                minItems: T['length']
            } & ({ maxItems: T['length'] } | { additionalItems: false })
                : T extends any[]
                    ? {
                        type: JSONType<'array', _partial>
                        items: JSONSchemaType<T[0]>
                        contains?: PartialSchema<T[0]>
                        minItems?: number
                        maxItems?: number
                        minContains?: number
                        maxContains?: number
                        uniqueItems?: true
                        additionalItems?: never
                    }
                    : T extends Record<string, any>
                        ? {
                            // JSON AnySchema for records and dictionaries
                            // "required" is not optional because it is often forgotten
                            // "properties" are optional for more concise dictionary schemas
                            // "patternProperties" and can be only used with interfaces that have string index
                            type: JSONType<'object', _partial>
                            // "required" type does not guarantee that all required properties are listed
                            // it only asserts that optional cannot be listed
                            required: _partial extends true ? (keyof T)[] : RequiredMembers<T>[]
                            additionalProperties?: boolean | JSONSchemaType<T[string]>
                            unevaluatedProperties?: boolean | JSONSchemaType<T[string]>
                            properties?: _partial extends true ? Partial<PropertiesSchema<T>> : PropertiesSchema<T>
                            patternProperties?: { [Pattern in string]?: JSONSchemaType<T[string]> }
                            propertyNames?: JSONSchemaType<string>
                            dependencies?: { [K in keyof T]?: (keyof T)[] | PartialSchema<T> }
                            dependentRequired?: { [K in keyof T]?: (keyof T)[] }
                            dependentSchemas?: { [K in keyof T]?: PartialSchema<T> }
                            minProperties?: number
                            maxProperties?: number
                        }
                        : T extends null
                            ? {
                                nullable: true
                            }
                            : never) & {
    [keyword: string]: any
    $id?: string
    $ref?: string
    $defs?: {
        [Key in string]?: JSONSchemaType<Known, true>
    }
    definitions?: {
        [Key in string]?: JSONSchemaType<Known, true>
    }
    allOf?: PartialSchema<T>[]
    anyOf?: PartialSchema<T>[]
    oneOf?: PartialSchema<T>[]
    if?: PartialSchema<T>
    then?: PartialSchema<T>
    else?: PartialSchema<T>
    not?: PartialSchema<T>
}

type Known = KnownRecord | [Known, ...Known[]] | Known[] | number | string | boolean | null

interface KnownRecord extends Record<string, Known> {
}

type PropertiesSchema<T> = {
    [K in keyof T]-?: (JSONSchemaType<T[K]> & Nullable<T[K]>) | { $ref: string }
}

type RequiredMembers<T> = {
    // [K in keyof T]-?: undefined extends T[K] ? never : K                  // <=== change this
    [K in keyof T]-?: undefined extends T[K] ? K : never                    // <=== FIX to this
}[keyof T]

type Nullable<T> = undefined extends T
    ? {
        // nullable: true                  // <=== change this
        nullable?: true                    // <=== FIX to this
        const?: never // any non-null value would fail `const: null`, `null` would fail any other value in const
        enum?: (T | null)[] // `null` must be explicitly included in "enum" for `null` to pass
        default?: T | null
    }
    : {
        const?: T
        enum?: T[]
        default?: T
    }


```

if any other have face same issue like me, you can try to make a copy file of `JSONSchemaType.ts`, fix that like above , import this one instead of the Ajv versioin.

**Comment by erikbrinkman** [comment]
@epoberezkin do you have a comment on my suggestion from earlier? In short, I get the opinionatedness, and the reason for it, but I think it could be made more general. I'm happy to submit a PR to address it, but I want to make sure the general layout makes sense to you / other maintainers.

Thanks!

**Comment by epoberezkin** [comment]
> Aren't unions supported by oneOf, e.g. couldn't a union be written as oneOf([{type: "string"}, {type: "null"}]), or are you saying that unions are supported in ajv, but the typescript checking of appropriate validation is not available for unions, e.g. JSONSchemaType does not accurately break a union down into a schema type like oneOf

the latter - JSONSchemaType does not break unions

> optionalImpliesNullable

I'd rather we figure out how to manage unions - this may change design, and it may be more difficult once additional type parameters added...

**Comment by erikbrinkman** [comment]
Do you have thoughts as to what type of behavior you think should be supported? I've thought a little about what's feasible, and without the schema being tagged, it's not clear how best to resolve the union. I'm not sure there's a good way to say take:
`number | { val: string }` and make sure it's `anyOf: [ { type: "number" }, { type: "object", ... } ]`, but it might be feasible to make `JSONSchemaType` accept either `{ type: "number" }` or `{ type: "object", ... } ` and then have a schema type do something like `Schema<T> = { ... } | { anyOf: Schema<T>[] } | { oneOf: Schema<T>[] }`. With that kind of structure it may also be able to use some partial expansion of the keys to actually check a schema with oneOf or anyOf as part of the properties, but that's even more complicated than supporting just the verbose case as I've somewhat described.

One major downfall of this, is that it would allow someone to write `JSONSchemaType<A | B> = ( ... as JSONSchemaType<A>)` which seems like a bad mistake to not catch. However, without tagging, I'm not sure of a good way to get around it.

**Comment by epoberezkin** [comment]
@erikbrinkman what do you think should be done here after the union changes?

**Comment by erikbrinkman** [comment]
@epoberezkin I think the change I suggested, adding an extra parameter to the type makes sense and should be viable.

However, I'm using jtd now which has more explicit treatment of the difference between undefined an null, so I don't really care as much.

I'm happy to still put up a patch of you think it's useful, but given that I'm the only one who's complained, and I don't care anymore, it seems like the added work and complexity aren't justified.

**Comment by epoberezkin** [comment]
Thank you - will close it then - let's see what people ask for after all the changes to JSONSchemaType are released

**Comment by JamesJansson** [comment]
I feel like this is the breaking change that may thwart my type implementations. At an API level, sending an PUT request of  `{id: 123, a: 'hello'}` is VERY different to `{id: 123, a: 'hello', b: NULL}`. The second is clearing the field. Unfortunately there is no was to consistently represent the first because AJV forces you to accept a NULL in the field.

EDIT: I see v9 has it, thanks. When is the release on NPM?

**Comment by niklas-paro** [comment]
I'm running into issues with Ajv requiring `"nullable": true` for every non-required property as well. Considering copy-pasting https://github.com/ajv-validator/ajv/blob/v9/lib/types/json-schema.ts to my project for now as that seems to get around it. Thanks for the clue @JamesJansson.

**Comment by cwhitemaddox** [comment]
Hi there, so for where things stand today, is it possible to type a property (using `JSONSchemaType`) that can be absent (`undefined`) or a specific type, but is not allowed to be `null`?

For example, this works as expected:

```js
const a = {
  type: "object",
  properties: {
    field: { type: "string" },
  },
};

const ajv = new Ajv();

const is_valid = ajv.compile(a);

console.log(is_valid({ field: "asdf" })); // true
console.log(is_valid({ field: undefined })); // true
console.log(is_valid({})); // true
console.log(is_valid({ field: null })); // false
```

But if I then do this:

```ts
interface A {
  field?: string;
}

const a: JSONSchemaType<A> = {
  type: "object",
  properties: {
    field: { type: "string" },
  },
};

...
```

I get a type error for `const a`:
```
Type '{ type: "object"; properties: { field: { type: "string"; }; }; }' is not assignable to type 'UncheckedJSONSchemaType<A, false>'.
  The types of 'properties.field' are incompatible between these types.
    Type '{ type: "string"; }' is not assignable to type '{ $ref: string; } | (UncheckedJSONSchemaType<string | undefined, false> & { nullable: true; const?: null | undefined; enum?: readonly (string | null | undefined)[] | undefined; default?: string | ... 1 more ... | undefined; })'.
      Type '{ type: "string"; }' is not assignable to type '{ type: "string"; } & StringKeywords & { allOf?: readonly UncheckedPartialSchema<string | undefined>[] | undefined; anyOf?: readonly UncheckedPartialSchema<string | undefined>[] | undefined; ... 4 more ...; not?: UncheckedPartialSchema<...> | undefined; } & { ...; } & { ...; }'.
        Property 'nullable' is missing in type '{ type: "string"; }' but required in type '{ nullable: true; const?: null | undefined; enum?: readonly (string | null | undefined)[] | undefined; default?: string | null | undefined; }'.ts(2322)
```

I'm currently using ajv 8.11.0

**Comment by erikbrinkman** [comment]
@cwhitemaddox 
@epoberezkin can correct me, but unfortunately, I believe this is currently the case. The fix is already in the v9 branch, but since it's breaking, the fix won't come until v9. To get around this in the current version there are a few solutions, none of which are great, but which should unblock whatever you're doing:

1. If you don't need the complexities of JSONSchema, then the current JTD schema provides for this:
   ```const a: JTDSchemaType<A> = { optionalProperties: { field: { type: "string" } } }```
3. Otherwise you need to trick typescript. You can do this on a case by case basis by doing something like:
   ```
   const a: JSONSchemaType<A> = {
     type: "object",
     properties: {
       field: { type: "string" } as { type: "string"; nullable: true },
     },
   };
   ```

   alternatively you could declare a helper function like:
   ```
   function nullable<T>(inp: T): T & { nullable: true } {
     return inp as T & { nullable: true };
   }
   ```
   and then do:
   ```
   ...
   properties: {
     field: nullable({ type: "string" }),
   },
   ...
   ```
   which will work for arbitrarily complex types and just tells the compiler to ignore the missing nullable option.

**Comment by cwhitemaddox** [comment]
@erikbrinkman -- ah. Thanks -- this is helpful.

**Comment by joshstrange** [comment]
For anyone else like me who was confused:

If you want to define your Type like: 

```typescript
// ✅ 
type MyType {
  myProp: string | null;
}
```

And you want Ajv to correctly check it and allow a string or null like such:

```typescript
const schema: JSONSchemaType<GetParams> = {
  type: 'object',
  properties: {
    myProp: {type: 'string', nullable: true}
  },
  required: ['myProp'], 
  additionalProperties: false
};
```

But don't want `JSONSchemaType` complaining and forcing you to define your Type like this:

```typescript
// 👎 
type MyType {
  myProp?: string | null;
}

// OR

// 👎 
type MyType {
  myProp?: string;
}
```

Then you need the use the inverse of @erikbrinkman proposed (though it was very helpful in pointing me in the right direction). You'll want something like this:

```typescript
export const nullable = <T>(input: T): T => {
  return {
    ...input,
    nullable: true
  } as T ;
}
```

And you'll use it like this:

```typescript
const schema: JSONSchemaType<GetParams> = {
  type: 'object',
  properties: {
    myProp: nullable({type: 'string'}), // <- Here is the change
  },
  required: ['myProp'], // Does not have to be required, but it will work as expected
  additionalProperties: false
};
```

With all that in place the following will be true:

```typescript
const ajv = new Ajv();
const validate = ajv.compile(schema);

validate({}); // False, `myProp` is missing (assuming you set it as required)
validate({myProp: 123}) // False, wrong type
validate({myProp: null}) // True
validate({myProp: 'my string'}) // True
```

And your data (that you pass into `validate`) will be correctly typed as:

```typescript
data.myProp // <- Type: string | null;
```

I hope this helps someone else. Personally I despise using `undefined` in place of `null` (they are very different) especially when passing data between client<->server so I was very glad to find a way to wrangle this library to handle all my validation while also using types the way that works best for me.
