### ISSUE TITLE
Unicode escapes in regex patterns are marked invalid as of Ajv v7

### ISSUE THREAD

**Issue by mattiekat** [ajv-validator/ajv#1379]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v7.0.3, yes.

**Ajv options object**

All options are default, `ajv-formats` added the the `avj` instance.

**JSON Schema**

```json
{
  "$id": "http://example.com/util/myschema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Example",
  "type": "string",
  "pattern": "\\x{00a1}"
}
```

**Sample data**
Not relevant.

**Your code**
Tested with ts-node, I am simply reproducing in the shell.

```ts
import Ajv from 'ajv'

const schema = {
  "$id": "http://example.com/util/myschema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Example",
  "type": "string",
  "pattern": "\\x{00a1}"
}

const ajv = new Ajv()
ajv.compile(schema)
```

**Validation result, data AFTER validation, error messages**
> Uncaught SyntaxError: Invalid regular expression: /\x{00a1}/: Invalid escape

**What results did you expect?**
No compilation error, this works with v6 of ajv and `new RegExp("\\x{00a1}")` works without issues.

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
I need to check the details but I think it’s likely to be an expected change (that needs to be added to release notes) - from v7 the patterns are treated as having “u” flag - it’s how it is required by the spec.

So the pattern in your schema is equivalent to `new RegExp("\\x{00a1}", "u")` that might be not valid - need to check it.

**Comment by epoberezkin** [comment]
> new RegExp("\\x{00a1}", "u")

Uncaught SyntaxError: Invalid regular expression: /\x{00a1}/: Invalid escape

As I thought, this regular expression is invalid when used with "u" flag - please check the docs on MDN how to change it.

**Comment by darlanalves** [comment]
@epoberezkin I bumped into a similar issue today, related to the 'u' flag.

This flag is not supported by any IE browser version.
Is it by design that AJV 7.x does not support IE?

Otherwise, is there a way we could make this flag optional, e.g. if es5 is enabled in AVJ options?

https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/code.ts#L98

**Comment by epoberezkin** [comment]
Adding option to create regular expressions without u flag is ok - need to think what to name it.

It should be a separate issue - PR is welcome.

**Comment by darlanalves** [comment]
Cheers! 
I opened a new ticket with more details:

https://github.com/ajv-validator/ajv/issues/1474
