### ISSUE TITLE
Ajv class doesn't have constructor

### ISSUE THREAD

**Issue by lygstate** [ajv-validator/ajv#1383]
```
src\schema.ts(10,14): error TS2351: This expression is not constructable.
  Type 'typeof import("E:/CI-Cor-Ready/study/vscode-cmake-tools/node_modules/ajv/dist/ajv")' has no construct signatures.
```

**Are you going to resolve the issue?**
Yeap

**Comment by epoberezkin** [comment]
See comment in the PR - I think it might be a problem of compatibility with some tool? Constructors in subclasses are optional I think

**Comment by lygstate** [comment]
Thanks you are correct,

```
 src/schema.ts |  6 +++---
 
diff --git a/src/schema.ts b/src/schema.ts
index 5b7027c..fc798d7 100644
--- a/src/schema.ts
+++ b/src/schema.ts
@@ -1,11 +1,11 @@
-import * as ajv from 'ajv';
+import ajv, { ValidateFunction } from 'ajv';
 import * as path from 'path';
 
 import {fs} from './pr';
 import {thisExtensionPath} from './util';
 
-export async function loadSchema(filepath: string): Promise<ajv.ValidateFunction> {
+export async function loadSchema(filepath: string): Promise<ValidateFunction> {
   const schema_path = path.isAbsolute(filepath) ? filepath : path.join(thisExtensionPath(), filepath);
   const schema_data = JSON.parse((await fs.readFile(schema_path)).toString());
-  return new ajv({allErrors: true, format: 'full'}).compile(schema_data);
+  return new ajv({allErrors: true}).compile(schema_data);
 }

```

Does the format options are removed in new version?

**Comment by epoberezkin** [comment]
Correct, because this is now configured via the options in ajv-formats (all formats are moved there).

Is there a way to stop the tools complaining about no constructor in subclass?

**Comment by lygstate** [comment]
> Correct, because this is now configured via the options in ajv-formats (all formats are moved there).
> 
> Is there a way to stop the tools complaining about no constructor in subclass?

not tooling problem，import syntax changed

-import * as ajv from 'ajv';
+import ajv, { ValidateFunction } from 'ajv';

**Comment by epoberezkin** [comment]
Thank you!

**Comment by tlanclos** [comment]
I may be missing something obvious, but there still seems to be issues with Ajv imports in TypeScript (e.g. the [example](https://npm.runkit.com/ajv) fails to execute with "TypeError: Ajv is not a constructor"). It seems to be specifically related to v7. v6 seems to work fine.

**Comment by epoberezkin** [comment]
Yes - need to be updated indeed - the import has changed. See the example in Getting started.

**Comment by tlanclos** [comment]
Cool, got it working. ty :)
