### ISSUE TITLE
v7: addKeyword custom error code example not work

### ISSUE THREAD

**Issue by kpkonghk01** [ajv-validator/ajv#1385]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
7.0.3 (it is the latest now)

**Ajv options object**
```javascript
{
  $data: true,
}
```

**JSON Schema**
```javascript
{
  type: 'object',
  properties: {
    evenNum: {
      type: 'number',
      even: true,
    },
  },
}
```

**Sample data**

```javascript
{
  evenNum: 1,
}
```

**Your code**

```javascript
'use strict';

const { default: Ajv, _ } = require('ajv');

const validator = new Ajv(options);

validator
  // copy from doc https://github.com/ajv-validator/ajv/blob/master/docs/keywords.md
  .addKeyword({
    keyword: 'even',
    type: 'number',
    schemaType: 'boolean',
    code(cxt) {
      const { data, schema } = cxt;
      const op = schema ? _`!==` : _`===`;

      cxt.fail(_`${data} %2 ${op} 0`);
    },
  });

validator.validate(schema, data);

console.log(validator.errors);

```

**Validation result, data AFTER validation, error messages**

```javascript
[
  {
    keyword: 'even',
    dataPath: '/evenNum',
    schemaPath: '#/properties/evenNum/even',
    params: {},
    message: 'should pass "even" keyword validation'
  }
]
```

**What results did you expect?**
```
[
  {
    keyword: 'even',
    dataPath: '/evenNum',
    schemaPath: '#/properties/evenNum/even',
    params: {},
    message: '1 %2 !== 0'
  }
]
```

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
Sorry, I am not sure what is wrong here. `evenNum: 1` is not even, so it fails validation - that is how it should be.  Can you please clarify?

**Comment by epoberezkin** [comment]
I think I understand what you expected. The tagged template literal that you pass to `cxt.fail` is not an error message, it is an expression (tagged literal actually returns instance of `_Code` class, but you should not be using constructor directly) that will be evaluated during validation to establish that the validation failed.

The generated code would look like `data1 %2 !== 0` (it can be some other index with `data` - it's just a name that is unique within the function).

You can change error messages providing `error` object as part of keyword definition - see the same doc, keywords defined in vocabularies folder or in some of the keywords in ajv-keywords package.
