### ISSUE TITLE
Update repo description to remove draft-04

### ISSUE THREAD

**Issue by Relequestual** [ajv-validator/ajv#1393]
I note that draft-04 is no longer supported, but it's still included in the description.

draft-04 should also be removed from the JSON Schema implementations list for ajv.

🎉

**Comment by epoberezkin** [comment]
v6 does support draft-04 - why should it be removed?

**Comment by Relequestual** [comment]
I assumed v6 would no longer be supported. I see it's supported till end of Feb 2021.

How about an error message, other than "schema not found" when someone tries to use draft-04 via $schema in v7?

It's not super obvious what the problem is: https://stackoverflow.com/questions/65726164/how-to-use-ajv-with-dependent-json-schemas

**Comment by epoberezkin** [comment]
Yes - I will support v6 for critical security issues beyond this date, but even lack of library support does not automatically mean that the library itself does not support a specification - it may be no longer developed, but it can still be used...

It is a big philosophical debate whether to be useful software needs to be actively developed or supported - I am on the side that believes that a piece of software can (and should) reach the point of being completed at some point and not require any changes and support beyond that point.

**Comment by epoberezkin** [comment]
https://github.com/ajv-validator/ajv/issues/1398
