### ISSUE TITLE
Throw runtime error

### ISSUE THREAD

**Issue by zdiary** [ajv-validator/ajv#1396]
ajv version: 7.0.3

Here is the error message:

```
Error compiling schema, function code: const schema2 = scope.schema[2];const schema1 = scope.schema[1];return function validate1(data, {dataPath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(!(((typeof data == "number") && (!(data % 1) && !isNaN(data))) && (isFinite(data)))){validate1.errors = [{keyword:"type",dataPath,schemaPath:"#/definitions/nonNegativeInteger/type",params:{type: "integer"},message:"should be integer"}];return false;}if((typeof data == "number") && (isFinite(data))){if(data < 0 || isNaN(data)){validate1.errors = [{keyword:"minimum",dataPath,schemaPath:"#/definitions/nonNegativeInteger/minimum",params:{comparison: ">=", limit: 0},message:"should be >= 0"}];return false;}}validate1.errors = vErrors;return errors === 0;}
```

My code([Refer to official documents](https://github.com/ajv-validator/ajv#getting-started)):

```typescript
import Ajv, {JSONSchemaType, DefinedError} from "ajv"

const ajv = new Ajv()

type MyData = {foo: number}

const schema: JSONSchemaType<MyData> = {
  type: "object",
  properties: {
    foo: {type: "number", minimum: 0},
  },
  required: ["foo"],
  additionalProperties: false,
}

const validate = ajv.compile(schema)
```

What suggestions do you have for this? 
Thank you

**Comment by epoberezkin** [comment]
I cannot reproduce it I am afraid: https://runkit.com/esp/6007447942d546001a48a2a0

This schema does compile... The issue can be in some specific typescript settings, but difficult to say without having a full set up. Can you share maybe a compiled JS code via runkit.com so I can see the issue.

**Comment by zdiary** [comment]
Thank you for your answer. I found that this problem is caused by `use strict`. Some code in the project, such as compile, uses code incompatible with strict mode when generating compiler functions

**Comment by zdiary** [comment]
I found the problem because Wechat Mini-program does not support `eval` and `new function`, but the error reported is very misleading: `Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at A.s`
[reason](https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/js-support.html)
I'm very sorry for the trouble~

**Comment by vvenv** [comment]
@zdiary what's your solution at last? just stop using AJV  in Wechat Mini-program?

**Comment by zdiary** [comment]
@crossjs 是的，这个确实没办法解决，只好在微信小程序里停用了，有个专门针对此类问题的库：[eval5](https://github.com/bplok20010/eval5)，不过我没有尝试，你可以试一下~

**Comment by epoberezkin** [comment]
A possible solution is to precompile schemas to avoid compiling in run time

**Comment by ZenwalkerD** [comment]
> A possible solution is to precompile schemas to avoid compiling in run time

You mean to say that load the schema document to a variable like
var a = JSON.stringfy(schema.json)?

**Comment by RiddhiShah23** [comment]
How to implement precompiled schema ?

**Comment by epoberezkin** [comment]
https://ajv.js.org/standalone.html

**Comment by nirmid** [comment]
Hey! i'm facing the same issue, i'm getting it only when i build the react app and serving it as static files from the backend. Is there another solution beside precompiling the schema ? Using Ajv 8.17.1
