### ISSUE TITLE
ajv@^7.0.0 fails to compile JSON Schemas with "email" format

### ISSUE THREAD

**Issue by mstaicu** [ajv-validator/ajv#1397]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

^7.0.0

**Ajv options object**

```javascript
import Ajv from 'ajv';

const ajv = new Ajv();

const validateRequestBody = (bodySchema: JSONSchema7) => (
  req: Request,
  _: Response,
  next: NextFunction,
) => {
  // This blows up with the schema below
  const validate = ajv.compile(bodySchema);

  const isPayloadValid = validate(req.body);

  isPayloadValid
    ? next()
    : next(new ValidationError({ invalid_params: validate.errors }));
};
```

**JSON Schema**

```jsonc
import { JSONSchema7 } from 'json-schema';

const signupSchema: JSONSchema7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Signup request payload',
  type: 'object',
  required: ['email', 'password'],
  properties: {
    email: {
      type: 'string',
      format: 'email',
      description: 'User account email address',
    },
    password: {
      type: 'string',
      minLength: 1,
      description: 'Keys to the kingdom',
    },
  },
};
```

**Sample data**

```jsonc
{
  email: "hello@hello.com",
  password: "cookie"
}
```

**What results did you expect?**

This works in < ^7.0.0, i.e. last working version is 6.12.6

**Comment by mstaicu** [comment]
Also, please feel free to correct my understanding of how JSON Schemas should be structured with regards to my use case, would gladly appreciate

**Comment by epoberezkin** [comment]
Formats are in ajv-formats package - https://github.com/ajv-validator/ajv-formats

**Comment by mstaicu** [comment]
Thank you!

**Comment by paul-uz** [comment]
@epoberezkin can I ask why JSON API valid formats were removed from AJV?

**Comment by epoberezkin** [comment]
There are two main reasons - see [this post](https://www.poberezkin.com/posts/2020-11-14-ajv-time-to-migrate-to-version-7.html):

> The first reason was that JSON Schema specification draft-2019-09 made format validation optional. The second, and more important, reason is that semantic string validation is complex, and it is impossible to find the right balance between correctness, performance and complexity that is acceptable to all users and applications. While you still can easily add the formats provided by ajv-formats package, it is up to you to assess their suitability and, if needed, to replace with other implementations that are appropriate for your use cases.

In short - to encourage users to choose format definitions, and not to rely of the default definitions previously bundled with ajv - their suitability has to be assessed in the context of your application.

**Comment by epoberezkin** [comment]
Even something that seems as "simple" as datetime format is non-trivial: ajv-formats (and ajv previously) stops at allowing "leap seconds" on any day at 23:59:60 (and there is actually a bug that needs fixing - it doesn't account for the fact that this is UTC time, but the timezone can be different), but some applications may need to only allow actual past and future announced "leap seconds".

Email validation is much more complex - some application may want to validate domains asynchronously - it's a rabbit hole to try to cater for all usage scenarios in a validation library.

**Comment by paul-uz** [comment]
@epoberezkin thank you for the explaination!
