### ISSUE TITLE
format: 'date-time', can you set a time range？

### ISSUE THREAD

**Issue by wpbjiuy** [ajv-validator/ajv#1400]
`{
    type: 'string',
    format: 'date-time',
    min: '2010-01-01',
    max: '2020-01-01',
    default: new Date()
  }`

**Comment by epoberezkin** [comment]
you can use formatMinimum / formatMaximum keywords from ajv-formats to set date/time range and dynamicDefaults keyword from ajv-keywords to make current date/time the default.
