### ISSUE TITLE
Disallow properties not in schema

### ISSUE THREAD

**Issue by paul-uz** [ajv-validator/ajv#1404]
I can't seem to find anything about this in the documentation.

Is there a way to throw a validation error if a property not in the schema is present in the payload?

eg if `uuid` is "disallowed" and its present in the JSON being validated, it errors as invalid

**Comment by epoberezkin** [comment]
Please read JSON schema specification or docs/json-schema.md . For this particular problem you need “required” keyword

**Comment by paul-uz** [comment]
@epoberezkin 'required' is the wrong keyword. That defines properties that must be included. I want to make sure no extra properties not in the schema are rejected.

Turns out I needed `additionalProperties: false`
