### ISSUE TITLE
How to make AJV output error information using the standard official structure?

### ISSUE THREAD

**Issue by jviotti** [ajv-validator/ajv#1408]
I would like to validate a schema and obtain the results in the various output structures specified in: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4.

I might be missing something, but the docs don't seem to mention how to use these output structures and the `.errors` array does not match that format either.

**Comment by epoberezkin** [comment]
It is not supported yet. Possibly in v8 but more likely in v9. There are some substantial changes compared to how Ajv historically reported errors, not only error object property name changes.

**Comment by kiendang** [comment]
Hi will there be support for annotation outputs too?

**Comment by epoberezkin** [comment]
Probably best to make a separate issue and see how much interest is there to have annotations collection. It’s not in immediate plans.

**Comment by jviotti** [comment]
Closing stale issues
