### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by clydee-geng** [ajv-validator/ajv#1412]
error
![image](https://user-images.githubusercontent.com/39870180/105965349-41449b00-60be-11eb-9c4b-0af0e9124782.png)

using
```
import Ajv from 'ajv';

export const deepClone = (obj) => {
  console.log('深复制');
  return JSON.parse(JSON.stringify(obj));
};

export const checkJSON = (value, schema) => {
  const ajv = new Ajv();
  const validate = ajv.compile(schema);
  const valid = validate(value);
  if (!valid) return validate.errors;
  return true;
};
```

**Comment by epoberezkin** [comment]
this is not an Ajv issue - you need to change configuration of your build process.

Possibly the issue is that Ajv is compiled to JS 2018, and you need to recompile typescript to an earlier target to be compatible with your build/environment.

**Comment by clydee-geng** [comment]
@epoberezkin Solved it, it was my fault, thank you
