### ISSUE TITLE
Bug related to combining `removeAdditional` with `oneOf`

### ISSUE THREAD

**Issue by cyberixae** [ajv-validator/ajv#1420]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

ajv 7.0.3

**Ajv options object**

```javascript
var options = {
    allErrors: true,
    removeAdditional: 'failing',
}
```

**JSON Schema**

```json
var schema = {
  "$id": "https://example.com/ajv-test.json",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "foo": { "const": "foo" }
      },
      "required": ["foo"],
      "additionalProperties": false,
    },
    "bar": {
      "type": "object",
      "properties": {
        "bar": { "const": "bar" }  
      },
      "required": ["bar"],
      "additionalProperties": false,
    }
  },
  "oneOf": [
    { "$ref": "#/definitions/foo" },
    { "$ref": "#/definitions/bar" }
  ]
};
```

**Sample data**

```json
var data = {
  "bar": "bar"
};
```

**Your code**

https://runkit.com/cyberix/ajv-issue

```javascript
var Ajv = require('ajv').default;
var ajv = new Ajv(options)
var validate = ajv.compile(schema);

console.log(validate(data));
console.log(validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
false
[
  {
    keyword: 'required',
    dataPath: '',
    schemaPath: '#/definitions/foo/required',
    params: { missingProperty: 'foo' },
    message: "should have required property 'foo'"
  },
  {
    keyword: 'required',
    dataPath: '',
    schemaPath: '#/definitions/bar/required',
    params: { missingProperty: 'bar' },
    message: "should have required property 'bar'"
  },
  {
    keyword: 'oneOf',
    dataPath: '',
    schemaPath: '#/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
```

**What results did you expect?**

```
true
null
```

The above result is what you get with input `{ "foo": "foo" }` but `{ "bar": "bar" }` fails for some reason. The schema is intended to be symmetric but the order of sub schemas is `oneOf` seems to affect validation behaviour.

**Are you going to resolve the issue?**

Not right now, maybe one day, who knows.

**Comment by epoberezkin** [comment]
This is not a bug, this is based on how additionalProperties is defined - local to the schema object. So the order of subschemas is important here - because "foo" is the first, it removes "bar".

"removeUnevaluated" option (#1346) will work as you expect in this scenario - it's not complete yet though.

Also see this doc: https://github.com/ajv-validator/ajv/blob/master/docs/faq.md#why-the-validation-fails-when-i-use-option-removeadditional-with-the-keyword-anyofetc

**Comment by cyberixae** [comment]
@epoberezkin Thank you for the fast response. I'm the main author of another JSON schema validator [iotsfjs](https://github.com/maasglobal/io-ts-from-json-schema). I'm fully aware of the problem you are describing but I think it is a different problem. The page you linked discusses how `additionalProperties` is supposed to be handled when it is at the *same level* as `oneOf`. However, my example talks about a situation where two schemas are combined with `oneOf` but both of those sub schemas have a separate and *complete* object definition ( `additionalProperties` together with `type` and `properties` ). My example would not work with `allOf` since then the branches would be mutually exclusive. However, `oneOf` should avoid the mutual exclusion by evaluating the branches separately.

You are saying that `oneOf` is supposed to work like a pipe, passing the output of the first validator to the next. I find it possible that the JSON Schema specification doesn't discus this topic at all since it probably expects the input to immutable. Since you are mutating the input, I believe you should pass a separate copy of the input to each branch of `oneOf`. This way the handling of `additionalProperties` would be "local to the schema object" in the example I provided. Each one of the branches would then remove properties that are additional in their context and the `oneOf` combinator would then pick the correct set of removed properties based on which copy of the schema got selected while validating each one of them. The `allOf` should probably continue to be a pipe since that is supposed to accumulate all listed validators.

**Comment by epoberezkin** [comment]
This approach is possible, but it is not how it is implemented - making a copy of the data for each branch is at least expensive, but in a general case not possible (ajv can be/is used to validate arbitrary data structures, not only plain JS objects)...

There are different approaches to constructing [discriminated] unions that produce more predictable results and errors, other than oneOf keyword - e.g. if/then/else, non-standard select from ajv-keywords, trying to make oneOf work with additionalProperties is a dead end that even JSON Schema abandoned by introducing unevaluatedProperties in 2019-09...

**Comment by cyberixae** [comment]
The `unevaluatedProperties` and `removeUnevaluatedProperties` sound good but I don't think they will properly solve this issue. Consider the following response format providing either result or error information. In TypeScript this pattern of having a constant `kind` field to distinguish between different object shapes is the [recommended](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) way of distinguishing between different types of objects.

```javascript
var schema = {
  "$id": "https://example.com/ajv-test.json",
  "definitions": {
    "result": {
      "type": "object",
      "properties": {
        "kind": { "const": "result" },
        "value": { "type": "number" }
      },
      "required": ["kind", "value"],
      "additionalProperties": false,
    },
    "err": {
      "type": "object",
      "properties": {
        "kind": { "const": "err" },
        "reason": { "type": "string" }
      },
      "required": ["kind", "reason"],
      "additionalProperties": false,
    }
  },
  "oneOf": [
    { "$ref": "#/definitions/result" },
    { "$ref": "#/definitions/err" }
  ]
};
```

The above schema would match the following object as a valid input of kind _result_. However, the field `reason` has nothing to do with an object of kind _result_ and should be deleted when `deleteAddtitionalProperties` is enabled. However, I imagine it would *not* be deleted by `deleteUnevaluatedProperties` since the field `reason` *is* evaluated as part of finding the correct format for the input object.

```
var data = {
  kind: 'result',
  value: 42,
  reason: 'ultimate answer'
}
```

**Comment by epoberezkin** [comment]
Please read the docs for unevalutedProperties - it solves this problem. It would not be used in each subschema but only on the top level.

**Comment by epoberezkin** [comment]
Instead of additionalProperties keyword
