### ISSUE TITLE
$schema keyword not supported

### ISSUE THREAD

**Issue by Sleepful** [ajv-validator/ajv#1432]
Simple, I can't use `$schema`:
```json
{
  "$id": "...",
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "title": "Event",
  "type": "object",
  "properties": {}
}
```
Error:
```
  message: 'no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"',
```
ajv@6.12.4

https://json-schema.org/understanding-json-schema/reference/schema.html

**Comment by Sleepful** [comment]
also `"$schema": "..."` gives weird errors with `"require"`

**Comment by epoberezkin** [comment]
Draft 2019-09 is supported in ajv v7, you cannot use it in v6. Your specific schema should work in draft-07 though - so you need to change $schema to point to draft-07 metaschema.

**Comment by Sleepful** [comment]
@epoberezkin I'm still getting the error after updating to `ajv@7.0.4` :(

```
$ npm list ajv

├── ajv@7.0.4
├─┬ eslint@6.8.0
│ ├── ajv@6.11.0
│ └─┬ deps
│   └── ajv@6.11.0
└─┬ moreDeps
  └── ajv@6.12.4
```

Same schema `event.json`:
```json
{
  "$id": "...",
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "title": "Event",
  "type": "object",
  "properties": {}
}

```

And I import AJV like this:

```ts
import Ajv from 'ajv/dist/2019'
import EventSchema from 'schema/event.json'

...

    const ajv = new Ajv()
    const validate = ajv.compile(EventSchema) // Error! 'no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"'
```

Message:
```
  message: 'no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"',
  stack: 'Error: no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"\n' +
    '    at Ajv2019.validate (.../node_modules/ajv/lib/core.ts:304:21)\n' +
```

**Comment by Sleepful** [comment]
Found the issue

```diff
< "$schema": "http://json-schema.org/draft/2019-09/schema#",
> "$schema": "https://json-schema.org/draft/2019-09/schema#",
```

**Comment by Sleepful** [comment]
You might want to consider this a bug, as it doesn't allow the schema ref [from the spec](https://json-schema.org/understanding-json-schema/reference/schema.html) (it has `http` *not* `https`)

**Comment by epoberezkin** [comment]
This is actually the mistake on their website - it has changed to https in draft-2019-09 - see here for example: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4

**Comment by epoberezkin** [comment]
There is issue + PR there:

https://github.com/json-schema-org/understanding-json-schema/issues/134

We found the culprit!
