### ISSUE TITLE
 Getting compile time error  while using Ajv with angular version 9.

### ISSUE THREAD

**Issue by PParshive** [ajv-validator/ajv#1436]
Hi Team,
Getting compile time error by using ng serve. I am using following version in my project
![Screenshot (20)](https://user-images.githubusercontent.com/75675307/107245696-70abbe00-6a55-11eb-8222-9a759c704f36.png)
 :
 "dependencies": {
    "@angular/animations": "~9.0.7",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7"",
    "ajv": "^7.0.4",
    "ang-jsoneditor": "^1.10.3",
    "bootstrap": "^4.5.2",
    "crypto-js": "^4.0.0",
    "jsoneditor": "5.19.2",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.19.16",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }

Screenshot already uploaded. I am struck here, please tell me how to solve this problem with angular 9 in my project.

**Comment by epoberezkin** [comment]
I don't think I can help with using Angular 9, also I am not sure what exactly is imported.

I can suggest reviewing Angular on how to configure the project and use dependencies in it.

If you cannot resolve the issue, please resubmit as "compatibility" issue type and include the link to the minimal repository with as few dependencies as possible that reproduces the problem - try to reproduce the problem with a clean angular project installation and installing nothing other than Ajv.

**Comment by stayingcool** [comment]
I have this issue as well. 

Due to lack of time, I have installed v6 and I'm able to use this library!
`npm i ajv@6.12.6`

If someone got it working on v7 with Angular, please share your solution as well.

**Comment by epoberezkin** [comment]
I would like to understand the issue. Setting up a minimal repo to demonstrate the issue would help - please submit another issue answering all questions in “compatibility” template.
