### ISSUE TITLE
Warn about non json-schema object

### ISSUE THREAD

**Issue by safqwf** [ajv-validator/ajv#144]
The following code returns true. I would expect to get an error on this by default.

```
var Validator = require('ajv');
var validator = Validator();
var validate = validator.compile({ 'yahooo': 'blaaaa' });
var isValid = validate({ 'blabla': 'bla' });
// isValid -> true
```

**Comment by epoberezkin** [comment]
Additional properties are allowed in schemas. Your schema has no defined validation keywords and any data is valid according to such schema. So this is a correct behaviour.

**Comment by safqwf** [comment]
Data is valid, but the schema is not correct. This schema doesn't have any of the following: 'type', 'definitions', 'properties'. Based on that information schema validator can warn the library user that he's doing wrong.

**Comment by epoberezkin** [comment]
None of these properties are required for the schema to be correct. `{}` is a valid schema according to spec.

**Comment by epoberezkin** [comment]
You can validate the schema against your own meta-schema if you want to require these properties.

**Comment by safqwf** [comment]
I'm not talking about the spec, but about the non-sense `{}` schema. Why would someone validate something against an empty schema? That may be only if the library user has some nasty bugs in the code, and schema validator can warn about such. This is definitely not a bug, but a suggestion to improve the UX of the lib.

**Comment by epoberezkin** [comment]
I will think about it. There are many cases when empty schema is used, so it is not non-sense. If you want to do additional validation of schemas the solution already exists - creating and using meta-schemas.

At the moment I don't think it should be a part of the library, but I will think about an option to warn on some missing properties in top level schemas.

**Comment by epoberezkin** [comment]
See #90 for example - you now can supply your own default meta-schema that would prevent what you consider invalid schemas from passing validation.

**Comment by safqwf** [comment]
Great, thanks!
