### ISSUE TITLE
https $schema not supported

### ISSUE THREAD

**Issue by davidebriani** [ajv-validator/ajv#1450]
Using ajv 6.7.0, with the schema

```json
{
        "$id": "https://json-schema.org/draft-07/schema",
        "$schema": "https://json-schema.org/draft-07/schema",
        "additionalProperties": false,
        "properties": {},
        "title": "SomeTitle",
        "type": "object"
      }
```

ajv complains with the error `no schema with key or ref "https://json-schema.org/draft-07/schema"`.
The error does not occur replacing `https` with `http` in the uri.
Is `https` not supported?

**Comment by epoberezkin** [comment]
Yes, this is per spec - the correct URI for draft-07 meta-schema is with http (it changed to https with draft-2019-09)

**Comment by epoberezkin** [comment]
these URIs are not used to download anything, they are just identifiers.

**Comment by noelleleigh** [comment]
I should note that the JSON Schema website itself uses HTTPS URLs in its meta-schema links, [even for Draft-07](https://json-schema.org/specification-links.html#draft-7).

**Comment by epoberezkin** [comment]
Correct, but the schema in those files does not have https.

Possibly Ajv could just accept both http and https for all metaschemas, the transition from http in draft7 to https in draft2019 causes some confusion...
