### ISSUE TITLE
How to validate every type of object inside an array

### ISSUE THREAD

**Issue by aiamjay415** [ajv-validator/ajv#1451]
**What version of Ajv you are you using?** 6.12.5

**What problem do you want to solve?** 
validate every object inside a array, those objects are in different types

**What do you think is the correct solution to problem?**
I don't know

**Will you be able to implement it?**
my implementation:

```
// array object definition
export default {
  type: "array",
  items: {
    "anyOf": [
      typeOne,
      typeTwo,
    ],
  },
}

// type one defination:
typeOne = {
    type: 'object',
    required: ['lat', 'lng'],
    properties: {
      lat: {
      type: 'number',
    },
    lng: {
      type: 'number',
    },
  },
}
// type two definition:
typeTwo = {
  type: 'object',
  required: ['x', 'y', 'z'],
  properties: {
    x: {
      type: 'number',
    },
    y: {
      type: 'number',
    },
    z: {
      type: 'number',
    },
  },
}

```

**Comment by aiamjay415** [comment]
When there are two type objects in array, it will return true, if one of two is valid, and the other is invalid.

**Comment by epoberezkin** [comment]
Sorry l, I do not understand what the problem is, the schemas look valid. Please add the full code sample, the result you receive and the result you expect/need.

**Comment by aiamjay415** [comment]
Sorry for the confusion, what I want to do is that:
I have an array, which contains a lot of objects in it. Some objects are typeOne. Some are typeTwo. I want to validate all types of objects inside this array.

**Comment by aiamjay415** [comment]
"Anyone " keyword is that when any object inside this array is valid typeOne or valid typeTwo, it will stop checking others. But I want to check all objects inside this array.

**Comment by epoberezkin** [comment]
what makes you think it would stop validating other items in the array? I would validate all items to be valid against either schema. Depending on the option allErrors it may stop if one item is invalid, but it would validate all of them otherwise.

**Comment by what2eat2night** [comment]
The reason is that I want to use ajv like the following:
`const ajv = new Ajv({useDefaults: true, coerceTypes: true})`
I want to inject and correct each items in all types.
I do provide default values for all properties in each type.
But I only get type-one items corrected and assigned default value for missing properties,
there is nothing changed in type-two items.

**Comment by epoberezkin** [comment]
Please submit the full code sample of what you do and how is it different. Defaults are ignored inside anyOf, coercion works but it has to be used carefully - ajv doesn’t know in advance which branch is valid, there is no tag to discriminate on. You can consider using it/then/else in schema.

**Comment by aiamjay415** [comment]
how to work inside anyof, or is there any other solution to replace anyof
so that defaults works with any items in array

**Comment by epoberezkin** [comment]
As I wrote, if/then/else might work - please review the docs
