### ISSUE TITLE
The format type of 'email' validates for non email regex formats

### ISSUE THREAD

**Issue by asthikwow** [ajv-validator/ajv#1465]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.12.4
**Ajv options object**

```javascript

```

**JSON Schema**
Schema object:
username: {
      type: ['string'],
      format: 'email',
      maxLength: 30,
    },

```json

```

**Sample data**
data1 - userstring
data2 - user123@test.com
data3 - user@test

ajv successfully validates data2 as a valid email format and data1 as invalid one. But for data3 sample, it passes the validation instead it should have not allowed as the entry does not contain both the '@' and '.' character in it.
<img width="257" alt="ajv-git-data1" src="https://user-images.githubusercontent.com/72003560/108854701-4274d380-763c-11eb-91cf-d333b8fb3fa0.PNG">
<img width="258" alt="ajv-git-data2" src="https://user-images.githubusercontent.com/72003560/108854708-430d6a00-763c-11eb-8647-cafbd4abe18b.PNG">
<img width="261" alt="ajv-git-data3" src="https://user-images.githubusercontent.com/72003560/108854711-43a60080-763c-11eb-9c6f-c7e0ad12fd64.PNG">

```json

```

**Your code**

```javascript

```

**Validation result, data AFTER validation, error messages**

```

```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
You didn’t send Ajv options or code sample, but most likely you are using “fast” format mode - this is the default in v6.

With “full” format mode - see options and docs for v6 - would use more stringent regular expression.

In ajv v7 formats are split in a separate package - it’s important to evaluate if they work for your use case and consider using 3rd party parsers/validators - they can be hooked to formats in schema via addFormat method.

Please note that ajv v6 will be only supported for security issues after the end of February.
