### ISSUE TITLE
enum doesn't play well together with nullable

### ISSUE THREAD

**Issue by lehni** [ajv-validator/ajv#1471]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

v7.1.1, latest

**Ajv options object**

```js
{
  strict: false,
  allErrors: true,
  ownProperties: true,
  passContext: true,
  useDefaults: true,
  validateSchema: true
}
```

**JSON Schema**

```json
const schema = {
  "$id": "test",
  "properties": {
    "myEnum": {
      "type": ["string"],
      "nullable": true,
      "enum": [
        "one",
        "two",
        "three"
      ]
    }
}
```

**Sample data**

```json
{
  "myEnum": null
}
```

**Validation result, data AFTER validation, error messages**

```
ERROR: [
  {
    keyword: 'enum',
    dataPath: '/myEnum',
    schemaPath: '#/properties/myEnum/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  }
]
```

**What results did you expect?**

`nullable: true` should affect the `enum` keyword validation.

We've been here before, see #824, but now that `nullable` is a keyword, let's revisit this question?

**Are you going to resolve the issue?**

I could try.

**Comment by epoberezkin** [comment]
This is consistent with how OpenAPI treats nullable - as an alternative syntax to extend allowed types in "type" keyword, it has no impact on "enum" - null has to be added there explicitly.

You probably know that in JSON schema properties without type does not require that data is an object, just mentioning as the schema does not have type: object.

Please note that this is different in JTD that ajv now supports via a separate import (import Ajv from "ajv/dist/jtd") - nullable there actually extends the schema and the correct JTD schema that allows null is:

```json
const schema = {
  "properties": {
    "myEnum": {
      "nullable": true,
      "enum": [
        "one",
        "two",
        "three"
      ]
    }
}
```

(and this schema requires that the data is an object).

**Comment by lehni** [comment]
Ok thank you for the explanations!
