### ISSUE TITLE
Current status of JTD / TypeScript?

### ISSUE THREAD

**Issue by jrr** [ajv-validator/ajv#1476]
I was bringing AJV in to a new project, and got excited reading about JSON Type definition,
then realized that the "Getting Started" example from the Readme doesn't work with the current release.

https://github.com/ajv-validator/ajv#getting-started

(in particular, it looks like the `JTDSchemaType` type arrived some time after 7.1.1)

I see from issues and PRs that this area is still in active development.

Is there a doc that describes the currently-released capabilities? 

How can I install a development build to try out the new stuff?

**Comment by epoberezkin** [comment]
Yes JTD is really cool. @erikbrinkman added JTDSchemaType that converts data type to schema type, and there is PR that looks ready to go that does the opposite - given JTD schema (as const) constructs the type of data.

There are also serializers and parsers compiled from JTD schema, the serializers are 10x faster than JSON.parse, the parsers replace the need to validate (and are as fast as JSON.parse, but the main advantage is that they don’t need to parse the whole object to fail - although in some cases it may be inconvenient).

I am planning to release 7.2 tomorrow that would include it all.

You can always git clone and npm install locally, and then use npm link if you want to play with something that’s not released yet.

The website is just updated - the docs are quite comprehensive on JTD.

This is all brand new stuff, I’ll be supporting/fixing any issues that would come up pretty quickly, so it’ll stabilise pretty soon.

**Comment by epoberezkin** [comment]
Although the basic support for JTD is there in 7.1 already, but you are right - some newest examples won’t work with 7.1

**Comment by epoberezkin** [comment]
[7.2.0](https://github.com/ajv-validator/ajv/releases/tag/v7.2.0) released
