### ISSUE TITLE
Maximum call stack size exceeded without loopEnum option

### ISSUE THREAD

**Issue by cipchk** [ajv-validator/ajv#1480]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

7.2.1

**Ajv options object**

See demo code below

**JSON Schema**

See demo code below

**Sample data**

See demo code below

**Your code**

https://stackblitz.com/edit/js-hxwjp8?file=index.js

It can be working when reduce the enum data to 1000 rows.

**Validation result, data AFTER validation, error messages**

```
Maximum call stack size exceeded
```

**What results did you expect?**

Expected is pass.

**Are you going to resolve the issue?**

No

**Comment by epoberezkin** [comment]
You need to use loopEnum option to limit the size of enum that compiles as expression.
