### ISSUE TITLE
oneOf of schemas with common properties

### ISSUE THREAD

**Issue by guerrap** [ajv-validator/ajv#1488]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
I'm using the latest version 7.2.1

**Ajv options object**

```javascript
{}
```

**JSON Schema**

```json
{
  "definitions": {
    "schema1": {
      "type": "object",
      "properties": {
        "prop1": { "type": "string" },
        "prop2": { "type": "string" }
      },
      "additionalProperties": false
    },
    "schema2": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/schema1"
        },
        {
          "properties": {
            "prop3": { "type": "string" },
            "prop4": { "type": "string" }
          }
        }
      ],
      "additionalProperties": false
    }
  },
  "oneOf": [
    { "$ref": "#/definitions/schema1" },
    { "$ref": "#/definitions/schema2" }
  ]
}

```

**Sample data**

```json
{
  "prop1": "string",
  "prop2": "string",
  "prop3": "string",
  "prop4": "string"
}

```

**Your code**

```javascript
const Ajv = require("ajv").default;
const ajv = new Ajv();

const validate = ajv.compile(schema);
const valid = validate(data);

if (!valid) console.log(validate.errors);

```

https://runkit.com/guerrap/604b35dfbb8bcc001a57abd5

**Validation result, data AFTER validation, error messages**

```
[
  {
    keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/definitions/schema1/additionalProperties',
    params: { additionalProperty: 'prop3' },
    message: 'should NOT have additional properties'
  },
  {
    keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/definitions/schema1/additionalProperties',
    params: { additionalProperty: 'prop3' },
    message: 'should NOT have additional properties'
  },
  {
    keyword: 'oneOf',
    dataPath: '',
    schemaPath: '#/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
```

**What results did you expect?**

This is more a question than an actual issue because that's probably how JSON schema is supposed to work.
Anyway, I'm trying to define a schema that validates multiple definitions using the `oneOf`, each of which can't have any additional prop. The "problem" is that the schemas have common properties, so I extend the first one and add the additional properties that I need.

Now, since the first schema has `additionalProperties` set to `false`, the example data provided above fails the validation; if I remove the `additionalProperties` in the first schema the validation passes but then something like this is also accepted:

```json
{
  "prop1": "string",
  "prop2": "string",
  "prop5": "string"
}
```
My use case is to have `n` schema definitions, each of which can't have any additional prop, and they can share properties (or extend other schema).

How is this achievable with JSON schema? I'm sure doing something wrong, but I can't figure it out.

**Comment by epoberezkin** [comment]
draft2019-09 has unevaluatedProperties for that instead of additionalProperties.

**Comment by epoberezkin** [comment]
You can also construct JTD discriminator schema or JSON schema in JavaScript, by mixing in shared properties (so they would be repeated in underlying object but not in code)
