### ISSUE TITLE
JTDDataType signature for compile and verify

### ISSUE THREAD

**Issue by erikbrinkman** [ajv-validator/ajv#1489]
**What version of Ajv you are you using?**

master (7 or 8)

**What problem do you want to solve?**

Add signatures to `AjvJTD`'s `compile` and `verify` methods that would support something like:
```
const schema = { ... } as const
const verify = ajv.compile(schema)
if (verify(data)) {
    const typed: JTDDataType<typeof schema> = data // no type errrors
}
```

**What do you think is the correct solution to problem?**

Note entirely sure, opening this up for discussion, versus continuing to talk on PR #1458.

I've been looking at how to do this, and I'm starting by implementing `SomeJTDSchemaType` and modifying the signature of compile. Previously I remember talking about having the AjvJTD subclass have different type arguments from the core Ajv class. I vaguely remember you not wanting to. Is there a reason you don't want to do this? Is there a significant cost to the `super` call?

**Will you be able to implement it?**

Yes

**Comment by epoberezkin** [comment]
> 7 or 8

It's ok to add to 7 I think

> implementing SomeJTDSchemaType and modifying the signature of compile

That seems ok, as you suggested in the PR there would be extra signatures in the core class:

```
compile<T extends SomeJTDSchemaType >(schema: T): ValidateFunction<JTDDataType<T>>;
```

> having the AjvJTD subclass have different type arguments from the core Ajv class

some risk of divergence, additional complexity, some cost of extra call. Is there a reason why adding extra signature could be bad? Also, If JTD type signature were to be in the subclass why would JSON Schema signature be in core?

I do not plan many schema languages, so keeping it in core seems ok.

Also, I just never liked it when I had to add any executable code to satisfy type system/improve type safety :) It would have been nice if typescript had some zero-cost abstractions to add method overloads in subclasses...

**Comment by erikbrinkman** [comment]
yeah, those are good points. I'll see why I can do. There's some complexity that seems to come from the mingling of JTDDataType and ValidateFunction that I'm trying to understand. Will update. My guess is this won't make it in until 8.

**Comment by erikbrinkman** [comment]
The more I've played with this, the more it seems that JTDDataType is teetering right at the limits of typescripts complexity. It works when used by itself, but adding one more indirection of inferring it as a function argument makes typescript fail.

The solution probably lies in making it a little simpler if possible, or maybe having compile only work for definitions without refs, as that seems to be the cause of a lot of the complexity.

I'm still playing around with ideas, because I think it would be really cool for
```
const schema = ... as const
const validator = ajv.compile(schema)
```
to just work without additional typing.
