### ISSUE TITLE
I want to be able to use errorsText and similar helpers without the need of creating ajv instance

### ISSUE THREAD

**Issue by alyahmedaly** [ajv-validator/ajv#1492]
I want to be able to use errorsText and similar helpers without the need of creating ajv instance.

Right now if you want to use errorsText you need to create ajv instance

`
  return new ajv().errorsText(errors, options);
`
this is happening now because in errorsText implementation we have `errors || this.errors`.

it would be better if you can export errorsText directly and have wrapper under ajv instance.
`
function errorsText(errors, options) {
  exportedVersionofErrorsText(errors || this.errors,options);
}
`

I think this related to #1359

**What version of Ajv you are you using?**
7.2.1

**What problem do you want to solve?**
API, this will allow utills methods for Ajv as we abstract the use of ajv with in our project.

**Will you be able to implement it?**
why not :) if you guys agree

**Comment by epoberezkin** [comment]
Sorry - probably missing something - what’s the use case?

You need to have an instance to get the errors in the first place - can you use it?

**Comment by alyahmedaly** [comment]
@epoberezkin for example I have this class

```
import { Ajv, ErrorObject } from 'ajv';

export interface ISchemaValidator {
validate(key: object | string | boolean, data: unknown): [boolean, Array<ErrorObject>];
}

export class SchemaValidator implements ISchemaValidator {
  constructor(private readonly ajv: Ajv) {}

  validate(key: object | string | boolean, data: unknown): [boolean, Array<ErrorObject>] {
      const valid = this.ajv.validate(key, data);
      return [valid as boolean, this.ajv.errors ? [...this.ajv.errors] : []];
  }
}
```

and it's used like the following

```
function validateXAndLogErrors(schemaValidator: ISchemaValidator, param: unknown): param is number {
  const [valid, errors] = schemaValidator.validate('#/definitions/XX/properties/param', param);
  // in this case I don't have access to Ajv instance and I don't this we really need it here
  if (!valid) {
        console.log(ajvErrorsToText(errors)); // or logger.log
  }
  return valid;
}

export function ajvErrorsToText(errors: Array<ErrorObject>): string {
  return new ajv().errorsText(errors, {
    separator: '\n',
  });
}
```

I hope that make it more clear for you.

**Comment by epoberezkin** [comment]
You could expose your version of errorsText from SchemaValidator, in the same way as validate. I don't think it justifies api change to be honest, it usually helps to have some application level framework around a library...

On schema management patterns - this can be helpful: https://ajv.js.org/guide/managing-schemas.html#using-ajv-instance-cache

**Comment by alyahmedaly** [comment]
Well, I agree there is no strong reason to change the API, but it will improve the API if we did it.
