### ISSUE TITLE
missingProperty undefined with ownProperties: true

### ISSUE THREAD

**Issue by brigand** [ajv-validator/ajv#1493]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

7.2.1

**Ajv options object**

```javascript
const options = {
	ownProperties: true,
};
```

**JSON Schema**

```json
{
  "type": "object",
  "required": [
    "a"
  ],
  "properties": {
    "a": {
      "type": "string"
    }
  }
}
```

**Sample data**

```json
{}
```

**Your code**

```javascript
const ajv = new Ajv(options);
const foo = ajv.compile(schema);
foo(data);
assert.deepEqual(foo.errors[0], {
  keyword: 'required',
  dataPath: '',
  schemaPath: '#/required',
  params: { missingProperty: undefined },
  message: "should have required property 'undefined'",
});
```

**What results did you expect?**

missingProperty should be `'a'`, and message should reference it instead of undefined.

**Are you going to resolve the issue?**

If recommended as a good first issue.

**Comment by epoberezkin** [comment]
thank you - fixed!

**Comment by epoberezkin** [comment]
in 7.2.2
