### ISSUE TITLE
allOf + additionalProperties: false

### ISSUE THREAD

**Issue by sinclairzx81** [ajv-validator/ajv#1496]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

7.2.1, Yes

**Ajv options object**

Defaults

**JSON Schema**

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "b": {
          "type": "number"
        }
      },
      "required": [
        "b"
      ],
      "additionalProperties": false
    }
  ]
}
```

**Sample data**

```json
{ "a": "hello", "b": 3000 }
```

**Your code**

```javascript
const Ajv = require('ajv')

const ajv = new Ajv.default()

const validate = ajv.compile({
  allOf: [
    {
      type: "object",
      properties: {
        a: { "type": "string" }
      },
      required: ["a"],
      additionalProperties: false
    },
    {
      type: "object",
      properties: {
        b: { "type": "number" }
      },
      required: ["b"],
      additionalProperties: false
    }
  ]
})

const success = validate({ a: 'hello', b: 3000 })
const errors = validate.errors
console.log(success, errors)
```

**Validation result, data AFTER validation, error messages**

```javascript
[
  {
    keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/allOf/0/additionalProperties',
    params: { additionalProperty: 'b' },
    message: 'should NOT have additional properties'
  }
]
```

**What results did you expect?**

I guess the expectation here is that this schema should validate. But I'm not sure. There may be ambiguities with respect how to handle inner `allOf` schemas with `additionalProperties`, and especially for `additionalProperties` where the values vary for each inner schema. However, I think the most reasonable interpretation of the above schema would be to interpret it as the following flat schema...

```javascript
{
    type: "object",
    properties: {
      a: { "type": "string" },
      b: { "type": "number" }
    },
    required: ["a", "b"],
    additionalProperties: false
}
```
And perhaps with the following rules for varying `additionalProperties` values.

- If ALL inner `allOf` schemas have `additionalProperties: false`. The validation should assume `additionalProperties: false`.
- If NONE or SOME inner `allOf` schemas have `additionalProperties: false`. The validation should assume `additionalProperties: true`.

**Comment by sinclairzx81** [comment]
Will close this issue. Looking at the RFC, Ajv would be following the spec closely here. I had interpreted `allOf` acting as a kind of Intersection of objects, but this isn't the case. Relevant section below.

### [AllOf](https://json-schema.org/draft/2020-12/json-schema-core.html#allOf)

> An instance validates successfully against this keyword if it validates successfully against all schemas defined by this keyword's value.

Which would imply the correct behavior from Ajv. The schema provided with this issue is effectively non-validate-able (which is interesting, in and of itself), but everything seems in order. Apologies :)

**Comment by epoberezkin** [comment]
That is correct, the behaviour you need can be implemented with `unevaluatedProperties` (from draft-2019-09) on the top level - ajv supports it via a separate export in "ajv/dist/2019".

**Comment by richardgarnier** [comment]
I believe this use case is handled by https://ajv.js.org/guide/combining-schemas.html#merge-and-patch-keywords

**Comment by epoberezkin** [comment]
@richardgarnier It can be used indeed, but it’s a non-standard extension, while unevaluatedProperties is a part of JSON Schema spec

**Comment by ChuckJonas** [comment]
> That is correct, the behaviour you need can be implemented with unevaluatedProperties (from draft-2019-09) on the top level - ajv supports it via a separate export in "ajv/dist/2019".

@epoberezkin could you provide an example of how this would work?

1. I'm not 100% sure on what the schema would look like in the example above.  Is the following correct?

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        }
      },
      "required": [
        "a"
      ]
    },
    {
      "type": "object",
      "properties": {
        "b": {
          "type": "number"
        }
      },
      "required": [
        "b"
      ]
    }
  ]
  "unevaluatedProperties": false
}
```

2. I don't see `"ajv/dist/2019".` in the npm `dist` folder.  How would you import this in a node project?

## Update

I was able to get this to work with the following code:

```js
import  Ajv from 'ajv/dist/2019';
const ajv = new Ajv();
const validate = ajv.compile({
    type: "object",
    allOf: [
      {
        type: "object",
        properties: {
          a: { "type": "string" }
        },
        required: ["a"],
        // additionalProperties: false
      },
      {
        type: "object",
        properties: {
          b: { "type": "number" }
        },
        required: ["b"],
        // additionalProperties: false
      }
    ],
    unevaluatedProperties: false
})

const success = validate({ a: 'hello', b: 3000, c: true })
console.log(validate.errors)
```
