### ISSUE TITLE
Cannot use Ajv version 7 in JavaScript

### ISSUE THREAD

**Issue by sabrineChe** [ajv-validator/ajv#1502]
I want to use the Ajv 7 in my project. I already used the previous versions without any problems, but using version 7 leads to an exception: "Uncaught ReferenceError: Ajv is not defined"
Here is my example, how i am calling the Ajv library:
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
    </head>
    <body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ajv/7.2.1/ajv7.min.js"></script>
        <script>
            const ajv = new Ajv();
           const validate = ajv.compile(schema)
          const valid = validate(data)
          if (!valid) console.log(validate.errors)
      </script>
    </body>
</html>

**Comment by 22aa96** [comment]
The script you linked exports the library as `ajv7`, attached to `window`, so you just have to replace `const ajv = new Ajv();` by ~~const ajv = new ajv7();~~ (**See next comment below**).

**Comment by sabrineChe** [comment]
I become as an error that ajv7 is not a constructor.

**Comment by 22aa96** [comment]
My bad I read it too fast. It tried with `var ajv = new ajv7.default()` it works. `Object.keys()` is your friend when you need to explore API ;)
You may want to import it this way to keep your syntax: `const Ajv = ajv7.default;`.

**Comment by sabrineChe** [comment]
It works. Thanks a lot for your help :)
