### ISSUE TITLE
strict mode tuple warning should give full path to location of problem

### ISSUE THREAD

**Issue by nornagon** [ajv-validator/ajv#1509]
**What version of Ajv you are you using?**
7.2.1

**What problem do you want to solve?**
I have a large autogenerated schema (created using typescript-json-schema), and ajv's strict mode is giving warnings about it like:

```
strict mode: "items" is 2-tuple, but minItems or maxItems/additionalItems are not specified or different
```

There are lots of possible `"items"` in the schema! Which is it referring to?

**What do you think is the correct solution to problem?**

Other strict mode warnings give the full path in the schema to the place where the issue is occurring, e.g.

```
strict mode: use allowUnionTypes to allow union type keyword at "#/anyOf/0/properties/workbench/properties/volume" (strictTypes)
```

It would be great if the tuple warning did the same!

**Will you be able to implement it?**

Maybe?

**Comment by epoberezkin** [comment]
Agreed - it would also have to be added to v8 which is due to release this week.

PR would be great!

**Comment by nornagon** [comment]
Thanks @asaid-0 :)
