### ISSUE TITLE
Access root data in code generation custom keyword

### ISSUE THREAD

**Issue by domnantas** [ajv-validator/ajv#1514]
**What version of Ajv you are you using?**
7.2.3

**What problem do you want to solve?**
I'm trying to validate whether array items are used as object keys.

Let's say I have a schema like this
```json
{
	"keys": {
		"type": "array",
		"arrayItemsAreKeysOf": "/specialObject" // attempting to implement this custom keyword
	},
	"specialObject": {
		"type": "object"
	}
}
```

This is valid:
```json
{
	"keys": ["one", "two"],
	"specialObject": {
		"one": true,
		"two": true
	}
}
```

This is invalid:
```json
{
	"keys": ["one", "two", "three"],
	"specialObject": {
		"one": true,
		"two": true
	}
}
```

**What do you think is the correct solution to problem?**
In ajv v6 I had a custom "validate" function to check this:
```js
ajv.addKeyword('arrayItemsAreKeysOf', {
	validate(schema, data, parentSchema, dataPath, parentData, propertyName, rootData) {
		const validArrayItems = R.pipe(
			R.path(schema.split('/')),
			R.keys,
		)(rootData);
		return R.all(R.includes(R.__, validArrayItems))(data);
	},
	errors: false,
});
```
(If you're unfamiliar with Ramda, this takes the keys of a given path (`/specialObject`) from `rootData` and then checks if all items of `data` (`keys` array in examples) are present)

And it worked fine. I tried rewriting this for ajv v7+ using the code generation keyword, but I'm not sure if it's possible to access `rootData` there.

**Will you be able to implement it?**
Maybe it's already possible to do what I'm trying to achieve?

**Comment by epoberezkin** [comment]
Your code is inserted into a validation function scope, root data is "data" there.

See https://github.com/ajv-validator/ajv/blob/master/lib/compile/validate/index.ts#L24

**Comment by domnantas** [comment]
I have rewritten the above v6 code to v7, took `rootData` from `dataCtx`:
```js
ajv.addKeyword('arrayItemsArePropertiesOf', {
	validate(schema, data, parentSchema, dataCtx) {
		const validArrayItems = R.pipe(
			R.path(schema.split('/')),
			R.keys,
		)(dataCtx.rootData);

		return R.all(R.includes(R.__, validArrayItems))(data);
	},
});
```

So `rootData` is only accessible in validation functions and not in code generation functions, right?

**Comment by shuzootani** [comment]
> So rootData is only accessible in validation functions and not in code generation functions, right?

@epoberezkin 
I'd appreciate it if you would answer the question above 🙏🏼 

https://ajv.js.org/keywords.html#define-keyword-with-code-generation-function

The doc shows an example like the following but `data` is always `undefined`.

```
ajv.addKeyword({
  keyword: "even",
  type: "number",
  schemaType: "boolean",
  // $data: true // to support [$data reference](./validation.md#data-reference), ...
  code(cxt: KeywordCxt) {
    const {data, schema} = cxt
    const op = schema ? _`!==` : _`===`
    cxt.fail(_`${data} %2 ${op} 0`) // ... the only code change needed is to use `cxt.fail$data` here
  },
})
```

As far as I look at types of code generation functions it seems that there is no way to access to `data` inside `code generation function`...
So I'm wondering how I can get `data` and `$data` ref in my custom keyword using code generation functions.

**Comment by epoberezkin** [comment]
As I wrote in above comment you just need to use “data” (not interpolated, just as part of code template literal) to access root data, not interpolated data from the context which gives the part of data structure that is currently validated.

**Comment by domnantas** [comment]
To make it slightly more clear for anyone stumbling on this, this is how you access the rootData in the `code` function:

```js
ajv.addKeyword({
  keyword: "even",
  code(cxt: KeywordCxt) {
    cxt.fail(_`console.log(data)`) // data here returns the "rootData" 
  },
})
