### ISSUE TITLE
Error: Cannot find module 'ajv/lib/refs/json-schema-draft-06.json'

### ISSUE THREAD

**Issue by Jason3S** [ajv-validator/ajv#1529]
Looks like the latest release (8.0.4) no longer contains the `lib` folder.

https://github.com/ajv-validator/ajv/commit/c4de1a4628757527a579ad179adf29c462acad1b#r49028541

```
Error: Cannot find module 'ajv/lib/refs/json-schema-draft-06.json'
Require stack:
- /home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/ajv.js
- /home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/compile.js
- /home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/index.js
- /home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/ajv.js:10:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/ajv.js',
    '/home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/compile.js',
    '/home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/commands/index.js',
    '/home/runner/work/cspell/cspell/packages/cspell-types/node_modules/ajv-cli/dist/index.js'
  ]
}
```

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript

```

**JSON Schema**

```json

```

**Sample data**

```json

```

**Your code**

```javascript

```

**Validation result, data AFTER validation, error messages**

```

```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
The instant fix is to require from "ajv/dist/refs/json-schema-draft-06.json"

It was a breaking change to remove "lib", sorry for that, but it's been documented that it's in "dist": https://ajv.js.org/json-schema.html#draft-06

The reason to remove was to reduce npm package size - the [wrong] assumption was that nobody needs libs in npm any more.

Options are:
1. Restore lib till v9. (extra 300k in npm package) - vote "thumbs down" if you think it's the right option
2. Restore only lib/refs - I would probably do that...
3. Do not restore lib - affected users will have to change the imports to "ajv/dist" folder - vote "thumbs up"

**Comment by Jason3S** [comment]
@epoberezkin,

Thank you for the quick reply. I'm using `ajv-cli` with nothing special.

Here is the [ajv-cli/ajv.ts](https://github.com/ajv-validator/ajv-cli/blob/a02fbbfab3ffa0103d13c95391c5f1b4969df61e/src/commands/ajv.ts#L12) line with the issue:

```js
// ajv.ts
// ...
import {getOptions} from "./options"
import * as util from "./util"
import * as path from "path"
import * as draft6metaSchema from "ajv/lib/refs/json-schema-draft-06.json"

type AjvMethod = "addSchema" | "addMetaSchema"

```

**Comment by epoberezkin** [comment]
right... I am reverting it. Best to leave it till v9

**Comment by epoberezkin** [comment]
reverted in 8.0.5

**Comment by Jason3S** [comment]
Thank you
