### ISSUE TITLE
Redirect old Contributing Guide link to new one

### ISSUE THREAD

**Issue by marsonya** [ajv-validator/ajv#1534]
The old link to contributing guide `https://ajv.js.org/contribute.html` no longer works.
It would be nice to redirect it to `https://ajv.js.org/contributing/`.

Issue spotted [here](https://github.com/openjs-foundation/cross-project-council/pull/734)

**Comment by epoberezkin** [comment]
Something got broken in the site logic... - there are quite a few .html links - will fix

**Comment by epoberezkin** [comment]
ah - it's not that - I've found where this link is used.
