### ISSUE TITLE
Type `uuid` isn't exists for Array in Ajv v7/v8?

### ISSUE THREAD

**Issue by dalisoft** [ajv-validator/ajv#1536]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**
```javascript
{ allErrors: true, strict: true }
```

**JSON Schema**

```json
{
        "type": "array",
        "items": { "type": "string", "format": "uuid" }
}
```

**Sample data**

```json
["0d7051b1-7d4d-4d26-b5ee-9a20ea30e310", "0d7051b1-7d4d-4d26-b5ee-9a20ea30e310"]
```

**Your code**

https://runkit.com/dalisoft/606c9ce9ccb884001b7e9794

**Validation result, data AFTER validation, error messages**

```bash
Error: unknown format "uuid" ignored in schema at path "#/items"
```

**What results did you expect?**

Correct validation

**Are you going to resolve the issue?**

I don't know enough yet, but if someone from team can help, i really want solve this issue

**Comment by epoberezkin** [comment]
Formats are moved to ajv-formats package - see https://ajv.js.org/guide/formats.html

**Comment by dalisoft** [comment]
Thanks @epoberezkin. I didn't noticed it before

**Comment by mastrobardo** [comment]
Same error Here. Is there any news on this ? 
{
  "name": "vx-mock",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "axios": "^1.6.8",
    "express": "^4.19.2",
    "fs": "^0.0.1-security",
    "mongoose": "^8.3.2",
    "path": "^0.12.7"
  },
  "dependencies": {
    "ajv": "^8.12.0",
    "ajv-errors": "^3.0.0",
    "ajv-formats": "^3.0.1"
  }
}
