### ISSUE TITLE
Missing propagation of second type parameter in JTDSchemaType

### ISSUE THREAD

**Issue by capitnflam** [ajv-validator/ajv#1537]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I'm using:

- `ajv`: `8.0.5`
- `typescript`: `4.2.3`

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ajv@8.0.5` for the project I'm working on.

I have the following types:

```typescript
interface ConfigDataExtend {
  source?: 'github'
  version: string
}
export interface ConfigData {
  extends?: Record<string, ConfigDataExtend>
  rules?: string[]
}
```

After a bit of trial and error I arrived at the following schema:

```typescript
const schema: JTDSchemaType<ConfigData, { extendItem: ConfigDataExtend }> = {
  definitions: {
    extendItem: {
      optionalProperties: { source: { enum: ['github'] } },
      properties: {
        version: { type: 'string' },
      },
    },
  },
  optionalProperties: {
    extends: {
      values: {
        ref: 'extendItem',
      },
    },
    rules: { elements: { type: 'string' } },
  },
}
```

But here is the error I had on the `ref: 'extendItem'` line:

> Type '{ ref: string; }' is not assignable to type 'JTDSchemaType<ConfigDataExtend, Record<string, never>>'.
  Object literal may only specify known properties, and 'ref' does not exist in type 'JTDSchemaType<ConfigDataExtend, Record<string, never>>'.ts(2322)
jtd-schema.d.ts(59, 5): The expected type comes from property 'values' which is declared here on type 'JTDSchemaType<Record<string, ConfigDataExtend>, { extendItem: ConfigDataExtend; }>'

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ajv/dist/types/jtd-schema.d.ts b/node_modules/ajv/dist/types/jtd-schema.d.ts
index d06b3a2..5b52d35 100644
--- a/node_modules/ajv/dist/types/jtd-schema.d.ts
+++ b/node_modules/ajv/dist/types/jtd-schema.d.ts
@@ -56,7 +56,7 @@ export declare type JTDSchemaType<T, D extends Record<string, unknown> = Record<
 } : true extends IsElements<Exclude<T, null>> ? T extends readonly (infer E)[] ? {
     elements: JTDSchemaType<E, D>;
 } : never : true extends IsValues<T> ? T extends Record<string, infer V> ? {
-    values: JTDSchemaType<V>;
+    values: JTDSchemaType<V, D>;
 } : never : true extends IsRecord<T, false> ? ([RequiredKeys<Exclude<T, null>>] extends [never] ? {
     properties?: Record<string, never>;
 } : {
```

Looking at the definition of `JTDSchemaType`, this is the only place where `JTDSchemaType` is used with only one type parameter which seems odd to me.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by epoberezkin** [comment]
Thank you - seems like it has to be added - PR is welcome!

@erikbrinkman any reason why it shouldn't be there I could be missing?
