### ISSUE TITLE
Status of unevaluatedProperties

### ISSUE THREAD

**Issue by sinclairzx81** [ajv-validator/ajv#1544]
Hello! I'm just writing to ask the status of `unevaluatedProperties` which is currently available by importing

```typescript
import Ajv from 'ajv/dist/2019'
```
Is there plans to promote this keyword in the future, or is there a reason why `unevaluatedProperties` is only available on the `ajv/dist/2019` import path? Having this keyword available on a separate import gives the impression that it may be unstable or potentially not ready for use, so really just writing to ask about it's general status.

Many Thanks
S

**Comment by sinclairzx81** [comment]
Might close this one off. Will do a bit more reading on the keyword. Thanks

**Comment by epoberezkin** [comment]
No plans to remove, there are just multiple exports, depending on which schema version / language you want to choose.

https://ajv.js.org/guide/schema-language.html

https://ajv.js.org/json-schema.html#json-schema-versions
