### ISSUE TITLE
How can I ignore some keywords in schemas when validating?

### ISSUE THREAD

**Issue by secreter** [ajv-validator/ajv#1545]
**What version of Ajv you are you using?**
6.12.6
**What problem do you want to solve?**
In my project , I use the same jsonschema in many place, like web page and backend API。when I use the same jsonschema to validate the search params, I hope every  param can be optional, however the original jsonschema may be set the key 'required',ajv throw an error。

**What do you think is the correct solution to problem?**
May be ajv can provide an ignore keyword list 

**Will you be able to implement it?**
provide an ignore keyword list or function

**Comment by epoberezkin** [comment]
Keywords are part of JSON Schema specification, the requirement to ignore some of them is similar to ignoring some of the code statements in any other programming language...

It is not possible with "required" keyword in ajv v6, it is tightly coupled with "properties"

Some other keywords can be removed with removeKeyword.

Ajv v7/8 has more independent "required" implementation - it can be removed there.

You can also construct your own subclass of AjvCore (core.ts) similarly how it is done for bundled subclasses - see v7/8

**Comment by secreter** [comment]
Thanks,I got it.
