### ISSUE TITLE
Compile does not throw exception when unknown keyword is used in schema definition that is not referred to in the schema

### ISSUE THREAD

**Issue by akarasulu** [ajv-validator/ajv#1546]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Latest 8.0.5

**Ajv options object**

Default

**JSON Schema**

Snippet embedded in test suite below

**Sample data**

No data just schema validation.

**Your code**

[Code on RunKit](https://runkit.com/wardog/ajv) with contents of 3rd test case that should raise error. Entire test suite is below. All three tests should succeed. The first two succeed but the third fails.

```javascript
// note draft 2019
const Ajv = require('ajv/dist/2019');

describe('Ajv behavior tests', () => {
  it('Schema with definitions should compile', () => {
    const ajv = newAjv();
    const schema = {
      $id: 'https://example.com/test/schema/1.0.0/',
      $schema: 'https://json-schema.org/draft/2019-09/schema#',
      type: 'object',
      definitions: {
        A: {
          type: 'integer',
        },
      },
    }

    expect(ajv.compile(schema)).not.toBeUndefined();
  });

  it('Schema with definitions but unknown "foo" keyword should fail', () => {
    const ajv = new Ajv();
    const schema = {
      $id: 'https://example.com/test/schema/1.0.0/',
      $schema: 'https://json-schema.org/draft/2019-09/schema#',
      type: 'object',
      foo: 'bar',
      definitions: {
        A: {
          type: 'integer',
        },
      },
    }

    expect(() => {
      ajv.compile(schema);
    }).toThrow(new Error('strict mode: unknown keyword: "foo"'));
  });

  it('Schema with definitions but unknown "foo" keyword in definition A should fail', () => {
    const ajv = new Ajv();
    const schema = {
      $id: 'https://example.com/test/schema/1.0.0/',
      $schema: 'https://json-schema.org/draft/2019-09/schema#',
      type: 'object',
      definitions: {
        A: {
          type: 'integer',
          foo: 'bar',
        },
      },
    }

    expect(() => {
      ajv.compile(schema);
    }).toThrow(new Error('strict mode: unknown keyword: "foo"'));
  });
});
```

**What results did you expect?**

I expected the 3rd test case to fail saying that it did not recognize keyword `foo`.

**Comment by epoberezkin** [comment]
The error is not raised because this definition is not used. It will be raised when the definition is used by this or some other schema. It is not practical to pre-compile all definitions, but if you need it to validate the schema definitions that might be used elsewhere you can do it with a loop:

```javascript
ajv.addSchema(schema)
for (ref in schema.definitions) ajv.getSchema(`{schema.$id}#/definitions/${ref}`)
```

It will throw if any of the schemas in the definitions does not compile.

Doing it as part of compile could be wrong for some use cases.

**Comment by akarasulu** [comment]
Thanks for the quick feedback. I understand the impracticality of compiling all schema definitions, especially those without predecessors. This could result in some odd situations for Ajv users where invalid schema are presumed to be valid. A configuration parameter to toggle compiling all would have been wonderful here. It would serve the schema only validation use cases well.

**Comment by akarasulu** [comment]
> ```js
> for (ref in schema.definitions) ajv.getSchema(`{schema.$id}#/definitions/${ref}`)
> ```

Unfortunately, ^^^^ is not raising the error either. Is there a way to explicitly trigger validation?

**Comment by akarasulu** [comment]
> > ```js
> > for (ref in schema.definitions) ajv.getSchema(`{schema.$id}#/definitions/${ref}`)
> > ```
> 
> Unfortunately, ^^^^ is not raising the error either. Is there a way to explicitly trigger validation?

Doh, I found out why this did not work as-is. There was no dollar sign in front of `${schema.$id}#/def...`
