### ISSUE TITLE
Strict check on keyword?

### ISSUE THREAD

**Issue by mikethecalamity** [ajv-validator/ajv#1549]
**What version of Ajv you are you using?**
7.0.0

**What problem do you want to solve?**
This may already be possible, but can you require a keyword to exist? Like a strict check on `description`?

**What do you think is the correct solution to problem?**

**Will you be able to implement it?**
No

**Comment by epoberezkin** [comment]
This can be achieved by extending meta-schema to make keywords required - it's a bit easier with draft2019/2020 than with draft7 - see for example how hyper schema meta schema is constructed in JSON Schema org.

That may unpractical though to require description
