### ISSUE TITLE
strict mode: missing type "object" for keyword "required" at "#" (strictTypes)

### ISSUE THREAD

**Issue by iangregsondev** [ajv-validator/ajv#1553]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.1

**Ajv options object**

```javascript
    const ajv = new Ajv({ allErrors: true })
```

**JSON Schema**

Its a small extraction  - I have left out the full properties..

```json
{
      required: ["PoolConfig"],
      properties: {
        PoolConfig: {
          type: "object",
          required: [
            "address",
            "coinbaseString",

```

The error that is displayed is

```
strict mode: missing type "object" for keyword "required" at "#" (strictTypes)
```

It doesn't stop it from working.

But the "required" is there, I should not disable strict mode, right ?

**Comment by epoberezkin** [comment]
The problem is that `type: "object"` is absent, so the data can be any JSON type.

**Comment by darbio** [comment]
From the [documentation](https://ajv.js.org/strict-mode.html#defined-required-properties), the solution is to add `type: "object",` to your schema root object:

This simple JSON Schema is valid, but it violates strictTypes:
```
{
  properties: {
    foo: {type: "number"},
    bar: {type: "string"}
  }
  required: ["foo", "bar"]
}
```

This is a very common mistake that even people experienced with JSON Schema often make - the problem here is that any value that is not an object would be valid against this schema - this is rarely intentional.

To fix it, "type" keyword has to be added:

```
{
  type: "object",
  properties: {
    foo: {type: "number"},
    bar: {type: "string"}
  },
  required: ["foo", "bar"]
}
```

**Comment by xiaoas** [comment]
The schema given on https://json-schema.org/understanding-json-schema/reference/conditionals:
```json
{
  "type": "object",
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "default": "United States of America",
      "enum": ["United States of America", "Canada", "Netherlands"]
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "country": { "const": "United States of America" }
        }
      },
      "then": {
        "properties": {
          "postal_code": { "pattern": "[0-9]{5}(-[0-9]{4})?" }
        }
      }
    },
    {
      "if": {
        "properties": {
          "country": { "const": "Canada" }
        },
        "required": ["country"]
      },
      "then": {
        "properties": {
          "postal_code": { "pattern": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" }
        }
      }
    },
    {
      "if": {
        "properties": {
          "country": { "const": "Netherlands" }
        },
        "required": ["country"]
      },
      "then": {
        "properties": {
          "postal_code": { "pattern": "[0-9]{4} [A-Z]{2}" }
        }
      }
    }
  ]
}
```
Will trigger these warning as well. maybe the warning should not be emitted if the schema is in a `if` clause?

minimal example:
```json
{
  "if": {
    "required": [
      "field_a"
    ]
  },
  "then": {
    "required": [
      "field_b"
    ]
  }
}
```
