### ISSUE TITLE
 validate a multipart/formData that has a file in one of its properties 

### ISSUE THREAD

**Issue by ngingihy** [ajv-validator/ajv#1556]
**What version of Ajv you are you using?**
latest

**What problem do you want to solve?**
validating formData/multipart type file

**What do you think is the correct solution to problem?**
validate against 'file' type

**Will you be able to implement it?**.
No

**Comment by epoberezkin** [comment]
`type` is defined in JSON Schema spec, it cannot be extended. I think in this case you should use "string" type
