### ISSUE TITLE
Site / Readme has broken links

### ISSUE THREAD

**Issue by xta** [ajv-validator/ajv#1559]
In the footer of the site index page (docs/README.md), there are two broken links:

* https://ajv.js.org/docs/getting-started.html
* https://ajv.js.org/contributing.html

It appears these are the intended target links:
* https://ajv.js.org/guide/getting-started.html
* https://ajv.js.org/contributing/

The 2nd link is weird. In Chrome, when I open it in a new tab, I get 404. If I click on contributing (same page, not new tab), it works fine.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
N/A

**What results did you expect?**
Clicking on link takes me to the page

**Comment by epoberezkin** [comment]
> The 2nd link is weird. In Chrome, when I open it in a new tab, I get 404. If I click on contributing (same page, not new tab), it works fine.

this is because the site is SPA and the internal routing in vue/vuepress probably works a bit differently.

**Comment by epoberezkin** [comment]
PR is welcome!
