### ISSUE TITLE
Serializable validation function

### ISSUE THREAD

**Issue by ReactiveRaven** [ajv-validator/ajv#156]
Is there a way to get a serializable validation function that can be used in another context?

For example, CouchDB is a document-based database with a 'validate_doc_update' function which is serialised as a string on a special class of JSON documents called Design Documents. It would be very useful to be able to store the validate function to a string so it could be used to validate documents as they're being updated in the document-database, but currently there are dependencies outside the validation function's context (eg the `equals` function being missing is the current error message I'm getting).

Short of serialising the entire `bundle.js` file in from npm, eval-ing it and generating a validation function inside the inner context, is there a way to generate a serializable validation function?

**Comment by epoberezkin** [comment]
Not at the moment, validation function is a closure as you pointed out.

I was planning to implement it in [ajv-cli](https://github.com/jessedc/ajv-cli/issues/1) (and it would require splitting some run-time dependency from ajv).

Maybe the better way to do it is to have the api for creating a serialisable validation function exposed in ajv and have ajv-cli simply use this api.

**Comment by epoberezkin** [comment]
@ReactiveRaven I was looking at [couchdb docs](http://guide.couchdb.org/draft/validation.html), it seems like this function should have everything inside, so it won't be able to use any dependencies or globals, correct? Are there any other limitations?

**Comment by gabrielmancini** [comment]
ajv still dont work on couchdb

**Comment by epoberezkin** [comment]
@gabrielmancini this is a very old issue - since then you can create serialisable self-contained validation functions with ajv-pack (with some limitations).

**Comment by mugwhump** [comment]
@gabrielmancini I can confirm that it does, in case anyone else is wondering. The output generated by `ajv-cli compile` can be plunked into a design doc as a commonJS lib and used by other design functions. :)
