### ISSUE TITLE
Cannot use AJV Formats, documentation incorrect.

### ISSUE THREAD

**Issue by paul-uz** [ajv-validator/ajv#1574]
Using the example code results in errors and simply does not work.

```
const Ajv = require("ajv")
const addFormats = require("ajv-formats")

const ajv = new Ajv()
addFormats(ajv)
```

The above code, from the documentation, does not work.

Both `const ajv = new Ajv()` and `addFormats(ajv)` produce an error "This expression is not constructable." 

Package versions:

```
    "ajv": "^8.2.0",
    "ajv-formats": "^2.0.2"
```

NB - I can get rid of one error, from `const ajv = new Ajv()` by add `.default` to the require statement, but `addFormats(ajv)` still errors.

**Comment by seriousme** [comment]
Hi,

The code works under Node.js , see https://runkit.com/seriousme/ajv-addformats-sample
What type of enviroment do you use ? Node.js, rollup , TypeScript,versions etc ??

Kind regards,
Hans

**Comment by paul-uz** [comment]
node v15.11.0
npm 7.6.0

Writing simple JS in VSCode

I have attached a ZIP file, that in my VSCode shows the errors mentioned. Check the AJV version and compare the code to that form the documentation. It does not work.

[ajvtest.zip](https://github.com/ajv-validator/ajv/files/6390801/ajvtest.zip)

**Comment by seriousme** [comment]
I extracted your zip and it shows package.json as:

```json
{
  "name": "ajvtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ajv": "^8.2.0"
  }
}
```
My first advice would be to run `npm install ajv-formats`
as it is not listed in the package.json

I tried your zip using node v15.11.0 and vscode 1.55.2 on Linux and did the following:
1. opened a terminal in vscode (using 'ctrl + `')
2. ran `npm install` 
3. ran `npm install ajv-formats`
4. ran `node index.js`
    Result no error
5. opened index.js in vscode and selected Run->Run without debugging
   Result no error

Do other modules work as expected ?
(e.g. something as simple as https://www.npmjs.com/package/oddoreven)

Kind regards,
Hans

**Comment by paul-uz** [comment]
@seriousme oh sorry, I have ajv-formats in my project, I made the ZIP to show that even just AJV has issues.

It looks like VSCode is showing the error, but the code is working. So possible something to do with the TS interpretation?

**Comment by epoberezkin** [comment]
vscode showing the error is not ajv issue - closing

**Comment by epoberezkin** [comment]
it might be just caching the old version - it often does
