### ISSUE TITLE
Typescript build failed

### ISSUE THREAD

**Issue by YuraNeyton** [ajv-validator/ajv#1575]
Currently I'm using ajv version 8.2.0
My project use typescript 3.9.9
When I add import to my code `import Ajv from 'ajv';` and then I try to build typescript with `tsc` I'm reserving error 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/43609887/116409944-ff51ff00-a83c-11eb-931a-08c0972c901a.png)
Can somebody help me please?

**Comment by seriousme** [comment]
It is not a bug report but a typescript issue (item 5 on the 'new issue' menu ;-)), it does not follow the template and the screenshot is quite vague :-(

Did you check:  https://github.com/ajv-validator/ajv/issues/1330

**Comment by epoberezkin** [comment]
It’s not tested with anything prior to 4.2.3 (and some things won’t work with earlier versions).

**Comment by epoberezkin** [comment]
Looking at screenshot it is an unsupported syntax in TS 3.x
