### ISSUE TITLE
Combining Enum with Default breaks

### ISSUE THREAD

**Issue by ouifi** [ajv-validator/ajv#1578]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.12.2

**Ajv options object**

```javascript
{ useDefaults: true }
```

**JSON Schema**

```json
{
    type: "string",
    enum: ["one", "two", "three"],
    default: "two"
}
```

**Sample data**

```json
""
```

**Your code**

```javascript
const Ajv = require("ajv");

const ajvCompiler = new Ajv({ useDefaults: true });

const testSchema = {
    type: "string",
    enum: ["one", "two", "three"],
    default: "two"
};

const data = "";

const validate = ajvCompiler.compile(testSchema);
console.log(data); // Prints ""
console.log(validate(data)); // Prints false
```

**Validation result, data AFTER validation, error messages**

```

```

**What results did you expect?**
Expected data to be "two" after validation. 

Using the following code produces the expected output:

```javascript
const Ajv = require("ajv");

const ajvCompiler = new Ajv({ useDefaults: true });

const testSchema = {
    type: "string",
    default: "two"
};

const data = "";

const validate = ajvCompiler.compile(testSchema);
console.log(data); // Prints "two"
console.log(validate(data)); // Prints true

```

**Are you going to resolve the issue?**
Not sure I understand this question. 

My main question here is why including an enum with a default causes the validation to fail to substitute. I did some looking online but could not find this brought up. I feel like this use case is not that odd, so I am mostly posting this out of curiosity and naivete than anything. Any help is appreciated!

**Comment by asaid-0** [comment]
You can't use `useDefaults` options if it's not in properties or items subschemas
https://ajv.js.org/guide/modifying-data.html#assigning-defaults

> why including an enum with a default causes the validation to fail to substitute

As you provided an empty string and it's not in the enum (default is ignored), also when you removed enum it worked as "" is a valid string, but actually, it will not add the default values (try to log data after validation)

**Comment by epoberezkin** [comment]
Enum should indeed work with default inside properties/items
