### ISSUE TITLE
Allow coerce to array of {integer,number,string,boolean,null}

### ISSUE THREAD

**Issue by willfarrell** [ajv-validator/ajv#158]
I have a use case when I'm validating query parameters. I have `/api?filter=A` => `{ filter:'A' }` and `/api?filter=A&filter=B` =>  `{ filter:['A','B'] }` being passed in. Currently I'm iterating through the object and schema to find this case and coerce before validation, but it would be faster and cleaner to have it built-in.

Can we extend the coerce to allow casting to an array when it's items type is non-array/object?

**example**
partial schema:

``` javascript
{ "type":"object", "properties":{
"filter":{
   "type":"array",
  "items":{ "type":"integer" } // possible types: integer,number,string,boolean,null
}
}}
```

input

``` json
{
  "filter":"42"
}
```

expected output:

``` json
{
  "filter":[42]
}
```

**Comment by epoberezkin** [comment]
It may be an interesting idea, please let me think about it.
The immediate workaround is to either use anyOf/oneOf keywords or to define some custom keyword.

**Comment by willfarrell** [comment]
Not a problem, I have a working work around in place for now. Just looking for a more performant solution.
I was using anyOf/oneOf keywords before moving to the solution I have in place now. I found this approach to be cleaner.

**Comment by epoberezkin** [comment]
My concerns are:
1. unless you expect this coercion it can be surprising and unexpected.
2. it may be coerced twice (first to array, then potentially to the type of array item, although maybe it's fine).
3. if it coerces to array it should also be able to coerce array of a single item to a scalar type, but it means that it would coerce twice in one go (first to a scalar than to the expected type)...

So if all these things seem ok, then at least it should be a different option value (`coerceTypes: 'array'`) that would coerce to/from arrays in addition to scalar coercion...

**Comment by willfarrell** [comment]
All three points are bang on for what I was thinking. `coerceTypes: 'array'` would be perfect.

**Comment by epoberezkin** [comment]
in [4.3.0](https://github.com/epoberezkin/ajv/releases/tag/4.3.0)
