### ISSUE TITLE
error: Maximum call stack size exceeded with schemas having ~510 properties or more

### ISSUE THREAD

**Issue by ssbarnea** [ajv-validator/ajv#1581]
While this was originally posted on https://github.com/ajv-validator/ajv-cli/issues/134 it proved to not be caused by the cli itself, but being more of a generic issue with ajv schema loader.

I recently discovered that bigger generated schemas can easily produce a a error: Maximum call stack size exceeded, even when the checks are quite simple.
```
ajv -- validate --strict=false --errors=json -s f/ansible-playbook.json -d /Users/ssbarnea/c/a/schemas/examples/playbooks/run.yml
schema f/ansible-playbook.json is invalid
error: Maximum call stack size exceeded
```

Based on my initial tests 500 properties worked but 1000 generated this error, which is a very low number. My expectation that that I will likely need 10k in the end. I tested with 510 and job only one schema failing instead of both, with 550 both failed. Clearly the moment it starts to fail is just after 500.

I am not sure what is confusing the loader because in the end the entries are very simple.

Here is one file that has ~1000 entries https://sbarnea.com/ss/ansible-playbook.json and is only ~100kb, just removing some of the properties will make it pass.

I also observed that if I reduce the number of properties to be near the limit, i also get an interesting behavior where it randomly fails with `Maximum call stack size exceeded` on each run. As soon you increase the number bit more it fails all the time.

I tried to use the API directly in order to to some of the options, like `loopRequired` as I was told by @epoberezkin but I was unable to find any configuration option that would prevent this bug from occurring.

**Comment by seriousme** [comment]
Can you share the schema and the javascript code you are using ?

Kind regards,
Hans

**Comment by ssbarnea** [comment]
There is no need to even attempt to validate a file, schema loading fails. Try `ajv compile` on https://github.com/ansible-community/schemas/blob/ff85c21ce03de48dbfb97c1769a5421c70ca9f6d/f/ansible-playbook.json  and you will get
```
error: Maximum call stack size exceeded
```

**Comment by seriousme** [comment]
Ok, just tried it myself:

```javascript
const Ajv = require("ajv")
const schema = require("./ansible-playbook.json")

const options = {strict: false, code: {optimize: false}} 
const ajv = new Ajv( options )
const validate = ajv.compile(schema);
```

this gives the following error:
```
/home/seriousme/node_modules/ajv/dist/compile/index.js:120
        throw e;
        ^

RangeError: Maximum call stack size exceeded
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:205:18)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:157:32)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:206:15)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:157:32)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:206:15)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:157:32)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:206:15)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:157:32)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:206:15)
    at If.optimizeNodes (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:157:32)
```

Trying to generate code using:
```
const options = {strict: false, code: {source:true, optimize: false}} 
```

results in:
```
/home/seriousme/node_modules/ajv/dist/compile/index.js:120
        throw e;
        ^

RangeError: Maximum call stack size exceeded
    at _Code.toString (/home/seriousme/node_modules/ajv/dist/compile/codegen/code.js:31:13)
    at If.render (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:200:31)
    at /home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:151:56
    at Array.reduce (<anonymous>)
    at If.render (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:151:27)
    at If.render (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:186:38)
    at If.render (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:200:52)
    at /home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:151:56
    at Array.reduce (<anonymous>)
    at If.render (/home/seriousme/node_modules/ajv/dist/compile/codegen/index.js:151:27)
```

Although this does not immediatly solve your problem it might help in finding a resolution.

Cheers,
Hans

**Comment by seriousme** [comment]
I tested some more:

I can compile the schema using:
```
/bin/bash -c "ulimit -s 65500; exec /usr/local/bin/node --stack-size=65500 ansibleTest.js
```
(thanks to: https://stackoverflow.com/a/20940085)

However...
Generating code from the 500K JSON schema file resulted in a 4.3 Mb standalone parser javascript file.

Kind regards,
Hans

**Comment by ssbarnea** [comment]
Thanks for looking into this! The ulimit workaround is quite inconvenient to use but I will try to see if I can squeeze it as a script command inside package.json

The issue can be reproduced with a far smaller file than the one in my example. Based on my test somewhere right after 500-510 properties is enough, not 5000 like in my the example. Still, the final schema will have more than 5000 and these will all have their own parameters not being just plain "object".

**Comment by seriousme** [comment]
Ajv  basically compiles your schema into javascript code and then executes this code. 
If your schema is more or less stable you could compile the code once (getting the 4.3 Mb parser ;-)) 

This works for me to create the parser:
`/bin/bash -c "ulimit -s 65500; npx --node-arg=--stack-size=65500 ajv-cli compile -s ansible-playbook.json -o ansibleParser.js --code-lines`
However the resulting 115K lines of javascript in ansibleParser.js also run out of stack.

If you only need this as a command line parser then there might be tools that are currently better suited for this use case.

Kind regards,
Hans

**Comment by ssbarnea** [comment]
Inside [schemas](https://github.com/ansible-community/schemas) project I am only using ajv as a way to validate that the generated schema is valid and produce expected results on a set of tests files. The only deliverables of the project are the schemas themselves, without any loader/parser. Still, these schemas will be published to https://www.schemastore.org/json/ so I have zero control over who will make use of them.

At this moment the only known consumer of these schemas is the vscode-ansible extension, which idirectly makes use of https://github.com/microsoft/vscode-json-languageservice which has its own schema validator implementation. 

I am planning to drop use of ajv completely due to this limitation, especially as I suspect that even if some improvement is done now, I will later face the same kind of issues when the schema size will be full grown.

**Comment by epoberezkin** [comment]
> Generating code from the 500K JSON schema file resulted in a 4.3 Mb standalone parser javascript file.

That's not that bad, given that JSON Schema is a much higher level (however restrictive) language than JS :)

The problem is that with "properties" keyword each property is compiled into its own code, but if there is a substantial similarity between them, it would be highly repetitive...

Some optimisation ideas:
1. Try using allErrors: true option - it should results in the code with less nesting of conditions (which is what causing deep recursion stack). It would collect all errors, though, rather than bail on the first one.
2. Try extracting (programmatically) any share parts into definitions and use inlineRefs: false (to make sure that the definition is compiled into a separate function and not just inlined every time it is used).

As a library improvement, there might be a possibility to break recursion into async code, but not sure how widely it is needed.

**Comment by epoberezkin** [comment]
The above suggestions work: see https://runkit.com/esp/6097b403293f88001a7fbb96

Using allErrors: true makes validation function shallow, so it doesn't exceed the stack regardless of the number of properties (I tried 10000 too).

Using $ref with `inlineRefs: false` option substantially reduces the size of the validation function.
