### ISSUE TITLE
Typescript: impossible to use JSONSchemaType with mixed index signatures and defined properties

### ISSUE THREAD

**Issue by lgarczyn** [ajv-validator/ajv#1588]
ajv version: 8.2.0

```typescript
interface T {
  a: number;
  [key: string]: unknown;
}

const b: JSONSchemaType<T> = {
  type: 'object',
  properties: { a: { type: 'number' } },
  required: ['a'],
  additionalProperties: true, // doesn't affect anything
};
```

<p>
<details>
<summary>ts error</summary>

<pre><code>
Type '{ type: "object"; properties: { a: { type: "number"; }; }; required: string[]; }' is not assignable to type 'JSONSchemaType<T, false>'.
  Type '{ type: "object"; properties: { a: { type: "number"; }; }; required: string[]; }' is not assignable to type '{ type: "object"; additionalProperties?: boolean | JSONSchemaType<unknown, false> | undefined; unevaluatedProperties?: boolean | JSONSchemaType<unknown, false> | undefined; ... 7 more ...; maxProperties?: number | undefined; } & { ...; } & { ...; } & { ...; }'.
    Type '{ type: "object"; properties: { a: { type: "number"; }; }; required: string[]; }' is not assignable to type '{ type: "object"; additionalProperties?: boolean | JSONSchemaType<unknown, false> | undefined; unevaluatedProperties?: boolean | JSONSchemaType<unknown, false> | undefined; ... 7 more ...; maxProperties?: number | undefined; }'.
      Types of property 'properties' are incompatible.
        Type '{ a: { type: "number"; }; }' is not assignable to type 'PropertiesSchema<T>'.
          Property 'a' is incompatible with index signature.
            Type '{ type: "number"; }' is not assignable to type '{ $ref: string; } | (JSONSchemaType<unknown, false> & { nullable: true; const?: undefined; enum?: readonly unknown[] | undefined; default?: unknown; })'.
              Type '{ type: "number"; }' is not assignable to type '{ oneOf: readonly JSONSchemaType<unknown, false>[]; } & { [keyword: string]: any; $id?: string | undefined; $ref?: string | undefined; $defs?: { [x: string]: JSONSchemaType<Known, true> | undefined; } | undefined; definitions?: { ...; } | undefined; } & { ...; }'.
                Property 'oneOf' is missing in type '{ type: "number"; }' but required in type '{ oneOf: readonly JSONSchemaType<unknown, false>[]; }'.
</code></pre>

</details>
</p>

I've tried just about everything to make it work, only solution right now is to pass a different, less defined, type to JSONSchemaType.

Things I've tried

*  typecasting the schemas
* defining the additional properties as { type: 'string' }
* all manners of redefining the index signature

**Comment by epoberezkin** [comment]
It seems unsupported indeed.

**Comment by ivansieder** [comment]
@epoberezkin are there any plans on enhancing this one? Or is there any better workaround other than specifying a less specific type? Thank you in advance!

**Comment by lgarczyn** [comment]
@ivansieder I just ended up extending the interface (T in the example). It's not as good, but works fine

**Comment by ivansieder** [comment]
@lgarczyn you mean you created a separate interface for the static props and one for the index signature props?

**Comment by lgarczyn** [comment]
not fully separate, the index one extending the static one

**Comment by ivansieder** [comment]
Sadly for my use case I'll have to go for `//@ts-ignore` as it's a nested object and if I'd have to use generics it would get way too nested. Would be awesome to have this implemented, too

**Comment by erikbrinkman** [comment]
I'm intrigued by this, however there are typescript limitations with implementing it. If you define `type Keys = keyof T` what do you get? `string | number`. I'm not going to go into why, but from an inspection perspective, it's not possible for `JSONSchemaType` to determine the explicitly named properties afaik.

The reverse should be possible. I'm not sure if `JTDDataType` supports it, but it probably should.

**Comment by Chucky-ux** [comment]
JTDDataType

**Comment by epoberezkin** [comment]
Going to close it.

The main reason to use JSONSchemaType is to avoid typos in large but common schemas. It doesn’t have to be used for all schemas, and some typescript types would always remain out of scope.
