### ISSUE TITLE
JTD - Schema with discriminator does not compile (mistake in the docs)

### ISSUE THREAD

**Issue by zekth** [ajv-validator/ajv#1593]
Using the example from :
- https://ajv.js.org/guide/getting-started.html
- https://ajv.js.org/json-type-definition.html#discriminator-form

Am i doing something wrong?

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`^8.2.0`

**Your code**

```javascript
const Ajv = require("ajv/dist/jtd");
const ajv = new Ajv();

const schema = {
  discriminator: "version",
  mappings: {
    1: {
      properties: {
        foo: { type: "string" },
      },
    },
    2: {
      properties: {
        foo: { type: "uint8" },
      },
    },
  },
};

const validate = ajv.compile(schema);
const data = {
    version: "1",
    foo: "bar"
}
const valid = validate(data);
if (!valid) console.log(validate.errors);

```

**Validation result, data AFTER validation, error messages**

```
Error: schema is invalid: data/discriminator must NOT have additional properties, data must have property 'ref', data must have property 'type', data must have property 'enum', data must have property 'elements', data must have property 'properties', data must have property 'optionalProperties', data must have property 'mapping', data must have property 'values', data must match a schema in 
union
```

**What results did you expect?**
A successfull compilation

**Are you going to resolve the issue?**
Sorry i have no knowledge in AJV.

**Comment by epoberezkin** [comment]
The correct JTD syntax is `mapping`, not `mappings`: https://runkit.com/esp/6097b21e090157001a802d38

**Comment by epoberezkin** [comment]
It's a mistake in the docs actually.

It is correct here: https://jsontypedef.com/docs/jtd-in-5-minutes/

**Comment by epoberezkin** [comment]
Corrected https://github.com/ajv-validator/ajv/commit/0404a50be13b9079b0a4669e9e2cf04d79011b0c
