### ISSUE TITLE
strongly type data

### ISSUE THREAD

**Issue by jon49** [ajv-validator/ajv#16]
I work with XML Soap calls quite a bit. So all the data comes back as strings. I was wondering if you would like your code to support strongly typing an object or if that would be better to do spin off. Or if some other library would be better suited for this?

**Comment by jon49** [comment]
Found what I was looking for, [`schemasaurus`](https://github.com/AlexeyGrishin/schemasaurus) will do what I need.

**Comment by epoberezkin** [comment]
I was focussing on implementing JSON-Schema standart that schemasaurus does only partially...
You can check the [benchmark](https://github.com/ebdrup/json-schema-benchmark) to see which parts of the standart are not supported in different validators.

**Comment by jon49** [comment]
Thanks. It looks like your library is very good. I was just wondering about a more general purpose tool that is very similar to what json-schema validators already do. It looks like schemasaurus was built with general purpose in mind. I'll evaluate yours for validation though. It looks good!

**Comment by epoberezkin** [comment]
Thanks! Yes, you are right - schemasaurus allows you to create your own tools based on json documents, essentially creating your own processing standard - json validation is almost a side-effect :)
