### ISSUE TITLE
How to validate objects against Nested Schema?

### ISSUE THREAD

**Issue by katmug** [ajv-validator/ajv#160]
My Schema is as below. Zone schema inherits Coordinate schema.

``` json
 "Coordinate": {
    "id": "Coordinate",
    "required":["x","y","z"],
    "properties": {
      "x": {        "type": "number"      },
      "y": {        "type": "number"      },
      "z": {        "type": "number"      }
    }
  },
  "Zone": {
    "id": "Coordinate",
    "required":["name","coordinate"],
    "properties": {
      "name": {        "type": "string"      },
      "coordinates": {        "type": "Coordinate"      }
    }
  }
```

Im trying to validate a object (http request) againt the "Zone" schema using ajv as below: 
`var valid = ajv.validate(schemas.Zone, request);`

Ajv throws the following error:
_Error: schema is invalid:data.properties['coordinates'].type should be equal to one of the allowed values, data.properties['coordinates'].type should be array, data.properties['coordinates'].type should match some schema in anyOf_

How can i get ajv to validate my nested Schema?

**Comment by epoberezkin** [comment]
It's not quite clear what you want to do from the example.

`type` keyword should be a simple type (`string`, `number` etc.) or array of simple types. If you want to make `coordinates` property an array of objects each of which matches the schema Coordinate you need to use keywords `items` and `$ref`:

``` JSON
"Coordinate": { "id": "#coordinate" }
```

and

``` JSON
"coordinates": { "items": { "$ref": "#coordinate" } }
```

See [keywords reference](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md)

**Comment by katmug** [comment]
I have edited the Json in my original comment for clarity.

Im trying to validate a request to the schema **Zone**.  But Zone schema in-turn has a property "coordinates" of type **Coordinate**. Im not able to get this working.

In short, can i have another schema (_which is Coordinate here_) as type in my schema (_i.e in Zone Schema_)?

**Comment by epoberezkin** [comment]
You need to use $ref, as I wrote above.

**Comment by katmug** [comment]
coordinates is not an array. It is just a property of type "Coordinate". 
"Zone": {
"id": "Coordinate",
"required":["name","coordinate"],
"properties": {
"name": { "type": "string" },
**"coordinates": { "type": "Coordinate" }**
}
}
 I have separated the schema Coordinate as it is used in multiple other schema.

**Comment by epoberezkin** [comment]
Without items in this case, but you still need to use $ref.

**Comment by epoberezkin** [comment]
http://code.tutsplus.com/tutorials/validating-data-with-json-schema-part-2--cms-25640

**Comment by manjudr** [comment]
@epoberezkin @katmug 
Please need help on this since I am unclear.

```
{
  "Iname": "xyz",
  "Place1": {
    "P1Name": "abc",
    "Place2": {
      "P2name": "pq"
    }
  }
}
```

How can I write a schema for this nested object structure?
