### ISSUE TITLE
TypeScript Example does not work

### ISSUE THREAD

**Issue by phifa** [ajv-validator/ajv#1603]
![image](https://user-images.githubusercontent.com/3061129/117855854-34257380-b28b-11eb-9c83-53f033d4bf69.png)

Module '"ajv"' has no exported member 'JSONSchemaType'.

I just took the original example from the docs: 

https://ajv.js.org/guide/typescript.html#utility-types-for-schemas

```
import Ajv, {JSONSchemaType} from "ajv"
const ajv = new Ajv()

interface MyData {
  foo: number
  bar?: string
}

const schema: JSONSchemaType<MyData> = {
  type: "object",
  properties: {
    foo: {type: "integer"},
    bar: {type: "string", nullable: "true"}
  },
  required: ["foo"],
  additionalProperties: false
}

// validate is a type guard for MyData - type is inferred from schema type
const validate = ajv.compile(schema)

// or, if you did not use type annotation for the schema,
// type parameter can be used to make it type guard:
// const validate = ajv.compile<MyData>(schema)

const validData = {
  foo: 1,
  bar: "abc"
}

if (validate(data)) {
  // data is MyData here
  console.log(data.foo)
} else {
  console.log(validate.errors)
}

```

**Comment by epoberezkin** [comment]
Ajv definitely exports it, you probably have the previous version installed:

https://github.com/ajv-validator/ajv/blob/master/lib/ajv.ts#L66

Also, please do not submit VSCode screenshots in bug reports - they are not something that can be debugged. The tsc output would be more helpful...

**Comment by mmetan0** [comment]
interestingly this is due to the fact that its not installing the latest version of AJV when npm install ajv executed. not sure why but i had to force for ^7.x version later on from the package.json

**Comment by cre8** [comment]
@phifa I have the same issue. I used eslint that has version 6.X as a dependency. So running npm install ajv will install the 6.X version. Setting the latest version number into the package.json let me install 8.X that exports the type correclty.

**Comment by epoberezkin** [comment]
@cre8 that's a good point, doc's need to have `npm install ajv@8` then...
