### ISSUE TITLE
Trying to compile to ES5 target without success

### ISSUE THREAD

**Issue by shibormot** [ajv-validator/ajv#1607]
Hello, I just tried to compile to ES5 target Ajv v7.2.4 on node v14.17.0 with npm v6.14.13, and also Ajv v8.3.0 on node v16.1.0 with npm v7.11.2 to the same target. My tsconfig.json is:
```
$ cat tsconfig.json 
{
  "extends": "@ajv-validator/config",
  "include": ["lib"],
  "compilerOptions": {
    "outDir": "dist",
    "lib": ["ES5"],
    "types": ["node"],
    "allowJs": true,
    "target": "ES5",
    "resolveJsonModule": true
  }
}
```

Both attempts gave same 7 errors:
```
> ajv@8.3.0 build
> rm -rf dist && tsc && cp -r lib/refs dist && rm dist/refs/json-schema-2019-09/index.ts && rm dist/refs/json-schema-2020-12/index.ts && rm dist/refs/jtd-schema.ts

lib/compile/codegen/index.ts:250:25 - error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
250     const names = super.names
                            ~~~~~

lib/compile/codegen/index.ts:281:27 - error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
281     return addNames(super.names, this.iteration.names)
                              ~~~~~

lib/compile/codegen/index.ts:302:38 - error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
302     const names = addExprNames(super.names, this.from)
                                         ~~~~~

lib/compile/codegen/index.ts:328:27 - error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
328     return addNames(super.names, this.iterable.names)
                              ~~~~~

lib/compile/codegen/index.ts:378:25 - error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
378     const names = super.names
                            ~~~~~

lib/compile/index.ts:229:21 - error TS2569: Type 'Set<SchemaEnv>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
229   for (const sch of this._compilations) {
                        ~~~~~~~~~~~~~~~~~~

lib/compile/validate/dataType.ts:55:7 - error TS2322: Type 'Set<string>' is not assignable to type 'Set<"string" | "number" | "boolean" | "object" | "integer" | "null" | "array">'.
  Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "integer" | "null" | "array"'.
55 const COERCIBLE: Set<JSONType> = new Set(["string", "number", "integer", "boolean", "null"])
         ~~~~~~~~~

Found 7 errors.
```

**Comment by epoberezkin** [comment]
Ajv v7/8 can compile JSON schemas (and JTD schemas) to ES5 code, but I don’t know if it’s possible to compile Ajv itself to be ES5 compatible.

It might be possible by using Babel to transpile JavaScript with polyfills for Map, Set etc. - but I’ve never tried it - I cannot help with that, Ajv from v7 is no longer intended to be used in ES5 environments, only compiled validation code is.

If you must use Ajv itself in ES5 env you need to use v6.x - it should be fully ES5 compatible, but it’s not supported other than for critical security vulnerabilities.

**Comment by shibormot** [comment]
Thank you for clarification. May be your words need to be added to the documentation at https://ajv.js.org/guide/environments.html#es5-environments to make the world better a little?)

**Comment by epoberezkin** [comment]
I guess I did expect it to compile at some point :)

Worth trying with babel... If you do and it works, please post the recipe here.

**Comment by epoberezkin** [comment]
@shibormot Actually you can transpile - see this change in docs, about to merge it #1594

**Comment by shibormot** [comment]
@epoberezkin thank you, I decided to stick with Ajv v6 for now, as I was, because I'm new to Node, transpilation, JS specs, typescript and kitchen of all of that things. I will go deep into it on next big refactoring. Thank you for your lib and good luck)
