### ISSUE TITLE
How to create a custom error message?

### ISSUE THREAD

**Issue by xfg** [ajv-validator/ajv#161]
I read the [docs](http://epoberezkin.github.io/ajv/custom.html#define-keyword-with-validation-function) and try to do a test method:

```
ajv.addKeyword('auth', {
  validate: function (schema, data) {
    this.errors = [{keyword: 'auth', message: 'shoud be authenticated.', params: {keyword: 'auth'}}];
    return false;
  },
  errors: true
});
```

but this don't work. How to make a right?

**Comment by epoberezkin** [comment]
`errors` is a property of a validation function, not of a context (assuming it is a synchronous function)

**Comment by xfg** [comment]
Can example? I don't understand.

**Comment by epoberezkin** [comment]
```
ajv.addKeyword('auth', {
  validate: function validate (schema, data) {
    validate.errors = [{keyword: 'auth', message: 'shoud be authenticated.', params: {keyword: 'auth'}}];
    return false;
  },
  errors: true
});
```

**Comment by xfg** [comment]
Thanks, it work.

**Comment by epoberezkin** [comment]
You're welcome!

**Comment by moshfeu** [comment]
> validate.errors = [{keyword: 'auth', message: 'shoud be authenticated.', params: {keyword: 'auth'}}];

PLEASE, add this to the [docs](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords) it's not that clear there.

**Comment by hassan-jahan** [comment]
Worked 3 hours to find this :|

**Comment by moshfeu** [comment]
Same here. so I wrote a medium post. Hopefully will help to find it earlier :)

https://medium.com/@moshfeu/test-json-schema-with-ajv-and-jest-c1d2984234c9

**Comment by akshayjai1** [comment]
https://stackoverflow.com/questions/49212708/ajv-custom-error-message-for-type/64714691#64714691

**Comment by rofrol** [comment]
Example repo https://github.com/rofrol/ajv-regexp-errormessage-example

**Comment by VassuRaw** [comment]
> `errors` is a property of a validation function, not of a context (assuming it is a synchronous function)

And how to for async validate function case?

**Comment by steve2507** [comment]
[The docs](https://ajv.js.org/api.html#validation-errors) are a bit vague but for async handlers;
> In case of [asynchronous validation](https://ajv.js.org/guide/async-validation.html), the returned promise is rejected with exception Ajv.ValidationError that has errors property.

The following should work;
```js
  schemaValidator.addKeyword({
    keyword: 'myValidator',
    async: true,
    type: 'string',
    validate: async (schema, data) => {
      if (data === 'success') {
        return true;
      }

      const errorMessage = 'My error message.';
      const err = new Error(errorMessage);
      err.errors = [{
        code: 123,
        message: errorMessage,
      }];

      throw err;
    },
  });
```

**Comment by prieston** [comment]
To anyone still struggling with this, in the [docs](https://ajv.js.org/keywords.html#common-attributes-of-keyword-definitions) they state to use the error property so something like this for my case:

```
ajv.addKeyword("isNotEmpty", {
  type: "string",
  validate: function (schema, data) {
    if (typeof data === "string") return data.trim() !== "";
    return data != null;
  },
  error: {
    message: "property is required and should not be empty",
  },
});
```

**Comment by vincerubinetti** [comment]
> ```
> ajv.addKeyword('auth', {
>   validate: function validate (schema, data) {
>     validate.errors = [{keyword: 'auth', message: 'shoud be authenticated.', params: {keyword: 'auth'}}];
>     return false;
>   },
>   errors: true
> });
> ```

Just to be clear, only this very specific syntax works. This behavior is very confusing and weird design.

---

❌ does not work

```js
{
  validate: () => { validate.errors = [] }
}
```

❌ does not work

```js
{
  validate() { validate.errors = [] }
}
```

❌ does not work

```js
{
  validate() { this.errors = [] }
}
```

❌ does not work

```js
{
  validate: function validate() { this.errors = [] }
}
```

✅ does work

```js
{
  validate: function validate() { validate.errors = [] }
}
```

And then apparently the behavior is different when the function is async. Huh????? [The docs even as they are today](https://ajv.js.org/keywords.html#define-keyword-with-validate-function) are still not clear.
