### ISSUE TITLE
Why not use strict equals for const when the value on the right hand side isn't an object?

### ISSUE THREAD

**Issue by SoAsEr** [ajv-validator/ajv#1612]
**What version of Ajv you are you using?**
8.2.0
**What problem do you want to solve?**
when using {const: true} the resulting codegen still pulls in deepequals and calls that function. This even happens when I do {const: true, type: "boolean"}
**What do you think is the correct solution to problem?**
I think if value of const is a literal and not an object, it would probably be better to use strict equality (===)
**Will you be able to implement it?**
Probably, I haven't dug around the code, but I am willing to put the time in.

**Comment by SoAsEr** [comment]
Sorry, just noticed this is a known thing in the code 
https://github.com/ajv-validator/ajv/blob/325ac9a6396baed3eaf588ee80aed3b1f23d12dd/lib/vocabularies/validation/const.ts#L20-L21

**Comment by epoberezkin** [comment]
PR is welcome, it should still support $data reference, so it won’t be one line.

**Comment by SoAsEr** [comment]
Working on it now
