### ISSUE TITLE
Validating particular index objects inside an array of objects

### ISSUE THREAD

**Issue by saswat3115** [ajv-validator/ajv#1619]
```
schema: {
    type: "array",
    items: {
      type: "object",
      properties: {
         field1: { type: "string" },
         field2: { type: "string" }
       },
      required: [ "field2" ]
  }
}
```

```
data : [ 
  { field1: "value1", field2: "value2" },
  { field1: "value1" },
]
```

Above is the schema and the data.
Here I want to validate "required" field for only first index in array. 
                          OR
I want to run validator for particular specific indexs. Is there any way to do this in avj ?

**Comment by epoberezkin** [comment]
JSON Schema supports array form for items - see JSON Schema docs on site.

**Comment by himpan1998** [comment]
JSON support array but if I want to create json schema validator for multiple items then how can I make array of objects to insert multiple items inside array
