### ISSUE TITLE
Any method which will discard the invalid data from data object against a schema (if/else/then conditions)

### ISSUE THREAD

**Issue by saswat3115** [ajv-validator/ajv#1623]
```
schema = {
  type: "object",
 properties: {
    firstName: {
       type: "string"
     }
  },
  if: {
    { properties: { firstName: { const: "abc" } } }
  },
  then: {
    { properties: { lastName: { type: "string" } } }
  }
}
```

```
data = {
  firstName: "def",  // other than "abc"
  lastName: "some value"
}
```

If you observe the `data` is not satisfying the `if` condition in schema but still `data` has `lastName` value

My requirement is to have a method which will take these two as parameter and return` { firstName: "def" }` .  (Discarding the `lastName` field becasue the conditions is not matched)

**Comment by SivaGanesh56** [comment]
+1

**Comment by epoberezkin** [comment]
This logic is easier to express in the application code, rather than achieve via the schema and general purpose library - it's quite specialised...

Please look at `discriminator` keyword and `removeAdditional` option - maybe combining them in some way would help you achieve what you need.
