### ISSUE TITLE
No tracking of patternProperties with true schemas as their values

### ISSUE THREAD

**Issue by P0lip** [ajv-validator/ajv#1625]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.5.0

**Ajv options object**

```javascript
{}
```

**JSON Schema**

```json
{
  "type": "object",
  "patternProperties": {
    "^x-": true
  },
  "unevaluatedProperties": false
}
```

**Sample data**

```json
{
  "x-internal": false
}
```

**Your code**

```javascript
import Ajv from 'ajv/dist/2020';

const ajv = new Ajv();

const schema = {
  type: 'object',
  patternProperties: {
    '^x-': true,
  },
  unevaluatedProperties: false,
};

const validate = ajv.compile(schema);
validate({ 'x-internal': false });
```

**Validation result, data AFTER validation, error messages**

```js
[
  {
    instancePath: '',
    schemaPath: '#/unevaluatedProperties',
    keyword: 'unevaluatedProperties',
    params: { unevaluatedProperty: 'x-internal' },
    message: 'must NOT have unevaluated properties'
  }
]

```

**What results did you expect?**

No errors

**Are you going to resolve the issue?**

Yes

---

Very likely to be caused by https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/applicator/patternProperties.ts#L16

**Comment by epoberezkin** [comment]
merged, will be in 8.6.0
