### ISSUE TITLE
validating data within Maps and Sets

### ISSUE THREAD

**Issue by ssube** [ajv-validator/ajv#1634]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

v8.5.0

**Your typescript code**

```typescript

export interface NestedMap {
  foo: string;
  bar: Map<string, string>;
}

export const MAP_SCHEMA: JSONSchemaType<NestedMap> = {
  type: 'object',
  properties: {
    foo: {
      type: 'string',
    },
    bar: {
      type: 'object',
      properties: {
        clear: {
          type: 'object',
        },
        delete: {
          type: 'object',
        },
        forEach: {
          type: 'object',
        },
        // some methods omitted
        values: {
          type: 'object',
        },
      },
      required: [],
    },
  },
  required: ['foo', 'bar'],
};
```

The schema type expects all of the methods on `Map` to be specified as objects, but does not provide a type for the data within the `Map`.

**Typescript compiler error messages**

Leaving out some of the methods causes:

```
Types of property 'properties' are incompatible.
  Property 'delete' is missing in type '{ clear: { type: "object"; }; forEach: { type: "object"; }; has: { type: "object"; }; get: { type: "object"; }; set: { type: "object"; }; size: { type: "number"; }; entries: { type: "object"; }; keys: { type: "object"; }; values: { ...; }; }' but required in type 'UncheckedPropertiesSchema<Map<string, string>>'.  ts(2322)
```

**Describe the change that should be made to address the issue?**

I'm not sure how to validate the data within the `Map` (or `Set`): `keys` and `values` are both required to be present in the schema, but return iterators. I checked the docs and additional keywords repo, but have not found a conclusive answer.

In general, I would expect `JSONSchemaType` to omit methods, some kind of `T extends Function ? never : ...` clause in the mapped type might do the trick. A `type: 'object'` is not really meaningful for a method (is it?), and on a whim I tried to define the type of `values`, which is allowed but does not seem right:

```typescript
        values: {
          type: 'object',
          properties: {
            [Symbol.iterator]: {
              type: 'array',
              items: {
                type: 'string',
              }
            }
          },
          required: [],
        },
```

Within each of the methods (like the above), `required` is `Array<never>`.

Is this a case for user-defined keywords, or something that needs to be changed within the typedef?

**Are you going to resolve the issue?**

Happily, if I can get some advice on the correct method.

**Comment by epoberezkin** [comment]
JSONSchema is intended for validation of plain JSON object that were created by JSON.parse.

You could define separate validation keywords to validate Maps (but they won't be supported by JSONSchemaType utility type).

Btw, using JSONSchemaType is completely optional - you can define schemas as plain objects and use type parameters with ajv.compile to have validation function act as a type guard.

**Comment by ssube** [comment]
Ok, I think that makes sense. These objects are being parsed from YAML, which is _close_ to the intended usage, but js-yaml allows custom and complex types. Setting up keywords for those should be easy enough.

The type-checking done by JSONSchemaType is really handy, fwiw. I've been maintaining schemas in JSON and YAML files for the most part, but having the TS compiler do some validation is great.
