### ISSUE TITLE
maximum call stack trace on new browsers

### ISSUE THREAD

**Issue by powisss** [ajv-validator/ajv#1644]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
All versions.

**Ajv options object**

var ajv = new Ajv({ useDefaults: true, removeAdditional: true } )

**JSON Schema**

all schemas small/large (was working no problems before)

var 06schema= require('ajv/lib/refs/json-schema-draft-06.json');
var ajv = new Ajv({ useDefaults: true, removeAdditional: true } )
avj.addMetaData(06schema)
addDefaultsAndRemoveAdditional = avj.compile(schema)
addDefaultsAndRemoveAdditional(object)

**What results did you expect?**
object to be autopopulated, as it was before.

**Are you going to resolve the issue?**
Chances are no, trying currently.
NOTE: error shows up mostly on new versions of chrome/firefox. Both in linux and windows environment. There are cases where newset version still has no error.

**Comment by epoberezkin** [comment]
Please send the full code sample, with schema and data.

**Comment by epoberezkin** [comment]
closing, please resubmit with a complete code sample
