### ISSUE TITLE
It is impossible to use AJV in ESModule-based bundled frontend applications.

### ISSUE THREAD

**Issue by Qix-** [ajv-validator/ajv#1645]
**The version of Ajv you are using**

8.6.0

**The environment you have the problem with**

Rollup + Browsers + ESModules

**Your code (please make it as small as possible to reproduce the issue)**

```javascript
import Ajv from 'ajv';
```

**If your issue is in the browser, please list the other packages loaded in the page in the order they are loaded. Please check if the issue gets resolved (or results change) if you move Ajv bundle closer to the top**

N/A

**Results in node.js v8+**

N/A

**Results and error messages in your platform**

N/A

---

Modern bundled web-apps are moving to ES Modules (`.mjs`) for everything. As it stands, AJV cannot be bundled using e.g. Rollup and `import` statements. Fullstop.

I have tried:

- `import Ajv from 'ajv'` using just the default `ajv` package.
- `import * as Ajv from 'ajv'`
- Some other ugly hacks to try to get imports working.
- Using `@rollup/plugin-commonjs` to import the CommonJS module, which results in the Node version it seems (getting errors about missing `stream`, `http`, `Url`, etc.)
- Forking and Re-compiling to emit ESModules from `tsc` (and then renaming them to `.mjs` - see the ridiculous 4-year-old issue over at microsoft/typescript#18442) - not sure if this is a Typescript compiler issue or AJV's, but `import`s would need to use the full path, including `.mjs`.

Literally nothing I try works. I don't really come across this issue with many modules so I have to assume it's AJV trying to be "hybrid" when in reality it needs to ditch CommonJS and do a major version bump (or something of that sort).

**Comment by Qix-** [comment]
Just my luck. Been banging my head on this for hours and then five minutes after resorting to this ticket, I find the solution.

AJV uses JSON imports, which are a hack from the CommonJS days and do not translate to ESModules. In my Rollup config, I had to add `@rollup/plugin-json`. Then AJV successfully imported.

I will close this as the original claim of being "impossible" is not true, but I really urge the maintainers to consider refreshing the codebase a bit and removing some old sores such as JSON imports and the like.

**Comment by harleylang** [comment]
I found this repository with pre-bundled bundles that can be imported easily imported on the client side https://github.com/ajv-validator/ajv-dist

    import 'ajv-dist/dist/ajv7.bundle.js'; 
    import schema from './schema';
    const Ajv = (window as any).ajv7;
    // do the thing

**Comment by gerardogalvez** [comment]
@Qix- which other plugins did you have in your Rollup config? I have @rollup/plugin-node-resolve and added @rollup/plugin-json per your suggestion but I keep getting the error:

`Error: 'default' is not exported by node_modules/ajv/dist/ajv.js`

I'm importing with `import Ajv from 'ajv'`.

**Comment by jodigiordano** [comment]
Working `rollup.config.js`:

```ts
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default {
  input: "dist/index.js",
  output: {
    file: "dist/bundle.js",
    format: "iife",
  },
  plugins: [commonjs(), json(), nodeResolve()],
};
```
