### ISSUE TITLE
Unable to use Ajv with esModuleInterop set to true

### ISSUE THREAD

**Issue by patrickmead** [ajv-validator/ajv#1647]
**The version of Ajv you are using**
8.6.0
ajv-formats 2.1.0

**The environment you have the problem with**
Node v12.13.0
 typescript 4.0.2
 tsc for compiles

**Your code (please make it as small as possible to reproduce the issue)**
```
import Ajv from 'ajv'
import addFormats from 'ajv-formats'
const ajv = new Ajv({coerceTypes: true})
addFormats(ajv)
return ajv.compile(schema)
```

**Results and error messages in your platform**

Setting `esModuleInterop` to false resolves the error below but it should be set to true for this project.

```
 node_modules/ajv/lib/compile/resolve.ts:5:1
    5 import * as traverse from "json-schema-traverse"
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

node_modules/ajv/lib/compile/resolve.ts:101:38 - error TS7006: Parameter 'sch' implicitly has an 'any' type.

101   traverse(schema, {allKeys: true}, (sch, jsonPtr, _, parentJsonPtr) => {
                                         ~~~

  node_modules/ajv/lib/compile/resolve.ts:4:1
    4 import * as equal from "fast-deep-equal"
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
```

**Comment by epoberezkin** [comment]
Firstly, ajv requires TS >=4.2.3 to compile.

Secondly, not sure why your build tries to recompile ajv - normally when you `import Ajv from 'ajv'` it would use compiled JS code as per package.json (and it still won't work with older TS).

Finally it does work with esModuleInterop here - maybe post your tsconfig?

**Comment by patrickmead** [comment]
First of all, thank you very much for the reply.

> Secondly, not sure why your build tries to recompile ajv

I agree. I'm looking into that as well. 

> Firstly, ajv requires TS >=4.2.3 to compile.

Upgrading my TS version didn't work. However, after I posted I created a very simple project to aid in debugging.  It sets esModuleInterop to true and works fine. It uses TS 4.3.2. 

Given that I have a very simple project working in my environment, I can use that to resolve the build issues in my "real" project and close this defect 

Thanks again.

**Comment by patrickmead** [comment]
Just to follow up, incorrect imports caused the compile error in my project.

```
import Ajv from 'ajv'
import { ValidateFunction } from 'ajv/lib/types/index'
```

This is the correct import. 

`import Ajv, { ValidateFunction } from 'ajv'`

**Comment by epoberezkin** [comment]
great - yes, you need to import either from the module or from "ajv/dist" if you need some internals. Most useful stuff is re-exported on the top level though.
