### ISSUE TITLE
Consider linking to ajv-inspector

### ISSUE THREAD

**Issue by e0ipso** [ajv-validator/ajv#166]
I had to create a project to inspect schemas and I based it on `ajv`. Maybe you want to link to that project on the `README.md` for `ajv`.

https://github.com/e0ipso/ajv-inspector

**Comment by epoberezkin** [comment]
cool, thank you, I will have a look

**Comment by epoberezkin** [comment]
Hi, sorry it takes some time to comment...

At the moment the package seems to have quite a few undocumented limitations. Please see the issues I've submitted.

Happy to reference it here once the limitations are removed or documented. Also ci build / test coverage would be good.

Closing the issue for now, please re-open when the issues are addressed.
