### ISSUE TITLE
Warning: these parameters are deprecated, see docs for addKeyword

### ISSUE THREAD

**Issue by a-tonchev** [ajv-validator/ajv#1665]
I get this message when I initialize ajv, my code looks like this:

```
import Ajv from 'ajv-draft-04';
import AjvBson from 'ajv-bsontype';
import AjvErrors from 'ajv-errors';

const ajv = new Ajv({ allErrors: true, strictTypes: false });
AjvBson(ajv);
AjvErrors(ajv);
```

I am using 

ajv 8.6.0
ajv-bsontype 1.0.7
ajv-draft-04 1.0.0
ajv-errors 3.0.0

**Comment by epoberezkin** [comment]
this is an issue with ajv-bsontype that uses deprecated API of ajv.addKeyword method.

**Comment by epoberezkin** [comment]
specifically, here: https://github.com/BoLaMN/ajv-bsontype/blob/13540ee0e38f916971744414b8eae4fc3b9463f3/index.js#L98
