### ISSUE TITLE
add support for `type: "symbol"`

### ISSUE THREAD

**Issue by sokra** [ajv-validator/ajv#1675]
**What version of Ajv you are you using?**

6.12.6 and 8.6.0

**What problem do you want to solve?**

I want to allow passing Symbols as values in the webpack configuration.

**What do you think is the correct solution to problem?**

``` json
{
  "type": "symbol"
}
```

For symbols in JS `typeof Symbol() === "symbol"`, so I think that makes most sense here. But Symbols are not part of JSON, so maybe it might be better as ajv plugin?

**Will you be able to implement it?**

If you point me to the file where `type` is implemented, I think so

**Comment by epoberezkin** [comment]
hey - this would be against JSON Schema spec, it actually already exists as [typeof in ajv-keywords](https://github.com/ajv-validator/ajv-keywords#typeof) - would that work?

EDIT "this" = "extending type"

**Comment by sokra** [comment]
Yes that's perfect
