### ISSUE TITLE
Question: Is there a way to supply multiple schemas for compilation?

### ISSUE THREAD

**Issue by wcaneira** [ajv-validator/ajv#1680]
I have a set of growing and somewhat redundant schemas that I'd like to break down into smaller "main" schemas with _shareable_ "subschemas" using the `$ref` keyword.  The schemas needed by the application would all be known at initialization time; I have no need for dynamic loading of schemas.  

With my current (large) schemas, I call the `compile` function once at initialization/module load time as suggested [here](https://ajv.js.org/guide/managing-schemas.html#re-using-validation-functions).

```js
    const ajv = new Ajv({ allErrors: true })
    const validate = ajv.compile(myBigOriginalSchema1) 
```

After reading [the documentation](https://ajv.js.org/guide/combining-schemas.html#a-name-ref-a-combining-schemas-with-ref) and the API reference I'm unclear (I'm sorry) on whether there is a way to have `ajv` compile multiple schemas at once (or whether that is even advisable).  I notice the `compile` function only takes a single schema.

For example, I tried this, with `addSchema`:
```js
    const ajv = new Ajv({ allErrors: true })
    ajv.addSchema(mySubschema1)
    ajv.addSchema(mySubschema2)
    const validate = ajv.compile(mySmallerMainSchema1) 
```

...and I looking at the source, I don't believe it compiles the other schemas added via `addSchema` at the time of the `compile` call.

I also read [here](https://ajv.js.org/api.html#ajv-addschema-schema-object-object-key-string-ajv) that the `addSchema` function itself doesn't actually compile the schemas by design, until they are first needed.  In my use case I KNOW these subschemas will very likely used on the first validation attempt.  Breaking the large single schema down into a bunch (e.g. a dozen) subschemas will likely mean I am deferring most/all the compilation to the first validation attempt instead of compiling at initialization.  Is my understanding correct?  Is what I have above the most efficient approach?  Is there a way to compile multiple schemas at initialization time instead?

I also experimented with the following, but I'm not sure it's any different...I thought the constructor simply called `addSchema` on each schema given:

```js
    const ajv = new Ajv({ allErrors: true, schemas: [mySubschema1, mySubschema2] })
    const validate = ajv.compile(mySmallerMainSchema1) 
```

Just to further try and illustrate what I'm asking about, I almost want to do something like this, but the `compile` function needs a schema argument:

```js
    const ajv = new Ajv({ allErrors: true, schemas: [mySmallerMainSchema1, mySubschema1, mySubschema2] })
    const validate = ajv.compile() //needs a schema here, obviously
```

...OR like this, but I know this argument isn't supported either:

```js
    const ajv = new Ajv({ allErrors: true })
    const validate = ajv.compile({ schemas: [mySmallerMainSchema1, mySubschema1, mySubschema2] })  //only one allowed
```

Any advice is appreciated.  And if I am missing the point of how subschemas and `$ref` are supposed to be used, please let me know.

Thank you for creating & maintaining a useful library in `ajv`.

**Comment by epoberezkin** [comment]
There is no way to compile multiple schemas at once via the API - the reason addSchema does not compile them is to allow for mutual references between the schemas.

The usual approach to add multiple schemas is to either use `addSchema` multiple times or pass them via options - you are right, it simply calls addSchema under the hood - and then use `getSchema` with schema ref (schema $id member) that would compile and return compiled schema functions. That can be useful to identify any errors in schemas that would otherwise only come up at compilation.

Another approach to compile multiple schemas that can be better is to compile them at build time (as they are all static in your case) with standalone validation code - see the reference on it.

**Comment by wcaneira** [comment]
Thank you @epoberezkin for responding, I appreciate it.

In regard to your first suggestion:
> and then use getSchema with schema ref (schema $id member) that would compile and return compiled schema functions

Do you mean something like this?  I tested it and it seems to work functionally, but I'm not sure how to tell if the compliation optimizations are happening or not
```js
   const ajv = new Ajv({ allErrors: true })
    ajv.addSchema(mySubschema1, 'sub1')
    ajv.addSchema(mySubschema2, 'sub2')
    ajv.getSchema('sub1')  //force a compilation using key or $id
    ajv.getSchema('sub2')  //force a compilation using key or $id
    const validate = ajv.compile(mySmallerMainSchema1)  //I still only care about THIS validation function from the "main" schema
```

Also, per your second suggestion:

> compile them at build time (as they are all static in your case) with standalone validation code

...I read about the [standalone validation code option](https://ajv.js.org/standalone.html) and I actually think it sounds great.  But I neglected to mention to you (I apologize) that I also have user-defined keywords in my JS, and I noticed that the standalone code validation feature [is limited](https://ajv.js.org/standalone.html#configuration-and-limitations) to `code` and `macro` user-defined keywords, and we presently use `validate` functions to do a range of things from business rules/IF conditionals up to more complex async HTTP service calls to validate the given data.  I think `macro` only works with rules that can be expressed in JSON schema (so I don't think that will work for me), and I'm guessing using `code` for these cases will be equally if not more difficult.

Am I correct in my understanding that standalone will not work with `validate` user-defined keywords?

Any feedback is appreciated.

**Comment by epoberezkin** [comment]
> Do you mean something like this?

yes

> I'm not sure how to tell if the compliation optimizations are happening or not

not sure, which optimizations? It should all work correctly like that.

> Am I correct in my understanding that standalone will not work with validate user-defined keywords?

yes, they are not supported. Re-implementing them as `code` is always possible - you can check the examples in ajv-keywords

**Comment by wcaneira** [comment]
Thank you again for your quick response.

> not sure, which optimizations? It should all work correctly like that.

My meager understanding of `ajv` is that the compilation step turns my JSON schemas into actual JS code.  All I was saying is that in the `addSchema`/`getSchema` example, there isn't really any perceptible way for me (AFAIK) as a consumer of `ajv` to see any real difference in the behavior (the code works with & without `getSchema`, and I don't have a profiler setup to measure performance diffs) ...so I just wanted to ask if my approach was correctly compiling those subschemas, and that it was the best I could do in terms of efficiency. :-)

At this point, if the `addSchema`/`getSchema` approach (at module initialization, not first validation request time) is an acceptable/efficient approach, I may try that.  

Switching to standalone validation will require a bunch of refactoring of my code, and if I understand correctly, the effect would be the same as `addSchema`/`getSchema`.  

I'm looking over the `ajv-keyword` examples (thank you) of `code` functions, and I'm still trying to understand how I'd convert a `validate` function that implements an HTTP service request into `code`.  I'm struggling to see how much plain JS I can write, versus codegen/templated code.  I'll keep looking and try maybe playing with a sample.

**Comment by epoberezkin** [comment]
Yes, it’s all the same compilation - you can either use compile with the actual schema, or getSchema with its reference - it produces the same results.

**Comment by wcaneira** [comment]
I have a sample working with `addSchema/getSchema`, so I can close this issue, but before I do, one related follow-up, please - are `code` functions appropriate for database/HTTP service call validation?  I see your range example but I feel like that's a schema-based validation rule with no external dependencies.  I'm struggling to see how my use case would be a good fit with a function that ends with `ctx.fail` or `ctx.pass`  and string templates.  Is a `validate` function (what I'm currently using) more appropriate for database/HTTP service-based validation?

This link was broken so I couldn't see the additional examples
![image](https://user-images.githubusercontent.com/47794014/125319220-8e34ca80-e308-11eb-9167-2c9219edfa7f.png)

I assume it leads to the `ajv-keyword` examples you mentioned earlier, which I did look over, but I only see a couple examples there, and I'm still unclear.  I'm sorry.

I'll close this issue after receiving your reply.

**Comment by epoberezkin** [comment]
This is the folder where you can see the examples: https://github.com/ajv-validator/ajv/tree/master/lib/vocabularies/validation

> are code functions appropriate for database/HTTP service call validation

they are used for all standard keywords, but they are only used during schema compilation. HTTP service call validation is the main use case, it’s all ok.
