### ISSUE TITLE
how to compare two fields value

### ISSUE THREAD

**Issue by z7658329** [ajv-validator/ajv#1688]
{
 type: "object",
properties: {
   minAge: {type: "number"},
   maxAge: {type: "number"}
}
}

how can i confirm  maxAge must bigger than minAge ?

**Comment by CocaColf** [comment]
Hi @z7658329 :

you can use `$data`.

```js
const ajv = new Ajv({$data: true})

const schema = {
    type: "object",
    properties: {
        minAge: {
            type: "number"
        },
        maxAge: {
            type: "number",
            minimum: {"$data": "1/minAge"}
        }
    }
}

ajv.validate(schema, {
    minAge: 10,
    maxAge: 5
})
```

docs shows [here](https://ajv.js.org/guide/combining-schemas.html#data-reference)

**Comment by epoberezkin** [comment]
@CocaColf thanks
