### ISSUE TITLE
How to return the property in question

### ISSUE THREAD

**Issue by kaykhancheckpoint** [ajv-validator/ajv#1692]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`8.6.2`

**Ajv options object**

```javascript
{ allErrors: true }
```

**JSON Schema**

```json
{
   "type":"object",
   "properties":{
      "rank":{
      "type":"string"
      },
      "entity_types":{
         "type":[
            "string",
            "array"
         ]
      },
      "country":{
         "type":"string",
         "nullable":true
      },
      "region":{
         "type":"string",
         "nullable":true
      },
      "start_date":{
         "type":"string"
      },
      "end_date":{
         "type":"string"
      },
      "top":{
         "type":"string",
         "nullable":true
      }
   },
   "required":[
      "rank",
      "entity_types",
      "start_date",
      "end_date"
   ],
   "additionalProperties":false
}
```

**Sample data**

```json
rank=popularity&entity_types=person&region=Europe&country=Germany&end_date=2021-06-15&top=10
```

**Your code**

```javascript
    const validate = ajv.compile(LeaderboardQuerySchema);
    if (validate(req.query)) {
        console.log("NO ERROS");
    } else {
        console.log(validate.errors);
    }
```

**Validation result, data AFTER validation, error messages**

```
[
  {
    instancePath: '',
    schemaPath: '#/required',
    keyword: 'required',
    params: { missingProperty: 'start_date' },
    message: "must have required property 'start_date'"
  },
  {
    instancePath: '/top',
    schemaPath: '#/properties/top/type',
    keyword: 'type',
    params: { type: 'number' },
    message: 'must be number'
  }
]

```

**What results did you expect?**

Its difficult to determine what the property in question for each error is referring to. In the old version i used `dataPath` but in the newer version its no longer available. For the first error i have to get `params.missingProperty` to be able to get the property in question `start_date` and the for the second error i have to parse instancePath to get the property in question `top`.  My problem is there is no consistent way to display the property in question back to the user. Is there some way i can return the property as a simple as possible. e.g 

```
[
  {  property: start_date, message: "must have required property 'start_date"}
  {  property: top, "must be number" },
]
```

**Comment by epoberezkin** [comment]
> Its difficult to determine what the property in question for each error is referring to

it's a conscious design decision to report missing properties as errors on the object level, this will not change for many reasons. You need application level code/function that maps how errors are reported from ajv to how you need them reported in your application - it's very straightforward, error parameters for all keywords are documented here: https://ajv.js.org/api.html#error-objects

You can also look at ajv-errors - it can also be used to change error reporting.

**Comment by kaykhancheckpoint** [comment]
@epoberezkin I don't quite understand what you mean, i'm not referring to any specific type of error. i fully understand that i would need to map it into my own schema. 

My main question has been how do i know for each error what the original field name was e.g `start_date` and `top` because for each error in the output below its difficult to extract. For each object in the error array is there a way to get the original field/`property` name?.

```
     for (const err of validate.errors as DefinedError[]) {
            console.log(err);
        }
```

**output**

```
{
  instancePath: '',
  schemaPath: '#/required',
  keyword: 'required',
  params: { missingProperty: 'start_date' },
  message: "must have required property 'start_date'"
}
{
  instancePath: '/top',
  schemaPath: '#/properties/top/type',
  keyword: 'type',
  params: { type: 'number' },
  message: 'must be number'
}
```

**What i want to build**

```
[
  {  property: "start_date", message: "must have required property 'start_date"}
  {  property: "top", message: "must be number" },
]
```

**Comment by epoberezkin** [comment]
This property name is available is error.params.missingProperty for “required” keyword error.

**Comment by kaykhancheckpoint** [comment]
> This property name is available is error.params.missingProperty for “required” keyword error.

Ye... thats what i already know
