### ISSUE TITLE
$schema is not supported

### ISSUE THREAD

**Issue by sabrineChe** [ajv-validator/ajv#1693]
I'm using ajv7 and trying to validate this schema
`{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "title": "Title",
            "description": "Title of object."
        }
    }
}`
ajv complains with the error no schema with key or ref `http://json-schema.org/draft/2019-09/schema#`
I got the same error when replacing `http` with `https`

**Comment by epoberezkin** [comment]
it must be "https://json-schema.org/draft/2019-09/schema", not http

**Comment by sabrineChe** [comment]
Even with `https` it doesn't work.

**Comment by epoberezkin** [comment]
Are you importing ajv from ajv/dist/2019? If not - this metaschema won’t be available

**Comment by sabrineChe** [comment]
I'm importing the ajv7 using this link: `https://cdnjs.cloudflare.com/ajax/libs/ajv/7.2.1/ajv7.min.js` and i'm calling it in JS like that: `const ajv = new ajv7.default({strict: false, allErrors: true});`

**Comment by epoberezkin** [comment]
You need a separate bundle with draft-2019-09 support
