### ISSUE TITLE
Validate method is taking long time to return values on large json data

### ISSUE THREAD

**Issue by hsnassaad** [ajv-validator/ajv#1697]
I am creating a typescript npm package that will read json files (that have different types of data) and then validate their content against predefined `json-schemas`.

So for example I have this file, that has this kind of data (I have removed some of the objects just for the sake of the example if you want me to provide all the data please let me know) :

```
[
    {
        "numberVerification": [
            {
                "longNumber": 281474976710655
            }
        ]
    },
    {
        "metaData": [
            {
                "name": "nodes",
                "elementCount": 155,
                "idCounter": 155,
                "version": "1.0",
            },
            {
                "name": "edges",
                "elementCount": 312,
                "idCounter": 312,
                "version": "1.0",
            },
            {
                "name": "networkAttributes",
                "elementCount": 14,
                "idCounter": 14,
                "version": "1.0",
            },
            {
                "name": "nodeAttributes",
                "elementCount": 330,
                "idCounter": 330,
                "version": "1.0",
            },
            {
                "name": "edgeAttributes",
                "elementCount": 3120,
                "idCounter": 3120,
                "version": "1.0",
            },
            {
                "name": "cartesianLayout",
                "elementCount": 155,
                "idCounter": 156
            },
        ]
    },
    {
        "nodes": [
            {
                "@id": 0,
                "n": "TYK2",
                "r": "uniprot:P29597"
            },
            {
                "@id": 1,
                "n": "ISGF3 complex",
                "r": "signor:SIGNOR-C124"
            },
            {...}
        ]
    },
    {
        "edges": [
            {
                "@id": 0,
                "s": 0,
                "t": 1,
                "i": "up-regulates activity"
            },
            {
                "@id": 1,
                "s": 2,
                "t": 1,
                "i": "up-regulates activity"
            },
            {...}
        ]
    },
    {
        "nodeAttributes": [
            {
                "po": 0,
                "n": "type",
                "v": "protein"
            },
            {
                "po": 0,
                "n": "location",
                "v": "cytoplasm"
            },
            {...}
        ]
    },
    {
        "edgeAttributes": [
            {
                "po": 0,
                "n": "citation",
                "v": [
                    "pubmed:15120645"
                ],
                "d": "list_of_string"
            },
            {
                "po": 0,
                "n": "mechanism",
                "v": "phosphorylation"
            },
            {...}
        ]
    },
    {
        "cartesianLayout": [
            {
                "node": 0,
                "x": 97.73626669665249,
                "y": -114.99468800778627
            },
            {
                "node": 1,
                "x": 307.72737757573987,
                "y": 4.091777979752425
            },
            {...}
        ]
    },
    {
        "status": [
            {
                "error": "",
                "success": true
            }
        ]
    }
]
```
so I have created a schema for each object in the array (numberVerification, metadata, nodes, nodesAttributes...).
And then i have created a schema called `_network` that has all the other schemas as reference.

and because I want to get the location of the error I am using `json-source-map`
```
    const sourceMap = jsonMap.parse(networkFile);
    const data = sourceMap.data;
    const pointers = sourceMap.pointers;
```

and then I am creating a new ajv instance and then I validate against the data

```
  ajv = getAjvInstance();
  validate = getValidateInstance();
  console.log("start valdiating...");
  const valid = validate(data);

  if (!valid) {
    const errors = validate.errors?.filter(error => error.keyword === 'errorMessage');
    errors?.map((error) => {
        const errorPointer = pointers[error.instancePath];
        const splittedMessage = error.message!.split(':', 2);
        addError(splittedMessage[0], splittedMessage[1], [errorPointer]);
    });
  }
```

```
function getAjvInstance() {
  if (!ajv) {
    ajv = new Ajv({
      allErrors: true,
      strictTypes: false,
    });
    require('ajv-errors')(ajv);
  }
  return ajv;
}
```

```
function getValidateInstance() {
  if(!validate) {
    validate = ajv.compile(_network);
  }
  return validate;
}
```

**What version of Ajv you are you using?**
    "ajv": "^8.6.0",
    "ajv-errors": "^3.0.0",
    "json-source-map": "^0.6.1",

**What problem do you want to solve?**
When reading big json files (10MB or larger) the validation function freeze the terminal, so I am forced to kill the terminal using `Ctrl+C`, although  when trying it on data of size ~500Kb the performance was excellent and it return error messages as it should. 

**Note:** I am not using `$id` in any of the schemas, because I am not going to host the schemas online, so if there is an issue with that please let me know to update my schemas and retry, but I don't think that would solve the problem because the validation function worked with smaller files and it was returning data as it suppose but the problem only occurred when dealing with large files.

I can't tell for sure if the problem is related to the memory of the heap being exceeded because I am not getting any warning or error messages related to that.

If I have to provide any additional information please let me know, and thanks for creating such a wonderful library, I really appreciate the help.

**Comment by epoberezkin** [comment]
Please try to measure the time it takes for validate function to execute, not anything else.

Also you can easily isolate what exactly takes a long time to execute - it can be related JSON source map for the file - it can be quite large for 10Mb JSON file - you can try to measure its size (while not exactly the memory usage, JSON.stringify(pointers).length can give you a rough indication - I won’t be surprised if it’s about 500mb for 10Mb JSON file - just a guess, let me know how large it is)

**Comment by hsnassaad** [comment]
Ok I used [performance-now](https://www.npmjs.com/package/performance-now) to get the performance time 
so: 
- File reading is taking `41.463 ms` i am using fs.readFileSync(filePath, 'utf-8').
- Parsing the file using `json source map` takes `2422.886 ms` and the size of `JSON.stringify(pointers).length` is 160593305.
- I also measure the schema compilation time `254.400 ms`.

![Screenshot (2)](https://user-images.githubusercontent.com/43029993/126075862-2862864d-7b79-41c9-a7ab-b40fe0d5c2ed.png)


the problem is that I am not able to get the performance time of the validate method because it is not finishing I waited more than 6 minutes and nothing happen so I was forced to use `Ctrl+C` to kill the terminal.

I have a 12 GB RAM in my pc.

**Comment by hsnassaad** [comment]
I tried to read the data from the file and then use the normal `JSON.parse(data)` and then tries to validate the data but it is the same I am not able to get the validation function to work.

**Comment by epoberezkin** [comment]
Interesting. Can you please put all that in some sample repo so I can run it?

**Comment by hsnassaad** [comment]
Please check this [repo](https://github.com/frankkramer-lab/CX-Typescript) where the code of the validation is done on in [here](https://github.com/frankkramer-lab/CX-Typescript/blob/main/src/validate.ts#L86)

So I am reading the file as a string, and then I parse it using `json-source-map` to get the pointers array in order to then get the error location.

After that I am calling the `validateDataAgainstSchema()` which will create an `ajv` instance -> compile the schema -> call the validate method against the data.

If you run the code using the [DrugBank - Carrier drugs.cx](https://github.com/frankkramer-lab/CX-Typescript/blob/main/test/networks/DrugBank%20-%20Carrier%20drugs.cx)  (587 KB) the package will work.

If you want to check that the package works you can change this [line](https://github.com/frankkramer-lab/CX-Typescript/blob/main/test/networks/DrugBank%20-%20Carrier%20drugs.cx#L5) into `"longNumber": true ` and it should return an error like this 

```
numberVerification
"longNumber" must be of type "number"
[
  {
    value: { line: 5, column: 30, pos: 84 },
    valueEnd: { line: 5, column: 34, pos: 88 },
    key: { line: 5, column: 16, pos: 70 },
    keyEnd: { line: 5, column: 28, pos: 82 }
  }
]
```

but when trying to validate the [BioPlex 3 - Shared Interactions.cx](https://github.com/frankkramer-lab/CX-Typescript/blob/main/test/networks/BioPlex%203%20-%20Shared%20Interactions.cx) (~10MB) you can see that it will block when it reaches the `validate(data)` method.

As for the schemas you can find them in the [schema](https://github.com/frankkramer-lab/CX-Typescript/tree/main/src/schema) folder.

Please let me know if there are additional things that needs to be provided.

**Comment by epoberezkin** [comment]
I've looked at the code - the schema you have is quite complex and it is constructed programmatically, it needs debugging you code, I won't be able to do it.

The usual approach would be to keep simplifying the schema and code until the execution time gets substantially less - in this way you should be able to identify what exactly causes slow execution. Another approach would be to start from scratch and keep adding the features you need until you hit the problem.

There may be multiple reasons for slow execution - complex recursion, slow regular expressions, some problem with ajv that is triggered by a particular schema structure etc.

Once you were able to identify a specific small part of the schema that causes performance degradation and can show it on the small example please resubmit a small code sample.
