### ISSUE TITLE
Plans for Draft 2019-09 and 2020-12

### ISSUE THREAD

**Issue by sinclairzx81** [ajv-validator/ajv#1698]
Hi,

I'm just writing to get a little bit of insight into AJV's plans for updating the default schema specification (currently to `draft-07`) and what the key indicators are for the AJV project to consider updating the default specification to either `draft-2019-09` or `draft-2020-12`. 

I'm actually not too familiar with how JSON schema drafts work these days. Would the AJV project be waiting on some finalized specification for `draft-8` or are JSON schema drafts rolling out on the current `year-month` scheme for future publishing of the specification?

I guess my question is, if JSON-schema is rolling out on `year-month` specs from this point forward, would this mean that AJV will continue on the `require("ajv/dist/2019")` approach to retro fit updates on the spec over `draft-7`, or is AJV just waiting on a possible `draft-8` to be finalized before moving over to that as a default?

I actually have some downstream projects that would like to rely on some of the features of the `2019-09` draft, but unsure if it's worth taking the `2019` functionality in it's current form, or waiting until some of these newer features roll into the default specification for AJV.

Any insights you can provide would be very helpful.
Many Thanks
S

**Comment by epoberezkin** [comment]
draft-2019-09 was a big change from draft-07, and draft-2020-12 introduced another major breaking change for “items”.

I’d like to see it stabilising - I think that the change for items in 2020 is quite unintuitive and hopefully will be reverted by the time it gets to RFC.

Neither is a criteria to make it a default in Ajv though, and if they become default I wouldn’t see it as an indication of their longevity in JSON schema spec…

The reason draft-07 is the default is that draft-2019/2020 compilation needs to add extra code even if it’s new features are not used - so it will remain opt-in rather than default, as many users don’t need these features.

I’m not sure what to suggest to be honest - if you do need to use draft2019 (or 2020) features you should use respective exports - both are stable implementations.

For simple API validation I am using JTD lately, but for any advanced scenarios 2019 is often better - this trade off is in the docs (Choosing schema language)

**Comment by sinclairzx81** [comment]
@epoberezkin Hey, thanks for the insights. I don't work very closely with emerging JSON schema draft specifications, so it's interesting learning what the AJV engineers have to reconcile when things change from the draft to draft. I appreciate that changing specifications must be very awkward to code against.

> I’d like to see it stabilising - I think that the change for items in 2020 is quite unintuitive and hopefully will be reverted by the time it gets to RFC.

Yeah, this is quite interesting. I'm curious, is there a mailing list or community were one can get up to speed on possible reverts to the drafts? I'm not familiar with the `2020` change to `items` but will try do some reading up on that (I'm surprised something as fundamental as `items` could break). Historically, it's been quite difficult to find specific information and reasoning on each new schema draft (particularly for the intended downstream use-cases). I will say tho, the potential for `items` to be reverted (in whatever form it currently is in) does certainly raise some uncertainly with respect to adopting new functionality in these drafts. 

> The reason draft-07 is the default is that draft-2019/2020 compilation needs to add extra code even if it’s new features are not used - so it will remain opt-in rather than default, as many users don’t need these features.

Mostly I'm just interested in the `2019-09` spec for `unevaluatedProperties` in tandem with `allOf`, mostly to facilitate composition of `intersection` types for [this](https://github.com/sinclairzx81/typebox) project. The main motivation is for the library to produce idealized schemas to match the TypeScript type system, of which, `Type.Intersect(...)` does see quite a bit of usage (as users are approaching type composition from TS perspective and expecting an appropriate JSON schema representation to be created for them).

Currently the library is fudging intersections by mashing two schemas together manually (and is currently locked at `draft 6`), but the preference would be to leverage `draft-2019-09` to take advantage of `unevaluatedProperties` and get better compositional usage from JSON schema. The uncertainty however arises around if it's reasonable for this library to generate `2019-09` schemas if the `2019-09` draft is still up in the air. I've held back implementing `unevaluatedProperties` as a result.

In your opinion, how stable do you feel `unevaluatedProperties` is on the `2019-09` draft? Is there a potential for this to change also? (From what I understand, there was a lot of discussion around `unevaluatedProperties`, but I'm unfamiliar with any contention there, or potential for this to be reverted also).

Sure would be good if JSON schema finally settled on a final specification everyone could work against. But thank you for your excellent work on AJV, it's an excellent library.

Regards
S
