### ISSUE TITLE
Unconstrained tuples doesn't fully consider `maxItems` when `additionalItems` is not `false`

### ISSUE THREAD

**Issue by Relequestual** [ajv-validator/ajv#1703]
Issue filing as a result of a [StackOverflow question](https://stackoverflow.com/questions/68419621/a-strict-mode-warning-of-electron-store/68437348).

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Looks like v8. Not sure.

**Ajv options object**
Unknown. Using `electron-store`

**JSON Schema**

```json
{
  "type": "array",
  "items": [
    true
  ],
  "minItems": 0,
  "maxItems": 999,
  "additionalItems": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string"
      }
    }
  }
}
```

**Sample data**

N/A

**Your code**

https://stackoverflow.com/questions/68419621/a-strict-mode-warning-of-electron-store/68437348
Copied for prosperity

```javascript
const Store = require('electron-store')

/** @type import('json-schema-typed').JSONSchema */
const schema = {
  todo: {
    type: 'array',
    items: [true],
    minItems: 0,
    maxItems: 999,
    additionalItems: {
      type: 'object',
      properties: {
        id: {
          type: 'number'
        },
        name: {
          type: 'string'
        }
      }
    }
  }
}

const todoStore = new Store({ schema })

const todoItem = [{ id: 1, name: '11111' }]

todoStore.set('todo', todoItem)

console.log(todoStore.get('todo'))

const newTodo = [...todoStore.get('todo')]
newTodo.push({ id: 2, name: '22222' })

todoStore.set('todo', prev)

console.log(todoStore.get('todo'))

module.exports = todoStore

```

**Validation result, data AFTER validation, error messages**
Does not reach validation.
Strict mode throws an error regarding unconstrained tuples.

**What results did you expect?**
I understand (and actually quite like in some ways) strict mode.

In this situation, I assume what's happening is if `additionalItems` is not `false`, the error is thrown. But given `maxItems` is set, I would expect this to be considedered not unconstrained tuples.

Maybe just a fail early oversight?

Sorry I'm not able to validate this with the latest version, nor look to see what version is being used by the electron store library. It must be 8 though because strict mode is kicking in.

**Are you going to resolve the issue?**
No 😅 busy making JSON Schema happen.

**Comment by epoberezkin** [comment]
This is by design. The idea here is an opinionated statement that that such data structures should be avoided in APIs, they are simply not tuples :)

With strictTuples enabled minItems and maxItems must be the same value rather than the range.

The possible improvement here is to allow to define some items with “items”, and some items with “additionalItems” - it is still possible to have fixed size arrays defined like that, but this seems a bit artificial situation.

**Comment by Relequestual** [comment]
I better understand the documentation having re-read it. OK.

Frustratingly, the library the Stackoverflow user is using provides no access to pass configs to ajv. It's a nested dependency, which would require a chain of config passthrough.

This opens up some of the thoughts I've been having. I think a lot of the "strict mode" rules could actually be linting rules.
AND, I think it could make sense for linting rules to be part of the schema, with some sort of default, making the linting rules configurable on a per schema basis as the end user wishes (or via virtue of a new dialect the end user creates to span across a collection of schemas).

This is all future talk, but it's something I think we should investigage together at some point assuming you'd be interested.

**Comment by epoberezkin** [comment]
Yes - happy to chat about it! I do hope that as JSON Schema evolves to RFC a simpler option could be achieved - eliminate the need for linting entirely, to make any ambiguous schemas just invalid.
