### ISSUE TITLE
Discrepancy in treating numbers between v6 and v8

### ISSUE THREAD

**Issue by gaitat** [ajv-validator/ajv#1704]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv@6.12.6 vs ajv@8.6.2

**Ajv options object**

```javascript
{ allErrors: true }
```

**JSON Schema**

```json
{
  type: "object",
  properties: {
    foo: {type: "number"},
  },
  required: ["foo"],
  additionalProperties: false,
}
```

**Sample data**

```json
{foo: Number.POSITIVE_INFINITY}
```

**RunKit sample**
[RunKit sample](https://runkit.com/gaitat/60f5f51587632e0013db51a2)

**Your code**

```javascript
const validate = ajv.compile(schema)

test({foo: Number.POSITIVE_INFINITY})

function test(data) {
  validate(data) ? console.log("Valid!") :
    console.log("Invalid: " + ajv.errorsText(validate.errors))
}
```

**Validation result, data AFTER validation, error messages**

```
under ajv@6.12.6:
"Valid!"

under ajv@8.6.2:
"Invalid: data/foo must be number"
```

**What results did you expect?**
Expecting that under both versions of ajv the `data` will validate to `true`

**Are you going to resolve the issue?**
No

**Comment by gaitat** [comment]
After further investigation, I found that If I replace `Number.POSITIVE_INFINITY` with `Number.MAX_SAFE_INTEGER` then the validation succeeds with both ajv versions.

**Comment by epoberezkin** [comment]
This change is intentional, it also rejects NaN now. You can get the old behaviour with strictNumbers: false

https://ajv.js.org/strict-mode.html#strict-number-validation

**Comment by epoberezkin** [comment]
Also see https://ajv.js.org/v6-to-v8-migration.html#changed-options

**Comment by gaitat** [comment]
Thank you
