### ISSUE TITLE
JTDDataType no unions created for oneOf

### ISSUE THREAD

**Issue by java-james** [ajv-validator/ajv#1712]
Want to make sure I'm not missing something and that `oneOf` doesn't generate the union types when using `JTDDataType`

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`8.6.2`

**Your typescript code**

```typescript
import { JTDDataType } from "ajv/dist/jtd";

const schema = {
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
    },
    "bar": {
      "type": "string",
    },
  },
  "oneOf": [
    { "required": [ "foo" ] },
    { "required": [ "bar" ] }
  ]
};

export type TestType = JTDDataType<typeof schema>

// Invalid
const testType: TestType = {
  foo: ""
}
```

**Typescript compiler error messages**

```
TS2322: Type '{ foo: string; }' is not assignable to type '{ foo: unknown; bar: unknown; } & {}'.   Property '"bar"' is missing in type '{ foo: string; }' but required in type '{ foo: unknown; bar: unknown; }'. 
```

**Describe the change that should be made to address the issue?**

Type is generated with unions specified in oneOf

**Are you going to resolve the issue?**

No

**Comment by epoberezkin** [comment]
This comment: https://github.com/ajv-validator/ajv/issues/1713#issuecomment-886006386

**Comment by java-james** [comment]
Thanks for your reply. Understand!
