### ISSUE TITLE
JSONSchemaType allows omission of required members

### ISSUE THREAD

**Issue by akoll** [ajv-validator/ajv#1715]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
* Ajv v8.6.2
* TypeScript 4.3.5

**Your typescript code**

When defining a `JSONSchemaType`, members that are required in the argument type are not required to be included in the `required` array of the schema. This means that a schema is considered valid that allows the omission of required properties.
The result type of `ajv.compile` is a type guard of the argument type to `JSONSchemaType` but I believe this to be misleading, since data passes the validation that is not actually of the correct type.

```typescript
import Ajv, { JSONSchemaType } from 'ajv';

const ajv = new Ajv({});

type Example = {
    kek: number;
};

const schema: JSONSchemaType<Example> = {
    type: 'object',
    properties: {
        kek: {
            type: 'number',
        },
    },
    required: [
        // Empty!
    ],
};

const data = {
    // No `kek` field. This is not a valid `Example` instance.
};

// `validate` is a type guard returning `is Example`.
const validate = ajv.compile(schema);

console.log(validate(data)); // true
console.log(validate.errors); // null
```

**Typescript compiler error messages**

There is no error and that's the problem.

**Describe the change that should be made to address the issue?**

Expressing the type of the `required` array (i.e. a tuple containing all required member names in any order) in TypeScript is apparently really hard and potentially impossible. Have we hit an unsurmountable limitation?

I see several approaches to attempt supporting this, all with their own quirks:
* Change the type of the `required` schema field to be a tuple consisting of the `UncheckedRequiredMembers` by using some union-to-tuple conversion as shown in [this stackoverflow answer](https://stackoverflow.com/a/55128956) (which is rather hacky).
While this would fix the issue for `JSONSchemaType`s, it leads to an excessively deep type instantion on the `ajv.compile` call.
Another drawback of this is that there is no control over the order within the tuple and only a single permutation would be considered valid. This could lead to incompatibilities with code generation and might unpredictably invalidate schema definitions in the future or with other TS versions.
* Assert the correctness through the parameter to `ajv.compile` (using `extends`) and fall back to either `never` or some string literal type like is done in the [`StrictNullChecksWrapper`](https://github.com/ajv-validator/ajv/blob/master/lib/types/json-schema.ts#L2).
This would require significant changes to the signature of `compile` and would likely not yield very friendly error messages. Furthermore, errors would not emerge in the initialization of a `JSONSchemaType` but rather in the later compilation thereof.
* Give up and use JSON Type Definitions which have their `JTDSchemaType` inferred correctly. Unfortunately, JTD is lacking validation features like regex-matching and min/max values.

Since there seems to be no obvious, elegant solution, has this issue been considered before and rejected because of this? I was unable to find a related issue.

**Are you going to resolve the issue?**
I would love to provide a pull request if a suitable solution is found (if it is even theoretically possible).

**Comment by epoberezkin** [comment]
It is indeed a limitation that cannot be addressed. JSONSchemaType ensures you cannot use wrong members in required, but does not ensure that you use all members. Not much can be done about it, you just have to ensure that your schema matches the type in relation to required in some other way (tests, attention, etc.)

**Comment by akoll** [comment]
The following workaround solves the issue in a similar manner to the second point of my original proposal:
```typescript
import { JSONSchemaType, RequiredMembers } from 'ajv/dist/types/json-schema';

type MissingRequiredFieldsError<Fields extends string | number> = {
  required: `Missing required field ${Fields}.`;
};

type AssertRequired<Data, Schema extends JSONSchemaType<Data>> = RequiredMembers<Data> extends Schema['required'][number] ? Schema : MissingRequiredFieldsError<Exclude<RequiredMembers<Data>, Schema['required'][number] | symbol>>;

export type CheckJSONSchemaType<Data, Schema extends JSONSchemaType<Data>> = AssertRequired<Data, Schema> & (Schema extends { properties: any } ? {
  properties: {
    [K in keyof Schema['properties']]: CheckJSONSchemaType<Data[K], Schema['properties'][K]>;
  }
} : unknown);
```
It works by merely asserting that a given schema type is valid instead of trying to enumerate all possible schema instances (which is practically impossible, as stated above).

This allows doing something like this:
```typescript
/**
 * Asserts that a schema contains all required fields.
 * Identity function that returns the schema as is at runtime.
 */
function makeSchema<Data>() {
  return function <Schema extends JSONSchemaType<Data>>(schema: Schema & CheckJSONSchemaType<Data, Schema>) {
    return schema;
  };
}

// Generates compile-time error for assignment to "Missing required field b.";
makeSchema<{ a: string; b: string; c: number; }>()({
  type: 'object',
  required: ['a', 'c'],
});
```

Or using a class to avoid the ugly double function call (`()({ ... })`):
```typescript
class JSONSchemaCompiler<Data> {
  assert<Schema extends JSONSchemaType<Data>>(schema: Schema & CheckJSONSchemaType<Data, Schema>) {
    return schema;
  }

  compile<Schema extends JSONSchemaType<Data>>(schema: Schema & CheckJSONSchemaType<Data, Schema>) {
    return ajv.compile(schema);
  }
}

// Generates compile-time error for assignment to "Missing required field b.";
const validate = new JSONSchemaCompiler<{ a: string; b: string; c: number; }>().compile({
  type: 'object',
  required: ['a', 'c'],
});
```

To try it out, see the example in [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQQFYDcA0cDecBSBlAeQDk8BjACwFMQBDAFQE8xK4BfOAMyghDgHIaqPgG4AUKEiwscAEqUAjgFdgUSgBMAstQBGlKAGc2nbrwGoA9GuD6Y5mE0r7zSfRAB2AWn0VqNEaNFSdxs4QRQ4AF44N0oAd0RUAApMVgBKMVF7ZjgNa31gNwBzOSUVdQAxYEoAGzV9AFEobigAHkqaurhKAA8YSjdOmygCwrgAH2jFEF0oAD5IrFE4OFVS1TUALjgAA1z9fKKVhWV1zirauAASTHba-VYAOm2xVgyslgR9vRgSk-UWgAiNBgNAwZCotC6vX6nXwxHBvkYzEBwJos3mUV+ZU0Oj0+hRIPmPT6A0MCNoAG0+Ks-mo+ABdCluKYzelwAD8cHJNDgWz2B2Kx2xtzqjWaLXq3VI1UUakoLSx6y00zxBLRYJ8lOpQvWDKZLL0bIm+gY0wg1XRGR6kng7zgAGEqKQANZwkia+gONUaiE84kwwxu7lI+VAwkYxBfWCK-5h0Fcj3zABkcES3KhJM62DA3GYsCq+i2NDcDCMnMwSzgOYgeZgBa2FeWywpAGk4AU4M7KAwIBwE76qdXawWGfSto7KC6gx6Q2rW-Sfb5B7nviPGS36bMxMtWKJ2FtFG5nW4ILE3OkAuYAFRXpZXyP6b6GGDkYGhODeX1wIJuEEFQw0NU1RHGs6hnB0+gPHecAAJJyr+wD2Jwh6kHW7hwC+b6qDAihQG4z5UB+HqhIY1ihPAUCHnWICUFBcBXuYogcChaFuHAtBdtyaqzIkqSLMs2G4WxzFuKhwDoS06b+qSuCEO6vqznG6KJJ+vhbOmKYTlOcnBl6caLrQsx8Y2TaCXhRG+tubAvJe5hwAA4v0ejAo4348GAwDVJQHjUSwejNJw0AkfkhRuDRv4YRAcAAET8iMIG0uBFzaA80ViBxlBcdgNBbEMIzCHA2i5TAwxFAVpBbMyKpQAVrA8akySVu8Wx8BA2hIJOMB8GglY0tiWxUn4GB8KQDI9WkGSiOYdkEFAJHvtKND7O2+F9DQaiRaEKAQMAG0viwiiFNUpZqBAijaF5HikIBwHbLxyRwA8T1sKk2xQYty3Tr69ruZ5ejcfxwXfJJxHSbCOkznpqLKaptDqcRmlOq6EMKVDIIGWixmVgJlA4eZsM0FZu6VkE4B-SDX5g4GKOImjaI8QT8Nfojk7I-CkPIvp-a+EZgM43jbFhA8pMeV5KkeheO57rZDlOVALmGCLf0+aAflNEFHBBUtIVhf0tpRbFeTxX1pwcOcG0pWlgTBPAKCAbtLkLDE8Rfb4P1k15rTZcVpWFAVRUfiV+XfpVBo1Ww9XC79Ysmc1-BtR1qHdb1OrqANAjdfwo0Lnu6RAA).
