### ISSUE TITLE
Include details on failing "not" conditions in error messages/params

### ISSUE THREAD

**Issue by manuschillerdev** [ajv-validator/ajv#1716]
Currently subschemas defined in `"not"` keywords do not provide any details on fields, that must not exist on an object. I'd expect something similar to the error message provided for additionalProperties with `additionalProperties` set to `true`.

example (reproduction: https://stackblitz.com/edit/js-6tzy3g)

```js
import Ajv from 'ajv';

const ajv = new Ajv({ allErrors: true });

const validate = ajv.compile({
  type: 'object',
  not: {
    required: ['badProperty']
  }
});

validate({
  badProperty: 'exists'
});

// message: must NOT be validate
// params: {}

// would be nice, if params could contain
// '"badProperty" must NOT exist on object'
console.log(validate.errors);

```

**What version of Ajv you are you using?**
8.6.2

**What problem do you want to solve?**
Missing information about why a "not" condition fails

**What do you think is the correct solution to problem?**
I believe it is hard to reason about this feature, since it involves much more than required fields and could get complicated very quickly. But nevertheless it would be cool to show that a property is explicitly not wanted here

**Will you be able to implement it?**
with some guidance, yes

**Comment by epoberezkin** [comment]
What can be in “not“ schema is not constrained to the required properties - it’s can be any schema. So the schema itself is the best way to express the requirements that must be failed - the schemaPath is available in error.params and with `verbose` option you can have the schema itself.

What you are asking, effectively, is to convert JSON Schema requirements into a plain language - it can probably be done, but it is definitely out of scope - it deserves a separate library.
