### ISSUE TITLE
link to files in docs is not working

### ISSUE THREAD

**Issue by safareli** [ajv-validator/ajv#1722]
on page: https://ajv.js.org/api.html#ajv-compile-schema-object-data-any-boolean-promise-any

> See more advanced example in [the test](https://ajv.js.org/spec/types/json-schema.spec.ts).

The link is broken.  It points to: https://ajv.js.org/spec/types/json-schema.spec.ts

---

Tho if you check it on github: https://github.com/ajv-validator/ajv/blob/master/docs/api.md#ajvcompileschema-object-data-any--boolean--promise--any-

It points to: https://github.com/ajv-validator/ajv/blob/master/spec/types/json-schema.spec.ts

**Comment by nicolas-saubi** [comment]
Adding :
in page https://ajv.js.org/faq.html#additional-properties-inside-compound-keywords-anyof-oneof-etc
We have a link to the Readme which should contains a "filtering data" section, which seems not.
(https://github.com/ajv-validator/ajv#filtering-data)
