### ISSUE TITLE
Asynchronous validation

### ISSUE THREAD

**Issue by simon-p-r** [ajv-validator/ajv#173]
Hello

Is it possible to use a callback async validation function instead of the current compiling options?  

Thanks

**Comment by epoberezkin** [comment]
Not sure I understand. Do you want to have validation function that calls node style callback?

**Comment by simon-p-r** [comment]
Yes node style callback, from what I understand from reading the docs it must be a promise resolving to true or false.

**Comment by epoberezkin** [comment]
Asynchronous schemas are compiled to either generator function or ES7 async function - that's the reason to use promises. Compiling to functions using callbacks would require completely rewriting code generation - essentially that's what transpilers (nodent/regenerator) are doing.

It's simple to convert callback functions to/from functions returnig promises.

So whether you have node-style functions with callbacks for your custom keywords or you need to use validation function with callbacks you just need to convert them to what ajv/you need.

**Comment by simon-p-r** [comment]
Ok thanks for the answer, the reason why I asked is because with callbacks I can get the context of why the validation fails as opposed to just the true or false value returned by the promise.  Are you open to callback style being implemented?

**Comment by epoberezkin** [comment]
Sorry, not sure I understand. What do you mean by the context? Validation function returns promise that rejects if validation fails. The rejection error contains validation errors. In readme:

> Validation result will be a promise that resolves to true or rejects with an exception Ajv.ValidationError that has the array of validation errors in errors property.

I don't think it is possible implementing callback style without rewriting code generation completely.

**Comment by simon-p-r** [comment]
Ok thanks for your response

**Comment by epoberezkin** [comment]
I actually tried doing async validation with callbacks everywhere - this attempt is in async-callback branch.

**Comment by simon-p-r** [comment]
Thanks I will check it out, what problems were you encountering with code generation?

**Comment by epoberezkin** [comment]
The main thing is that you cannot have a single function, it all has to be refactored into multiple functions. So for example if you have some async keyword that is only validated if the property is present, everything after should become a function that in one case is called immediately and in another in the callback. Now think about async keywords inside loops etc. You will be essentially implementing the same logic that is in nodent/regenerator to keep track of all these functions.

With generators or async functions it is simple - you just put yield or await in front of async function calls, but the code flow remains the same and you still have a single function.

If you want to see how code changes try compiling some simple async schema into ES7 await function (source code is in `sourceCode` property of compiled validation function) and then transpile it to callbacks with [nodent](http://nodent.mailed.me.uk/#%2F%2FES7%20code) in "Pure ES5" mode.
