### ISSUE TITLE
Several compilation errors with AJV 8.6.2 and Typescript 4.3.5

### ISSUE THREAD

**Issue by ahoehn** [ajv-validator/ajv#1730]
Since upgrading to the latest version, tsc can't compile anymore AJV. As reported by several other users, it seams to be a core problem of the current version. I report this, because my output is different from the others but the core problem seams to be a incompatibility with typescript.

What version of Ajv are you using? 8.6.2

What results did you expect? that the lib can be compiled with tsc

Are you going to resolve the issue? No but I hope you can reproduce and fix it.

```javascript
tsc -v
Version 4.3.5

//same result with or without --noEmit option
tsc --project tsconfig.build.json --noEmit
node_modules/ajv/lib/compile/codegen/code.ts:52:5 - error TS2322: Type 'CodeItem' is not assignable to type 'string'.

52     return (this._str ??= this._items.reduce((s: string, c: CodeItem) => `${s}${c}`, ""))
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ajv/lib/compile/codegen/code.ts:52:13 - error TS2322: Type 'CodeItem' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

52     return (this._str ??= this._items.reduce((s: string, c: CodeItem) => `${s}${c}`, ""))
               ~~~~~~~~~

node_modules/ajv/lib/compile/codegen/code.ts:139:3 - error TS2322: Type 'string | number | boolean | string[]' is not assignable to type 'string | SafeExpr'.
  Type 'string[]' is not assignable to type 'string | SafeExpr'.
    Type 'string[]' is not assignable to type 'string'.

139   return typeof x == "number" || typeof x == "boolean" || x === null
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
140     ? x
    ~~~~~~~
141     : safeStringify(Array.isArray(x) ? x.join(",") : x)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ajv/lib/core.ts:356:3 - error TS2394: This overload signature is not compatible with its implementation signature.

356   compile<T = unknown>(schema: Schema | JSONSchemaType<T>, _meta?: boolean): ValidateFunction<T>
      ~~~~~~~

  node_modules/ajv/lib/core.ts:368:3
    368   compile<T = unknown>(schema: AnySchema, _meta?: boolean): AnyValidateFunction<T> {
          ~~~~~~~
    The implementation signature is declared here.

node_modules/ajv/lib/core.ts:377:3 - error TS2394: This overload signature is not compatible with its implementation signature.

377   compileAsync<T = unknown>(
      ~~~~~~~~~~~~

  node_modules/ajv/lib/core.ts:390:3
    390   compileAsync<T = unknown>(
          ~~~~~~~~~~~~
    The implementation signature is declared here.


Found 5 errors.
```

**Comment by epoberezkin** [comment]
I am not sure what exactly your setup is, but you are probably trying to recompile ajv as a dependency, instead you should be requiring it from dist where it is pre-compiled.

I cannot re-produce the problem compiling ajv separately with 4.3.5 (and this is what it uses in CI anyway).

If you really need to compile ajv together with your project (e.g. if you need to compile it to earlier target) you can:
1. compile it separately with a different target in your build - it should work
2. compare your project tsconfig with ajv tsconfig - some options must be different that cause the compilation to fail.
3. Try to find a conflicting dependency by starting from scratch and adding your dependencies one by one until it fails to compile

**Comment by ahoehn** [comment]
To reproduce it, here is my tsconfig.json file. Try to compile a project where you **import** AJV and you should see the effect.
`{`
`  "compilerOptions": {`
`    "module": "commonjs",`
`    "declaration": true,`
`    "removeComments": true,`
`    "emitDecoratorMetadata": true,`
`    "experimentalDecorators": true,`
`    "allowSyntheticDefaultImports": true,`
`    "skipLibCheck": true,`
`    "resolveJsonModule": true,`
`    "target": "es2017",`
`    "sourceMap": true,`
`    "outDir": "./dist",`
`    "baseUrl": "./",`
`    "incremental": true`
`  },`
`  "exclude": ["node_modules", "dist"]`
`}`

According to https://github.com/microsoft/TypeScript/issues/41883 it doesn't help you if you exclude node_modules or use the option skipLibCheck. As soon as you import a class from a library it will be checked.

So the only currently working workaround is the following:
`//instead of an import statement use required`
`//import Ajv from 'ajv';`
`const Ajv = require('ajv');`

But this only excluded the class from getting checked. I still belive that AJV has some serious problems with typing as shown in the compiler output above.

**Comment by epoberezkin** [comment]
As I wrote, ajv itself does compile with 4.3.5, and it is not a widespread issue (otherwise there would be many reports), so it must be something specific to your project / dependencies / configuration.

I can help investigate, but could you please create a separate repo (as I suggested in 3) having no other dependencies than Ajv with your configuration. If the issue does not appear without other dependencies, please add your dependencies one by one until the issue re-appears. Once you've identified the dependency (or some of your code) that triggers the issue, remove all other dependencies. If the issue disappears, then try finding the next one that creates an issue.

Etc - what I need to help investigate is an absolutely minimal project setup that reproduces the issue. I would not be able to help based on the partial information or looking at a complete project, you have to debug it to find the root cause.

**Comment by Celbine** [comment]
I also had this problem and it was in the import line

`import ... from "ajv/lib/types/index";`

Perhaps you have a similar import line somewhere, it should be replaced with

`import ... from "ajv";`

**Comment by epoberezkin** [comment]
It’s also safe to import from dist folder rather than from lib, if you need something that’s not exposed at the top level.

**Comment by AlexanderRyabov** [comment]
> I also had this problem and it was in the import line
> 
> `import ... from "ajv/lib/types/index";`
> 
> Perhaps you have a similar import line somewhere, it should be replaced with
> 
> `import ... from "ajv";`

Similar issue, import was added automatically by WebStorm.

**Comment by theogravity** [comment]
> It’s also safe to import from dist folder rather than from lib, if you need something that’s not exposed at the top level.

Changing 

`import { ErrorObject } from 'ajv/lib/types';`

to

`import { ErrorObject } from 'ajv/dist/types';`

Does fix the issue.

**Comment by YukiGibson** [comment]
Had the same issue, was importing `SchemaObject` as
> import {SchemaObject} from 'ajv/lib/types';

But it was exposed at the top level, so issue resolved

> import {SchemaObject} from 'ajv';
