### ISSUE TITLE
Broken link in faq.md

### ISSUE THREAD

**Issue by jsbrain** [ajv-validator/ajv#1731]
The link with the description `Filtering Data` in [the FAQ](https://github.com/ajv-validator/ajv/blob/1b07663f3954b48892c7210196f7c6ba08000091/docs/faq.md) leads to the repo readme which does not include such anchor.

Is this resource even still existing or should this link be removed?

**Comment by epoberezkin** [comment]
This is the section: https://ajv.js.org/guide/modifying-data.html#removing-additional-properties

Feel free to update in PR
