### ISSUE TITLE
nullable with allOf and $ref yields unexpected results

### ISSUE THREAD

**Issue by chrisolson443** [ajv-validator/ajv#1736]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.6.2

**Ajv options object**
```javascript
{ allErrors: true, strict: false }
```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "myObject": {
      "$ref": "#/components/schemas/MyObject"
    }
  },
  "components": {
    "schemas": {
      "MyObject": {
        "type": "object",
        "properties": {
          "property1": {
            "$ref": "#/components/schemas/Wrapper"
          }
        }
      },
      "Wrapper": {
        "type": "object",
        "nullable": true,
        "allOf": [{ "$ref": "#/components/schemas/UnmutableExternalReference" }]
      },
      "UnmutableExternalReference": {
        "type": "object",
        "properties": {
          "foo": {
            "type": "boolean"
          }
        }
      }
    }
  }
}
```

**Sample data**

```json
{
"myObject": {
      "property1": null
    }
}
```

**Your code**

https://runkit.com/crizo23/611ac6cd2da767001a22e806

**Validation result, data AFTER validation, error messages**

```
[{"instancePath":"/myObject/property1","schemaPath":"#/components/schemas/UnmutableExternalReference/type","keyword":"type","params":{"type":"object"},"message":"must be object"}
```

**What results did you expect?**
Expected validation to pass

**Are you going to resolve the issue?**
I wish I could!

**Comment by epoberezkin** [comment]
You don’t have nullable in MyObject schema

**Comment by chrisolson443** [comment]
@epoberezkin thanks for the reply.

I just realized that I forgot wrapping parentheses around my sample data above ( I just fixed that).

In my example above, it's setting `property1` to null, not the top level `myObject` property, and so I shouldn't need `nullable` in `MyObject` schema. Right?

For example, if my sample data were:
```
{
"myObject": null
}
```
Then as you said I'd need nullable in MyObject

**Comment by epoberezkin** [comment]
Yes, correct. Looking at the error you are missing nullable in UnmutableExternalReference.

nullable only extends type keyword, not the whole schema.

**Comment by chrisolson443** [comment]
@epoberezkin exactly. My use case here is that `UnmutableExternalReference` is a type I can't change. I know that in JSON Schema, to extend we use `$ref` inside `allOf`, and that sibling properties are cumulative from the `$ref` (`UnmutableExternalReference` joined with `Wrapper` in this case), but since `UnmutableExternalReference` doesn't have `nullable: false`, I thought `Wrapper` would be adding `nullable: true` to the "joined" schema properties.

I appreciate your time here

**Comment by epoberezkin** [comment]
> I thought Wrapper would be adding nullable: true to the "joined" schema properties.

I understand, that's not how it works I am afraid...

> My use case here is that UnmutableExternalReference is a type I can't change.

By combining multiple keywords in the same schema you can only "extend the type of your data" (that is, narrow the allowed values, not widen them). To widen it you need a union, which is anyOf:

```javascript
{
  anyOf: [
    {const: null},
    {$ref: "#/components/schemas/UnmutableExternalReference"}
  ]
}

**Comment by chrisolson443** [comment]
@epoberezkin 

> {const: null}

I'm assuming you meant `{ type: "null" }` ?

Unfortunately we can't use `{ type: "null" }` as we require Open API (OAS) version 3.0, and only 3.1 supports this (completely unrelated to your library, I know)

**Comment by chrisolson443** [comment]
@epoberezkin regarding `"const": "null"` - I now understand what you're saying, but when I try using `"const": "null"` in the schema, and send `"property1": null`, I get:

```
[
   {
      "instancePath":"/myObject/property1",
      "schemaPath":"#/components/schemas/UnmutableExternalReference/type",
      "keyword":"type",
      "params":{
         "type":"object"
      },
      "message":"must be object"
   },
   {
      "instancePath":"/myObject/property1",
      "schemaPath":"#/anyOf/1/const",
      "keyword":"const",
      "params":{
         "allowedValue":"null"
      },
      "message":"must be equal to constant"
   },
   {
      "instancePath":"/myObject/property1",
      "schemaPath":"#/anyOf",
      "keyword":"anyOf",
      "params":{
         
      },
      "message":"must match a schema in anyOf"
   }
]
```

sending `"property1": "null"` gives:
```
[
   {
      "instancePath":"/myObject/property1",
      "schemaPath":"#/type",
      "keyword":"type",
      "params":{
         "type":"object"
      },
      "message":"must be object"
   }
]
```

**Comment by epoberezkin** [comment]
You need const: null, not const: “null”

**Comment by epoberezkin** [comment]
(That is, a proper null, not a string)

**Comment by chrisolson443** [comment]
@epoberezkin 🤦   A typescript compile error threw me. It's working. Thanks again
