### ISSUE TITLE
Provide tested value itself as additional key in ErrorObject

### ISSUE THREAD

**Issue by thybzi** [ajv-validator/ajv#1750]
**What version of Ajv you are you using?**
8.6.2

**What problem do you want to solve?**
When browsing validation errors, I can see the path to mismatched value (instancePath), but not the value itself.
In my case (tested data is built dynamically), that prevents quick finding and fixing the problem.

**What do you think is the correct solution to problem?**
Provide additional key in ErrorObject, containing the tested value itself

**Will you be able to implement it?**
Unsure

**Comment by epoberezkin** [comment]
There is verbose option that does it

**Comment by thybzi** [comment]
thanks, will try it today!

**Comment by thybzi** [comment]
`verbose: true` options extends ErrorObject with `data` key, which contains the value I needed.

thanks a lot!
