### ISSUE TITLE
import of Standalone module in ESM module requires using .default property

### ISSUE THREAD

**Issue by bhvngt** [ajv-validator/ajv#1754]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`v8.6.2`

**Your code**
[Sandbox](https://codesandbox.io/s/typescript-node-forked-rsymo?file=/src/index.ts)

```javascript
import Ajv from "ajv";
import standalone from "ajv/dist/standalone/index.js";
const ajv = new Ajv();
const validate = ajv.compile({ type: "number", maximum: 5 });

const schema_compiler: string = standalone(ajv, validate);
```
**Validation result, data AFTER validation, error messages**

```
TypeError: standalone is not a function
    at file:///sandbox/src/index.ts:6:13
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**What results did you expect?**
I should be able to import `standalone` module without using `.default` property

**Are you going to resolve the issue?**
This one is very similar to #1381. If required, I can create a PR to add `module.exports = exports = standaloneCode` for `lib/standalone/index.ts`

**Comment by epoberezkin** [comment]
If it is backward compatible (that is, the current usage with `.default` should still work) it can indeed be improved. If you do the PR, please check how other exports are done, so it's consistent with all exports.

**Comment by bhvngt** [comment]
Cool. I have raised #1757 with the changes. My changes are consistent with what was done to fix #1381. CI seems to be failing for the PR and I don't understand the reason why it is failing. Same tests when I run locally passes.

**Comment by epoberezkin** [comment]
thank you! There was some incompatible typescript change I know fixed.

**Comment by cyberwombat** [comment]
I am on `8.11.0` an have to do `new Ajv.default()`.  I am on TS 8.3.3 in an ESM project. I have these settings in my tsconfig:
```
 "target": "es2020",
    "lib": ["es2020"],
    "module": "node16",
    "moduleResolution": "Node16",
    "esModuleInterop": true, // Eases ESM support
    "types": ["node"],
    "allowSyntheticDefaultImports": true,
```
Any idea why it would still not work?

**Comment by bhvngt** [comment]
@cyberwombat. Here's my `tsconfig` with which I could instantiate `Ajv` object with `new Ajv()`.

```json
"target": "esnext",
"module": "esnext",
"lib": ["dom", "esnext"],
"moduleResolution": "node",
"esModuleInterop": true,
"importsNotUsedAsValues": "error",
"isolatedModules": true,
"allowJs": true,
```

**Comment by cyberwombat** [comment]
@bhvngt yes it works fine with `moduleResolution node`. It's moving to nodeNext that is problematic. I think it has to do with packages needing some esm stuff - I noticed for example that this [package](https://github.com/sindresorhus/get-port) (and all others by him) went esm only - the older version gave me same issue but now they work. Migration pains.

**Comment by bhvngt** [comment]
@cyberwombat Yeah I agree. I had quiet a bit of struggle with `esm` in the past. Ecosystem is much better now.
