### ISSUE TITLE
Cannot use \. in a pattern - Error: schema is invalid: .../pattern should match format "regex"    

### ISSUE THREAD

**Issue by tombburnell** [ajv-validator/ajv#1755]
Hi Evgeny - Hope you are well. I have an issue trying to expand the definition of tildePath to allow a dot character - remember it? :-) 

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I'm using v5 - I tried using 5.6.1 and it also failed. I couldn't figure out yet how to use the latest version yet as that was giving a different error.  [Error: Cannot find module 'ajv/lib/compile/equal']

**JSON Schema**

path:
  pattern: '^~$|^(~[a-z0-9_-]+)+$'.         <!-- this works

path:
  pattern: '^~$|^(~[a-z0-9_-\.]+)+$'.         <!-- this fails with    Error: schema is invalid: .../pattern should match format "regex"    

I also tried 
/^~$|^(~[a-z0-9_-\.]+)+$/
'^~$|^(~[a-z0-9_-\\.]+)+$'
'^~$|^(~[a-z0-9_-\\\.]+)+$'

Even just a dot causes it to fail  '^~$|^(~[a-z0-9_-.]+)+$'

Oddly this one with \.  does work      '^(~[a-z0-9_-]+)*~\.profile$'

**Comment by epoberezkin** [comment]
Hi - hope all is good too :)

All ajv does is passing this string to RegExp constructor, so it it fails it means that RegExp constructor rejects it - it's just not a valid RegExp. What I think is happening here is that "-" between two characters is used to mean "range", unless it is the last character, as in the first example, or unless it is escaped: 

```
new RegExp('^$|^([a-z0-9_\\-\\.]+)+$')
```

(also because it is a string constant you need double escape)

**Comment by epoberezkin** [comment]
closing it - but please comment if I am missing something

**Comment by tombburnell** [comment]
Oh yeah - you are totally right - I should have checked with new RexExp() - I think I just assumed because the error said  "match format" that there was a regex validation check. 
It's a bit how the - is used in the [] - it also fails if you escape the -. 
If I put the \. at the beginning of the [] it works fine - so ill try that. 
Thanks for taking a look for me.
Take care, Tom
