### ISSUE TITLE
Fix CI to build the website and to update ajv-dist

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1759]
Website currently is disabled, it breaks the build: https://github.com/ajv-validator/ajv/blob/master/.github/workflows/build.yml#L25

ajv-dist update [failed](https://github.com/ajv-validator/ajv/runs/3080443051?check_suite_focus=true) with the last release: https://github.com/ajv-validator/ajv-dist/releases

**Comment by rubiagatra** [comment]
Helo @epoberezkin, I would help this one.

is this something error with https://github.com/ajv-validator/ajv/runs/3080443051?check_suite_focus=true#step:9:12 ? `rm -rf bundle && rollup -c`

Any idea to start this?

**Comment by epoberezkin** [comment]
thank you.

You need to make it work locally first, substituting ajv dist with any repo you have the rights to push to

once it works locally, please make a PR, that you think would fix it, I will make a patch release to see if it works… If not - repeat until it does - it might take a few patch releases, but it’s not a problem.

**Comment by rubiagatra** [comment]
I just search about it, it is not about the code it's about the GitHub action issue and is still open.

https://github.com/actions/checkout/issues/417 and the last comment

```
I use the actions latest version 2.3.4，then succeed. you can try it.

```

may we can try to bump the new version @epoberezkin? and uncomment the website workflow.

like this one https://github.com/kiegroup/kogito-editors-java/pull/112
