### ISSUE TITLE
Incorrect behaviour with `prefixItems`

### ISSUE THREAD

**Issue by viebel** [ajv-validator/ajv#1764]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.6.3

**Ajv options object**

```javascript
{allErrors: true, strict: false}
```

**JSON Schema**

```json
{
  type: "array",
  prefixItems: [{type: "integer"}, {type: "integer"}],
  minItems: 2,
}

```

**Sample data**

```json
["a","b"]

```

**Your code**

```javascript
const Ajv = require("ajv")
const ajv = new Ajv({allErrors: true, strict: false})

var s = {
  type: "array",
  prefixItems: [{type: "integer"}, {type: "integer"}],
  minItems: 2,
};

ajv.validate(s, ["a","b"])


```

**Validation result, data AFTER validation, error messages**

```
true

```

**What results did you expect?**

false

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
You are using JSON Schema draft-07 with this import (and you’ve disabled strict mode, so ajv simply ignores prefixItems - it is an unknown keyword).

You need to import Ajv from “ajv/dist/2020” to use draft-2020-12 that defined prefixItems

**Comment by viebel** [comment]
Awsome! Thanks for the clarification.
It works like a charm.
