### ISSUE TITLE
Get the line number on which there is an error

### ISSUE THREAD

**Issue by MuhammadHaseebAli** [ajv-validator/ajv#1768]
Is it possible to get the line number on which there is an error while validation the schema definition
for example, if we have a schema and we make a typo like "objects" (the correct one is "object") and it will tell us that there is an error on line number "20"

**Comment by epoberezkin** [comment]
Ajv validates objects, not json text, so mapping of json object properties to json text lines is out of scope. You could use https://github.com/epoberezkin/json-source-map to map object properties back to JSON text lines, possibly there are other packages
