### ISSUE TITLE
where to find example to use user defined format?

### ISSUE THREAD

**Issue by ghost** [ajv-validator/ajv#1769]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.6.3
**Your typescript code**

```typescript
ajv.addFormat('identifier', /^a-z\$_[a-zA-Z$_0-9]*$/)
```

**Typescript compiler error messages**

```
but how to use the above defined format 'identifier'?
```

**Describe the change that should be made to address the issue?**
Add some example to document.
**Are you going to resolve the issue?**
I have studied one whole day but  can not find the answer.

**Comment by epoberezkin** [comment]
https://ajv.js.org/json-schema.html#format
