### ISSUE TITLE
The default keyword in oneOf not works

### ISSUE THREAD

**Issue by adoyle-h** [ajv-validator/ajv#1771]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

ajv version: 8.6.3

**Your code**

```json
'use strict';

const Ajv = require('ajv/dist/2020');

const schema = {
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    '$id': '/test',
    'oneOf': [
        {
            'type': 'string',
        },

        {
            'type': 'object',
            'required': ['file'],
            'properties': {
                'file': {
                    'type': 'string',
                },

                'names': {
                    'type': 'array',
                    'default': [],
                },
            },
        },
    ],
};

const ajv = new Ajv({
    strict: 'log',
    useDefaults: true,
});

const validate = ajv.compile(schema);

const obj = {
    file: 'abc',
};
validate(obj);

console.log(obj);
```

I have tried the `discriminator` keyword, but still cannot resolve this issue, because `discriminator` requires both `oneOf` keyword and type "object".

**Validation result, data AFTER validation, error messages**

```
strict mode: default is ignored for: data.names
{ file: 'abc' }
```

**What results did you expect?**

```
{ file: 'abc', names: [] }
```

**Are you going to resolve the issue?**

No

**Comment by epoberezkin** [comment]
Please see the docs - it’s a known limitation, not a bug. Defaults in oneOf are applied only if you use discriminator because in this case ajv can choose the correct branch, rather than to validate against all branches

**Comment by adoyle-h** [comment]
@epoberezkin Yes, I have read the docs. In my case, the subschemas in oneOf are `type: object` and `type: string`. While `each oneOf subschema must have properties keyword with discriminator property.` is the requirement and limitation of using `discriminator` keyword, so that I cannot use `discriminator` to choose the correct branch.

In my case, I want to validate objects `'abc'` and `{ file: 'abc', names: [] }`. When object is string such as `'abc'`, then I can normalize it into `{ file: 'abc', names: [] }`.
