### ISSUE TITLE
using standaloneCode() with ajv instance

### ISSUE THREAD

**Issue by alex-kinokon** [ajv-validator/ajv#1777]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.6.3

**Ajv options object**

```javascript
{ code: { source: true } }
```

**JSON Schema**
Taken from https://json-schema.org/learn/miscellaneous-examples.html.
```json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
```

**Your code**
https://runkit.com/proteriax/615a679fdea26e0008143877

**Result**

```
"use strict;"
```

**What results did you expect?**
Not an empty JavaScript file.

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Please put the full code sample that produced this result - or check out the tests where it works.

**Comment by epoberezkin** [comment]
You either have to use addSchema, if you want all schemas in the instance included, or to pass the compiled validation function as the second parameter.

https://runkit.com/esp/615a9b817db8bc0008b25f00

It's not specific to 2020-12 draft - did you try with others?
