### ISSUE TITLE
Make error messages shorter

### ISSUE THREAD

**Issue by mcucalon** [ajv-validator/ajv#1782]
**What version of Ajv you are you using?**
I'm using ajv version 6.10.2

My team and I ran into a case where we have to display several ajv messages in a modal. Some of those messages are too long, so it's not user friendly because one message can take the whole modal and it has to scroll a lot until the next message. 
Is there a way to make AJV produce more concise/shorter error messages? If not, is there a way we can obtain a similar result?

Thank you in advance.

**Comment by epoberezkin** [comment]
The main use case for error messages is error logging, whether server side or browser console. Your options to change them:
1. Map in your code
2. ajv-errors package
