### ISSUE TITLE
Throw an exception during schema validation when first additional property is encountered

### ISSUE THREAD

**Issue by serge-fabiano** [ajv-validator/ajv#1783]
**What version of Ajv you are you using?**
8.6.3

**What problem do you want to solve?**
I want the user that enters data in the Json document not declared in the schema to fail when I validate it.
Like if I omitted a required field.

**What do you think is the correct solution to problem?**
Add an additional property named 'failOnAdditionalProperty: boolean' in the Options object.
When the first additional prop is encountered -> throw an exception.

**Will you be able to implement it?**
It depends on the language :-)

**Comment by epoberezkin** [comment]
It’s already supported with additionalProperties keyword

**Comment by serge-fabiano** [comment]
It does not report an error when validating the schema, it simplies remove them if I'm not mistaken.
In that case, I would like the validate method to report me an error.
Let me know.

**Comment by epoberezkin** [comment]
It only removes them with removeAdditional option, by default it would return validation error.
