### ISSUE TITLE
Unattainable branches in validation function generated code

### ISSUE THREAD

**Issue by ericmorand** [ajv-validator/ajv#1798]
I'm using AJV 8.6.3 to generate a validation function for the following schema:

```json
{
  "type": "string",
  "pattern": "^\\d{7}$"
}
```

The generated code looks like this - I just added the `// unattainable` comments:

```js
"use strict";
module.exports = validate10;
module.exports.default = validate10;
const schema11 = {"type":"string","pattern":"^\\d{7}$"};
const pattern0 = new RegExp("^\\d{7}$", "u");

function validate10(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){
let vErrors = null;
let errors = 0;
if(typeof data === "string"){
if(!pattern0.test(data)){
const err0 = {instancePath,schemaPath:"#/pattern",keyword:"pattern",params:{pattern: "^\\d{7}$"},message:"must match pattern \""+"^\\d{7}$"+"\""};
if(vErrors === null){
vErrors = [err0];
}
else {
// unattainable
vErrors.push(err0);
}
errors++;
}
}
else {
const err1 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err1];
}
else {
// unattainable
vErrors.push(err1);
}
errors++;
}
validate10.errors = vErrors;
return errors === 0;
}
```

As you can see, it is impossible for the `if(vErrors === null)` else branches to be attained since `vErrors` is always initialized to `null`. It makes obtaining 100% code coverage on the validation function impossible and, thus, obtaining 100% code covegare on the schema impossible too.

Why are these branches on the generated code?
In which context can `vErrors` be different to `null`?
Why isn't `vErrors` an array to begin with, empty when no error occured, populated when errors occured?

**Comment by epoberezkin** [comment]
This is not a bug - while there is some effort invested to optimise and avoid unreachable code, it's non-trivial to completely avoid with programmatically generated code (and it's not really necessary).

> Why are these branches on the generated code?

They are needed in more complex schemas and difficult to avoid with one-pass compilation.

> In which context can vErrors be different to null?

Whenever there is a validation error

> Why isn't vErrors an array to begin with, empty when no error occured, populated when errors occured?

This is for performance reasons - in real applications the absolute majority of validations are successful, allocating arrays in all these cases would create unnecessary garbage collection on every validation call.

**Comment by ericmorand** [comment]
Thanks for your answers.

> They are needed in more complex schemas and difficult to avoid with one-pass compilation.

To ensure that our schemas are fully tested - and thus that we can detect non-backward compatible changes to them, we cover the validation function of each of them with test cases until we get 100% code coverage.

How can we enable two-passes compilation to remove unreachable codes?

If it is not possible, what are your recommandations to get 100% code coverage for JSON schemas using AJV?

**Comment by ericmorand** [comment]
Would you accept a PR that add something like this?

```ts
function addError(gen: CodeGen, errObj: Code): void {
  const err = gen.const("err", errObj)

  // let's ignore the else that may not be reachable
  gen.code(_`/* istanbul ignore else */`)

  gen.if(
    _`${N.vErrors} === null`,
    () => gen.assign(N.vErrors, _`[${err}]`),
    _`${N.vErrors}.push(${err})`
  )
  gen.code(_`${N.errors}++`)
}
```

Maybe this could be controlled by some configuration?

Or maybe there is a way to plug into the rendering system of AJV that would allow us to customize the output without having to change to source code of AJV itself?

**Comment by ericmorand** [comment]
Or maybe AJV is not optimizing the code as advertised [here](https://github.com/ajv-validator/ajv/blob/master/docs/codegen.md#code-optimization):

```
CodeGen class generates code trees and performs several optimizations before the code is rendered:

* removes empty and unreachable branches (e.g. else branch after if(true), etc.).
```

Clearly, `if(vErrors === null)` is identical to `if (true)` in the context of my example, and it is clearly identified as such by IDEs like WebStorm:

![image](https://user-images.githubusercontent.com/125664/138610121-28887e86-765f-4680-a878-151cd6e0c419.png)

Would you accept a PR that fixes this optimization issue? Or maybe I did not enable it correctly. Here is what I am doing to instanciate AJV:

```ts
const compiler = new Ajv({
  code: {
    source: true,
    es5: false,
    lines: true,
    optimize: 2
  },
  allErrors: true
});
```

By the way, we have the same issue when disabling `allErrors`:

```js
function validate10(data, {instancePath = "", parentData, parentDataProperty, rootData = data} = {}) {
  let vErrors = null;
  let errors = 0;
  // else not reachable
  if (errors === 0) {
    if (typeof data === "string") {
      if (!pattern0.test(data)) {
        validate10.errors = [{
          instancePath,
          schemaPath: "#/pattern",
          keyword: "pattern",
          params: {pattern: "^\\d{7}$"},
          message: "must match pattern \"" + "^\\d{7}$" + "\""
        }];
        return false;
      }
    } else {
      validate10.errors = [{
        instancePath,
        schemaPath: "#/type",
        keyword: "type",
        params: {type: "string"},
        message: "must be string"
      }];
      return false;
    }
  }
  validate10.errors = vErrors;
  return errors === 0;
}
```

**Comment by epoberezkin** [comment]
> How can we enable two-passes compilation to remove unreachable codes?

It's not something you can enable, it might be possible in theory to avoid unreachable code, but it was never the design objective.

> until we get 100% code coverage

I don't think it's achievable (or even necessary) - you can get close to it though, by covering all the main branches.

> Would you accept a PR that add something like this?

You can absolutely do it in the fork, but I am not supportive of the idea to add something that is not needed by a substantial number of the users, sorry.I don't know anybody else who tests schemas, leave alone aiming for 100% coverage... I did measure coverage of the compiled schema code, it gets to about 98% on medium size schemas - it seems good enough.

> maybe AJV is not optimizing the code as advertised

it does, but it only analyses relatively simple cases like `if (true) { ... }` or `if (false) { ... }` etc. - you can check out the optimizer code

> Clearly, if(vErrors === null) is identical to if (true) in the context of my example

That requires non-local optimization - possibly, some other optimizers can do it.

> Would you accept a PR that fixes this optimization issue

It's all about the return on investment, to be honest (as in how much extra code for how much benefit).

**Comment by ericmorand** [comment]
Well, it seems that cleaning the generated code with a dead code elimination tool (like https://babeljs.io/docs/en/babel-plugin-minify-dead-code-elimination) removes the unreachable parts of the validation code, at least when `allErrors` is set to false. It mean that we should be able to generate a flavor of the code for our testing and code coverage, while publishing another flavor (with `allErrors` set to true) for production.

**Comment by epoberezkin** [comment]
Ah - great - worth adding it to the doc as a suggestion for standalone compilation toolchain.

ajv internal optimiser makes some aggressive assumptions, so it’s helpful anyway (unless you have custom keywords and cannot make such assumptions - see the doc - in which case it can be disabled and external optimiser would be even more valuable:).
