### ISSUE TITLE
Ajv-related error in the build stage during docker execution

### ISSUE THREAD

**Issue by MagicDev090** [ajv-validator/ajv#1801]
Hi
I am using ajv@8.1.0 and ajv-formats@2.0.2 and ajv-errors@3.0.0
My project is built without any errors on my local environment.
But when building docker image, it throws error as follow:
![image](https://user-images.githubusercontent.com/54931597/138936113-938ca827-aaa4-4343-98e7-87e02cb0ca6d.png)

Why does this error happen? What should I do to fix this error?
Please help me.
Thanks

**Comment by epoberezkin** [comment]
Most likely you have a different Ajv version. This is not an Ajv issue as it runs locally, sorry
