### ISSUE TITLE
For ultimate performance for nodejs, take a look here!

### ISSUE THREAD

**Issue by ahungrynoob** [ajv-validator/ajv#1802]
**What version of Ajv you are you using?**

**What problem do you want to solve?**

**What do you think is the correct solution to problem?**
https://github.com/ahungrynoob/jsonschema
**Will you be able to implement it?**

**Comment by epoberezkin** [comment]
Sorry, this is not an Ajv issue... There are many lists of JSON Schema validators online - please post there
