### ISSUE TITLE
Overriding default errors on custom keyword is not working

### ISSUE THREAD

**Issue by TBoonX** [ajv-validator/ajv#181]
I am using version 4.0.5 <- there I defined the following keyword:

```
ajv.addKeyword("validateMaxPoints", {
  errors: true,
  async: false,
  validate: function(value, dataObject) {
    if (this.errors === null)
      this.errors = [];

    this.errors.push({
      keyword: "validateMaxPoints",
      message: "maxPoints attribute should be " + 0 + ", but is " + 0,
      params: {
        keyword: "validateMaxPoints"
      }
    });

    return false;
  }
});
```

I added _validateMaxPoints_ to the schema, compiled it and validated my data.

I expected to see my custom error object in the errors array, but instead I got:

```
{ keyword: "validateMaxPoints",
    dataPath: "",
    schemaPath: "#/validateMaxPoints",
    params: { keyword: "validateMaxPoints" },
    message: "should pass "validateMaxPoints" keyword validation",
    schema: true,
    parentSchema: 
     { type: "object",
       properties: [Object],
       required: [Object],
       validateMaxPoints: true },
    data: 
     { user: "112233445566778899101112",
       title: "title",
       timestamp: "Wed May 04 2016 12:26:24 GMT+0200 (CEST)",
       maxPoints: 10,
       type: "list",
       limit: "",
       questions: [Object] } }
```

Is this an error or did I missed something?

**Comment by epoberezkin** [comment]
looks like a bug, thanks

**Comment by epoberezkin** [comment]
not a bug actually. `errors` is a property of validation function, not a property of `this`.

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords

**Comment by TBoonX** [comment]
OK. Would you provide the code for that? I don't know to access the property of my synchronous validating keyword. Perhaps adding this code snippet to the docs would also be nice.

**Comment by epoberezkin** [comment]
``` javascript
ajv.addKeyword("validateMaxPoints", {
  errors: true,
  validate: function xyz(value, dataObject) {
    xyz.errors = [];

    xyz.errors.push({
      keyword: "validateMaxPoints",
      message: "maxPoints attribute should be " + 0 + ", but is " + 0,
      params: {
        keyword: "validateMaxPoints"
      }
    });

    return false;
  }
});
```

**Comment by TBoonX** [comment]
With that the error array (_var model = ajv.compile(myModel); model(data); model.errors_) does not contain my error.

**Comment by epoberezkin** [comment]
Not sure what is myModel in your case, maybe it does not contain the keyword?
It works for me: https://tonicdev.com/esp/5730bf365b4cad1100742570

**Comment by TBoonX** [comment]
You example works on my machine.
Here my full not working code:

```
var Ajv = require('ajv');
var ajv = Ajv({
  verbose: true,
  allErrors: true
    //v5: true  //enable v5 proposal of JSON-schema standard
}); // options can be passed, e.g. {allErrors: true}

//build schema
//TODO added points to questions and check if the summation of all points are equals to maxPoints
ajv.addKeyword('validateMaxPoints', {
  errors: true,
  async: false,
  type:'object',
  validate: function myValidation(value, dataObject) {
    if (myValidation.errors === null)
      myValidation.errors = [];

    myValidation.errors.push({
      keyword: 'validateMaxPoints',
      message: 'maxPoints attribute should be ' + 0 + ', but is ' + 0,
      params: {
        keyword: 'validateMaxPoints'
      }/*,
      dataPath: '.maxPoints',
      schemaPath: '#/validateMaxPoints',
      schema: true*/
    });

    return false;
  }
});
const test = {
  type: 'object',
  properties: {
    user: objectid,
    title: {
      type: 'string'
    },
    timestamp: {
      type: 'string'
    },
    maxPoints: {
      type: 'number'
    },
    type: {
      type: 'string',
      enum: ['auto', 'list', 'exam']
    },
    limit: {
      type: 'number'
    },
    /*questions: {
      type: 'array',
      items: question
    }*/
  },
  required: ['user', 'timestamp', 'type'],
  validateMaxPoints: true
};

//export
module.exports = ajv.compile(test);
```

After that I do:

```
      const success = TestModel(slightlyWrongTest);

      expect(success).to.equal(false);
      console.log(TestModel.errors);
```

Versions: nodejs 6.0.0, npm 3.8.6

**Comment by epoberezkin** [comment]
https://tonicdev.com/esp/5731a55eabbf001200bbc028 - it works.
The issue seems to be though that it doesn't validate this custom keyword if there is some other error before it.

**Comment by TBoonX** [comment]
Please add this information to the docs if its a desired behavior.

**Comment by epoberezkin** [comment]
It's something that needs improving/fixing rather than documenting :)

**Comment by epoberezkin** [comment]
Fixed in 4.1.3

**Comment by jtlapp** [comment]
I didn't grok what it might mean to add `errors` to the validator function until I saw @epoberezkin's example of doing so. Sure would have helped to see this in the documentation:

> ```
> ajv.addKeyword("validateMaxPoints", {
>   errors: true,
>   validate: function xyz(value, dataObject) {
>     xyz.errors = [];
> 
>     xyz.errors.push({
>       keyword: "validateMaxPoints",
>       message: "maxPoints attribute should be " + 0 + ", but is " + 0,
>       params: {
>         keyword: "validateMaxPoints"
>       }
>     });
> 
>     return false;
>   }
> });
> ```

**Comment by QuotableWater7** [comment]
This is a pretty awkward API...

**Comment by bykbtzr** [comment]
@QuotableWater7 probably because its an internal API that was just made public without any adaptation.

**Comment by thomaux** [comment]
Almost lost my mind trying to figure out why the errors I was assigning to `this.errors` were not showing up.
It might be helpful to include a specific note on the need to name your `validate` function in order for this setup to work? The docs at this point are not clear enough on that point.

**Comment by Qix-** [comment]
Years later, docs still kind of leave a lot to be desired.

**Comment by aqualaguna** [comment]
damn it this issue is still there. please fix asap.

**Comment by rofrol** [comment]
Example repo https://github.com/rofrol/ajv-regexp-errormessage-example
