### ISSUE TITLE
Dynamic module import not working

### ISSUE THREAD

**Issue by odungern** [ajv-validator/ajv#1823]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
/8.6.1/ajv2019

**JSON Schema**
Don't get to the point where a schema could be loaded ..

**Sample data**
Don't get to the point where data could be checked with the schema ..

**Your code**
```javascript
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="expires" content="0" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
<div><h3>Dynamic Module Import</h3></div>

	<script type="module">
		
		import('https://specif.de/check.js').then( mod => {
			console.debug('mod: ',mod);
			console.info('7x3=',mod.multiply(7,3));
		});

		import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.6.1/ajv2019.min.js').then( mod => {
			console.debug('mod: ',mod);
		});

	</script>
</body>
</html>
```

**Validation result, data AFTER validation, error messages**
Chrome Console:
- First module is loaded and can be used
- Second module (ajv2019) creates an error
![grafik](https://user-images.githubusercontent.com/8947971/142674597-06d98153-3501-446d-994b-a7ec599e04c3.png)

**What results did you expect?**
ajv module is dynamically loaded and can be used.

**Are you going to resolve the issue?**
We wouldn't know how ...

Thanks a lot!  We have been using /4.11.8/ajv for quite a while and are very pleased with it!
- https://specif.de/apps/edit.html

Best regards, 
The Specif-Viewer Team

**Comment by epoberezkin** [comment]
Please try 8.8.0

**Comment by odungern** [comment]
Module seems to get loaded with 8.8.0 and 8.8.1:
![grafik](https://user-images.githubusercontent.com/8947971/142703413-1d000ec2-b8fb-4250-b92c-5f5544c6e687.png)

Will have a look tomorrow whether I can instantiate and use it. Not sure whether I should see any exported functions.

Thanks a lot for the quick tip - I hadn't realized the 8.6.1 was already outdated ..

**Comment by odungern** [comment]
Added an instantiation:
```javascript
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="expires" content="0" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
<div><h3>Dynamic Module Import</h3></div>

	<script type="module">
		
		import('https://specif.de/check.js').then( mod => {
			console.debug('mod: ',mod);
			console.info('7x3=',mod.multiply(7,3));
		});

		import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.1/ajv2019.min.js').then( mod => {
			console.debug('mod: ',mod);
			let ajv = new mod.Ajv({allErrors: true})
			console.debug('ajv: ',ajv);
		});

	</script>
</body>
</html>
```

The console says:
![grafik](https://user-images.githubusercontent.com/8947971/142704113-092878b4-f91d-49d9-857e-23a672d2079f.png)

**Comment by odungern** [comment]
Will try tomorrow to destructure the module on import to obtain Ajv explicitly - perhaps it will work.

**Comment by odungern** [comment]
Can't get it working:

```
const mod = await import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.1/ajv2019.min.js');
```
--> mod is defined, but nothings seems to be exported.

```
const { Ajv } = await import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.1/ajv2019.min.js');
```
--> Ajv is undefined

```
const { default: Ajv } = await import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.1/ajv2019.min.js');
```
--> Ajv is undefined

```
const { default: {Ajv} } = await import('https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.1/ajv2019.min.js');
```
--> Ajv is undefined

Frankly, I have no idea any more what I could try ...

**Comment by epoberezkin** [comment]
8.8.0 fixed the bundle that was broken when bundled with rollup, it’s now back to browserify…

I’ve never used the asynchronous import, it’s possible that bundle doesn’t support it properly, But assuming it’s executed after it’s loaded Ajv should be in global ajv2019

**Comment by epoberezkin** [comment]
https://ajv.js.org/guide/environments.html#browsers

**Comment by odungern** [comment]
Thanks for the tip and your time to support us. Bundling at compile time is static import, which we wanted to avoid. But your link let us find the option of 'standalone validation support'. That's a great feature we will explore. 

Thanks again, will close the issue.
