### ISSUE TITLE
Working with int64 timestamps (JTD)

### ISSUE THREAD

**Issue by arsinclair** [ajv-validator/ajv#1825]
I have a timestamp that I need to validate, and in my JSON it looks like this: `"postedOn": 1508689942000,`.

I'm using JTD with Typescript. The data type of this timestamp would be int64, however it looks like this type is not implemented in ajv.
I found a package that implements it - https://ajv.js.org/packages/ajv-formats.html, however it turns out I can't use `formats` keyword with JTD.

I'm stuck, and I can't find anything helpful online. I believe _int64_ is a very common use-case, and I'm surprised to not find any clear guidance on that.

**Comment by epoberezkin** [comment]
int64 is not recommended to use for Internet messages for compatibility reasons. In fact, JavaScript itself does not support int64, the maximum integer it can represent is 2^53 – JTD spec has a reference to a relevant RFC.

There is an option int32range for JTD validation that removes range checking though: https://ajv.js.org/options.html#int32range

JTD also supports `type: timestamp` - why can't you use this one instead?

"format" (or any other non-standard JTD keyword) can be used with JTD schemas inside metadata member – it has to be added to the instance using addKeyword method, e.g. "format" definition is here: https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/format/format.ts (you have to import compiled file from "dist" folder though).

**Comment by arsinclair** [comment]
Thank you for your help. I have briefly looked through formats allowed by rfc3339 and figured out that they don't accept timestamps in _number-of-ticks-since_ format, therefore I didn't want to use `timestamp` type.

However, I just read the whole paper and it looks like this is the endorsed standard for the Internet, so I guess I'll have redesign the system, so it produces rf3339 supported timestamps.

Unfortunately, it doesn't accept milliseconds (only fractions of a second), but luckily I don't need them in my case.

**Comment by epoberezkin** [comment]
It does accept milliseconds after the decimal point in seconds parts.

Using the number is fine too, if you don’t need milliseconds 2^32 seconds will last you 49000 years, and if you do - you could either store it as a decimal string or use JS integer limit where 2^53 will last over 200k years, so all should be fine.
