### ISSUE TITLE
VSCode intelliSense is too slow with ajv >= 8.0.0

### ISSUE THREAD

**Issue by turkerdev** [ajv-validator/ajv#1829]
With version 8 and greater, in VSCode ajv intellisense getting slower and slower. here are the roughly calculated times to load and a video proof.
```
8.8.2 ~10 secs
8.3.0 ~10 secs
8.1.0 ~5 secs
8.0.0 ~3 secs
7.2.4 instant
7.0.0 instant
```

https://user-images.githubusercontent.com/48413508/143576552-026ff2f6-48fe-4bb5-8129-2019d5cdc87b.mp4

**Comment by rehanvdm** [comment]
What version of TS are you on? This is a known issue https://github.com/ajv-validator/ajv/issues/1667, if you just search this repo for the word slow, you will find multiple issues. Upgrading your TS might work?

**Comment by turkerdev** [comment]
> What version of TS are you on? This is a known issue #1667, if you just search this repo for the word slow, you will find multiple issues. Upgrading your TS might work?

its already the latest one, v4.5.2

**Comment by epoberezkin** [comment]
@rehanvdm thank you - closing as a duplicate, please raise any questions there.

@bajosiaa the reason for slowness could be that your are importing .ts source of Ajv (so it has to be recompiled) and not a compiled .js file, but not sure without seeing your validate.ts
