### ISSUE TITLE
Coerce type breaking with oneOf

### ISSUE THREAD

**Issue by mmatena** [ajv-validator/ajv#183]
cc @tnrich

I am using Ajv version 4.0.5. Using type coercion sometimes causes validation to fail where it would not have failed if type coercion was not used.

Here is an example snippet:

``` javascript
var schema = {
    "oneOf": [
        {"type": "null"}, 
        {"type": "integer"}
    ]
};

var valid = require("Ajv")({
        coerceTypes: false,
    })
    .validate(schema, null);

// true
console.log(valid)


var valid2 = require("Ajv")({
        coerceTypes: true,
    })
    .validate(schema, null);

// false
console.log(valid2)
```

**Comment by epoberezkin** [comment]
Coercing types affects validation result, what is wrong here? `null` is coerced to `0` (see [coercion rules](https://github.com/epoberezkin/ajv/blob/master/COERCION.md)), so both subschemas become valid and `oneOf` becomes invalid.

How is it different from validating `null` against the schema `{ "not": { "type": "integer" } }`? With type coercion it fails, without - passes.

**Comment by tnrich** [comment]
Hey @epoberezkin , I think we're probably confused as to how type coercion is supposed to work in ajv. 

To me, this line from the documentation suggests a different functionality to the one you just described:

> If there are multiple types allowed in type keyword the coercion will only happen if none of the types match the data and some of the scalar types are present (coercion to/from object/array is not possible). 

Can you not have multiple allowed types and do type coercion with ajv?

If not, why not? If you can, how would we implement the above case?

Thanks for the help,
Thomas

**Comment by epoberezkin** [comment]
type keyword can have multiple types: `{ "type": ["integer","null"] }`

**Comment by tnrich** [comment]
Aha, thanks for the help!
