### ISSUE TITLE
Integer type keywords

### ISSUE THREAD

**Issue by btd** [ajv-validator/ajv#1836]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Migrate from v6 to v8

**Repro**

```javascript
const Ajv = require('ajv');
const ajv = new Ajv({ allErrors: true, useDefaults: true });

ajv.compile({ type: 'integer', minumum: 10 }) // throws unknown keyword
ajv.compile({type: "number", maximum: 5}) // fine
ajv.compile({type: "number", minimum: 5}) // fine
```

**What results did you expect?**
Like it was before, integer type to have minimum keyword.
I did not found the difference in schema drafts from v6 to v8. Maybe i am looking not in right place?

**Are you going to resolve the issue?**
If it is a bug, i can help

**Comment by epoberezkin** [comment]
it's typo - s/minumum/minimum/

**Comment by btd** [comment]
Oh, sorry for such a dumb issue 🤦

**Comment by btd** [comment]
I just found we have this typo for a year 🤦 🤦🤦 Really thank you for adding strict option and making it default. I would not notice the typo otherwise

**Comment by epoberezkin** [comment]
Not to worry, happens to the best of us...

That's exactly why this feature was added - writing tests for schemas is "mission impossible", and kind of pointless - schemas supposed to reduce the need for testing, and now you have to test them - and permissiveness of JSON Schema spec is just wrong I think - this should be an invalid schema in the spec imho (as it would be in JTD)...

If you use typescript, you may also look into type transformers that further reduce the coding mistakes by making sure that your data type and schema types are consistent: https://ajv.js.org/guide/typescript.html
