### ISSUE TITLE
How to make a property nullable conditionally depending on other property

### ISSUE THREAD

**Issue by awesomelike** [ajv-validator/ajv#1839]
I have an object that can be in one of 4 states:

 1. `{"A": "something", "B": [{"C": "D"}]}`
 2. `{"A": "", "B": [{"C": "D"}]}`
 3. `{"A": "something", "B": null}`
 4. `{"A": "", "B": null}`

In my Ajv schema validation I want to make the property `"B"` `nullable: true` only if the property `"A"` is **not** an empty string. 

How can I achieve this?

**Comment by epoberezkin** [comment]
Hi @awesomelike 

This question is a general JSON Schema usage question, it's not specific to Ajv that implements this specification. The best place to get advice on how to write JSON Schemas is StackOverflow - it is usually quite fast there.

You may also look to ajv site for JSON Schema keywords, you either need `nullable` or `type`.

**Comment by awesomelike** [comment]
https://stackoverflow.com/questions/70303053/ajv-how-to-make-a-property-nullable-conditionally-depending-on-other-property
