### ISSUE TITLE
Should we let useDefaults 'empty' work on fields containing whitespaces after executing `trim` transform

### ISSUE THREAD

**Issue by asaid-0** [ajv-validator/ajv#1842]
**What version of Ajv are you using?**
ajv@6.12.6
ajv-keywords@3.5.2

**What problem do you want to solve?**
I used `trim` transform to remove whitespaces and `useDefaults: 'empty'` and actually this didn't work for me

To reproduce: https://runkit.com/asaid-0/61b3e99224487e000899e8ee

**What do you think is the correct solution to problem?**
I don't know if this should be handled the way I think (execute the transform before adding the defaults) or it should be like this.

or maybe adding a new value for useDefaults like `useDefaults 'whitespaces'`

**Will you be able to implement it?**
Yes, maybe

**Comment by epoberezkin** [comment]
You need to use allOf and have transform in the first subschema, and the rest in the second subschema, as otherwise default checks the property before it is trimmed...
