### ISSUE TITLE
Replace uri-js by fast-uri

### ISSUE THREAD

**Issue by zekth** [ajv-validator/ajv#1844]
fast-uri is a fork of uri-js which is rewritten in javascript to focus on performances issues.

**What version of Ajv you are you using?**

Ajv 8.8.2

**What problem do you want to solve?**
Speed improvement

**What do you think is the correct solution to problem?**
As discussed with @epoberezkin , an option can be added to inject `fast-uri` to replace `uri-js` to not have a breaking change in the current version

**Will you be able to implement it?**

Yes

Ref: https://github.com/fastify/fast-uri

**Comment by epoberezkin** [comment]
Let's please do in the same way regexp option was added, with URI as default - there should be defined a required interface (type) and fast-url would be dev dependency for tests only.

It would be good if tests are run with it though (doubling the test time...), to see if we can swap in in v9.

Thank you!
