### ISSUE TITLE
dist directory missing when using bower install

### ISSUE THREAD

**Issue by irmarod** [ajv-validator/ajv#186]
I'm using your library in my webapp (on the browser).  

I did a `bower install --save ajv` which did as expected, pulled the ajv repo into my bower_components directory.  The dist directory & ajv.min.js file are missing (in your bower.json you have the following: `"main": "dist/ajv.min.js",`).  Is this a bug or do I need to pull the library into my app a different way?

**Comment by epoberezkin** [comment]
dist directory is not in the repo and bower does not have its own storage. You can choose one of the following:
1. `npm install` - the dist is there
2. `npm run build` after you install from bower
3. use cdnjs

I recommend to stop using bower and use npm instead.

**Comment by irmarod** [comment]
my company does not allow loading from cdn's unfortunately :( lame!

the `npm run build` task, did you mean to run it from the bower_components/ajv dir or create my own build task in my own app's package.json?  

I looked at your build task in your package.json & it's running `"build": "node scripts/compile-dots.js",` That's what will build out the dist dir?

**Comment by epoberezkin** [comment]
Sorry, you need to run `npm run build && npm run bundle-all`.
`compile-dots.js` only converts dots to js, then you need to bundle it for the browser.
It's a shame that bower stopped allowing to automate it with post-install script without providing their own storage like npm. See #132 and #171.
I simply stopped using bower because of that...

**Comment by irmarod** [comment]
I ran into issues w/the npm install timing out trying to get phantomJS & consequently none of the other devDependencies installed after that.  As expected ran into issues with the `npm run build && npm run bundle-all` since the other devDependencies weren't installed.

I gave up & included the ajv.min.js file into our app off of the node_modules/ajv/dist directory (instead of bower)
On a different note, in our build process we min all js files into one; as a result I get an error in the browsers console where ajv.min.js references dist/ajv.min.js.map.  I suppose we can fork and update.  

Btw, your library rocks!  Thanks for your quick help! 👍 👍

**Comment by epoberezkin** [comment]
Thank you. If you do `npm install` you don't need to run this script, all the bundles are included in the npm package already.

Closing this issue until we come up with some better ideas...

**Comment by meticoeus** [comment]
One common strategy I've seen is to commit dist/*.js in the repo for the tagged release commit, then delete it afterwards in a followup commit. This keeps bower usage simple as long as you are using release commits. I think it will be a little while before bower dies off completely.
