### ISSUE TITLE
JSON Type Definition ok when inlined, fails when imported

### ISSUE THREAD

**Issue by Javarome** [ajv-validator/ajv#1860]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.8.2

**Ajv options object**
```javascript
{allErrors: true, validateSchema: "log"}
```

**JSON Schema**

```json
{
  "properties": {
    "string": {"type": "string"}
  }
}
```

**Your code**

```javascript
import Ajv from "ajv/dist/jtd"
import * as rangeTypeDef from "./BeamRange.typedef.json"

const ajv = new Ajv({allErrors: true, validateSchema: "log"})
ajv.addSchema(rangeTypeDef, "range")
const validate = ajv.compile(rangeTypeDef)
```

**Validation result, data AFTER validation, error messages**
```
strict mode: unknown keyword: "default"
```

**What results did you expect?**
Validation to pass without errors, which works if I inline the JSON Type def instead of importing it:
```javascript
import Ajv from "ajv/dist/jtd"

const ajv = new Ajv({allErrors: true, validateSchema: "log"})
const rangeTypeDef = {
   properties: {
      string: {type: "string"}
   }
}
ajv.addSchema(rangeTypeDef, "range")
const validate = ajv.compile(rangeTypeDef)
```

**Are you going to resolve the issue?**
No, but I could see while debugging that there is indeed a `default` property created in the `schema` object:
```javascript
{
  properties: {
    string": {
      type: "string"
    }
  },
  default: {  // <-- Why this when importing?
    properties: {
      string: {
        type: "string"
      }
    }
  }
}
```
It suspect this is related to the `default` exported value of a module.

**Comment by epoberezkin** [comment]
I suspect this is how typescript (or bundler you use) imports JSON, I don't think Ajv could add it, and it would have added it to inline object too.

You can try `import x = require('...')` maybe?

**Comment by Javarome** [comment]
Indeed using `require` fixes the problem, thanks.
