### ISSUE TITLE
Validate a json object with depth constraint

### ISSUE THREAD

**Issue by c3Vu** [ajv-validator/ajv#1863]
Hello,

I am wondering if I could validate a json object with a configurable depth. Because validating a big deep json always costs a lot of time. Could I just validate the object partially? Like for a depth of 1, I can validate the object and array without going deeper?

**Comment by epoberezkin** [comment]
you could do it with a user-defined keyword: https://ajv.js.org/guide/user-keywords.html

**Comment by epoberezkin** [comment]
I mean if the intention is to fail when the object is deeper than X. If you want to ignore any errors deeper than X, it won't be possible I think.
