### ISSUE TITLE
Parse objects on the query string

### ISSUE THREAD

**Issue by miladezzat** [ajv-validator/ajv#1867]
I will try to send an object via query string from the frontend, to the API and I set the ajv as validation layer by it doesn't convert the object 

example:
```js
http://localhost:300?bedrooms={min: 5, max: 6}
```

result 
`"bedrooms={min: 5, max: 6}"`

I expect 
```js
{
 bedrooms : {
   min: 5,
   max: 6,
}
}
```

**Comment by miladezzat** [comment]
could you help man @epoberezkin

**Comment by miladezzat** [comment]
Hello Man @epoberezkin

**Comment by epoberezkin** [comment]
sorry for the delay.

Converting strings to objects is definitely out of scope of what Ajv does, it should happen in your application code...
