### ISSUE TITLE
Using strict mode in both draft-2019-09 and draft-07

### ISSUE THREAD

**Issue by annahassel** [ajv-validator/ajv#1872]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`^8.8.2`

**Your code**

```javascript
const Ajv = require('ajv/dist/2019')
const draft7MetaSchema = require('ajv/dist/refs/json-schema-draft-07.json')

const ajvInstance = new Ajv()

ajvInstance.addMetaSchema(draft7MetaSchema)

const validate = ajvInstance.compile({
  $schema: 'http://json-schema.org/draft-07/schema',
  type: 'array',
  contains: {
    type: 'number',
  },
  minContains: 2
})

const result = validate([1])

console.log(result, validate.errors)
```

**Validation result, data AFTER validation, error messages**

```
[
  {
    instancePath: '',
    schemaPath: '#/contains',
    keyword: 'contains',
    params: { minContains: 2 },
    message: 'must contain at least 2 valid item(s)'
  }
]
```

**What results did you expect?**

`Error: strict mode: unknown keyword: "minContains"`

Is it bug or feature? I want to use both drafts in my project as it described here https://ajv.js.org/guide/schema-language.html#draft-2019-09-and-draft-2020-12, but it seems like there is no difference between draft 2019-09 and draft-07 in this case.

**Comment by epoberezkin** [comment]
I'd say it's a limitation. `$schema` is only indicating which metaschema to validate against, not which ajv version to use. Strict mode does not take into account $schema, it is completely defined by the import.

If you want to combine 07 and 2019-09 schemas AND have strict mode working correctly, the only way to do it to use two ajv imports from "ajv" for draft-07 schemas and from "ajv/dist/2019" for 2019 schemas.

The reason it's not handled inside Ajv is that it would create both bundle size overheads (a single Ajv class that supports all schemas) and it's needed by a small minority of users. We could potentially have some ajv/dist/universal that does it - I need to think whether it's worth the effort given how rarely it is needed...

The simple workaround have all your schema in 2019-09 instance, so they can depend on each other, and do a separate compilation in the correct instance, probably best as part of CI/tests to identify and misused keywords based on $schema with a very simple logic in your app or tests:

```javascript
const Ajv2019 = require('ajv/dist/2019')
const Ajv7 = require('ajv')

const ajv2019 = new Ajv2019()
const ajv7 = new Ajv7()

schemas.forEach(s => s.$schema == "http://json-schema.org/draft-07/schema" ? ajv7.compile(s) : ajv2019.compile(s))
```

**Comment by annahassel** [comment]
Thank you for the detailed answer!
