### ISSUE TITLE
Broken links in doc

### ISSUE THREAD

**Issue by roman-khazanskii** [ajv-validator/ajv#1873]
https://github.com/ajv-validator/ajv/blob/418cd0f4308c07c627071b4d03544e7cc57f235c/docs/guide/combining-schemas.md?plain=1#L44

Links to `Options` and `addSchema` are broken

**Comment by smithc10** [comment]
currently working on this. will have a PR up shortly

**Comment by smithc10** [comment]
https://github.com/ajv-validator/ajv/pull/2006
