### ISSUE TITLE
addFormat definitions ignored

### ISSUE THREAD

**Issue by sirkrisp** [ajv-validator/ajv#1880]
Hi, in my code (see below) I create the ajv instance in `validation.ts`, and then import that instance into other files. However, I get an error message when calling `validateSchema` from `utils.ts` complaining about a missing format identifier `email` (and indeed, `ajv.formats` returns an empty object). When I add the format in the function `validateSchema` itself it works - but why does it fail when I add the format in `validation.ts`?

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

```
"ajv": "^8.8.2"
```

**Your code**

```javascript
// validation.ts
export const ajv = (new Ajv({
    discriminator: true,
    formats: {
        email: <a valid regex expression>
    }
}))

// utils.ts
import {JSONSchemaType} from "ajv";
import {ajv} from "./validation";

export function validateSchema<T>(
    args: T,
    schema: JSONSchemaType<T>,
) {
    if(!schema.$id) throw Error("id missing")
    const validate = ajv.getSchema(schema.$id) || ajv.compile(schema)
    const isValid = validate(args)
    if(isValid) return {isValid: true as const}
    else {
        return {
            isValid: false as const,
            errors: validate.errors
        }
    }
}

// auth.ts
import {JSONSchemaType} from "ajv";

export interface SignUpArgs {
    firstName: string,
    lastName: string,
    email: string,
}

export const nameSchema: JSONSchemaType<string> = {
    type: "string",
    maxLength: 18,
    minLength: 1,
}

// Error: unknown format "email" ignored in schema at path "#/properties/email" 
export const emailSchema: JSONSchemaType<string> = {
    type: "string",
    format: "email",
    maxLength: 60,
}

export const signUpArgsSchema: JSONSchemaType<SignUpArgs> = {
    type: "object",
    $id: "signUpArgsSchema",
    properties: {
        firstName: nameSchema,
        lastName: nameSchema,
        email: emailSchema
    },
    required: ["firstName", "lastName", "email"],
    additionalProperties: false
}
```

**Validation result, data AFTER validation, error messages**

```
Error: unknown format "email" ignored in schema at path "#/properties/email"

```

**Comment by epoberezkin** [comment]
hi - all format definitions are shipped as part of ajv-formats package, not as part of ajv - see ajv-formats docs please.

**Comment by sirkrisp** [comment]
This error also occurs with ajv-formats (e.g. if I use `addFormats(ajv)` in `validation.ts`. I did not use ajv-formats in my code to demonstrate that it is an issue with ajv. So here I just used a custom format (see https://ajv.js.org/guide/formats.html#user-defined-formats).

**Comment by epoberezkin** [comment]
I don’t quite follow what is called to produce the error.

Could you please put a self-contained code sample in one file that I could run to see an error? Ideally, please put it into runkit.com

**Comment by epoberezkin** [comment]
Also please remove all the unnecessary details if possible to minimise the size of the example that creates the error, e.g. the schema could have been `{format: “email”}`

**Comment by sirkrisp** [comment]
Hi, I tried to create a runkit file but ajv version 8.9.0 does not work with runkit => gives Syntaxerror message (you can see the error just by using the sample runkit notebook and updating ajv). Anyway, below is the javascript file for testing:

```javascript
var Ajv = require('ajv');

var ajv = new Ajv({
    // options here
    discriminator: true,
    formats: {
        email: /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i
    }
});

// it also did not work for me when I call
// ajv.addFormat("email", <regex>)

function validateSchema(
    args,
    schema,
) {
    if(!schema.$id) throw Error("id missing")
    // if I call ajv.addFormat("email", <regex>) here, it works
    const validate = ajv.getSchema(schema.$id) || ajv.compile(schema)
    const isValid = validate(args)
    if(isValid) return {isValid: true}
    else {
        return {
            isValid: false,
            errors: validate.errors
        }
    }
}

const signUpArgsSchema = {
    type: "object",
    $id: "signUpArgsSchema",
    properties: {
        email:{format: "email"}
    },
    required: ["email"],
    additionalProperties: false
}

console.log(validateSchema({email: "qweqwe@test.com"}, signUpArgsSchema));
```

**Comment by sirkrisp** [comment]
For others who may have the same problem: What I did now is to put the schemas with formats into the definitions schema, and then added the definitions schema to ajv in the same file where I added the formats. Once you have added the definitions you can reference your schemas with formats with `$ref`.

(I think there might be an issue with ajv when you add the formats in a file different from where you add the schema, although I do not understand how this is possible)

**Comment by epoberezkin** [comment]
I will check what’s going on… Thank you!

**Comment by epoberezkin** [comment]
I am not sure what was the problem, but your example works in runkit: https://runkit.com/esp/61fd65af45df1c0008a15948

What was missing is type keyword alongside format, but I cannot reproduce the original error.

Going to close - please re-open or comment it it's not resolved
