### ISSUE TITLE
only array $ref not resolving, object $ref does from same file

### ISSUE THREAD

**Issue by marko911** [ajv-validator/ajv#1895]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.6.3
**Ajv options object**
``` {
        customOptions: {
          coerceTypes: true,
        },
      }
```

**JSON Schema**
```javascript
{
  "$id": "http://example.com/common",
  "type": "object",
  "definitions": {
    "ThoughtLeader": {
      "properties": {
        "dossierId": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        }
      }
    },
    "CreatedBy": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "fullName": {
          "type": "string"
        }
      }
    },
    "ImperativeGroup": {
      "title": "Imperative Group",
      "type": "object",

      "properties": {
        "createdBy": {
          "$ref": "#/definitions/CreatedBy"
        },
        "recentThoughtLeaders": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ThoughtLeader"
          }
        }
      }
    }
  }
}

```

So the issue is that the `ImperativeGroup.createdBy` resolves fine but the `ImperativeGroup.recentThoughtLeaders` errors with: 
`can't resolve reference #/definitions/ThoughtLeader from id #"`

I've tried every combination of $id and ref structure and still same issue. I'm missing something?

**Comment by epoberezkin** [comment]
Could you please add a minimal executable code that produces the error (ideally to runkit.com - it’s faster to debug there)? The case is pretty basic, either I am missing something or it should work…

**Comment by marko911** [comment]
So here is a runkit [runkit](https://runkit.com/marko911/6209911ba9f71e0008bcdd70). But its returning valid on there. I am using fastify and am getting that error I posted above when the same response returns. So something inside fastify  calling ajv is faultering. Thanks for looking anyways.

**Comment by epoberezkin** [comment]
So maybe it is used there with some other options - could you check? cc @zekth

**Comment by zekth** [comment]
This is likely a fastify problem and not a AJV one. Could you raise this issue in the fastify project for the follow up?https://github.com/fastify/fastify

Thanks

**Comment by marko911** [comment]
Will do. Thanks all @epoberezkin @zekth

**Comment by epoberezkin** [comment]
Thank you @zekth - closing here!
