### ISSUE TITLE
Using `discriminator` in a definition causes failure to compile if `oneOf` contains a reference

### ISSUE THREAD

**Issue by mshick** [ajv-validator/ajv#1899]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`8.10.0`

**Ajv options object**

```javascript
{ discriminator: true }
```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "container": {
      "$ref": "#/definitions/Container"
    }
  },
  "definitions": {
    "Block": {
      "type": "object",
      "properties": {
        "_type": {
          "type": "string",
          "enum": ["foobar"]
        }
      },
      "required": ["_type"],
      "title": "Block"
    },
    "Container": {
      "type": "object",
      "properties": {
        "object": {
          "type": "object",
          "oneOf": [
            {
              "$ref": "#/definitions/Block"
            }
          ],
          "discriminator": {
            "propertyName": "_type"
          },
          "required": ["_type"]
        },
        "array": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/Block"
              }
            ],
            "discriminator": {
              "propertyName": "_type"
            },
            "required": ["_type"]
          }
        }
      }
    }
  }
}
```

**Sample data**

n/a

**Your code**

```javascript
var ajv = new Ajv(options);
var validate = ajv.compile(schema);
```

**Validation result, data AFTER validation, error messages**

```
Error: discriminator: oneOf subschemas (or referenced schemas) must have "properties/_type"
```

**What results did you expect?**

The schema to compile.

**Are you going to resolve the issue?**

Not immediately. 

**Reproduction**

https://runkit.com/mshick/620a919455b3e30009ef1f50

**Comment by epoberezkin** [comment]
Try using full references based on schema $id (like https://example.com/schema#/definitions/Block) - would it work like that?

**Comment by mshick** [comment]
Nice! Glad that PR landed. Appears to solve the issue.

**Comment by Cameramorphic** [comment]
Hi, I also tested this locally and it solves the issue.
I have a question though: I'm glad to see the fix was already merged, but I'm currently blocked by this bug and am wondering when you plan to release it? @epoberezkin
