### ISSUE TITLE
Create schema  from a json object

### ISSUE THREAD

**Issue by kumail194** [ajv-validator/ajv#1904]
Hey can the library support creating the schema from a json object 

Example

```
 const JSONEXAMPLE = {
    "checked": false,
    "dimensions": {
        "width": 5,
        "height": 10
    },
    "id": 1,
    "name": "A green door",
    "price": 12.5,
    "tags": [
        "home",
        "green"
    ]
}
```

and some function like `ajv.createSchema(JSONEXAMPLE)` 

if there is any please point towards the right direction other wise can you add this feature ?

**Comment by epoberezkin** [comment]
Hi - it’s definitely out of scope of the library I’m afraid… I think there must be some other library that does it though, I can’t remember off the top of my head.

In general, you cannot derive a schema from data, but you can create some template of course - if that’s what you need it’s just a loop traversing the object and constructing the schema as it goes - it could be in the application code wherever you need it.
