### ISSUE TITLE
How to put country/state limitation using enum.  Like using Enum value of state based on country

### ISSUE THREAD

**Issue by swamx** [ajv-validator/ajv#1914]
**What version of Ajv you are you using?**
v8.10.0
**What problem do you want to solve?**
I have a list of 3 countries defined as enum [US, UK, CANADA], I would like to keep the enum value of state based on country.
**What do you think is the correct solution to problem?**
NA
**Will you be able to implement it?**
No

**Comment by epoberezkin** [comment]
This is a general JSON schema usage question, not specific to ajv. The best place to ask it is StackOverflow.

**Comment by epoberezkin** [comment]
Quick answer: it should be possible in several ways combining standard JSON schema keywords
