### ISSUE TITLE
minimum and maximum constraints (exclusive or not) that use $data references are improperly validated

### ISSUE THREAD

**Issue by jimklo** [ajv-validator/ajv#1915]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.10.0

**Ajv options object**

```javascript
const Ajv2020 = require("ajv/dist/2020")
const ajv = new Ajv2020({$data: true, allErrors:true})
```

**JSON Schema**

```json
{
    "$id": "rangeList",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "prefixItems": [
      {
        "type": "number",
        "minimum": 0,
        "exclusiveMaximum": { "$data":  "1/prefixItems/1" }
      },
      {
        "type": "number",
        "exclusiveMinimum": { "$data":  "1/prefixItems/0" },
        "maximum": 100
      }
    ],
    "minItems": 2,
    "items": false   
}
```

**Sample data**

```json
[ 50, 50 ]
```

**Your code**

```javascript
const Ajv2020 = require("ajv/dist/2020")

const ajv = new Ajv2020({$data: true, allErrors:true})

const schema = {
    "$id": "rangeList",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "prefixItems": [
      {
        "type": "number",
        "minimum": 0,
        "exclusiveMaximum": { "$data":  "1/prefixItems/1" }
      },
      {
        "type": "number",
        "exclusiveMinimum": { "$data":  "1/prefixItems/0" },
        "maximum": 100
      }
    ],
    "minItems": 2,
    "items": false   
}

const validate = ajv.compile(schema)

const data = [ 50, 50 ]

const valid = validate(data)
if (!valid) {
    console.log(validate.errors)
} else {
    console.log("should not be valid")
}

```
RunKit example: https://runkit.com/jimklo/ajv-range-list-validation

**Validation result, data AFTER validation, error messages**

```
true
```

**What results did you expect?**

I expected validation of `[50, 50]` to fail as the `exclusiveMinimum` constraint for index `1` should not permit the value of index `1` to equal the value of index `0`; as well as the `exclusiveMaximum` constraint for index `0` should not permit the value of index `0` to equal the value of index `1`. 

**Are you going to resolve the issue?**

Not sure how to resolve.

**Comment by epoberezkin** [comment]
your schema is incorrect - the references should point to the locations in the data (they are data references!), not in the schema.

The correct references would be "1/1" and "1/0" respectively - see the working example here: https://runkit.com/esp/622e4e1ada0cfa00087c4fb6
