### ISSUE TITLE
coerceTypes: true only works with "type", can I use coerceTypes: true for "format", if not then can I define my own custom type?

### ISSUE THREAD

**Issue by dilipkumar2k6** [ajv-validator/ajv#192]
My json schema is having many data types, for example date-time, mongoid etc. I liked the concept of coerceTypes: true which help to convert my input json data to corresponding type. However it only works for "type". Since "type" has limited to primitive data types therefore I can't use it for "date-time" or "mongo db id". 

I tried to use the custom "addFormat" method however it doesn't seem like working. Following is my code. Please help.

```
validateSchema: (document, callback)=> {
    //read schema as per collection name
    const collectionName = "schema";
    const schema = require("./transactions/" + collectionName + ".json");
    var ajv      = Ajv({loadSchema: module.exports.loadSchema, coerceTypes: true});
    ajv.addFormat('date-time', function(data, cb) {
      try {
        var obj = new Date(data);
      } catch (err) {
        return cb(err);
      }
      cb(null, obj);
    })
    //compile schema as per $ref
    ajv.compileAsync(schema, function(err, validate) {
      if (err) {
        console.log("validateAgainstSchema err " + err);
        callback(false);
      }
      var valid = validate(document);
      !valid && console.log("error in json schema validation " + JSON.stringify(validate.errors));
      console.log("document after validation  status " + valid + "  modified document " + JSON.stringify(document));
      callback(valid);
    });
  }
```

Following is my scema

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "number"
        },
        "builton": {
          "format": "date-time"
        },
        "_id": {
          "format": "mongoid"
        }
      },
      "required": [
        "street_address",
        "city",
        "state",
        "zip",
        "builton",
         "_id"
      ]
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "$ref": "#/definitions/address"
    }
  }
}
```

Following is test data

```
{
  "shipping_address": {
    "_id":"573a1093d918fe4c19e054d7",
    "zip":"85027",
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC",
    "builton":"2016-03-01T15:55:00.000Z"
  },
  "billing_address": {
    "_id":"573a1093d918fe4c19e054d6",
    "zip":85027,
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC",
    "builton":"2015-03-01T15:55:00.000Z"
  }
}
```

On successful validation, I want this to convert as following

```
{
  "shipping_address": {
    "_id":ObjectId("573a1093d918fe4c19e054d7"),
    "zip":"85027",
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC",
    "builton": new Date("2016-03-01T15:55:00.000Z")
  },
  "billing_address": {
    "_id":ObjectId("573a1093d918fe4c19e054d6"),
    "zip":85027,
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC",
    "builton": new Date("2015-03-01T15:55:00.000Z")
  }
}

```

**Comment by epoberezkin** [comment]
Custom formats can't do coercion, only validation. They are synchronous functions.

You can achieve what you want with custom keywords - they allow modifying data during validation

**Comment by epoberezkin** [comment]
Let me know if custom keywords work for you, closing for now

**Comment by dilipkumar2k6** [comment]
I tried to add keyword "convert", though its calling my function but not doing conversion. Any idea?

```
const ajv = Ajv({coerceTypes: true, useDefaults: true, loadSchema: utils.loadSchemaHandler});

ajv.addKeyword('convert',{
  type: 'string',compile: function(sch,parentSchema) {
    return parentSchema.format === 'date-time' && sch ? function(data) {
      console.log('Converting data '+ data+' to Date object')
      return new Date(data);
    } : function(data) {
      console.log('Not converting data '+ data)
      return data;
    }
  }
});
```

Following is my schema

```
  "createdAt": {
    "type": "string",
    "format": "date-time",
    "convert": true
  }
```

After validation I still see the input createdAt type is string. 

```
  const validSchema    = schemaService.validateData(collectionName, document, true);
  expect(validSchema).to.be.equal(true);
  expect(typeof document.ts.createdAt).to.be.equal('Date');
```

**Comment by epoberezkin** [comment]
See [Define keyword with "compilation" function](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-compilation-function)

> This validation function will be passed data during validation (and also data path, parent object and the property name in the parent object - it allows to create keywords that modify the validated data)

By changing `data` you are not updating the object that contains this data, you are simply updating the local variable. You need to update the property in the parent object - parent object is passed as the 3rd and the property name as the 4th parameter to your validation functions.

**Comment by epoberezkin** [comment]
Sorry, the previous response is a bit confusing. The return value should be the validation result rather than the new data value. If the keyword is purely for data conversion it should return `true`.

**Comment by dilipkumar2k6** [comment]
Thank you for sharing more details. Finally it worked for me & I feel like to treat you :-). Following are details on the final code.

**Schema validation code excerpt:** 

```
// Configure AJV object
const ajv = Ajv({coerceTypes: true,loadSchema: utils.loadSchemaHandler});

// Add convert keyword for date-time schema
ajv.addKeyword('convert',{
  type: 'string',
  compile: function(sch,parentSchema) {
    return parentSchema.format === 'date-time' && sch ? function(value,objectKey,object,key) {

      // Update date-time string to Date object
      object[key] = new Date(value);
      return true;
    } : function() {
      return true;
    }
  }
});
```

**Schema excerpt**

```
"createdAt": {      
  "type": "string",
  "format": "date-time",
  "convert": true
}
```

**My test data excerpt**

```
"createdAt": "2016-07-12T22:34:30.160Z",
"updatedAt": "2016-07-12T22:34:30.160Z"
```

**My test code excerpt**

```
it('should return true for valid json data',function() {      
  const document = _.cloneDeep(require('user_profile.json'));
  const validSchema = schemaService.validateData('user_profile',document,true);

  expect(validSchema).to.be.equal(true);
  expect(typeof document.ts.createdAt).to.be.equal('object');
  expect(document.ts.createdAt).to.be.an.instanceOf(Date);
});

it('should return false for invalid json data',function() {      
  const document = _.cloneDeep(require('user_profile.json'));
  const validSchema = schemaService.validateData('user_profile',document,true);
  expect(validSchema).to.be.equal(false);
  expect(typeof document.ts.createdAt).to.be.equal('string');
});
```

**Comment by dilipkumar2k6** [comment]
One quick question, is it possible to change the data just before validation starts? For my use case, it might be possible that `ts.createdAt` can have `Date` object or string. Since my schema has `type` as string and `format` as date-time therefore value as `Date` object fails. Can I add any function which will do quick check and if type is `Date` then convert to string before `ajv` start validation?

Note: Don't want to modify original date object bcz I need to pass date as an object into mongodb database. Using `addKeyword` I took care of modifying data to convert date string to object after validation. Not sure how to change date object to string just before validation without modifying the data?

**Comment by epoberezkin** [comment]
Can be either a separate code or separate schema applied to the cloned data.

**Comment by alex-sherwin** [comment]
While the example from @dilipkumar2k6 works as-is, is always runs and modifies the data value as long as it is any string.

Meaning that some non-compliant ISO-8601 string in the `value` variable will be passed to `new Date(value)` constructor, which will be a `Date` instance, but will be an "Invalid Date" (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

I haven't found a way, as of yet, to have the custom `compile` function not run if the `date-time` format validation fails (in fact, based on the AJV docs I have no idea if `compile` runs after that check would be run anyways), meaning that the code written in the `compile` function should probably be more defensive so that it wont mutate the object under validation with an invalid `Date` object.

I settled on using `Date.parse()` to get back an epoch, which returns `NaN` if the passed string is non-compliant, which makes for an easy way to check validity before mutating the object under validation.

**Comment by epoberezkin** [comment]
> While the example from @dilipkumar2k6 works as-is, is always runs and modifies the data value as long as it is any string.

“compile” returns the function that will run during validation. You can either validate your keyword value using metaSchema in keyword definition (see the docs) or with the code in “compile” (and throw the exception of itnis invalid).
