### ISSUE TITLE
Typescript JTD examples fail with "is not assignable to type 'never'"

### ISSUE THREAD

**Issue by jkav77** [ajv-validator/ajv#1925]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Ajv v8.9.0 - this is the latest version
typescript v4.5.4

**Ajv options object**
Empty options object

Example code below from JTD reference page, found [here](https://ajv.js.org/json-type-definition.html#jtdschematype). I only modified the code to add import and initialization of the `ajv` object. This is the complete code I am trying to compile.
```javascript
import Ajv, { JTDSchemaType } from "ajv/dist/jtd";
const ajv = new Ajv();

interface MyType {
  num: number;
  optionalStr?: string;
  nullableEnum: "v1.0" | "v1.2" | null;
  values: Record<string, number>;
}

const schema: JTDSchemaType<MyType> = {
  properties: {
    num: { type: "float64" },
    nullableEnum: { enum: ["v1.0", "v1.2"], nullable: true },
    values: { values: { type: "int32" } },
  },
  optionalProperties: {
    optionalStr: { type: "string" },
  },
};
```

**JSON Schema**
No JSON formatted schema is used. The schema is a javascript object of type `JTDSchemaType` as shown in the javascript snippet above.

**Sample data**
Sample data is not relevant because the schema will not even compile.

**Your code**
The minimal javascript shown above is the complete code I am trying to troubleshoot. Again, this is the example from the JTD reference page. All I added was the import statement and initialization of `ajv`.

**Typescript compilation messages**

```
npx tsc src/test.ts

src/test.ts:13:12 - error TS2322: Type 'string' is not assignable to type 'never'.

13     num: { type: "float64" },
              ~~~~

src/test.ts:14:28 - error TS2322: Type 'string' is not assignable to type 'never'.

14     nullableEnum: { enum: ["v1.0", "v1.2"], nullable: true },
                              ~~~~~~

src/test.ts:14:36 - error TS2322: Type 'string' is not assignable to type 'never'.

14     nullableEnum: { enum: ["v1.0", "v1.2"], nullable: true },
                                      ~~~~~~

src/test.ts:14:45 - error TS2322: Type 'boolean' is not assignable to type 'never'.

14     nullableEnum: { enum: ["v1.0", "v1.2"], nullable: true },
                                               ~~~~~~~~

src/test.ts:15:25 - error TS2322: Type 'string' is not assignable to type 'never'.

15     values: { values: { type: "int32" } },
                           ~~~~

src/test.ts:18:20 - error TS2322: Type 'string' is not assignable to type 'never'.

18     optionalStr: { type: "string" },
                      ~~~~


Found 6 errors.
```

**What results did you expect?**
I expect the example code to compile without error.

**Are you going to resolve the issue?**
I am happy to submit a documentation PR. Maybe I just failed to understand something about the examples and I could clarify the documentation. I do not understand what's going wrong so I can't resolve this myself.

**Comment by epoberezkin** [comment]
I don’t think there is such example in the reference - could you please share the link?

On the schema itself - it might be unsupported case to have null in enum list… Possibly it would work if you make the property optional, without listing null in the list of values - please let me know if you try.

cc @erikbrinkman

**Comment by jkav77** [comment]
@epoberezkin @erikbrinkman 
I added a link to the example on the ajv site in my comment above. Also here for convenience: https://ajv.js.org/json-type-definition.html#jtdschematype.

I just copied the enum field with the schema from the example. Removing the enum removes the errors related to that field, but does not change the overall behavior that the typescript does not compile.

```
npx tsc src/test.ts                                                                             ✹ ✭PT-91 
src/test.ts:13:12 - error TS2322: Type 'string' is not assignable to type 'never'.

13     num: { type: "float64" },
              ~~~~

src/test.ts:14:25 - error TS2322: Type 'string' is not assignable to type 'never'.

14     values: { values: { type: "int32" } },
                           ~~~~

src/test.ts:17:20 - error TS2322: Type 'string' is not assignable to type 'never'.

17     optionalStr: { type: "string" },
                      ~~~~


Found 3 errors.
```

**Comment by erikbrinkman** [comment]
what version of typescript are you using, and do you have strict null checks set to false? It works fine in [this playground](https://www.typescriptlang.org/play?#code/PQKhAIDsFcFsFMBOBLAxuAzgFxZA5huCMAFBYCeADvOAHJwBGSAKlTQLzgBEAZgDYB7AIZYAzACYu4AD7d+wrADYALFNldkkLAA413aJp16NWgIyLjBsxZndDEy-ckkSoCNlx5MOTQSKkKanAAZR98ViDOLg9fYyxkBGwhWEouFzdwAHF4SCQ0cAApZgARENQAC3hYIXAAd2QscoFoLHBNHiQc1BoBHnBGmkR4SiGMHKx4ABN+tn8SeAAPSgFEVsCaYIEEIuLgiqqhCI5wAAoScFtgYHAhnnPwAG8b+B4ALm9PcABfe6vwEYSDWQADd4Bh7rInut3vRYExEEdbKFPIj1AwBAI+PAhJApD8Ln8cnAIY9wETYO8YvgANoAXW+v2u8CxCC04IukLJLPGGHem22JT2lWqiPx4D+wKEfGgYJJT0l0rBfK28B2QoOosZ-0QAmoq2Qso5j3uFxGuqQ8SV4AASvBUCtJgAeKl4AA0IRVav2IrYAD4TeBdfEBJApQAFHV6y0YAD871t9sQTpd7v5qsF3sOfoDQkmkyBIfDkYtBtj73RmOxkHuYshAbNUdLcZtdodzrCbo9At2maO-ouFyDyELfAj5v1VoTbZTXfTPeFWeo-YHufzwdDo+LE7L4ArWJxNa1+YwqBQsE0IhWcvAx9PgNDWBWlI7AG5wNVKJRfPHW0n255U09DMFz7BkCSZFIKC1WgAHlmAAUUweAaAGMlIGmXotXKLAsEoXkrjwBpymgBgADp7VgYB1hPFBKCwABaME+EMKi2Bo5A6MYjBmK0YBkAwDAZQwYBxAABkUUQAGJ+ME1tYFZBjFAAdgAVlMFSVAATnELUmMMejjyEBgsXo3IFgYniaAAAWou9OL03iGBxejqLlH4AEpwAAMmNC4YD4PgjKxZs9yre4ECwXMRCEZspz-GdoEgABrSABFqSBl0mF5NALSAdzi5MO0A7t1R9JcSB+VwwGeABHAwhmmJL4HIQhenAHFAwYAArO0sHdVLWkSrKeE0KY5nWFs6uQBqAGlmowR1mF9cBOAee5qRmtpIHAJryDa5haXo5shuy3JpkWCZ0MIZgNvpGMoHgUFEHAd4Zoq6ldv22l0mqocR0DZ6huQEazvooKaF21q+g6gRut68bZhgujhw3OaWsW5bVvWzbNB25qvqO94TpBsaLpySZrtu8B7s295cie97Pr6A6fogCb+P6RAZTaZm2kIGpEpRmYgmIMhZgASQwABVSAUYAfUW90pbJczyeulbwCWjWeClMYVcuinTnuZh9bV8BEpStLtvuk5qSl+kyau8BqQO6nwB1vg9feHAZU8unHqQEh3Pue6PbGe5va5+AxaCSWZZRjGNbj2WQwVpbWeFmgOZ9rPeY55Asq0NApT4chwEQ0WJqOeC6qlBpyEV8vMed13HcN6l4Lu04O4d1WnZdruc5e93dfgP2R896OqrZ2Zs6jnnNYBqBoACvm2kL+JUBLsvEJWZeAsr2Z6AC6va+YihG-g5vT+gOuL5N2R-L4d1EMfle+H9afwDweAsFayBS79EqB8Xw4Bz5IF1oGaGmcl5PwXjUdmGBIAAHJWg1BdGAhoEC+AIyCPBGAsBkS+ETpwAept+70yQN9C490n4R0Xm3QgLoQ4gPwOQw2zAWF0IuO8ThPD958AzkPYGMCOYCxTttNqGDwGIEgYfWOGB8FwBIQI9hhAlGEI7I6eCCxUDSiyo3J+vplqh1HsPHOQj54hkASIkumd+ZDHaogWRZdqKnAGv0aAlAsQYE8qLP4sEELPGYmCQM21UI61QGscoIhPHeNCZMEMqDwAxNBO1bamgsoLHaq0USpEVLugYC0JxLjwR-FSTQDqmTFg5LJE9MuBD4QxxoJLeC3I2QqLDjQRh4Bk4J3TjQluvcDaEGpEMXM1iy4W1SulOk1C3bE1GudPuHDqR5JUvM0xk96EWP4V0+h+yv7CL6KhU5s9+bgAVEJGB8iWkYAAGpSiEp0sxPS+khm0bo-R8BDHv2MSwm+d8G5M3Ll86ABjmD9T+e6F0y53iHIyMc0RFyzTDG3DAnE0x44hjXl090e9EHtRvPxO854HwEtmJi8A2KMmECHrc3pGACqNxpWo3cGJ9wZQ1qyt50sJGfL0eCn5kKBH-MGXAnpGiiH4EdCCnRgqIVQoCmKt2+z+G7OHgi6qQgom3xwSeBccxFjLFWDAr0IE2CN1KD05lCVkozK5ZwW1RUHpPWMRrM4Ro-i3EIPROolRHFwNqEIJBySMDUFQMDA0kx3SwGgNgd8IgKgqx1VgUu9wTgSpWeogh0q8Cyvxn0Yoy5xUB0QAGV4AZZAnCeBtLaeM9pFtpO8MhPTqTFFul3J4txXrfGHpQ56XwPqFvAMUekPknhP3Bs2Lp3xg4DnFNcJ+Y0fXgD9SI24a8p3GUqehAR4M17hrtFGqY7oBgZNaFvasC6-jVCwMm+AREkCqL3qlSApl343lOrldkA5q1ZpGZrAMgy1oLoXXW3GIKx0tvld835yrhlmw7mCgxHaZq0iVR-eZYG3bdpeL2sUOH-YMxw0OqD47STbqxJHbmhGBzEaQO5edi6ySQTLn6qodEy4GoOPzT2AhObYlaFRmg+YeAdCGFoGx4SYmtAaMgwgMz3bvzLsgPAqUGokhONMq2bKTb3Une-ad5YOVVj7QxxAzG-h2IEAMZ6rkjQnBOH8RpSBfVhMATq7odE6XAImq58tC6h49OPnwQF58G4ioCyW3DmcYSMBYLMOj7w-ihRxO5rzww-5AJQrMNL16BzBezXQd+4X66N3yzFgzcXuD5bxBWljLp3OTPaqgbz2WzlBGYUF+eIXStsBrnq8rIrYUBmq9CEIHZNQLpS9cJra6PNl0yz5nLMDigiGjj17mfWT4DbPsN9062JhVdJBNrg8REiRRSPVmbLHyTNYAUttrWXCCCxxVIjsmCJiyM9gGP4zAYLFBgnUGgV7kmpr1YA-YqAkpANiWW8gjRQG41Qm97awamERpPZMAMRXAOtIIRjMbpJyTvClVo2DQr4Mf19HSMC9GWNCGcUIFqC2WvLey0z0p7p7Qr2mEwEpLOoHmwkXSgTAvRiYlBNMQK33ce9eK609pf8BVwai38k7JsenjMSY9047Rn3wXcnSYnoGwPMiqDyd45qNSWvgodmLyXXWB1uxKJ5hpCsK-xw893C0BkDnulr4rzqAJbQk+Ae5J2zcLquVaG3ZUfn3IdwGJ3A6Gt-AbCWD3Fw8dm0lsykVXSTu21tFNWa81VdU-V8q30iGKFluwwH3yOHtTjmjLFX8hVQ8DpixcOj-Do9gcz9ud4tacbbVL-VKYaM-e1+t8BW31BFq3Qd-ThdXxPJeQDLbJG64pQz8r4q0Vte2XUgHY3kDwGBx-Q3GORsYIO+Ji774fqZbe9r4Z4PhdN+ixt9LKPq-cDcfcAXfFGffCvJaZtQoBfBPQ-YVFfEXYaJZX0ZPFvD-PvTfZvHDVcXKX-e-HcfLK-J3P4W8M8C8R8QLT3bbRXJlTvRuHOKPK-CDbaOVFDYVTDWvQmUFBVdg0VKmHpbrMDAzQA4ldiMlS8RAV6EQj8L8fAAAtA8CTWQHYHVAaAZxcYTzAKNKQgLKMQ8gglcXGgEYMEcYetHjaoEQi4akAAWXrUpyPyMU7Xn3nEXx+UsIHBgnPCwEWjZVrQAGF610N3hbCvg3YTYLN3QZoUD3CLhih3D38+8iCr8LMU9h1G1uC1cODG8LNN9t8AMzY+EhCsCwMRMaNNswN+9h5DMApjMJ49YN9g5MCzdCRzJZFW98Dwpf4opIpH9pwXUdN0plx-tlCcs9YMAmg+dFtdxKktDagxpYlTldQwEA5BELgkDZZ1wdwx961yNnDSpFwfk0MMNR1lofhKoJodgjshBigXhHRghDs2UQ8X8RdLZBjMYtNvUXgAxghfDng3hWEvA6N7prVittjcZghqQuBbguBaQoCDdnp7kP97pLjoobieBHQk8TiGs09Xdrh1hvjfiJtYR4Rpsm8AsGsfiekoQ2B3guA6skT2VKwDxbtKTQSatogOwbsm9BD+FWTANqTqBaSLswQrtUgGSMFZAjtyj+FCQCECSqS0I4B3gdcWsTh4Ty5jd6QgSAS2V4JiccSGce5T8XRG97o9TbsDSZSmRldf0Lg+SzYngLcFJeQw9DcGSUTIo0TtEHcTdcT2is9bSQhfCr9h9owfwn9-xniBiMor8f9Nw-8H9wy+jQ9oz38cC994z8CQpTNmSBxtSnh6IVS9dmCG02oISuBQzSwYTDpmwPTrjbjyzKywQYSEDi0+0J0r9CzsRddAESyQVyy4y78AzqyABqWskoK4r0kQgc5GEcIc7cFs9DV0EQuInDR3bybucs9MsAzM4c2E0-HOLuJ4-Ad0VM4eaM5jXk4MnDJs-KOgu1V4mMnDQcrcMMlsCMh8h1NMvMXA3c7cbMpkgrRIhdarLsiZYs4A-syE286srgusr0xs18qs2kVs04jcr-NdIs3syCkdGcjM+c6MUc8c4oSc246cyEl8hMjARcjDFcq-dcnyW2Lcn8-CpC5s-cttQ8t2Y8zsM8ome1K2S84eN3RUQM+0p2eUX3d4dUxE7Uni90eC24zE4tGLWbUQ0lfQygu0340g+8CQ6SyAcPawt8GQ78d85MqMgSwYhkmwuvduE003JgnC9I8s0y-Aas5w0i9E1yoQT8WIFCpck49C52GaWw3GawqAzaOjMjXCyEtyvAas7EstdPCCLjAMC8rTcSw2aowKHdMovtWhT9HIlwY1FYNYWYOso4O45uLKwgJ4dYn9JM+KfoqyrlMUZEic1Ehs1MSEhqzYmEuFaAkirq7y90eS53RAf5FwQwJASJGgaw8gREM3AhOmBLSguM5EZsQQkTDRWk4EUwUiUSYwfa0iSQWwbhS5KS8y5q7vNa-0Sqe0PKVocwoQPY3sS1Ba0CLGU0Nil0wfFax4M7eQEQFQLgL4ZchdHagGh4UnZ2LgE6o690eGg6yQY40ozmGUcGgMWPP6nG0fM7JwMGrGvvCGwMWc2-X6+Q6-cmqUZEfGmk7gF0MG0mrGn4IAA).

**Comment by jkav77** [comment]
Setting `strictNullChecks` to `true` in my tsconfig.json compiler options fixed the issue. 

The documentation already says to enable this, which I failed to do. I recommend the [Using with Typescript](https://ajv.js.org/guide/typescript.html) guide emphasize and explain this a little more for other developers like me who are not as experienced with typescript. 

I am happy to help with that. Would you be interested in a PR for the documentation?

**Comment by erikbrinkman** [comment]
I can't say what @epoberezkin will accept, but I think clarity improvements are always welcome. Alternatively we could just use the same wrapper we do for JSONSchema which returns the closest thing currently to an error in typescript:

https://github.com/ajv-validator/ajv/blob/95b15b683dfb60f63c5129b0426629b968d53af8/lib/types/json-schema.ts#L2-L4

**Comment by epoberezkin** [comment]
@erikbrinkman thank you!
