### ISSUE TITLE
{ not : {required[] } } Behaving Incorrectly

### ISSUE THREAD

**Issue by otobot1** [ajv-validator/ajv#1927]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.10.0

**Ajv options object**
```javascript
{
    allowUnionTypes: true,
    schemas: { mapPostSchema },
    logger: {
        log: console.log.bind(console),
        warn: function warn() {
            console.warn.apply(console);
        },
        error: function error() {
            console.error.apply(console);
        },
    }
}
```

**JSON Schema**
```javascript
{
    type: "object",
    properties: {
        A: {
            type: "integer",
            minimum: 1,
        },
        B: {},
        C: {},
        D: {},
    },
    allOf: [
        {
            if: {
                properties: {
                    A: {
                        type: "integer",
                        minimum: 1,
                    },
                },
                required: ["A"],
            },
            then: {
                allOf: [
                    { not: { required: ["C"] } },
                    { not: { required: ["D"] } },
                ],
            },
        },
    ],
    additionalProperties: false,
}
```

**Sample data**

```json
{
    "chapter": 2
}
```

**Your code**
```javascript
const validateMapPatch = ajv.compile(mapPatchSchema);
const valid = validateMapPatch(data)
```

**Validation result, data AFTER validation, error messages**
```
valid = false

Error:
  {
    instancePath: '',
    schemaPath: '#/allOf/0/then/allOf/1/not',
    keyword: 'not',
    params: {},
    message: 'must NOT be valid'
  }
```

**What results did you expect?**
I expected valid to equal true. I also tried using param: false instead of not: { required: ["param"]} but both give errors. Both methods were valid json schema according to https://www.jsonschemavalidator.net/s/jNIPMtGg , so the issue must be with AJV. I may have configured things incorrectly, but after a day of reading the documentation I decided to post this.

**Comment by otobot1** [comment]
Not sure why the whole schema is highlighted in red... If someone lets me know how, I will fix it

**Comment by epoberezkin** [comment]
> Not sure why the whole schema is highlighted in red... If someone lets me know how, I will fix it

because it was not a valid json, it was javascript - I amended

The example is too large to understand what is going on there - could you please reduce to the smallest example that demonstrates the issue? It is usually possible to fit in 10-15 lines schema at most.

Also please submit the executable code, ideally via runkit.com, the problem might be not in the schema/data, but in your code.

**Comment by otobot1** [comment]
I trimmed the schema down. Basically, there are 4 relevant parameters. If A or B are there, C and D must NOT be there. And if C or D are there, A and B must not be there. I have an if-then inside of the allOf for each of the 4 parameters. The relevant js code is here: http://runkit.com/otobot1/ajv-error . I've trimmed it as well so that the irrelevant properties aren't cluttering it.

**Comment by epoberezkin** [comment]
sorry, I can't run the code in runkit - it doesn't seem to be a valid JS...

**Comment by epoberezkin** [comment]
this is the working example with your schema: https://runkit.com/esp/622e4cbb9d7bdc0008d65f51

I had to remove additionalProperties: false for it to pass, but it doesn't show the error you have.

**Comment by epoberezkin** [comment]
I am pretty certain that the issue is unrelated to `not: required` - there are tests for that - it's elsewhere in your code.

**Comment by otobot1** [comment]
Alright. I'll take another look through my code and see if I can find anything.

**Comment by otobot1** [comment]
Ah. Yep. Sometimes that variable is passed in as null or undefined. Is there a succinct way to allow for that? I don't mind if those parameters are there as long as they're undefined or null.

**Comment by epoberezkin** [comment]
This is related to #937 - how undefined should be handled.

in general, all keywords that test for property existence rather than the value consider undefined properties present…

to allow null you can use type: null or nullable: true in the property schema.

I don’t remember off top of my head whether that would also allow undefined - I suspect it won’t in itself but when validating property value it is most likely ignoring undefined properties, so {properties: {a: {type: “null”}}} should work and allow only null and undefined for a

**Comment by epoberezkin** [comment]
… and also it being absent

**Comment by epoberezkin** [comment]
not: required: [a] is stricter as you see :)
