### ISSUE TITLE
Issue with AJV on Docker

### ISSUE THREAD

**Issue by petaluma007** [ajv-validator/ajv#1937]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.5.2

**Ajv options object**

```javascript

```

**JSON Schema**

```json

```

**Sample data**

```json

```

**Your code**

```javascript

'use strict';

var compileSchema = require('./compile')
  , resolve = require('./compile/resolve')
  , Cache = require('./cache')
  , SchemaObject = require('./compile/schema_obj')
  , stableStringify = require('fast-json-stable-stringify')
  , formats = require('./compile/formats')
  , rules = require('./compile/rules')
  , **$dataMetaSchema = require('./$data')**
  , patternGroups = require('./patternGroups')
  , util = require('./compile/util')
  , co = require('co');
```

**Validation result, data AFTER validation, error messages**

```
Cannot find module './$data'
```

**What results did you expect?**
After further investigation it appears during AJV installation it failed to create $data.js on Docker. We believe somewhere in the AJV code the $ character must be escaped when creating $data.js.

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
The current version is 8, please upgrade.

**Comment by epoberezkin** [comment]
I believe v6 has it resolved too if you cannot upgrade to v8 for some reason

**Comment by petaluma007** [comment]
Thank you. Confirm using AJV version 6.12.5 solved the issue.
