### ISSUE TITLE
Display additionalProperty in error.message

### ISSUE THREAD

**Issue by BCsabaEngine** [ajv-validator/ajv#1943]
**What version of Ajv you are you using?**
8.11.0

**What problem do you want to solve?**
Display informative error message with instancePath+message

**What do you think is the correct solution to problem?**
(Almost) Every error can be displayed with instancePath and message. But from additionalProperty error message missing the affected property. I can read it only from params. I would like to inform the user about additional property not only the error category. Like when required property missing or value must be greater then...

**Will you be able to implement it?**
I think yes, need implement here: https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/applicator/additionalProperties.ts#L21 similar to https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/validation/required.ts#L20 . And of course I need to looking for 2 other usage of string "must NOT have additional properties".

Should I make a PR?

**Comment by BCsabaEngine** [comment]
```
  {
    instancePath: '/valami',
    schemaPath: '#/properties/valami/required',
    keyword: 'required',
    params: { missingProperty: 'b' },
    message: "must have required property 'b'"
  }
```
vs.
```
  {
    instancePath: '/valami',
    schemaPath: '#/properties/valami/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'd' },
    message: 'must NOT have additional properties'
  }
```

**Comment by BCsabaEngine** [comment]
I have found two more place where too simple message displays: propertyNames.ts and enum.ts.

**Comment by epoberezkin** [comment]
Sorry, it’s a conscious design choice not to include property names in error messages, it’s covered here: https://ajv.js.org/faq.html#why-don-t-additionalproperties-false-errors-display-the-property-name

**Comment by epoberezkin** [comment]
(That is, property names that are not present in the schemas)

**Comment by BCsabaEngine** [comment]
I understand the reason (vulnerability). Thank you for your work!
