### ISSUE TITLE
unevaluatedProperties does not consider nested property as evaluated

### ISSUE THREAD

**Issue by marcospassos** [ajv-validator/ajv#1944]
Based on my understanding of the `unevaluatedProperties` keyword, this validation should pass without errors. 

Am I missing something? If so, is there a workaround?

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.11.10

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "attributes": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["a", "b"]
        }
      }
    }
  },
  "allOf": [
    {
      "type": "object",
      "properties": {
        "attributes": {
          "type": "object",
          "properties": {
            "foo": {
              "type": "string"
            }
          },
          "unevaluatedProperties": false
        }
      },
      "additionalProperties": false
    } 
  ]
}
```

**Sample data**

```json
{
  "attributes": {
    "type": "a",
  }
} 
```

**Your code**

```ts
const ajv = new Ajv();
const validate = ajv.compile({
    type: 'object',
    properties: {
        attributes: {
            type: 'object',
            properties: {
                type: {
                    enum: ['a', 'b'],
                },
            },
        },
    },
    allOf: [
        {
            type: 'object',
            properties: {
                attributes: {
                    type: 'object',
                    properties: {
                        foo: {
                            type: 'string',
                        },
                    },
                    unevaluatedProperties: false,
                },
            },
            additionalProperties: false,
        },
    ],
});

validate({
    attributes: {
        type: 'a',
    },
});

expect(validate.errors).toBeNull();
```

**Validation result, data AFTER validation, error messages**

```ts
[{
    instancePath: '/attributes',
    keyword: 'unevaluatedProperties',
    message: 'must NOT have unevaluated properties',
    params: {unevaluatedProperty: 'type'},
    schemaPath: '#/allOf/0/properties/attributes/unevaluatedProperties',
}];
```

**What results did you expect?**
No errors.

**Are you going to resolve the issue?**
Maybe.

**Comment by epoberezkin** [comment]
I believe this is how it’s supposed to work - unevaluatedProperties would account for the properties evaluated in the same schema (in sibling keywords) or in the children of siblings keywords, but not not in parents / siblings of parents.

For it to work as you expect (that is, account for “a” as evaluated) you need to move unevaluatedProperties to the top level of the schema

**Comment by epoberezkin** [comment]
https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/unevaluatedProperties.json

See this “official” test where it “can’t see inside cousins”
