### ISSUE TITLE
JTD values form accepts any value

### ISSUE THREAD

**Issue by VirtuaBoza** [ajv-validator/ajv#1949]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.11.0 (latest at time of writing)

**Ajv options object**

```javascript
undefined
```

**JSON Type Definition**

```json
{
  values: {}
}
```

**Sample data**

```json
undefined
```

**Your code**

```typescript
import Ajv from "ajv/dist/jtd";

const ajv = new Ajv();
console.log(ajv.validate({ values: {} }, undefined)); // true, expected false
console.log(ajv.validate({ values: {} }, null)); // true, expected false
console.log(ajv.validate({ values: {} }, 1)); // true, expected false
console.log(ajv.validate({ values: {} }, "foo")); // true, expected false
```

**Validation result, data AFTER validation, error messages**

```
true
```

**What results did you expect?**

I expected `false`. Unless I misunderstand the documentation, `{ values: {} }` is equivalent to `Record<string, any>`, but it appears to be treated as `any`.

**Are you going to resolve the issue?**

First I'm interested to know if I'm mistaken. I haven't taken a look at the source code to know if I might be able to resolve it myself.

My workaround for the moment is to replace `{ values: {} }` with `{ optionalProperties: { foo: {} }, additionalProperties: true }`.

**Comment by epoberezkin** [comment]
This is indeed a bug - it happens with an empty "values" form.

As a workaround, you should be using "properties" form without properties.
