### ISSUE TITLE
unevaluatedProperties: false doesn't work for array type sub-schema 

### ISSUE THREAD

**Issue by aleung** [ajv-validator/ajv#1963]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.11.0

**Ajv options object**

default options

**JSON Schema**

```json
{
  "type":"object",
  "unevaluatedProperties":false,
  "properties":{
    "list":{
      "type":"array",
      "items":{
        "type":"object",
        "properties":{
          "id":{
            "type":"string"
          }
        }
      }
    }
  }
}
```

**Sample data**

```json
{
  "list":[
    {
      "foo":1,
      "id":"abc"
    }
  ]
}
```

**Your code**

https://runkit.com/aleung/6260f73f3308ec0009307718

**Validation result, data AFTER validation, error messages**

Validation pass

**What results did you expect?**

`list[0].foo` is  unevaluated

**Are you going to resolve the issue?**

Maybe

**Comment by epoberezkin** [comment]
I believe this is how it is specified in JSON Schema - it only applies to properties on the current instance level (so it won't apply to sub-objects as well).

**Comment by epoberezkin** [comment]
The use case for unevaluatedProperties is to apply it to properties from the same instance level that might have been validated on different schema levels (unlike additionalProperties is defined), but you have to use it for each data instance level separately.

**Comment by aleung** [comment]
@epoberezkin 

> The use case for unevaluatedProperties is to apply it to properties from the same instance level that might have been validated on different schema levels (unlike additionalProperties is defined), but you have to use it for each data instance level separately.

Interesting, it sounds oppose to your [comment](https://github.com/ajv-validator/ajv/issues/1350#issuecomment-744656165) in #1350:

> The idea of this keyword is that you would only use it in your top level schema that you actually use to validate data, while any components used by it won't have unevaluatedProperties.

From your comment in #1350 and #1944 I understand that `unevaluatedProperties` doesn't apply to parent level but should apply to the same schema (in sibling keywords) or in the children of siblings keywords.

**Comment by epoberezkin** [comment]
> The idea of this keyword is that you would only use it in your top level schema that you actually use to validate data, while any components used by it won't have unevaluatedProperties.

The comment related to the fact that you won't need to use it in subschemas of anyOf/oneOf/if etc., but it still applies only to one instance level - that issue was specifically about allOf.

That issue references the spec in question - please read it, I believe ajv implements it as specified (possibly, with some minor limitations)

> From your comment in https://github.com/ajv-validator/ajv/issues/1350 and https://github.com/ajv-validator/ajv/issues/1944 I understand that unevaluatedProperties doesn't apply to parent level but should apply to the same schema (in sibling keywords) or in the children of siblings keywords.

That is all correct with regards to different schema levels/branches, as long as they all apply to the same instance level - that was implied.

**Comment by maingi4** [comment]
I have the same issue, my requirement is simple: `nowhere should the user be able to pass a value other than what is defined in a schema`, this is mostly to enforce developers to keep updating the schema and not just accept a new property in the code without updating the same.

Is there any way I can make that happen?

I tried automatically assigning `unevaluatedProperties` to every schema, however, that breaks in many instances of "oneOfs" and "allOfs" where the schema where the above is set is part of another schema as one of the "oneOfs/allOfs". I am stuck currently on how to achieve the first statement.

**Comment by juneidy** [comment]
> `nowhere should the user be able to pass a value other than what is defined in a schema`

On the same boat here, I was quite surprised that achieving it is not as easy as I initially thought.
