### ISSUE TITLE
Support HTTPS schema

### ISSUE THREAD

**Issue by xinbenlv** [ajv-validator/ajv#1966]
See:
[AJV: no schema with key or ref "https://json-schema.org/draft-07/schema"](https://stackoverflow.com/questions/69133771/ajv-no-schema-with-key-or-ref-https-json-schema-org-draft-07-schema)

It seems that currently AJV doesn't support HTTPS, is it possible support it? Otherwise there can be security concern.

@shohoku11wrj also brought up this issue.

**Comment by byF** [comment]
If you look inside the meta schema, you'll see its `id` is `http://json-schema.org/draft-07/schema#`, which is actually URI in this context, not URL.

The meta schema itself is packaged within `ajv`, so there is no remote retrieval happening, but you need to use the correct id above.

**Comment by epoberezkin** [comment]
@byF thank you - correct, ajv doesn't IO with this URI - this is just an identifier defined in the specification, that happens to look like URI.

Ajv does have a schema compilation method compileAsync that could treat schema IDs as resource locations, but you have to provide a function that performs IO (so you can map from http to https in this function, if, for example, you need to load schemas with http IDs). In any case draft7 meta-schema is indeed bundled.
