### ISSUE TITLE
only iterate over own properties

### ISSUE THREAD

**Issue by mbroadst** [ajv-validator/ajv#197]
Please excuse me if I'm missing some crucial option, but it seems like the generated code for the validator iterates over enumerable types (`for (var d in data) { ... }`) whereas I would like to restrict that to only own types (the same as `Object.keys`). Is it possible to tweak the generated validator to accommodate this?

**Comment by epoberezkin** [comment]
@mbroadst it is still validating prototype properties against schemas in properties keyword (additionalProperties and patternProperties are resolved with #198, but it doesn't cover properties themselves).

That's the failing test: https://runkit.com/esp/585d958bc5386f00131c3093

**Comment by epoberezkin** [comment]
@mbroadst the option is also not used in "required" keyword validation

**Comment by epoberezkin** [comment]
TODO:
- [x] "properties"
- [x] "required" with "properties"
- [x] "required" for few properties
- [x] "required" for many properties
- [x] "required" with $data
- [x] "dependencies" with property list
- [x] "dependencies" with schema
