### ISSUE TITLE
Validate failed: oneOf

### ISSUE THREAD

**Issue by stpnov** [ajv-validator/ajv#1985]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.11.0
**Ajv options object**

```javascript
{
    useDefaults: true,
    coerceTypes: 'array',
    allErrors: true,
    removeAdditional: true,
}
```

**JSON Schema**

```json
{
  "oneOf": [
    { "type": "null" }, 
    { "type": "integer" }  
  ]
}
```

**Sample data**

```json
null
```

**Your code**

```javascript
            const ajv = new Ajv({
                useDefaults: true,
                coerceTypes: 'array',
                allErrors: true,
                removeAdditional: true,
            })
            const validate = ajv.compile({
                oneOf: [{ type: 'null' }, { type: 'integer' }],
            })
            validate(null) // false
```

**Validation result, data AFTER validation, error messages**

```javascript
//valid: false
[
  {
    instancePath: '',
    schemaPath: '#/oneOf',
    keyword: 'oneOf',
    params: { passingSchemas: [Array] },
    message: 'must match exactly one schema in oneOf'
  }
]

```

**What results did you expect?**
The result should pass, if you remove the coerceTypes flag, then everything works fine
**Are you going to resolve the issue?**
Not Sure

**Comment by epoberezkin** [comment]
This is not a bug, this is how coerceTypes option works - as you wrote, removing it fixed the problem.

As a result of coercion your data matches both schemas, that’s why it fails validation.

In this case you should use type: [“null”, “integer”] instead of oneOf, while they are equivalent without type coercion, with coercion they are not (and in any case the former is much more efficient).

**Comment by stpnov** [comment]
@epoberezkin 
I missed that null can be cast to 0,
Thank you for your reply and your time

**Comment by epoberezkin** [comment]
you're welcome!

**Comment by SpinGit** [comment]
What happens when a value has a complex type as well?

```
value: {
  type: ["string", "boolean", "number"],
  nullable: true
}
```

`value` should allow `string[]` as well. 

How to resolve it in a valid schema?
