### ISSUE TITLE
anyOf returns repeated errors

### ISSUE THREAD

**Issue by felixjb** [ajv-validator/ajv#1987]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

```json
"ajv": "^8.11.0",
"ajv-formats": "^2.1.1",
```

**Ajv options object**

I am using Ajv with `allErrors` option, a few keywords and formats as well

```javascript
const ajv = new Ajv({allErrors: true})
const formats: FormatName[] = ['date']
this.validator = addFormats(ajv, formats).addKeyword('kind').addKeyword('modifier')
```

**JSON Schema**

My schema is being generated through another package called [typebox](https://github.com/sinclairzx81/typebox/). This is what the schema looks like when it's passed to Ajv for the validation.

```javascript
{
  kind: Symbol(ObjectKind),
  type: 'object',
  properties: {
    enumProperty: {
      kind: Symbol(EnumKind),
      anyOf: [Array],
      modifier: Symbol(OptionalModifier)
    }
  }
}
```

**Sample data**

```json
{
  "enumProperty": "invalid-value"
}
```

**Your code**

Not relevant at this point, I think.

**Validation result, data AFTER validation, error messages**

```
"data/enumProperty must be equal to constant, data/enumProperty must be equal to constant, data/enumProperty must be equal to constant, data/enumProperty must be equal to constant, data/enumProperty must be equal to constant, data/enumProperty must be equal to constant, data/enumProperty must match a schema in anyOf"
```

**What results did you expect?**

I would like to have a simple message indicating that the value is not valid for the schema and the acceptable values for that property:

```
"data/enumProperty must match a schema in anyOf: ["value1", "value2"]"
```

If that's not possible, than just the first part would suffice:

```
"data/enumProperty must match a schema in anyOf"
```

**Are you going to resolve the issue?**

Unlikely

**Comment by epoberezkin** [comment]
All errors are reported because of allErrors option you use.

**Comment by felixjb** [comment]
I understand the use of the `allErrors`options, but I don't think the string `data/enumProperty must be equal to constant` should repeat for each entry in the enum.

**Comment by epoberezkin** [comment]
Possibly… It’s ok to improve in v9, it’s about time to catch it up with v8 and release.

I would rather not change how errors are reported within a single major version.

**Comment by epoberezkin** [comment]
But I don’t understand - if it is enum then why it uses anyOf schema, and not enum keyword?

If typebox generates schemas with anyOf for normal enum values it’s something that should be improved in typebox, not in ajv…

**Comment by felixjb** [comment]
@epoberezkin that's a great point! I hadn't of it. 

@sinclairzx81 is it possible to make `Type.enum()` use the `enum` keyword instead of `anyOf` ?

**Comment by sinclairzx81** [comment]
@felixjb Refer to comment https://github.com/sinclairzx81/typebox/issues/174#issuecomment-1134944761 for reasoning behind TypeBox's preference for `anyOf` over `enum`.

**Comment by felixjb** [comment]
Thank you so much!
