### ISSUE TITLE
Cannot get schema whose $id starts with #

### ISSUE THREAD

**Issue by ivan-tymoshenko** [ajv-validator/ajv#1998]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.11.0

**Ajv options object**

I'm using the default options.

**JSON Schema**

```json
{
  "type": "object",
  "definitions": {
    "def1": {
      "$id": "#number-property",
      "type": "number"
    },
    "def2": {
      "$id": "number-property",
      "type": "number"
    }
  },
  "properties": {
    "property1": {
      "$ref": "number-property"
    }
  }
}
```

**Your code**

```javascript
'use strict';

const assert = require('assert')
const Ajv = require('ajv')

const schema = {
  type: 'object',
  definitions: {
    def1: { $id: 'number-property', type: 'number' },
    def2: { $id: '#number-property', type: 'number' }
  },
  properties: {
    property1: { $ref: 'number-property' },
    property2: { $ref: '#number-property' }
  }
}

const ajv = new Ajv()

ajv.addSchema(schema)

assert.ok(ajv.getSchema('number-property'))
assert.ok(ajv.getSchema('#number-property')) // fails, returns undefined
```

**What results did you expect?**

To get the schema by `#number-property` reference

**Comment by epoberezkin** [comment]
This is not a bug.

IDs that start with hash are local anchors in draft-07 (which is the default JSON Schema spec when you import from "ajv"), the later spec versions (that you can use with other imports) removed it and replaced with $anchor.

So you cannot find them in the global namespace of all Ajv schemas with getSchema.

You can retrieve these subschemas if you add $id to the root of your schema, e.g. `$id: "mySschema"` or `$id: "https://example.com/mySchema"` (the latter is closer to the spec, root schema $id should be an absolute URI), then you would be able to reference subschemas with anchors as "mySschema#number-property" (or "https://example.com/mySchema#number-property")
