### ISSUE TITLE
Comma in serialization result

### ISSUE THREAD

**Issue by piliugin-anton** [ajv-validator/ajv#2001]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Version: 8.11.0**, **JTD**

**Ajv options object**

```javascript
{
  coerceTypes: 'array',
  useDefaults: true,
  removeAdditional: true,
  uriResolver: fastUri,
  allErrors: false
}
```

**JSON Schema**

```json
{
  "optionalProperties": {
    "test": {
      "type": "boolean"
    },
    "error": {
      "type": "string"
    }
  },
  "additionalProperties": false
}
```

**Sample data**

```json
{ "error": "Something went wrong" }
```

**Your code**

```javascript
const AjvJTD = require('ajv/dist/jtd')

const ajv = new AjvJTD({
  coerceTypes: 'array',
  useDefaults: true,
  removeAdditional: true,
  uriResolver: fastUri,
  allErrors: false
})
const serialize = ajv.compileSerializer(schema)
const result = serialize(object)
```

**Serialized data (NOTICE COMMA)** 
```
{,"error":"Something went wrong"}
```

**What results did you expect?**

````{"error":"Something went wrong"}````

**Are you going to resolve the issue?**
Yes, look at #2028

**Comment by piliugin-anton** [comment]
I'm trying to achieve the result when serialized object could have some data on success or error

**Comment by craggy2593** [comment]
Also experiencing the same issue. With a schema of only optional properties, when the first optional property in the schema is missing from the object, the serialized output has a comma at the start, causing JSON validation issues downstream.

**Comment by epoberezkin** [comment]
That does look like a bug - the fix should be simple - PR is welcome, otherwise I’ll fix some time next month.

**Comment by piliugin-anton** [comment]
@epoberezkin  Please have a look at https://github.com/ajv-validator/ajv/pull/2028
