### ISSUE TITLE
how to reduce validation errors to chosen path of `anyOf`

### ISSUE THREAD

**Issue by mbroadst** [ajv-validator/ajv#201]
relevant code example:

```
let PointSchema = {
  id: 'point',
  anyOf: [
    {
      type: 'object',
      properties: {
        latitude: { type: 'number' },
        longitude: { type: 'number' }
      },
      required: [ 'latitude', 'longitude' ]
    },
    {
      type: 'array',
      description: 'GeoJSON format',
      items: [ { type: 'number' }, { type: 'number' } ],
      additionalItems: false,
      minItems: 2
    }
  ]
};

const Ajv = require('ajv');
let ajv = Ajv();
ajv.addSchema(PointSchema, 'point');
let validate = ajv.compile(PersonSchema);
let valid = validate({
  name: 'BadBob',
  location: [ 200 ]
});

console.log(validate.errors);
```

results in:

```
[ { keyword: 'type',
    dataPath: '.location',
    schemaPath: 'point/anyOf/0/type',
    params: { type: 'object' },
    message: 'should be object' },
  { keyword: 'minItems',
    dataPath: '.location',
    schemaPath: 'point/anyOf/1/minItems',
    params: { limit: 2 },
    message: 'should NOT have less than 2 items' },
  { keyword: 'anyOf',
    dataPath: '.location',
    schemaPath: 'point/anyOf',
    params: {},
    message: 'should match some schema in anyOf' } ]
```

In this case, the first path of `anyOf` should not have been followed (as the input is not an object but instead an array). Unfortunately, I get back a sort of confusing collection of errors for the user which I'll now have to go back and parse my way through manually it seems. 

Is there a way to reduce the output errors to only the path followed which best matches the input?

**Comment by mbroadst** [comment]
hm, I thought the solution might be to switch to `oneOf` (instead of `anyOf`, so we're only reporting errors for the path chosen), but that results in the following somewhat useless error:

```
testing:  { name: 'BadBob', location: [ 200 ] }
valid:  false
errors:  [ { keyword: 'oneOf',
    dataPath: '.location',
    schemaPath: 'point/oneOf',
    params: {},
    message: 'should match exactly one schema in oneOf' } ]
```

**Comment by epoberezkin** [comment]
anyOf collects one error for each subschema and if no valid subschema is found it also adds anyOf error. Determining which of failing subschemas "best matches" the input is not trivial - it seems to be out of scope of validation and more like in application scope.

oneOf only passes if only one subschema is valid. In most cases anyOf faster - it only needs to validate until valid subschema is found; oneOf will have to validate all schemas if the data is valid. The error in your case has schemaPath and dataPath that allow to determine what the error relates to. Maybe it should like anyOf keep the errors from subschemas...

**Comment by mbroadst** [comment]
@epoberezkin thanks for the explanation, looks like I can use v5's `switch` to get the more specific errors I'm looking for!
