### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by VassuRaw** [ajv-validator/ajv#2016]
**What version of Ajv you are you using?
8.11

**What problem do you want to solve?**
Async validation of one field using the value of other field and making async call and validate the data.

**What do you think is the correct solution to problem?**
I have implemented same using yup validation schema using when api, in which i got the value of country field and using that country value , I was able to validate services field for that country by async call to server.

**Will you be able to implement it?**

**Comment by epoberezkin** [comment]
There is support for user-defined async keywords, and they can access any field in the data - check out the docs - what exactly is missing there?

**Comment by epoberezkin** [comment]
https://ajv.js.org/guide/async-validation.html

**Comment by VassuRaw** [comment]
Any demo or example if you have?

**Comment by epoberezkin** [comment]
I sent the link, and you can see validation examples in the tests.

**Comment by epoberezkin** [comment]
Closing - please add any specific suggestion around async validation if needed
