### ISSUE TITLE
Consider implementing v5 features

### ISSUE THREAD

**Issue by gajus** [ajv-validator/ajv#203]
https://github.com/json-schema/json-schema/wiki/v5-Proposals

I realise these features are still in proposal stage, however it would give a leading edge competing with other implementations, such as tv4.

**Comment by gajus** [comment]
Features such as:
- `enumNames` https://github.com/json-schema/json-schema/wiki/enumNames-(v5-proposal)
- Custom errors, https://github.com/json-schema/json-schema/wiki/Custom-error-messages-(v5-proposal)

could be supported without breaking contract with v4.

**Comment by gajus** [comment]
Ignore. Didn't read the docs fully before commenting.

https://github.com/epoberezkin/ajv#validation-keywords

**Comment by epoberezkin** [comment]
I guess I could add to the tagline "the only validator supporting v5 proposals" ;)
