### ISSUE TITLE
Many errors when using oneOf for switch/case validation

### ISSUE THREAD

**Issue by m2broth** [ajv-validator/ajv#2041]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10
**Ajv options object**

```javascript

```

**JSON Schema**

```json
{
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'carsSchema',
  type: 'object',
  oneOf: [
    { $ref: '#/$defs/trainRequiredFields' },
    { $ref: '#/$defs/busRequiredFields' },
    { $ref: '#/$defs/carRequiredFields' }
  ],
  additionalItems: false,
  required: ['vehicleType'],
  $defs: {
    trainRequiredFields: {
      type: 'object',
      properties: {
        vehicleType: { const: 'train' },
        name: {
          type: 'string'
        },
        trainType: {
          type: 'string'
        }
      },
      required: ['name', 'trainType']
    },
    busRequiredFields: {
      type: 'object',
      properties: {
        vehicleType: { const: 'bus' },
        name: {
          type: 'string',
        },
        isSchool: {
          type: 'boolean'
        }
      },
      required: ['name', 'isSchool']
    },
    carRequiredFields: {
      type: 'object',
      properties: {
        vehicleType: { const: 'car' },
        name: {
          type: 'string'
        },
        engineType: {
          type: 'string'
        },
        hp: {
          type: 'number'
        }
      },
      required: ['name', 'engineType']
    }
  }
}
```

**Sample data**

```json

```

**Your code**

```javascript

```

**Validation result, data AFTER validation, error messages**
Message:
Value "car" does not match const.
Schema path:
carsSchema#/$defs/busRequiredFields/properties/vehicleType/const
Message:
Value "car" does not match const.
Schema path:
carsSchema#/$defs/trainRequiredFields/properties/vehicleType/const
Message:
Invalid type. Expected Number but got String.
Schema path:
carsSchema#/$defs/carRequiredFields/properties/hp/type
Message:
Required properties are missing from object: isSchool.
Schema path:
carsSchema#/$defs/busRequiredFields/required
Message:
Required properties are missing from object: trainType.
Schema path:
carsSchema#/$defs/trainRequiredFields/required
```

```

**What results did you expect?**
Does it correct behaviour to add additional fields per "vehicleType" eg. only the "car" type has the "hp" property. I'm getting many errors from other types too. How to create create a schema that will validate only one particular type? eg. only train if the vehicleType is "train"
**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
most likely you are using allErrors: true option, in which case this is the expected behaviour.

**Comment by m2broth** [comment]
I'm testing it using the https://www.jsonschemavalidator.net service. Setting the allErrors to false doesn't help on the application side.

**Comment by epoberezkin** [comment]
> How to create create a schema that will validate only one particular type?

you need to use discriminator for that (in ajv v8) - keyword and option.

without discriminator ajv has no way to decide which branch to choose and has to validate all branches to make sure one (and only one) branch passes. allErrors won't help in this case, as it cannot short-circuit branches without discriminator keyword.

**Comment by m2broth** [comment]
Thank you!
