### ISSUE TITLE
schema must be object or boolean

### ISSUE THREAD

**Issue by Profesor08** [ajv-validator/ajv#2052]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v8.11.0

**Your code**

```javascript
import Ajv from "ajv";

const ajv = new Ajv();
```

**Additional trace**
```
core.js:444 Uncaught Error: schema must be object or boolean
    at Ajv._addSchema (core.js:444:1)
    at Ajv.addSchema (core.js:234:1)
    at Ajv.addMetaSchema (core.js:242:1)
    at Ajv._addDefaultMetaSchema (ajv.js:24:1)
    at new Ajv (core.js:114:1)
    at new Ajv (ajv.js:10:1)
    at 
```

**What results did you expect?**
Code to not to crash on `new Ajv()`

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
This looks to be a compatibility issue, this code would work in plain JS. Please resubmit using compatibility template

**Comment by dimer191996** [comment]
@epoberezkin fu

**Comment by kajyr** [comment]
FYI: I can reproduce this error when compiling with webpack and having set:
```
{
    test: /\.(png|jpg|gif|svg|ico|xml|json)$/,
    type: 'asset/resource'
},
```

For some reasons ajv requires some internal schema from a json file, and with this rule it will receive the path of the json copied by webpack, instead of the json obj.

**Comment by Profesor08** [comment]
@kajyr yes, I think I had similar issue, causes by file loader, because I need some json files to be loaded in runtime. But ajv wants to load it's own json files for it's own purposes, and this is making unexpected conflicts. Any way it is ajv issue and easily can be fixed on it's side moving contend of json files into ts files.
