### ISSUE TITLE
patternProperties reports invalid expression `Lone quantifier brackets` for escaped, and other seemingly valid, expression

### ISSUE THREAD

**Issue by ReinsBrain** [ajv-validator/ajv#2054]
Ajv version 8.11.0

The javascript:
```javascript
let ajv = new Ajv({ strict: false });
addFormats(ajv);
const validate = ajv.addSchema([ openapischema ]).compile(apixpschema);
console.log(JSON.stringify(validate(data)));
validate(data);
return validate;
```

The schema (vastly simplified for example):
```json
{
	"type": "object",
	"patternProperties": {
		"^\\\/(?!-)(?:[a-zA-Z0-9-]+|{\\w+})(?<!-)(?:\\\/(?!-)(?:[a-zA-Z0-9-]+|{\\w+})(?<!-))*(\\\/(?!-\\.)[a-zA-Z0-9-\\.]+(?<!-\\.))?$": {
			"type": "object"
		}
	}, "additionalProperties": false
}
```

The data (simplified) to validate:
```json
{ "/test/{testpatharg}/test": {} }
```

Proof that the regex works: https://regex101.com/r/1nMc3V/1

There is quite a bit of escaping in the regex so I do use this online resource to help me escape properly: https://www.freeformatter.com/json-escape.html#before-output

The (unexpected and confounding) syntax error:
```
SyntaxError: Invalid regular expression: /^\/(?!-)(?:[a-zA-Z0-9-]+|{\w+})(?<!-)(?:\/(?!-)(?:[a-zA-Z0-9-]+|{\w+})(?<!-))*(\/(?!-\.)[a-zA-Z0-9-\.]+(?<!-\.))?$/: Lone quantifier brackets
    at new RegExp (<anonymous>)
    at defaultRegExp (/home/rein/git/rebelstack/apixp/node_modules/ajv/dist/core.js:23:39)
    at usePattern (/home/rein/git/rebelstack/apixp/node_modules/ajv/dist/vocabularies/code.js:73:16)
    at /home/rein/git/rebelstack/apixp/node_modules/ajv/dist/vocabularies/applicator/additionalProperties.js:53:127
    at Array.map (<anonymous>)
    at isAdditional (/home/rein/git/rebelstack/apixp/node_modules/ajv/dist/vocabularies/applicator/additionalProperties.js:53:74)
    at /home/rein/git/rebelstack/apixp/node_modules/ajv/dist/vocabularies/applicator/additionalProperties.js:36:28
    at /home/rein/git/rebelstack/apixp/node_modules/ajv/dist/compile/codegen/index.js:519:71
    at CodeGen.code (/home/rein/git/rebelstack/apixp/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen._for (/home/rein/git/rebelstack/apixp/node_modules/ajv/dist/compile/codegen/index.js:488:18)
```

**Comment by ReinsBrain** [comment]
Following up with more tests in plain javascript, I've had to resort to escape-insanity:
```javascript
var schema = `{
	"type": "object",
	"patternProperties": {
		"^\\\\\/(?!-)(?:[a-zA-Z0-9-]+|{\\\\w+})(?<!-)(?:\\\\\/(?!-)(?:[a-zA-Z0-9-]+|{\\\\w+})(?<!-))*(\\\\\/(?!-\\\\.)[a-zA-Z0-9-\\\\.]+(?<!-\\\\.))?$": {
			"type": "object"
		}
	}, "additionalProperties": false
}`;
var parsed = JSON.parse(schema);
var regex = new RegExp(Object.keys(parsed.patternProperties)[0]);
let match = "/test/{templatearg}/test".match(regex);
console.assert(match.length > 0,{parsed,regex,match}); // passes
```
This extra escaping works in javascript, but same regex string in `patternProperties` still reports
```
Syntax Error:
Invalid regular expression: /^\\/(?!-)(?:[a-zA-Z0-9-]+|{\\w+})(?<!-)(?:\\/(?!-)(?:[a-zA-Z0-9-]+|{\\w+})(?<!-))*(\\/(?!-\\.)[a-zA-Z0-9-\\.]+(?<!-\\.))?$/ : Lone quantifier brackets
```

**Comment by epoberezkin** [comment]
This is how it is when you put regular expressions into strings.

**Comment by ReinsBrain** [comment]
I have no choice but to put regular expression into string, Regular expression literals were excluded from JSON and it's founder frequently insists JSON will not change. Between rock and hard place is where I'm at. Of course, I recognize that you've probably been down this road before and before me. And it looks like it may not be the fault of Ajv (hence not an issue here).

If that is the case, do you have any suggestions please?

**Comment by epoberezkin** [comment]
JSON Schema has to be a plain object, with regular expressions represented as stings - there is nothing to fix here, sorry.

If you want to use JS syntax for regular expressions in schemas you have to do something like  `/^a\.bc$/.toString().slice(1, -1)` to avoid escaping of back slashes in strings (and you cannot use flags).

Alternatively, you can use a non-standard keyword for regular expressions from ajv-keywords (but it would still expect regexes to be strings).

**Comment by ssbarnea** [comment]
Maybe someone can explain me how this is not a bug:
```
Invalid regular expression: /^{{[\S\s]*}}$/: Lone quantifier brackets
```

I tested and `^{{[\S\s]*}}$` is perfectly valid regular expression conforming to ECMA-262 and also validated via https://regex101.com/ -- still ajv chokes when it finds a pattern described like this. JSON representation requiring escaping of the backslash only, so `"^{{[\\S\\s]*}}$"`.

Documentation from http://json-schema.org/understanding-json-schema/reference/regular_expressions.html is also clear regarding how a pattern should be stored inside JSON file.
