### ISSUE TITLE
The instancePath property of errors

### ISSUE THREAD

**Issue by TangCL123** [ajv-validator/ajv#2057]
I would like to know if there is any other solution to cancel the "errorDataPath:'property'" parameter, to solve the "required" check that the "instancePath:''" property is empty

`
{
    instancePath: '',
    schemaPath: '#/required',
    keyword: 'required',
    params: { missingProperty: 'name' },
    message: "must have required property 'name'"
  }
`

**Comment by epoberezkin** [comment]
This is not a bug.

The missing property is not a property error, it is an object level error. To convert errors to the messages that are meaningful to the users you can either write code, that would generate errors depending on the failed keyword (that would be my recommendation, as it allows you better control of user facing messages), or you could use a non-standard `errorMessage` keyword defined in ajv-error (which puts error generation logic in the schema, makes it non-standard, and less flexible than just writing code).
