### ISSUE TITLE
Support creating ajv bundle in Windows

### ISSUE THREAD

**Issue by sushant160185** [ajv-validator/ajv#206]
Hi, 

While install ajv throug npm I'm getting error. Attached is the error log "npm-debug.txt"
[npm-debug.txt](https://github.com/epoberezkin/ajv/files/302571/npm-debug.txt)

I was also not able to create separate UMD bundle for browser using npm run bundle script. Attached in the error log "npm-run-bundle-debug.txt" Is it required that I install ajv before creating the bundle? 
[npm-run-bundle-debug.txt](https://github.com/epoberezkin/ajv/files/302577/npm-run-bundle-debug.txt)

Let me know what could be the problem here.

Thanks.

**Comment by epoberezkin** [comment]
Can't reproduce, although I tried with npm 3.9.3 (I used nvm to install, that's the latest it has), yours is 3.9.5

**Comment by epoberezkin** [comment]
Ah, just noticed, you have windows...

**Comment by epoberezkin** [comment]
Also, did you just 'npm install'ed or 'git clone'd and then installed?

**Comment by sushant160185** [comment]
Yes. I'm trying it on windows.

I tried two ways. First downloaded the zip and copied in into file system and then tried npm install. Then also tried to git cloned and then install, however the issue was same.

**Comment by epoberezkin** [comment]
It all works on mac...

Can you at least install ajv as a dependency?

The only existing circular dependency, if that's what it is, is that ajv depends on gh-pages-generator that depends on ajv. gh-pages-generator is a dev dependency (although it makes no difference on mac, it works ok if it's a normal dependency as well)... Can you maybe try removing it from package.json and run npm install without it?

**Comment by ralphtheninja** [comment]
@sushant160185 Can you provide us with a `package.json` of your project so we can try and reproduce this?

**Comment by epoberezkin** [comment]
It's in repo: https://github.com/epoberezkin/ajv/blob/master/package.json

**Comment by epoberezkin** [comment]
@ralphtheninja Ah, sorry, got it :)

**Comment by epoberezkin** [comment]
As I understood, @sushant160185 did just the following:

```
git clone git@github.com:epoberezkin/ajv.git
cd ajv
npm install
```

So ajv is not a dependency, it was installed separately.

@sushant160185 is it correct?

**Comment by ralphtheninja** [comment]
Works well on linux as well. I suspect something is fishy here ;)

**Comment by sushant160185** [comment]
@epoberezkin Yes, all I did was create a clone of ajv (using git desktop), "cd ajv" and "npm install ajv" and I got this error. I haven't changed or added anything in the ajv repository. I'm trying it on windows 7 os. 

@ralphtheninja package.json is part of the ajv repository. No changes done in that.

I'm new to this npm environment so if you can give me some steps on how should I do it on windows environment then it will be helpful for me.

Thanks.

**Comment by epoberezkin** [comment]
Did you try removing gh-pages-generator from package.json before npm install?

**Comment by sushant160185** [comment]
Yes, I did. Seems it still gave same exception. Attached is the log.
[npm-debug.txt](https://github.com/epoberezkin/ajv/files/304340/npm-debug.txt)

**Comment by ralphtheninja** [comment]
> I'm new to this npm environment so if you can give me some steps on how should I do it on windows environment then it will be helpful for me.

You shouldn't need to do anything special. Unfortunately I don't have access to a windows machine at home :/ I can try tomorrow.

**Comment by epoberezkin** [comment]
@sushant160185 Can I ask what are you trying to do in general? To make some change in ajv?

**Comment by sushant160185** [comment]
No, not to change anything in ajv. I wanted to try this in a simple browser based app. So at first I tried creating bundle from ajv package, however, "npm run build" script failed. I then tried to do installation first and then check the build process, however, that also failed. 

In the meantime, I picked up the file from cdnjs site for my app so as such I'm not stuck but was just hoping that I should be able to install and/or create the bundle independently.

**Comment by epoberezkin** [comment]
Bundle is included in npm package. If you make ajv a dependency in your app (`npm install ajv --save`), there will be a bundle in the folder `node_modules/ajv/dist`. Using CDN is also an option.

I still need to figure out what is wrong with npm install inside ajv in windows.

**Comment by blakeembrey** [comment]
It's not a bug, it's caused by the command you've tried to run. You don't want to do `npm install ajv` inside `ajv` - you can not install the module inside itself. If you're trying to use it locally, you can use `npm install` (no `ajv`) to install dependency and `npm link` to link it to other places. Most likely, you just want to install `ajv` inside your project - so you'd `cd` into your project and run `npm install ajv` there.

**Comment by sushant160185** [comment]
Thanks @blakeembrey. This copied the ajv and other dependencies inside my project app with some warnings.
For the package creation for web ("npm run bundle" mentioned in the browser documentation section), what should I do since there is no bundle script in this copied folder. Although as @epoberezkin mentiond, it already has those files inside dist folder. Still how to create the ajv bundle for browser usage? Can you give me the steps?

**Comment by epoberezkin** [comment]
The bundle shipped with ajv can be used as is - this is recommended.

If you really want to re-build you need:

```
git clone git@github.com:epoberezkin/ajv.git
cd ajv
npm install
npm run build
npm run bundle
```

**Comment by sushant160185** [comment]
@epoberezkin  Thanks. I ran these commands. Everything ran fine except npm run bundle, which gave error 

> '.' is not recognized as an internal or external command,operable program or batch file.

**Comment by blakeembrey** [comment]
Most likely because https://github.com/epoberezkin/ajv/blob/master/package.json#L21 isn't a Windows executable. I think if you change `./scripts/` to `node script/` it will work on Windows.

**Comment by sushant160185** [comment]
@blakeembrey I made the changes however it still failed with following error. 

> <ajvrepo>ajv\scripts\bundle:9
> name=$(./scripts/info $package name)
>        ^
> SyntaxError: Unexpected token .
>     at Object.exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:513:28)
>     at Object.Module._extensions..js (module.js:550:10
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Function.Module.runMain (module.js:575:10)
>     at startup (node.js:160:18)
>     at node.js:456:3

**Comment by epoberezkin** [comment]
@sushant160185 You have to fix lines 9-12 in bundle script in the same way.

**Comment by sushant160185** [comment]
I did that as well. The error this time was: 

> ajv\scripts\bundle:9
> name=$(node scripts/info $package name)
>        ^^^^
> SyntaxError: missing ) after argument list

**Comment by epoberezkin** [comment]
in 4.11.5
