### ISSUE TITLE
String maxLength works incorrectly with Hebrew

### ISSUE THREAD

**Issue by Zaporozhec7** [ajv-validator/ajv#2078]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Happens on latest *8.11.0* as well as on *8.6.2*

**Ajv options object**

No options passed - default

**JSON Schema**

```json
{
    "type": "string"
    "maxLength": 24
}
```

**Sample data**

```json
"מענה אנושי👨🏼‍🦰 👱🏽‍♀️"
```

**Your code**

```javascript
var Ajv = require('ajv');
const assert = require('assert');

ajv = new Ajv({
    // options here
});

var schema = {
    type: 'string',
    maxLength: 24,
};

var data = "מענה אנושי👨🏼‍🦰 👱🏽‍♀️";
// String have length == 25
assert.equal(data.length, 25);

var validate = ajv.compile(schema);

console.log(validate(data));
console.log(validate.errors);

```

On RunKit - https://runkit.com/zaporozhec7/630fad1baaf36c000a0376b6

**Validation result, data AFTER validation, error messages**

No errors, but should be

**What results did you expect?**

String do not pass validation, because actually 25 characters long

**Are you going to resolve the issue?**
Not sure yet

**Comment by Zaporozhec7** [comment]
Just tried deprecated **unicode** option, and when it is set to ```false```, validation works as expected - returning error where it should.
But it not good to use deprecated option, and also it write warning to logs

**Comment by epoberezkin** [comment]
"It's a feature, not a bug" :)

JSON schema defines string length differently from JavaScript - as actual string length in unicode characters. JavaScript "characters" are not really characters, they are fixed at 16 bits, so many characters occupy more than one 16-bit slot. By default Ajv counts real string length, and with the deprecated `unicode: false` option it uses JavaScript `.length`.
