### ISSUE TITLE
override default validation behavior in custom keyword

### ISSUE THREAD

**Issue by mbroadst** [ajv-validator/ajv#208]
I might be trying to bend the rules a bit much here, but is it possible to override the validation behavior of other keywords in a custom keyword - perhaps like so:

```
{ type: 'string', allowAFunctionAsWell: true }
```

Understandably this could be implemented with `anyOf`/`oneOf`, but in my particular case this would make implementation much cleaner if it were possible.

**Comment by epoberezkin** [comment]
It's not possible at the moment. I have some doubts that it is a good idea to be honest, particularly for type keyword.

You may want to use independent custom keywords instead. I've recently started adding some useful keywords to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords), both to use them and to serve as implementation examples...

**Comment by mbroadst** [comment]
@epoberezkin so I'm using ajv to replace an existing home brewed schema system in an ODM (we've briefly discussed this via email), and it supports ReQL `terms` which are functions later evaluated by the database driver. For example, let's say I have the following schema:

```
let Model = test.thinkagain.createModel(test.table(0), {
  type: 'object',
  properties: {
    id: { type: 'string' }
  }
});
```

It's reasonable for the user to want to do something like `let m = new Model({ id: r.uuid() })`, which will result in a string once processed by the server and returned, however on initial validation it will fail because `r.uuid` evaluates to a function. I'm trying to find a way to easily support that, instead of monkey-patching every schema provided to `createModel` to change a simple definition to e.g. `oneOf: [ <schema they provided>, { myKeyword: 'that supports ReQL Terms' } ]` which may make validation results a bit confusing. One solution that seemed reasonable to me was to patch the schemas to just add a keyword that might instead override the `type` in this special case.

I _totally_ understand this is a very special contortion that sort of exists outside the intentions of json-schema, but I figured it was worth the discussion!  I think this would improve the user experience, as adding the `anyOf`/`oneOf` is more of a non-trivial modification of the initial schema.

Thoughts?

**Comment by epoberezkin** [comment]
I think using a custom keyword `{ "typeof": ["string", "function"] }` is better than redefining standard `type` keyword for several reasons.

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv-keywords#typeof

**Comment by mbroadst** [comment]
@epoberezkin one of the main goals of using json-schema in my case is to actually be able to reuse the schema for the front and backend of my system. I'm trying to make the schema I use for this particular model as "pure" as possible, using such a keyword sort of completely defeats the purpose. Further, the goal here is to internally amend the given schema only in the case where you are going to actually use the rethinkdb driver (the backend), so you could still use the same schema for form generation on the front end (no need to accept functions here). 

I guess the real issue I have presently is that there is no way to bypass the default validation behavior at all. I could have, for instance, manually checked the schema and somehow omitted the property using a function from validaton as an alternative to the proposed keyword solution of bypassing the `type` check - if there had only been a way to do so. So I guess more to the point: is there _some_ method you might find more palatable here for bypassing validation rules? (I'd also like to point out that I wasn't initially proposing we be allowed to override the `type` keyword itself, although that would work too, but instead allow another keyword to indicate that validation had succeeded and no other validation functions should be run - a potential optimization in some cases as well perhaps)

**Comment by epoberezkin** [comment]
You can define custom keyword that would analyse errors collected so far and remove them based on some criteria. So your `allowAFunctionAsWell` could be a custom keyword that would check that if type validation failed but the data is a function it would remove the validation error.

**Comment by mbroadst** [comment]
@epoberezkin ah very clever 😄 I'll give that a shot, as ever I appreciate the quick feedback

**Comment by mbroadst** [comment]
@epoberezkin if I'm not misunderstanding this would have to be done as an inline validator, because we don't have access to the aggregated errors in a plain `compile` right?

**Comment by mbroadst** [comment]
got it, at least an incredibly basic form of ignoring all errors;

```
keywords.ignoreErrors = {
  errors: 'full',
  statements: true,
  inline: (it, keyword, schema) => {
    return 'return true;';
  }
};
```

I think I can get this working from here, cheers!

**Comment by epoberezkin** [comment]
Yes, that's correct, it will have to be inline. You've probably found that already: https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords :)

By the way, `return true;` may not complete validation if it is in some subschema that was compiled to a separate function rather than inlined. But in general, that's the idea.

**Comment by mbroadst** [comment]
Okay, I'll start with the simple cases and move from there. If it's part of a subschema there's no real way to fully bypass validation though right?

**Comment by epoberezkin** [comment]
Subschemas that don't have refs inside them are inlined (can be turned off). Also, before you return you need to clear errors. But I don't think you want to return, do you? I thought you would update `vErrors` and `errors`.

**Comment by epoberezkin** [comment]
See this too: https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#short-circuit-validation

**Comment by mbroadst** [comment]
@epoberezkin aye, I've seen it thanks! I've got an incredibly early preview of the work I've been doing over here: https://github.com/mbroadst/thinkagain, cheers!
