### ISSUE TITLE
How to get several values of properties within a validation function?

### ISSUE THREAD

**Issue by xfg** [ajv-validator/ajv#209]
I want to create the authentication schema, but my custom keyword `validatePassword` need two schema properties `email` and `password` to then check the user credentials against the database. I don't  understand how can i get the value of email property within my validatePassword function ?

Here is my simple example.

``` javascript
{
    "$async": true,
    "type": "object",
    "properties": {
      "email": {
        "allOf": [
          {"type": "string"},
          {"format": "email"}
        ]
      },
      "password": {
        "allOf": [
          {"type": "string"},
          {"validatePassword": true}
        ]
      }
    },
    "require": ['email', 'password']
  }

validator.addKeyword('validatePassword', {
    async: true,
    compile: function (schema, parentSchema) {
      return function validate (data) {
        return User.where('email', HERE_I_NEED_THE_VALUE_OF_EMAIL_PROPERTY).fetch()
          .then(model => {
            if (model === null) {
              return false;
            }
            return validatePassword(data, model.get('password'));
          });
      }
    },
    errors: true
});
```

How can I get the email value instead `HERE_I_NEED_THE_VALUE_OF_EMAIL_PROPERTY` string within my validatePassword function ?

How to solve similar problems with ajv? Thanks.

**Comment by epoberezkin** [comment]
You need to use this custom keyword in the parent object, not in the property:

``` json
{
    "$async": true,
    "type": "object",
    "properties": {
      "email": {
         "type": "string",
         "format": "email"
      },
      "password": { "type": "string" }
    },
    "required": [ "email", "password" ],
    "validatePassword": true
}
```

``` javascript
validator.addKeyword('validatePassword', {
    async: true,
    schema: false,
    validate: function (data) {
      return User.where('email', data.email).fetch()
        .then(model => {
          if (model === null) {
            return false;
          }
          return validatePassword(data.password, model.get('password'));
        });
    },
    errors: true
});
```

You can use validation function straight away and pass `schema: false` when you don't need keyword value: https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-validation-function

Btw, you don't need to use allOf when combining two rules, it's only needed when combining two schemas and 1) one of them is $ref; 2) the order is important (custom keyword will be the last one to be validated anyway); 3) you need to combine two different values for the same keyword (e.g. two different patterns).

**Comment by xfg** [comment]
Thanks for your reply. It's work, but I want to send a client the errors in this format:

``` json
{
  "email": [
    "error message 1",
    "error message 2",
    "error message N"
  ],
  "password": [
     "error message 1",
     "error message 2",
     "error message N"
  ]
}
```

I create the my errors with this function

``` javascript
  function createValidationErrors(err) {
    var errors = {};
    err.errors.forEach(error => {
      objectPath.push(errors, error.dataPath, error.message);
    });
    return errors;
  }
```

But in the parent object my keyword `validatePassword` (and `required` too) have empty `dataPath` and I don't understand how can I assign the `validatePassword` error to my `errors` object for the password property.

Is it real?

**Comment by epoberezkin** [comment]
Probably just code to transform the object ajv returns to the object you need. dataPath is empty string because it refers to the top level object you pass, not to some property.

The structure of error object is documented and is not going to change without notice and major version change.
