### ISSUE TITLE
Nested allOf and anyOf: runtime validation fails

### ISSUE THREAD

**Issue by thomasheartman** [ajv-validator/ajv#2096]
**Description**

I'm trying to create a schema that allows for a set of shared properties plus two _mutually exclusive_ properties. That is, an object can have all properties A,B...P, but only one of Q or R (though both are optional). 

It may be that I'm doing it wrong, but I've consulted all the documentation I've found on the subject, and I can't seem to do it right. The type does seem to come out right, but the validation fails. I suspect that this is an error with this library. However, it may well be that it is just my mistake. In that case: please let me know what the right way to do this would be.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.11 (already on the latest version)

**Ajv options object**

```javascript
const ajv = new Ajv({
    schemas: Object.values(schemas).map((schema) =>
        omitKeys(schema, 'components'),
    ),

    // example was superseded by examples in openapi 3.1, but we're still on 3.0, so
    // let's add it back in!
    keywords: ['example'],
});

addFormats(ajv, ['date-time', 'uri', 'uri-reference']); 
```

**JSON Schema**

```json
       {
        "allOf": [
          {
            "type": "object",
            "required": [
              "username"
            ],
            "properties": {
              "username": {
                "type": "string"
              }
            }
          },
          {
            "oneOf": [
              {
                "properties": {
                  "project": {
                    "type": "string"
                  }
                }
              },
              {
                "properties": {
                  "projects": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            ]
          }
        ]
      }
```

**Sample data**

```json
  {
    "username": "string",
    "project": "default"
  }
```

**Your code**

I have tried to make a [working code sample on runkit with 8.11](https://runkit.com/63219d2678f048000852fd37/63219d318c14410009a801bd), but there seems to be something wrong with it. I get a syntax error. The same syntax error occurs if I just clone the default sample code and upgrade ajv.

Instead, here's [sample code with ajv 4.4.0](https://runkit.com/63219d2678f048000852fd37/63219eebab75740008b91a58): it showcases the same issue.

I'm not sure what code you're looking for here (sorry!), so here's what's in the runkit instead
```javascript
var Ajv = require('ajv');

var ajv = new Ajv({
     // example was superseded by examples in openapi 3.1, but we're still on 3.0, so
    // let's add it back in!
    keywords: ['example']
});

var schema = 
 {
        "allOf": [
          {
            "type": "object",
            "required": [
              "username"
            ],
            "properties": {
              "username": {
                "type": "string"
              }
            }
          },
          {
            "oneOf": [
              {
                "properties": {
                  "project": {
                    "type": "string"
                  }
                }
              },
              {
                "properties": {
                  "projects": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            ]
          }
        ]   
};

var data = {
        "username": "string",
    "project": "default"
};

var validate = ajv.compile(schema);

console.log(validate(data));
console.log(validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
{"error":"Request validation failed","validation":[{"keyword":"oneOf","dataPath":".body","schemaPath":"#/components/schemas/createApiTokenSchema/allOf/1/oneOf","params":{"passingSchemas":[0,1]},"message":"should match exactly one schema in oneOf"}]}
```

**What results did you expect?**

I would expect the above schema to let me submit **either** `username` and `project` **or** `username` and `projects` **or** just username.

**Are you going to resolve the issue?**

I'd be happy to help if there's something I can do, but I'm not very familiar with the library just yet, so I'm not sure it would do much good.

**Additional context**

I've been trying in as many different ways as I can imagine to make this work, but I haven't been able to. For reference, this seems to be about the closest I've gotten in code (using the json-schema-to-ts package and avj)

<details>

<summary>Actual source code</summary>

```ts
export const createApiTokenSchema = {
    $id: '#/components/schemas/createApiTokenSchema',
    type: 'object',
    required: ['username', 'type'],
    oneOf: [
        {
            properties: {
                username: {
                    type: 'string',
                },
                type: {
                    type: 'string',
                    enum: Object.values(ApiTokenType),
                },
                environment: {
                    type: 'string',
                },
                expiresAt: {
                    type: 'string',
                    format: 'date-time',
                    nullable: true,
                },
                project: {
                    type: 'string',
                },
            },
        },
        {
            properties: {
                username: {
                    type: 'string',
                },
                type: {
                    type: 'string',
                    enum: Object.values(ApiTokenType),
                },
                environment: {
                    type: 'string',
                },
                expiresAt: {
                    type: 'string',
                    format: 'date-time',
                    nullable: true,
                },
                projects: {
                    type: 'array',
                    items: {
                        type: 'string',
                    },
                },
            },
        },
    ],
    components: {},
} as const;

export type CreateApiTokenSchema = FromSchema<typeof createApiTokenSchema>;
```

</details>

----

Any help or insight is much appreciated.

**Comment by epoberezkin** [comment]
The problem seems to be that neither project no projects properties are required, so both branches pass, and oneOf only allows one branch to pass to be valid. You need to use required and a third branch prohibiting both properties. Or you can use “not: required”. Or you can probably use anyOf. However you do it you need to make sure that only one branch of oneOf can pass, not both.

**Comment by thomasheartman** [comment]
Ah! That makes a lot of sense, actually. That's probably the issue here! I'll go have a look. Thank you!

**Comment by thomasheartman** [comment]
I've had a look at this now, but can't quite make it work. You're more than likely spot on, but I'm not sure how to represent it. Could you give me some pointers?

> You need to use required and a third branch prohibiting both properties. 

How can I prohibit specific properties? We generally don't want to set `additionalProperties: false` on incoming data objects, so don't think I could do it here either in the case that it breaks someone's setup. 

Would `not: required` work for that? E.g.

```json
{
  "not": { "required": ["project", "projects"] }
}
```

From what I can tell, that works for the third branch, but might just be because either property is required on the other two branches.

Side question: What does `not: required` mean? Is it one of the following two statements?
1. These properties are not required on the object (same as the default for properties not marked as required)
2. These properties are **not allowed** on the object

> Or you can use “not: required”. Or you can probably use anyOf. However you do it you need to make sure that only one branch of oneOf can pass, not both.

Got it! I'm not exactly sure how to do that. Would you be able to give me any pointers? I've got something that looks about like this now, but I'm still getting errors when I try and use either project or projects:

## Current version

```json
      {
        "type": "object",
        "allOf": [
          {
            "properties": {
              "username": {
                "type": "string"
              },
            }
          },
          {
            "oneOf": [
              {
                "required": [
                  "username",
                  "project"
                ],
                "not": {
                  "required": [
                    "projects"
                  ]
                },
                "properties": {
                  "project": {
                    "type": "string"
                  }
                }
              },
              {
                "required": [
                  "username",
                  "projects"
                ],
                "not": {
                  "required": [
                    "project"
                  ]
                },
                "properties": {
                  "projects": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              {
                "required": [
                  "username",
                  "type"
                ],
                "not": {
                  "required": [
                    "project",
                    "projects"
                  ]
                }
              }
            ]
          }
        ]
      }
```

### Errors

I get this when I try and use `project`. When I use `projects`, I get the opposite error. It seems to think that it's failing validation for one of them, but matching two of them, if I read that correctly?

```json
{
  "error": "Request validation failed",
  "validation": [
    {
      "keyword": "required",
      "dataPath": ".body",
      "schemaPath": "#/components/schemas/createApiTokenSchema/allOf/1/oneOf/1/required",
      "params": {
        "missingProperty": "projects"
      },
      "message": "should have required property 'projects'"
    },
    {
      "keyword": "oneOf",
      "dataPath": ".body",
      "schemaPath": "#/components/schemas/createApiTokenSchema/allOf/1/oneOf",
      "params": {
        "passingSchemas": [
          0,
          2
        ]
      },
      "message": "should match exactly one schema in oneOf"
    }
  ]
}
```

**Comment by epoberezkin** [comment]
The issue is not specific to Ajv issue, it's related to using JSON schema spec. In short, you either need to use anyOf, if both subschemas can be valid for the data, or you need to make subschemas mutually exclusive when you use oneOf (and the error says it is not the case).

You can ask general questions on using JSON schema on StackOverflow.

**Comment by thomasheartman** [comment]
Got it; appreciate the input 🙏🏼
