### ISSUE TITLE
how to use in browser

### ISSUE THREAD

**Issue by siddo420** [ajv-validator/ajv#21]
I am writing test cases using Jasmine and need to use ajv through my browser.

I have already attempted to use it with browserify but it doesn't seem to work. Please provide a quick example as to how to use it within browser after bundling the package using browserify.

Here is what I have done so far:

```
browserify node_modules/ajv/lib/ajv.js -o node_modules/ajv/lib/bundle.js
```

and added that into my jasmine Spec file using:

```
  <script src="../../node_modules/ajv/lib/bundle.js"></script>
```

Then??

**Comment by epoberezkin** [comment]
We use it with browserify with require('ajv') in dependent module, not as a separate bundle, but it should work the way you do it too. Are you using the latest version? it only works from 0.5.2.

**Comment by siddo420** [comment]
Yes, using the latest versions of browserify and ajv.

**Comment by epoberezkin** [comment]
ah, yes, it doesn't create any global at the moment. You can:
1) require it directly from your code as we do
2) create file bundle.js like this:

```
window.Ajv = require('ajv');
```

and then browserify and use this bundle

**Comment by siddo420** [comment]
It looks like Browserify does not make require function available with the command I was using. Here is what I used instead:

```
browserify -r ./node_modules/ajv/lib/ajv.js:ajv -o ./node_modules/ajv/lib/bundle.js
```

Then, I was able to use it normally (after including bundle.js)

```
    Ajv                  = require('ajv')
  , ajv                  = Ajv()
```

**Comment by epoberezkin** [comment]
Cool, thanks. I will add to readme. Just to confirm, you are still loading bundle in a separate script tag, correct?

**Comment by siddo420** [comment]
Yes, I still load bundle.js in a script tag in HTML file.

```
  <script src="node_modules/ajv/lib/bundle.js"></script>
```

For some reason, many of the browserify articles do not mention -r option.

**Comment by epoberezkin** [comment]
Thanks, added "Using in browser" to readme.

**Comment by nsdelgadov** [comment]
@epoberezkin Can you add a link to this thread in the readme please? [This help me a lot](https://github.com/epoberezkin/ajv/issues/21#issuecomment-123800576) :D
PD: sorry for my english.

**Comment by epoberezkin** [comment]
@nsdelgadov it's changed since then - the supplied bundle already creates global (it is "universal"). So if you load bundle from npm package or from cdnjs you can just use global Ajv. Maybe just one line comment can be added to readme.
