### ISSUE TITLE
Parse and serialize produces unexpected "undefined" string

### ISSUE THREAD

**Issue by eikooc** [ajv-validator/ajv#2101]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Using version 8.11.0

**Ajv options object**

```javascript
const ajv = new Ajv()
```

**JSON Type Definition (JTD)**

```json
{
  "properties": {
    "foo": { "type": "string" }
  }
}
```

**Sample data**

```json
{}
```

**Your code**

```javascript
const serialize = ajv.compileSerializer(schema)
const parser = ajv.compileParser(schema)
parser(serialize({}))
```

**What results did you expect?**

```js
{
  foo: undefined
}
```

But got:
```js
{
  foo: "undefined"
}
```

**Comment by epoberezkin** [comment]
compiled serialiser does not validate the data, it assumes the data is valid according to the provided schema (it can be enforced with types). In this case an empty object is not valid, because foo is required property. If you tried to parse "{}" it would fail.

**Comment by eikooc** [comment]
@epoberezkin this behavior is really surprising. If `foo` is a required property then shouldn't the serialiser either give some sort of error or returning an empty object? Letting it produce a string with data seems incorrect since you can't distinguish between missing data, wrong data and errors?

**Comment by epoberezkin** [comment]
This decision is based on the fact that the application has control of the data it produces – it can be achieved with types in Typescript. Serialiser could have done validation of course (this is what you are suggesting), but it would be at the cost of performance, so the decision was to assume that the passed data is consistent with the schema you used to compile this serializer (and in TypeScript the serialiser won't even accept incorrect data type - see the example [here](https://ajv.js.org/guide/typescript.html#type-safe-parsers-and-serializers)). This would be the same in every other language that has type-based marshalling/unmarshalling of data into JSON strings.

If you need to validate the data you can do it as a separate step (e.g. you could have it in debugging mode, or during development, there is no need to include validation into serialisation).

Also see this: https://ajv.js.org/api.html#ajv-compileserializer-schema-object-data-any-string

**Comment by eikooc** [comment]
I see, thanks for the explanation
