### ISSUE TITLE
Cannot serialize and then parse int32 type

### ISSUE THREAD

**Issue by eikooc** [ajv-validator/ajv#2102]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Using version 8.11.0

**Ajv options object**

```javascript
const ajv = new Ajv()
```

**JSON Type Definition (JTD)**

```json
{
  "properties": {
    "foo": { "type": "int32" }
  }
}
```

**Sample data**

```json
{}
```

**Your code**

```javascript
const serialize = ajv.compileSerializer(schema)
const parser = ajv.compileParser(schema)
const data = parser(serialize({}))
```

**What results did you expect?**

```js
// data to be:
// {
//   foo: undefined
// }
```

But got:
```js
// data is:
// undefined
```

**Comment by GabenGar** [comment]
`"int32"` is not a valid json schema type.

**Comment by eikooc** [comment]
@GabenGar I've updated the header to read "JSON Type Definition (JTD)" to avoid confusion. It should be a valid JTD.

**Comment by epoberezkin** [comment]
this is a duplicate of #2101, see the comment there, this is not a bug.
