### ISSUE TITLE
Meta-Schema-Validation not working / no guide available

### ISSUE THREAD

**Issue by manuelwaltschek** [ajv-validator/ajv#2109]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Integrating Ajv2019 from `"ajv": "^6.12.6",` with Angular

**Ajv options object**

```javascript

 const ajv = new Ajv2019({allErrors: true});

```

**JSON Schema**

Use case: Trying to validate custom schemas against meta schema draft 2019-09
e.g:

```json

{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://example.com/schemas/template.json",
    "title": "Template",
    "type": "object",
    "properties": {},
    "required": [],
    "additionalProperties": false
}

```

**Your code**

```javascript

const ajv = new Ajv2019({allErrors: true});
 valid = ajv.validateSchema(json);
errors = ajv.errors;

```

**Validation result, data AFTER validation, error messages**

```
no schema with key or ref "https://json-schema.org/draft/2019-09/schema"

```

**What results did you expect?**

Meta-Schema validation working.

**Are you going to resolve the issue?**

**Comment by GabenGar** [comment]
Does it work if you remove `$schema` key? Can also try changing the protocol in it to `http`.

**Comment by manuelwaltschek** [comment]
@GabenGar I'll try to write some unit tests and will check out these cases now
When I try changing it to http it complains with 

> Error: no schema with key or ref "http://json-schema.org/draft/2019-09/schema"

**Comment by manuelwaltschek** [comment]
When I remove the "$schema" keyword it seems to work, but as far as I understand this keyword should be included as a best practice?
How do I assert that the validateSchema function works as expected for 2019-09 draft schemas?
I found https://github.com/json-schema-org/JSON-Schema-Test-Suite

But do I really need to implement the complete test suite to assert this?

**Comment by GabenGar** [comment]
It shouldn't be included because the usage of `Ajv2019` already implies `"https://json-schema.org/draft/2019-09/schema"` meta-schema. Also you aren't using [`validateSchema()` properly](https://ajv.js.org/options.html#validateschema).

**Comment by manuelwaltschek** [comment]
@GabenGar thank you for your response. So what would be the correct way to validate a schema against 2019-09 meta schema?

**Comment by GabenGar** [comment]
They are validated automatically when [added to the `ajv` instance](https://ajv.js.org/api.html#ajv-validateschema-schema-object-boolean).

**Comment by manuelwaltschek** [comment]
@GabenGar yes I know but as the documentation states

> By default this method is called automatically when the schema is added, so you rarely need to use it directly.

I believe I have such a rare use case since usually the validator is used to validate data against a custom schema.
In my use case the user creates custom schemas and therefore I need to explicitly validate the schema against the meta schema (draft 2019-09) and report any issues with the validation.

For this use case I see no examples in the documentation hence I reported a missing guide / I am not sure if and how this use case is covered by ajv.

The closest I got was calling the validateSchema() method explicitly but then again I don't really understand the behavior of it.

The resource on the link you provided ([validateSchema()](https://ajv.js.org/options.html#validateschema)) states

> Validate added/compiled schemas against meta-schema (true by default). $schema property in the schema can be http://json-schema.org/draft-07/schema or absent (draft-07 meta-schema will be used) or can be a reference to the schema previously added with addMetaSchema method.

I don't know if this is also true for an instance of `Ajv2019` or if it implicitly validates schemas against meta-schema 2019-09 by default. Then again it does not accept the value of `$schema` being neither _"https://json-schema.org/draft/2019-09/schema"_ nor _"http://json-schema.org/draft/2019-09/schema"_

**Comment by GabenGar** [comment]
> In my use case the user creates custom schemas and therefore I need to explicitly validate the schema against the meta schema (draft 2019-09) and report any issues with the validation.

Should've started with that.

Get the validator function directly then:
```typescript
const validateMetaSchema = ajv.getSchema("https://json-schema.org/draft/2019-09/schema")
```

**Comment by manuelwaltschek** [comment]
Thank you I will try it out
Are there any docs on the get method?
And what is the purpose of using Ajv2019 then?

**Comment by GabenGar** [comment]
That was my mistake, it is [`getSchema()`](https://ajv.js.org/api.html#ajv-getschema-key-string-undefined-data-any-boolean-promise-any).

**Comment by manuelwaltschek** [comment]
Do you even think that is necessary?
How should validateSchema behave with an instance of Ajv2019?

**Comment by epoberezkin** [comment]
you should import this class and use it to create Ajv instance - see the samples here: https://ajv.js.org/json-schema.html#draft-2019-09

**Comment by epoberezkin** [comment]
> How should validateSchema behave with an instance of Ajv2019?

It would validate it agains draft-2019 meta-schema

**Comment by GabenGar** [comment]
> Do you even think that is necessary?

Yes, because you are just validating an incoming JSON which has to conform to a `"https://json-schema.org/draft/2019-09/schema"` schema. So you get a validator function which AJV itself uses to validate schemas added to it (and meta-schemas must be self-validating).
The whole meta-schema/`validateSchema()` setup is for a different purpose not related to your usecase.

**Comment by manuelwaltschek** [comment]
@epoberezkin thank you! @GabenGar but it seems that this is exactly what I need. Why wouldn't it be related to my use case?

@epoberezkin why wouldn't it accept the $schema property? It seems the 07 version would accept it or imply it.

**Comment by epoberezkin** [comment]
> why wouldn't it accept the $schema property? It seems the 07 version would accept it or imply it.

ajv has different Ajv classes for different drafts, you cannot combine them in one instance.
