### ISSUE TITLE
dependentSchemas unknown keyword

### ISSUE THREAD

**Issue by spinlud** [ajv-validator/ajv#2112]
I am getting error when switching from `dependencies` to `dependentSchemas`:

```ts
import Ajv from 'ajv';

const ajv = new Ajv();

export const schema = {
    type: 'object',
    properties: {
        foo: { type: 'string' },
        bar: { type: 'string' },
    },
    dependentSchemas: { // <- dependencies works
        foo: { required: ['bar'] }
    }
}

const validate = ajv.compile(schema);
```

```
Error: strict mode: unknown keyword: "dependentSchemas"
```

Reference: [https://ajv.js.org/json-schema.html#dependentschemas](https://ajv.js.org/json-schema.html#dependentschemas)

`node`: `v16.17.0`
`ajv`: `8.11.0`

**Comment by agjs** [comment]
@spinlud Did you manage to solve this? Thanks

**Comment by epoberezkin** [comment]
This keyword is only defined in draft-2019, by default Ajv imports draft-7. You need to change the import to `import Ajv from 'ajv/dist/2019'` (or 2020 if you want to use draft-2020).
