### ISSUE TITLE
Question: "1/larger" and "0#"?

### ISSUE THREAD

**Issue by AshCoolman** [ajv-validator/ajv#213]
I am confused by `"1/larger"` and `"0#"` in the [$data](https://github.com/epoberezkin/ajv#data-reference) docs. I can _infer_ what is going on, but I can't find an explanation of this syntax. Could someone point me in the right direction?

**Comment by epoberezkin** [comment]
There is a link to relative JSON-pointer draft in docs: https://tools.ietf.org/html/draft-luff-relative-json-pointer-00

**Comment by epoberezkin** [comment]
also see examples here: https://gist.github.com/geraintluff/5911303
