### ISSUE TITLE
customKeyword error for Compile checks

### ISSUE THREAD

**Issue by claudio-viola** [ajv-validator/ajv#217]
Hi I am trying to create a custom error for a custom Keyword while using compile instead of validate.

The example here that you shared in a previous issue works fine for me https://tonicdev.com/esp/5731a55eabbf001200bbc028
However if i replace validate with compile . I cannot add any error 

`var Ajv = require('ajv');
var ajv = Ajv({
  verbose: true,
  allErrors: true
    //v5: true  //enable v5 proposal of JSON-schema standard
}); // options can be passed, e.g. {allErrors: true}

//build schema
//TODO added points to questions and check if the summation of all points are equals to maxPoints
ajv.addKeyword('validateMaxPoints', {
  errors: true,
  async: false,
  type:'object',
 compile: function myValidation(value, dataObject) {
    if (myValidation.errors === null)
      myValidation.errors = [];

```
myValidation.errors.push({
  keyword: 'validateMaxPoints',
  message: 'maxPoints attribute should be ' + 0 + ', but is ' + 0,
  params: {
    keyword: 'validateMaxPoints'
  }/*,
  dataPath: '.maxPoints',
  schemaPath: '#/validateMaxPoints',
  schema: true*/
});

return false;
```

  }
});`

Could you perhaps point me if i am doing something wrong? 
I am using the exact same code just replacing validate with compile !
How do i go about adding custom errors for the compile function?
Thanks in advance!

**Comment by epoberezkin** [comment]
Function in compile property of keyword definition should return validation function, rather than validation result.

**Comment by claudio-viola** [comment]
hi epoberezkin. I believe I have already tried that without success
compile: function myValidation(bla,balb) {
  return validation() {
     validation.errors = []
     validation.errors.push( .... )
     return false;
 }
}

Can you provide a working example?

**Comment by epoberezkin** [comment]
https://tonicdev.com/esp/576fa7d3b9a58d120006e88c

That's exactly your code. Not sure what did you expect...

**Comment by claudio-viola** [comment]
Hi there thanks for the prompt response!
The code was indeed partly as you showed in the end I finally realised where the issue was
This piece of code https://tonicdev.com/57710050b5157813007dd853/217/2.0.0  will explain better why I did not get the errors  
The solution is to do the following  https://tonicdev.com/57710050b5157813007dd853/1

The code shown at https://tonicdev.com/57710050b5157813007dd853/217/2.0.0 is certainly partly my mistake in accessing the library api, there could be a slight issue as well though.
 What do you think?

**Comment by epoberezkin** [comment]
It is all correct. If you use ajv.validate method, the returned value is validation result (boolean) and the errors are added to ajv instance (ajv.errors).

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv#getting-started

**Comment by claudio-viola** [comment]
Thanks. can be closed!
