### ISSUE TITLE
Receiving 'Content Security Policy of your site blocks the use of 'eval' in JavaScript' error while using AJV library.

### ISSUE THREAD

**Issue by RiddhiShah23** [ajv-validator/ajv#2175]
ajv.validate(schema, data); is not working without specifying 'unsafe-eval' in CSP.

I want to know if is there any plan to resolve this issue without modifying CSP since this is creating security breach.

Is there any workaround to this issue ?

**Comment by epoberezkin** [comment]
https://ajv.js.org/security.html#content-security-policy

that page links to https://ajv.js.org/standalone.html - that’s the only approach
