### ISSUE TITLE
Ajv fails to validate schema for Object with "propertyNames" from "enum"

### ISSUE THREAD

**Issue by marke-apexit** [ajv-validator/ajv#2177]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

latest / 8.11.2

**Ajv options object**

Using defaults

**JSON Schema**
```json
{
    "type": "object",
    "propertyNames": {
        "enum": ["Foo","Bar"]
    },
    "patternProperties": {
        ".*": {
            "type": "number"
        }
    }
}
```

```json
{
    "Foo": 123,
    "Bar": 456
}
```
**Your code**

```javascript
    const schema = ajv.addSchema(schema_Test);
    console.log(schema.validate(schema_Test, json_test));
    console.error(schema.errorsText());
```

**Validation result, data AFTER validation, error messages**

```
false
data must be equal to one of the allowed values, data property name must be valid
```

**What results did you expect?**

I expected this to successfully validate. A leading JSON Schema validator for .Net does successfully validate the JSON against the JSON Schema.

**Are you going to resolve the issue?**
No.

**Comment by marke-apexit** [comment]
If anyone is wondering about the use case for this, in my actual schema I have a few different enums that are used in multiple ways. For example, the enum is used for the set of valid values in a REST API request, but the response will include an object where the possible properties are also defined by the same enum.  By sharing the enum any changes for the request/response are made in one place, just add/edit/delete items in the enum.

**Comment by epoberezkin** [comment]
it does work correctly - https://runkit.com/esp/639b6a80507997000895088a

You need to post the whole code sample, ideally to runkit, to reproduce.

You are not using API correctly - ajv.addSchema returns ajv, it is done simply to allow chaining, but it doesn't change anything – it should still work.

Possibly, you are using incorrect import?
