### ISSUE TITLE
keyword: 'type' message: 'must be array' 

### ISSUE THREAD

**Issue by habsfanongit** [ajv-validator/ajv#2185]
Hi, I am getting an error ```keyword: 'type' message: 'must be array' ```
There is a complete example with schema and code https://github.com/habsfanongit/ajvExample. 
Please note that the example is using pnpm. to use npm delete the pnpm-lock.yaml and run npm install and change the start script in the package.json file to ```npm run build && node dist/src/server.js``` from  ```"start": "pnpm run build && node dist/src/server.js",``` 
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
 "ajv": "^8.11.2" is the latest version

**Ajv options object**
```allErrors: true``` is passed to the ajv constructor

**JSON Schema**

```json
{
    "$schema": "http://json-schema.org/schema#",
    "description": "Post Schema Definition",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "Id": {
                "type": "string",
                "description": "Post ID"
            },
            "PostedBy": {
                "type": "string",
                "description": "Name of poster"
            },
            "category": {
                "type": "string",
                "description": "Post Category"
            },
            "UserName": {
                "type": "string",
                "description": "Name of user"
            },
            "effectiveDate": {
                "type": "string",
                "format": "date",
                "description": "Effective date of the post. Format YYYY-MM-DD"
            },
            "reviewerId": {
                "type": "number",
                "description": "Reviewer ID"
            }
        },
        "required": ["Id", "PostedBy", "category", "UserName","effectiveDate", "reviewerId"]
    }
}


```

**Sample data**
The POST is using VSCode Rest Client Plugin (in the rep under restCall directory)

```json
@url = http://localhost:3000/validate/
 POST {{url}}
 Content-Type: application/json


{
	"items": [{
			"Id": "1",
			"PostedBy": "Jane Doe",
			"category": "Some Category",
			"UserName": "Me",
			"effectiveDate": "2022-09-30",
			"reviewerId": "Mon"
		},
        {
			"Id": "2",
			"PostedBy": "Jon Doe",
			"category": "Category 2",
			"UserName": "Someone else",
			"effectiveDate": "2022-09-30",
			
		}
        
    ]
}
```

**Your code**
```javascript

```

```javascript
import express, {Express,Request, Response} from "express"
import Ajv, { AnySchema } from "ajv";
import addFormats from "ajv-formats";
import Post from "./interfaces/Post";
import { readFileSync } from "fs";

const schemaFile =  readFileSync("./schemas/posts.json", "utf-8");
const app:Express = express();
app.use(express.json());
app.post("/validate",(req:Request, res:Response)=>{
    const schemaObject =JSON.parse(schemaFile)
    const ajv = new Ajv({ allErrors: true});
    addFormats(ajv);
    const isValid = ajv.compile<Post>(schemaObject);
    if(isValid(req.body)){
        console.log("Valid");
        
    }
    else{
        console.log(isValid.errors);
       
    }
    res.end();
});
app.listen(3000, ()=>{
    console.log('running on port 3000');
})
```

**Validation result, data AFTER validation, error messages**
```
{
    instancePath: '',
    schemaPath: '#/type',
    keyword: 'type',
    params: { type: 'array' },
    message: 'must be array'
  }
```

**What results did you expect?**
expect the validation to fail because the request first object of the array ```"reviewerId": "Mon"``` should be a number 
**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
> const isValid = ajv.compile<Post>(schemaObject);

this is a really bad idea to compile schema as part of the request handling - you should either compile it lazily and cache, or compile on application start. As is, it gets recompiled, with a memory leak on every request. Read this doc: https://ajv.js.org/guide/managing-schemas.html

In you case you can just have this line outside the request handler.

On the actual error, I am pretty sure that schemaObject is not what you think it is. Create a minimal sample where schema is just taken from a variable.

**Comment by habsfanongit** [comment]
Thanks @epoberezkin.

**Comment by epoberezkin** [comment]
Ah, sorry, your data is just incorrect - your whole data should be an array according to your schema, which is what the error says, and not an object with items property - so you need to either change your data or your schema.
