### ISSUE TITLE
schemaPath is different between AWS Lambda and local execution

### ISSUE THREAD

**Issue by m-ronchi** [ajv-validator/ajv#2186]
**The version of Ajv you are using**
8.11.0

**The environment you have the problem with**
AWS Lambda

**description**

when validating invalid data 

**Results in node.js v8+**
also occurs with `sam local invoke`
```
,"errors":[{
    "instancePath":"/join_ts",
    "schemaPath":"depot:com.<redacted>/analytics/user_ctx/2-0-0/properties/join_ts/format",
    "keyword":"format",
    "params":{"format":"date-time"},
    "message":"must match format \"date-time\""
}]
```

**Results and error messages in your platform**

```
  "errors": [
        {
          "instancePath": "/join_ts",
          "schemaPath": "#/properties/join_ts/format",
          "keyword": "format",
          "params": {
            "format": "date-time"
          },
          "message": "must match format \"date-time\""
        }
      ]
```

**Comment by epoberezkin** [comment]
if schema ID is not part of the schema itself, then it will be taken from the key, so you must be providing a different key in that env - it doesn't seem to be an issue with ajv at all.

**Comment by m-ronchi** [comment]
the code is exactly the same. I tried modifying it to ensure the schema with $id is at the top-level and now I get the `#/...` schemaPath in my unit tests.

code is dynamically loading schemas like this:
init: 
```
const ajv = new Ajv({
    allErrors: true,
    async loadSchema(uri) {
      return await depot.get(uri); // <- wrapped http client
    },
  });
```
fetching schemas:
```
...
 ajv.getSchema(s) ??
                (logger.debug("fetching schema:", { schema: s }),
                await ajv.compileAsync({ $ref: s })
...
```

and the modified version is like 
```
...
 ajv.getSchema(s) ??
                (logger.debug("fetching schema:", { schema: s }),
                await depot.get(s)
                  .then((s) => ajv.compileAsync(s))
...
```

how is schemaPath calculated?

ps: what do you mean by "the key" and how do I pass it to ajv?

**Comment by epoberezkin** [comment]
in this case ajv.compileAsync uses schema URI as the key, if it is missing in the schema doc. You either need to have the same URIs (probably impossible in different envs), or define schema IDs (that's what I'd do), or you'd have different paths in errors.
