### ISSUE TITLE
Removing schema by key reference doesn't remove the schema reference by id

### ISSUE THREAD

**Issue by qurafi** [ajv-validator/ajv#2187]
When removing a schema by key, you can still get the schema by id or vice versa.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.11.2

**Ajv options object**
No options

**JSON Schema**
With any schema
```javascript
const schema = {
    $id: "id",
    type: "object",
    properties: {
        nested: {
            type: "number",
        },
    },
};
```

**Your code**

```javascript
ajv.removeSchema("id");
console.log(schemas()); // ['key']
console.log(ajv.getSchema("key")?.schema); // schema found {"$id": ...}
console.log(ajv.getSchema("id")?.schema); // undefined
```
run again but with key ref:
```javascript
ajv.removeSchema("key");
console.log(schemas()); // []
console.log(ajv.getSchema("key")?.schema); // undefined
console.log(ajv.getSchema("id")?.schema); // schema found {"$id": ...}
```

**What results did you expect?**
When removing a schema by id or key it should remove both references by key and id.

**Comment by epoberezkin** [comment]
Why do you need both ID and key reference? Usually you would use one or another, with ID being a better approach.

The main reason key was even added is to support 3rd party schemas without IDs, if you author schemas you won’t normally use keys.

**Comment by qurafi** [comment]
I assumed the key reference will work as a name alias of long schema IDs and the docs is not clear about key ref use cases. If this the case, is not possible to just add id dynamically with `{...schema, $id: "your id"}` .?

**Comment by epoberezkin** [comment]
Yes, you can do it like that… Possibly it needs to be changed like you describe, but I wouldn’t do it without a major version release. For short aliases - in most cases you are better off with some map in your own app to refer to the schemas, Ajv still uses keys for ref lookup, so in theory you can get some collisions.

**Comment by qurafi** [comment]
Yeah I think it's better to just use external maps. Currently working on automatic file-based endpoints validation and I thought using key ref to quickly know which schema belong to endpoint using combination of path and schema id(so no id and key collision in this case). But this was not the case.

Anyways. Thank you. Appreciate your hard work 👍
