### ISSUE TITLE
Custom validation function (including multiple properties)

### ISSUE THREAD

**Issue by targhs** [ajv-validator/ajv#2189]
Sorry if this is already answered. This isn't a bug or feature request rather a question. 

We have a schema with 2 date fields "date_fr" and "date_to". And need to validate that "date_fr" is always smaller than "date_to". I can't add any keyword. Is there any way i can add additional validation function along with what is defined in the schema. Or is there any other way to achieve this?

Schema isn't formatting correctly when pasting here. 
You can check my question on [here](https://stackoverflow.com/questions/74959707/custom-validation-function-with-ajv). Happy to provide any further details. 
Thanks

**Comment by epoberezkin** [comment]
You can do one of two things:

1. use $data reference - https://ajv.js.org/guide/combining-schemas.html#data-reference
2. create custom keyword - https://ajv.js.org/keywords.html
