### ISSUE TITLE
Ignore all unknown format in v8 (unknownFormats: 'ignore')

### ISSUE THREAD

**Issue by sl-nigelalmada** [ajv-validator/ajv#2198]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.12.0

**Ajv options object**

Default

**Issue**

I'm currently upgrading one my project from using ajv v6 to ajv v8
I would like to keep all functionalities as close as possible as what we have right now 

One of them is to ignore all unknown formats from the schema 

From the documentation from the v8 I don't see a way to mimic the  `unknownFormats: 'ignore'` option anymore

I can only see that we can whitelist a specific format or just disable all format validation at once

But since I don't have control about how format are provided on schemas that I will compile, I reallly need a way to ignore unknown format while still being able to validate known ones

Is it something that is possible in v8 ?

**Comment by epoberezkin** [comment]
You can use `strictSchema: false` or `strictSchema: "log"` to ignore unknown formats and keywords: https://ajv.js.org/strict-mode.html#unknown-formats.

Defining all used format as always valid (see the link) is better, as this way you avoid typos.

**Comment by pimterry** [comment]
I agree this is very inconvenient @sl-nigelalmada.

In my case I'm taking schemas as input (I'm effectively using AJV to let users to validate their own data client side) so I have absolutely no way to know which unknown formats may be used in advance! I definitely want to ignore these issues regardless - in many cases schemas come with all sorts of extra metadata & odd formats that are used elsewhere but not relevant here, and I need to be able to do core validation immediately regardless, without that blocking anything or filling up the console logs with warnings.

`unknownFormats: 'ignore'` was perfect, and it's impossible to use the workaround you describe above @epoberezkin in this scenario.

Anyway, although it seems that nowadays AJV doesn't support this without `unknownFormats`, fortunately you can work around it with a JS proxy:

```javascript
const ajv = new Ajv({
    formats: new Proxy({}, {
        // Return 'true' (ignore) for *all* undefined formats:
        get(target, name) {
            if (name in target) return target[name];
            else return true;
        }
    })
});
```

This will ignore any unknown formats (with no annoying logging - it will just ignore them) but will still correctly validate any formats that are actually explicitly defined, e.g. with ajv-format.

(I still really wish AJV supported this directly though)
