### ISSUE TITLE
Custom format attributes should not fail validation

### ISSUE THREAD

**Issue by JonathanPlasse** [ajv-validator/ajv#2203]
The CI of [SchemaStore](https://github.com/SchemaStore/schemastore) fails with custom format attributes like `"format": uint`.

**JSON Schema**

Here is a snippet that fails taken from Ruff schema generated by [schemars](https://github.com/GREsau/schemars).

```json
    "line-length": {
      "description": "The line length to use when enforcing long-lines violations (like `E501`).",
      "type": [
        "integer",
        "null"
      ],
      "format": "uint",
      "minimum": 0.0
    },
```

According to this issue GREsau/schemars#97,
> That sounds like a bug in ajv:
> https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.2.3
>> An implementation MUST NOT fail validation or cease processing due to an unknown format attribute.

I would be open to making a pull request to ignore unknown formats.

**Comment by epoberezkin** [comment]
by default Ajv is less permissive than the spec (that allows typos and unknown keywords and formats). Ajv considers schema to be a code and treats all unknown things as error. It can be changed with strict mode options: https://ajv.js.org/strict-mode.html
