### ISSUE TITLE
Error on date-time validation

### ISSUE THREAD

**Issue by medez** [ajv-validator/ajv#221]
Hi, 

There is an issue when validating a date-time property. If the data matches the ISO pattern, but defines an invalid date, the validation passes.

For example : 

``` json
{
  "type" : "object",
  "properties" : {
     "start" : {
       "type" : "string",
       "format" : "date-time"
     }
  }
}
```

If I send { "start" : "2016-15-12T00:00:00.123Z" }, The test should fail, but it passes.

BR
Seb

**Comment by epoberezkin** [comment]
There is an option `format: "full"`. See [options](https://github.com/epoberezkin/ajv#validation-and-reporting-options) in docs

**Comment by epoberezkin** [comment]
See https://tonicdev.com/esp/5772e2ec8dc3051200da3961

**Comment by medez** [comment]
Thank's, i'll try it

**Comment by davidsimonboyd** [comment]
@epoberezkin 
We've also encountered this issue. 
Unfortunately there are 4 other libs sitting between my code and ajv, none of which support passing options through.
Would you accept a PR using a slightly stricter regex in the default fast mode?
I have a working branch, and would like permissions to raise a PR if possible.

**Comment by epoberezkin** [comment]
What would be the regex change?

**Comment by davidsimonboyd** [comment]
I was hoping it could be something like this:
`(\d\d\d\d)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])`

with the same change applied to date-time as well

It would catch many incorrect dates, and not affect performance too much ..

**Comment by VilleViktor** [comment]
@epoberezkin , this isn't resolved? https://github.com/ajv-validator/ajv/blob/master/lib/compile/formats.js#L5 ?
