### ISSUE TITLE
Property name with `/` converted into `~1`

### ISSUE THREAD

**Issue by jaimesangcap** [ajv-validator/ajv#2226]
Why property names with `/` gets replaced with `~1`? 
`user/username` becomees `user~1username` for example.

Where does it happen and is it possible to disable it?

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript

```

**JSON Schema**

```json
{
  type: "object",
  properties: {
    "user/username": {type: "integer"},
    "user/password": {type: "string", "minLength": 6},
  },
  additionalProperties: false,
}
```

**Sample data**

```json
{
  "user/username": "user1",
  "user/password": "abc",
}
```

**Your code**
Codesandbox link
https://codesandbox.io/s/tender-flower-yybhqt?file=/src/index.js

```javascript

```

**Validation result, data AFTER validation, error messages**

```
instancePath: "/user~1username"
schemaPath: "#/properties/user~1username/type"
keyword: "type"
params: Object
type: "integer"
message: "must be integer"
```

**What results did you expect?**
Retain the `/`,
`instancePath` should be `/user/username`
`schemaPath` should be `#/properties/user/username/type`

**Are you going to resolve the issue?**

**Comment by AanshSavla** [comment]
Hello @jaimesangcap! The JSON object consists of instancePath and schemaPath. For any type of path the special symbols are always encoded into a particular format. Say for e.g. HTML URL Encoding. Please check this:
https://www.w3schools.com/tags/ref_urlencode.ASP
If '/' is not converted to '~1' then the path will be interpreted as 'username is inside user'.

**Comment by epoberezkin** [comment]
this is not a bug. schemaPath uses a format JSON Pointer (RFC6901) to reference the path to the location in JSON object. As / is used to separate property names on different level, / inside property name has to be escaped like that - it's by the spec. See the examples here: https://www.rfc-editor.org/rfc/rfc6901.html#section-5
