### ISSUE TITLE
The instancePath property is empty. 

### ISSUE THREAD

**Issue by Mupli** [ajv-validator/ajv#2237]
Missing instance path "". ?? when throws "required". Maybe we should have path:"/name" 
```
{ 
instancePath: '', 
schemaPath: '#/required', 
keyword: 'required', 
params: { missingProperty: 'name' }, 
message: "must have required property 'name'" 
}
```
How I can get nested required if the first level required is shadowing the real property that I want to validate? Example: 

```
{
  root: {
       value: {},
       "required": ["value"]
  }
}
```

and get : /root/value  for body {}

**Comment by AanshSavla** [comment]
Can you send the data which is to be validated?

**Comment by epoberezkin** [comment]
Required error is always reported on the level of the object, not of the property. The property itself is never validated, the object is, and the object error is missing property name. You need to process errors in your code and report to users the way it's most suitable.
