### ISSUE TITLE
boolean coerce for URL parameters

### ISSUE THREAD

**Issue by chunlampang** [ajv-validator/ajv#2238]
Since boolean is able to use **number** form `1` or `0` when enabled `coerceTypes`.
However, for URL parameters validation, the parameters is always a string.
It will be invalid when putting 1 or 0 on URL (`/api?bool=1`) even `coerceTypes` is enabled.

**Requested change:**
Also allow **string** form `"1"` and `"0"` for boolean coerce

**Comment by epoberezkin** [comment]
I don't understand the issue, please resubmit with the code sample using the template.

**Comment by chunlampang** [comment]
Maybe I just write the result

https://github.com/ajv-validator/ajv/blob/45583fde112f80c06ba6ad5583b744ef22d0640a/lib/compile/validate/dataType.ts#L114-L119

```js
case "boolean": 
   gen 
     .elseIf(_`${data} === "false" || ${data} == 0 || ${data} === null`) 
     .assign(coerced, false) 
     .elseIf(_`${data} === "true" || ${data} == 1`) 
     .assign(coerced, true) 
```

Changed:
`${data} === 0` to `${data} == 0`
`${data} === 1` to `${data} == 1`

Accept the string `0` `1` instead of only `type === 'number'` will make it URL friendly
