### ISSUE TITLE
Question: changing the order of validation for enums

### ISSUE THREAD

**Issue by bios1337** [ajv-validator/ajv#2239]
Enum validation fails before applying custom keyword compilation in AJV v8.x

```
ajv.addKeyword({
  keyword: 'upperCase',
  modifying: true,
  type: 'string',
  compile(sch) {
    if (sch) {
      return (data, { parentData, parentDataProperty }) => {
        parentData[parentDataProperty] = data.toUpperCase();
        return true;
      };
    }
    return false;
  },
  errors: false,
  metaSchema: {
    type: 'boolean',
  },
});

const schema = {
    type: "object",
    properties: {
        "prop1": {
            type: 'string',
            enum: ['A', 'B', 'C'],
            upperCase: true, // custom keyword
        }
    }
}

const validator = ajv.compile(schema)
const isValid = validator.validate({ prop1: 'a' })
console.log(validator.errors) 
```

output:
```
0: {
instancePath: ..., 
schemaPath: ..., 
keyword: 'enum', 
params: { allowedValues: ['A', 'B', 'C'] }, 
message: 'must be equal to one of the allowed values'
}
```

There were no errors in AJV v6.x, this is related to change in order validation in AJV introduced in ajv v7.x

Custom keyword compilation/transformation is happening after enum validation that is why it is failing, any work arounds? Thank you.

**What version of Ajv you are you using?**
v8.x

**What problem do you want to solve?**

**What do you think is the correct solution to problem?**

**Will you be able to implement it?**

**Comment by AanshSavla** [comment]
Hello @bios1337 ! If the 'enum' variable consists of upperCase 'A' and if we pass lowerCase 'a' in prop1 then it will give error. Hence the message is that prop1 value must be equal to one of allowed values in enum. I am not able to understand your exact issue.

**Comment by epoberezkin** [comment]
to control validation order you need to use allOf - in this case your custom keyword will be in the first branch and enum in the second.
