### ISSUE TITLE
Browser page freezes when validate a value against a regular expression

### ISSUE THREAD

**Issue by konvict-dev** [ajv-validator/ajv#2248]
validated value (text): 
```javascript
xn-b1afk4ade4e.xnb1ab2a0a.xnb1aew.xn-p1ai/info-service.htm?sid=2000
```
condition:
```json
{
    "pattern": "^(([a-z0-9.-]+)(,|,\\s)?)+$"
}
```
example code:
```javascript
const text = "xn-b1afk4ade4e.xnb1ab2a0a.xnb1aew.xn-p1ai/info-service.htm?sid=2000"
const condition = {
    "pattern": "^(([a-z0-9.-]+)(,|,\\s)?)+$"
}

const validator = (schema) => {
    const validate = ajv.compile(schema);
    return (model) => {
        if (!validate(model)) return validate.errors;
   };
}

const validate = validator(condition);

const error = validate(text); // here the code execution hangs
```

**Comment by epoberezkin** [comment]
This is not an Ajv bug, but a general limitation of JS engine - it's easy to construct a regular expression + string combination with very long evaluation time.

You would get the same problem simply with `/^(([a-z0-9.-]+)(,|,\\s)?)+$/.test("xn-b1afk4ade4e.xnb1ab2a0a.xnb1aew.xn-p1ai/info-service.htm?sid=2000")` (not in Safari, btw)

Your choices are:
- don't use such regular expressions that result in long evaluation times
- use another regexp engine - Ajv allows configuring it

See https://ajv.js.org/security.html#redos-attack
