### ISSUE TITLE
Adding TypeScript definition to DefinitelyTyped

### ISSUE THREAD

**Issue by brierel** [ajv-validator/ajv#225]
Hi, I am using ajv in a TypeScript project and only recently figured out you provide a definition file. And that's great.
But I didn't found it on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository. Does someone plan adding it?

**Comment by epoberezkin** [comment]
@blakeembrey should it be there?

**Comment by blakeembrey** [comment]
No.

**Comment by brierel** [comment]
Ok... Can you detail why not? Is it because it declares a namespace, and for public use on DefinitelyTyped we would rather expect a module? This would not involve that much modifications.

**Comment by blakeembrey** [comment]
Because the definition is already written and works with typescript. All you have to do is install the module.

**Comment by brierel** [comment]
Ok thank you, indeed it makes sense. 
ajv module has been effectively in my project dependencies for some time, so I have now to check why the definition file was not correctly detected by WebStorm.

**Comment by epoberezkin** [comment]
@blakeembrey thank you!

**Comment by onury** [comment]
ok. it's in npm/@types. 👍
