### ISSUE TITLE
Ajv code ` typeof data == 'object'`

### ISSUE THREAD

**Issue by loynoir** [ajv-validator/ajv#2258]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.12.0

**Ajv options object**

```javascript

```

**JSON Schema**

```json

```

**Sample data**

```json

```

**Your code**

```javascript

```

**Validation result, data AFTER validation, error messages**

```

```

**What results did you expect?**

Actual 

`typeof data == 'object'`

Expected

`typeof data === 'object'`

Related

https://github.com/ajv-validator/ajv/issues/2257

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Assuming you refer to compiled code? In any case, it’s not a bug but a taste preference - these lines are always producing identical results as typeof operation always returns string
