### ISSUE TITLE
Issue with line feed chars in json

### ISSUE THREAD

**Issue by skolmer** [ajv-validator/ajv#226]
I want to validate a json file with keys that contain `\n` chars. This is a valid JSON string produced by JSON.stringify. Unfortunately ajv cannot compile these keys and is producing the following javascript code which causes schema compilation to fail with `Uncaught SyntaxError: Unexpected token ILLEGAL`

``` js
var valid1 = errors === errs_1; }  if (data['
    <users>
    ${0}
    </users>
'] !== undefined) {   var errs_1 = errors; if (typeof data['
    <users>
    ${0}
    </users>
'] !== "string") {    var err =  { keyword: 'type' , dataPath: (dataPath || '') + '[\'
    <users>
    ${0}
    </users>
\']' 
```

**json:**

``` json
"\n        <user name=\"${0}\">${1}</user>\n    ": {
  "type": "string"
},
"\n    <users>\n    ${0}\n    </users>\n": {
  "type": "string"
}
```

**Comment by epoberezkin** [comment]
@skolmer thank you.

JSON with special characters is not supported indeed...

It's relatively easy to address by escaping control characters in the code that inserts properties.

**Comment by skolmer** [comment]
Thanks for the fast response. Does it mean that you are planning to add support for special characters?

**Comment by epoberezkin** [comment]
Yes. Can you maybe check if I am missing some control characters in the test?

**Comment by skolmer** [comment]
Looks right, thank you!

**Comment by epoberezkin** [comment]
In 4.1.6. Please reopen if you notice some cases when control characters are not supported.
