### ISSUE TITLE
Default errror message is displayed even when custom error message is provided.

### ISSUE THREAD

**Issue by ktn05** [ajv-validator/ajv#2266]
Hi,

Im validating whether the property name provided matches the pattern that i have provided and., if it doesnt match, i have provided a custom error message, so that default message is overridden by custom message. 
But the issue is that along with the custom message even the default message is displayed which is not what i expected.

_Please click the below link to check the issue mentioned above._
https://codesandbox.io/s/sweet-taussig-q8ubk6

_Steps:_ 
In codepen, click the button that is available on top of angular logo, and check in its console.

**_Versions:_**
"ajv": "^8.12.0",
"ajv-errors": "^3.0.0",
 "ajv-keywords": "^5.1.0",

**Comment by epoberezkin** [comment]
Not an ajv issue difficult to debug – please submit to ajv-errors with a code sample as one file in the issue or, better, in runkit.com
Thank you!
