### ISSUE TITLE
compile a simple 2019-09 schema fails with: no schema with key or ref "${schemaKeyRef}"

### ISSUE THREAD

**Issue by sturmf** [ajv-validator/ajv#2273]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

```
$ npm list --depth=1
└─┬ ajv-cli@5.0.0
  ├── ajv@8.12.0
  ├── fast-json-patch@2.2.1
  ├── glob@7.2.3
  ├── js-yaml@3.14.1
  ├── json-schema-migrate@2.0.0
  ├── json5@2.2.3
  ├── minimist@1.2.8
  └── UNMET OPTIONAL DEPENDENCY ts-node@>=9.0.0
```

**Ajv options object**

```javascript
const Ajv = require("ajv")
const fs = require('fs');

let rawdata = fs.readFileSync('schema.json');
let schema = JSON.parse(rawdata);

const ajv = new Ajv() 
const validate = ajv.compile(schema)
```

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    }
  }
}
```

**Validation result, data AFTER validation, error messages**

```
../node_modules/ajv/dist/core.js:147
                throw new Error(`no schema with key or ref "${schemaKeyRef}"`);
                ^

Error: no schema with key or ref "http://json-schema.org/draft/2019-09/schema"
    at Ajv.validate (../node_modules/ajv/dist/core.js:147:23)
    at Ajv.validateSchema (../node_modules/ajv/dist/core.js:260:28)
    at Ajv._addSchema (../node_modules/ajv/dist/core.js:460:18)
    at Ajv.compile (../node_modules/ajv/dist/core.js:158:26)
    at Object.<anonymous> (../x/validate.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**What results did you expect?**
A successful compile of the schema

I also tried the following but it did not make a difference

```
const Ajv2019 = require("ajv/dist/2019")
const ajv = new Ajv2019()
```

**Comment by epoberezkin** [comment]
You need the second import indeed, and the URI should be https://json-schema.org/draft/2019-09/schema (not http).

**Comment by JeffCoster** [comment]
I get this error too. Using browser and getting ajv like this: <script src="https://cdnjs.cloudflare.com/ajax/libs/ajv/8.12.0/ajv2019.min.js" integrity="sha512-0lJa9spNGDvx2WdJx9SR4BnB+DHbGc5QKPA0S8Lj2M+rtMyeIyIO8T9Vc8swa/lvZ+kr2nzG3oMJxapZHOlX2A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
is OK. 
But in Node I get that error previously listed.
Code in browser is:
    const Ajv = window.ajv2019;
      const ajv = new Ajv({
      schemas: [mergerSchema]
      });

In Node its:
import {mergerSchema} from "../schema/merger-schema.js";
import Ajv2019 from "ajv"

 const ajv = new Ajv2019({
      schemas: [mergerSchema]
   });

--------------------------------
merger-schema has:
export const mergerSchema = {
    "$schema": "https://json-schema.org/draft/2019-09/schema",
