### ISSUE TITLE
Validate object value against array of objects

### ISSUE THREAD

**Issue by tanyamadaan** [ajv-validator/ajv#2282]
I am trying to create ajv based json schema validations. I want to validate if page.id value is equal to any one navigation.ids present in an array. For example:

    `"page": {
        "id": "1"
    },
    "navigation": [
        {"id": "1"},
        {"id": "2"},
        {"id": "3"}
    ]`

Can anyone please help suggest how can I validate this using ajv.

I was able to check if page.id is equal to first/second/third element in array, but if I specifically mention the element index while checking. However, the requirement is to check if id is equal to any of the element inside the array. Note: the size of navigation array is not limited or fixed.

    `page: {
        type: "object",
        properties: {
          id: {
            type: "string",
            const: { $data: "/navigation/0/id"},
          }
    `

**Comment by webdev-ashishk** [comment]
Try This out ->


{
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "contains": {
        "const": { "$data": "/navigation/*/id" }
      }
    }
  }
}

**Comment by jasoniangreen** [comment]
Closing as a potential solution has been offered with no reply for more than 2 weeks. In future it can really help the diagnoses of problems if you provide full code samples or even better a [runkit](https://runkit.com/jasoniangreen/ajv-issue) example.
