### ISSUE TITLE
Do we need to [make sure the folder exists](https://stackoverflow.com/questions/793858/how-to-mkdir-only-if-a-directory-does-not-already-exist) first?

### ISSUE THREAD

**Issue by Truonghau83** [ajv-validator/ajv#2287]
Do we need to [make sure the folder exists](https://stackoverflow.com/questions/793858/how-to-mkdir-only-if-a-directory-does-not-already-exist) first?
```suggestion
	  mkdir -p bibtex
          cd bibtex
```

_Originally posted by @sgbaird in https://github.com/sgbaird/awesome-self-driving-labs/pull/10#discussion_r1211156557_

**Comment by jasoniangreen** [comment]
This one isn't clear at all
