### ISSUE TITLE
Modify value while validating

### ISSUE THREAD

**Issue by ghost** [ajv-validator/ajv#2288]
hello there.... i am new to `Ajv`. i just want to ask how can i modify value while validatiing...
**For example**
lets say i have date field and date is in format `yyyy-MM-dd` and i just want to add time `hh:mm:ss`...
how can i acheive this....?

**Comment by jacobshirley** [comment]
I also cannot find how to do this.. is it even possible?

**Comment by mzeeshan7100** [comment]
Ajv is excellent but too much weak documentation . I switched to joi

**Comment by jasoniangreen** [comment]
Here is a general page on [modifying data while validating](https://ajv.js.org/guide/modifying-data.html), but for your specific request I think you would need to look into [adding a custom keyword](https://ajv.js.org/api.html#ajv-addkeyword-definition-string-object-ajv).
