### ISSUE TITLE
Support for nested/multiple discriminators in JTDSchemaType

### ISSUE THREAD

**Issue by rajataghi** [ajv-validator/ajv#2294]
**What version of Ajv you are you using?**

8.12.0

**What problem do you want to solve?**

I need to create a schema which can validate 3 different types based on values of 2 different fields in the input
Here is my code:
```
interface employeeEngineer {
  employeeType: "Engineer";
  jobType: "Full Time" | "Part Time";
  employeeId: string;
}

interface employeeManagerL1 {
employeeType: "Manager";
jobType: "Full Time";
managerId: string;
}

interface employeeManagerL2 {
employeeType: "Manager";
jobType: "Part Time";
managerId: string;
managerHours: number;
}

const schema: JTDSchemaType<employeeEngineer | employeeManagerL1 | employeeManagerL2>= {
  discriminator: "employeeType",
  mapping: {
    "Engineer": {
      properties: {
        jobType: {enum: ["Full Time", "Part Time"]},
        employeeId: {type: "string"}
      }
    },
    "Manager": {
      discriminator: "jobType", // error here - Object literal may only specify known properties, and 'discriminator' does not exist in type 'JTDSchemaType<Omit<employeeManagerL1 | employeeManagerL2, "employeeType">, Record<string, never>>'.
    }
  }
}
```
As you can see, I'm stuck while defining the 2nd level of discriminator

**What do you think is the correct solution to problem?**
The `mapping` field does not allow adding a `discriminator` property for nested discriminators, could not find any mention of nested discriminators for JTD in the documentation

**Will you be able to implement it?**
Not sure how, but happy to help

**Comment by joshmossas** [comment]
The JTD spec doesn't allow for nested discriminators inside the mapping property. The only allowed fields are `properties`, `optionalProperties` and `additionalProperties`

See here from the Json Type Definition website: https://jsontypedef.com/docs/jtd-in-5-minutes/#:~:text=You%20can%20only%20use%20properties%20/%20optionalProperties%20/%20additionalProperties%20in%20the%20schemas%20you%20put%20directly%20in%20mapping.%20You%20can%E2%80%99t%20use%20any%20other%20kind%20of%20schema%2C%20otherwise%20things%20would%20become%20ambiguous.

**Comment by joshmossas** [comment]
You could nest the discriminator inside of the `properties` key, but it does start to muddy things up I suppose.

```ts
const schema = {
    discriminator: 'employeeType',
    mapping: {
        Engineer: {
            properties: {
                jobType: { enum: ['Full Time', 'Part Time'] },
                employeeId: { type: 'string' },
            },
        },
        Manager: {
            properties: {
                data: {
                    discriminator: 'jobType',
                    mapping: {
                        'Part Time': {
                            properties: {
                                propA: { type: 'string' },
                            },
                        },
                        'Full Time': {
                            properties: {
                                propA: { type: 'string' },
                                propB: { type: 'string' },
                            },
                        },
                    },
                },
            },
        },
    },
};
```
