### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by PaulWalkerUK** [ajv-validator/ajv#2295]
**The version of Ajv you are using**
8.12.0

**The environment you have the problem with**
Firefox, Chrome

**Your code (please make it as small as possible to reproduce the issue)**
I'm loading it with this in my HTML:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/ajv@8.12.0/dist/ajv.js"></script>
  </head>
  <body></body>
</html>
```

**Results and error messages in your platform**
The browser console gives me this error:
```
Uncaught ReferenceError: exports is not defined
    <anonymous> https://unpkg.com/ajv@8.12.0/dist/ajv.js:2
```

I'm sorry, I assume I must be doing something wrong...

**Comment by klvenky** [comment]
I think the url(`https://unpkg.com/ajv@8.12.0/dist/ajv.js`) which is being used is not supposed to be used in browser. 
I have tried the same html markup with cdnjs & I have not faced any issue. Refer below @PaulWalkerUK 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ajv/8.12.0/ajv7.min.js"></script>
  </head>
  <body></body>
</html>
```

**Comment by PaulWalkerUK** [comment]
Thank you very much for your help, yes, that seems to be working fine.
