### ISSUE TITLE
Azure Pipelines schema error

### ISSUE THREAD

**Issue by bdovaz** [ajv-validator/ajv#2296]
@epoberezkin I am using `ajv-cli` but for the problem I have I want to think it is irrelevant that I use the cli.

Running:

> I get the url from:  https://www.schemastore.org/json/

```bash
curl "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json" --output service-schema.json

ajv compile -s service-schema.json
```

Output:

```
schema service-schema.json is invalid
error: strict mode: unknown keyword: "deprecationMessage"
error: Invalid regular expression: /^[^\/~\^\: \[\]\\]+(\/[^\/~\^\: \[\]\\]+)*$/: Invalid escape
```

**Comment by epoberezkin** [comment]
not an Ajv issue, not enough context.

**Comment by bdovaz** [comment]
@epoberezkin why do you say it is not an ajv problem and there is not enough context? I have put the command executed and the corresponding output, what else do you need? If you don't say so I can't help.

Also, I mention the issue from https://github.com/chris48s/v8r/issues/328 which is where they tell me as possibly the problem is in ajv.....
