### ISSUE TITLE
Type error: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.

### ISSUE THREAD

**Issue by dmkachko** [ajv-validator/ajv#2302]
**The version of Ajv you are using**

8.12.0

**Operating system and node.js version**

 13.4.1 Ventura  node v16.15.1

**Package manager and its version**
8.11

**Link to (or contents of) package.json**
  "dependencies": {
    "ajv": "^8.12.0",
    "autoprefixer": "10.4.14",
    "eslint-config-next": "13.4.4",
    "guid-ts": "^1.1.2",
    "lodash": "^4.17.21",
    "next": "13.4.4",
    "next-api-decorators": "^2.0.2",
    "path-to-regexp": "^6.2.1",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "rxjs": "^7.8.1",
    "tailwindcss": "3.3.2"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.195",
    "@types/node": "20.2.5",
    "@types/react": "18.2.8",
    "@types/react-dom": "18.2.4",
    "eslint": "8.42.0",
    "ts-json-schema-generator": "^1.2.0",
    "typescript": "5.1.3"
  }
**Error messages**
./node_modules/ajv/lib/ajv.ts:41:3
Type error: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.

  39 | 
  40 | export {
> 41 |   Format,
     |   ^
  42 |   FormatDefinition,
  43 |   AsyncFormatDefinition,
  44 |   KeywordDefinition,

**The output of `npm ls`**

The errors in fact is during the project build, but it cause of Nextjs dependency which sets the TS isolated modules to true during compilation all the time.

**Comment by jcamden** [comment]
Same problem here. We could try just renaming/splitting out the re-exported types in ajv.ts to use the keyword `export type { BlaBla }`, but I'm a little confused about why we're hitting ajv.ts anyway, instead of dist/ajv.js and dist/ajv.d.ts. Looking into that.

**Comment by jcamden** [comment]
Ah, okay: I was importing ajv types from `"ajv/lib/types"`. That URL came from vscode Intellisense, in my case. The lib directory is included in the release because it is listed under `files` in package.json. 

If we make sure to import from `"ajv"` instead, the entry points defined in the package.json will get us into dist. No error during the `Linting and checking validity of types...` stage of `next build` 😊

**Comment by dmkachko** [comment]
@jcamden You're right thanks a lot for pointing on that. 

import { ValidateFunction } from 'ajv';  // instead of ajv/lib/types

fixed the problem
