### ISSUE TITLE
$merge/$patch pre-processing keywords for schema extension

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#231]
Proposed by @fge

The reason to implement them is to allow to extend existing schemas (e.g. meta-schemas, but equally important for any large schema).

For non-recursive schemas `allOf`/`anyOf` keywords can be used, but for recursive schemas there is no extension mechanism.

https://github.com/daveclayton/json-schema-validator/wiki/v5:-merge
https://groups.google.com/forum/#!topic/json-schema/sztyQoNlnDM

@fge, syntax you propose is a bit ambiguous, it would be good to clarify and add to v5 proposals page.

**Comment by yyscamper** [comment]
+1,  I am also looking forward to this feature.  In my case, the `additionalProperties` doesn't work as my  expectation when I use the `allOf` to merge two-schemas, but `merge` can.

**Comment by epoberezkin** [comment]
For small/non-recursive schemas you own you can always refactor at least...

**Comment by epoberezkin** [comment]
See [$merge and $patch keywords](https://github.com/epoberezkin/ajv#merge-and-patch-keywords).
