### ISSUE TITLE
Nullable doesn't cover unions with null in it

### ISSUE THREAD

**Issue by SMJSProductions** [ajv-validator/ajv#2310]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`8.12.0`

**Your typescript code**

```typescript
export const UUID_PARAM: JSONSchemaType<{ uuid: string | null }> = {
    type: "object",
    additionalProperties: false,
    properties: {
        uuid: {
            nullable: true,
            type: "string",
            format: "uuid"
        }
    },
    required: [ "uuid" ]
};
```

**Typescript compiler error messages**

```
Type '{ type: "object"; additionalProperties: false; properties: { uuid: { nullable: true; type: "string"; format: string; }; }; required: "uuid"[]; }' is not assignable to type 'JSONSchemaType<{ uuid: string | null; }>'.
  The types of 'properties.uuid' are incompatible between these types.
    Type '{ nullable: true; type: "string"; format: string; }' is not assignable to type '{ $ref: string; } | ({ anyOf: readonly UncheckedJSONSchemaType<string | null, false>[]; } & { [keyword: string]: any; $id?: string | undefined; $ref?: string | undefined; $defs?: Record<...> | undefined; definitions?: Record<...> | undefined; } & { ...; }) | ({ ...; } & ... 1 more ... & { ...; }) | ({ ...; } & ... 2...'.
      Types of property 'nullable' are incompatible.
        Type 'true' is not assignable to type 'false'.
```

**Describe the change that should be made to address the issue?**

Nullable should cover unions which include null.

**Are you going to resolve the issue?**

I would love for this to be resolved but I don't have enough experience with the internals of AJV to solve this type error myself. I would prefer it if someone who maintains this library would take a look at this.

**Comment by oyamauchi** [comment]
I believe this is the same as: #1664

This is the workaround I'm using:

```typescript
type MyClass = {
  field: number | null;
}

const nullable = <T>(input: T): T => {
  return { anyOf: [input, { type: 'null' }] } as T;
};

const schema: JSONSchemaType<MyClass> = {
  // ...
  properties: {
    field: nullable({ type: 'number' })
  }
}
```

The `nullable` function adds the right element to the schema, so that the right thing happens in runtime validation, but hides it from tsc.

**Comment by SMJSProductions** [comment]
The story you mentioned isn't exactly the same. Also I get that you can trick TS into accepting the values, but my point is that null unions and nullable should be considered the same thing rather than being a type error (especially considering it doesn't handle unions properly in genera making it impossible to properly validate them without tricking TS).

**Comment by Renegade334** [comment]
Duplicate: #2163

**Comment by jasoniangreen** [comment]
Closing as it is a duplicate of #2163
