### ISSUE TITLE
strict mode fails to invalidate draft-07 schema with additional keywords alongside $ref

### ISSUE THREAD

**Issue by errodrigues** [ajv-validator/ajv#2321]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.11.0

**Ajv options object**

```javascript
const ajvOptions = {
    strict: true,
    validateFormats: false,
    discriminator: true,
    verbose: true,
    allErrors: true
};
```

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "security-x",
  "type": "object",
  "properties": {
    "replace": {
      "$ref": "replace.json",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "minProperties": 1
}
```

**Your code**

```javascript
const ajv = new Ajv(options);
registerAjvFormats(ajv);
require("ajv-errors")(ajv, {singleError: false} )
console.log(ajv.validateSchema(schema));
```

**Validation result, data AFTER validation, error messages**

```
true
```

**What results did you expect?**
My understanding is that on draft-07, no other keywords can appear alongside the **"$ref"** keyword, therefore my expectation is that validateSchema would return **false** for the example schema above.

**Comment by epoberezkin** [comment]
Might be confusing, but validateSchema simply validates schema, as data, against draft-07 meta-schema, it doesn't do any other checks.

Strict mode checks happen during schema compilation, so you need to "compile".

This docs say: "By default this method is called automatically when the schema is added, so you rarely need to use it directly."
