### ISSUE TITLE
Compiling JSON Schema generates code with Syntax Error: redeclaration of const schema1

### ISSUE THREAD

**Issue by robertpatrick** [ajv-validator/ajv#2334]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.12.0

**Ajv options object**
None

**JSON Schema**

Please see the attached schema.json.txt file (rename to schema.json).

**Sample data**

```json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "name": "mysql",
        "namespace": "mysql",
    },
    "spec": {
        "clusterIP": "10.96.58.31",
        "clusterIPs": [
            "10.96.58.31"
        ],
        "internalTrafficPolicy": "Cluster",
        "ipFamilies": [
            "IPv4"
        ],
        "ipFamilyPolicy": "SingleStack",
        "ports": [
            {
                "name": "mysql",
                "port": 3306,
                "protocol": "TCP",
                "targetPort": 6446
            },
            {
                "name": "mysqlx",
                "port": 33060,
                "protocol": "TCP",
                "targetPort": 6448
            },
            {
                "name": "mysql-alternate",
                "port": 6446,
                "protocol": "TCP",
                "targetPort": 6446
            },
            {
                "name": "mysqlx-alternate",
                "port": 6448,
                "protocol": "TCP",
                "targetPort": 6448
            },
            {
                "name": "mysql-ro",
                "port": 6447,
                "protocol": "TCP",
                "targetPort": 6447
            },
            {
                "name": "mysqlx-ro",
                "port": 6449,
                "protocol": "TCP",
                "targetPort": 6449
            }
        ],
        "selector": {
            "component": "mysqlrouter",
            "mysql.oracle.com/cluster": "mysql",
            "tier": "mysql"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
}

```

**Your code**

I have a Nuxt 3/Vue.js 3 app that is making a Rest API call to the server to get a generated JSON schema for Kubernetes resource types (e.g., a Service).  When I try to compile the attached generated schema (while it is still a JavaScript object--not a string), I see two errors in the browser Dev Tool console immediately after the stringified schema output.

1. `Error compiling schema, function code: ` - see attached file generated.js.txt file for the function code of the error.
2. `SyntaxError: redeclaration of const schema1` - see attached DevToolsScreenshot.png file for the call stack.

Note that I tried putting a try/catch block around the compile() function call but it did no good (i.e., no error was thrown).

```javascript
    const ajv = new Ajv();
    // The contents of the attached file schema.txt came from this output
    console.log(JSON.stringify(schemaObject, null, 2));
    const validate = ajv.compile(schemaObject);
```

**Validation result, data AFTER validation, error messages**

The compile step fails 

**What results did you expect?**

I expected the compile to succeed.

**Are you going to resolve the issue?**

I have tested the JSON schema in several online tools and it appears to be valid so I am not sure how to resolve this issue but I would like to get it resolved.  Please tell me what I am doing wrong.

[schema.json.txt](https://github.com/ajv-validator/ajv/files/12775006/schema.json.txt)
[generated.js.txt](https://github.com/ajv-validator/ajv/files/12775007/generated.js.txt)
![DevToolsScreenshot](https://github.com/ajv-validator/ajv/assets/31662131/25ce99df-6244-4418-979c-6dc79c5a8fc7)

**Comment by robertpatrick** [comment]
OK, I worked through a few issues with the schema, added `ajv-formats`, and now have standalone code running in Node.js successfully.  I am still not able to run successfully in a browser though...same errors.  What am I missing?

[schema.json.txt](https://github.com/ajv-validator/ajv/files/12777363/schema.json.txt)

**Comment by epoberezkin** [comment]
maybe generated code conflicts with some globals?

**Comment by jasoniangreen** [comment]
Your examples are very big and complicated, have you tried removing pieces, bit by bit to see at what point it stops breaking?

**Comment by robertpatrick** [comment]
@jasoniangreen no, I moved on without using this package.  I think the complexity is a matter of perspective.  If I have to start with a hello world example to debug this package, it’s simply not worth the effort.

**Comment by wagich** [comment]
For anyone who encounters this same error (as I did):

This seems to occur when the `Ajv` object was made into a reactive proxy by Vue 3. Probably because it was declared inside `data` when using the options API or when using ES6 classes and decorators (like vue-facing-decorator) where every class property automatically becomes reactive.

It seems that schema compilation code-gen (and who knows what else inside ajv) does interact badly with being proxified by Vue 3.
