### ISSUE TITLE
Can't make it work with OpenAPI

### ISSUE THREAD

**Issue by Garito** [ajv-validator/ajv#2347]
Hi
I'm trying to validate data from an openapi schema but I do not understand the logic or I'm missing something
Sorry if this is a dumb question
This is my code:
```javascript
const ajv = new Ajv({allErrors: true});
ajv.addSchema(openapi)
console.log(ajv.validate({ $ref: `#/components/schemas/${ schema }` }, JSON.parse(data)))
````
This is the error:
```
Uncaught Error: can't resolve reference #/components/schemas/Schema from id #
```
openapi is the json object version 3.0.2 generated by a fastapi backend
I want to validate data against the schema at #/components/schemas/Schema
What am I missing?
Thanks

**Comment by jeremyfiel** [comment]
https://stackoverflow.com/a/77520493/8564731

**Comment by Garito** [comment]
Thanks for that @jeremyfiel 
I'm following the example but raises:
```
Uncaught Error: reference "<schema>" resolves to more than one schema
```
when ```ajv.addSchema(openapi, 'openapi.json')``` but there are no duplicate schemas on that openapi (has been generated by fastapi)

**Comment by jeremyfiel** [comment]
post your code where it's having an error.  including the import statements or variables you have defined for `schema` and `openapi`

**Comment by Garito** [comment]
I'm sorry, writing this response i have noticed that two schemas have the same id so I correct that and test the openapi file with the swagger editor
But now it raises ```Uncaught Error: reference "properties" resolves to more than one schema``` which seems a little weird

The problem is that the error doesn't help too much

The line that fails is:
```javascript
ajv.addSchema(openapi, 'openapi.json')
```
so seems to be an openapi schema validation problem
Any clue as to how debug this issue besides the swagger editor? (the new version doesn't complain of any schema errors at all)

**Comment by jeremyfiel** [comment]
short of seeing the schemas, or your code, not much I can reference to help you

**Comment by jasoniangreen** [comment]
Closing as we are missing a reproducible issue there. Feel free to post a clean example with schemas and data example and I'll reopen.
