### ISSUE TITLE
Deprecation Warning: punycode Dependency via uri-js

### ISSUE THREAD

**Issue by camiloux** [ajv-validator/ajv#2350]
Version 8.12.0, Node 21.2.0, using npm.

Hi there,
I wanted to raise an issue regarding `uri-js` dependency, which uses `punycode` under the hood, which has been deprecated.

While working with ajv, I've noticed deprecation warnings related to the usage of the `punycode` module through its dependency on uri-js. It seems uri-js hasn't been updated for three years, causing these warnings.

├─┬ ajv@8.12.0
│ └─┬ uri-js@4.4.1
│   └── punycode@2.3.0

Just thought I'd bring this up for consideration. Thank you for your work on ajv!

**Comment by domdomegg** [comment]
I've opened a PR to fix this in uri-js, the package ajv depends on here: https://github.com/garycourt/uri-js/pull/95

**Comment by ThatOneCalculator** [comment]
Since `uri-js` seems to be unmaintained, maybe `ajv` should use a fork of `uri-js` (i.e. the repo maintained by domdomegg)

**Comment by kibertoad** [comment]
@ThatOneCalculator I've created a fork that addresses this problem: https://github.com/kibertoad/toad-uri-js

Happy to invite ajv folks to co-maintain if there is interest.

**Comment by ttodua** [comment]
any update on this? 
@kibertoad did you have any response from ajv devs?

**Comment by andreinwald** [comment]
Hi there,
I created a replacement for library uri-js as temporal solution.
- Based on Node.js and browser URL api
- 99% compatible with original URI.js library
- Solves "The punycode module is deprecated" warning in Node
- Tested with libraries: ESLint, Webpack, Ajv (runned all Ajv tests)

https://github.com/andreinwald/uri-js-replace

You can add to package.json of your project:
```json
"overrides": {
    "uri-js": "npm:uri-js-replace"
 }

**Comment by Niek** [comment]
@jasoniangreen Any chance to switch over the dependency to `uri-js-replace`?

**Comment by jasoniangreen** [comment]
Hi @Niek thanks for your suggestion but I think [this](https://github.com/ajv-validator/ajv/pull/2415) will be our most likely move. We already have fast-uri as a second option in the codebase/docs so it makes sense to switch it to be the default.

**Comment by jasoniangreen** [comment]
Closed as we are moving to fast-uri

**Comment by kibertoad** [comment]
@jasoniangreen fast-uri was reverted. What is the plan now?
