### ISSUE TITLE
How can I iterate over a JSON Schema using typescript?

### ISSUE THREAD

**Issue by johann1301s** [ajv-validator/ajv#2351]
I would like to implement a typescript function called `iterateAllOfJsonSchema`.

```ts
const iterateAllOfJsonSchema = (schema: GenericSchema) => {
  Object.entries(schema).reduce((acc, cur) => {
    if (cur.type === 'string') {  // <-- Can I get typescript intellisense here?
      // do stuff if string...
    } else if (cur.type === 'object') {
      // do stuff if object...
    }
   // ...etc
  })
}
```

Can I import a type similar to `GenericSchema` from Ajv? If not, where can I import it from? If it can't be imported, where can I begin to read the definitions so I can implement it myself? How do I make sure that the version of JSON Schema in the type `GenericSchema` is the same as the type exported from Ajv?

-----

I tried importing `JSONSchema7` from [json-schema](https://www.npmjs.com/package/json-schema). But how can I know that 7 is the correct version matching Ajv? And is this library official?

```
import {JSONSchema7} from 'json-schema'
```

-----

The ultimate goal is to create a React library, where I use the JSON Schema's of each component to show the `props` in a web view. Thus, I need to 'loop' over the JSON Schema.

**Comment by johann1301s** [comment]
I tried using `JSONSchemaType` from Ajv.

```ts
import {JSONSchemaType} from 'ajv'

const iterateAllOfJsonSchema = (schema: JSONSchemaType<any>) => {

    switch (schema.type) {
        case '': { // <--- type is any here?

        }
    }
}
```

Does not give type intellisense...

**Comment by jasoniangreen** [comment]
To get that example to work you need to pass in the json schema [meta schema](https://json-schema.org/draft-07/schema) into the JSONSchemaType. For example:

```
import Ajv, {JSONSchemaType} from 'ajv';
const ajv = new Ajv({ allErrors: true });

type Schema = JSONSchemaType<{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
    ... etc etc
```

From there I was able to use the `Schema` type and get intellisense.

<img width="325" alt="Screenshot 2024-06-22 at 09 59 09" src="https://github.com/ajv-validator/ajv/assets/3481367/d93d2cce-8cc7-4583-a88c-30598b552f15">

Beware, however, there are different versions of the metaschema available, but for your purposes I think any of them will be appropriate as you are only referencing standard props.
