### ISSUE TITLE
Error: strict mode: unknown keyword: "errorMessage"

### ISSUE THREAD

**Issue by brion-fuller** [ajv-validator/ajv#2361]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I am on version 8.12.0.  I believe this should be the latest version.  

**Ajv options object**

Default option: no custom params.

**JSON Schema**

```json
{
    title: "schema",
    $schema: "http://json-schema.org/draft-07/schema",
    type: "object",
    properties: {
      known: {
        type: "string",
      },
    },
    additionalProperties: {
      not: true,
      errorMessage: "extra property is ${0#}",
    },
  }
```

**Sample data**

```json
{
  "known": "test",
  "unknown": "test"
}
```

**Your code**

```javascript
const schema = {
    title: "schema",
    $schema: "http://json-schema.org/draft-07/schema",
    type: "object",
    properties: {
      known: {
        type: "string",
      },
    },
    additionalProperties: {
      not: true,
      errorMessage: "extra property is ${0#}",
    },
  };

  // Validate the schema
  const validator = new Ajv().compile(schema);
  const valid = validator({
  "known": "test",
  "unknown": "test"
});
  if (!valid) {
    log.error("Invalid schema:");
    log.error(validator.errors);
    throw new Error("Invalid schema");
  }
```

**Validation result, data AFTER validation, error messages**

```
Error: strict mode: unknown keyword: "errorMessage"
```

**What results did you expect?**

I should see this validate the json string and see the error message similar to this.
```
Error: strict mode: no additional properties extra property is `unknown`
```

**Are you going to resolve the issue?**

I haven't looked into this repo.  But if I get some direction to location of bug and I can look into it.

**Comment by epoberezkin** [comment]
it's a custom keyword defined in ajv-errors package

**Comment by arlan85** [comment]
I'm getting this same issue, how to solve this?

**Comment by ThamalDilanka** [comment]
@arlan85 `'errorMessage'` is a custom keyword introduced with the [ajv-errors package](https://ajv.js.org/packages/ajv-errors.html). You can simply add it to your AJV instance as follows. Ensure to include the option `allErrors: true` to enable its functionality.

```js
import Ajv from 'ajv';
import AjvErrors from 'ajv-errors';

// Ajv option allErrors must be true
const ajv = new Ajv({
  allErrors: true,
});

// This method call extends your JSON schema to utilize AJV Errors
AjvErrors(ajv);
```
