### ISSUE TITLE
default value not applied when using $ref

### ISSUE THREAD

**Issue by ilteoood** [ajv-validator/ajv#2364]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.12.0

**Reproduction**
https://codesandbox.io/p/sandbox/ajv-playground-forked-fhmgk2?file=%2Fsrc%2Findex.js%3A7%2C20

**What results did you expect?**
The same output as: https://codesandbox.io/p/sandbox/ajv-playground-forked-gc97mx?file=%2Fsrc%2Findex.js%3A15%2C7

**Are you going to resolve the issue?**
With some hints, I could try

**Comment by epoberezkin** [comment]
This is a documented limitation, not a bug: see https://ajv.js.org/guide/modifying-data.html#assigning-defaults

There is an option to fail schema compilation on ignored defaults (https://ajv.js.org/strict-mode.html#ignored-defaults)
