### ISSUE TITLE
Default export broken for typescript moduleResolution node16

### ISSUE THREAD

**Issue by apottere** [ajv-validator/ajv#2381]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.12.0

**Your code**
```json5
// tsconfig.json
{
    // ...
    "compilerOptions": {
        "module": "node16",
        "moduleResolution": "node16",
        // ...
    }
}
```

```typescript
import Ajv from 'ajv';

const ajv = new Ajv();
```

**What results did you expect?**
No TS error is thrown.

**Actual result:**
```
error TS2351: This expression is not constructable.
  Type 'typeof import("[project]/node_modules/.pnpm/ajv@8.12.0/node_modules/ajv/dist/ajv")' has no construct signatures.

6 const ajv = new Ajv();
                  ~~~
```

I saw https://github.com/ajv-validator/ajv/issues/2204, but it doesn't look like it was resolved in that issue.  This is an issue with how ajv exports its types: https://arethetypeswrong.github.io/?p=ajv%408.12.0

I can provide a reproduction in a sample project but it should be fairly easy to reproduce.

**Comment by jasoniangreen** [comment]
Hi there, thanks for raising this.

Do you think this can be replicated in https://runkit.com/ ? Or would it need to be in a project.

I am wondering though, given Node 16 had it's EOL brought forward by 7 months due to [potential vulnerabilities](https://nodejs.org/en/blog/announcements/nodejs16-eol), should we actually by dropping support for node 16?

**Comment by apottere** [comment]
I haven't used runkit before but I'll take a look.

The `node16` module resolution name is confusing.  It isn't the module resolution for node 16, it's the module resolution compatible with the changes _introduced in_ node 16.  Per the [docs](https://www.typescriptlang.org/tsconfig#moduleResolution):
> 'node16' or 'nodenext' for modern versions of Node.js. Node.js v12 and later supports both ECMAScript imports and CommonJS require, which resolve using different algorithms. These moduleResolution values, when combined with the corresponding [module](https://www.typescriptlang.org/tsconfig#module) values, picks the right algorithm for each resolution based on whether Node.js will see an import or require in the output JavaScript code.

As of now, `node16` is the most up-to-date value for `moduleResolution` (not including `bundler` of course).

**Comment by apottere** [comment]
It looks like there's no way to fiddle with builds in runkit, so I create a minimal reproduction here: https://github.com/apottere/ajv-typescript-node16

**Comment by jasoniangreen** [comment]
I see, I will take a look, thanks.

**Comment by yernandus** [comment]
any updates on this?

**Comment by benasher44** [comment]
This should be fixed by #2365. Can you try `@benasher44/ajv`? I published that PR there

**Comment by apottere** [comment]
Looks good in https://arethetypeswrong.github.io/?p=%40benasher44%2Fajv%408.12.1 and seems to resolve the issue in my reproduction 👍

**Comment by jasoniangreen** [comment]
Interesting tool @apottere, it does indeed look all green.

<img width="440" alt="Screenshot 2024-02-28 at 21 01 07" src="https://github.com/ajv-validator/ajv/assets/3481367/9e178007-eb3a-4867-b609-fd551b78c97a">

This is compared with what we currently have
<img width="804" alt="Screenshot 2024-02-28 at 21 03 33" src="https://github.com/ajv-validator/ajv/assets/3481367/f0c7ce55-1273-4616-b490-5f58ffd7b8a8">

I'll just check it out a bit more, but looking good 👍

**Comment by jomaa-daniel** [comment]
When can we expect the fix to be in? Thanks

**Comment by StormeHawke** [comment]
Also seeing this same issue in my code. 
The error I'm seeing is in resolve.ts, the following two imports:
```
import * as equal from "fast-deep-equal"
import * as traverse from "json-schema-traverse"
```
can be minimally rewritten as 
```
import equal from "fast-deep-equal"
import traverse from "json-schema-traverse"
```
to get it to compile (though I haven't tested if it actually works that way). 

Right now I'm having to manually copy a significant amount of code from one of our internal libraries into another project because the node16 module resolution features are broken by this issue

**Comment by jasoniangreen** [comment]
Can you try the new version `v8.13.0`?

**Comment by leppaott** [comment]
@jasoniangreen same issue with that and `8.17.1`?
