### ISSUE TITLE
Documentation dead links

### ISSUE THREAD

**Issue by jauntyjocularjay** [ajv-validator/ajv#2387]
These links in the documentation readme.md are dead:

- [ajv-formats](https://github.com/ajv-validator/ajv/blob/master/docs/packages/ajv-formats.md) - formats defined in JSON Schema specification
- [ajv-keywords](https://github.com/ajv-validator/ajv/blob/master/docs/packages/ajv-keywords) - additional validation keywords (select, typeof, etc.)
- [ajv-errors](https://github.com/ajv-validator/ajv/blob/master/docs/packages/ajv-errors.md) - defining error messages in the schema
- [ajv-i18n](https://github.com/ajv-validator/ajv/blob/master/docs/packages/ajv-i18n) - internationalised error messages
- [ajv-cli](https://github.com/ajv-validator/ajv/blob/master/docs/packages/ajv-cli.md) - command line interface

Looks like this one was moved to the parent folder and renamed. Easy fix.

[ajv-keywords](https://github.com/ajv-validator/ajv/blob/master/docs/keywords.md) - additional validation keywords (select, typeof, etc.)

**Comment by jasoniangreen** [comment]
Thanks for pointing these out, I will take a look.
