### ISSUE TITLE
Toss a Warning instead of throwing an error when adding a keyword

### ISSUE THREAD

**Issue by jauntyjocularjay** [ajv-validator/ajv#2388]
**What version of Ajv you are you using?**
8.12.0

**What problem do you want to solve?**

When attempting to test the same piece of data as part of multiple tests in unit testing, throwing an error and refusing to continue until the tester renames the keys every time one wants to test the same data. 

**What do you think is the correct solution to problem?**

TL:DR = Toss a warning instead of throwing an error.

Adding the same '{key:value}' pair to an object as part of `addKeyword` seem drastic. If the keyword is removed in one place (ie. key: false) and then added to be used again (ie. key: true). I may not understand why this precaution is being taken, I searched for an answer but could not find one.

**Will you be able to implement it?**

Unless there are reasons not to.

`node_modules/ajv/dist/core.js`

`line 525`

```
const KEYWORD_NAME = /^[a-z_$][a-z0-9_$:-]*$/i;
function checkKeyword(keyword, def) {
    const { RULES } = this;
    (0, util_1.eachItem)(keyword, (kwd) => {
        if (RULES.keywords[kwd])
            this.logger.warn(`Keyword ${kwd} is already defined`); // A warning rather than an error
        if (!KEYWORD_NAME.test(kwd))
            throw new Error(`Keyword ${kwd} has invalid name`);
    });
    if (!def)
        return;
    if (def.$data && !("code" in def || "validate" in def)) {
        throw new Error('$data keyword must have "code" or "validate" function');
    }
}
```

**Comment by jasoniangreen** [comment]
Apologies but I am not sure I understand the problem here. Can you provide some example code of the issue on https://runkit.com ?

**Comment by jauntyjocularjay** [comment]
Hi Jason.

I was stuck on this for several days before I solved the issue. Now I am having trouble reproducing the issue. This is frustrating. Can you close this issue and I will reopen it if I run into it again?

**Comment by jauntyjocularjay** [comment]
Looks like I can

**Comment by jauntyjocularjay** [comment]
Okay got it. Here is the [Runkit link](https://runkit.com/georgeschafer/ajvkeyword).

So the reason this is a problem is that I have an algorithm that automatically combs through the schema and picks out keywords. If I have a keyword (like `id`) that is pre-defined, I will have to add additional logic to exclude keywords already built into Ajv when I am telling AJV to look for a keyword it already looks for. I am not telling it to make a change to what it already does, just that I want to make sure it is included as a keyword.

As a workaround, I tell my code to take all the keywords that are in my schema, take them out of AJV, so I can put them back in and then take them out again at the end of the test.

This is truncated as I have the function encapsulated in another library. You can find the function [here](https://github.com/GeorgeSchafer/ChaiFunctions/blob/release/SchemaJS.ext.mjs) named: `schemaCorresponds`.

```javascript
function schemaCorresponds(subject, alias, target, bool=true){
    const description = getCounter() + alias + does(bool) + `correspond to response`

    const correspondsTo = () => {
        it(description, () => {
            const ajv = new Ajv()
            let validate
            let valid

            decompileKeywords(ajv, target) // Remove any keywords AJV already knows
            compileKeywords(ajv, target) // Comb through the target schema and add the keywords

            validate = ajv.compile(target)

            valid = validate(subject)

            bool
                ? expect(valid).to.be.true
                : expect(valid).to.be.false
            
            if (!valid && bool) {console.log(validate.errors)}

            decompileKeywords(ajv, target) // Remove the keywords I added to AJV
        })
        count()
    }
    correspondsTo()
}
```

Please let me know this makes sense. I am still a pretty fresh, self taught coder. There is a lot I still have to learn.

**Comment by jasoniangreen** [comment]
Thanks for the example, that makes it much easier to understand what you are talking about. Unfortunately I would say this is something we would definitely not want to change. With a library like AJV that is used by millions, the fact that it throws in any given situation is something that possible thousands could be relying upon within their code. We are also against adding options for things like this, it may seem low cost to add an option to configure it not to throw, but but every option adds complexity and increases the overall footprint of the code.

Question though, why can't you try catch the `addKeyword` call if what you preferred was that it just warned?

**Comment by jauntyjocularjay** [comment]
Good point. Even small changes have big ramifications at scale. 

That's a good idea, I didn't think of that. Thanks!
