### ISSUE TITLE
JSONSchemaType $ref doesn't work in array type.

### ISSUE THREAD

**Issue by ghost** [ajv-validator/ajv#2392]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v8.12.0
**Your typescript code**

```
import Ajv, { JSONSchemaType } from "ajv";

interface TypeA {
  valueA: TypeB[];
}

interface TypeB {
  valueB: string;
}

const SchemaA1: JSONSchemaType<TypeA> = {
  type: "object",
  required: ["valueA"],
  properties: {
    valueA: {
      type: "array",
      items: {
        $ref: "#/definitions/TypeB",
      },
    },
  },
  definitions: {
    TypeB: {
      type: "object",
      required: ["valueB"],
      properties: {
        valueB: {
          type: "string",
        },
      },
    },
  },
};
```

When I use `$ref` in array type, errors will occur.
After that, I looked at issues below and tried to change it, but it didn't work.

[JSONSchemaType does not work when $ref is used #1638](https://github.com/ajv-validator/ajv/issues/1638)
[The type definition of $ref not correctly resolve #1845](https://github.com/ajv-validator/ajv/issues/1845)

```
const SchemaA2: JSONSchemaType<TypeA> & {
  definitions: {
    TypeB: JSONSchemaType<TypeB>;
  };
} = {
  type: "object",
  required: ["valueA"],
  properties: {
    valueA: {
      type: "array",
      items: {
        $ref: "#/definitions/TypeB",
      },
    },
  },
  definitions: {
    TypeB: {
      type: "object",
      required: ["valueB"],
      properties: {
        valueB: {
          type: "string",
        },
      },
    },
  },
};
```

**Describe the change that should be made to address the issue?**
How can I compile and reference correctly in array type?

**Are you going to resolve the issue?**
No.

**Comment by GabenGar** [comment]
I don't see any types casts as per example in [this post](https://github.com/ajv-validator/ajv/issues/1845#issuecomment-995296579).

**Comment by jasoniangreen** [comment]
Thanks for sharing @GabenGar, yes I think the best bet to work around this issue is to cast the ref object to `any`. For example:

```
const SchemaA1: JSONSchemaType<TypeA> = {
  type: "object",
  required: ["valueA"],
  properties: {
    valueA: {
      type: "array",
      items: ({
        $ref: "#/definitions/TypeB",
      } as any),
    },
  },
  // etc etc
};
```

It could be there is a simple fix for this, and we welcome any PRs. I might be able to look into it later, but for now am focussed on updating deps and getting a new release ready.

**Comment by ghost** [comment]
Thanks a lot!

**Comment by CalebMacdonaldBlack** [comment]
@jasoniangreen Can we reopen this issue please?

 Using any is not ideal, i can expand on why if needed.

**Comment by GabenGar** [comment]
There is nothing to expand, `"$ref"` resolution can go as bad as an async request. Therefore it's impossible to infer on the level of typescript compiler. At scale you will need to have a codegen pipeline which would generate typescript interfaces off schema files using something like [`json-schema-to-typescript`](https://github.com/bcherny/json-schema-to-typescript).

**Comment by CalebMacdonaldBlack** [comment]
@GabenGar Ah okay. Thanks, makes sense.
