### ISSUE TITLE
JTD schema parser errors on empty properties field

### ISSUE THREAD

**Issue by brian-statsig** [ajv-validator/ajv#2399]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
latest version

**Ajv options object**
no options

**JSON Schema**

```json
{ "properties": {} }
```

**Validation result, data AFTER validation, error messages**

```
TypeError: Reduce of empty array with no initial value
```

**Code**

```javascript
  const ajv = new Ajv();
ajv.compileParser({ properties: {} });
```

**What results did you expect?**
A compiled schema that passes nothing or everything. I think more graceful handling would be nice

**Comment by jasoniangreen** [comment]
If you want to validate JSON Type Definition schemas you need to invoke Ajv differently ([see top of page](https://ajv.js.org/json-type-definition.html#properties-form)). 

```
import Ajv from "ajv/dist/jtd"
const ajv = new Ajv()
```
