### ISSUE TITLE
Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by shenxxu720** [ajv-validator/ajv#2413]
When using the electron-store plug-in (https://github.com/sindresorhus/electron-store), it prompts Cannot find module 'ajv/dist/compile/codegen'. What is the problem?

**Comment by harit-basant-sharma-db** [comment]
Even we are facing similar issues.

`Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- C:\Users\sharharb\Harit\UI\eos-pulse-ui\node_modules\ajv-keywords\dist\definitions\typeof.js`

**Comment by epoberezkin** [comment]
if you are using ajv via electron-store, rather than directly, please report the issue to them - otherwise please post a minimal code sample to reproduce.

**Comment by jasoniangreen** [comment]
Hi all, please post a minimal example we can use. If at all possible using this [runkit template](https://runkit.com/esp/ajv-issue) is best for us to investigate, but I understand some issues might need a simple repo.

**Comment by jasoniangreen** [comment]
Closing for now. Feel free to open if you can repro with AJV on it's own or if the maintainers of electron-store track the problem down to AJV.
