### ISSUE TITLE
How can I make a property value depend on the value of another property?

### ISSUE THREAD

**Issue by bertolo1988** [ajv-validator/ajv#2414]
Using [ajv](https://ajv.js.org/) is it possible to get a validation error if minPrice is bigger than maxPrice in this schema?

```JSON
{
  "type": "object",
  "properties": {
    "minPrice": {
      "type": "number"
    },
    "maxPrice": {
      "type": "number"
    }
  }
}
```

**Comment by jasoniangreen** [comment]
I think you can look into the `$data` keyword. It allows you to refer to the actual validated values of other parts of the data in your validation rules.

https://ajv.js.org/guide/combining-schemas.html#data-reference
