### ISSUE TITLE
Integers as Discriminators

### ISSUE THREAD

**Issue by b-wils** [ajv-validator/ajv#2419]
**What version of Ajv you are you using?**

8.12.0

**What problem do you want to solve?**

I have an existing schema where I'm trying to use it's integer properties as discriminators. 

It seems that ajv discriminators only allow integers. I'm not sure if this is an [implementation](https://github.com/ajv-validator/ajv/blob/5370b842a92158454cf56de907894223bc5537ef/lib/vocabularies/discriminator/index.ts#L102) limitation or something defined by the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#discriminator-object).

**What do you think is the correct solution to problem?**

Update the discriminator to allow integers. Ideally the integer can just be converted to a string for the map lookup.

**Will you be able to implement it?**

Possibly

**Comment by jasoniangreen** [comment]
Hi there, could you put together a [runkit](https://runkit.com/esp/ajv-issue) exhibiting the issue? Try and keep the example as simple as possible.

**Comment by b-wils** [comment]
https://runkit.com/b-wils/ajv-number-discriminator

**Comment by jasoniangreen** [comment]
Judging by the example here https://ajv.js.org/json-schema.html#discriminator your schema is not quite right.

Looks like you are missing `propertyName` in `discriminator: {propertyName: "foo"}`.

**Comment by b-wils** [comment]
Ah yes, my apologies. https://runkit.com/b-wils/ajv-number-discriminator is updated with the correct discriminator declaration and now should demonstrate the issue with numbers as discriminators.

**Comment by jasoniangreen** [comment]
Thanks for that. So after reviewing things I can see that it is indeed a deliberate restriction and there was actually [a PR a while back](https://github.com/ajv-validator/ajv/pull/1729) to add support for other scalar data types.

I am just in the process of preparing a release (the first in a long time) but I can look into this afterwards and follow up with @epoberezkin.

**Comment by jasoniangreen** [comment]
Hi @b-wils, I have spoken to EP and this is not a change we're open to exploring at this time. I don't have all the context but there are reasons it should be a string and my interpretation of the spec is that it should be a string too. It should be pretty trivial to work around too.

**Comment by b-wils** [comment]
Thanks for looking into it, if this is isn't part of the spec then that makes sense to not extend it in ajv.

By workaround, you mean change the fields from numbers to strings? Unfortunately our data is already in use and won't be feasible to change existing users. Replacing `oneOf` with `if/then` is a (slightly awkward) workaround to reduce error noise, or we may just live with the noise.
