### ISSUE TITLE
DeprecationWarning: The punycode module is deprecated #96

### ISSUE THREAD

**Issue by tianyingchun** [ajv-validator/ajv#2422]
(node:29131) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Can we update the module to replace "punycode"?

it seem that https://github.com/garycourt/uri-js/issues/96 is dead, the Creator and maintainer haven't updated it for last 3 years.

can we update this using. https://github.com/andreinwald/uri-js-replace

**Comment by tianyingchun** [comment]
https://github.com/ajv-validator/ajv/issues/2422

**Comment by andreinwald** [comment]
#2343
