### ISSUE TITLE
compileAsync does not loadSchema a schema that is $ref’d by a oneOf with a discriminator

### ISSUE THREAD

**Issue by yonran** [ajv-validator/ajv#2427]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

latest (8.13.0)

**Ajv options object**

```javascript
const options = {
  discriminator: true,
  async loadSchema(url) {
    console.log('loadSchema', url)
    const name = url.substring("scheme://".length)
    return schemas[name]
  },
};
```

**JSON Schema**

```js
const schemas = {
  main: {
    type: "object",
    discriminator: {propertyName: "foo"},
    required: ["foo"],
    oneOf: [
      {
        $ref: "scheme://schema1",
      },
      {
        $ref: "scheme://schema2",
      },
    ],
  },
  schema1: {
    type: "object",
    properties: {
      foo: {const: "x"},
    },
  },
  schema2: {
    type: "object",
    properties: {
      foo: {enum: ["y", "z"]},
    },
  },
};
```

**Sample data**

```json
{"foo": "x"}
```

**Your code**

```javascript
const Ajv = require("ajv");
const ajv = new Ajv(options);
// If you uncomment this, then there is no error
// Object.entries(schemas).forEach(([id, schema]) => {
//   ajv.addSchema(schema, 'scheme://' + id)
// })
async function main() {
  const validate = await ajv.compileAsync(schemas.main)
  validate(data)
}
main().catch((err) => console.log(err))
```

**Validation result, data AFTER validation, error messages**

```
Error: discriminator: oneOf subschemas (or referenced schemas) must have "properties/foo"
```

**What results did you expect?**
No error

**Are you going to resolve the issue?**
Maybe if it is easy

Notes:
* If you call `ajv.addSchema` (i.e., uncomment the commented code), then the error goes away. Therefore, it is the resolving of the `$ref` that is the issue
* When `discriminator: true`, then `loadSchema` is **not** called.
* But if you set `discriminator: false` and remove the `discriminator` from `schema.main`, then `loadSchema` **is** called.

  ```
  loadSchema scheme://schema1
  loadSchema scheme://schema2
  ```

My guess is that lib/vocabularies/discriminator/index.ts’s `getMapping()` needs to `throw new MissingRefError` so that _compileAsync can catch the error and load the missing schemas.

**Comment by jasoniangreen** [comment]
Hi @yonran thanks for raising this, I have setup your example and it does look like it could be a bug. Since you responded "Maybe if it is easy" I'll ask if you would like to have a go at submitting a PR? Either way I will look into this and consider it a bug for now.

**Comment by mathieubathalon** [comment]
lib/commands/query.js

**Comment by mathieubathalon** [comment]
``
