### ISSUE TITLE
How to return error when the vlaue of field is '' and set the field as required

### ISSUE THREAD

**Issue by nick121212** [ajv-validator/ajv#2430]
**What version of Ajv you are you using?**

latest

**What problem do you want to solve?**

`const schema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      minLength: 1,
    },
  },
  required: ['name'],
}`

`
const valid = ajv.compile(schmea)({name:''});

// valid is true

// Can i get required error when name is ''?

`

**What do you think is the correct solution to problem?**

can we add some option to change the behavior?

**Will you be able to implement it?**

**Comment by jasoniangreen** [comment]
Hi @nick121212, can you replicate this in Runkit (you can clone this https://runkit.com/esp/ajv-issue)?

I tried running this locally and it works as expected, i.e. valid is false for an empty string.

**Comment by jasoniangreen** [comment]
Closing as I have been unable to repro. Happy to reopen if you can provide a runkit link demonstrating the issue.
