### ISSUE TITLE
Using with "numeric" type

### ISSUE THREAD

**Issue by suricactus** [ajv-validator/ajv#244]
Hello. I need to validate data of type "numeric" a.k.a. decimal or string of digits (see numeric type in postgresql). In schema v5 there is `formatMinimum` and `formatMaximum`, but it does not support "numeric" type. Using `parseFloat` in js is not an option, because you know the result of 0.1+0.2. Any suggestions?

**Comment by epoberezkin** [comment]
You can define custom format "numeric" - it can have functions for both validation and for comparisons: https://github.com/epoberezkin/ajv#addformatstring-name-stringregexpfunctionobject-format

**Comment by suricactus** [comment]
It would be nice if we have something like this by default, I think. Thank you!
