### ISSUE TITLE
8.15 requires fast-uri, which requires `node:url`, which makes it not bundelable for the web

### ISSUE THREAD

**Issue by retorquere** [ajv-validator/ajv#2446]
**edit: please stop posting "+1". The team is on it, the problem is reproducible, you're not adding useful information by posting "+1", and everyone in the thread is getting spurious mail updates**.

If you are commenting because you want updates, see the big "subscribe" button to the right. If you want to mark yourself as affected, click the counting emoji below this post.

---

**The version of Ajv you are using**
8.15.0

**The environment you have the problem with**
esbuild, targeted to Firefox (but I believe this will be a problem for all browsers)

**Your code (please make it as small as possible to reproduce the issue)**
```
import AJV from 'ajv'
```

**Results in node.js v8+**
this works, because `node:url` is a native node module

**Comment by arvinxx** [comment]
we meet the same problem, I have to pin to `8.14.0` now

**Comment by godky** [comment]
There are also compatibility issues with earlier versions of node.

**Comment by hanzebang** [comment]
> we meet the same problem, I have to pin to `8.14.0` now

+1

**Comment by FFFFourwood** [comment]
+1

**Comment by BroKun** [comment]
+1

**Comment by serializedowen** [comment]
+10086

**Comment by xiaojiezj** [comment]
+1

**Comment by CrazyWood007** [comment]
+1

**Comment by yhz1992** [comment]
+1

**Comment by Ricklzy** [comment]
+1,we meet the same problem 
![Uploading Snipaste_2024-06-04_15-27-39.png…]()

**Comment by Ricklzy** [comment]
+1,We found the same problem with nx
![Snipaste_2024-06-04_15-27-39](https://github.com/ajv-validator/ajv/assets/107994784/eb58b19b-e9d1-4764-83bd-04d2c0df2dfe)
The node environment is 14.17.5

**Comment by retorquere** [comment]
If you also experience this problem, please click the thumbs-up emoji on the top comment instead of adding a note with "+1". The emoji counts automatically, and by posting "+1", everyone who commented earlier (including me) gets a mail notification.

**Comment by jasoniangreen** [comment]
Yep, we’re onto it. Please pin until we get a fix out asap.

**Comment by jasoniangreen** [comment]
> There are also compatibility issues with earlier versions of node.

Can you provide more detail?

**Comment by Ricklzy** [comment]
> > There are also compatibility issues with earlier versions of node.
> 
> Can you provide more detail?

Our project uses @nx/webpack, but @nx/webpack relies on schema-utils, and schema-utils ends up using ajv

**Comment by justmywyw** [comment]
+1

**Comment by jled7** [comment]
+1

**Comment by rupeesdev** [comment]
There are a lot of dependencies that uses ajv with an unpinned version. This is a breaking change in lower versions of node. Could you please rollback? Thanks in advance for the good work 😄

**Comment by alexander-schranz** [comment]
All who are unsure how to downgrade to a previous minor version as a temporary workaround you can run:

```bash
npm install "ajv@8.14.*" --save
```

and should get then the previous version which does not require the fast-uri package.

**Comment by errodrigues** [comment]
+1
Btw, 8.15.0 also broke several JSON schema validations with errors like: `can't resolve reference #/properties/replace/properties/values/patternProperties/.%2B/allOf/0 from id http://foo.bar/json-schemas/myschema`

Same exact JSON files validate just fine against exact same JSON schemas using Ajv 8.14.0

**Comment by joshkel** [comment]
@errodrigues, I opened that as a separate issue (#2447) to not clutter this discussion.

**Comment by kujtimprenku** [comment]
> +1 Btw, 8.15.0 also broke several JSON schema validations with errors like: `can't resolve reference #/properties/replace/properties/values/patternProperties/.%2B/allOf/0 from id http://foo.bar/json-schemas/myschema`
> 
> Same exact JSON files validate just fine against exact same JSON schemas using Ajv 8.14.0

As a workaround maybe you can override the version of `ajv` in `package.json` for the validator package such as:

```json
"overrides": {
    "@the-validator-package": {
        "ajv": "8.14.0"
    }
},
```

**Comment by jdimmerman** [comment]
@kujtimprenku I'm running into some trouble (which I can of course share) with doing the same via yarn resolutions. Any advice you might have? The resolution is being installed (ajv@8.14.0), but the original version's dependencies are also being installed, including fast-uri.

**Comment by jasoniangreen** [comment]
Reverting now. New version will be 8.16.0 and will set everything back to how it was in 8.14.0. Sorry for the disruption.

**Comment by jasoniangreen** [comment]
Reverted in v8.16.0
