### ISSUE TITLE
Cannot get sub-schema validation to work

### ISSUE THREAD

**Issue by mikesnare** [ajv-validator/ajv#2451]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

8.16.0 (latest)

**Your code**

Link to runkit: https://runkit.com/mikesnare/ajv-issue

```javascript
var Ajv = require('ajv');

ajv = new Ajv({
    // options here
});

var schema = {
  '$id': 'https://whatever.com/simple-schema',
  type: "object",
  additionalProperties: false,
  definitions: {
    CustomType: { enum: [ 'one', 'two' ], type: 'string' },
    SimpleType: {
      additionalProperties: false,
      properties: {
        id: { type: 'number' },
        custom_type: { '$ref': '#/definitions/CustomType' }
      },
      required: [ 'id' ],
      type: 'object'
    }
  }
};

var data = {
    what: 'ever',
};

ajv.addSchema(schema);
const validate = ajv.getSchema('https://whatever.com/simple-schema#definitions/SimpleType')

console.log(validate(data));
console.log(validate.errors);

```

**Validation result, data AFTER validation, error messages**

There is no validation result, because no validation function is returned.  It simply fails.

**What results did you expect?**

I expected ajv to find the correct validator based on the given path.

**Are you going to resolve the issue?**

I don't know how to answer this question.

**Comment by mikesnare** [comment]
According to [this](https://github.com/ajv-validator/ajv/issues/1009#issuecomment-596927293) (admittedly old) comment, it should be possible using the code above.

**Comment by jasoniangreen** [comment]
Sorry @mikesnare, but I have been unable to find any docs that indicate this is expected functionality. As far as I can tell this just isn't how `getSchema` works. At least it isn't anymore if it ever was.

**Comment by jasoniangreen** [comment]
I managed to get this to work by explicitly giving an `$id` to your subschema, which seems a perfectly reasonable solution.

```
SimpleType: {
      '$id': 'https://whatever.com/simple-schema#definitions/SimpleType',
      additionalProperties: false,
      properties: {
        id: { type: 'number' },
        custom_type: { '$ref': '#/definitions/CustomType' }
      },
      required: [ 'id' ],
      type: 'object'
    }
```

Note it doesn't need to be the same format as the root schema.

**Comment by mikesnare** [comment]
@jasoniangreen Nice.  The tool I'm using to generate the schema from TS doesn't add that, but it should be pretty easy to add it myself at runtime.  Thanks!
