### ISSUE TITLE
Error: Cannot find module 'ajv/dist/core'

### ISSUE THREAD

**Issue by alexandrebodin** [ajv-validator/ajv#2452]
Our app started to fail when dependencies are installed by npm (works with yarn & pnpm) 

```
Error: Cannot find module 'ajv/dist/core'
Require stack:
Require stack:
- /project/node_modules/ajv-draft-04/dist/index.js
- /project/node_modules/@rushstack/node-core-library/lib/JsonSchema.js
- /project/node_modules/@rushstack/node-core-library/lib/index.js
- /project/node_modules/@rushstack/terminal/lib/NormalizeNewlinesTextRewriter.js
- /project/node_modules/@rushstack/terminal/lib/index.js
- /project/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js
- /project/node_modules/@rushstack/ts-command-line/lib/providers/ScopedCommandLineAction.js
- /project/node_modules/@rushstack/ts-command-line/lib/index.js
- /project/node_modules/umzug/lib/cli.js
- /project/node_modules/umzug/lib/umzug.js
- /project/node_modules/umzug/lib/index.js
```

I tried installing the dependencies with --force & --legacy-peer-deps with no success. 

```
  ├─┬ project
  │ └─┬ umzug@3.2.1
  │   └─┬ @rushstack/ts-command-line@4.22.0
  │     └─┬ @rushstack/terminal@0.13.0
  │       └─┬ @rushstack/node-core-library@5.4.1
  │         ├─┬ ajv-draft-04@1.0.0
  │         │ └── ajv@6.12.6 deduped invalid: "^8.5.0" from node_modules/ajv-draft-04
  │         ├─┬ ajv-formats@3.0.1
  │         │ └── ajv@8.16.0
  │         └── ajv@8.13.0
 
```

it seems that ajv-draft-04 has an invalid peer dep config (or npm doesn't know what to do with it ?) that resolves to and old version of ajv instead of the right one. 

Let me know if I can provide more information :)

**Comment by jasoniangreen** [comment]
Hmm, if it works with yarn and pnpm maybe you should try posting on [npm issues](https://github.com/npm/cli/issues). We haven't made any changes recently that touched peer dependencies or ajv-draft-04.

**Comment by alexandrebodin** [comment]
Will investigate ty

**Comment by reslear** [comment]
same fixed for v4 is install `npm i ajv`

**Comment by Maxttier** [comment]
@alexandrebodin @jasoniangreen not work with bun

I run `bun mikro-orm migration:create --initial` and `bun -b mikro-orm migration:create --initial`

>  Cannot find module 'ajv/dist/core' from

**Comment by berdev80381** [comment]
npm install ajv@latest ajv-keywords@latest
solved it for me

**Comment by ianzone** [comment]
`bun` has the same issue, it's due to `ajv` being marked optional in `peerDependenciesMeta` in `ajv-draft-04`. https://github.com/ajv-validator/ajv-draft-04/issues/10

**Comment by ZzyzxIsAlreadyTaken** [comment]
Im having the same issue and have had it for a while. Im on Mac using homebrew and nvm.

I need to install ajv on each SPFX project. 
I also have to install PostCSS 8.

`kjetil@Mac fieldCustomizers % gulp serve --nobrowser
Error: Cannot find module 'ajv/dist/core'
Require stack:
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/ajv-draft-04/dist/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/node_modules/@rushstack/node-core-library/lib/JsonSchema.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/node_modules/@rushstack/node-core-library/lib/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/dist/rush-lib.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/lib/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/spfx-heft-plugins/lib-commonjs/plugins/devDeployPlugin/SpDevDeploy.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/spfx-heft-plugins/lib-commonjs/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-core-tasks/lib-commonjs/webpack/ConfigureWebpackTask.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-core-tasks/lib-commonjs/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-web/lib-commonjs/index.js
- /Users/kjetil/Dev/sharepoint/fieldCustomizers/gulpfile.js
- /opt/homebrew/lib/node_modules/gulp-cli/lib/shared/require-or-import.js
- /opt/homebrew/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /opt/homebrew/lib/node_modules/gulp-cli/index.js
- /opt/homebrew/lib/node_modules/gulp-cli/bin/gulp.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/ajv-draft-04/dist/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/ajv-draft-04/dist/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/node_modules/@rushstack/node-core-library/lib/JsonSchema.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/node_modules/@rushstack/node-core-library/lib/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/dist/rush-lib.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/rush-lib/lib/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/spfx-heft-plugins/lib-commonjs/plugins/devDeployPlugin/SpDevDeploy.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/spfx-heft-plugins/lib-commonjs/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-core-tasks/lib-commonjs/webpack/ConfigureWebpackTask.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-core-tasks/lib-commonjs/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/node_modules/@microsoft/sp-build-web/lib-commonjs/index.js',
    '/Users/kjetil/Dev/sharepoint/fieldCustomizers/gulpfile.js',
    '/opt/homebrew/lib/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/opt/homebrew/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/opt/homebrew/lib/node_modules/gulp-cli/index.js',
    '/opt/homebrew/lib/node_modules/gulp-cli/bin/gulp.js'
  ]
}`
