### ISSUE TITLE
Replace fast-deep-equal with dequal

### ISSUE THREAD

**Issue by rtritto** [ajv-validator/ajv#2466]
**What version of Ajv you are you using?**
8.16.0

**What problem do you want to solve?**
`dequal` is faster than `fast-deep-equal`: [benchmarks](https://github.com/lukeed/dequal?tab=readme-ov-file#benchmarks)

**What do you think is the correct solution to problem?**
```diff
-import deepEqual from 'fast-deep-equal'
+import { dequal } from 'dequal/lite'
```

**Will you be able to implement it?**
No

**Comment by jasoniangreen** [comment]
I spoke with the author and we're not interested in this at this time.
