### ISSUE TITLE
RE2 integration incorrectly typed

### ISSUE THREAD

**Issue by ramijarrar** [ajv-validator/ajv#2476]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Yes - issue happens with the latest version (currently v8.17.1).

**Your typescript code**

```typescript

import RE2 from "re2";
import Ajv from "ajv";

const ajv = new Ajv({
  code: { regExp: RE2 },
});

```

**Typescript compiler error messages**

```
Property 'code' is missing in type 'RE2Constructor' but required in type 'RegExpEngine'.  ts(2741)
```

**Describe the change that should be made to address the issue?**

The code property should potentially be marked as optional in the RegExpEngine interface since it is ["only needed for standalone code generation"](https://github.com/ajv-validator/ajv/pull/1684#discussion_r747459311): https://github.com/ajv-validator/ajv/blob/9050ba1359fb87cd7c143f3c79513ea7624ea443/lib/types/index.ts#L233

**Are you going to resolve the issue?**

Happy to submit a PR if that is desired.

**Comment by jasoniangreen** [comment]
Hi @ramijarrar it does indeed look like a typescript issue as the js version of this same code runs fine. I'm happy for you to submit and PR and I'll try and get @epoberezkin opinion on it.

**Comment by jasoniangreen** [comment]
After discussing with the author @ramijarrar I have discovered that it is preferred to keep this property as required, but you can work around it either like this:

```
import RE2 from "re2";
import Ajv from "ajv";

const re2other = (pattern: string, u: string) => RE2(pattern, u);
re2other.code = 'require("ajv/dist/runtime/re2").default';

const ajv = new Ajv({
  code: { regExp: re2other },
});
```

Or use the same approach the tests use to create a [separate module](https://github.com/ajv-validator/ajv/blob/master/lib/runtime/re2.ts) to wrap RE2 and then [require it where needed](https://github.com/ajv-validator/ajv/blob/8ed855b317ade9e13a21f219b72cf8a25b2d36d1/spec/issues/1683_re2_engine.spec.ts#L8).
