### ISSUE TITLE
Add `sideEffects: false` flag to `package.json` to allow tree-shaking

### ISSUE THREAD

**Issue by josdejong** [ajv-validator/ajv#2479]
I have a library that amongst others exports a utility function `createAjvValidator ` that uses `ajv`. Now, not all users of my library use this utility function, but I noticed that the Ajv library is always included when creating a js bundle containing my library, also when the ajv utility function is not used at all. It turns out that tree-shaking is not working.

Can the flag `"sideEffects": false` be added to the `package.json` file of `ajv`? That will enable tree shaking by Vite/Rollup/Webpack out of the box.

See:

- https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
- https://github.com/rollup/rollup/issues/2593

**Comment by jasoniangreen** [comment]
Sure @josdejong, do you want to make a PR for it and I'll run it by @epoberezkin ?

**Comment by josdejong** [comment]
Definitely! Here you go: #2480

**Comment by jasoniangreen** [comment]
Merged. Not sure when it will go out, but I'll keep you posted.

**Comment by josdejong** [comment]
Thanks Jason 👍

**Comment by josdejong** [comment]
Any news on this @jasoniangreen? A bug fix release would be very welcome 😅

**Comment by thibaultdalban** [comment]
Hi @jasoniangreen 

I'm interested in the feature added by @josdejong.
Do you have some updates on when/if this will be released?

Thanks.
