### ISSUE TITLE
Question: Do relative schema's work for files?

### ISSUE THREAD

**Issue by abritinthebay** [ajv-validator/ajv#248]
Having some problems with this locally and want to check if I'm screwing it up or it's just not supported.

Basically if I have a node module with all my schema's in can I just do `"$ref": "./some/path/schema.json"` and have that resolve? It would seem like I should be able to.. but I'm running into issues.

**Comment by epoberezkin** [comment]
You need to use "id" property in schemas, add them to ajv instance using addSchema method. $ref refers to the schema ID (schema uri, as per spec), it has nothing to do with file names.

**Comment by abritinthebay** [comment]
Yes... I know that. That's not what I asked. 

Will ajv load _local_ files using that id method? I can do a local uri for the schema uri. I'm trying that now (it works if it's a remote uri) but I'm running into issues with a local uri and I'm wondering if I've screwed it up OR it's not supported.

eg:

`"id": "./my/local/path/"` 
`"$ref": "some/other/file.json"`

I'm not asking for clarity on the schema id property - I'm well aware of that.

**Comment by epoberezkin** [comment]
Got it. Ajv doesn't implement any loading mechanism - it's out of scope. You can either add all referenced schemas using `addSchema` method (or via `schemas` option) or use [asynchronous compilation](https://github.com/epoberezkin/ajv#asynchronous-compilation) - you will need to supply your own loading logic as an option to the Ajv instance. This way you can load from files if you run on the server or via network when you run in the browser.

**Comment by abritinthebay** [comment]
ahh ok, I see. That makes sense. I have no idea how I have this working with remote files then! 👍

**Comment by epoberezkin** [comment]
You may have added them with `addSchema`?
