### ISSUE TITLE
serializing Infinity creates invalid JSON

### ISSUE THREAD

**Issue by MatthiasMann** [ajv-validator/ajv#2482]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.17.1

**Ajv options object**
{}

Test case:
```javascript
interface LoudnessMeasurement {
  m: number | null,
  s: number | null,
  g: number | null,
  g_seconds: number
}
const schema: JTDSchemaType<LoudnessMeasurement> = {
  properties: {
    m: { type: "float64", nullable: true },
    s: { type: "float64", nullable: true },
    g: { type: "float64", nullable: true },
    g_seconds: { type: "float64" }
  }
};
const ajv = new Ajv();
let serializer = ajv.compileSerializer(schema);
console.log(serializer({m:-Infinity, s:-12.0, g:null, g_seconds: 420.69}));
```
Result:
```{"m":-Infinity,"s":-12,"g":null,"g_seconds":420.69}```

This JSON is invalid and should instead be:
```{"m":"-Infinity","s":-12,"g":null,"g_seconds":420.69}```

**Comment by MatthiasMann** [comment]
Setting the options object to ```{strictNumbers: false}``` did not help.

**Comment by jasoniangreen** [comment]
Hi @MatthiasMann thanks for raising this. It does indeed seem wrong to me that `compileSerializer` is able to produce a string that will throw when passed to `JSON.parse` but according to the JSON spec your proposal is also incorrect. In theory `Infinity` (and also `NaN`) should be be converted to `null` when serialised. You can try it yourself:

```
> JSON.stringify({"blah": Infinity})
> '{"blah":null}'
```

So the correct fix (though I would need to consult on this more to be sure) would be to convert to `null`. If you wanted `"-Infinity"` in your case, then that is something you would need to manage separately, for instance, by traversing your objects and swapping `Infinity` for `"Infinity"`.

**Comment by MatthiasMann** [comment]
Hmm you are right - this is very annoying.

As I only have very few elements which need to handle -Infinity I just replaced these with my own function and template literals for this object:
```javascript
function peak_to_JSON(n: number): string {
  return (n > -190) ? n.toString() : "\"-Infinity\"";
}
function peak_to_JSON_nullable(n: number | null): string {
  return (n === null) ? "null" : peak_to_JSON(n);
}```

let serializer = (data:LoudnessMeasurement) => `{\"m\":${peak_to_JSON_nullable(data.momentary)},\
\"s\":${peak_to_JSON_nullable(data.short_term)},\
\"g\":${peak_to_JSON_nullable(data.gated)},\
\"g_ms\":${data.gated_recorded.ms()}}`;
```
(this also avoid to convert it to another object to change the key names)

**Comment by jasoniangreen** [comment]
Yeah, that should also mean when we fix this behaviour to return the standardised `null` your fix will not mess anything up, it will just not find any Infinity to replace.

**Comment by jasoniangreen** [comment]
@epoberezkin not a high priority but I wanted to flag to you that I do think this one is a legit bug. The serializer shouldn't be returning invalid JSON strings and therefore `Infinity` and `NaN` should become `null`.
