### ISSUE TITLE
[feature request] Add more formats and support for `qt-*` keys

### ISSUE THREAD

**Issue by Bluscream** [ajv-validator/ajv#2488]
**What version of Ajv you are you using?**
`@master`

**What problem do you want to solve?**
```
Failed to validate: unknown format "boolean" ignored in schema at path "#/properties/App_RapidStartup"
similar error for qt-uri-protocols and qt-uri-extensions
```

**What do you think is the correct solution to problem?**
For example https://app.quicktype.io/schema is producing a lot of [`boolean`](https://github.com/Bluscream/AMPTemplates/actions/runs/10434803032) and it also produces `"qt-uri-protocols": ` and `"qt-uri-extensions": ` for URIs which would be nice if supported but atleast shouldnt fail the validation

- [ ] Support boolean as format `/(true|false|0|1|yes|no|enabled|disabled|on|off)/ig`
- [ ] Add option to ignore unknown formats
- [ ] Support validating `qt-uri-protocols` and `qt-uri-extensions`
- [ ] Add option to ignore unknown keys entirely or just to ignore the unsupported `qt-*` keys

**Will you be able to implement it?**
No

**Comment by jasoniangreen** [comment]
Hi @Bluscream I'm going to close this one as there are a few problems with the issue. It's addressing too many things with too few details and specific examples. I can answer a few of your questions, but in general it would help a lot if you can provide a specific failing schema, along with the data you passed and error/results and your expected outcome. It would also help if you can keep the query separate from any other dependencies, I don't know what qt is, but AJV and JSON Schema are generic tools which can handle any schema, so you can just focus on specific examples.

- `Support boolean as format /(true|false|0|1|yes|no|enabled|disabled|on|off)/ig` - There is already a [pattern](https://ajv.js.org/json-schema.html#pattern) keyword you can achieve this with
- `Add option to ignore unknown formats` not sure what you mean but JSON schema will ignore unknown keywords if you pass `strict: false` - [strict mode](https://ajv.js.org/options.html#strict-mode-options)
- `Support validating qt-uri-protocols and qt-uri-extensions` - You can write your [own custom keywords](https://ajv.js.org/api.html#ajv-addkeyword-definition-string-object-ajv)
- `Add option to ignore unknown keys entirely` - does [additionalProperties](https://ajv.js.org/json-schema.html#additionalproperties) help?
