### ISSUE TITLE
Any object is valid

### ISSUE THREAD

**Issue by slavaGanzin** [ajv-validator/ajv#2492]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
          "ajv": "https://esm.sh/ajv@8.17.1",

**Ajv options object**

```javascript
const ajv = new Ajv({code: {esm: true}, allErrors: true});
```

**Your code**

```javascript
const validate = ajv.compile({"type":"object","properties":{"heartbeat":{"type":"string","pattern":"please"}}})
validate({a: 1}) //true
validate.errors // == []
```

*** generated code from debugger ***
```js
function anonymous(self, scope
) {
    const schema13 = scope.schema[8];
    const pattern0 = scope.pattern[0];
    return function validate12(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}) {
        let vErrors = null;
        let errors = 0;
        if (errors === 0) {
            if (data && typeof data == "object" && !Array.isArray(data)) {
                if (data.heartbeat !== undefined) {
                    let data0 = data.heartbeat;
                    const _errs1 = errors;
                    if (errors === _errs1) {
                        if (typeof data0 === "string") {
                            if (!pattern0.test(data0)) {
                                validate12.errors = [{
                                    instancePath: instancePath + "/heartbeat",
                                    schemaPath: "#/properties/heartbeat/pattern",
                                    keyword: "pattern",
                                    params: {
                                        pattern: "please"
                                    },
                                    message: "must match pattern \"" + "please" + "\""
                                }];
                                return false;
                            }
                        } else {
                            validate12.errors = [{
                                instancePath: instancePath + "/heartbeat",
                                schemaPath: "#/properties/heartbeat/type",
                                keyword: "type",
                                params: {
                                    type: "string"
                                },
                                message: "must be string"
                            }];
                            return false;
                        }
                    }
                }
            } else {
                validate12.errors = [{
                    instancePath,
                    schemaPath: "#/type",
                    keyword: "type",
                    params: {
                        type: "object"
                    },
                    message: "must be object"
                }];
                return false;
            }
        }
        validate12.errors = vErrors;
        return errors === 0;
    }
}
```

**Comment by slavaGanzin** [comment]
Yeah I understand that:
Properties are not required
properties keyword does not require that the properties mentioned in it are present in the object (see examples).

but still, it's unexpected

**Comment by csahid** [comment]
I do not know if it is related but `validateSchema` method with latest ajv version return `true` for any schema specified.

I used this simple node code to test it :
```javascript
const Ajv = require("ajv").default
const ajv = new Ajv()
const schema = {
    should:"not work on ajv"
}

console.log(ajv.validateSchema(schema))
```
It returns `true`.

The method was working as wanted before though. Also the `ajv.compile()` method works correctly and throws an exception with schema specified on my example.

**Comment by jasoniangreen** [comment]
> I do not know if it is related but `validateSchema` method with latest ajv version return `true` for any schema specified.

Hi @csahid - Regarding this comment, this has been discussed before [here](https://github.com/ajv-validator/ajv/issues/2463). Long story short, it's not something we're open to changing and is not supposed to be a guarantee that a schema will compile. It's just a basic syntax check. If you want to test that a schema is valid to compile you can try catch the compile.

**Comment by jasoniangreen** [comment]
> Yeah I understand that: Properties are not required properties keyword does not require that the properties mentioned in it are present in the object (see examples).
> 
> but still, it's unexpected

Exactly @slavaGanzin, you should use `required` and `additionalProperties: false` to get the behaviour you want. This is in line with the JSON Schema spec, it is generally designed as quite permissive by default. You can compare this to JTD which disallows additional properties by default, it's just a different ethos.

**Comment by slavaGanzin** [comment]
@jasoniangreen I got that. And it makes sense if you read the spec, but quite confusing for newcomers and also it's error prone: really easy to miss this. 

It would be really useful to get console.error that you "don't validating anything because of [link to spec#required]".

**Comment by jasoniangreen** [comment]
As this behaviour is to spec and it doesn't seem to have had any further discussion around it I'm going to close.
