### ISSUE TITLE
uri check fails

### ISSUE THREAD

**Issue by ruegenbfr** [ajv-validator/ajv#2505]
Ajv reports a validation error for a valid uri string.

URI: `https://hi.wikipedia.org/wiki/जर्मनी`
Validation error text: `data must match format "uri"`

I know e.g. `नी` is not ASCII and RFC 3086 does not define the use of other characters. Nethertheless it is a valid url and
shouldn't the strings representing an URL be u subset of the strings representing an URI?

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv version: 8.17.1 (latest version)

**Ajv options object**
```
{
  allErrors: true, 
  strictSchema: true
}
```

**JSON Schema**
```
{
    "type": "string",
    "format": "uri"
}
```

**Sample data**

```
"https://hi.wikipedia.org/wiki/जर्मनी"
```

**Your code**

```
import Ajv from "ajv";
const addFormats = require("ajv-formats");
const ajv = new Ajv(options);
const validResult = ajv.validate(schema, data);
const errors = ajv.errors;
const message = ajv.errorsText(ajv.errors);
```

**Validation result, data AFTER validation, error messages**

```
validationResult: false

errors: [{
    "instancePath": "",
    "schemaPath": "#/format",
    "keyword": "format",
    "params": {
        "format":"uri"
    },
    "message": "must match format \"uri\""
}]

message: data must match format "uri"
```

**What results did you expect?**

```
validationResult: true

errors: null

message: No errors
```

**Comment by coderextreme** [comment]
![image](https://github.com/user-attachments/assets/9fa91436-b9ad-4119-b007-594387a2c07a)

I also ran into validation issues with an emoji in a uri (a local file, uri-reference I think ).  See image.  Please try validating glTF files.

**Comment by coderextreme** [comment]
@ruegenbfr I think we want to include iri and iri-reference instead of uri and uri-reference for international purposes.

**Comment by coderextreme** [comment]
https://en.m.wikipedia.org/wiki/Internationalized_Resource_Identifier

**Comment by coderextreme** [comment]
This library helps with uri, uri-reference, and especially iri and iri-reference formats.  Search for iri or iri-reference in your ajv-formats installation for package link, which I list here:

ajv-formats-draft2019:  [ajv-formats-draft2019 - npm](https://www.npmjs.com/package/ajv-formats-draft2019)

So far, it looks like this works with JSON schema draft 2020-12, but there's more work to do.

**Comment by coderextreme** [comment]
Using ajv-formats-draft2019 as a drop-in replacement for ajv-formats has worked for me so far.  Please test throughly.

**Comment by jasoniangreen** [comment]
Thanks @coderextreme for providing this extra information and providing the solution.

**Comment by coderextreme** [comment]
If you are still having issues, check my code that adds the “uri” and “iri” formats: https://github.com/coderextreme/x3dvalidate

**Comment by coderextreme** [comment]
const Ajv2020 = require("ajv/dist/2020");
const apply = require('ajv-formats-draft2019');
let ajv = new Ajv2020({ strict: false });
apply(ajv, {mode: "full", formats: ["uri-reference", "uri", "iri-reference", "iri"], keywords: true});  // fast mode is "fast"
