### ISSUE TITLE
Question: Is this library abandoned?

### ISSUE THREAD

**Issue by abdalla-rko** [ajv-validator/ajv#2510]
I see the last pr was merged in September and new pr's don't get merged or get feedback. Don't get me wrong I know it's open source and maintainers may not have time. I just would love to do a pr for #2129. Thanks.

**Comment by TheOneTheOnlyJJ** [comment]
It would be great getting an answer on this one.

**Comment by Kenneth-Sills** [comment]
If activity on a project this big has slowed down, making an issue ticket asking if it's abandoned won't do much. You're more likely to get a response if you reach out to the maintainer directly: @epoberezkin.

It looks like he's been active working on other projects, and as we approach the holidays he may just have less time. Like you said, FOSS projects without organizational maintainers just have lulls sometimes.

**Comment by jasoniangreen** [comment]
I have been helping on maintaining AJV, but I had to take a break for a couple of months. I am just becoming free again to find some time, but it will be outside of UK working hours. I will check in tonight and try and catch up.

**Comment by jasoniangreen** [comment]
@abdalla-rko if you have a proposal for #2129 can you please discuss it on that issue. Though I will have to try and get some input from @epoberezkin as I'm not sure of the history behind why the types are not separated already.
