### ISSUE TITLE
Extending properties with $ref

### ISSUE THREAD

**Issue by gobbledygook88** [ajv-validator/ajv#260]
Considering the following schema

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema",
  "type": "object",
  "definitions": {
    "ref": {
      "type": "integer"
    }
  },
  "properties": {
      "prop": {
          "$ref": "#/definitions/ref",
          "minimum": 10
      },
      "propWithAllOf": {
          "allOf": [{
            "$ref": "#/definitions/ref",
          }, {
            "minimum": 10
          }]
      }
  }
}
```

I currently get the following results when validating against a range of input objects

| Input Object | Valid |
| --- | --- |
| `{ "prop": 10 }` | `true` |
| `{ "prop": 1 }` | `false` |
| `{ "propWithAllOf": 10 }` | `true` |
| `{ "propWithAllOf": 1 }` | `false` |

According to the [JSON spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3)

> Any members other than "$ref" in a JSON Reference object SHALL be ignored.

Does that mean the second result should be `true`? Thanks!

**Comment by epoberezkin** [comment]
You are right.

Ajv doesn't comply with this provision, it allows extending $refs with additional keywords.
I was going to address it in the next major version change.
I was also considering adding the option in the current version that would allow to choose between:
- failing schema compilation (I think it should be the default to be honest)
- ignoring extra keywords (as per spec, should log warning)
- using extra keywords (current behaviour).

In this case the 1st or 2nd option could become the default in the next major version.

**Comment by mbroadst** [comment]
@epoberezkin can you expand on what we need to change here? I'm getting this warning now and it pointed me here but I'm not quite sure what the implications are.

I'm currently using `$ref` to reference a definition which is a `oneOf` a number of schemas with custom keywords in it - are you saying this will not be possible in the upcoming release?

**Comment by mbroadst** [comment]
Oh. I think this is a false positive for my case, after reading this more closely.  My schema looks like:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema",
  "type": "object",
  "definitions": {
    "date": {
      "oneOf": [
        { "instanceOf": "Date" },
        { "type": "string", "coerceTo": "Date" },
        { "type": "number", "coerceTo": "Date" }
      ]
    }
  },
  "properties": {
      "prop": { "$ref": "#/definitions/date" }
  }
}
```

"coerceTo" and "instanceOf" are custom keywords, but as far as the definition goes there is no other keyword other than `$ref` in my definition - yet the warning is popping up

**Comment by epoberezkin** [comment]
Could you please submit a new issue - it may be a bug

**Comment by mbroadst** [comment]
ah! apologies after some deep diving I discovered I am indeed auto-generating some schema bits that use a custom keyword with `$ref`, is that not going to be possible in the next major version?

**Comment by epoberezkin** [comment]
There will be an option to preserve the current behaviour.
By spec everything but $ref should be ignored, the correct way to extend $ref is to use allOf keyword.

**Comment by epoberezkin** [comment]
in [4.4.0](https://github.com/epoberezkin/ajv/releases/tag/4.4.0)

**Comment by emarkovskyi** [comment]
> You are right.
> 
> Ajv doesn't comply with this provision, it allows extending $refs with additional keywords.
> I was going to address it in the next major version change.
> I was also considering adding the option in the current version that would allow to choose between:
> 
> * failing schema compilation (I think it should be the default to be honest)
> * ignoring extra keywords (as per spec, should log warning)
> * using extra keywords (current behaviour).
> 
> In this case the 1st or 2nd option could become the default in the next major version.

Dear @epoberezkin first of all thank you for so nice and powerful project,
we find weird issue wrt extending of $ref (BTW such extending is a great fetaure)
We trying to create some base schema inside definition and also extend this schema by extra fields **inside** the same definitions, e.g.
```
 {
    '$schema': 'http://json-schema.org/draft-07/schema',
    '$id': 'http://www.mydomain.com/definitions.json',
    'type': 'object',
    'definitions': {
        "basic-definition": {
         },
        "extended-basic-definition": {
          //reference to the basic, but extra properties are ignored
          "$ref": "http://www.mydomain.com/definitions.json#/definitions/basic-definition"
           "properties": {
               extra properties....
            }
        }
     }
  } 
```
and AJV in this case just ignore extra filed and uses on properties from the basic.
_**Could we achieve such extending somehow?**_ 
If $ref in *properties* e.g (below) everything works like a charm
```
 {
    '$schema': 'http://json-schema.org/draft-07/schema',
    '$id': 'http://www.mydomain.com/definitions.json',
    'type': 'object',
    'definitions': {
        "basic-definition": {
         },
        "extended-basic-definition": {          
           "properties": {
              "my-property": {
                  **//reference to the basic, works great**
                   "$ref": "http://www.mydomain.com/definitions.json#/definitions/basic-definition"
                    "properties": {
                         extra properties....
                     }
               }
            }
        }
     }
} 
```
Thank you in advanced.

**Comment by epoberezkin** [comment]
Ajv now ignores all siblings to $ref but it can be changed with options. See the docs.

**Comment by emarkovskyi** [comment]
> Ajv now ignores all siblings to $ref but it can be changed with options. See the docs.

@epoberezkin, thank you for quick response, so TBH quite difficult to find correct option :-), I tried to play with extendRefs: true, inlineRefs: false}
What option do you mean? Maybe it could be a specific option of add/compileSchema methods?
Thank you in advanced.

**Comment by emarkovskyi** [comment]
> Ajv now ignores all siblings to $ref but it can be changed with options. See the docs.

@epoberezkin we still could not find proper options, tend to think that hierarchy described above (schema extending inside definitions) is impossible for now, but could you please give us a hint what  `options` do you mean?
Thank you in advanced.
