### ISSUE TITLE
$data usage returns an error when trying to compare minimum value

### ISSUE THREAD

**Issue by giladmatko** [ajv-validator/ajv#269]
Hi,

I've tried the following example taken from:
https://github.com/json-schema/json-schema/wiki/%24data-(v5-proposal)

``` json
{
    "type": "object",
    "properties": {
        "smaller": {"type": "number"},
        "larger": {
            "type": "number",
            "minimum": {"$data": "1/smaller"},
            "exclusiveMinimum": true
        }
    },
    "required": ["larger", "smaller"]
}
```

I wrote a simple json example:

``` javascript
{
  smaller: 6,
  larger: 8
}
```

Unfortunately I got the following error:
data.properties['larger'].minimum should be number

Can someone assist me with this issue?

Thank you very much,

Gilad

**Comment by epoberezkin** [comment]
are you using v5 option?

**Comment by giladmatko** [comment]
Hi,

Thank you for your quick reply.
Somehow I missed it.

Now it works. 

Thank you so much!!!

Have a nice day

**Comment by epoberezkin** [comment]
The reason it failed is that it is not a valid draft 4 JSON-schema.

**Comment by giladmatko** [comment]
Thank you very much.

I started using it a week ago... so i'm very new with this package.

I highly appreciate your help
