### ISSUE TITLE
Feature request - strict mode

### ISSUE THREAD

**Issue by simon-p-r** [ajv-validator/ajv#283]
Hi

Is it possible to allow a strict mode option when compiling schemas?  For example you may want to enforce that a string field must have min or max length defined or an array must have items defined.

Thanks

**Comment by epoberezkin** [comment]
There are two solutions already:
1. to extend draft4/v5 meta-schema with whatever additional requirements you have and put this extended meta-schema in $schema keyword. You need to use [$merge keyword](https://github.com/epoberezkin/ajv#merge-and-patch-keywords) to extend meta-schemas.
2. Define additional schema to validate your schemas and do it in your code before schema compilation.

Neither requires additional options or compilation modes, it is all in the scope of validation, you just need to treat your schemas as data and validate them for any requirements you need to enforce.

**Comment by epoberezkin** [comment]
Closing this issue, please post here if you have a use case that cannot be implemented in the suggested way.

**Comment by simon-p-r** [comment]
Ok thanks I will look at these suggested options
