### ISSUE TITLE
'patternProperties' overrides 'properties'

### ISSUE THREAD

**Issue by TheRealWelshCJ** [ajv-validator/ajv#286]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

4.5.0

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

``` javascript
{
  allErrors: true,
  verbose: true
}
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "test" : { "type" : "string" }     
    },
    "patternProperties" : {
        "^.*$" : 
        {                                             
                "type": "boolean"
        }
    },
    "additionalProperties": false,
    "uniqueProperties" : true     
}
```

**Data (please make it as small as posssible to reproduce the issue):**

``` json
{ "test" : "example" }
```

**Your code (please use `options`, `schema` and `data` as variables):**

Using your Tonic example:

``` javascript
var Ajv = require('ajv');
var ajv = Ajv({allErrors: true, verbose: true});

var schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "test" : { "type" : "string" }     
    },
    "patternProperties" : {
        "^.*$" : 
        {                                             
                "type": "boolean"
        }
    },
    "additionalProperties": false,
    "uniqueProperties" : true     
};

var validate = ajv.compile(schema);

test({ "test" : "example" });

function test(data) {
  var valid = validate(data);
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}
```

**Validation result, data AFTER validation, error messages:**

```
"Invalid: data['test'] should be boolean"
```

**What results did you expect?**

It appears that 'patternProperties' overrides the standard 'properties' field.  I would expected this to pass without issue as 'test' is defined as a string, not a Boolean.  A similar example is shown on the json-schema site here: http://json-schema.org/example2.html .  This shows both 'properties' and 'patternProperties' being used.

**Are you going to resolve the issue?**

I will attempt to find and fix this issue, but would appreciate someone who is more familiar with the code base looking in to this as well.

**Comment by TheRealWelshCJ** [comment]
The JSON Validation Schema: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-12 Sections 5.4.4.4 & 5.4.4.5, suggest that items matching the 'properties' set should be validated and removed from the larger set before the 'patternProperties' is processed.

**Comment by TheRealWelshCJ** [comment]
Related to: https://github.com/epoberezkin/ajv/pull/196

Author closed that issue, but I do believe that it is an issue based on what the Validation Schema says in my above comment.

**Comment by epoberezkin** [comment]
The paragraphs you are referring to are about determining whether the property is additional or not. 5.4.4.1 requires that both keywords apply.

**Comment by epoberezkin** [comment]
Ok, requires is a bit too strong a word here... I'd say implies. [This test](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/properties.json#L38) requires it though.

**Comment by TheRealWelshCJ** [comment]
I understand, however, the example in 5.4.4.5 seems to suggest that you can have something that matches a 'properties' object which does not match a 'patternProperties' object, and the base schema example here: http://json-schema.org/example2.html states the following:

"
- we have a properties keyword with only a / entry;
- we use patternProperties to match other property names via a regular expression (note that it does not match /);
- as additionalProperties is false, it constrains object properties to be either / or to match the regular expression
  "

This seems to suggest that you can have '/' as a valid property, even though it does not match the regular expression within the 'patternProperties'.

json-schema.org also references the 'Space Telescope Science Institute' JSON Schema writing guide, which under 'patternProperties' states "Any properties explicitly defined in the properties keyword are also accepted".

To be fair, every online validator appears to do it the way that Ajv does, but I am struggling to see how this is correct behaviour given the above.

Thanks for the reply.

Best regards,

C.

**Comment by TheRealWelshCJ** [comment]
The test here: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/9723c8f2f5f7c471c5147d5d6d08f4aa10a89f83/tests/draft4/additionalProperties.json#L3 Also seems to suggest that properties is independent from pattern properties, although not quite in the same use case as my initial comment.

**Comment by TheRealWelshCJ** [comment]
btw, I've echoed this concern in to the JSON test suite, as it appears it is more an issue with their testing rather than any specfic implementation.  If I understand this correctly.

**Comment by epoberezkin** [comment]
> This seems to suggest that you can have '/' as a valid property, even though it does not match the regular expression within the 'patternProperties'.

That is correct, you can have a property that does not match the pattern. But if it matches the pattern it should be valid according to the schema related to that pattern (even if it is explicitly listed in properties too).

The test you are pointing to has different properties in `properties` and `patternProperties`, neither `foo` nor `bar` match `/^v/` pattern.

The confusion about the validation of `properties` and `patternProperties` comes from the general confusion related to seeing JSON-schema as a declarative standard the defines the structure of the data (which it is not). It all becomes much simpler to reason about if you think about the schema as about the list of requirements that should be fulfilled for the data to be valid, each keyword defining its own requirement. In some simple cases this list may look like the structure of the data, but in many advanced cases it does not. In this way the requirements defined inside `properties` keyword have nothing to do with those defined in `patternProperties` keyword.
