### ISSUE TITLE
"name" property fails required check

### ISSUE THREAD

**Issue by braco** [ajv-validator/ajv#287]
```
{
  'properties': {
    'name': {
      'type': 'string',
    },
  },
  'required': ['name'],
}
```

No 'required property' error messages returned 

```
{
  'properties': {
    'notname': {
      'type': 'string',
    },
  },
  'required': ['notname'],
}
```

"required property" error message returned

Also, I wonder if you could squeeze some more speed out by checking for the existence of the property before the format? It seems like other required properties are returning "format of property should be XXX" instead of just "property doesn't exist"

**Comment by epoberezkin** [comment]
Works for me: https://tonicdev.com/esp/57be3188f18f321300ea7763
Could you please submit everything I asked for (ajv version, ajv options, schema, data, code, results/errors/messages)?

> Also, I wonder if you could squeeze some more speed out by checking for the existence of the property before the format? It seems like other required properties are returning "format of property should be XXX" instead of just "property doesn't exist"

I don't understand that. Please submit the example. Sounds like a separate issue - a potential improvement? Only existing properties are validated at the moment, ajv wouldn't validate format of the property that doesn't exist if that's what you mean.

**Comment by epoberezkin** [comment]
@braco could you please clarify?

**Comment by braco** [comment]
@epoberezkin : Sorry about that. I rm'ed my node_modules, ran npm install again with the latest version and the error seems to have vanished. Must have been user error. Thank you for being so thorough as always.
