### ISSUE TITLE
Broken / Out of Date Readme

### ISSUE THREAD

**Issue by jeremykentbgross** [ajv-validator/ajv#290]
The readme is currently broken or out of date, containing many dead links to itself, presumably because some sections have been removed.

One important example (but not the only one) is the options link. It appears that the section documenting the options (a highly desirable section of the documentation btw) has been removed, yet self links to it remain. There are more examples of this, but this is the most important one given this would presumably be the primary documentation for your libraries initialization options.

**Comment by epoberezkin** [comment]
> The readme is currently broken or out of date, containing many dead links to itself, presumably because some sections have been removed. One important example (but not the only one) is the options link.

I have no better idea than that you have some issue with you your browser (or its settings)... [Options link](https://github.com/epoberezkin/ajv#options) in the table of contents is fine, it points to the options section. If there are some specific broken links that are not working please either post them here or you can make the RP.

**Comment by epoberezkin** [comment]
@jeremykentbgross could you please clarify the issue?

**Comment by epoberezkin** [comment]
Please re-open if you see some issue
