### ISSUE TITLE
exclusive properties

### ISSUE THREAD

**Issue by niquola** [ajv-validator/ajv#295]
@epoberezkin Excuse me for question in issue, but could you point how to implement `exclusive properties` in JSON schema, i.e. we allows property "a" or "b" - but not both (we also sometimes want to require "a" or "b").

**Comment by epoberezkin** [comment]
SO is a better place indeed :)

``` json
{
  "type": "object",
  "anyOf": [
    {
      "additionalProperties": false,
      "required": [ "a" ],
      "properties": {
        "a": {}
      }
    },
    {
      "additionalProperties": false,
      "required": [ "b" ],
      "properties": {
        "b": {}
      }
    }
  ]
}
```

**Comment by cheerfulstoic** [comment]
I realize that this is probably better on SO, but I ran across this and struggled with it for a bit, so I wanted to leave a breadcrumb 😄   At least in my case, `oneOf` was what I wanted instead of `anyOf`

**Comment by epoberezkin** [comment]
Unless you use discriminator, oneOf would always validate all branches, even if only one can ever be valid. So it's usually better to either use discriminator or use anyOf...
