### ISSUE TITLE
Is there any way to reuse compiled schema 

### ISSUE THREAD

**Issue by nomi-ramzan** [ajv-validator/ajv#296]
Hi 
I am using AJV(latest) with [express](http://npmjs.com/package/express). here is current code

```
app.get('test', function (req, res, next) {
    var validate = ajv.compile(schema);
    if( !validate(req.body) ) return sendError(validate.errors)
    next();
})
```

Is there any way to do this. Like just compile it once and use clone/copy of it on each call.

```
var validate = ajv.compile(schema);

app.get('test', function (req, res, next) {
    if( !validate(req.body) ) return sendError(validate.errors)
    next();
})
```

I also tried clone, cloneDeep of [lodash](http://npmjs.com/package/lodash). But now working.
Thank you.

**Comment by epoberezkin** [comment]
You should use your second code sample - that's exactly how it should be.

**Comment by nomi-ramzan** [comment]
I tried this code. It will overwrite codes in case of multi calls at the same time. Let suppose two calls came and  before sending errors of first call second call will overwrite errors then first call will send errors of second call instead of first call ( which i have lost now).

**Comment by nomi-ramzan** [comment]
Can you please help me how can I clone deeply `validate` object ?

**Comment by epoberezkin** [comment]
That's not correct. Validation is synchronous, JavaScript is single threaded. It could have only happened if you use the errors in the next execution block (in callback, nextTick, setTimeout etc.). Please see [FAQ](https://github.com/epoberezkin/ajv/blob/master/FAQ.md#ajv-api-for-returning-validation-errors) and https://github.com/epoberezkin/ajv/issues/242#issuecomment-234369094

So you don't need to clone, you just need to use your second sample, it doesn't have the problem you describe.

**Comment by nomi-ramzan** [comment]
Thank you I got it.

**Comment by carcigenicate** [comment]
I have to wonder though (almost a decade later, sorry), what is the point of `compile` then?

If it was compiled once then reused, that would make sense, presumably because it would skip re-compiling. It seems like `compile` is just an extra function call just to produce a function, when that function produced by `compile` could just accept both the schema and data in one go.
