### ISSUE TITLE
What is wrong with my schema ?

### ISSUE THREAD

**Issue by nomi-ramzan** [ajv-validator/ajv#298]
**Schema**

```
{
    type:'array', minItems:1,
    items:{
        type:'string',
        oneOf:[
          {enum:['admin']},
          {enum:['read','search']}
        ]
    }
}
```

**Data**
 `['admin','read']`

**Result**
`true`

**Expected Result**
 `false`
**Reason**
`admin` and `read` can not come together.
Valid inputs are 

```
['admin']
['read'] | ['search']
['read', 'search']
```

**Comment by epoberezkin** [comment]
That's an SO question :)

Each item should be valid according to the schema in `items` keyword. And each item is valid, so the result is true. Your schema is equivalent to this one:

``` javascript
{
    type:'array', minItems:1,
    items:{
        type: 'string',
        enum: ['admin', 'read', 'search']
    }
}
```

What you seem to want though is this:

``` javascript
{
    type:'array', minItems:1,
    items:{ type: 'string' },
    oneOf: [
      { items: { enum: ['admin'] } },
      { items: { enum: ['read', 'search'] } }
    ]
}
```

**Comment by epoberezkin** [comment]
And actually in the second schema using `anyOf` is more efficient, as no data can be valid according to both schemas at the same time.
