### ISSUE TITLE
Multilingual meta data

### ISSUE THREAD

**Issue by amiika** [ajv-validator/ajv#299]
**What version of Ajv you are you using?**
4.7.0

**What problem do you want to solve?**
Title&Description localization. HTTP Accept-Language is not a good solution for transferring schemas localized to multiple languages. 

**What do you think is the correct solution to problem?**
First option from:
https://github.com/json-schema/json-schema/wiki/Multilingual-meta-data-(v5-proposal)

First option would also be compatible with https://www.w3.org/TR/json-ld/#dfn-language-map for example:

```
{
  "@context":
  {
    ...
    "title": { "@id": "dcterms:title", "@container": "@language" }
  },
  "title":
  {
    "ja": "忍者",
    "en": "Ninja",
    "cs": "Nindža"
  }
  ...
}
```

**Will you be able to implement it?**
No

**Comment by epoberezkin** [comment]
`title` keyword is not used for validation, so the only change that is really needed is to change [v5 meta-schema](https://github.com/epoberezkin/ajv/blob/master/lib/refs/json-schema-v5.json#L52) to allow objects of strings in addition to simple strings (or locale references from the second part of the proposal).

**Comment by amiika** [comment]
Neat. I quess something like this could work then:

```
 "title": {
            "oneOf":[
              {"type":"string"},
              {"type":"object",
                "patternProperties":{"^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$":{"type":"string"}},
                "additionalProperties":false
              }     
              ]
        }
```

This lang-object with the patternProperty could also be stored under definitions and reused for description.

**Comment by epoberezkin** [comment]
I wouldn't complicate it with pattern-matching locales, to be honest. Maybe just make the second subschema:

``` json
{
  "description": "localised strings",
  "type":"object",
  "additionalProperties": {"type":"string"}
}
```

**Comment by amiika** [comment]
Should there be additional primitive type for localized strings? For example:

"simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string", "langString"]
},

... and langString would be validated against:

{
  "description": "localised strings",
  "type":"object",
  "additionalProperties": {"type":"string"}
}

**Comment by epoberezkin** [comment]
No, it can't be a basic type. Type is something that exists on the JSON level, not on the data structure level. It's still "object" type.

**Comment by amiika** [comment]
Right. So the $ref is the only way to reference localized string "type".

**Comment by epoberezkin** [comment]
Closing it as this idea is not included in draft-06 and probably won't be included in the next version too. In any case meta-schema change can be made separately or using some plugin...
