### ISSUE TITLE
Removing failing properties with removeAdditional=failing

### ISSUE THREAD

**Issue by zandaqo** [ajv-validator/ajv#300]
Hi,
I was looking into delegating some data cleaning to ajv using removeAdditional, for example, remove empty strings or other failing optional properties from objects. Straight up defining those optional properties in object's `properties` and running with `removeAdditional: 'failing'` doesn't seem to do the trick: validation just fails. I'm wondering if I misunderstood the concept and whether there is another way to achieve this result with ajv by refactoring the schema.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.7.0

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

``` javascript
  useDefaults: true,
  removeAdditional: 'failing',
  coerceTypes: true,
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

``` json
{
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "optionalString": {
            "type": "string",
            "minLength": 5
        },
        "optionalObject": {
            "type": "object",
            "minProperties": 1
        }
    },
    "additionalProperties": false,
    "required": ["_id"]
}
```

**Data (please make it as small as posssible to reproduce the issue):**

``` json
{
    "_id": "someid",
    "optionalString": "1",
    "optionalObject": {
        "a": "b"
    },
    "randomOption": true
}
```

**Your code (please use `options`, `schema` and `data` as variables):**

ajv -s schema.json -d data.json --changes --remove-additional failing

**Validation result, data AFTER validation, error messages:**
# /properties/optionalString/minLength should NOT be shorter than 5 characters

**What results did you expect?**

Removal of optionalString as a failing property without invalidating the object.

**Comment by zandaqo** [comment]
Ok, little digging into the source code[[1]](https://github.com/epoberezkin/ajv/blob/master/lib/dot/properties.jst#L56) points me to the fact that, surprisingly, only `additionalProperties` are removed by `removeAdditional` option. Now, the question is how to convince ajv that my "optional" properties are "additional" ones.

**Comment by epoberezkin** [comment]
Lol. Funny indeed.

The idea is that "additionalProperties" keyword value can be a schema, in which case those properties that failed validation by that schema would be removed.

To achieve what you want there are two approaches:

 1) Make them additional indeed:

``` json
{
    "type": "object",
    "allOf": [
        {
            "properties": {
                "_id": {},
                "optionalString": {},
                "optionalObject": {}
            },
            "additionalProperties": false
        },
        {
            "properties": {
                "_id": {
                    "type": "string"
                }
            },
            "additionalProperties": {
                "anyOf": [
                    {
                        "type": "string",
                        "minLength": 5
                    },
                    {
                        "type": "object",
                        "minProperties": 1
                    }
                ]
            }
        }
    ],
    "required": ["_id"]
}
```

It looks a bit hacky and complex but does the job - the first subschema in "allOf" would remove all but allowed properties, the second would remove optional properties if they are invalid.

 2) I would prefer another approach though - using a custom keyword

``` json
{
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "optionalString": {
            "type": "string",
            "minLength": 5,
            "removeIfFails": true
        },
        "optionalObject": {
            "type": "object",
            "minProperties": 1,
            "removeIfFails": true
        }
    },
    "additionalProperties": false,
    "required": ["_id"]
}
```

``` javascript
ajv.addKeyword('removeIfFails', {
    inline: function() {} // TODO
});
```

Only [inline keywords](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-inline-compilation-function) have access to validation errors at the moment.

**Comment by zandaqo** [comment]
Thank you, Evgeny!

I too like the second approach, the first one would make my already huge schemas enormous. Mimicking the `removeAdditional` code with my limited understanding of the library got me this implementation of that inline function:

``` javascript
ajv.addKeyword('removeIfFails', {
  inline(it) {
    return `if (!valid${(it.dataLevel || '')}) {
      if (validate.errors !== null) {
        if (errors) validate.errors.length = errors;
        else validate.errors = null;
      }
      delete data[${it.dataPathArr[it.dataLevel]}];
    }`;
  },
  statements: true,
});
```

It seems to correctly compile and inline, but it neither removes the failing property nor stops ajv from invalidating the object. Can you give any pointers here?

**EDIT:** Ok, found the code it generates. Firstly, I guess we cannot exit upon the first found mistake if we want to correct them with `removeIfFails`, so we have to use ajv option `allErrors: true`. Secondly, this code seems to work for me so far:

``` javascript
ajv.addKeyword('removeIfFails', {
  inline(it) {
    return `if (errs__${(it.dataLevel || '')}) { // check if there has been a mistake while checking the current property
          vErrors.length = errs_${(it.dataLevel || '')}; // remove mistakes of the current property from the array of all found errors by redefining length to the size of previously found mistakes
          errors = errs_${(it.dataLevel || '')}; // re-set current errors to errors found before the current property
          delete data[${it.dataPathArr[it.dataLevel]}]; // and finally delete the property
        }`;
  },
  statements: true,
});
```

**EDIT2:** Had to fix the above code to work in `patternProperties` too:

``` javascript
ajv.addKeyword('removeIfFails', {
  inline(it) {
    return `if (errors) { 
          vErrors.length = errs_${(it.dataLevel || '')};
          errors = errs_${(it.dataLevel || '')};
          delete data${(it.dataLevel - 1 || '')}[${it.dataPathArr[it.dataLevel]}];
        }`;
  },
  statements: true,
});
```

**Comment by epoberezkin** [comment]
> the first one would make my already huge schemas enormous. 

Probably makes sense splitting them so they are manageable

I will look at the code later.

**Comment by stamler** [comment]
@zandaqo @epoberezkin What is the difference between `errs_` and `errs__` [in this comment](https://github.com/epoberezkin/ajv/issues/300#issuecomment-247667922) I've searched the repo for references and found some but the multiple levels of complexity created by the doT templates is difficult to make sense of.

EDIT: my understanding is that `errors` and `vErrors` are the cumulative total and array of all errors for the entire schema tree, and that `errs_` and `errs__` are somehow a subset of that. Is that correct and if so how are the later two different? There isn't any documentation on this particular subject.

**Comment by epoberezkin** [comment]
There is info on the variables that are available for inline keywords to use in CUSTOM.md

**Comment by parthasarathysarathy** [comment]
Hi @epoberezkin, Hope you are doing well. I am facing memory leak issue in AJV. I have created an instance for AJV and added the schema in it. And stored this AJV instance in Global variables as I need to access this in another file. In that another file I am validating the JSON content. For larger JSON files I am seeing memory leak it's increasing the script completion time.

Please help me out here.
