### ISSUE TITLE
Generating errors object in JSON API spec?

### ISSUE THREAD

**Issue by kjs3** [ajv-validator/ajv#304]
I didn't find anything in issues but has any work been done on outputting errors in the [JSON API spec](http://jsonapi.org/examples/#error-objects)?

Is there interest in this?

**Comment by epoberezkin** [comment]
How is it related to JSON-Schema validation?

**Comment by kjs3** [comment]
@epoberezkin It's not directly related. I started using ajv to validate json in a POST body. If that body isn't valid according to my schema I'd like to return errors in the JSON API format.

**Comment by epoberezkin** [comment]
I understand now. It should not be a part of Ajv package I think. It can be a separate package, e.g. ajv-json-api that would contain the code to transform errors returned by ajv into the format defined by JSON API spec (and maybe some other things related to this spec, e.g. schema for it).

**Comment by kjs3** [comment]
That makes sense, I'll start working on a module.

**Comment by brendo** [comment]
@kjs3 did you ever start on that module? In the same boat ⛵️

**Comment by kjs3** [comment]
@brendo, no sadly. I've failed you. :disappointed: 
The API I was making was small and I just hand-rolled the errors.

**Comment by binarymist** [comment]
+1
