### ISSUE TITLE
Unexpected validation failure

### ISSUE THREAD

**Issue by aaronshaf** [ajv-validator/ajv#307]
Schema:

https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json

API definition example:

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-minimal.json

In AJV this fails with:

```
[ { keyword: 'not',
    dataPath: '.paths[\'/pets\'].get.responses',
    schemaPath: '#/not',
    params: {},
    message: 'should NOT be valid' } ]
```

This otherwise succeeds at http://www.jsonschemavalidator.net/

**Comment by aaronshaf** [comment]
Neeeevermind :-D. `{removeAdditional: true}` threw it off.

**Comment by aaronshaf** [comment]
`{removeAdditional: true}` was throwing it off.

**Comment by epoberezkin** [comment]
It can be tricky indeed
