### ISSUE TITLE
Date validation fails

### ISSUE THREAD

**Issue by henryjw** [ajv-validator/ajv#308]
The validation for dates fails using "string" type and "date-time" format. From some experimentation, it seems that the failure is because the date is treated as an object and not a string. But since ajv is a JSON validator, shouldn't it validate dates as if they were strings instead of objects since that's their JSON representation?

Below is an example. By the way, I'm using version 4.3.1

Schema

```
{
  "type": "object",
  "properties": {
    "someDate": {
      "type": "string",
      "format": "date-time"
    }
  }
}
```

Object
`{ someDate: new Date() }`

**Comment by epoberezkin** [comment]
Date indeed is an object and not a string, so your data is invalid according to your schema. If you want to validate Date objects you can do it with custom keywords, for example:

``` json
{
  "type": "object",
  "properties": {
    "someDate": {
      "instanceof": "Date"
    }
  }
}
```

instanceof keyword is defined in [ajv-keywords](https://github.com/epoberezkin/ajv-keywords#instanceof).

Ajv doesn't stringify/parse data - it validates it as is. It allows for much wider range of applications, beyond data validation. If you need to you can stringify/parse objects in your code.

**Comment by henryjw** [comment]
That makes sense. Thanks for the clarification.
