### ISSUE TITLE
Missing releases/tags/changelog

### ISSUE THREAD

**Issue by blakeembrey** [ajv-validator/ajv#31]
It would be extremely helpful to consumers if you provided a changelog or did releases and tags with each version. I find `npm version` or `mversion` to be extremely simple to use for this.

Edit: Did just see it at the bottom of the README. I think this is still valid though.

**Comment by epoberezkin** [comment]
I will use `npm version`, no problem. I think I was adding tags for most major releases, but probably missed some.

**Comment by blakeembrey** [comment]
Thanks :+1: It makes checking commits between version much simpler.
