### ISSUE TITLE
Hostname Format Regex Failure

### ISSUE THREAD

**Issue by dubiousdavid** [ajv-validator/ajv#312]
The following fails the `hostname` format regex:

```
lead-routing-qa.lvuucj.0001.use1.cache.amazonaws.com
```

I did a quick SO search and found this regex, which works on the above host:

``` javascript
/^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$/
```

http://stackoverflow.com/a/106223

Full error:

``` javascript
[ { keyword: 'format',
    dataPath: '.services[\'lead-matching\'].redis.databases[0].host',
    schemaPath: '#/properties/services/properties/lead-matching/allOf/0/properties/redis/properties/databases/items/properties/host/format',
    params: { format: 'hostname' },
    message: 'should match format "hostname"' } ]
```

AJV version: `4.7.4`

**Comment by epoberezkin** [comment]
Not sure about this one.

According to https://tools.ietf.org/html/rfc1034#section-3.5 the sections should start with letter, not with digit. So it is invalid according to this RFC and to the pattern Ajv is using.

It works though (I can even ping it), which means that such "hostnames" are supported.

As a workaround you can redefine the format in any way you like:

``` javascript
ajv.addFormat('hostname', /.*/);
```

Please post here if you know what is the standard that defines the syntax for hostnames.

**Comment by dubiousdavid** [comment]
This gives a pretty definitive answer to the question:

http://serverfault.com/a/516230

**Comment by epoberezkin** [comment]
cool, thank you, has to be fixed then.

**Comment by epoberezkin** [comment]
in 4.7.6
