### ISSUE TITLE
Can not use array index  in $data json v5

### ISSUE THREAD

**Issue by eakarsu** [ajv-validator/ajv#314]
I like to validate  one array with another one but I like to use "0#" notation to get the current index of array. In this schema, "0#" returns index value and use it to index to other array.
Is it possible?
The following does not validate.

``` javascript
var schema =  {
    "properties": {
        "arr": {
            "items": [{},{},{}],
            "additionalItems": false
        },
        "sameArr": {
            "items": {
                "constant": {
                    "$data": "/arr/0#"
                },
            "additionalItems": false
        }}
    }};

var data = {
    "arr": [ 1, "abc", {"foo": "bar"} ],
    "sameArr": [ 1, "abc", {"foo": "bar"} ]
};
```

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

the latest from git

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

var options = {"v5":true};

``` javascript


```

**JSON Schema (please make it as small as possible to reproduce the issue):**

as above

**Data (please make it as small as posssible to reproduce the issue):**
as above

**Your code (please use `options`, `schema` and `data` as variables):**

``` javascript


var ajv = new Ajv(options); // options can be passed, e.g. {allErrors: true}
var validate = ajv.compile(schema);
var valid = validate(data);
if (!valid) console.log(validate.errors);

```

**Validation result, data AFTER validation, error messages:**

```
[ { keyword: 'constant',
    dataPath: '.sameArr[0]',
    schemaPath: '#/properties/sameArr/items/constant',
    params: {},
    message: 'should be equal to constant' } ]

```

**What results did you expect?**

validate successfully

**Are you going to resolve the issue?**

No

**Comment by epoberezkin** [comment]
JSON pointer `/arr/0#` means (in JavaScript) `.arr['0#']`

I understand that the intention is to get the index of the current element, but the only defined syntax is `0#`.

There is no syntax to point to the element with the same index in the different array.

You can (possibly programmatically) create the schema using array syntax of `items` keyword when element 0 in one array would point to el 0 in another, 1 to 1, etc.:

``` json
{
    "properties": {
        "arr": {
            "items": [{},{},{}],
            "additionalItems": false
        },
        "sameArr": {
            "items": [
                { "constant": { "$data": "/arr/0" } },
                { "constant": { "$data": "/arr/1" } },
                { "constant": { "$data": "/arr/2" } }
            ],
            "additionalItems": false
        }
    }
}
```

(btw, `additionalItems` keyword when `items` is a schema, as in your example, rather than array, is simply ignored).

Or you can:

``` json
{
    "properties": {
        "arr": {
            "items": [{},{},{}],
            "additionalItems": false
        },
        "sameArr": {
            "constant": { "$data": "/arr" }
        }
    }
}
```

As I wrote in another issue, the only alternative is the custom keyword:

``` json
{
    "properties": {
        "arr": {
            "items": [{},{},{}],
            "additionalItems": false
        },
        "sameArr": {
            "sameItemsAs": { "$data": "/arr" }
        }
    }
}
```

You'll have to write some code to implement the keyword `sameItemsAs` but it's easily doable.

**Comment by eakarsu** [comment]
Thanks for quick update,
Can you please give some hint on how I can implement sameItemsAs keyword?
Any related example or code or any algorithm?
Remember that each element of array can be object or another array.

**Comment by eakarsu** [comment]
Is it possible to use a value (key attribute) in sameArr  to index validated array "arr"?

Here I validate only "abc" field of sameArr against a/b in second entry of "arr" array. The index of second entry is given by "key" field

Can we use another value (key field) in another json pointer?

```
"sameArr": {
            "constant": { "$data": "/arr/"+"./key/"+ "a/b"}
        }

var data = {
    "arr": [ "1":1, "a":{"b":"abc"}}, "bar":{"foo": "bar"} ],
    "sameArr": [ "1":1, "abc":"abc", "bar",{"foo": "bar"} ,"key":1]
};
```

**Comment by epoberezkin** [comment]
I was thinking about JSON-pointer expressions :) It's neither standardised nor supported at the moment. Using custom keywords (see docs) is the only available solution at the moment.

**Comment by eakarsu** [comment]
I have already started for custom keyword "refdata". Here I need 2  key values "targetKey" and "key". I assume that I should be able to fetch them v5 $data. But when validation function is called, $data is not being evaluated. How can I get those key values before my custom validation started?
I appreciate your help

```
scheme ={
"refdata":{
              "basepath":"/tarray",
              "relpath":"a/c",
              "targetkey":{"$data":"/inputRecord/id"},
              "key":{"$data":"1/accountReferenceId"}
          }
}
```

**Comment by epoberezkin** [comment]
Top level $data can be evaluated (with an option). The way you have it, you will have to code for it. You may consider using multiple sibling keywords, although it may become more complex.

You can simplify things a lot by using property name instead of $data reference, assuming that you are referring to the sibling property in the same object as the current data.

**Comment by eakarsu** [comment]
I am sorry I have not got what you said
Which option will I choose for $data to be evaluated before compile phase?

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv#addkeywordstring-keyword-object-definition

But it won't work with your example, Ajv will only evaluate $data if the keyword value is `{ "$data": "..." }`, not if it's used in some sub-property.

**Comment by epoberezkin** [comment]
Closing this issue. There may be a place to do deep $data evaluation, but it seems like an unnecessary complication - several sibling keywords that work together can be used instead ( where some of them simply hold values and some do actual validation - in the same way as maximum/exclusiveMaximum etc. work).
