### ISSUE TITLE
JSON Pointers

### ISSUE THREAD

**Issue by blakeembrey** [ajv-validator/ajv#32]
I'm curious, but why did you use a custom notation instead of using [JSON Pointers](https://tools.ietf.org/html/rfc6901) in error objects?

**Comment by epoberezkin** [comment]
I don't think I was choosing really. I just used JavaScript property access syntax as it can be easily used in the code that processes errors (either with eval or with a library like object-path). And the same (or similar) syntax is also used internally in generated code.

I can see the use case where errors are consumed outside of JavaScript environment (node.js server accessed by non-javascript client). While I don't think it's common, I don't mind having an option say `errorsJsonPointer` or smth like this that would make generated code report errors using JSONPath.

**Comment by blakeembrey** [comment]
That would be cool, I'll look into it if I get a chance. For reference, http://jsonapi.org/ and other formats use pointers as the primary notation format.

Edit: Having a consistent format can be important and, at least, the errors I'm generating is for an API and, most likely, will be consumed outside of JS.

**Comment by epoberezkin** [comment]
That's a relatively easy change - wherever `it.errorPath` or `$it.errorPath` is appended (in doT folder) with path segment using JS syntax, they should be appended using JSONPointer syntax if `it.opts.errorsJSONPointer` is present.

`it.errorPath` maintains the code for "validation-time" (as opposed to compile-time) expression that will evaluate to the path of the data currently validated. It is only used to report errors, nothing else relies on it. So changing it to a different format won't affect anything.

I've just discovered and removed unused `it.dataPath` from everywhere - at some point it was used but not anymore, so if you decide to do it please use the latest commit.

Thanks!

**Comment by epoberezkin** [comment]
@blakeembrey I've found one more case where jsonPointers should be used - fixed.

By the way, with json pointers it reports error message slightly differently in this case (see https://github.com/epoberezkin/ajv/blob/master/spec/errors.spec.js#L93). I think it's not important to be honest.

**Comment by epoberezkin** [comment]
Thanks!
