### ISSUE TITLE
Pass options to validate function at runtime

### ISSUE THREAD

**Issue by mrhooray** [ajv-validator/ajv#322]
Thanks for making this awesome library.

We have a use case that need to do both following operations given a schema
- validate & filter data with compile time option `removeAdditional: true`
- dry run above process without actually removing fields, just to see whether there are errors

We were on v4.0.6 and the approach we took was to compile two validate functions for each schema, one with `removeAdditional: true` and the other with `removeAdditional: 'dryRun'` and modify [related part in properties.jst](https://github.com/epoberezkin/ajv/blob/master/lib/dot/properties.jst#L94-L97) into following:

```
       {{? $noAdditional }}
         {{? $removeAdditional === 'dryRun' }}
         {{?? $removeAdditional }}
           delete {{=$data}}[key{{=$lvl}}];
         {{??}}
```

It works pretty well except doubling the number of validators in memory. We're looking into ways to turn dry run from compile time option into runtime/validation time option to reduce memory usage:

``` js
var ajv = new Ajv({removeAdditional: true});
var validate = ajv.compile(schema);
// actually removing fields
validate(data);
// dry run
validate(
  data,
  /*dataPath*/,
  /*parentData*/,
  /*parentDataProperty*/,
  /*option e.g. {dryRun: true}*/
); 
```

Got lost a few times on how to pass that runtime option to sub/referenced validate functions(recursively?). Could you give some hints on how to do that properly, or is there a better way to do that at runtime?

**Comment by epoberezkin** [comment]
Runtime options would be detrimental for performance for the majority of users who don't need them, so I will not be adding them. You can obviously change it in the fork. Is it what you want? Also bear in mind that validation function has 5 parameters at the moment, so you'll have to use some other way to pass these runtime options, e.g. by attaching them to the function as property(ies).

I also considered compile time options, but the problem is that you will potentially have different functions compiled with different options, and these functions may call each other, so it complicates caching those functions - not only schema but also options should be used as part of the key. It also would complicate api.

Using multiple Ajv instances appears to be a much simpler solution, both from implementation and from users' point of view.

**Comment by mrhooray** [comment]
Yeah in a fork. We started using multiple Ajv instances and compiled functions exactly because of the simplicity but it's growing to heap limit due to the amount/size of schemas.

Following seems to work but want to double check with you to see whether it's correct or there's better ways to do it.

Template Change:

```
      {{? $noAdditional }}
        {{? $removeAdditional }}
           if (!validate.dryRun) {
             delete {{=$data}}[key{{=$lvl}}];
           }
        {{??}}

```

Before/after running validate function, recursively set/reset the flag to each validate function

``` js
var ajv = new Ajv({removeAdditional: true});
var validate = ajv.compile(schema);
// set dry run
markDryRun(validate, true)
// reset
markDryRun(validate, undefined)

function markDryRun(v, dryRun) {
    if (v.dryRun === dryRun) {
        return;
    }

    var i;

    v.dryRun = dryRun;

    for (i = 0; i < v.refVal.length; i++) {
        if (typeof v.refVal[i] === 'function') {
            markDryRun(v.refVal[i], dryRun);
        }
    }
}
```

**Comment by epoberezkin** [comment]
Re heap size: use option sourceCode: false (it will be the default in the next major version anyway).
I will look at the rest later.

**Comment by epoberezkin** [comment]
Not sure what you mean to each function... You really need to either set to all cached validation functions or pass it to referenced schemas (in ref.jst). It is probably simpler to set this flag on the instance, it is available as `self`. Actual property removal happens in 3 places in properties.jst file (just search for "removeAdditional" or for "delete").

EDIT: Actually yes, you can iterate refVal array. But on the instance is probably cleaner. It all gets complicated though if you use async validation. In this case you can use validation context and pass it with option passContext: true.

You will have to call validation function as `v.call(context, data)` - context can be anything you want, it will be `this` everywhere.

**Comment by epoberezkin** [comment]
@mrhooray please close if it's resolved. Thank you!

**Comment by mrhooray** [comment]
Thanks for the hints and I'll do more digging among these options.

> It is probably simpler to set this flag on the instance
> But on the instance is probably cleaner

I think the instance you mentioned here is instance of Ajv, via `new Ajv()`, right?

**Comment by epoberezkin** [comment]
Correct, ajv instance. In code templates it's `self` and you can assign some custom properties to it. Maybe I should reserve some name for user object to provide a guarantee it's never used...
Passing validation context as I suggested is also safe and already documented option; it also can be used for async validation, so maybe it's a bit cleaner and future proof approach.
