### ISSUE TITLE
oneOf will not validate if includes a format

### ISSUE THREAD

**Issue by onury** [ajv-validator/ajv#339]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.8.2

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
{
    formats: {
        alphabetic(value) {
            return typeof value === 'string' && /^[a-z]+$/i.test(value);
        }
    }
}
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
{
    "oneOf": [
        { "format": "alphabetic" },
        { "type": "integer" }
    ]
}
```

**Data (please make it as small as posssible to reproduce the issue):**

```json
10
```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
let ajv = new AJV({
    formats: {
        alphabetic(value) {
            return typeof value === 'string' && /^[a-z]+$/i.test(value);
        }
    }
});
const validate = ajv.compile({
    "oneOf": [
        { "format": "alphabetic" },
        { "type": "integer" }
    ]
});
validate(10); // —> false
```

**Validation result, data AFTER validation, error messages:**

```
[ { keyword: 'oneOf',
    dataPath: '',
    schemaPath: '#/oneOf',
    params: {},
    message: 'should match exactly one schema in oneOf' } ]

```

**What results did you expect?**
value `10` should validate successfully.
Note that this will validate if I don't use the `format` keyword within `oneOf`.

**Are you going to resolve the issue?**

**Comment by onury** [comment]
Here is a runkit: https://runkit.com/onury/ajv-issue-339

**Comment by epoberezkin** [comment]
`oneOf` is valid when only one subschema in it is valid. `10` is valid according to both subschemas. That's why the final result is invalid. That's all according to the spec, nothing Ajv specific here.

**Comment by epoberezkin** [comment]
You probably need to add `"type": "string"` to the subschema with `format` keyword.

**Comment by onury** [comment]
I don't get it. How is number `10` alphabetic? It's not even a string.
`10` is not valid `alphabetic` format but it's a valid `integer`. So it's valid for exactly one sub-schema. 

I believe you should re-open this issue.

It works if I add `"type": "string"` but I still think this should not be mandatory, for 2 reasons:
- `format` is already only for strings
- My validator function already checks for that (already returns false)

**Comment by epoberezkin** [comment]
The behaviour you disagree with is by the spec. "Format is only for strings" and "format requires that the data is a string" is not the same thing, the former means that format only applies to strings, for everything else it is valid.

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#type

**Comment by epoberezkin** [comment]
All type specific keywords defined by JSON schema do NOT require that the data is of any type, so type restriction should always be explicitly applied.

**Comment by onury** [comment]
fair enough.. thanks.
