### ISSUE TITLE
fast-stable-stringify

### ISSUE THREAD

**Issue by kapouer** [ajv-validator/ajv#340]
https://github.com/nickyout/fast-stable-stringify
might be a better maintained alternative to the current module.
It is GPL3 though.

**Comment by epoberezkin** [comment]
@kapouer thanks for the suggestion, I will think about it. Maybe make a PR so that we can see that all tests are passing?

**Comment by kapouer** [comment]
Thinking of which, i'm surprised you don't use the schema id to build a cache key (if it exists of course).
This would work unless the schema is mutable, and would avoid the cost of building that key.

**Comment by epoberezkin** [comment]
id is optional... They also can be subschemas (when you use $refs).

**Comment by alexkuz** [comment]
@epoberezkin is it possible to use schema itself as a cache key and move `stableStringify` in the default `Cache` object? That way one could replace `Cache` with `WeakMapCache` for example, that would use WeakMap with raw (immutable) schemas as keys.

**Comment by epoberezkin** [comment]
@alexkuz I think it can be done in 5.0.0, need to think about it.
The downside is that if the same fragments exist in different places they will be compiled twice. Maybe it's an edge case.

Why do you want it, I wonder?

**Comment by epoberezkin** [comment]
Actually, [sacjs](https://github.com/epoberezkin/sacjs) that can be used as an alternative already has json-stable-stringify inside...

**Comment by alexkuz** [comment]
I'm using `ajv` with huge schemas and it goes really slow - mostly because of `json-stable-stringify` (I compared it with `JSON.stringify` on simple test - the latter goes 5 times faster). Maybe it will be better after I refactor my own code, it's quite unoptimized right now, but I suspect this would be still a bottleneck, which I could avoid using WeakMap.

**Comment by epoberezkin** [comment]
I see. I suspected something like this... What is huge? I guess you retrieve by id, but it still takes some time to cache them... Also it can consume a bit of memory.

Feel free to make a PR (move stringify to cache and update docs) to 5.0.0 branch, I am going to release the next beta soon (although there will be some migration effort needed).

Is it maybe a good idea to always use weakmap if they are available? It'll just have to take into account that schemas can be Boolean, although it's an edge case when they'll be cached separately.

**Comment by epoberezkin** [comment]
Probably better to make it a separate package

**Comment by alexkuz** [comment]
Ok, I'll try to implement new caching later.

Here's the simple test I used:

```js
'use strict';

var getAjvInstances = require('./spec/ajv_instances');


var instances = getAjvInstances({
  allErrors:    true,
  verbose:      true,
  inlineRefs:   false
});

var i;

var schema = {
  id: 'http://x.y.z/rootschema.json#',
  properties: {
    foo: { '$ref': '#/definitions/schema0' }
  },
  required: [ 'foo' ],
  definitions: {}
};

for (i = 0; i < 1000; i++) {
  schema.definitions['schema' + i] = {
    id: 'schema' + i,
    type: 'integer'
  };
}

instances.forEach(function (ajv) {
  for (i = 0; i < 1000; i++) {
    var validate = ajv.compile(schema);
    var data = { foo: 1 };
    validate(data);
  }
});
```

It runs for 30+ seconds, and it's just 5 seconds if I place `return JSON.stringify(obj);` in `json-stable-stringify`.

**Comment by epoberezkin** [comment]
@alexkuz thank you. You do know that it serialises the schema 8000 times in this case, so it's 3.7ms vs 0.6ms per time (even though it's a big schema), and it normally happens only once.

It's better not to call compile every time you need to use the schema... During run-time it's a better idea to use getSchema that accepts schema uri (id in this case) - it will be retrieving validation function from a different map in this case, and it will be much faster. Maybe it needs some better explanation in docs...

In any case, I don't mind moving json-stable-stringify to cache.js, please update docs too if you do it.

WeakMap cache can be a separate package, no point overloading ajv with it.

**Comment by alexkuz** [comment]
Sure, that was just to demonstrate the difference between two serialization methods.

Actually, I rewrote today https://github.com/dancasey/json-schema-default-instance, that I'm using to get default values, so that it's not using its own `ajv` instance - and it works much faster now, I think there was my main problem.

But still I think that rewrite would be useful, I'll give it a try. Thank you too!

**Comment by epoberezkin** [comment]
@kapouer I am thinking to provide `serialize` option instead: https://github.com/epoberezkin/ajv/issues/385#issuecomment-269705947
