### ISSUE TITLE
Feature Request. Filter out array's items during validation

### ISSUE THREAD

**Issue by acheshkov** [ajv-validator/ajv#351]
**Use case example:** i want remove all items in the array that violate schema.

**Comment by epoberezkin** [comment]
Have a look at [inline custom keywords](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-inline-compilation-function) - I think using them for can be a better idea that making it an Ajv feature.

**Comment by acheshkov** [comment]
Evgeny,

as far as i understood keywords feature is about validation. In my case i have to validate + transform json document.

**Comment by epoberezkin** [comment]
@acheshkov you can transform document with keywords too. You need to use inline keywords as other kinds don't give you access to errors (which will be the criteria to filter items).

**Comment by acheshkov** [comment]
@epoberezkin please correct me. you suggest is 

- define keyword and inside define custom validation function through  **doT** template or string
- inside validation function i have to push error inside **vErrors** array
- eventually something in the library removes invalid data 

is it ?

**Comment by epoberezkin** [comment]
> inside validation function i have to push error inside vErrors array
eventually something in the library removes invalid data

It's the other way around - based on validation errors in vErrors for the failed array items (this would indicate that they have to be removed) your keyword removes these items, removes the errors related to these items and then returns true. The keyword would exist on array level.

> through doT template

You don't have to use doT template, your keyword function just have to return code snippet as a string (your function will be called during schema compilation, the code snippet will be executed during validation as a part of validation function).

**Comment by acheshkov** [comment]
I tried to declare simple keyword, that should remove data always

```javascript
ajv.addKeyword('deleteAnyway', { inline: function (it, keyword, schema) {
    return '(vErrors = (vErrors === null) ? [] : vErrors) && vErrors.push({"keyword": "deleteAnyway", "message": "test"}) && errors++ && false';
    }, metaSchema: { type: 'boolean' } 
});
```

i see the error in a validation results, but data **is not removed**.

**Comment by epoberezkin** [comment]
As I wrote above, you have to remove the data yourself. And you have to check if there is an error associated with a particular item (there may be some other error) to decide what to remove.

**Comment by acheshkov** [comment]
@epoberezkin how i can use **for** statement inside inline string function ? I got error ""Unexpected token for" during compilation. 

example 

`return "for (var i=data2.length-1;i>=0; i--){i % 2 == 0 ? data2.splice(i,1) : void 0}"`

**Comment by epoberezkin** [comment]
you probably need to use `statements` option, as by default Ajv expects expression. Please see: https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-inline-compilation-function

**Comment by acheshkov** [comment]
@epoberezkin 

the code snippet like this can not be compiled, i guess it because of "function"

`valid3 = (function (d, s) { return true; })(data3, validate.schema.properties.data.filterRel)`

any workarounds ?

**Comment by epoberezkin** [comment]
What is the error?

**Comment by acheshkov** [comment]
The message is

`SyntaxError: Unexpected token if  at localCompile ... node_modules/ajv/lib/compile/index.js:138:26"
`

**Comment by epoberezkin** [comment]
The error is in your generated code - just put it in any JS validator and it will show you where. Most likely some unbalanced parens or missing semicolon. Also using JS-beautify simplifies debugging. If you can't resolve, submit another issue with all information - there is not enough info here to understand what's going on. Closing this one.

**Comment by acheshkov** [comment]
@epoberezkin the problem was a missing semicolon character. thank you !
