### ISSUE TITLE
Detect if schema has been added or overwrite a schema without errors ?

### ISSUE THREAD

**Issue by mmc41** [ajv-validator/ajv#352]
I have a case with the latest Ajv (4.9.0) where I need to add multiple schemas lazily with multiple separate calls to ajv.addSchema. Unfortunately, there seem to be no easy way to detect if a schema has been added already (regardless of compilation status). If I call addSchema twice with the same id I get an exception and from the docs the getSchema method appears to work with compiled schemas only so I can not use this method to simply check if addSchema has been called already ?

It would be nice if addSchema could take an option where it would ignore or overwrite an existing schema OR if there could be a method to check if a schema has been added already (compiled or not).

**Comment by epoberezkin** [comment]
`getSchema` compiles schema, you don't have to compile it separately.

So you can use `addSchema` to add and `getSchema` to retrieve (and compile, if it wasn't compiled before). If the schema doesn't exist, `getSchema` should return undefined.

Does it just need clarification in the docs or it is not sufficient for your use case? Some context of your use case would be helpful. Also, have you seen `compileAsync` method?

In any case, as a temporary workaround you can use `ajv._schemas[id] || self._refs[id]` to check the schema.

**Comment by mmc41** [comment]
Thank you very much for the explanation. I think it is sufficient. Maybe a bit clarification of the docs for getSchema would be a good idea. I thought getSchema would only return something if already compiled.

**Comment by epoberezkin** [comment]
> I thought getSchema would only return something if already compiled.

@mmc41 thank you for the reply and closing. I will clarify in docs.
