### ISSUE TITLE
Support options.loadScheme in synchronous compile()

### ISSUE THREAD

**Issue by angelowang** [ajv-validator/ajv#364]
**What version of Ajv you are you using?**
4.9.1

**What problem do you want to solve?**
We are using Jenkins to monitor a repo which consists of some json schema and some test json. The json schema files contain references which should be using loadSchema for custom loading.
To use loadSchema, we have to use compileAsync(), but it's asynchronous, so the node process already exits and no results can be collected.

**What do you think is the correct solution to problem?**
Support loadSchema in compile().

**Will you be able to implement it?**
not capable enough :)

**Comment by epoberezkin** [comment]
@angelowang loadSchema is asynchronous itself. How can it be used in synchronous function?
Is it not sufficient to add all required schemas in advance with addSchema?

**Comment by angelowang** [comment]
Thanks for the response. 
Our Jenkins will scan all folders recursively and compile them one by one. And 
These schema files are in various folders, and it's not clear which should be added in which order. Or maybe I am new to ajv, I don't need to care about the order?

An alternative is having a simple way to make my main process wait until the compileAsync() finishes, something like Promise.

**Comment by epoberezkin** [comment]
> These schema files are in various folders, and it's not clear which should be added in which order.

Yes, order in which you pass schemas to addSchema is not important. You can load them all in array/object and then pass via options property `schemas` when you create Ajv instance. And then they will be compiled when you call getSchema.

> An alternative is having a simple way to make my main process wait until the compileAsync() finishes, something like Promise.

Yes, also possible.

**Comment by epoberezkin** [comment]
@angelowang closing this issue, seems like your situation is covered.
