### ISSUE TITLE
URI formatting weirdness

### ISSUE THREAD

**Issue by dubiousdavid** [ajv-validator/ajv#374]
Uses latest ajv. Lot's of examples. Click the code to expand (RunKit oddity).

https://runkit.com/dubiousdavid/ajv-uri-bug

**Comment by epoberezkin** [comment]
Why "3" should be a valid URI?

**Comment by dubiousdavid** [comment]
It shouldn't, which is why that fails to validate. I wanted at least one example of a proper failing case.

**Comment by epoberezkin** [comment]
Then what is the problem?

**Comment by epoberezkin** [comment]
If you mean other URLs then you can use `format: 'full'` option that does slower but more correct validation.

**Comment by epoberezkin** [comment]
Actually, no. Maybe they are valid URIs?

**Comment by epoberezkin** [comment]
The last 4 (including "3") fail in `"full"` mode

**Comment by epoberezkin** [comment]
You can use less permissive "url" format: https://runkit.com/esp/584b14bae50294001406f653
None of the examples above pass it. Also see #481
