### ISSUE TITLE
For successful asynchronous validations, return the validated data instead of `true`

### ISSUE THREAD

**Issue by robertwbradford** [ajv-validator/ajv#377]
**What version of Ajv you are you using?**
`4.10.0`

**What problem do you want to solve?**

When using asynchronous validation, it is likely that the user will be doing something with the data object after it is validated. Since the `then` is reached only if the data object is valid, it's not useful to have it return a `true` value. Instead, if it returned the now-validated original data object, we could then easily chain things.

**What do you think is the correct solution to problem?**

Say we have the following simplified application:

```javascript
const AJV = require('ajv'),
      ajv = new AJV();

const validate = ajv.compile({
  "$async": true,
  "properties": { ... }
});
```

Now say we want a `render` function that first checks whether the given `something` object is valid and then actually renders it when the object is valid.

```javascript
function render(something) {
  return validate(something)
    .then(function (valid) {
      // "valid" is always true here
      actuallyRender(something);
    })
    .catch(function (err) {
      if (!(err instanceof Ajv.ValidationError)) throw err;
      // data is invalid
      console.log('Validation errors:', err.errors);
    });
}

function actuallyRender(something) {
  console.log('Actually rendering', something);
}
```

For the `then`, we have to create a new function which then calls what we actually want to do with the data object. The `render` function could be simplified if the `validate` resolve value was the valid data object:

```javascript
function render(something) {
  return validate(something)
    .then(actuallyRender)
    .catch(function (err) {
      // ...
    });
}
```

**Will you be able to implement it?**

I looked through the source, but I'm not seeing where to modify this return value.

**Comment by epoberezkin** [comment]
The proposed change is simple - it's this line: https://github.com/epoberezkin/ajv/blob/master/lib/dot/validate.jst#L174

Plus a couple of other related lines (see comment there), docs and tests.

It can be done in 5.0.0.

I'm always [a bit reluctant with api changes](https://github.com/epoberezkin/ajv/blob/master/FAQ.md#ajv-api-for-returning-validation-errors) that can be implemented with a simple wrapper; in this case you can:

```javascript
var validateWrapper = (data) => validate(data).then(()=>data);
```

And it gives you what you want so you can:

```javascript
validateWrapper(data).then(render, handleErrors);
```

But given that the current return value for async validation is ALWAYS the same and it is something that was bothering me from the very beginning, maybe it is a strong enough reason to resolve Promise with something more useful. Also in all practical cases even if there is some `if` with that value (although it's not needed), unless the data is some falsy primitive, which would be highly unusual, it would still work, so it would be almost fully backwards compatible change.

**Comment by robertwbradford** [comment]
Thanks for the reply. Great module, btw. 

That's what I was thinking too about the backwards compatibility. Of course, never say never, but it seems that most data objects would be a truthy value. Besides, a major release to `5.0.0` would mean some "breaking" changes anyway :)

Thanks again, look forward to the next release!

**Comment by epoberezkin** [comment]
In [5.0.1-beta.0](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.0)
To use: `npm install ajv@^5.0.1-beta`
