### ISSUE TITLE
Allow to track unknown additional properties found

### ISSUE THREAD

**Issue by gerodp** [ajv-validator/ajv#379]
**What version of Ajv you are you using?**
4.10.0

**What problem do you want to solve?**
When a schema sets additionalProperties to false or to another schema and the input data contains additional properties not present in the schema I'd like to known which are those additional properties. This is useful if the client starts sending new properties in the JSON and I want my software to continue processing it while notifying me that there are new properties in the JSON, that could require an adaptation of the program, for example.

**What do you think is the correct solution to problem?**
One possible solution is to create a new option 'warnings' : (true|false) that indicates that warnings will be collected. Then for each additional property found a new warning will be added. These warnings will be accessible via the validate object  (.e.g.: validate.warnings)

In the future warnings can be used to signal other situations.

**Will you be able to implement it?**
Yes

**Comment by epoberezkin** [comment]
I don't think I like it as a designated option/feature designed specifically for additionalProperties to be honest.

It seems like it could be a part of a bigger feature - converting some errors into warnings. As such, it could have been a part of https://github.com/epoberezkin/ajv/issues/100 - custom keyword(s) for processing/reporting errors (there is even a bounty on it and a pledge from @crkepler to match contributions).

I suggest, as a starting point, to contribute a custom keyword say `warningKeywords` to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords) that would take parameters to specify errors in which keywords should be converted to warnings. E.g.:

```json
{
  "properties": {
    "foo": {}
  },
  "additionalProperties": false,
  "warningKeywords": ["additionalProperties"]
}
```

would mean that errors in "additionalProperties" in the current schema (and maybe in subschemas too) should be converted to warnings.

It would satisfy your use-case and also would be a useful bolt-on for some other users. Eventually it can evolve into more generalised error processing for #100.

Another approach would be to use two schemas generated from a single source (with and without additionalProperties), and the diff between errors will be the warnings - I would have done it this way to be honest.

**Comment by epoberezkin** [comment]
An even simpler approach could be to clone data, use `removeAdditional: true` (or `removeAdditional: 'failing'`) option and diff the data after validation (by using [JSON Merge Patch (RFC 7396)](https://tools.ietf.org/html/rfc7396) or [JSON Patch (RFC 6902)](https://tools.ietf.org/html/rfc6902) - there are several good implementations for both specs) - it will give you the additional properties without failing validation.
