### ISSUE TITLE
fails when id in schema is not a string (invalid schema) - improve error reporting

### ISSUE THREAD

**Issue by scott-martin** [ajv-validator/ajv#380]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.10.2

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "first_name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "last_name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "phone_number": {
      "type": "string",
      "format": "phone"
    },
  },
  "required": [
    "id",
    "first_name",
    "last_name",
    "phone_number"
  ]
}
```

**Data (please make it as small as posssible to reproduce the issue):**

```json
{
  "id": 1,
  "first_name": "Draco",
  "last_name": "Malfoy",
  "phone_number": "+18435550001"
}                   
```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript

'use strict';

const Ajv = require('ajv');
const schema = require('./contact.schema');
let ajv = Ajv({ allErrors: true });
ajv.addFormat('phone', () => { return true; });
ajv.compile(schema);

exports.validate = function (data) {
    ajv.validate(data);
    return ajv.errors;
};
```

**Validation result, data AFTER validation, error messages:**

```
TypeError: id.replace is not a function
    at Function.normalizeId (/XXXX/node_modules/ajv/lib/compile/resolve.js:216:18)
    at _addSchema (/XXXX/node_modules/ajv/lib/ajv.js:282:22)
    at Ajv.validate (/XXXX/node_modules/ajv/lib/ajv.js:94:23)
```

Currently using integer ids in my project. As you can see, ajv is failing because there is no `replace` function on the integer type in Javascript.

**Comment by epoberezkin** [comment]
@scott-martin please check docs - there are 3 suggested options in [Getting started](https://github.com/epoberezkin/ajv#getting-started), you are not using it correctly. `ajv.validate` expects a schema as the first parameter.

**Comment by epoberezkin** [comment]
Maybe better error reporting [here](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.js#L282) would be helpful...

**Comment by epoberezkin** [comment]
in [5.0.1-beta.3](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.3)
