### ISSUE TITLE
Option serialize to be able to replace json-stable-stringify

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#385]
So that objects (or booleans) are passed as keys to cache, rather than strings.

Reasons:
- WeakMap can be used as cache
- sacjs that is suggested as alternative serialises keys already using json-stable-strigify

See https://github.com/epoberezkin/ajv/issues/340#issuecomment-269140439

**Comment by epoberezkin** [comment]
@alexkuz I looked at the code and it seems it can't be done without making the default case performance worse.

Ajv stringifies schemas only once and then the string is used first to check whether the schema is present and then to save the schema in cache if not (and it can't be combined in a single cache call because there is schema compilation between `cache.get` and `cache.put`).

There is another, less common use case when these strings are re-used - when all schemas are removed...

Moving json-stable-stringify inside cache would mean that the schema will have to be stringified twice every time the schema is added.

So, unless you have an idea how this problem could be addressed, I don't think this is an acceptable change.

**Comment by alexkuz** [comment]
@epoberezkin yeah, I saw that _just_ moving it to cache wouldn't work, but hadn't look deeply into the code, that's why I asked if it is possible. I suppose it could be done with some refactoring though.

**Comment by epoberezkin** [comment]
The problem is that if it is inside the cache then it will be called multiple times for the same schema, however it is refactored...

**Comment by alexkuz** [comment]
The easiest way I see is to add `getKey` method that would return `stableStringify(schema)` for default Cache and `schema` itself for WeakMapCache:

```js
var Cache = {
  getKey: schema => stableStringify(schema),

  get: key => ...,

  put: (key, value) => ...,

  ...
};

var WeakMapCache = {
  getKey: schema => schema,

  get: key => ...,

  put: (key, value) => ...,

  ...
};
```

this would require minimal changes in the rest of the code.

**Comment by epoberezkin** [comment]
It works. That can even be:

```javascript
var Cache = {
  serialize: stableStringify,
  ...
};
```

to avoid extra function call, in which case the default behaviour won't change at all.
And schemaObj can store that key as well (now it's called jsonStr, and it will be cacheKey), to avoid calling this method every time.

Serialize would take the key and return serialized key.

**Comment by epoberezkin** [comment]
@alexkuz I think that all that is needed to address your use case is `serialize` option. Otherwise it doesn't make any sense... Not sure I like one more option, but alternatives are worse. Apart from doing nothing :)
