### ISSUE TITLE
Why not just required:true

### ISSUE THREAD

**Issue by iyobo** [ajv-validator/ajv#386]
I see this array of strings needed to specify required fields, but why can't we just do this?

{
...
field1: {type: string, required:true},
field2: {type: number, required:true},
...
}

**Comment by epoberezkin** [comment]
Because it's not part of the JSON-schema standard that Ajv implements.

**Comment by epoberezkin** [comment]
The reason why it was removed from the standard (it existed in draft-03) is most likely the fact that you can't impose requirement on something that does not exist and never gets validated. And you can't impose the requirement on the parent data from the schema that applies to the child data.

These are general design principles of JSON schema.
