### ISSUE TITLE
Remove (or reduce) `addKeyword()`'s requirement that `keyword` is a valid JS identifier

### ISSUE THREAD

**Issue by farrago** [ajv-validator/ajv#389]
**What version of Ajv you are you using?**
4.3.10

**What problem do you want to solve?**
[Swagger](http://swagger.io/) API definitions use JSON Schema to define input and output values.  However, the swagger [spec for vendor extensions](http://swagger.io/specification/#vendorExtensions) (i.e. custom keywords) says they MUST start with `x-`.  

This is incompatible with `addKeyword()`'s requirement that keywords must be a valid JS identifier.  So as it stands, ajv can't be used to validate any custom keywords / vendor extentions in conjunction with Swagger.

**What do you think is the correct solution to problem?**

From looking at `keyword.js` I can't see why this test is in place as the name doesn't seem to be used as a JS identifier directly (i.e. all property accessors use bracket notation rather than dot notation, so any string is ok).

I also tested just commenting out the test, and was able to successfully add and validate against a keyword called `x-test-keyword`.

I presume I am missing something as it was deliberately added in commit 694e81684fcbc0e29ef787764779f42c2c4f5196.  I'm assuming it's something to do with macro function keywords (which I haven't used)?

Based on the above, my proposal is to entirely remove the constraint, or potentially only check it if a `macro` function is being specified.  Does either sound reasonable?

**Will you be able to implement it?**
Happy to, if the proposed solution seems reasonable?

**Comment by epoberezkin** [comment]
I think it is used as property access somewhere in .jst files, probably in custom.jst, errors.def, maybe in compile/index.js too (the part that generates code?)

What is the limitation you propose instead? If it is identifier with optional hyphens inside (not starting or trailing) I don't mind.

The starting point it to write a couple of additional tests in custom.spec.js (or maybe just change camel case to dash case in some examples) to see where it fails.

**Comment by farrago** [comment]
Thanks for the quick response!

You're right, it appears to be failing on compiled code.  If I comment out the `if` that checks for valid JS identifiers, then change `custom.spec.js`: `testEvenKeyword()` to use `x-foo` as the keyword instead of `even`, then all 6 tests that use testEvenKeyword() fail with errors that look like:

```
1) Custom keywords custom rules rule with "interpreted" keyword validation should add and validate rule:
     ReferenceError: foo is not defined
      at validate (eval at localCompile (lib\compile\index.js:139:26), <anonymous>:3:397)
      at shouldBeValid (spec\custom.spec.js:863:5)
      at spec\custom.spec.js:692:7
      at Array.forEach (native)
      at testEvenKeyword (spec\custom.spec.js:687:15)
      at Context.<anonymous> (spec\custom.spec.js:25:9)
```

where `compile\index,js:139` is unsurprisingly `var makeValidate = new Function(...`.
My assumption would therefore be that there is indeed some statement along the lines of  `bar = x-foo;`  (where "x-foo" is the keyword) being created in the code.  This also (as shown) applies to more than just the macro keywords and it's relation to that in the commit's message appears to be coincidental.

I haven't had a look at the generated code yet but it sounds like it might be quite a bit bigger than my naive first look (if not impossible or at least too complex for a corner case).

I'm on Windows where a lot of the npm scripts don't work, so I may run up a VM tomorrow and look a bit further.  Do you think there's much point in that, or does it look like something that's intrinsic to the design and not likely to be easily changeable?

**Comment by epoberezkin** [comment]
It should be relatively straightforward change - you'll need to use `{{=it.util getProperty(keyword)}}` instead of `.{{=keyword}}` where it is used to access a property, most likely within the files I mentioned above, maybe some others.

**Comment by farrago** [comment]
I've added a pull request for this, though - assuming you're generally happy with the change - we need to agree the limitations you would like to keep on the keyword name.

In theory, I believe any string can be used in brackets notation, though I read a few rumours that some reserved words were not allowed by some older browser implementations.  

Some suggestions might be:
1. allow any string
1.1 most flexible, but also most likely to allow names that might cause issues
2. add `-` to the list of valid characters for all but the first char
2.1 i.e. change  `/^[a-z_$][a-z0-9_$]*$/i` to  `/^[a-z_$][a-z0-9_$\-]*$/i`
2.2 minimum change that fixes the specific issue with swagger
3. add a blacklist of reserved words (e.g. toString, switch, case, etc.)
3.1 might give more flexibility with some protection, but blacklists are always wrong and/or incomplete and a maintenance nightmare.
4. Something else?

Let me know your thoughts and I'll update the pull request.

Also, I tested this by changing the keywords for some existing tests to not be valid identifiers.  If you prefer a different set of tests or I've missed some important cases then please let me know and I'll update.

**Comment by epoberezkin** [comment]
Thank you. I prefer 2 - just add hyphen to the list of allowed characters but the first.
