### ISSUE TITLE
Integers rejected

### ISSUE THREAD

**Issue by IBwWG** [ajv-validator/ajv#390]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

4.10.3 (on node 7.3.0 on win7x64sp1)

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
undefined
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
{
  "type": "object",
  "properties": {
    "count": {
      "type": "integer"
    }
  },
}
```

**Data (please make it as small as posssible to reproduce the issue):**

```json
{
    "count": "1"
  }
```

**Your code (please use `options`, `schema` and `data` as variables):**

(As you can see, this is not a dupe of #380 because I am calling on the results of `compile()`.)

```javascript
const Ajv = require('ajv');
const ajv = new Ajv(); 

const schema = {
  "type": "object",
  "properties": {
    "count": {
      "type": "integer" // if this is "string", no error is thrown, everything works
    }
  },
};
const validate = ajv.compile(schema);

const conformsToSchema = () => (hook) => {
	const valid = validate(hook.data);
	if (!valid) {
	  throw new Error('Invalid json: ' + JSON.stringify(validate.errors, null, 2));
	}
};
```

**Validation result, data AFTER validation, error messages:**

```js
// valid===false and this gets thrown:
"Invalid json: [\n  {\n    \"keyword\": \"type\",\n    \"dataPath\": \".count\",\n    \"schemaPath\": \"#/properties/count/type\",\n    \"params\": {\n      \"type\": \"integer\"\n    },\n    \"message\": \"should be integer\"\n  }\n]"
```

**What results did you expect?**
I would expect that 1 would be treated as an integer, and pass the validation.  :)

**Are you going to resolve the issue?**
Maybe with help?  I'm completely new to ajv and was surprised when this feature did not work as expected.

**Comment by IBwWG** [comment]
Is https://github.com/epoberezkin/ajv/blob/7c95ec9fa83f707090d3103b8db97b1061130e6d/lib/compile/util.js#L48 the relevant line or am I looking in the wrong place?  I find it hard to believe I'd be the first one to notice this, though...?

**Comment by epoberezkin** [comment]
`"1"` in your data is a string, it is not an integer. So the validation should fail in this case.

There is an option [coerceTypes](https://github.com/epoberezkin/ajv#coercing-data-types) that converts data to the expected type, it also changes underlying data, not just passes validation.

**Comment by epoberezkin** [comment]
This would have passed:

```json
{ "count": 1 }
```

**Comment by IBwWG** [comment]
OK, it is in that representation.  But this still holds true via CURL using `-d 'count=1'`

**Comment by IBwWG** [comment]
Is it not a normal context to be validating things on the server that were sent as parameters and are therefore strings by default (or arrays of strings)?

**Comment by epoberezkin** [comment]
JSON-Schema is about validating JSON, where strings and numbers are distinct.

Option coerceTypes is exactly for this (and similar) situations.

**Comment by IBwWG** [comment]
Thank you for mentioning coerceTypes, that does the trick perfectly.  I see now the distinction--apparently my app sends form data in parameters and only uses JSON for the response, rather than JSON both ways.  Makes sense.  Thanks for your help!
