### ISSUE TITLE
Throw exception if $schema is present and it is not a string

### ISSUE THREAD

**Issue by tizmagik** [ajv-validator/ajv#394]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Latest

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
{}
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json

{
  "thing": {
    "type": 123,
  },
}

```

**Data (please make it as small as posssible to reproduce the issue):**

```
n/a
```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
const Ajv = require('ajv');
const ajv = new Ajv();

const isValid = ajv.validateSchema({
  thing: {
    type: 123,
  },
});

console.log(isValid); // true ??
```

**Validation result, data AFTER validation, error messages:**

```
none
```

**What results did you expect?**
returns `false`

**Are you going to resolve the issue?**
I'd be happy to, unless the issue is I'm doing something wrong (likely)

**Comment by epoberezkin** [comment]
`thing` is "an additional property" in the schema and the specification allows additional properties to be present. It's only if the value of defined keyword were invalid, schema validation would fail, e.g. `minimum: false` instead of a number.

Usually you don't have to explicitly validate schemas - they are validated when they are added to Ajv instance (unless you disable it).

**Comment by tizmagik** [comment]
@epoberezkin I can't re-open but here's the edge-case that I brought up on Gitter. Let me know if you'd like me to open a new issue or if you can edit the original description here.

```js
const Ajv = require('ajv');
const ajv = new Ajv();

const isValid = ajv.validateSchema({
  $schema: {
    thing: {
      type: 'asdf',
    },
  },
});

console.log(isValid); // true ??
```

**Comment by epoberezkin** [comment]
in [5.0.1-beta.3](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.3)
