### ISSUE TITLE
Allow underscores in email domains

### ISSUE THREAD

**Issue by wdullaer** [ajv-validator/ajv#396]
We're using ajv to validate customer data.
We have quite a few records which have an underscore in the domain part of the email address: `example@my_domain.com`

I have done a bit of research and it seems like ajv uses the regex mentioned in the HTML 5 specification. According to this, underscores are not allowed in the domain.
However in practise these email addresses are used and they do work (because underscores are allowed in dns entries).

Given my use case, the appropriate action is to be lenient and accept these email addresses.

I am mainly creating this issue to see whether it is worth opening a PR with the changed regex.

**Comment by epoberezkin** [comment]
It seems like email should have _ allowed, as this limitation applies to hostnames (as part of URL) only. I am ok with the change but please refer to the sources (EDIT: I mean references to normative documents) and it should go into 5.0.0 branch.

**Comment by wdullaer** [comment]
I'll try to open a PR shortly

**Comment by epoberezkin** [comment]
Closing, see https://github.com/epoberezkin/ajv/pull/397#discussion_r97484697
