### ISSUE TITLE
v4 draft meta-schemas reference issue

### ISSUE THREAD

**Issue by miljan-aleksic** [ajv-validator/ajv#409]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.0.1-b3

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

No custom options.

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#"
}
```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
ajv.validateSchema(MySchema)) {
```

**Validation result, data AFTER validation, error messages:**

```
Error: no schema with key or ref "http://json-schema.org/draft-04/hyper-schema#"
```

**What results did you expect?**
I expect the schema and hyper-schema to be loaded and it reference recognized as explained in the docs.

**Are you going to resolve the issue?**
I solved it by loading them by my self. Not a good solution.

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.0 - the part about Migrating.

That's the expected behaviour. Ajv 5.0.0 will implement draft-06 that's about to be published ($id is outstanding though).
Loading draft-04 meta-schema for users who only use draft-06 schemas is wasteful and shouldn't be the default behaviour.

**Comment by epoberezkin** [comment]
Just noticed you're talking about hyper-schema. The argument about not loading it by default applies even more.

**Comment by miljan-aleksic** [comment]
Yeah, but loading manually the `hyper-schema` failed because the `schema` ref was missing. I didn't saw the upgrade steps. All ok. Thanks.
