### ISSUE TITLE
Correct behaviour or not: Getting a schema compilation error when a $data reference points outside the root of the subschema

### ISSUE THREAD

**Issue by sondrele** [ajv-validator/ajv#411]
## The scenario is uploaded to runkit:
https://runkit.com/sondrele/589c81cd11ea6e0014d53f0f

**Problem:**
First, I had expected the schema to compile (no matter where the json pointer was pointing).

Then, given that the schema had been compiled successfully, I had expected the validation to succeed (at least in the provided example) because of the `$data` being resolved to `undefined` instead of `["FOO", "BAR"]` (due to the relative json pointer pointing to a property that does not exist).

The documentation on [$data reference](http://epoberezkin.github.io/ajv/#data-reference) states (in the last paragraph) the following: `$data reference is resolved safely - it won’t throw even if some property is undefined.`

However, the schema compilation fails because the `$data` reference points outside of the root level of the subschema. The documentation only says that a *relative JSON pointer cannot do this*, but not that it will fail to compile the schema. 

I am not sure whether I've interpreted the documentation wrong, and that it is correct behaviour that a the schema compilation should fail when it encounters a relative JSON pointer that points outside of the root, or that the `$data` reference should have been resolved to `undefined`.

**Validation result, data AFTER validation, error messages:**

Schema does not compile due to this error message being thrown: 
```

Error: Cannot access data 1 levels up, current level is 0

```

**What results did you expect?**

That the validation succeeds.

**Lastly**
Thank you for the time and effort put into this library! :)

**Comment by sondrele** [comment]
I should note that what I want to acheive, is to only validate a *subschema*, without looking at the *whole schema*. 

In my case, it is acceptable that the `$data` reference gets resolved to `undefined`, because I am not doing a full validation of `schema`, I'm only doing a partial validation of `schema-frequency`.

I have added another example here that explains it better here: https://runkit.com/sondrele/589c819811ea6e0014d53f05

**Comment by epoberezkin** [comment]
@sondrele This subschema would compile to something that expects a value. JSON pointer '1/property' points to another property of the parent object. But how can you define a parent object of the data that is passed to validation on the top level? Ajv cannot generate code to access that property as it has nothing to point to the parent object. So it is different from the property (or sub-property) being absent in the object Ajv has reference to (for which it would safely returns undefined). In this case Ajv doesn't even know where to start...

**Comment by epoberezkin** [comment]
> the $data reference points outside of the root level of the subschema

outside of the root data to be precise

**Comment by epoberezkin** [comment]
The documentation can be amended to say that $data can't point outside of root object passed to validation function and doing so results in schema compilation exception.

**Comment by sondrele** [comment]
Thanks for your quick response!

> But how can you define a parent object of the data that is passed to validation on the top level?

I guess I've been looking at this from the wrong angle.

> The documentation can be amended to say that $data can't point outside of root object passed to validation function and doing so results in schema compilation exception.

This makes sense, thanks :)

**However,** my use case is that I want to validate a (possibly) deeply nested subschema, because validating the entire schema would an unnecessary heavy operation.

What about a new API operation instead, let's call it `validateAtPath(path, data) -> Boolean`. The purpose of this function would be to only validate the schema that's referenced by the `path`, but in the context of the entire schema (and its data) that has been added to ajv with the `addSchema` method.

Is that an API operation that makes sense to support?

**Comment by epoberezkin** [comment]
It is already possible with both getSchema and validate methods - you can pass full URI including JSON pointer to subschema.
