### ISSUE TITLE
it.util.cleanUpVarErrors is not a function

### ISSUE THREAD

**Issue by adamtal3** [ajv-validator/ajv#414]
**it.util.cleanUpVarErrors is not a function**

Ajv 5.0.1-beta.3

I get this error when calling `addMetaSchema` with the v4 schema:
```javascript
    import Ajv from 'ajv/lib/ajv.js';
    import metaSchema from 'ajv/lib/refs/json-schema-draft-04.json';

    const ajv = new Ajv({
      meta: false,
      extendRefs: true,
      unknownFormats: 'ignore', 
    });
    
    ajv.addMetaSchema(metaSchema); // Throws the error
```

This is how `it.util` looks like in the chrome developer tools:
![chrome_2017-02-14_00-10-26](https://cloud.githubusercontent.com/assets/3287937/22905721/026efc4a-f24a-11e6-875a-6622d18860e2.png)

What can be the problem?

**Comment by adamtal3** [comment]
Updated `ajv` to `5.0.2-beta.0` and the error is gone (pretty sure the update fixed it, but not 100%),

**Comment by epoberezkin** [comment]
@adamtal3 thank you for figuring it out :) `npm run build && npm run bundle` would have fixed it too - most likely you had old compiled doT templates from some previous version. `cleanUpVarErrors` is not used anywhere in 5.0.1-beta.3, the last version it was used in was 5.0.0-beta.1, then it was renamed to `finalCleanUpCode`...
