### ISSUE TITLE
Switch statement weirdness

### ISSUE THREAD

**Issue by dvergeylen** [ajv-validator/ajv#416]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.11.2

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
{ v5: true, allErrors: true }
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
var Ajv = require('ajv');
ajv = new Ajv({ "v5": true, "allErrors": true });

var schema = {
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": ["authenticate", "get"]
        },
        "payload": {
          "type": "object",
          "switch": [
            {
              "if": { "properties": { "type": {"constant": "authenticate"} } },
              "then": {
                "properties": {
                  "token": {
                    "description": "Token [...]",
                    "type": "string"
                  }
                },
                "required": ["token"]
              }
            },
            {
              "if": { "properties": { "type": {"constant": "get"} } },
              "then": {
                "properties": {
                  "information": {
                    "type": "string",
                    "enum": ["relation"]
                  }
                },
                "required": ["information"]
              }
            }
          ]
        }
    },
    "additionalProperties": false
};
```

**Data (please make it as small as posssible to reproduce the issue):**

```json
var data = {
  "type": "authenticate",
  "payload": {
    "token": "token"
  }
};

var data2 = {
  "type": "get",
  "payload": {
    "information": "relation"
  }
};
```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
var validate = ajv.compile(schema);
console.log(validate(data)); // 'true', OK
console.log(validate.errors); // 'null', OK

console.log(validate(data2)); // 'false'
console.log(validate.errors));
```
Last command outputs:
>[ { keyword: 'required',
    dataPath: '.payload',
    schemaPath: '#/properties/payload/switch/0/then/required',
    params: { missingProperty: 'token' },
    message: 'should have required property \'token\'' } ]

Which means it validated against the first `if` of the `switch` statement.
Runkit [here](https://runkit.com/dvergeylen/58a2f1fe706a400014600068)

**What results did you expect?**
I would have expect `data2` to be validated against the second `if` statement of the `swtich`. I can't figure out what I am doing wrong.

**Are you going to resolve the issue?**
I am not even sure I am using this correctly! :laughing:

**Comment by epoberezkin** [comment]
@dvergeylen yes, you are using it incorrectly. The first schema in switch/if doesn't check the property `type` in the parent object (why would it?), it checks for the property `type` inside property `payload` (that's where the schema is located). As there is no property `type` there, the schema is valid and the schema in `then` is validated. Your `switch` keyword should be on the parent object level, not on the property level.

**Comment by epoberezkin** [comment]
And you probably want to make `type` required, as otherwise when this property is absent, the validation would pass.

Also, I'd recommend switching to 5.0.2-beta and using if/then/else from ajv-keywords rather than switch, as it is likely to become part of the spec in draft-07.

**Comment by epoberezkin** [comment]
Or you can use `select`, but it is not clear if it's going to be standard.

**Comment by dvergeylen** [comment]
:+1: Thank you for this very quick response, I will adapt the schema accordingly (installing 5.0.2-beta).

I know about the `required` attribute of `type`, present in my own schema but didn't pasted as guidelines asks for minimal schema to illustrate the problem.

Thank you again

**Comment by dvergeylen** [comment]
Works like a charm now, awesome module!
