### ISSUE TITLE
Validating propertyNames defined by a $data reference

### ISSUE THREAD

**Issue by sondrele** [ajv-validator/ajv#421]
## The code is also available on runkit:
- https://runkit.com/sondrele/589c8183c90f930014b5ec14https://runkit.com/sondrele/589c8183c90f930014b5ec14

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv: 4.11.2
ajv-keywords: 1.5.1

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
var Ajv = require('ajv@4.11.2');
ajv = new Ajv({
    v5: true,
    allErrors: true,
    errorDataPath: 'property',
    verbose: true,
    missingRefs: "fail",
    unknownFormats: 'ignore',
    multipleOfPrecision: 12,
    extendRefs: true,
    passContext: true,
    i18n: false
});
require('ajv-keywords@1.5.1/keywords/propertyNames')(ajv); 

```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
var schema = {
    "type": "object",
    "properties": {
        "selectedIps": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "FOO",
                    "BAR"
                ]
            }
        },
        "dynamicIps": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "ip": { "format": "ipv4" }
                },
                "required": [ "ip" ]
            },
            "propertyNames": {
                "enum": {
                    "$data": "/selectedIps"
                }
            }
        }
    }
};

```

**Data (please make it as small as posssible to reproduce the issue):**

```json
var invalidData = {
    "selectedIps": [ "FOO" ],
    "dynamicIps": {
        "BOO": { "ip": "0.0.0.0" }
    }
};

```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
console.log(ajv.validate(schema, invalidData))

```

**Validation result, data AFTER validation, error messages:**

```
true

```

**What results did you expect?**
I expected a validation error, but the result is `true`.

I had expected ajv to validate the properyName `BOO` against the value `["FOO"]`, and end the validation with an error, instead it validates to `true`.

I have provided two additional cases on [runkit](https://runkit.com/sondrele/589c8183c90f930014b5ec14):
* `Case 1 (unexpected)` - the example provided in this issue
* `Case 2 (expected)` - validates `additionalProperties` directly towards the `enum` in the `dynamicIps` schema
* `Case 3 (expected)` - validates `additionalProperties` like in `Case 1`, but also sets the properties as `required` with the same `$data` reference as the `propertyNames`

**Comment by epoberezkin** [comment]
@sondrele thank you. It all works correctly in version ^5.0.2-beta because propertyNames became a standard keyword (it's added to draft-06). In 4.x.x it's defined in ajv-keywords and the implementation has limitations (the data inside the subschema of propertyNames is the property name itself, rather than the whole object, so the data reference is undefined).

See https://runkit.com/esp/58a83949b356410015a169cc

Also see [migration guide](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.0)

If anything, it's ajv-keywords issue, but I will not be improving it as it all works in the next version.

**Comment by sondrele** [comment]
I see, thank you for the quick reply!
