### ISSUE TITLE
v5 patternRequired does`t find any matches considering declared pattern

### ISSUE THREAD

**Issue by dvakatsiienko** [ajv-validator/ajv#422]
Hello! it seems that `v5` `patternRequired` keyword desn't validate fields properly, or maybe i`m doing something wrong.

Im using
  ```ajv version: ^5.0.1-beta.3```

with options
```const ajv = new AJV({ v5: true });```

**JSON Schema:**

```
const schema = {
    type:       'object',
    properties: {
        provider: {
            type:       'object',
            properties: {
                name: {
                    type: 'string'
                }
            },
            patternRequired: ['name']
        }
    required: ['provider']
};

```

**JSON Data:**

```
const data = {
    "provider": {
        "name": "rest"
    },
}

```

**Your code:**

```
console.log(ajv.validate(test, data)
    ? 'Validation passed'
    : ajv.errorsText()
);
```

**Validation result, data AFTER validation, error messages:**

`patternRequired` keyword does not assert `name` property in json object in in mentioned 
different than declared in pattern.
It considers property as valid even if there is no property at all.

**What results did you expect?**
I expect that `patternRequired` keyword with `['name']` value inside should look into properties and consider json object as valid if there is property called `name` and assert if does`t.

**Comment by epoberezkin** [comment]
patternRequired has been moved to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords/tree/2.0.1-beta.0), as it didn't become part of the spec. See [migration guide](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.0) on how to use "v5" schemas with Ajv 5.0.x.

**Comment by dvakatsiienko** [comment]
thank you!
