### ISSUE TITLE
Type Definitions: Missing AJV Options

### ISSUE THREAD

**Issue by onury** [ajv-validator/ajv#425]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.11.2 Yes

TypeScript complains about the options passed to AJV constructor.
[interface Options](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts#L115) does not have `extendRefs?:boolean` and `sourceCode?:boolean` properties defined.

**Comment by epoberezkin** [comment]
They are added in 5.0.x-beta (5.0.0 branch), can be added to master branch too

**Comment by epoberezkin** [comment]
closed with https://github.com/epoberezkin/ajv/commit/8c0395908c498e8525b9c09e8f48112aa3635eb3
