### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by prettydiff** [ajv-validator/ajv#433]
Execution details and stacktrace: https://github.com/Glavin001/atom-beautify/issues/1543

**Comment by epoberezkin** [comment]
This PR once published will fix it: https://github.com/ahmadnassri/har-validator/pull/89

**Comment by epoberezkin** [comment]
@prettydiff har-validator in the dependencies tree should have version 4.2.1. If it is before that, you need to re-install. If it's 4.2.1 and it's still broken please let me know.

**Comment by idangozlan** [comment]
keep getting `unsafe-eval` error (tried reinstall `ajv`), I'm using `ajv` v5 if it's matter

**Comment by epoberezkin** [comment]
@idangozlan it's not about ajv version, it's about har-validator version, it should 4.2.1+. Can you please post your dependency tree here (`npm ls`)?
