### ISSUE TITLE
Unable to resolve module url from node_modules/ajv/lib/compile/resolve.js

### ISSUE THREAD

**Issue by pavlelekic** [ajv-validator/ajv#435]
![simulator screen shot mar 10 2017 15 46 54](https://cloud.githubusercontent.com/assets/7754193/23799395/b62b72d8-05a8-11e7-862e-b4dfbf370a2d.png)
I tried using Ajv in a React Native app, however I wasn't even able to include the module (see the screenshot). I tried the stable version, as well as 5.0.3-beta, same thing happens. I used the code example in the docs:

```
var Ajv = require('ajv');
var ajv = new Ajv(); // options can be passed, e.g. {allErrors: true}
var validate = ajv.compile(schema);
var valid = validate(data);
if (!valid) console.log(validate.errors);
```
But like the error says, I wasn't able to validate anything, it was failing even before with the require('ajv') statement.

**Comment by epoberezkin** [comment]
It says something about "url" module not found. It is a core node.js module that would also be available if you were to use browserify.

It also mentions https://github.com/facebook/react-native/issues/4968

**Comment by epoberezkin** [comment]
As a workaround I can suggest using supplied bundle - it exports global Ajv.

**Comment by pavlelekic** [comment]
Thanks!

**Comment by epoberezkin** [comment]
@claudiorodriguez do you know how to solve it?

**Comment by nenti** [comment]
I have the same issue. Unable to resolve module 'url'.
`var url = require('url');`
Seems as if core nodejs modules are not available in react-native and not related to this module.

**Comment by epoberezkin** [comment]
@nenti @pavlelekic I think including [url module from npm](https://www.npmjs.com/package/url) as your app dependency can help. Please let me know if it does or doesn't.

**Comment by superandrew213** [comment]
@epoberezkin I can confirm that adding `url` as a dependency works.

**Comment by epoberezkin** [comment]
@superandrew213 thank you

**Comment by jsaucedo** [comment]
How do you add url as dependency of your React Native project?

**Comment by superandrew213** [comment]
@jsaucedo `npm i --save url`

**Comment by ropering** [comment]
yarn add url
