### ISSUE TITLE
Are there any plans for i18n-support?

### ISSUE THREAD

**Issue by jmtoball** [ajv-validator/ajv#44]
We want to use ajv to validate complex configurations against predefined schemas, but our application is in German and English, so we would like to translate the error messages.
I guess the error messages are coming from def._errorMessages in [lib/dot/definitions.def](https://github.com/epoberezkin/ajv/blob/master/lib/dot/definitions.def), so maybe we could choose one set of translations there, dependent of some variable, but I have no experience with dot-templating.

Sorry for the premature issue-creation, I accidentally hit some kind of github-shortcut.

**Comment by epoberezkin** [comment]
Do you mean for error reporting?

**Comment by jmtoball** [comment]
exactly. I added a description. sorry about the confusion ;-)

**Comment by epoberezkin** [comment]
It's not that difficult. It shouldn't be in the template in this case if we want to support multiple languages. I can do the support if you are happy to contribute the actual messages once I've done it.

**Comment by jmtoball** [comment]
That would be awesome! I can definitely provide you with the German messages then, yes.

**Comment by epoberezkin** [comment]
Ok, I'll look at it this week

**Comment by blakeembrey** [comment]
@epoberezkin FWIW, I pulled this logic into an external module for handling request errors with i18n - the messages were extracted from `tv4` (https://github.com/mulesoft-labs/node-request-error-handler/blob/master/lib/messages/json.js).

Edit: As I'm not multilingual, I am trusting the existing translations a bit.

**Comment by epoberezkin** [comment]
That's cool, thanks a lot!

**Comment by epoberezkin** [comment]
Started working on it. @blakeembrey do you think it should be just an option of the validator instance (say `i18n: 'fr'` ) or there should be a way to make the same compiled shema return errors in different languages?

**Comment by blakeembrey** [comment]
@epoberezkin I'm probably not the best person to comment on the final implementation as I tend to structure APIs differently and prefer to provide l10n to application error instances instead of having every tool I use provide separate i18n. 

That said, I think the implementation requires that the option is passed as a second argument into the validation function as they'll be evaluated differently at runtime. I'm not sure what the difference is between your two options though, sounds like the same thing here? I'd also use `locale: 'fr'` for correctness over `i18n` too.

**Comment by epoberezkin** [comment]
got it. thanks

**Comment by epoberezkin** [comment]
So I guess the whole file with the rest of keywords can be moved to `ajv-i18n` package that will provide functions to create error messages from errors array created by ajv. And there will be nothing in ajv itself in this case. Do you mind?

**Comment by blakeembrey** [comment]
@epoberezkin Makes sense to me. Might want to check with `tv4` and try to collaborate with them on this as a general JSON schema i18n messages module to avoid unnecessary work - I can open an issue there and discuss with them, if you'd like.

**Comment by epoberezkin** [comment]
Good idea actually. Please do.

**Comment by epoberezkin** [comment]
@blakeembrey thanks!

**Comment by epoberezkin** [comment]
@jmtoball have a look at [ajv-i18n](https://github.com/epoberezkin/ajv-i18n). It has `en`, `hu`, `pl` and `ru` locales at the moment. You can contribute German translations of the messages in `/messages/index.js` file. Let me know if you need some help.

**Comment by jmtoball** [comment]
Sure, I will look into it later today. Thank you, that was fast :+1:
