### ISSUE TITLE
Crashes when in Docker when using the alpine base

### ISSUE THREAD

**Issue by daveisfera** [ajv-validator/ajv#440]
See https://github.com/nodejs/docker-node/issues/288#issuecomment-286306258 for a reproducer.

**Comment by epoberezkin** [comment]
@daveisfera please try to make the code reproducing the issue smaller, ideally only using Ajv and not other packages. Also could you please re-submit the issue answering all the questions from [compatibility template](https://github.com/epoberezkin/ajv/issues/new?labels=compatibility&body=**The%20version%20of%20Ajv%20you%20are%20using**%0A%0A**The%20environment%20you%20have%20the%20problem%20with.**%0A%0A**Your%20code%20(please%20make%20it%20as%20small%20as%20possible%20to%20reproduce%20the%20issue).**%0A%0A**If%20your%20issue%20is%20in%20the%20browser,%20please%20list%20the%20other%20packages%20loaded%20in%20the%20page%20in%20the%20order%20they%20are%20loaded.%20Please%20check%20if%20the%20issue%20gets%20resolved%20(or%20results%20change)%20if%20you%20move%20Ajv%20bundle%20closer%20to%20the%20top.**%0A%0A**Results%20in%20node.js%20v4.**%0A%0A**Results%20and%20error%20messages%20in%20your%20platform.**%0A%0A) (see the contribution guidelines).
