### ISSUE TITLE
Change signature of validating functions to use objects instead of positional arguments

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#443]
**Problem**

Compiled validating functions (and validating functions used in custom keywords) currently have 5 arguments:
- data
- dataPath
- parentData
- parentDataProperty
- rootData

If the custom keyword is "validate" kind, then the function has 7 arguments:
- schema
- data
- parentSchema
- dataPath
- parentData
- parentDataProperty
- rootData

All these arguments are positional so there are usual problems that functions with large number of positional arguments have (need to remember order, all arguments have to be used etc.).

I also need to add at least one more parameter.

**Solution**

Change function signatures.

Validating functions:
- data
- an object with properties:
  - data
  - dataPath
  - parentData
  - parentDataProperty
  - rootData
  - etc.

Custom keyword "validate" function:
- schema
- data
- an object with properties:
  - schema
  - data
  - parentSchema
  - dataPath
  - parentData
  - parentDataProperty
  - rootData
  - etc.

Pros:
- these signatures will still allow one or two positional arguments in the most common cases
- other arguments can be used in any order using destructuring
- easy to extend and no need to remember the order

Cons:
- some performance impact (constructing objects and destructuring), although the most performant custom keywords ("inline" and "macro") will not be affected
- uglier code in Ajv itself (it will remain ES5 compatible, so no destructuring inside Ajv)

Questions:
- Should objects contain positional arguments as well (as above) or only the properties that are not available as positional arguments?

**Comment by gajus** [comment]
As long as you validate the shape of the configuration object, then it is a good change.

My biggest grudge with using simple objects for configuration is when there are no assertions made about their content, e.g.

```js
webpack({
  debug: true,
  stirct: true,
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader'
    }
  ]
});
```

For all you know by scanning the code this is valid configuration. If `webpack` does not throw an error about unknown configurations, then you'd not know that `debug` is not a valid configuration here, `strict` is a typo and therefore will have no effect, etc.

i.e. If you do this, you need to use JSON schema to validate the shape of the validate instructions.

> At least in part this can be avoided using type annotations (e.g. Flow). This has no runtime costs. Though the benefits are restricted to the few who are using static type checking.

**Comment by epoberezkin** [comment]
@gajus thank you. I think both positional arguments and objects are equally affected by the [lack of] validation. So the main question is whether to use positional or objects, rather than whether to validate or not to validate ;)

**Comment by gajus** [comment]
> I think both positional arguments and objects are equally affected by the [lack of] validation.

No. You cannot make a typo in a parameter name when using positional arguments.

You can put them in a wrong order, sure, but thats likely to cause a runtime error.

Putting an unknown property to the configuration object will go unnoticed.

**Comment by epoberezkin** [comment]
You may be right... I'll leave it as is I think :)
