### ISSUE TITLE
Asynchronous schema compilation with loading schemas using supplied function.

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#45]
See #43

**Comment by blakeembrey** [comment]
My only comments on this is that synchronous compilation _must_ always be first class (less for you and more for anyone else landing on this issue or wanting this feature), but I don't have any real issue with a little utility for handling asynchronous loading. #43 

Aside from that, I don't think validation should ever be asynchronous either - it's easy enough to build a utility on top of this or in conjunction with this to handle the business logic related to validation. If it's a big enough or unsolved issue, it'd be interesting to build a little utility that applies business logic as simply as a schema and returns all the errors (or the first) in the same fashion. #40

**Comment by epoberezkin** [comment]
done in 4dc6cbecb9efb2cef8bf5d60916b82cf4cf35837

**Comment by epoberezkin** [comment]
@blakeembrey I agree. I've made a separate method `compileAsync`, so nothing changed in `compile` method.

While asynchronous compilation is a possible use case - lots of 3rd party schemas where it is not practical to pre-load all of them (although it's quite theoretic for me to be honest), I genuinely believe that asynchronous and custom validations are evil :), with the exception of custom format for strings.

I think it is wrong to mix JSON-schema validation with business/semantic validation. Although I may be fighting a lost battle here :) - lots of people seem to like the idea of cramming all sorts of validation logic into JSON-schema (at least by reference), disregarding all the negative consequences...
