### ISSUE TITLE
Keywords as variable name or property names are not compatible with QT Script Engine.

### ISSUE THREAD

**Issue by DAGapps** [ajv-validator/ajv#451]
This library (ajv.js) is not compatible with QT Script Engine. A Javascript Engine for ECMAScript in C++/QT. 
Because this engine has problems when the variable names or property names are also javascript keywords. 

**Version of ajv** 4.11.5

**Example**
In *ajv.js* (4.11.5, not minified) at line 1291:
Or in *util.js* (master, source) at line 63:
```javascript
code = types.null ? '(': '(!' + data + ' || ';
```
"null" is a keyword in javascript. The javascript script parser detect this as syntax error.

**Solution:**
```javascript
code = types["null"] ? '(': '(!' + data + ' || ';
```

Names which also represent keywords cause problems.
If they are not wrapped in a string. 

**Incorrect**
```javascript
// Example
var obj = {};
obj.null = 0;
obj.if = 1;
obj.byte = 2;
obj.default = 3;
```
**Correct**
```javascript
// Workaround
var obj = {};
obj["null"] = 0;
obj["if"] = 1;
obj["byte"] = 2;
obj["default"] = 3;
```
Or just other names.

In a browser on Windows Chrome 56.0.2924.87 it has no problems with keywords as names. 
Background: Using this library in embedded systems with QT Script Engine.

**Comment by epoberezkin** [comment]
@DAGapps thank you. PR is welcome, I'm happy to change property access to compatible way. A bigger question though, will Array.isArray etc. work? Maybe a better solution is to transpile to ES3.

**Comment by epoberezkin** [comment]
@DAGapps QT 5.8 seems to support at least ES5. Which version you are using?

**Comment by DAGapps** [comment]
@epoberezkin Thanks for your reply. Array.isArray is no problem. Unfortunately I can't say the QT version for now.  I asked the developer of this toolchain and awaiting the feedback. 

The following example shows keywords that are not allowed as variable names.
All properties which "clothed" in quotes are not allowed without quotes.
A comment behind is referenced to the ajv.js [Linked here](https://cdnjs.com/libraries/ajv) (Bundle, 4.11.5) Keywords from [here](https://www.w3schools.com/js/js_reserved.asp).
```
var obj = {
    abstract: 0,
    arguments: 1,
    await: 3,
    boolean: 4,
    "break": 5,
    byte: 6,
    "case": 7,
    "catch": 8,
    char: 9,
    "class": 10,
    "const": 11,
    "continue": 12, // ajv.js @ 4263
    "debugger": 13,
    "default": 14, // ajv.js @ 3511, 4534, 4538, 4550, 4553, 4557, 4559
    "delete": 15,
    "do": 16,
    double: 17,
    "else": 18,
    "enum": 19,
    eval: 20,
    "export": 21,
    "extends": 22,
    "false": 23,
    final: 24,
    "finally": 25,
    float: 26,
    "for": 27,
    "function": 28,
    goto: 29,
    "if": 30, // ajv.js @ 4172, 4177
    implements: 31,
    "import": 32,
    "in": 33,
    "instanceof": 34,
    int: 35,
    interface: 36,
    let: 37,
    long: 38,
    native: 39,
    "new": 40,
    "null": 41, // ajv.js @ 1291, 1293
    package: 42,
    private: 43,
    protected: 44,
    public: 45,
    "return": 46,
    short: 47,
    static: 48,
    "super": 49,
    "switch": 50,
    synchronized: 51,
    "this": 52,
    "throw": 53, // ajv.js @ 6939, 7068
    throws: 54,
    transient: 55,
    "true": 56,
    "try": 57,
    "typeof": 58,
    "var": 59,
    "void": 60,
    volatile: 61,
    "while": 62,
    "with": 63,
    yield: 64,
    array: 65,
    isArray: 66,
    undefined: 67
};
```
In the latest chrome browser (57) all keywords are allowed. 

Thanks you.
For me, you do not necessarily have to fix this issue. :-)

I changed the ajv.bundle.js and the ajv throws no errors now. 
But it says that my json is invalid for the schema (on embedded linux device). On chrome on windows PC it says valid. You see, I have another problem. I have to debug this first.

**Comment by DAGapps** [comment]
@epoberezkin Ajv prints "**Error: Error compiling schema, function code:**" (without code) while compiling the schema: 
```
var ajv = new Ajv();
var validate= ajv.compile(schema); // error
```
On chrome, there are no problems. Ajv works great. But not for embedded system. Nevermind my issue. Currently I can't tell if we will use this library. Because it does not work with the QT Script Engine. 

You do not need to adapt the library to out special purposes. Perhaps I will do. But not for sure.
It's a great Library. I will think on it, if I plan to validate json on browser or node side. 

Thanks for your time, mate.

**Comment by epoberezkin** [comment]
@DAGapps thank you. Happy to help if needed. Can the issue be that QT platform cannot execute Function constructor? If that is the case you can try pre-compiling the schemas during the build time using [ajv-cli](https://github.com/jessedc/ajv-cli) as I've done in [table](https://github.com/gajus/table) package.

**Comment by DAGapps** [comment]
@epoberezkin  Thanks. The pre-compiled schema does work. Ok I had to adjust a few things. For example x.enum to x["enum"]. Also I manually replaced the "require(..)" with source code. Like require('ajv/lib/compile/equal');

Btw. I work on Qt 4.8.5. (upgrade is not possible)
