### ISSUE TITLE
missing tag for 4.11.6 release

### ISSUE THREAD

**Issue by pravi** [ajv-validator/ajv#459]
latest version in npm is 4.11.6 but corresponding tag is missing from the repo

**Comment by epoberezkin** [comment]
I don't create tags for patches. You can see changes by looking at commits history. Why do you need them?

**Comment by pravi** [comment]
@epoberezkin I'm packaging ajv for debian and I want to take tarballs from github corresponding to the npm versions. If they are tagged, the process is automated, ie, I can find and download new version without any manual step. If you are going to include tests in the npm dist tarballs, I could use them. I want to run tests to make sure the debian package is working as expected.

**Comment by epoberezkin** [comment]
I see. Ok, I will start making tags for all releases...

**Comment by epoberezkin** [comment]
you got it

**Comment by pravi** [comment]
Thanks! Please do it for ajv-keywords too https://github.com/epoberezkin/ajv-keywords/issues/11
