### ISSUE TITLE
Is there any way to get straight schema after patch/merge or $ref resolved

### ISSUE THREAD

**Issue by nomi-ramzan** [ajv-validator/ajv#463]
Hi I am trying to get straight schema **without $ref** ?
I tried already `ajv.getSchema('newZone').schema` but its still with $ref and merge.
Is there any way to get fully straight schema.
Thank you

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/blob/master/FAQ.md#generating-schemas-with-resolved-references-ref
