### ISSUE TITLE
more than 2 patch calls gives an error about `add`

### ISSUE THREAD

**Issue by gunslingerfry** [ajv-validator/ajv#468]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv: 5.0.0
ajv-cli: 2.0.0
ajv-merge: 3.0.0

**JSON Schema**

```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "example.json#",
	"type": "object",
	"properties": {
		"anObject": {
			"$patch": {
				"source": {
					"$ref": "#/definitions/C",
					"additionalProperties": false
				},
				"with": []
			}
		}
	},
	"definitions": {
		"A": {
			"type": "object",
			"properties": {
				"item1": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": ["item1"]
		},
		"B": {
			"$patch": {
				"source": {
					"$ref": "#/definitions/A"
				},
				"with": [{
					"op": "add",
					"path": "/properties/item2",
					"value": {
						"type": "string"
					}
				}]
			},
			"required": ["item2"]
		},
		"C": {
			"$patch": {
				"source": {
					"$ref": "#/definitions/B"
				},
				"with": [{
					"op": "add",
					"path": "/properties/item3",
					"value": {
						"type": "string"
					}
				}]
			},
			"required": ["item3"]
		}
	}
}
```

**Sample data**

```json
{
    "thing": {
        "item1": "item1",
        "item2": "item2"
    }
}
```

**Your code**

```bash
ajv -s schema -d instance --all-errors -c ajv-merge-patch
```

**Validation result, data AFTER validation, error messages**

```
schema example is invalid
error: Cannot perform an `add` operation at the desired path

```

**What results did you expect?**
$patch is applied recursively

**Comment by epoberezkin** [comment]
@gunslingerfry It does patch "recursively" but not in the order you expect.

You expect the $patch in the source to be executed first and then apply patches.

What happens is that the patches are applied first and then the $patch in the resulting schema is applied.

**Comment by gunslingerfry** [comment]
So I'm not sure I actually understand the implication. If you wouldn't mind, can you show me a concrete example? My goal is DRY in validating our database and it seems the easiest to maintain by duplicating the class inheritance of the objects. e.g. an engineer updates the persistent data of a class, they can look at the analog in the schema to quickly identify where that change goes (and hopefully, create a migration script of some sort).

**Comment by epoberezkin** [comment]
$patch may be the wrong keyword for this purpose. Why can't you just use allOf?

```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "example.json#",
  "type": "object",
  "properties": {
    "thing": { "$ref": "#/definitions/C" }
  },
  "definitions": {
    "A": {
      "type": "object",
      "properties": {
        "item1": {
          "type": "string"
        }
      },
      "required": ["item1"]
    },
    "B": {
      "allOf": [
        { "$ref": "#/definitions/A" },
        {
          "properties": { "item2": { "type": "string" } },
          "required": ["item2"]
        }
      ]
    },
    "C": {
      "allOf": [
        { "$ref": "#/definitions/B" },
        {
          "properties": { "item3": { "type": "string" } },
          "required": ["item3"]
        }
      ]
    }
  }
}
```

Are you trying to merge several properties to be able to use additionalProperties: false?

**Comment by epoberezkin** [comment]
Alternatively, you can patch the patch in C:

```json
{
  "C": {
    "$patch": {
      "source": {
        "$ref": "#/definitions/B"
      },
      "with": [{
        "op": "add",
        "path": "/$patch/with/1",
        "value": {
          "op": "add",
          "path": "/properties/item3",
          "value": {
            "type": "string"
          }
        }
      }]
    }
  }
}
```

**Comment by gunslingerfry** [comment]
Yes. I'm trying to enforce the `additionalProperties: false` in all the inherited schemas (in addition to merging the required properties).

**Comment by epoberezkin** [comment]
Patching the patch (rather than its result) leads to a bit clunky implementation as you can see.

On another hand patching the result is not obvious as you cannot really see from the schema itself what is being patched.

So I am going to leave it as is, I think explicitness is more important here.

Using $merge may result in more intuitive schemas.

Going to close it here, if you have some ideas how $merge/$patch can be improved in some other way please submit the issue to ajv-merge-patch repo
