### ISSUE TITLE
Resolve reference passed to validate and getSchema methods

### ISSUE THREAD

**Issue by redben** [ajv-validator/ajv#47]
Is is possible for validate function to resolve ids inside schemas ?
example :

``` javascript
var ajv = require('ajv')();

ajv.addSchema({
    id: 'my-schema',
    type: 'object',
    definitions: {
        foo: {
            id: 'foo',
            type: 'object',
            required: ['bar']
        }
    }
}, 'my-schema');


ajv.validate(
    'my-schema#/definitions/foo', {
        bar: true
    });

// throws Error: no schema with key or ref "my-schema#/definitions/foo"
```

**Comment by epoberezkin** [comment]
At the moment `validate` method does not resolve references - it only allows to use references that were previously added via id attributes (both top level and internal). For now you can instead use this:

```
ajv.validate({ $ref: 'my-schema#/definitions/foo' }, {
    bar: true
});
```

By the way you don't need the inner id in this case

**Comment by redben** [comment]
Thanks ! passing $ref works.

By the way I think I got confused by the signature [in the docs](https://github.com/epoberezkin/ajv#validateobject-schemastring-keystring-ref-data---boolean):

> .validate(Object schema|String key|String ref, data) -> Boolean

Shouldn't it be this instead ?

> .validate(Object schema|String key|Object ref, data) -> Boolean

**Comment by epoberezkin** [comment]
Not really. `{ $ref: 'my-schema#/definitions/foo' }` is just a schema. `key` is the second argument passed to `addSchema` method, `ref` is schema `id` attribute (there is no need to have both btw, in your case you don't need to pass the second parameter at all).

I was thinking that validate should really resolve reference in the same way as it happens during the schema compilation.

**Comment by redben** [comment]
Would this be the right test for this feature?

``` javascript
    it('should validate against previously compiled schema by ref', function() {
      ajv.compile({ id: '//e.com/defs.json', definitions: { def: { type: 'string'}} }) .should.be.a('function');
      ajv.validate('//e.com/defs.json#/definitions/def', 'a') .should.equal(true);
      ajv.validate('//e.com/defs.json#/definitions/def', 1) .should.equal(false);
    });
```

**Comment by epoberezkin** [comment]
yes

**Comment by epoberezkin** [comment]
By the way, not sure if you saw it in readme - it's faster to use a compiled validation function than validate method.

Also if validate resolves the reference it most likely will need to compile the schema. This feature can be implemented by simply replacing string with the schema (as I did above) but this approach has the performance cost of an extra function call in compiled schema.

**Comment by redben** [comment]
Yes I saw that. I am actually using addSchema() then validate() or getSchema() because I have a bunch schemas scattered in different files, compile would complain if it can't resolve a ref to a schema that has not been added yet.

I tried to dig through the code to see if I can help with a pull request. Is it getSchema that needs work? or do I need to go to sleep :) (late in here...)
Something like :

``` javascript
   function getSchema(keyRef) {
        var parts = keyRef.match(/^([^#]+)(#\/.+)?$/),
            schemaObj = _getSchemaObj(parts[1]),
            v;
        switch (typeof schemaObj) {
            case 'object': 
               v = schemaObj.validate || _compile(schemaObj);
               break;
            case 'string':
               v =  getSchema(schemaObj);
        }
        return ( parts[2] ) ? v.refs[parts[2]] : v;
    }
```

And hey ajv rocks ! Thanks for this module.

**Comment by epoberezkin** [comment]
Thank you :) yes _getSchema, but you need to use resolve function... At the moment it is too tightly coupled to compile, but that's the one.

**Comment by epoberezkin** [comment]
Actually using getSchema also returns the same function that is returned by compile - it can be used after all schemes are added

**Comment by guymguym** [comment]
:+1: I would also like to be able to pass the JSON-pointer directly to getSchema, although the workaround to use `getSchema({$ref:ref})` works. Thanks.

**Comment by epoberezkin** [comment]
in [4.5.0](https://github.com/epoberezkin/ajv/releases/tag/4.5.0)
