### ISSUE TITLE
exclusiveMinimum is supposed to be boolean. Error: "exclusiveMinimum should be number"

### ISSUE THREAD

**Issue by LeviDooley** [ajv-validator/ajv#471]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

```javascript
// package.json
{ "ajv": "^5.0.0" }
```

**Ajv options object**

```javascript
// Probably unrelated
var Ajv = require('ajv');
var ajv = new Ajv({ loadSchema: loadSchema });
```

**JSON Schema**

(Partial schema)
```json
{
  "properties": {
    "factor": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    }
  }
}
```

**Your code**

```javascript
var ajv = new Ajv({ loadSchema: loadSchema });

function loadSchema(uri) {
    console.log(`Loading Schema: ${uri}`);

    return request(uri).then(function(res) {
        var schema = JSON.parse(res);
        return schema;
    });
}

var schema = ajv.compileAsync({
    "$ref": "some web url"
});
schema.then(() => {
    //...
}.catch((err) => {
    // err.message == "schema is invalid: data.definitions['meterpoint'].properties['factor'].exclusiveMinimum should be number"
})
```

**What results did you expect?**
exclusiveMinimum is supposed to be boolean. 
http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.5

**Are you going to resolve the issue?**
No, I'm going to remove exclusiveMinimum from my schema for the time being.

**Comment by epoberezkin** [comment]
By default Ajv treats your schema as [draft-06](https://trac.tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.3) - the latest published version of JSON schema spec (json-schema-org website has to be updated still). In this specification exclusiveMaximum/Minimum have been changed to be number.

See [docs on these keywords](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#maximum--minimum-and-exclusivemaximum--exclusiveminimum) for more details.

See [migration guide](https://github.com/epoberezkin/ajv/releases/tag/5.0.0) for info how to use Ajv 5.x.x with draft-04 schemas.

**Comment by epoberezkin** [comment]
So with draft-06 your schema should be:

```json
{
  "properties": {
    "factor": {
      "type": "number",
      "exclusiveMinimum": 0
    }
  }
}
```

**Comment by LeviDooley** [comment]
Thank you. 😄 

I had no idea that it updated recently. I was about to say, I wonder why the website is outdated, but then I saw that draft-06 was authored April 2017. I guess it makes sense.

**Comment by epoberezkin** [comment]
Ajv still supports boolean form for exclusiveMaximum/Minimum, but you need to tell it that it's a draft-04 schema.

**Comment by LeviDooley** [comment]
I figured, but I'm just now making these schemas, so I might as well start with the latest version. Thanks again.
