### ISSUE TITLE
no schema with key or ref "http://json-schema.org/draft-04/schema#"

### ISSUE THREAD

**Issue by mmc41** [ajv-validator/ajv#472]
I have upgraded from ajv 4.x to ajv 5.0 and I now get above errors when validating json files that I generate using the excellent 'typescript-json-schema' module that generate json schema with
`"$schema": "http://json-schema.org/draft-04/schema#"`.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.0

**Ajv options object**

allErrors: true, verbose: false, addUsedSchema: false, inlineRefs: false,

**JSON Schema**

```json
{
  ...
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Validation result, data AFTER validation, error messages**

```
 Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
```

**What results did you expect?**

The schema to validate like it did in ajv 4.x

Note, as my schemas are autogenerated they are a little difficult to change, so it would be great if Ajv 5 could accept them (like Ajv 4).

**Comment by admvx** [comment]
@mmc41 I had this issue too, but found the migration guide under the 5.0.0 release notes: https://github.com/epoberezkin/ajv/releases/tag/5.0.0

**Comment by epoberezkin** [comment]
@adamayogo that is correct. @mmc41 this guide explains how to use draft-04 schemas with 5.x.x version. By default it only includes meta-schema for draft-06.

**Comment by Domvel** [comment]
I do not understand why is the property `$id` with the url to the schema required for the schema? The property `$schema` is for the schema url, or not?

I fixed the error **no schema with key or ref** by adding the `$id` with the url to the json-schema.
Now my files looks like (snippet):

```json
{
  "$id": "http://json-schema.org/draft-04/schema#",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

I need `$schema` for the editor (VS Code). Why is id required?

**Comment by epoberezkin** [comment]
@Domvel $schema is URI of the meta-schema, $id is recommended rather than required, please see JSON schema spec

**Comment by Domvel** [comment]
@epoberezkin Why is not possible to use ajv without `$id`? Only with `$schema`. I just added the id property to work with.

**Comment by epoberezkin** [comment]
It is possible to use ajv without $id, it is only needed if you refer to a schema.

**Comment by steph643** [comment]
I 'm also experiencing the issue described at the top of this thread. It seems Ajv doesn't accept the `$schema` field at all. Whatever I put there, I get ` Error: no schema with key or ref "..."`

**Comment by epoberezkin** [comment]
@steph643 draft-04 meta-schema has to be added to Ajv instance - please see top of readme.

**Comment by steph643** [comment]
@epoberezkin , thanks for your answer. 

I use draft-06, not draft-04, but the readme says to call `addMetaSchema` for draft-06 also. Sorry, I didn't see this,  I will give it a try.

Thanks again.

**Comment by Yan502** [comment]
I have the same problem. Is there a solution

**Comment by epoberezkin** [comment]
Ajv v8 no longer supports draft-04, you need to use v6 or migrate your schemas

**Comment by Yan502** [comment]
![image](https://user-images.githubusercontent.com/26403272/179775757-479234a8-111a-4a67-96da-506957a314fe.png)
![image](https://user-images.githubusercontent.com/26403272/179775904-cee6e552-3d52-4445-9bb9-7ac78227c1cf.png)

Still don't understand. Can you answer my question? Thank you

**Comment by ssbarnea** [comment]
I spotted another unexpected side effect:
```
Error: no schema with key or ref "https://json-schema.org/draft-07/schema"
```

So basically if someone dares to use the HTTPS or to remove the "#" from the url, ajv stops recognizing the schema, even if from the HTTP point of view the schema file is perfectly accessible.

Not only this, but that means that AJV users are forced to use the unsecure HTTP protocol for loading the schemas, which opens another can of worms.

So far I am inclined to believe that the only way to make it work in all cases is use exactly `http://json-schema.org/draft-07/schema#` which happens to be its own exposed `$id`.

**Comment by BinToss** [comment]
> Ajv v8 no longer supports draft-04, you need to use v6 or migrate your schemas

from https://ajv.js.org/json-schema.html#draft-04
> You can use JSON Schema draft-04 schemas with Ajv from v8.5.0 and the additional package [ajv-draft-04](https://github.com/ajv-validator/ajv-draft-04) (both ajv and ajv-draft-04 should be installed).

**Comment by Bluscream** [comment]
What am i supposed to do if i get this:
```log

Run walbo/validate-json@v1.1.0
Validating JSON files
Finding files from manifest.json

Error: no schema with key or ref "http://json-schema.org/draft-06/schema#"
```
```json
{
  "$id": "http://json-schema.org/draft-06/schema#",
  "$schema": "http://json-schema.org/draft-06/schema#",
  ...
```

**Comment by nickdnk** [comment]
Does anyone know how to both specify `$schema` *and* have ajv work correctly on the CLI? This seems like such a weird bug or oversight.

I'm doing:

```json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "my schema",
    "description": "foo",
    "type": "object"
}
```
which works fine for the IDE, but ajv gives me the same error as this issue:
```
error: no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"
```
when using:
```cli
ajv validate --all-errors -s my_schema.json --spec=draft2019 -d my_data.yml
```

This is on version 8.17.1.

Edit: I figured it out. Apparently, now the requirements have been inverted since these issues were posted years back. HTTPS is now *required* for the schema property, or it doesn't work on the CLI, e.g.:

Good:
```
https://json-schema.org/draft/2019-09/schema
```

Bad:
```
http://json-schema.org/draft/2019-09/schema
```
