### ISSUE TITLE
Cant get rid of warning: "Warning in ./~/ajv/dist/ajv.bundle.js"

### ISSUE THREAD

**Issue by MusicGindos** [ajv-validator/ajv#475]
Hi,

I am using react and i got this warning i cant get rid of it:
Warning in ./~/ajv/dist/ajv.bundle.js
Critical dependencies:
1:476-483 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ajv/dist/ajv.bundle.js 1:476-483

**Comment by epoberezkin** [comment]
Possibly, you are using an old version.
If it's not the case, please submit the issue answering all the questions in the template.
