### ISSUE TITLE
Better error message when additional-properties are disallowed

### ISSUE THREAD

**Issue by Venryx** [ajv-validator/ajv#476]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

5.0.0

**Validation result, data AFTER validation, error messages**

Error message: `data should NOT have additional properties`

**What results did you expect?**

An error message listing what properties were there that "should not have been".

**********

At the moment, when an object is validating, and it has a property that wasn't listed (and `additionalProperties` is set to `false`), the error message is not very helpful.

It just says: "data should NOT have additional properties"

But it doesn't say what "additional properties" were present.

This makes it very hard to determine what property was accidentally added -- especially when using nested schemas.

Simply including a list of additional-properties in the error message would resolve the issue.

**Comment by epoberezkin** [comment]
Error objects should contain params property with that information, see https://github.com/epoberezkin/ajv#error-parameters

If in your case it doesn't please re-submit the issue providing the full info based on the issue template.

**Comment by retorquere** [comment]
I think this is more about ajv.errorsText, which outputs `data should NOT have additional properties` without further information on what properties are the culprit; for other errors, the message is nicely descriptive.

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/blob/master/FAQ.md#why-dont-additionalproperties-false-errors-display-the-property-name

**Comment by retorquere** [comment]
Clear - sorry for not looking it up.
