### ISSUE TITLE
Array indices in dataPath of error messages are in quotes

### ISSUE THREAD

**Issue by andrejpavlovic** [ajv-validator/ajv#48]
Everything is working great, I'm just wondering what's the best way to make the errors easier to track down and fix in the data object.

For example, I get an error that looks like this:

``` javascript
{ keyword: "required",
  dataPath: ".assetGroups['166'].previewUrl",
  message: "should have required property .previewUrl" }
```

Tracking down assetGroup object 166 in an array of 200 of them, is not that easy. Maybe if I used some sort of a good JSON editor it would help. However, would it be possible to instead of showing number 166 perhaps use another property that is available on that assetGroup.

So let's say that my assetGroup object 166 looks like this:

``` javascript
{ id: "cats" }
```

Could the error message look more like 

``` javascript
{ keyword: "required",
  dataPath: ".assetGroups['166'].previewUrl",
  prettyDataPath: "assetGroups[cats].previewUrl",
  message: "should have required property .previewUrl" }
```

It would make it a lot easier for me to find the object if I search for "cats".

Or maybe there could be a way to use the dataPath to programatically work backwords in the data to get the full objects that relate to the error?

Any suggestions are welcome :)

**Comment by blakeembrey** [comment]
Just some thoughts, but why wouldn't you be able to use `dataPath` programmatically? I think the idea of `prettyDataPath` would end up too opinionated. A different idea would be to show the containing object in the data output. That said, I think the tooling around consuming the `dataPath` is the best way to go forward - if you use JSON pointers you can use https://www.npmjs.com/package/json-pointer and with the default `dataPath` you could try something like https://github.com/component/to-function (haven't researched too much on that, maybe someone else can help you more).

**Comment by epoberezkin** [comment]
There is also a simple library [object-path](https://github.com/mariocasciaro/object-path) that can be used to find an object by path. Another approach is to use eval:

```
var data = { /*...*/ };
var dataPath = '.assetGroups['166'].previewUrl';
var value = eval('data' + dataPath);
```

It is most likely faster than a library that parses and iterates path.

There is also an option `verbose` that would include both the related schema and the data object in the error.

**Comment by epoberezkin** [comment]
What is probably wrong here is that the number should not be in quotes. Although it makes no difference for JS, they are unnecessary. So renaming the issue...
