### ISSUE TITLE
`select`/`selectCases` have issues with `additionalProperties`

### ISSUE THREAD

**Issue by beeplin** [ajv-validator/ajv#480]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

5.0.1
yes it happens in the latest version

**Ajv options object**

```javascript
{ $data: true }
```

**JSON Schema**

```json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "option": {}
  },
  "select": {
    "$data": "0/option"
  },
  "selectCases": {
    "a": {
      "required": [
        "a"
      ],
      "properties": {
        "a": {
          "type": "string"
        }
      }
    }
  }
}
```

**Sample data**

```json

{ 
  "option": "a", 
  "a": "xxx"
}
```

**Your code**

```javascript
var Ajv = require('ajv');
var keywords = require('ajv-keywords');
var ajv = new Ajv(options);
keywords(ajv);
var validate = ajv.compile(schema);
var valid = validate(data);
if (!valid) console.log(validate.errors);

```
https://runkit.com/beeplin/590a0e9406df05001212c1b6

**Validation result, data AFTER validation, error messages**

```
[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: 'a' },
    message: 'should NOT have additional properties' } ]

```

**What results did you expect?**

It should pass the validation, which means `addtionalProperties` should also take count in those `properties` under `selectCases`.

**Comment by epoberezkin** [comment]
@beeplin It has nothing to do with "select", "additionalProperties" only takes into account properties defined in the same schema object, so property "a" is indeed "additional".

See https://github.com/epoberezkin/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc

**Comment by epoberezkin** [comment]
Also example 3 in https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#additionalproperties

**Comment by beeplin** [comment]
Thanks @epoberezkin , sorry for missing the FAQ.

So I moved all the `properties` above to the top-level , only keeping `required` in `selectCases`, and it worked. :)
