### ISSUE TITLE
Move regenerator and nodent to ajv-async

### ISSUE THREAD

**Issue by segphault** [ajv-validator/ajv#482]
The regenerator runtime by itself makes up just under half of ajv's npm package installation footprint. Considering that the async features were split out into a separate package anyway and the regenerator runtime is relatively easy for frontend people to add to their projects separately, would it be possible to not include the regenerator runtime in the npm package? Or maybe have a separate package for the frontend dist stuff?

**Comment by epoberezkin** [comment]
It would be the right thing to do. It would require:
1. moving nodent and regenerator to ajv-async (its next major version)
2. moving all tests that use them there as well
3. publishing ajv-async to cdnjs

Once it's done, they can be removed from here in the next major version, together with the tests that use them.

**Comment by epoberezkin** [comment]
in [6.0.0-beta.2](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-beta.2)
