### ISSUE TITLE
Improve design of GitHub pages

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#487]
Also make it responsive / mobile and compatible with all major browsers.
http://epoberezkin.github.io/ajv/

**Comment by hachi-studio** [comment]
Still need help with this? 😄

**Comment by epoberezkin** [comment]
Somebody was going to do it but probably busy... So yes, thank you :)

**Comment by hachi-studio** [comment]
Could you contact them to let them know I'll be working on it incase they are still planning to start it?

It will take a few days for me to mock up and design, I will update you for Saturday with some ideas. Let me know if that's ok!

**Comment by hachi-studio** [comment]
Hey @epoberezkin, I have done some basic wireframes, here are my thoughts.

Currently, nearly everything is on one single page. We could de-clutter it with essentials (getting started, features etc) and have a documentation section with sub-sections for all the things on the home page (Formats, $data references etc)
Here are the wireframes:
[Desktop](https://s13.postimg.org/xk32o3oqf/Desktop.png)
[Mobile](https://s3.postimg.org/x4yv82503/Mobile.png)

This is just to give you an idea, I was thinking of having a fixed menu as the sidebar which follows you along, and menu items are accordion based (so we can #link to sections within documentation).

Again it's rough, content is just placed there to get a visual idea and no design has been applied, let me know your thoughts!

**Comment by epoberezkin** [comment]
Hi @ui-xp. I've sent logo via email.

I like the design suggestion, but I still want to have the site generated from readme and other markdown files, I don’t want to maintain separate HTML site… Would it be possible to break readme into sections with CSS and/or JavaScript?

**Comment by epoberezkin** [comment]
Otherwise in can be done by extending gh-pages-generator to support sections

**Comment by hachi-studio** [comment]
Thanks, I'll take a look to see how this works.

**Comment by epoberezkin** [comment]
@ui-xp maybe, to keep things simple, you could just improve the design/layout with the current information structure. Then I could look how to implement sections in gh-pages-generator.

Also, maybe it's enough to expose table of contents somewhere in navigation without breaking the readme to sections - it could be a good compromise (in a sense that only TOC will be duplicated, not all content).

**Comment by hachi-studio** [comment]
Yeah, I'll just create a responsive template, keep the current structure and add some light styling, we are ok with using bootstrap 4?

**Comment by epoberezkin** [comment]
sure

**Comment by hachi-studio** [comment]
Made a start on it at https://github.com/ui-xp/ajv-page

Nothing to really see yet, when I make some more progress I'll update you!

**Comment by hachi-studio** [comment]
Hey @epoberezkin 

Haven't had much time but here is something you can checkout.

https://github.com/ui-xp/ajv-page

Instructions are on the page how to run it, it's more of a style guide also did a variation on the logo to brand it a bit better, but up to you if you want to use it. 

Styles should be easy to update and however you popular the site currently (readme?) just pop that content in the main white container, also site is now responsive!

Let me know if you have any questions.

**Comment by jhohlfeld** [comment]
What about https://www.gitbook.com/? It's pretty much standard nowadays and looks great!

Check this option out (lowest effort possible): 
![bildschirmfoto 2017-09-25 um 17 20 48](https://user-images.githubusercontent.com/497141/30816415-363250c8-a216-11e7-838a-17fd0d81f7e4.png)

**Comment by Erioldoesdesign** [comment]
Can someone let me know if I can close the associated open source design job issue? https://opensourcedesign.net/jobs/jobs/2017-05-11-ajv-github-pages-design-for-desktop-and-mobile

**Comment by epoberezkin** [comment]
@Erioldoesdesign yes - thank you!
