### ISSUE TITLE
Validate JSON Schema

### ISSUE THREAD

**Issue by bassundar** [ajv-validator/ajv#489]
I validate JSON request against the JSON Schema,
Input may be address request or Phone request
If the request is Address, then i need to validate mandatory fields in address
If the request is Phone, then i need to validate mandatory fields in phone

But my below JSON schema, Please correct me if anything wrong

```
{
  "any Of": [
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "definitions": {},
      "id": "http://example.com/example.json",
      "properties": {
        "addresses": {
          "id": "/properties/addresses",
          "properties": {
            "address1": {
              "id": "/properties/addresses/properties/address1",
              "type": "string"
            },
            "address2": {
              "id": "/properties/addresses/properties/address2",
              "type": "string"
            },
            "countryId": {
              "id": "/properties/addresses/properties/countryId",
              "type": "string"
            },
            "stateId": {
              "id": "/properties/addresses/properties/stateId",
              "type": "string"
            },
            "typeId": {
              "id": "/properties/addresses/properties/typeId",
              "type": "string"
            }
          },
          "required": [
            "stateId",
            "typeId",
            "countryId"
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "definitions": {},
      "id": "http://example.com/example1.json",
      "properties": {
        "phones": {
          "id": "/properties/phones",
          "properties": {
            "areaCode": {
              "id": "/properties/phones/properties/areaCode",
              "type": "string"
            },
            "typeId": {
              "id": "/properties/phones/properties/typeId",
              "type": "string"
            }
          },
          "required": [
            "typeId"
          ],
          "type": "object"
        }
      },
      "type": "object"
    }
  ]
}
```

Validate against the below JSON phone request
```
{
  "phones":
    {
      "areaCode":"972",
      
    }
}
```

Even Type Id is required, it is not showing JSON 'FAILED' in the below online JSON validator
http://www.jsonschemavalidator.net/

**Comment by epoberezkin** [comment]
@bassundar it passes because it successfully validates against the first subschema and "phones" is not prohibited there. That's not the question related to Ajv specifically - it's about the usage of JSON schema.

**Comment by epoberezkin** [comment]
See: http://epoberezkin.github.io/ajv/contribute.html#json-schema

**Comment by bassundar** [comment]
Please correct my JSON schema in such a way for the below validation
1. If I provide below phone request with out type Id, it should say 'typeid is required'
{
  "phones":
    {
      "areaCode":"972",
      
    }
}
2.Similarly If I provide below address request with out type Id, I should say 'typeid is request'
{
  "addresses": {
  "address1": "vin st",
  "address2": "4444",
  "countryId": "616",
  "stateId": "55"
 }
}

Please help me on correcting my JSON schema, i really appreciate your help
