### ISSUE TITLE
improvement : add cli command

### ISSUE THREAD

**Issue by AlbanMinassian** [ajv-validator/ajv#49]
Like jayschema, can you add a client command, like 'ajv' 

ajv --externalschema=xxxxx  my.schema.json

Thnak
Ami44

**Comment by epoberezkin** [comment]
There is a package [ajv-cli](https://github.com/jessedc/ajv-cli) by @jessedc that does it.
If it misses some features it should be easy to add there.

**Comment by AlbanMinassian** [comment]
Ho ... thanks

**Comment by epoberezkin** [comment]
:)
