### ISSUE TITLE
Relative uris

### ISSUE THREAD

**Issue by wertlex** [ajv-validator/ajv#491]
Sorry for a bit stupid question, but does it really okay to make `uri` format not pass relative uris?
If so, is it possible to get motivations behind that decision?

Thanks

**Comment by epoberezkin** [comment]
That's the change from draft-04 to draft-06 of JSON schema specification - see [migration guide](https://github.com/epoberezkin/ajv/releases/tag/5.0.0). Relative uri are valid with "uri-reference" format.
