### ISSUE TITLE
Uniqueness across fields

### ISSUE THREAD

**Issue by bayleedev** [ajv-validator/ajv#492]
I have some objects inside of an array, and each object contains an `id` that should be unique within the array.

~~~js
{
  "items": [
    { "id": 1, "name": "ajv" },
    { "id": 2, "name": "ajv-cli" },
    { "id": 3, "name": "ajv-errors" }
  ]
}
~~~

Is there a way to validate the uniqueness of the `id` field within the `items` array?

**Comment by epoberezkin** [comment]
@blainesch Not using the standard keywords. You will need to either do it outside of schema or to define a custom keyword, e.g. "uniqueItemProperties" that accepts the array of property names which values should be unique across all items:

```json
{
  "uniqueItemProperties": ["id"],
  "items": [
    { "id": 1, "name": "ajv" },
    { "id": 2, "name": "ajv-cli" },
    { "id": 3, "name": "ajv-errors" }
  ]
}
```

It can be a useful thing, feel free to contribute to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords) if you do it.

**Comment by bayleedev** [comment]
Thanks!

**Comment by shogunzalo** [comment]
This is how I solved id, it can be improved to receive an array of keys in the future:

```
// In my schema:
customInfo: {
      type: ARRAY,
      uniqueItemProperties: "name",
      items: customPropertySchema,
},

// Keyword implementation
ajv.addKeyword("uniqueItemProperties", {
  validate: function(uniqueItemName, data) {
    const propertyValues = data.map(element => element[uniqueItemName]);
    return propertyValues.length > 1 ? !_hasDuplicates(propertyValues) : true;
  },
});

const _hasDuplicates = array => {
  return new Set(array).size !== array.length;
};

**Comment by epoberezkin** [comment]
Great! Also have a look at uniqueItemProperties in ajv-keywords
