### ISSUE TITLE
Malware? Clamav scan found infected file in your repo

### ISSUE THREAD

**Issue by rodrev** [ajv-validator/ajv#495]
Hello,
I've just run a scan with Clamav and it marked a file from your repo as malware. Can you pls have a look and let me know if I should report this as a false positive or if there is possibly some security flaw in the code that you can find. Thank you.

This is the filename and output from clamscan:
```
~/.npm/ajv/5.1.1/package/dist/regenerator.min.js
Sanesecurity.Malware.26777.JsHeur.UNOFFICIAL FOUND
```

**Comment by epoberezkin** [comment]
Most likely it is a false positive. Probably should be reported to https://github.com/facebook/regenerator as the bundle is created from their code.

**Comment by rodrev** [comment]
okay thank you.

**Comment by epoberezkin** [comment]
@rodrev closing it here, it would be good if you could submit to regenerator - they'll probably need more information about how to reproduce.
