### ISSUE TITLE
Problem with $data validation after migrating to 5.x.

### ISSUE THREAD

**Issue by gboysko** [ajv-validator/ajv#498]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

5.1.3

**Ajv options object**

```javascript
new Ajv({useDefaults: true, v5: true});
```

**JSON Schema**

```javascript
{
        $id: 'Foo',
        'properties': {
            'startOffset': {
                'type': 'integer',
                'minimum': 0
            },
            'endOffset': {
                'type': 'integer',
                'minimum': {'$data': '1/startOffset'},
            }
        }
}

```

**Sample data**

```javascript
{'startOffset': 1, 'endOffset': 0}
```

**Validation result, data AFTER validation, error messages**

```
Error: schema is invalid: data.properties['endOffset'].minimum should be number
```

**What results did you expect?**
This had worked in the past with an earlier version of ajv. I can't migrate my schema automatically because it is embedded inside some JavaScript code.

**Are you going to resolve the issue?**
I've read section on `$data` properties, and it seems like I did it right, but not sure how `minimum` can be a number at this point.

**Comment by epoberezkin** [comment]
`v5` option is no longer used, for $data reference support you need to use `$data` option. See https://github.com/epoberezkin/ajv/releases/tag/5.0.0

**Comment by gboysko** [comment]
Does this mean that I can no longer cache my validation functions for re-use? I create validation functions for each schema, compiling each separately. I'm getting the error when I try to assemble my schemas (using `Ajv.addSchema`). This happens before I have any data to validate yet.

**Comment by epoberezkin** [comment]
5.x is backward compatible, it still compiles schemas to functions. You just need to follow the migration guide as I wrote, and use $data option and not v5 option.

You cannot addSchema because it is not a valid schema unless you use $data option that makes it valid (by extending meta-schema).

**Comment by gboysko** [comment]
Thanks, @epoberezkin. Sorry for the confusion. I thought I had to supply the actual data object in the constructor. By using `new Ajv({useDefaults: true, $data: true})`, I was able to generate all of my schema validator functions.
