### ISSUE TITLE
Resolve previously missing references when additional schemas are compiled

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#5]
That will enable mutual (circular) references between schemas.
That is more complex than it seems because resolution could fail in the middle of resolution chain and the newly added schema may not contain the required reference but be inside some resolution chains.
So the resolutions that were stopped because they couldn't find the newly added schema (and also any IDs contained in it - another complication) have to be re-tried.

**Comment by epoberezkin** [comment]
The solution is to separate adding schemas from compiling schemas. Schemas will be compiled on demand or when they are first used, so multiple schemas can be added before the first one is compiled.

**Comment by cdm6a** [comment]
Would be great if you could add all your schemas and then compile as this would support being able to parse a folder of schemas and add them without having to manually put them in order.

**Comment by epoberezkin** [comment]
Agreed. Given the declarative nature of schema definition, the need to manage the order is not great. Also recursive definitions do have the use cases - I need them for another project. I think I may have time to do it some time this week. Or if you'd like to contribute that would be great. It's not the most simple change though - schemas are stored as functions at the moment and there are many places in the code that rely on that...

**Comment by epoberezkin** [comment]
@cdmcnamara check out the version in the branch 1.0.0. Compilation is separated from adding schemas, so addSchema returns nothing, order of addition is not important and circular dependencies between schemas also work.

Everything else works as before, schemas can either be compiled explicitly with compile or they will be compiled when they are first used with validate or with getSchema.

That would be great if you could try it with your schemas before I merge it into master. You can include it in package.json as epoberezkin/ajv#9b1361c92e (https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

Thanks!

**Comment by cdm6a** [comment]
Thanks @epoberezkin will start playing around with it today

**Comment by cdm6a** [comment]
Looks like all the tests are passing except one, I'm running a test were I validate the top level schema and have a definition in a schema that is a few children deep:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "AdditionalInfo",
  "title": "AdditionalInfo",
  "description": "More info about this payment",
  "definitions": {
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A human-readable string describing the error",
          "type": "string"
        },
        "code": {
          "description": "A machine-parseable string describing the error",
          "type": "string"
        }
      },
      "required": ["message", "code"]
    }
  },
  "type": "object",
  "properties": {
    "error": {
      "description": "Present if the SubPayment incurred an error",
      "$ref": "#/definitions/error"
    },
    "hash": {
      "$ref": "Hash256"
    }
  },
  "additionalProperties": true
}

```

When I attempt to validate this I get the following error:
`Error: can't resolve reference #/definitions/error from id Payment#`

Where Payment is the name of the top level schema. So it appears as if the context of `#/definition/error` is at the top level object and not on the object a few children deep.

If I just try and validate the object a few children deep, there are no issues

**Comment by epoberezkin** [comment]
Thanks. Could you post the Payment schema as well please? Am I right that it was working ok with the previous version? I will check anyway.

**Comment by epoberezkin** [comment]
@cdmcnamara sorry can't reproduce. Can you please post Payment and Hash256 and maybe some valid/invalid samples. Thanks

**Comment by epoberezkin** [comment]
Branch 1.0.0 was merged into master
