### ISSUE TITLE
The validation error for forbidden additionalProperties should include the additional properties name

### ISSUE THREAD

**Issue by astitt-ripple** [ajv-validator/ajv#500]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Using 4.x, I think the issue is still present in 5.x but have not yet migrated my project to 5.x to verify.

**Validation result, data AFTER validation, error messages**

Currently I will get a validation error like the following when my input data has additional properties and I've selected in the schema file that those are not allowed (some fields excluded for conciseness).

```
[{"keyword":"additionalProperties","dataPath":".test","message":"should NOT have additional properties"}]
```

**What results did you expect?**
Instead of a generic message, I would like to additionally see the name of the field, so I can more easily resolve the issue in my application (either by adding the field to my schema, or removing the extra field in the data).

So for example if I added a field named `foo` that isn't defined in the schema, I would see an error like this:
```
[{"keyword":"additionalProperties","dataPath":".test","message":"should NOT have additional properties: foo"}
```
**Are you going to resolve the issue?**

Absolutely, that is my intention!

I've tested the following change with 4.x and verified it includes the additional property name:
```
diff --git a/lib/dot/errors.def b/lib/dot/errors.def
index 3e04721..ac5994b 100644
--- a/lib/dot/errors.def
+++ b/lib/dot/errors.def
@@ -93,7 +93,7 @@
 {{## def._errorMessages = {
   $ref:            "'can\\\'t resolve reference {{=it.util.escapeQuotes($schema)}}'",
   additionalItems: "'should NOT have more than {{=$schema.length}} items'",
-  additionalProperties: "'should NOT have additional properties'",
+  additionalProperties: "'should NOT have additional properties: {{=$additionalProperty}}'",
```

**Comment by epoberezkin** [comment]
@astitt-ripple please see https://github.com/epoberezkin/ajv/issues/476

Also: https://github.com/epoberezkin/ajv/blob/master/FAQ.md#why-dont-additionalproperties-false-errors-display-the-property-name

Sorry, I don't want to make this change in the library.

**Comment by astitt-ripple** [comment]
Hmm. That faq section has the title 'Additional properties inside compound keywords anyOf, oneOf, etc.' However, I am not concerned with that situation at all in this issue, only with fields not described in the top level 'properties' section. The FAQ does not seem to address why that case cannot be supported, it only talks about how things get weird when oneOf or anyOf are mixed in. Given that, I'm having trouble getting from that faq section to how this bug and my proposed resolution is a duplicate/wont-fix.

The params field inside the error actually has the missing property name (this was mentioned in 476 as well). Other error types seemed to include those specifics in the message too. However since the library doesn't do that for this particular error, even though the information is available (as far as I can tell), I need to add some special casing to make the message actionable by appending the property name from the params. Sure I can do that in my integration, but that then makes it harder to use `errorsText()`.

I'm sorry to take any more of your time, but it would help me if you could explain how the anyOf/oneOf issue relates to why the additional property name cannot be added to the message when anyOf/oneOf are not involved. If there is some tricky technical issue where my patch will not work in that special case, I am happy to dive into the code and come up with an agreeable solution.

**Comment by epoberezkin** [comment]
> That faq section has the title 'Additional properties inside compound keywords anyOf, oneOf, etc.'

The section I sent the link to is titled: "Why don't "additionalProperties": false errors display the property name?"

> The FAQ does not seem to address why that case cannot be supported

It says: "Doing this would create a precedent where validated data is used in error messages, creating a vulnerability (e.g., when ajv is used to validate API data/parameters and error messages are logged)."

> Other error types seemed to include those specifics in the message too.

Only when these specifics are from the schema, not from the data.

> but that then makes it harder to use errorsText().

It is not the case. You can modify messages how you need, then you can call errorsText(). How is that more difficult?

**Comment by astitt-ripple** [comment]
I'm sorry, I was looking at the larger titled section, and not the smaller titled one right above it that you were actually citing. My apologies for the confusion, thank you for taking the time to reply.

That we can't put (potentially nasty) non-validated data from the input object into the error message makes sense.

Regarding getting `errorsText()` to print an actionable message for this case, you're right I would need to modify the error.message fields before calling it. Not ideal, I was hoping to avoid mutating the error object, but that is workable.

Thanks.
