### ISSUE TITLE
url missing in dependencies

### ISSUE THREAD

**Issue by bernharduw** [ajv-validator/ajv#503]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

v5.1.3 (latest from npm)

**result **
The `url` dependency is missing from package.json. It's required in [/lib/compile/resolve.js](https://github.com/epoberezkin/ajv/blob/fde7030a19833273b08e8de879cb2bf149adaf2f/lib/compile/resolve.js)

**Comment by epoberezkin** [comment]
url is a core nodejs module, it is also available when you use browserify/webpack.

For any other environment that doesn't include code nodejs modules you may need to add it to your app's package.json.

See https://github.com/epoberezkin/ajv/issues/435

**Comment by bernharduw** [comment]
Thanks, that's correct – I was using ajv within react-native.
