### ISSUE TITLE
Cannot load local $ref definitions

### ISSUE THREAD

**Issue by dolphub** [ajv-validator/ajv#505]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.1.3

**JSON Schema**

```json
{
  "id": "Sometypes",
  "type": "object",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    }
  }
}

{
    "id": "Animal",
    "type": "object",
    "properties": {
        "uid": {
            "$ref": "Sometypes#/definitions/uuid"
        },
    }
}
```

**Your code**

```javascript
const schema: any = require(filePath);
ajv.addSchema(schema);

ajv.validate('Animal', { uuid: '68208874-fdcb-4d9a-b9ee-cbbdc8cb7c4c'});
```

**Validation result, data AFTER validation, error messages**

```
Error: Reference not found: http://json-schema.org/Sometypes#/definitions/uuid

```

**What results did you expect?**
Expected to see that this validates, but it seems that the reference isn't finding our definitions for uuid.  Both of the json files are being passed through addSchema.

**Comment by epoberezkin** [comment]
the code sample uses only one schema

**Comment by epoberezkin** [comment]
it works for me: https://runkit.com/esp/59274b20c2d9b00012771e6b

**Comment by epoberezkin** [comment]
@dolphub And actually I cannot reproduce your error message even if I add only one schema - I am getting `"can't resolve reference Sometypes#/definitions/uuid from id Animal#"`, which is expected.

Can you post your code please?

**Comment by dolphub** [comment]
Interesting, it seems to be working when it's just a validate. 

Essentially I'm implementing a mocking functionality to the API I'm building using [json-schema-mocker](https://github.com/json-schema-faker/json-schema-faker).  I suspect it has something to do with how I'm getting the schema back out of AJV.  

```
// getSchema with error handling removed:
return ajv.getSchema('Animal').schema;
```
which is then passed into the mocker library with that return result.

```
const schemaFaker = require('json-schema-faker');
schemaFaker.sync(schema);
```

**Comment by epoberezkin** [comment]
@dolphub ok, so the error is from json-schema-faker, not from Ajv. Probably it is because Ajv doesn't resolve references, so you have to pass both schemas to this faker. See https://github.com/epoberezkin/ajv/blob/master/FAQ.md#generating-schemas-with-resolved-references-ref
