### ISSUE TITLE
Get required

### ISSUE THREAD

**Issue by eduardoinnorway** [ajv-validator/ajv#511]
I have a schema with conditionals "allOf" where one is required if a condition is set, for example Name starts with "A".

```
    {
      "if": {"properties": {"name": {"pattern": "^A"}}},
      "then": {"required": ["age"]}
    },
```

I want to show a "*" on the label of all required. I would like to avoid to have same logics implemented twice, both on the form and then on the schema.

Can I get if something is required from AJV matching schema to validation?

for example something like this:

```
const isAgeRequired = checkIsRequired(mySchema, data, 'age')
....
<label>Age {isAgeRequired && '*'}</label>
```

**Comment by epoberezkin** [comment]
> Can I get if something is required from AJV matching schema to validation?

I don't understand the problem. Ajv performs validation according to the spec. You can define custom validation logic using custom keywords. Then you can process errors (that have all the information about the reasons of failure) how your application needs. You problem fits in one of these. Or it's something else?

**Comment by epoberezkin** [comment]
I think I understand now that you want some schema analysis - to traverse the schema and to see if a particular field is required anywhere. It's definitely out of scope of Ajv. To traverse the schema you can use [json-schema-traverse](https://github.com/epoberezkin/json-schema-traverse) package.
