### ISSUE TITLE
Defaults not assigned when using compileAsync

### ISSUE THREAD

**Issue by irvinlim** [ajv-validator/ajv#515]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

5.1.5 (latest)

**Ajv options object**

```javascript
useDefaults: true,
loadSchema: (uri) => {
  return request.json(uri).then(function (res) {
    if (res.statusCode >= 400)
      throw new Error('Loading error: ' + res.statusCode);
    return res.body;
  });
}
```

**JSON Schema**

```json
{
    "properties": {
        "foo": {
            "default": { "bar": 1 }
        }
    }
}
```

**Sample data**

```json
{}
```

**Your code**

You can view the demo repro runkit [here](https://runkit.com/irvinlim/5938c4be4bee060012f96553).

```javascript
// Asynchronous: Bug exists

const validator = new Ajv({
    useDefaults: true,
    loadSchema: uri => {
        return request.json(uri).then(function(res) {
            if (res.statusCode >= 400)
                throw new Error('Loading error: ' + res.statusCode);
            return res.body;
        });
    }
});

validator.compileAsync(testSchema, true).then(validate => {
    const data = {};

    console.log('Async validate: ' + validate(data));
    console.log('Async data: ' + JSON.stringify(data));
});

// Synchronous: Bug does not exist

const validator2 = new Ajv({
    useDefaults: true
});

const validate2 = validator2.compile(testSchema2);
const data2 = {};
console.log('Sync validate: ' + validate2(data2));
console.log('Sync data: ' + JSON.stringify(data2));
```

**Validation result, data AFTER validation, error messages**

```
Sync validate: true
Sync data: {"foo":{"bar":1}}
Async validate: true
Async data: {}
```

**What results did you expect?**

```
Sync validate: true
Sync data: {"foo":{"bar":1}}
Async validate: true
Async data: {"foo":{"bar":1}}
```

**Are you going to resolve the issue?**

I'll try to look into it if I have time. I haven't looked at the codebase so I'm not sure if I will be able to hunt down the issue.

**Comment by irvinlim** [comment]
I just found out that omitting the second parameter from `compileAsync`, i.e. doing `validator.compileAsync(testSchema)` will make it work. I suppose we can close this as a non-issue.

I'm not 100% sure why this is the case though. The documentation says: 

> You can asynchronously compile meta-schema by passing true as the second parameter.

Maybe I don't fully understand what a meta-schema is, but how does this change things?

**Comment by epoberezkin** [comment]
meta-schema is a schema that describes the schema itself. All draft-06 schemas should be valid documents according to draft-06 meta-schema. Meta-schemas ignore option useDefaults, as otherwise your schemas would be modified.

**Comment by epoberezkin** [comment]
http://json-schema.org/documentation.html

**Comment by irvinlim** [comment]
Got it! Perhaps maybe we could add this in the documentation as well, because it's not exactly clear that meta-schemas should ignore useDefaults, and that setting the argument to `true` means that the schema is a meta-schema... 

I interpreted that line as to compiling the meta-schema defined in `$schema`, rather than saying that `compileAsync(schema)` will consider `schema` to be a meta-schema.
