### ISSUE TITLE
compileAsync race condition

### ISSUE THREAD

**Issue by abalmos** [ajv-validator/ajv#52]
If a schema has a $ref and compileAsync is called on it while another compileAsync is running on it then ajv randomly throws. Here is an example:

``` js
var Ajv = require('ajv');

var schemas =  {
  "http://example.com/parent.json": {
    "id": "http://example.com/parent.json",
    "required": [
      "a"
    ],
    "properties": {
      "a": { "$ref": "child.json" }
    }
  },
  "http://example.com/child.json": {
    "id": "http://example.com/child.json",
    "required": [
      "b"
    ],
    "properties": {
      "b": { "type": "string" }
    }
  }
};

var ajv = Ajv({
  loadSchema: function(uri, callback) {
    setTimeout(function() {
      callback(null, schemas[uri]);
    });
  }
});

ajv.compileAsync(schemas["http://example.com/parent.json"], function(err, validate) {
  console.log(validate({a: { b: "test"} }));
});

ajv.compileAsync(schemas["http://example.com/parent.json"], function(err, validate) {
  console.log(validate({a: { b: "test"} }));
});
```

Which typically results in the exception:

Error: schema with key or id "http://example.com/child.json" already exists

**Comment by epoberezkin** [comment]
Interesting. I guess there is no protection from it. Those calls should be queued and while the one is running another should not start. And by the time the first one finishes, the schema will already be compiled so that the second will return immediately. The solution is to queue inside ajv, the workaround is to queue outside.

**Comment by epoberezkin** [comment]
I've improved it. It doesn't queue calls, but it makes sure that each schema is only loaded once even if it is requested multiple times because of concurrent calls to compileAsync.
