### ISSUE TITLE
Missing error message after validation failed by missing required property

### ISSUE THREAD

**Issue by vmoebius** [ajv-validator/ajv#520]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.1.5

**Ajv options object**

```javascript
undefined


```

**JSON Schema**
```json
{
	"title": "Count Input",
	"type": "object",
	"properties": {
		"items": {
			"type": "array",
			"items": {
				"title": "Count Item",
				"type": "object",
				"properties": {
					"type": {
						"title": "Count Item Type",
						"type": "string"
					}
				},
				"required": [
					"type"
				]
			}
		}
	},
	"required": [
		"items"
	]
}
```

**Sample data**

```json
{

	"items": [
		{"type": "MO"},
		{}
	]
}

```

**Your code**

```javascript
const Ajv = require('ajv');
ajv = new Ajv();
validate = ajv.compile(schema);

if (!validate(data)) {
	console.log(ajv.errorsText());
}

```

**Validation result, data AFTER validation, error messages**

```
validate(data) == false && ajv.errorsText() == "No errors"

```

**What results did you expect?**

Meaningful error message (path of failing property) if validate returns false

**Are you going to resolve the issue?**

No

**Comment by epoberezkin** [comment]
if you use compiled function, you need to pass errors: `ajv.errorsText(validate.errors)`. It can be used without parameters after the call of `ajv.validate`.
