### ISSUE TITLE
Rename lib/$data.js and lib/refs/$data.json without the "$"

### ISSUE THREAD

**Issue by Kirtlander** [ajv-validator/ajv#526]
Using ajv-5.1.5

We use ajv as a dependency to webpack in the development of single page web applications. Our corporate build servers are configured (by design) to not be able to access Internet resources, including npmjs.com. Since we do not have an internal npm server, we are forced to check-in our dependencies so our build servers can build our web sites. The issue here is that ajx had two files that cannot be checked into TFS -  $data.js and $data.json. This is the first such issue we've encountered in a nodejs type library.

In order to maintain compatibility with the TFS system that is still popular in corporate environments, it would be helpful to rename the $data.* files to simply data.* to allow them to be checked in to TFS. TFS restricts filenames from including the following characters - "/ \ [ ] : | < > + = ; ? * https://www.visualstudio.com/en-us/docs/reference/naming-restrictions

I would create a pull request with a fix; however unfortunately I am forbidden by my employer from contributing to such projects.

**Comment by sreekumarp** [comment]
What can be the new file name ? data.js is fine ?

**Comment by cgocgo** [comment]
I would suppose that data.js is fine. TFS is refusing to accept file names that starts with a $ for some reason. In other words: It is the leading $ that is the problem.

**Comment by epoberezkin** [comment]
@Kirtlander if you do a PR please make it to the branch "beta", I can release it as a beta version.

**Comment by corte** [comment]
Any progress on this?
I really need to add this files to TFS and the leading $ is a complication.

**Comment by kietresolve** [comment]
what i have done in the mean time is replace all the "$" to "_dollar_" in this module while waiting for the 6.0

**Comment by epoberezkin** [comment]
Feel free to submit PR to "beta" branch. "$" can be just dropped.

**Comment by CosmicBara** [comment]
I am having issues with getting Pending Changes in Team Explorer on Eclipse (on a Mac) due to this issue. My Pending Changes list is always empty because it detects the $ and silently fails. What can I do in the meantime to resolve this?

**Comment by epoberezkin** [comment]
@GunslingerBara as I wrote above, you can submit PR to "beta" branch (not to master as it is a breaking change), I will then release version 6-beta.

**Comment by platinumazure** [comment]
@epoberezkin I'm running into this myself, so I could submit a pull request over the weekend. Would you mind giving me a quick primer on why this is a breaking change?

**Comment by Kirtlander** [comment]
I'm not sure why this would be considered a breaking change; I was able to
patch this locally by simply renaming the file and the reference, removing
the leading "$" symbol.

Ideally, I would like to install the package unpatched in the event I need
to refresh my node_modules in my project prior to checking them into TFS.
Our corporate build servers don't have access to the Internet; therefore
cannot run npm install on the fly, necessitating checking in all the
dependencies with the project.

**Comment by epoberezkin** [comment]
> why this is a breaking change?

Because this is a public schema URI that depends on the file name: https://raw.githubusercontent.com/epoberezkin/ajv/master/lib/refs/$data.json#

(https://github.com/epoberezkin/ajv/blob/master/lib/refs/%24data.json#L3)

> I would like to install the package unpatched

Once the change is released you will be able to install ajv@6.0.0-beta.0 without any patches

**Comment by epoberezkin** [comment]
in [6.0.0-beta.0](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-beta.0)

**Comment by platinumazure** [comment]
Thanks @epoberezkin, and sorry I couldn't get to this in a timely fashion.

Anything I can subscribe to for watching for the official 6.0.0 release? Thanks!

**Comment by epoberezkin** [comment]
No problem. Probably just watch the repo? Or gitter. Also, if you use greenkeeper it will tell.
