### ISSUE TITLE
can't resolve reference #/definitions/Pet from id #

### ISSUE THREAD

**Issue by sunshinecotejo** [ajv-validator/ajv#530]
Hi epoberezkin, 

We are using your library to validate against swagger json.
We just encountered error in using the validate method.

 ajv.validate( {"$ref": "#/definitions/Pet"}, obj);
ERROR {"message":"can't resolve reference #/definitions/Pet from id #","missingRef":
"#/definitions/Pet","missingSchema":""}
TypeError: Cannot read property 'message' of undefined

Possible Solutions
1) use the ajv.validate method but the problem is how to make the schemaRefKey dynamic in function validate(schemaKeyRef, data);

  ajv.addSchema(swaggerSchema, 'swagger.json')
  var isValid = ajv.validate({ $ref: 'swagger.json#/definitions/Pet' }, obj);
  console.log('isValid:'+ isValid)
  console.log(JSON.stringify(ajv.errors));
 
2) use the ajv.getSchema but id='http://example.com/schemas/swagger.json#/definitions/Pet' attribute creates some errors in swagger.json

> Errors
Hide
Schema error at instance
additionalProperty "id" exists in when not allowed
Jump to line 0

   ajv.addSchema(swaggerSchema, 'Pet');
   const validate = ajv.getSchema('http://example.com/schemas/swagger.json#/definitions/Pet');
  console.log(`validation: ${validate(obj)}`);

Thanks

**Comment by epoberezkin** [comment]
Approach 1 works for me, you need to submit a simplified failing code, ideally via runkit.com

**Comment by sunshinecotejo** [comment]
Hi @epoberezkin,

Please see https://runkit.com/timbuktuprincess/59560318379844001275b189.
Thanks

**Comment by epoberezkin** [comment]
there is no object with the JSON pointer '/definitions/Pet' in the schema, there is an object with the pointer '/paths/definitions/Pet'. If you fix it it resolves it: https://runkit.com/esp/59561ee71cba570012815d8f

There are missing formats, they should either be defined or ignored.

**Comment by pbelamkar** [comment]
Hi epoberezkin, 

I am facing different issue, could you please help me for this. 
I have checked "sunshinecotejo" schema and as per your suggestion, i have checked Json Pointer in '/definitions/Pet but i think there is already Json Pointer is present. Or i am not able to understand this. 

Same type of json schema i have which not throwing any error and not validating key type. Could you please help me. 

Use Case : If i am passing wrong type in schema it should throw error but it's not throwing any error.
