### ISSUE TITLE
"required" question

### ISSUE THREAD

**Issue by ro70** [ajv-validator/ajv#535]
```
var schema = {
  "id": "test.json#",
  "definitions": {
    "body": {
      "type": "object",
      "properties": {
        "name": {"type": "string"},
        "age": {"type": "integer"},
      }
    },
    "request": {
      "properties": {
        "user": {
          "$ref": "#/definitions/body"
        }
      }
    }
  },
  "typeA": {
    "$ref": "#/definitions/request"
  },
  "typeB": {
    "allOf": [
      {"$ref": "#/definitions/request"},
      {"required": ["name"]} // Should require the name field in the user object.
    ]
  }
}

var Ajv = require('ajv')
var ajv = Ajv({
  schemas: [schema]
})

var data = {
  user: {
    "name": "tom",
    "age": 1
  }
}

var valid = ajv.validate({$ref: "test.json#/typeA"}, data)
console.log('VALID', valid) // Returns true.
var valid = ajv.validate({$ref: "test.json#/typeB"}, data)
console.log('VALID', valid) // Returns false.
```

I'm new to ajv and json schemas. I'd like to reuse the request-schema in typeA and typeB. typeB should require the name field in the user-object. How do I achieve this? I know why my solution above is not working. Required should be something like "user.name".

Thanks you for your help.

**Comment by epoberezkin** [comment]
Hi @ro70. This is a general question on usage of JSON Schema - the specification that Ajv implements. Please submit the question to StackOverflow.

**Comment by ro70** [comment]
@epoberezkin Please excuse me. I partly solved my problem. Now I have the following code
```
var schema = {
  "id": "test.json#",
  "definitions": {
    "body": {
      "type": "object",
      "properties": {
        "name": {"type": "string"},
      }
    },
    "extendedBody": {
      "$merge": {
        "source": {"$ref": "#/definitions/body"},
        "with": {
          "properties": {
            "age": {"type": "integer"}
          }
        }
      }
    }
  },
  "request": {
    "properties": {
      "user": {"$ref": "#/definitions/extendedBody"}  // #/definitions/body works as expected.
    }
  }
}

var Ajv = require('ajv')
var ajv = Ajv({
  v5: true,
  removeAdditional: 'all',
  schemas: [schema]
})

var data = {
  user: {
    "name": "tom",
    "age": 1,
    "shouldBeRemovedByAJV": true
  }
}

var valid = ajv.validate({$ref: "test.json#/request"}, data)
console.log(data)
```
which gives
```
{ user: { name: 'tom', age: 1, shouldBeRemovedByAJV: true } }
```
Is removeAdditional not working with $merge?

**Comment by epoberezkin** [comment]
Your schema is equivalent to an empty schema - `{}`. There are no validation keywords on the top level. Additional properties will be removed if one of properties, patternProperties or additionalProperties keywords is present). None of them is present in the schema (only in definitions that are never used).

**Comment by epoberezkin** [comment]
Actually you are using not the root schema... not sure, please make a working example in runkit.com using the latest version (v5 option is no longer used, for example), I will have a look.

**Comment by ro70** [comment]
@epoberezkin I appreciate your help. I'd like to validate (remove additional properties) the user object (in data1/data2) against the request1/request2 schema. data1 with request1 works as expected. data2 with request2 does not.

[Example](https://runkit.com/ro70/596730dc5c80b5001232d0a8)

**Comment by ro70** [comment]
According to [this](https://github.com/epoberezkin/ajv#merge-and-patch-keywords) the schemas extendedBody and extendedBody2 should be equivalent, shouldn't they?

[Example](https://runkit.com/ro70/5967cce6734e0d0012b36126)

**Comment by epoberezkin** [comment]
You have not added $merge keyword to ajv instance - see [this](https://github.com/epoberezkin/ajv#merge-and-patch-keywords), by default $merge is simply ignored.

**Comment by epoberezkin** [comment]
https://runkit.com/esp/5967e408fdb38a0014cb0f33
https://runkit.com/esp/5967e4f3f3722d0012df4e82

**Comment by ro70** [comment]
@epoberezkin As we say here: In 99.9% of all cases it's not the computer... Thank you very much for spending your time to help me.
