### ISSUE TITLE
oneOf for alternate sets of properties not working

### ISSUE THREAD

**Issue by coderextreme** [ajv-validator/ajv#538]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.1.5 not sure what latest version does.

**Ajv options object**

```javascript


```

**JSON Schema Snippet**

    "ProtoInstance": {
      "type": "object",
      "additionalProperties": false,
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "@USE": {
              "type": "string"
            }
          },
          "required": [
            "@USE"
          ],
          "additionalProperties": false
        },
        {
			"type": "object",
			"properties": {
				"@DEF": {
					"type": "string"
				},
				"@name": {
					"type": "string"
				},
				"fieldValue": {
					"$ref": "#/definitions/fieldValue"
				},
				"IS": {
					"$ref": "#/definitions/IS"
				},
				"-children": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"#comment": {
								"type": "string"
							}
						},
						"additionalProperties": false
					}
				},
				"-metadata": {
					"$ref": "#/definitions/-metadata"
				}
			},
			"required": [
				"@name"
			],
			"additionalProperties": false
		}
	]
    },

```json


```

**Sample data**

```json


               { "ProtoInstance":
                  {
                    "@name":"f",
                    "@DEF":"kl"
                  }
                }

```

```javascript


```

**Validation result, data AFTER validation, error messages**

```
keyword: additionalProperties
 dataPath: X3D > Scene > -children > 25 > Group > -children > 5 > ProtoInstance
 value: {"@name":"f","@DEF":"kl"}
 message: should not have additional properties
 params: {"additionalProperty":"@name"}
 file: ../Examples/VRMLBanner/vrmlbanner.json
 version: 3.3


 keyword: additionalProperties
 dataPath: X3D > Scene > -children > 25 > Group > -children > 5 > ProtoInstance
 value: {"@name":"f","@DEF":"kl"}
 message: should not have additional properties
 params: {"additionalProperty":"@DEF"}
 file: ../Examples/VRMLBanner/vrmlbanner.json
 version: 3.3


```

**What results did you expect?**

valid.  ajv doesn't seem to be picking up the second array element in the oneOf array,   I am not sure if the schema is valid draft-04 or not.  If more recent metaschema passes or supports oneOf better, let me know.

**Are you going to resolve the issue?**

Not yet.  Waiting to find out if the schema is valid.  should type be oneOf?

**Comment by epoberezkin** [comment]
The problem is in "additionalProperties" keyword on the top level. Without "properties" and "patternProperties" keyword any object is invalid, as any property is additional. That is according to the JSON Schema specification.

**Comment by epoberezkin** [comment]
Also see https://github.com/epoberezkin/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc

**Comment by coderextreme** [comment]
Trying to achieve same effect with something else--any hints?   I believe I was given an example by someone developing with Altova. Why doesn't metaschema validation fail? Because you can't require one of "properties" or "patternProperties" (recursive problem)?

John

**Comment by epoberezkin** [comment]
> Trying to achieve same effect with something else--any hints?

Which effect? You should be able to express your validation logic with JSON Schema, just differently.

> Why doesn't meta-schema validation fail?

Because the schema is valid, it just fails validation if data is any non-empty object.
You can create a meta-schema that would require one of these two properties, but it is not required by the specification.

**Comment by coderextreme** [comment]
Okay, here's my next try (should I take out the first type property??):
```
                "ProtoInstance" : {
                        "type": "object",
                        "oneOf": [
                                {
                                        "type": "object",
                                        "properties": {
                                                "@USE": {
                                                        "type": "string"
                                                }
                                        },
                                        "required": [
                                                "@USE"
                                        ],
                                        "additionalProperties": false
                                },
                                {
                                        "type" : "object",
                                        "properties" : {
                                                "#comment": {
                                                    "type": "string"
                                                },
                                                "IS": {
                                                    "$ref": "#/definitions/IS"
                                                },
                                                "fieldValue" : {
                                                        "$ref":"#/definitions/fieldValue"
                                                },
                                                "-metadata" : {
                                                        "$ref":"#/definitions/-metadata"
                                                },
                                                "@name" : {
                                                        "type":"string"
                                                },
                                                "@DEF" : {
                                                        "type":"string"
                                                },
                                                "@class" : {
                                                        "type":"string"
                                                }
                                        },
                                        "required": [
                                                "@name"
                                        ],
                                        "additionalProperties": false
                                }
                        ]
                },
```
-----------------------------------------------------------------------------------------------------
```
    { "ProtoInstance":
            {
              "@name":"Camera",
              "@DEF":"Camera.AimPointTest",
              "fieldValue": [
                {
                  "@name":"description",
                  "@value":"AimPointTest for moving camera tracking moving target"
                },
                {
                  "@name":"position",
                  "@value":[4,4,10]
                },
                {
             
```
----------------------------------------------------------------------------------------------------
```
 keyword: additionalProperties
 dataPath: X3D > Scene > -children > 20 > ProtoInstance
 value: {"@name":"Camera","@DEF":"Camera.AimPointTest","fieldValue":"|omitted|"}
 message: should not have additional properties
 params: {"additionalProperty":"@name"}
 file: ../data/CameraExamples.json
 version: 3.3


 keyword: additionalProperties
 dataPath: X3D > Scene > -children > 20 > ProtoInstance
 value: {"@name":"Camera","@DEF":"Camera.AimPointTest","fieldValue":"|omitted|"}
 message: should not have additional properties
 params: {"additionalProperty":"@DEF"}
 file: ../data/CameraExamples.json
 version: 3.3


 keyword: additionalProperties
 dataPath: X3D > Scene > -children > 20 > ProtoInstance
 value: {"@name":"Camera","@DEF":"Camera.AimPointTest","fieldValue":"|omitted|"}
 message: should not have additional properties
 params: {"additionalProperty":"fieldValue"}
 file: ../data/CameraExamples.json
 version: 3.3


 keyword: required
 dataPath: X3D > Scene > -children > 20 > ProtoInstance
 value: {"@name":"Camera","@DEF":"Camera.AimPointTest","fieldValue":"|omitted|"}
 message: should have required property @USE
 params: {"missingProperty":"@USE"}
 file: ../data/CameraExamples.json
 version: 3.3
```
--------------------------------------------------------------------------------------------------------

**Comment by coderextreme** [comment]
I either want to accept @USE or the other properties, but not both. @USE is like IDREF, and creates a reference to the corresponding @DEF propertied object, so I don't need additional properties alongside @USE.

**Comment by coderextreme** [comment]
sorry, above @'s should have capitalized word fragment after them
