### ISSUE TITLE
Validation Fails for Type String when specifying Items with ref to object

### ISSUE THREAD

**Issue by ahlusar1989** [ajv-validator/ajv#539]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
5.2.0

**Ajv options object**

```javascript
{ allErrors: true, v5: true, removeAdditional: true }

```

**JSON Schema**

```json
{
	"createBlock": {
		"additionalProperties": false,
		"type": "object",
		"properties": {
			"name":	{
				 "type": "string"
			},
			"blocks": {
				"type": "array",
				"items": {
					 "$ref": "#/definitions/blockObj"
				}
			}
		},
		"required": ["name", "blocks"]
	},
	"blockObj":{
		"type": "object",
		"properties": {
			"quantity": {
				"type": "integer"
			},
			"rate": {
				"type": "integer"
			},
			"id": {
				"type": "string",
				"not": "integer"
			}
		},
		"required": [ "quantity", "rate", "id"]
	}
}

```

**Sample data**

```json

 { "data": {
			"name": "Some random name",
			"blocks": [
				{"cj5458hyl0001zss42td3waww": {
					"quantity": "",
					"rate": 356.77,
					"id": "ewdwe4434"
				}},
				{"cj5458hyl0001zss42td3wawu": {
					"quantity": 4,
					"rate": 356.77,
					"id": "3434ewdwe4434"
				}}]
		}
 }

```
**Your code**
https://gist.github.com/ahlusar1989/0a077c5dc769ee15854b8bb97074d04b

```javascript


```

**Validation result, data AFTER validation, error messages**

```
Valid is true

```

**What results did you expect?**

It should be false as the type indicated is string

**Are you going to resolve the issue?**
Not sure where to start 😄 . If need be I'll be happy to open a PR for the patch.

**Comment by epoberezkin** [comment]
several problems here:
- option v5 is no longer used
- not: 'integer' is not a valid schema, the only reason it doesn't fail is that that schema is never used
- I don't see you using the second schema (blockObj) at all - it has to be explicitly added to the instance with addSchema method.
- #/definitions/blockObj - I don't see definitions anywhere here

If it doesn't help, can you please make a self-contained code sample in runkit.com?

**Comment by epoberezkin** [comment]
Also I assume that data is not `{data:{...}}` but `{...}`, at least from looking at the code

**Comment by ahlusar1989** [comment]
@epoberezkin That is a request body used in Insomnia. I will work on a runkit example. thanks!

**Comment by epoberezkin** [comment]
Just looking at the code/sample - I see only two possibilities - either schema should not compile at all, because the reference can't resolve, or if you pass the whole object as schema it is equivalent to an empty schema.

**Comment by ahlusar1989** [comment]
@epoberezkin It is successfully compiled. It successfully throws errors if `name` or the `blocks` property is missing. However, the nested types are not validated.  I apologize as I did not include this as an additional note.

**Comment by ahlusar1989** [comment]
I should also add that I also thought of doing this: https://stackoverflow.com/questions/44133426/ajv-schema-validation-for-array-of-objects

**Comment by ahlusar1989** [comment]
@epoberezkin I finally understand what I need to do. You explain this is effectively here: https://github.com/epoberezkin/ajv/issues/160

I understand now what I should be doing. Thank you again for your time.
