### ISSUE TITLE
Schema "pattern" keyword does not work properly

### ISSUE THREAD

**Issue by urlin** [ajv-validator/ajv#54]
Hello, I'm using Node.js v4.1.1 and Ajv v1.4.2

**Test case**

``` javascript
var Ajv = require("ajv"),
    schema =  {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "pattern": "/^\w+$/"
            }   
        }
    };

var ajv = Ajv();
var validate = ajv.compile(schema);
validate({name: "John"}); // returns false
```

**console.log(validate.errors)**

> [ { keyword: 'pattern',
>     dataPath: '.name',
>     message: 'should match pattern "/^w+$/"' } ]

**Comment by blakeembrey** [comment]
@urlin The pattern is the regular expression content, without the slashes (that's JavaScript you are thinking of. Try it with `"^\\w+$"`.

**Comment by urlin** [comment]
The same problem:

``` javascript
[ { keyword: 'pattern',
    dataPath: '.name',
    message: 'should match pattern "^w+$"' } ]
```

**Comment by blakeembrey** [comment]
@urlin You need a backslash before the `w`, so two `\\` in your JSON. Otherwise you're only trying to match `w+` which will only work with `www`, etc.

Edit: Updated the example above.

**Comment by urlin** [comment]
I see, thank you

**Comment by blakeembrey** [comment]
No worries. Glad it's working now :smile:

**Comment by epoberezkin** [comment]
Thank you @blakeembrey !
