### ISSUE TITLE
Add instanceof property for type objects

### ISSUE THREAD

**Issue by joliejuke-orga** [ajv-validator/ajv#543]
What about add a property `instanceof` that could validate if an object is an instance of the right class.

e.g. 
```

const MyClass = require('./MyClass.js');
const Ajv = require('ajv');
let ajv = new Ajv();

let schema = {
  "type": "object",
  "instanceof": MyClass
}

let model = new Myclass();
ajv.validate(schema, model); // valid
ajv.validate(schema, {}); // invalid
```

Then when an "instanceof" prop is defined it could simply check:
`model instanceof schema.instanceof`

I know that ajv#keyword can do the trick, but it's really not developper friendly.
Your Ajv instance has to know about all your models.
best.

**Comment by epoberezkin** [comment]
> What about add a property instanceof that could validate if an object is an instance of the right class.

Ajv implements JSON Schema specification, instanceof is not a part of it, so it should not be in this package.

Also, it would be a very fundamental change to Ajv to allow non-serialisable schemes. Currently, you cannot have a function/class in the schema.

> I know that ajv#keyword can do the trick, but it's really not developper friendly.

Assuming you mean ajv-keywords package that implements instanceof keyword, what is not friendly about it? If it's the fact that you have to register the class and use its name rather than actual class constructor, it follows from the limitation that the schema must be serialisable. Or is it something else?

**Comment by joliejuke-orga** [comment]
Yes I understand that JSON Schema is language agnostic and should only know about JSON.

Yes I admit that you need to use the class name to do that.
But I would like to know if it's possible to accept a class argument during the instanciation of ajv instead of directly mutate the module (ajv-keyword) data?

```
const MyClass = require('./MyClass.js');
const Ajv = require('ajv');
const AjvKeyword = require('ajv-keywords');

let ajv = new Ajv();
let ajvKeyword = new AjvKeyword(ajv, {
  classConstructor: [{
    'myClass': MyClass
  }]
});

ajv.validate({instanceof: 'myClass', new MyClass());
```

Then only an ajvKeyword instance has the class constructor name. Therefore we can pass dynamic class constructor to an instance of AJV, and we don't need to initialize all the class constructor.

Thx for your fast answer btw :)

**Comment by epoberezkin** [comment]
It can be done in ajv-keywords, so closing it here.

The api to pass keyword-specific options would be

```javascript
const MyClass = require('./MyClass.js');
const Ajv = require('ajv');
const ajvKeywords = require('ajv-keywords');

let ajv = new Ajv;
ajvKeywords(ajv, { // array of keywords is supported, a map of options can be supported too
  typeof: true, // no options
  instanceof: {
    classes: {
      'MyClass': MyClass
    }
  }
});

ajv.validate({instanceof: 'MyClass'}, new MyClass);
```

It should be done for all keywords that support parameters, not just instanceof.
