### ISSUE TITLE
error in npm install

### ISSUE THREAD

**Issue by gerardob** [ajv-validator/ajv#545]
I try to install dependencies, with npm install I have a project with ionic, but I get this error:

Unexpected end of input at 1:19108
npm ERR! 85ee90a76dbf346","tarball":"https://registry.npmjs.org/ajv/-/ajv-0.4.

I try to install various versions with npm install ajv@5.0.0 ajv@0.4.0 for example and I get the same error and try with npm doctor npm cache verify and is not working always I get the same error

**Comment by epoberezkin** [comment]
Are you using ajv as dependency of your project? or do you git clone ajv and then npm install?
Are you loading from npm directly or is it npm in your network?
Also possibly some compatibility issue - Please re-submit it using compatibility template: https://github.com/epoberezkin/ajv/blob/master/CONTRIBUTING.md#browser-and-compatibility-issues

**Comment by epoberezkin** [comment]
https://github.com/npm/npm/issues/18036

**Comment by gerardob** [comment]
done!! I make **npm cache clean --force** and solved!! thanks a lot!
