### ISSUE TITLE
Async compile stuck in loop

### ISSUE THREAD

**Issue by henriklundgren** [ajv-validator/ajv#546]
I am using the latest version of Ajv.

What am I doing wrong?
I want to use the GeoJSON schema but `loadSchema`goes into a endless loop.

**Ajv options object**

```javascript
{
  loadSchema(uri) {
     // fetch(uri)
     return Promise.resolve(/* http://json-schema.org/draft-04/schema */)
  }
}
```

**Your code**

```javascript
const ajv = new Ajv({...})
ajv.compileAsync(/* https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/geojson.json */)
```

**Comment by henriklundgren** [comment]
Sorry for the noise, I found why https://github.com/epoberezkin/ajv/releases/tag/5.0.0

**Comment by krenor** [comment]
Could you please share how you managed to get it working?

**Comment by henriklundgren** [comment]
@krenor By adding the version 4 meta schema. See the first paragraph on the README.
