### ISSUE TITLE
params component of errors when ajv-errors is used

### ISSUE THREAD

**Issue by GeoffThorpeFT** [ajv-validator/ajv#550]
I am using v5.2.2 of ajv with v1.0.0 of ajv-errors and i'm seeing a variation in the format of the params object that is returned within errors. The variation occurs when the schema actions the errorMessages keyword.

Is this expected behaviour?

When no errorMessage is defined for the error that occurs then the expected documented format of errors is returned with params set to the validation rule from the schema.

e.g: schema
```
"moreInformation": {
    "type": "string",
    "pattern": "Geoff",
    "maxLength": 1000000,
    "errorMessage": {
        "maxLength": "please keep more information less than 1000000 characters"
    }
},
```
error result (when moreInformation is not set to "Geoff"):
```
 { keyword: 'pattern',
    dataPath: '/moreInformation',
    schemaPath: '#/properties/moreInformation/pattern',
    params: { pattern: 'Geoff' },
    message: 'should match pattern "Geoff"' } 
```

However, when the errorMessage becomes applicable the format of params changes to be an array that contains an error.params object.

e.g: (same) schema
```
"moreInformation": {
    "type": "string",
    "pattern": "Geoff",
    "maxLength": 1000000,
    "errorMessage": {
        "maxLength": "please keep more information less than 1000000 characters"
    }
},
```
result (when moreInformation is too long):
```
  { keyword: 'errorMessage',
    dataPath: '/moreInformation',
    schemaPath: '#/properties/moreInformation/errorMessage',
    params: { errors: [Object] },
    message: 'please keep more information less than 1000000 characters' } ]
```
(notice now params is now an error object array)
The errors array in params only has one entry (which is the original format of the error response):
```
{ keyword: 'maxLength',
  dataPath: '/moreInformation',
  schemaPath: '#/properties/moreInformation/maxLength',
  params: { limit: 1000000 },
  message: 'should NOT be longer than 1000000 characters' }
```

Should we expect this variation in the error response format or it is a side effect of the use of ajv-errors when we have not defined a message for every error?
Thanks
Geoff

**Comment by epoberezkin** [comment]
In general case, errorMessage keyword converts multiple errors into a single error with a defined message, so in parameters in contains the array of original errors that were replaced.

**Comment by GeoffThorpeFT** [comment]
So, would your advice be to check the type of the params field before using its contents.

Some context - we are using ajv to validate for required and pattern fields and wish to return json output that is an array of errors each of which identifies the field and the error.  I was aiming to use params to obtain the name of the field being validated.

**Comment by epoberezkin** [comment]
yes, params can be different depending on keyword, it's all documented [here](https://github.com/epoberezkin/ajv#error-parameters) and in case of errorMesage it's always the array of original errors.

You can replace errors per property rather than per keyword: https://github.com/epoberezkin/ajv-errors#messages-for-properties-and-items
