### ISSUE TITLE
Ability to add custom field types

### ISSUE THREAD

**Issue by pierissimo** [ajv-validator/ajv#554]
**What problem do you want to solve?**
Sometime the supported JSON types are not enough, or they doesn't fully describe the type of the field.
For example, I would like to define a objectId type (mongodb), with associated custom coercion and validation rules.
Any thoughts?

**Comment by epoberezkin** [comment]
You can define custom formats and custom keywords, that should allow to express any validation requirements. Not sure which coercions you need, but custom keywords allow to modify validated data.
