### ISSUE TITLE
Proposal: dynamic default assignment

### ISSUE THREAD

**Issue by EricMCornelius** [ajv-validator/ajv#555]
**What version of Ajv you are you using?**
5.2.2

**What problem do you want to solve?**
Easily enable default field assignments via externally supplied functions.

Currently, as near as I can figure anyway, it is not possible to dynamically allocate required schema properties.  Custom keywords appear to be invoked after the core JSON schema assertions are already made.  Take this intended behavior for instance:

```
{
  "type": "object",
  "properties": {
    "uuid_field": {
      "type": "string",
      "format": "uuid"
    }
  },
  "required": ["uuid_field"]
}
```

Now suppose we want to auto-generate a uuid if one isn't supplied.

If we try to achieve this behavior by using a custom keyword, it needs to be specified on the "object", but any "modifying" keywords won't be executed until after the required property list is executed.  E.g.:

```
const data = {};

const schema = {
  "type": "object",
  "properties": {
    "uuid_field": {
      "type": "string",
      "format": "uuid"
    }
  },
  "required": ["uuid_field"],
  "generate": {"uuid_field": "uuid_gen"}
}

const generators = {
  uuid_gen: () => uuid.v4()
}

ajv_instance.addKeyword('generate', {
  modifying: true,
  errors: true,
  compile(schema, parent) {
    for (const [field, gen] of Object.entries(schema)) {
      if (!generators[gen]) throw new Error(`Unsupported generator: ${gen}`);
    }

    return (data, path, parent, key) => {
      for (const [field, gen] of Object.entries(schema)) {
        data[key] = generators[gen]();
      }
      return true;
    }
  }
});
```

When validating the above, we get a "should have required property 'uuid'" error, because the generated code is verifying the required properties before the generate keyword has an opportunity to act on the object.

**What do you think is the correct solution to problem?**
I think allowing users to configure dynamic defaulter functions could be useful.  In this situation, the problem collapses to:

```
{
  "type": "object",
  "properties": {
    "uuid_field": {
      "type": "string",
      "format": "uuid",
      "default": "uuid_gen"
    }
  },
  "required": ["uuid_field"]
}

// ajv requires a new option and utilizes the existing "shared" defaults to invoke user-supplied default generator functions

const ajv = new ajv({useDefaults: 'shared', defaulters: {uuid_gen: () => uuid.v4()}});
```

**Will you be able to implement it?**
I have a functional PR ready to submit whenever and working against the unit tests.  Essentially, it just takes in these defaulter arguments, and generates function invocations here: https://github.com/epoberezkin/ajv/blob/master/lib/compile/index.js#L239 whenever the default value passed into this function is a registered defaulter name.

What it really seems might be useful to me is providing some control over the order of execution of addKeyword behavior (if this doesn't already exist and I'm not just missing it) so that "modifying" keywords can execute before standard "type" / "format" / "required" assertions are executed.  This would make format coercions viable as well without needing to a) put coercions on an object parent or b) replace the build-in "format" keyword.

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv-keywords#dynamicdefaults

I'm not sure I understand the problem with applying assertions after the defaults are inserted. If the data is not there then these assertions will not be applied, so the validation will pass. The only exception is `required`, but I would say if there can be dynamic default value, then there is no reason to include this field in required - strictly speaking it is not required.

**Comment by EricMCornelius** [comment]
It is true that the value is not required when useDefaults is enabled, so I understand that view.

As I think is common for practical usage though, my aim is to avoid creating minorly different versions of the same schema for handling inbound sanitization vs backend strict validation.

It probably boils down to the same pain points that lead to your $merge and $patch implementations.

Ideally, I want keywords related to sanitization and mutation/coercion to be enabled via flags when validating requests or preparing responses, and to use the same schema document to make strict assertions in the backend.

This feels achievable if we can control the execution order of the JSON schema core keywords vs. custom keywords, though I am very probably missing some roadblocks there.

Another example is the format keyword - defining custom format coercion during request validation and strict enforcement during backend invariant checks is very useful for things like flexible date-time parsing and sanitization.  Right now I'm achieving that by replacing the built-in format keyword entirely:

```
const formats =  {
  'date-time': data => {
    const d = new Date(data);
    if (isNaN(d)) {
      throw new Error(`Invalid date-time: ${data}`);
    }
    return d.toISOString();
  }
};

ajv_instance.removeKeyword('format');

ajv_instance.addKeyword('format', {
  modifying: true,
  errors: true,
  compile(schema, parent) {
    const format = formats[schema];
    if (!format) {
      console.log(`Unsupported format: ${schema}`);
      return () => true;
    }

    const validator = (data, path, parent, prop) => {
      try {
        parent[prop] = format(data);
        return true;
      }
      catch(err) {
        validator.errors = [{params: {keyword: 'format', format: schema, path, data}, message: err.message}];
        return false;
      }
    }
    return validator;
  }
});
```

However, I can't do things like coerce an inbound integer ipv4 address representation to it's quad dotted format without some weirdness.  E.g.:

```
const schema = {
  "type": "object",
  "properties": {
    "addr": {
      "type": "string",
      "format": "ipv4"
    }
  }
};

const data = {
  addr: 3232235777
}; // "192.168.1.1" in decimal format
```
The only way I've been able to see to make this validation-time coercion work is for ajv to do type coercion from int => string, then have a custom keyword (or format replacement as above) do the coercion back into an integer and then figure out the proper dotted quad format.

I'm not sure normalizing to the integer representation is even possible without somehow messing with the core schema "type" keyword assertions as well

```
const schema = {
  "type": "object",
  "properties": {
    "addr": {
      "type": "integer"
      "format": "ipv4_int"
    }
  }
};

const data = {
  addr: "192.168.1.1"
};
```

It seems that this will always assert that the type of addr is an integer (or can be coerced to one) before any custom keyword can modify the data?

The initial case above was really just about addressing the dynamic default assignment for mutation while keeping the required assertions during strict validation, but it seems like there's maybe a more general approach possible if we can customize the assertion execution order a bit.

**Comment by epoberezkin** [comment]
Changing the execution order would introduce ambiguity. Type is only checked once for all keywords for which type applies (for performance reasons). So at least it is not trivial.

Generating multiple schemas from a single template can be addressed in other ways - programmatic, string templates, $ref (depending on the environment your referenced schema for the same id can be different). https://github.com/epoberezkin/ajv/issues/398 is also about it.

Regarding formats, you can define formats that apply to numbers - I think it should help.
