### ISSUE TITLE
compiled templates aren't included in the latest release

### ISSUE THREAD

**Issue by marbemac** [ajv-validator/ajv#56]
Are they supposed to be? Looks like they haven't been included since release like, 1.2 - how are people using it without manually compiling them (aka, installed from npm).

**Comment by blakeembrey** [comment]
``` sh
➜  ajv  cat package.json | grep version
  "version": "1.4.2",
➜  ajv  ls lib/dotjs    
README.md        format.js        maximum.js       multipleOf.js    ref.js
allOf.js         items.js         minItems.js      not.js           required.js
anyOf.js         maxItems.js      minLength.js     oneOf.js         uniqueItems.js
dependencies.js  maxLength.js     minProperties.js pattern.js       validate.js
enum.js          maxProperties.js minimum.js       properties.js
```

Are those the templates you mean?

**Comment by marbemac** [comment]
Yup! Those are the ones. I can get them by running npm install & npm run build in the node_modules/ajv folder, but that seems less than ideal. All of my team members will need to do that on every new machine.

I now see they're included in the .gitignore file so perhaps this is intentional?

**Comment by blakeembrey** [comment]
They are not included from git, but from `npm`. How are you installing `ajv`?

**Comment by marbemac** [comment]
Weird, just deleted the folder and re-installed and all is good. Closing, thanks!

**Comment by blakeembrey** [comment]
Great, good to hear it works now :smile: Wonder what was up before...

**Comment by marbemac** [comment]
I forked for this pull (https://github.com/epoberezkin/ajv/pull/55) and I guess pulling down from "marbemac/ajv" doesn't run the same compile step maybe? In any case, all good!

**Comment by blakeembrey** [comment]
Ah, no it does not :smile: Normally you would want to do an `npm link` which, IIRC, runs `npm prepublish` for you.
