### ISSUE TITLE
Is there a way to validate and make sure at least one field exists?

### ISSUE THREAD

**Issue by RatchapongT** [ajv-validator/ajv#560]
```
const validate = this.ajv.compile({
      properties: {
         id : {type: "string"}
        a: { type: "string"}
        b: { type: "string"}
      },
      required: [ "id " ],
      type: "object"
    });
```
This schema will ensure id exist. Can I further reinforce at least `a` or `b` exist?

Valid `{id : "1", a : "hi"} {id : "1", b : "hey"} {id : "1", a : "hi", b : "hey"}`
Invalid `{a : "hi"} {id: "1"} { } {b :"hey"}`

**Comment by epoberezkin** [comment]
You can use `required` inside `anyOf` or `oneOf`. Or to can use `propertyNames` together with `minProperties`. Please see available JSON schema keywords.
