### ISSUE TITLE
Access to the source rootData from the custom keyword validator

### ISSUE THREAD

**Issue by VladimirShestakov** [ajv-validator/ajv#567]
Can I get access to the source rootData (that not changed by rules) from the custom keyword validator?

```
addKeyword('myKey', {
      modifying: true,
      compile: (sch, parentSchema) => {
        return (data, dataPath, parentObject, propName, rootData) => {
             console.log(rootData); // <<--- rootData is already changed
             return true;
        };
      }
```

**Comment by epoberezkin** [comment]
Ajv does not clone the original data in any way, see https://github.com/epoberezkin/ajv/issues/549 for the reasons. The rootData is always passed by the reference.

If your custom keywords modifies the data then all the keywords that execute after will have access to the modified data.

You can work around by passing both the original and the clone as two properties of the same object and either re-define your schemas accordingly or just construct the modified schema in code.

Data:

```JavaScript
{
  data: {/* your data */},
  original: {/* the deep-clone of your data */}
}
```

Schema:

```JavaScript
{
  type: 'object',
  properties: {
    data: {/* your schema */}
    original: {}
  },
  additionalProperties: false
}
```

**Comment by VladimirShestakov** [comment]
Nice idea, but I applied a closure. Thanks!
