### ISSUE TITLE
TypeScript definition for FormatValidator is incorrect

### ISSUE THREAD

**Issue by mnpenner** [ajv-validator/ajv#570]
I'm pretty sure the TypeScript definition for [FormatValidator](https://github.com/epoberezkin/ajv/blob/9a13b2835f7ab5217c1cec3dd4f1de2a64ce8e7b/lib/ajv.d.ts#L152) is incorrect.

It should return allow a `Promise<boolean>` to be returned if `async` is `true`, no?

I'm getting errors when trying to copy from [this Twitter example](https://runkit.com/esp/ajv-asynchronous-validation).

**Comment by epoberezkin** [comment]
That is correct, type definition doesn't allow returning Thenable, it has to be updated.
