### ISSUE TITLE
Improve error reporting of oneOf

### ISSUE THREAD

**Issue by jhohlfeld** [ajv-validator/ajv#573]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv@5.2.2

**Ajv options object**

```javascript
{
  $data: true,
  allErrors: true,
  jsonPointers: true
}
```

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "properties": {
    "propA": {
      "type": "string"
    },
    "propB": {
      "type": "string",
      "not": {
        "const": {
          "$data": "1/propA"
        }
      }
    }
  }
}
```

**Sample data**

```json
{
  "propA": "foo",
  "propB": "foo"
}
```

**Your code**

```javascript
ajv.validate(schema, data);
```

**Validation result, data AFTER validation, error messages**

```
[ { keyword: 'not',
    dataPath: '.propB',
    schemaPath: '#/properties/propB/not',
    params: {},
    message: 'should NOT be valid' } ]
```

**What results did you expect?**

The error message tells me that `not` is rejected, but the really relevant information would be that `const` was not satisfied.

**Are you going to resolve the issue?**

I will be using a custom error message using the [ajv-errors keyword](https://github.com/epoberezkin/ajv-errors). However, it's not optimal since it increases my configuration overhead.

Would it be possible to increase the verbosity just for the `not:` keyword so the contained `count:` schema becomes visible?

**Comment by epoberezkin** [comment]
This is discussed here: https://stackoverflow.com/questions/46365911/json-schema-ajv-not-const-error-message-is-obscure

@jhohlfeld do you have a better idea how the error should be reported?

**Comment by epoberezkin** [comment]
> but the really relevant information would be that const was not satisfied.

`const` IS satisfied, that's why `not` fails.

**Comment by epoberezkin** [comment]
Add "passingSchemas" to params object in the error for "oneOf" keyword (array of passing schema indices, null if none pass)

**Comment by epoberezkin** [comment]
in [6.0.0-beta.0](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-beta.0)
