### ISSUE TITLE
Custom keyword priority: Can be changed? How it works?

### ISSUE THREAD

**Issue by marqu3z** [ajv-validator/ajv#578]
I noticed there's no information about keyword execution order.

I'm playing with custom keyword, in particular i needed an option to trim the strings.
I noticed other keywords like `minLength` take place before the data has been trimmed creating a not desired result.

There's a way to change the keyword priority, or being aware of its order?

```javascript
const Ajv = require('ajv')
let ajv = new Ajv()

ajv.addKeyword('trim', {  
  type: 'string',
  modifying: true,
  metaSchema: {type: 'boolean'},
  compile: function (schema) {
    return (schema === true) ? trimValue : () => true

    function trimValue (data, path, obj, key) {
      obj[key] = data.trim()
      return true
    }
  }
})

let schema = {
  type: 'object',
  properties: {
    name: {type: 'string', trim: true, minLength: 3}
  }
}

let validate = ajv.compile(schema)
let data = {name: '   hi   '}
validate(data) // true
data.name // 'hi'
```

**Comment by epoberezkin** [comment]
Keywords are executed in the order that is defined [here](https://github.com/epoberezkin/ajv/blob/master/lib/compile/rules.js#L7), grouped by type. Custom keywords are executed after all standard keywords, in the order they are added (for a given type).

I considered implementing the ability to manage the execution order of keywords, but decided against it as it would make the result non-deterministic in some cases.

When you need to define a specific execution order of your keywords you need to use "allOf". It also makes it more obvious when looking at the schema than it would have been if you managed the execution order via ajv instance:

```javascript
{
  type: 'object',
  properties: {
    name: {
      type: 'string',
      allOf: [
        {trim: true},
        {minLength: 3}
      ]
    }
  }
}
```
