### ISSUE TITLE
AJV & Redis

### ISSUE THREAD

**Issue by cemtopkaya** [ajv-validator/ajv#58]
We are working on Redis and I think it would be perfect if ajv can retrieve schemas from Redis async.

**Comment by epoberezkin** [comment]
There is `compileAsync` method that uses `loadSchema` function from options passed to the instance constructor for actual loading. Please implement any loading mechanism you want using this option.

```
var Ajv = require('ajv');
var ajv = Ajv({ loadSchema: loadFromRedis });

var KEY_PREFIX = 'schemas:';

function loadFromRedis(uri, cb) {
  redis.get(KEY_PREFIX + uri, cb);
}

ajv.compileAsync('http://mydomain.com/myschema.json', function(err, validate) {
  var valid = validate(data);
});


// some time later the schema is available in memory:

var valid = ajv.validate('http://mydomain.com/myschema.json', data);
```

**Comment by epoberezkin** [comment]
@cemtopkaya please reopen the issue if the above is not covering your use case. Please provide more information in this case.

**Comment by sadiqhabib** [comment]
Hi @cemtopkaya did you implement ajv with redis ?
