### ISSUE TITLE
Is there a way with AJV to check if a schema is valid?

### ISSUE THREAD

**Issue by joliejuke-orga** [ajv-validator/ajv#581]
I would like to check if a JSON Schema is valid.
I dynamicaly generate JSON schema and I don't want to validate a model over a schema but the JSON schema itself.

**Comment by smeijer** [comment]
I was looking for this some time ago myself. But it turned out; AJV is doing this automatically for you when calling `compile`:

> [**readme.md**](https://github.com/epoberezkin/ajv#compileobject-schema---functionobject-data)
> Unless the option validateSchema is false, the schema will be validated against meta-schema and if schema is invalid the error will be thrown. See options.

**Comment by epoberezkin** [comment]
You can also explicitly use validateSchema method - see the docs
