### ISSUE TITLE
A question of instance configuration

### ISSUE THREAD

**Issue by Reaverart** [ajv-validator/ajv#597]
Hi, thank you for this library! I'm curious can I override ajv instance options for different validate calls?
I.e. I wish to run `ajv.validate(schema, data1)` with instance `useDefaults: false` and 
`ajv.validate(schema, data2)` with instance `useDefaults: true` in different cases

Or I need to create new ajv instance for this purposes?

**Comment by epoberezkin** [comment]
Yes, you need to create a new instance in case you need different options - they are used during schema compilation and cannot be changed on the fly.

**Comment by epoberezkin** [comment]
See #322
