### ISSUE TITLE
migration to use schema with other formats

### ISSUE THREAD

**Issue by Opticsponge** [ajv-validator/ajv#599]
**What version of Ajv you are you using?**
newest

**What problem do you want to solve?**
I need to use JSON schema as the source to generate elasticsearch templates, and more complicated flatten a nested JSON schema and convert to SQL. There are more "conversions" I have needs for and would like to have the solution extendable.

**What do you think is the correct solution to problem?**
I would rather not build a solution from scratch. The solution would require a pre and post modules, for elasticsearch templates would only require removing extraneous fields and converting types. Flatten, and create SQL table script would require a pre-module to compile and remove extraneous fields and converting type, flatten, then transform to SQL format.

**Will you be able to implement it?**
Yes, but not quickly, and reproducing allot of what has already been done

**Comment by epoberezkin** [comment]
> I need to use JSON schema as the source to generate elasticsearch templates ... flatten a nested JSON schema and convert to SQL

It would be out of scope of this package. You can try though, using Ajv custom keywords, to create some schema that coverts a schema into ES template.

> I would rather not build a solution from scratch

You can use json-schema-traverse (that Ajv uses) to traverse the schema to convert it to any other document you need.

**Comment by Opticsponge** [comment]
thanx for feedback, will let you know how it turns out
