### ISSUE TITLE
ISODate format and type

### ISSUE THREAD

**Issue by goldytech** [ajv-validator/ajv#607]
Hi,
My schema is as below
```
var schema = {
  'type': 'object',
  'additionalProperties': false,
  'properties': {
    'firstName': {'type': 'string'},
    'age': {'type': 'integer'},
    'dateofBirth': {'type': 'Date', 'format': 'date'}
  },
  'required': [ 'firstName' ]
}
```

and the json data that I'm passing for this schema is 

`var data = { 'firstName': 1, 'bar': 'false', 'dateofBirth': '2014-01-22 14:56:59.301Z'}`

The schema is not getting validated, Can you please advise where I'm going wrong ?

**Comment by epoberezkin** [comment]
"type" cannot be "Date"

see https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#type

**Comment by snoopy83101** [comment]
why? why cannot?

**Comment by snoopy83101** [comment]
@epoberezkin   
I need time-type data in my JSON because I want to create a time index in mongodb instead of a string. What do I do?

**Comment by epoberezkin** [comment]
Time is represented as a string in JSON, you can use “format”
