### ISSUE TITLE
Drop Ajv v5 mode support

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#614]
- [x] patternGroups keyword
- [x] v5 meta-schema

**Comment by epoberezkin** [comment]
in [6.0.0-rc.0](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-rc.0)

**Comment by filipesilva** [comment]
Heya, I was looking at https://github.com/epoberezkin/ajv#merge-and-patch-keywords but according to https://github.com/epoberezkin/ajv-merge-patch, it needs `v5: true`.

Is merge and patch not supported in Ajv v6+?

**Comment by epoberezkin** [comment]
@filipesilva Only the docs in ajv-merge-patch need updating, v5 option is not used there since the previous major version of ajv - so it's supported.

**Comment by epoberezkin** [comment]
see https://github.com/epoberezkin/ajv-merge-patch/issues/7

**Comment by filipesilva** [comment]
Oh cool, thanks for the clarification!

**Comment by filipesilva** [comment]
BTW the readme for `ajv-merge-patch` still mentions `v5` is needed, I put up a PR for that https://github.com/epoberezkin/ajv-merge-patch/pull/22.
