### ISSUE TITLE
option async: false to ignore async formats and keywords

### ISSUE THREAD

**Issue by nick121212** [ajv-validator/ajv#615]
According to document, when the field “$async” is set “true”, remote validation will be done by default. If there are too many fields to be validated, the procedure is time consuming. Is there any way to avoid the remote validation process even when $async” is set “true”?

**Comment by epoberezkin** [comment]
You can create ajv instance without adding custom async keywords and formats - they will be ignored.

I'll think whether an option async: false is a good idea.

**Comment by nick121212** [comment]
Looking forward to the next version.

**Comment by epoberezkin** [comment]
The option name will be $async, to distinguish from the current async option that is removed in v6.
Values:
- undefined (default) - current behaviour but all schemas referenced from async schemas are compiled as async functions, unless they are inlined or it is known in advance that they are sync (that will fix #612)
- true - all schemas are compiled to async functions, regardless of $async keyword
- false - all schemas are compiled to sync functions and async formats and keywords are ignored
