### ISSUE TITLE
Configuration for console logging

### ISSUE THREAD

**Issue by meirotstein** [ajv-validator/ajv#618]
**What version of Ajv you are you using?**
5.1.3

**What problem do you want to solve?**
Ajv uses console.warn to report some warnings to the console.
I had several issues with some consumers of my package (which uses Ajv) that on there site they have a customized version of the console object and they don't interested with the Ajv warnings, in some cases the customized version did not implemented the `warn` function what leads to an Error.

This force these kind of sites to change the implementation of the console object in order to use packages that are depended in Ajv - which is not so easy when it comes to a large scale sites of big firms.
 
**What do you think is the correct solution to problem?**
I think that there should be a new option: `consoleLog`, default true, that when set to false there will be no reports to the console object whatsoever. 

**Will you be able to implement it?**
Yes

**Comment by epoberezkin** [comment]
@meirotstein that's good, thank you.

I suggest calling the option `logger` and support:
- `false` to suppress all logging (but not exceptions)
- a custom logger object with methods `log`, `warn`, `error`

By default Ajv would simply assign `console` to this option.
There should be tests for all cases for all existing calls to console.

I don't think there is any logging during validation apart from $comment keyword but it is off by default and it has its own option that enables it.

**Comment by meirotstein** [comment]
HI @epoberezkin 

I like your suggestion - sounds better than just a simple boolean option.

As for the current logging - you can find a call for console.warn() [here](https://github.com/epoberezkin/ajv/blob/c73ff4435e0457a336209773c5aecf924ef3d74c/lib/ajv.js#L169), [here](https://github.com/epoberezkin/ajv/blob/c73ff4435e0457a336209773c5aecf924ef3d74c/lib/ajv.js#L383) and [here](https://github.com/epoberezkin/ajv/blob/c73ff4435e0457a336209773c5aecf924ef3d74c/lib/ajv.js#L389)

**Comment by epoberezkin** [comment]
in 5.4.0
