### ISSUE TITLE
Not wating till db call

### ISSUE THREAD

**Issue by kmahalingpur** [ajv-validator/ajv#622]
I am trying get the values from db and validating with the current value but the custom validator is exiting befor db call returns???

**Comment by epoberezkin** [comment]
Validation is usually synchronous, it is not supposed to wait. You can define asynchronous schema with asynchronous custom keywords - see https://github.com/epoberezkin/ajv#asynchronous-validation

**Comment by kmahalingpur** [comment]
Thanks @epoberezkin  i figured it out. is it possible to get value of other field in schema for validating current field ?

**Comment by epoberezkin** [comment]
@kmahalingpur You can access the parent object, see the docs for custom keywords.

**Comment by kmahalingpur** [comment]
@epoberezkin if i try to print parent schema.. i am able to see the custom keyword data or same field data.
for example 
schema = {
    "$async": true,
    "properties": {
        "title": {
            "async": true,
            "type": "string",
            "dropdown_check": { "prop": "SAL" }
        },
        "fname": {
            "async": true,
            "type": "string",
            "conditional_check":{"title_data":"need to pass **title** data"}
        }
}
Is it possible ???
For parent schema in custome keyword i am able to print fname data only not title. Is that the correct way.
