### ISSUE TITLE
Make ajv chainable

### ISSUE THREAD

**Issue by pithu** [ajv-validator/ajv#625]
Thank you for providing this great and awesome library.

I would like to ask for the following improvement. 

What do you think about making some ajv method returning `this`, that would allow to write more compact code by chaining methods. For example the following code would be possible:

```javascript
const validator = new Ajv()
    .addSchema(someSchema)
    .addMetaSchema(someMetaSchema)
    .addFormat('customeType', customValidator)
    .getSchema('customUri')

if (!validator(someJsonObject)) { // fail }
```

As far as i can see candidates for chaining would be `addSchema`, `addMetaSchema`, `addFormat`, `addKeyword`.

**Comment by epoberezkin** [comment]
Looks good. And drop “add”? :)

**Comment by epoberezkin** [comment]
Also removeSchema and removeKeyword can be chained, although they aren’t used too often.
@pithu if you do the PR please update .d.ts file as well

**Comment by epoberezkin** [comment]
I am now thinking whether renaming all methods (maybe leaving old names as aliases) is a good idea:

addSchema -> schema
addMetaSchema -> metaSchema
addFormat -> format
addKeyword -> keyword
getSchema -> get
removeSchema -> remove

**Comment by pithu** [comment]
I am fine with the current naming prefix `add*` and `remove*`, because imo it's more explicit and better readable.

**Comment by epoberezkin** [comment]
in 5.5.0

**Comment by pithu** [comment]
cool, thx for merging

**Comment by isTravis** [comment]
Forgive me if I've misunderstood the implementation of this, but it seems that addSchema is not chainable if an array of schemas is submitted.

I made a quick pull-request: #640.

**Comment by pithu** [comment]
You are right, i forgot the `this` at that place
