### ISSUE TITLE
Feature Request: add option to set smart defaults

### ISSUE THREAD

**Issue by hansl** [ajv-validator/ajv#626]
Currently the values of `useDefaults` are as follow:

1. `false`, default. Simply doesn't set default values to validated objects.
2. `true`. Set a copy of default values on the data during validation.
3. `"shared"`. Set the default values on the data during validation, as a shared reference to the schema value (if object/array).

I'd like to add another enum here: `"smart"` (or similar). It would:
1. if no default value is set, force the default of every non-required field to be `undefined`,
1. create empty array/objects for fields that have them,
1. imply `useDefaults: true` which means that if a value is not defined in the object (and its default is missing from the schema), it will actually be set to `undefined`.

This solves a problem to us in Schematics; our EJS templates uses `with() {}` which requires values to exists (even if undefined), otherwise an exception is thrown. Having them set to `undefined` allows us to check their existence in the templates, and being able to list them with `Object.keys()` has some nice properties as well. Having arrays and objects also allow us to use values without checking if they exist first (ie. `if (a.b.c.length)` instead of `if (a && a.b && a.b.c && a.b.c.length)`).

I've already made a PR that passes all the tests (and added new tests): #627

I could also add a `smart-shared` option if you see value to it.

**Comment by epoberezkin** [comment]
Thank you for the idea. I will think about it.

As is, explicitly defining `{"default": null}` or `{"default": {}}` for these properties should solve this problem, so I need to think whether implying these defaults is a good idea.

Another approach is to pre-process the schema (e.g. with json-schema-traverse) and whenever default is missing add it based on the same criteria.

**Comment by hansl** [comment]
I though about those two solutions. One imply that the schema author is rigorous, which might not be the case. 

The other is my fallback idea.  I’d prefer undefined to null personally, as some values could actually be null. 

Additional idea: it could be useful for AJV to have some sort of addPreprocessor API.

**Comment by Opticsponge** [comment]
one thing to think about when setting "default": null is that swagger doesn't support this and open api 3.0 requires you use new type boolean "nullable"

**Comment by epoberezkin** [comment]
The issue of swagger / open api implementing some non-standard dialect of JSON Schema should be raised there.

**Comment by hansl** [comment]
Closing all issues created by me that are older than 2 years as cleanup.
