### ISSUE TITLE
How to validate url such as http://localhost:3000

### ISSUE THREAD

**Issue by nassiharel** [ajv-validator/ajv#636]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

5.5.0

**Ajv options object**

```javascript


```

**JSON Schema**

```json

const schema = {
     "properties": {
                "url": {
                    "type": "string",
                    "format": "url"
                }
            }
}

```

**Sample data**

```json

```

**Your code**

```javascript

const Validator = require('ajv');
const validator = new Validator();

validator.addFormat('url', "(http|ftp|https)://[\w-]+(\.[\w-]+)*([\w.,@?^=%&amp;:/~+#-]*[\w@?^=%&amp;/~+#-])?")

const obj = {
       url: "http://localhost:4001"
 }

 const valid = validator.validate(schema, obj);
    const result = { valid, instance: obj };
    if (!valid) {
        result.error = validator.errorsText(validator.errors);
    }
    return result;

```

**Validation result, data AFTER validation, error messages**

```
url should match format \"url\""

```

**What results did you expect?**

valid: true

**Are you going to resolve the issue?**

NO

**Comment by epoberezkin** [comment]
"uri" works, not sure if "url" should
https://runkit.com/esp/5a1bcba2b9cbb90011985dfb
@gajus?

**Comment by gajus** [comment]
Localhost URLs are intentionally excluded.

See note at https://mathiasbynens.be/demo/url-regex

> Assume that this regex will be used for a public URL shortener written in PHP, so URLs like http://localhost/, //foo.bar/, ://foo.bar/, data:text/plain;charset=utf-8,OHAI and tel:+1234567890 shouldn’t pass (even though they’re technically valid). Also, in this case I only want to allow the HTTP, HTTPS and FTP protocols.

**Comment by nassiharel** [comment]
So how can I use custom format instead?

**Comment by gajus** [comment]
You can use `pattern` to define your own regex pattern.

**Comment by epoberezkin** [comment]
Or you can re-define "url" format as you did in your code.
