### ISSUE TITLE
export type as constant

### ISSUE THREAD

**Issue by seeden** [ajv-validator/ajv#639]
it would be nice to have exported standard types as constants

```js
export const JSONSchemaType = {
  STRING: 'string',
  NUMBER: 'number',
  ...
};
```

I will know that I am using right "type" in the schema

**Comment by epoberezkin** [comment]
I don't think anything needs to be done for this:
1. The hash of valid types is available at `ajv.RULES.types`.
2. If you use an incorrect type the schema validation against meta-schema will fail (that is always done by default).
3. Composing schemas is out of scope for ajv.
You may want to use something like [ajv-schema-builder](https://github.com/RomAnoX/ajv-schema-builder).

**Comment by seeden** [comment]
Thanks
