### ISSUE TITLE
es6 / yield

### ISSUE THREAD

**Issue by AlbanMinassian** [ajv-validator/ajv#64]
How use ajv with yield ?
have you an example ?
Thanks Ami44

**Comment by epoberezkin** [comment]
ajv is synchronous. Or am I missing something? compileAsync can be used with yield with partial that returns thunk

**Comment by AlbanMinassian** [comment]
copileAsync ? not google found

**Comment by epoberezkin** [comment]
Sorry. compileAsync is ajv method, the only one that is asynchronous

**Comment by AlbanMinassian** [comment]
thanks
