### ISSUE TITLE
Report data changes when validating with removeAdditional, coerceTypes, useDefaults options

### ISSUE THREAD

**Issue by tony-kerz** [ajv-validator/ajv#643]
**What version of Ajv are you using?**

`v6.0.0-rc.1`

**Ajv options object**
```javascript
const ajv = new Ajv({removeAdditional: 'all'})
```

**Comment by epoberezkin** [comment]
You can compare the copy of data before validation with the data after validation.

**Comment by tony-kerz** [comment]
gotcha.

would you consider setting a boolean internally and making it available via something like `validator.removed` to avoid the overhead of cloning/comparing the data?

**Comment by epoberezkin** [comment]
Possibly, need to think about it.
If it is added, it should be more generic and be set in case data updated in any way (there are 3 options that cause data change).

**Comment by btjones** [comment]
+1 on this, would be nice to have an easy way to do this with the overhead of doing it outside of ajv.

**Comment by epoberezkin** [comment]
It may be done as part of annotation collection that is needed for 2019-09 anyway.

**Comment by epoberezkin** [comment]
replaced by #1313
