### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by chen6516** [ajv-validator/ajv#648]
Hi, guys, Can you tell me how to validate json-schema is valid by use this plugin, Endless thanks!

**Comment by epoberezkin** [comment]
Do you want to validate the schema against meta-schema?

**Comment by chen6516** [comment]
Yes, Do you have any good Suggestions?

**Comment by epoberezkin** [comment]
Schemas are validated by default when they are first used, you don’t need to do anything special for it. In some rare cases you may want to use method validateSchema. See readme.
