### ISSUE TITLE
remove-additional on schema with allOf fails

### ISSUE THREAD

**Issue by bmfair** [ajv-validator/ajv#649]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv-cli@2.1.0

**Ajv options object**

```
fails> ajv -s bug.schema.json -d bug.test.json --remove-additional=all 
works> ajv -s bug.schema.json -d bug.test.json
```

**JSON Schema**

```json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"id": "file:///bug.schema.json",
	"definitions": {
		"A": {
			"type": "object",
			"properties": {
				"a": {
					"type": "number"
				}
			},
			"required": [
				"a"
			]
		},
		"B": {
			"type": "object",
			"properties": {
				"b": {
					"type": "number"
				}
			},
			"required": [
				"b"
			]
		}
	},
	"type": "object",
	"allOf": [
		{
			"$ref": "#/definitions/A"
		},
		{
			"$ref": "#/definitions/B"
		}
	]
}


```

**Sample data**

```json

{ "a": 1, "b": 2 }
```

**Your code**

```
Command Line:
fails> ajv -s bug.schema.json -d bug.test.json --remove-additional=all 
works> ajv -s bug.schema.json -d bug.test.json

```

**Validation result, data AFTER validation, error messages**

```
bug.test.json invalid
[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/definitions/B/required',
    params: { missingProperty: 'b' },
    message: 'should have required property \'b\'' } ]

```

**What results did you expect?**
bug.test.json valid

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
While validating against schema "A" property "b" is removed so the validation against "B" fails.

See https://github.com/epoberezkin/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc

**Comment by bmfair** [comment]
Thanks for the quick reply and apologies for not finding the duplicate myself.  Really appreciate your work on ajv!
