### ISSUE TITLE
if/then/else applying wrong schema if target property is not present

### ISSUE THREAD

**Issue by fpenim** [ajv-validator/ajv#650]
Ajv version: **^6.0.0-rc.1**

**JSON Schema**
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "countryOfBirth": {
      "type": "string",
      "enum": [
        "England",
        "Italy"
      ]
    },
    "cityOfBirth": {
      "type": "string"
    }
  },
  "required": ["firstName"],
  "if": {"properties": {"countryOfBirth": {"pattern": "^England$"}}},
  "then": {"required": ["cityOfBirth"]}
}

```
**Sample data**

```json
{
  "firstName": "Emma"
}
```
**Your code**

```javascript
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true});

function runValidation(inputSchema, submittable) {
  var validate = ajv.compile(inputSchema);
  var valid = validate(submittable);
  if (valid) {
    return { result: 'Valid!'};
  } else {
    return { result: 'Invalid: ' + ajv.errorsText(validate.errors)};
  }
}
```

**Validation result, data AFTER validation, error messages**

```
'Invalid: data should have required property \'cityOfBirth\', data should match "then" schema'
```

**What results did you expect?**
I would expect this object to be valid against the given schema. 

The property `countryOfBirth` is not required, when it's present it's being evaluated correctly. Adding an `else` block has no impact on this behaviour. This happens even when multiple `if/then/else` blocks are in place, the schema applied in the one for the first `if`.

**Comment by epoberezkin** [comment]
@fpenim The result is correct.

You need to add `required: ['countryOfBirth']` to the subschema in “if” keyword for the schema to work as you expect. Without it, “if” passes validation when the property “countryOfBirth” is absent and the subschema in “then” requires that “cityOfBirth” is present.

**Comment by epoberezkin** [comment]
Also, you could use `const: 'England'` instead of `pattern`.

**Comment by fpenim** [comment]
Thanks 👍
