### ISSUE TITLE
Self reference: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gpietro** [ajv-validator/ajv#658]
While validating this [json schema](https://www.hl7.org/fhir/Patient.schema.json) I get Maximum call stack size exceeded error.
Is it self reference possibile with ajv?

**Comment by epoberezkin** [comment]
@gpietro Can you please simplify the schema so it's as small as possible while still having the issue? In general, recursive schemas for deep data structures are fully supported, but this schema would have the same issue as yours and it doesn't mean much:

```json
{"$ref": "#"}
```

**Comment by gpietro** [comment]
Of course, here is [simpler one](https://www.hl7.org/fhir/Element.schema.json) with the same issue. I agree with you but I wonder if I can make it work anyway, because I would like to use these schemas without the need of rewrite them again. Thanks for your help.

**Comment by gpietro** [comment]
I did simplify my schemas like [this](https://gist.github.com/gpietro/58df688211ccb9e1aa7393550aafcd39) and it works but I suppose that also validation of arrays with items $refs isn't supported :/

**Comment by epoberezkin** [comment]
What makes you think it’s not supported? FHIR schemas have a problem with IDs and refs, it’s been discussed in Gitter.

**Comment by gpietro** [comment]
Because I made a script to rewrite all FHIR schemas (probably I still miss something) and try to make them compatible with ajv.
In this [example](https://gist.github.com/gpietro/ba1ce5575c59f2e1c4febac528697572), Patient's **name** property is set as **required** and to be an array. The **array elements** should be of type **HumanName**, and HumanName has **given** property has required. AJV does validate only that name must be an array but not the type of the array's elements.

**Comment by epoberezkin** [comment]
> try to make them compatible with ajv.

I’d say with JSON schema spec.

I am going to close this issue as the problem you have now is different and I don’t think it’s in ajv. If you cannot resolve it please try to isolate the issue to a really small example (10-15 lines of schemas is usually enough) and submit another issue answering all questions in the issue template. Also please use as minimal JS code as possible.
