### ISSUE TITLE
Custom async keyword error return [usage help]

### ISSUE THREAD

**Issue by fpenim** [ajv-validator/ajv#664]
I have implemented a custom async keyword `isChildTermOf` that calls an API to check if a given ontology term is a child of another term. I'm having issues returning the errors when validation fails.
The CUSTOM.md does state:

> Asynchronous keywords can return promise that rejects with `new Ajv.ValidationError(errors)`, where errors is an array of custom validation errors (...)

Which I think I'm doing but the validation still passes though it should be failing, _can you help me with this_?

**What version of Ajv are you using?**
6.0.0-rc.1

**JSON Schema**
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Is child term of.",
  "$async": true,

  "type": "object",
  "properties": {
    "attributes": {
      "type": "object",
      "properties": {
        "sex": {
          "type": "array",
          "minItems": 1,
          "items": {
            "properties": {
              "value": {
                "type": "string",
                "minLength": 1
              },
              "units": {"type": "string"},
              "terms": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "url"
                },
                "isChildTermOf": {
                  "parentTerm": "http://purl.obolibrary.org/obo/PATO_0000047",
                  "ontology": "pato"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Sample data**
```json
{
  "$async": true,
  "attributes": {
    "sex": [{
      "value": "female",
      "terms":[
        "http://purl.obolibrary.org/obo/PATO_0000001"
      ]
    }]
  }
}
```

**isChildTermOf keyword implementation**
```javascript
'use strict';

var Ajv = require('ajv');
var request = require('request');

module.exports = function defFunc(ajv) {
  defFunc.definition = {
    async: true,
    type: 'array',
    validate: findChildTerms,
    errors: true
  };

  function findChildTerms(schema, data) {
    return new Promise( function(resolve, reject) {
      const parentTerm = schema.parentTerm;
      const ontology = schema.ontology;
      const olsSearchUrl = "https://www.ebi.ac.uk/ols/api/search?q=";

      if (findChildTerms.errors === null) {
        findChildTerms.errors = [];
      }

      let errorCount = 0;
      for (var i = 0; i < data.length; i++) {
        const termUri = encodeURIComponent(data[i]);
        const url = olsSearchUrl + termUri
        + "&exact=true&groupField=true&allChildrenOf=" + encodeURIComponent(parentTerm)
        + "&ontology=" + ontology + "&queryFields=iri";

        request(url, function(error, response, body) {
          let jsonBody = JSON.parse(body);
          if(jsonBody.response.numFound === 1) {
            resolve(true);
          } else if(jsonBody.response.numFound === 0) {
            findChildTerms.errors.push({
              keyword: 'isChildTermOf',
              message: 'is not child term of ' + parentTerm,
              params: {keyword: 'isChildTermOf'}
            });
            errorCount++;
            if (errorCount === termsArray.length) {
              reject(new Ajv.ValidationError(findChildTerms.errors));
            }
          } else {
            findChildTerms.errors.push({
              keyword: 'isChildTermOf',
              message: 'Something went wrong while validating term, try again.',
              params: {keyword: 'isChildTermOf'}
            });
            errorCount++;
            if (errorCount === termsArray.length) {
              reject(new Ajv.ValidationError(findChildTerms.errors));
            }
          }
        });
      }
    });
  }

  ajv.addKeyword('isChildTermOf', defFunc.definition);
  return ajv;
};
```

**What results did you expect?**
I expected it to fail

**Comment by epoberezkin** [comment]
It's definitely incorrect to have errors as property of the function in async case - you may have multiple calls interleaving and they would write to the same errors property. It should be a local variable.

To debug further, I suggest trying to simplify and to mock the actual api with some function call so it can all be executed without server. If you submit the working code sample to runkit.com, I will have a look. If you can be certain that the promise rejects but validation still passes, there may be an issue.

Btw, no need to have "$async": true in data.

**Comment by fpenim** [comment]
Thanks for the feedback, I'll debug further and submit to runkit.

**Comment by epoberezkin** [comment]
No problem. Apart from shared errors property I don't see other issues.

**Comment by fpenim** [comment]
I have submitted my code on https://runkit.com/fpenim/json-schema-validator/branches/master

I simplified it by removing the API call.
Every time the `isChildTermOf` is evaluated it always returns 
`reject(new Ajv.ValidationError(errors));`
It should always fail when the keyword is present in the schema, but it's not failing 🤔 
Any help is greatly appreciated!

**Comment by epoberezkin** [comment]
For async schema the compiled validation function returns a promise that has to be resolved. See working example here: https://runkit.com/esp/5a535de37742630014e25486

Also `parentTerm` is undefined where you use it.

**Comment by fpenim** [comment]
All working now, thanks!
