### ISSUE TITLE
errorDataPath: 'property' with additionalProperties: false results in faulty dataPath values with square brackets

### ISSUE THREAD

**Issue by lehni** [ajv-validator/ajv#671]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

The error happens on the latest versions: 6.0.0 & 6.0.1. 

**Ajv options object**

```js
{
  errorDataPath: 'property'
}
```

**JSON Schema**
```js
{
  type: 'object',
  required: ['a'],
  additionalProperties: false,
  properties: {
    a: { type: 'string' }
  }
}
```

**Sample data**

```js
{
  a: 'test',
  additional: 1
}
```
**Your code**

```javascript
const Ajv = require('ajv')

const schema = {
  type: 'object',
  required: ['a'],
  additionalProperties: false,
  properties: {
    a: { type: 'string' }
  }
}

const ajv = new Ajv({ errorDataPath: 'property' });

const data = {
  a: 'test',
  additional: 1
}

const validate = ajv.compile(schema)
const valid = validate(data)
if (!valid) {
  console.log(validate.errors[0])
}
```

**Validation result, data AFTER validation, error messages**

```js
{
  dataPath: '[\'additional\']',
  keyword: 'additionalProperties',
  message: 'should NOT have additional properties',
  params: { additionalProperty: 'additional' },
  schemaPath: '#/additionalProperties'
}
```

**What results did you expect?**

The dataPath should be `'.additional'` without the square brackets, as this is not an array index.

**Are you going to resolve the issue?**

I don't know enough about Ajv to be able to.

Here's a runkit test-case for easy reproduction:

https://runkit.com/lehni/ajv-additionalproperties

**Comment by epoberezkin** [comment]
That is the intended behaviour.

As [documented](https://github.com/epoberezkin/ajv#error-objects), by default ajv uses JavaScript property access notation. It includes dot-notation and square brackets notation; the latter is used in this case. Dot-notation is only used for properties that are both valid identifiers/reserved keywords and are defined in the schema. As this property is not defined in the schema it is reported as `"['additional']"` and not as `".additional"`, to avoid the cost of validation-time check of its validity for dot-notation.

If you need to parse property names in dataPath, it is better to use the option `jsonPointers: true`, because JS property access notation is difficult to parse, in general case.

**Comment by lehni** [comment]
@epoberezkin ok, I understand. But is it strange that the error is then still `should NOT have additional properties`, instead of something like `is an illegal additional property`? The path does go to the additional property after all, so the message isn't correct anymore.

In the case of required properties, the message is already similarly changed from `"should have required property 'propertyName'"` to `is a required property`

**Comment by epoberezkin** [comment]
That’s a different issue - there was a PR that made the error message for “required” dependent on errorDataPath option, the current message for additionalProperties is for normal error reporting - the error relates to the object, not to the property. I will accept a similar PR for this error message as well.

errorDataPath option was added for backward compatibility with the original incorrect but convenient error reporting. I am going to mark this option as deprecated.

**Comment by lehni** [comment]
Ok great. Could you point me to the other PR?

**Comment by lehni** [comment]
@epoberezkin I've created PR For it in #674, looking forward to your feedback.

**Comment by heath-freenome** [comment]
> errorDataPath option was added for backward compatibility with the original incorrect but convenient error reporting. I am going to mark this option as deprecated.

If I was using `errorDataPath: "property"` in ajv 6 what do I use now?

**Comment by epoberezkin** [comment]
You should be processing the errors in the loop and preparing them for the presentation. This option was adding a lot of complexity, and the errors that Ajv generates are not very user-friendly anyway - they were designed for developers, so you need some presentation layer for the errors. Some people use ajv-errors for that, I do think it's better to write code.
