### ISSUE TITLE
$ref for keys

### ISSUE THREAD

**Issue by taylorzane** [ajv-validator/ajv#676]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`6.0.1`

**Ajv options object**

```javascript
/* using defaults */
```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "$my-key-ref": {
      "type": "object"
    }
  }
}
```

**Sample data**

```json
{
  "hello": {
    "foo": true
  }
}
```

I wasn't sure where to bring this up, but I'm trying to find out if something like this is possible, either via JSON Schema spec, or possibly via ajv helpers.

I want to replace `$my-key-ref` with a value stored either in the current schema, or preferably in a different schema a la [definitions](https://github.com/epoberezkin/ajv#combining-schemas-with-ref). Is this something that I can do with existing tooling, or should I just preprocess/find-and-replace the schema prior to using it for validation?

**Comment by epoberezkin** [comment]
You can use `propertyNames` together with `additionalProperties` and `properties`.

**Comment by taylorzane** [comment]
Thanks, I must have skipped right over that when reading the documentation, I was able to accomplish what I wanted using that plus `patternProperties` 👍
