### ISSUE TITLE
Fields dependency [question]

### ISSUE THREAD

**Issue by ok2ju** [ajv-validator/ajv#683]
Hi, i have use case when value of one field should starts with value of another.
For example:
```json
{
  "field1": "/foo",
  "field2": "/foo/bar"
}
```
How can I achieve this behaviour? Or it's impossible? I guess that I should use `$data` keyword in something like `pattern` or `format`.
Many thanks.

**Comment by epoberezkin** [comment]
You can define a custom keyword. You cannot use one string as a regular expression for another, in general case, but the logic is trivial here, so defining a keyword "startsFrom" should be easy (and custom keywords have built in $data support - see the docs).
