### ISSUE TITLE
Option to skip "required" checks?

### ISSUE THREAD

**Issue by ilearnio** [ajv-validator/ajv#685]
In my code I only need to check for required fields before creating an entry in DB. But when updating existing entry I don't need to enforce all the fields to be present.

Is there any way to skip checks for "required" properties? Couldn't find it in the docs. This is so necessary.

Thanks!

**Comment by epoberezkin** [comment]
There is no way to disable any standard JSON schema keywords. It won't be provided as part of this library, I believe it's not a correct pattern. Instead, you could have multiple schemas (possibly, created programmatically, e.g., using templates), one for each validation scenario.

**Comment by epoberezkin** [comment]
What can be provided in the future though is #398 that would help with expressing the schema generation logic in a declarative way.

**Comment by HenrikGr** [comment]
I just thought about this as well and wonder if somebody could explain for me the difference of the required property and validation keywords.

The reason why I ask is that I'm trying to build a solution that generating an uiModel for input fields of different kind and started to use the required property in the schema to reflect the uiModel and the html inputs but I now think I need to check if a specific field has a validation keyword.

How do I check is a specific field has a validation keyword?

**Comment by marioestradarosa** [comment]
Under the hood for any method in the controller where the `@requestBody`  is present, the parser will invoke `validateRequestBody`  which makes use of `ajv` library to validate the schema (open Api from model spec) agains the `JSON`  object being passed over the body.  

It is not possible  with the current implementation to skip the validation of a string property in the model with a null value in the body and according to AJV it would be a bad practice thought. 

So, I have tested different scenarios and I would probably **go for the removal of properties from the client application that contains null values**, that way you won't send it over to the `API`  and your validations will not be affected. More over, as the property is `?` in your model, it won't hurt either.

Lastly, if we find this scenario so recurrent, we might opt to change the `parser.ts` to grab a property such as `validateSchema` from the `@requestBody` decorator and pass it over to the final `validateRequestBody` in the AJV.options object , that way we could potentially say to AJV , please don't validate this schema.

In your model, you might have: 
```ts
 @property({
    type: 'string',
    required: false,
  })
  theDate?: Date;
```

The `required:false` is only telling AJV schema validator not to raise any error if that property is missing. `theDate?` is just telling typescript that object property is optional (_two different things)_.

**Comment by voxelbustersold** [comment]
Any way to get around this? As required flags being not optional while checking makes it difficult to model POST and PATCH data properties.

**Comment by THABISANI** [comment]
I had a similar use case. You could brute forcefully, modify your schema's `required` attribute before running your update schema validation.

Another option is to just ignore the required property validation errors as in:

```
            for schema_error in schema_errors:
                if REQUIRED_PROPERTY_ERROR_MESSAGE in schema_error:
                    log.warn("Ignoring required property error", schema_error)
                else:
                    raise SchemaValidationError(schema_errors)
```

**Comment by nurhasyim354** [comment]
Another workaround:

```
const originalSchema = {
  $id: 'your_schema',
  type: 'object',
  properties: {
   ...
  },
  required: ['name', 'id']
}

function validate(data, skipRequired = false) {
  const _schema: any = JSON.parse(JSON.stringify(originalSchema));
  _schema.$id = Date.now().toString();
  if (skipRequired) {
      _schema.required = [];
  }
  const validate = this.ajv.compile(_schema);
  validate(data);

 ... handle validation result
}
```
