### ISSUE TITLE
Ignore $comment when used together with $ref

### ISSUE THREAD

**Issue by FloEdelmann** [ajv-validator/ajv#686]
When `$ref` is used, no other keyword shall be used alongside it. That is enforced with the *extendRefs* option set to `"ignore"` or `"fail"`.

However, `$comment`s should be ignored by implementations. They are useful to give other developers additional knowledge about a property without affecting the schema.

Is it possible to change the behavior of the *extendRefs* option so that it will still warn / fail if other keywords except `$comment` are present alongside `$ref` but allow `$comment`?

---

**Example:** Here, the `$ref`s are rather used as a special type to avoid code duplication and the comments adds additional information.

```json
  ...
  "nonEmptySingleLineString": {
    "$id": "nonEmptySingleLineString",
    "type": "string",
    "pattern": "^[^\n]+$"
  },
  ...
  "name": {
    "$comment": "unique in file",
    "$ref": "nonEmptySingleLineString"
  },
  "shortName": {
    "$comment": "unique globally; if not set: name is used",
    "$ref": "nonEmptySingleLineString"
  },
  ...
```

**Comment by epoberezkin** [comment]
The default behaviour for $ref is to ignore sibling properties. That, by the way, can change in the next version of the spec.

Do you want $comment to be ignored even if extendRef is set to "fail"?

**Comment by FloEdelmann** [comment]
The question is which of these rules has a higher priority: Should `$comment`s be always ignored? Or should `$ref`s always forbid sibling properties?

Maybe an additional config option could solve this dilemma, as the user could decide.

**Comment by teoxoy** [comment]
I would like to have this too. I think `$comment`s should be ignored.

**Comment by phormio** [comment]
I like to use `$comment` alongside `$ref` in JSON Schemas.  I also like to pass `extendRefs: "fail"` to Ajv.  Unfortunately, the two are incompatible.

To deal with this problem, #867 adds a new option, `allowRefComments`, but I have a suggestion that I think is cleaner: allowing `extendRefs` to have the value `failUnlessComment`, which would cause Ajv to allow `$comment` alongside `$ref` but disallow any other keyword.

**Comment by FloEdelmann** [comment]
The behavior in #867 changed after an initial review: `$comment` is now always ignored, even with `extendRefs: "fail"`, without any option.

**Comment by epoberezkin** [comment]
not an issue in v7
