### ISSUE TITLE
ES6 module export

### ISSUE THREAD

**Issue by aubergene** [ajv-validator/ajv#687]
I'm using [Rollup](https://rollupjs.org/) to build my project. It would be good if AJV had ES6 module exports so that it could make full use of Rollup.

I could have a go at implementing this if you like

**Comment by epoberezkin** [comment]
@aubergene It'll be just a wrapper, correct?

**Comment by epoberezkin** [comment]
It's been migrated to typescript, so should be an issue of changing the compilation target probably. Please check v7-alpha and comment if something is still needed - closing
