### ISSUE TITLE
AJV always throws error "should be an object"

### ISSUE THREAD

**Issue by BrettStrongEH** [ajv-validator/ajv#690]
Hi There,

Bit of a noob in the realm of JSON schemas, NodeJS and ajv so please excuse me if there is something glaringly obvious I have overlooked here.

I have posted the different aspects of what I am trying to achieve below.

I have tested the same JSON schema and data sample using this online tool:
https://jsonschema.net/#/
and it passes validation fine using that tool.

However whenever I try to pass it using ajv running from within node I always get the following validation error raised:
 [{
    "keyword": "type",
    "dataPath": "",
    "schemaPath": "#/type",
    "params": {
        "type": "object"
    },
    "message": "should be object"
}]

I am assuming ajv thinks that the root object of the data passed in is not a valid json object ... ?

The only thing I am doing that is not really covered in the docs is requiring my JSON schema file from a relative path like so:
const assessChangesDtoSchema = require('./schemas/changeEventDto'); 

any help would be greatly appreciated.

Thanks greatly :)

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v 6.1.0

**Ajv options object**
No ajv initializing options are used

**JSON Schema**

{
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
      "dateStamp": {
        "$id": "/properties/dateStamp",
        "type": "string",
        "title": "The Datestamp Schema",
        "description": "Date object in UTC string format.",
        "default": "",
        "examples": [
          "2018-01-29T08:26:12.911Z"
        ]
      },
      "isReversal": {
        "$id": "/properties/isReversal",
        "type": "boolean",
        "title": "The Isreversal Schema",
        "description": "A boolean value indicating whether this change event is a reversal. Reversals are only possible if the change being reversed was the last change saved",
        "default": false,
        "examples": [
          false
        ]
      },
      "editingSessionId": {
        "$id": "/properties/editingSessionId",
        "type": "string",
        "title": "The Editingsessionid Schema",
        "description": "The assessment editing session id.",
        "default": "",
        "examples": [
          "a3c65ff7-ee67-44be-846a-7dc4441d96ca"
        ]
      },
      "changeItems": {
        "$id": "/properties/changeItems",
        "type": "array",
        "items": {
          "$id": "/properties/changeItems/items",
          "type": "object",
          "properties": {
            "changeType": {
              "$id": "/properties/changeItems/items/properties/changeType",
              "type": "integer",
              "enum": [0, 1, 2, 3, 4],
              "title": "The Changetype Schema",
              "description": "ChangeType enum { ClassFrequency = 0,  ClassNessecity = 1,  Recatorisation = 2,  NAFlag = 3,  Note = 4 }.",
              "default": 0,
              "examples": [
                1
              ]
            },
            "txnId": {
              "$id": "/properties/changeItems/items/properties/txnId",
              "type": "integer",
              "title": "The Txnid Schema",
              "description": "The insights core API transaction id reference.",
              "default": 0,
              "examples": [
                402128
              ]
            },
            "changedFrom": {
              "$id": "/properties/changeItems/items/properties/changedFrom",
              "type": ["integer", "boolean"],
              "title": "The Changedfrom Schema",
              "description": "In case of a ClassNess change its the ClassNess enum value { Mandatory = 1, Discretionary = 2 }. In case of a ClassFreq change its the ClassFreq enum value { Recurring = 1, OnceOff = 2 }. In case of a Category change its the Sub Category ID. In case of a NAFlag change its a boolean value.",
              "default": 0,
              "examples": [
                2
              ]
            },
            "changedTo": {
              "$id": "/properties/changeItems/items/properties/changedTo",
              "type": ["integer", "boolean"],
              "title": "The Changedto Schema",
              "description": "In case of a ClassNess change its the ClassNess enum value { Mandatory = 1, Discretionary = 2 }. In case of a ClassFreq change its the ClassFreq enum value { Recurring = 1, OnceOff = 2 }. In case of a Category change its the Sub Category ID. In case of a NAFlag change its a boolean value.",
              "default": 0,
              "examples": [
                1
              ]
            },
            "text": {
              "$id": "/properties/changeItems/items/properties/changedTo",
              "type": "string",
              "title": "The Changedto Schema",
              "description": "Only applicable to change of type 'Note'.",
              "default": 0,
              "examples": [
                1
              ]
            }
          }
        }
      }
    }
  }

**Sample data**

{
  "dateStamp": "2018-01-30T06:07:32.912Z",
  "isReversal": false,
  "editingSessionId": "32ca71b3-f110-4586-9fd8-f875d7f367b3",
  "changeItems": [
    {
      "changeType": 1,
      "txnId": 402128,
      "changedFrom": 2,
      "changedTo": 1
    },
    {
      "changeType": 0,
      "txnId": 402128,
      "changedFrom": 2,
      "changedTo": 1
    }
}
    

**Your code**

const Ajv = require('ajv');
const ajv = new Ajv({schemaId: 'id'});
ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));
const assessChangesDtoSchema = require('./schemas/changeEventDto');
var validate = ajv.compile(assessChangesDtoSchema);
var valid = validate(assessmentChangesDto);

**Validation result, data AFTER validation, error messages**
[{
    "keyword": "type",
    "dataPath": "",
    "schemaPath": "#/type",
    "params": {
        "type": "object"
    },
    "message": "should be object"
}]

**What results did you expect?**
I expected it to pass validation successfully.
I have tested the same schema and data within this online tool, and it passes successfully.
https://jsonschema.net/#/ 

**Are you going to resolve the issue?**

**Comment by BrettStrongEH** [comment]
So sorry ... it is working fine. Was an error on my part.
Please disregard. Closing issue.

**Comment by rdiacenco** [comment]
@BrettStrongEH How did you manage to fix the error?

**Comment by aftabmj** [comment]
Yes, I am having the same issue. please say how you fixed it.

**Comment by epoberezkin** [comment]
you may be using ajv API incorrectly.

**Comment by BrettStrongEH** [comment]
Hi Guys,

Sorry for late reply. To be honest I can't remember what I was doing wrong.

In an effort to help you, here the code I am using now ... hopefully you can spot the difference that makes the difference :) ...

const Ajv = require('ajv');
const ajv = new Ajv(); // options can be passed, e.g. {allErrors: true}
// const ajv = new Ajv({schemaId: 'id'});
ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));
// ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));

const assessChangesDtoSchema = require('./schemas/changeEventDto');

// Validate the incoming assessmentChange DTO json schema ...
var validate = ajv.compile(assessChangesDtoSchema);
var valid = validate(assessmentChangesDto); 
//Where assessmentChangesDto is the posted json object to validate

The json schema file i have create an am using is as below ... 
{
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-06/schema#",
    "required": [ "dateStamp", "isReversal", "editingSessionId" ],
    "properties": {
      "dateStamp": {
        "$id": "/properties/dateStamp",
        "type": "string",
        "title": "The Datestamp Schema",
        "description": "Date object in UTC string format.",
        "default": "",
        "examples": [
          "2018-01-29T08:26:12.911Z"
        ]
      },
      "isReversal": {
        "$id": "/properties/isReversal",
        "type": "boolean",
        "title": "The Isreversal Schema",
        "description": "A boolean value indicating whether this change event is a reversal. Reversals are only possible if the change being reversed was the last change saved",
        "default": false,
        "examples": [
          false
        ]
      },
      "editingSessionId": {
        "$id": "/properties/editingSessionId",
        "type": "string",
        "title": "The Editingsessionid Schema",
        "description": "The assessment editing session id.",
        "default": "",
        "examples": [
          "a3c65ff7-ee67-44be-846a-7dc4441d96ca"
        ]
      },
      "changeItems": {
        "$id": "/properties/changeItems",
        "type": "array",
        "items": {
          "$id": "/properties/changeItems/items",
          "type": "object",
          "required": ["changeType", "txnId"],
          "properties": {
            "changeType": {
              "$id": "/properties/changeItems/items/properties/changeType",
              "type": "integer",
              "enum": [0, 1, 2, 3, 4],
              "title": "The Changetype Schema",
              "description": "ChangeType enum { ClassFrequency = 0,  ClassNessecity = 1,  Recatorisation = 2,  NAFlag = 3,  Note = 4 }.",
              "default": 0,
              "examples": [
                1
              ]
            },
            "txnId": {
              "$id": "/properties/changeItems/items/properties/txnId",
              "type": ["integer", "string"],
              "title": "The Txnid Schema",
              "description": "The insights core API transaction id reference.",
              "default": 0,
              "examples": [
                402128
              ]
            },
            "existingOverrideId": {
              "$id": "/properties/existingOverrideId",
              "type": ["string", "null"],
              "title": "The existingOverrideId Schema",
              "description": "The existing overide record id in the database. If ",
              "default": "",
              "examples": [
                "a3c65ff7-ee67-44be-846a-7dc4441d96ca"
              ]
            },
            "applicantId": {
              "$id": "/properties/applicantId",
              "type": ["string"],
              "title": "The applicantId Schema",
              "description": "The applicantId id in the database.",
              "default": "",
              "examples": [
                "a3c65ff7-ee67-44be-846a-7dc4441d96ca"
              ]
            },
            "changedFrom": {
              "$id": "/properties/changeItems/items/properties/changedFrom",
              "type": ["integer", "string", "boolean"],
              "title": "The Changedfrom Schema",
              "description": "In case of a ClassNess change its the ClassNess enum value { Mandatory = 1, Discretionary = 2 }. In case of a ClassFreq change its the ClassFreq enum value { Recurring = 1, OnceOff = 2 }. In case of a Category change its the Sub Category ID. In case of a NAFlag change its a boolean value.",
              "default": 0,
              "examples": [
                2
              ]
            },
            "changedTo": {
              "$id": "/properties/changeItems/items/properties/changedTo",
              "type": ["integer", "string", "boolean"],
              "title": "The Changedto Schema",
              "description": "In case of a ClassNess change its the ClassNess enum value { Mandatory = 1, Discretionary = 2 }. In case of a ClassFreq change its the ClassFreq enum value { Recurring = 1, OnceOff = 2 }. In case of a Category change its the Sub Category ID. In case of a NAFlag change its a boolean value.",
              "default": 0,
              "examples": [
                1
              ]
            },
            "text": {
              "$id": "/properties/changeItems/items/properties/changedTo",
              "type": "string",
              "title": "The Changedto Schema",
              "description": "Only applicable to change of type 'Note'.",
              "default": 0,
              "examples": [
                1
              ]
            }
          }
        }
      }
    }
  }

**Comment by rdiacenco** [comment]
Hey guys,
I figured out what was happening, in my case.
I was sending the data for validation, in String format, instead of Object, this is why it complained, that the schema expected an Object type ("type": "object"), but in reality it was not an Object, it was a String.
To verify the type of your data (sent for validation), you could use typeof(data), to see if you are indeed sending an Object.

**Comment by locohost** [comment]
I'm getting this now too. However, unlike @rdiacenco  I am **not** passing any string property through that the schema is expecting to be an object. I've been going through my simple JSON data and schema line-by-line for an hour+ and there is no invalid data anywhere.

**Comment by epoberezkin** [comment]
@locohost you can post a code sample that fails to runkit.com and post the link here.

**Comment by JakeGinnivan** [comment]
I just hit this with fastify and took me a while to get to the bottom of it.

My problem was missing the response type:

```
response: mySchema,
```

Fix

```
response: {
   200: mySchema
}
```
