### ISSUE TITLE
Coercion of nullable integer values does not follow same rules as coercion of nullable numbers

### ISSUE THREAD

**Issue by igor-savin-ht** [ajv-validator/ajv#693]
**What version of Ajv you are you using?**
5.5.2
**What problem do you want to solve?**
Type coercion does not take into account nullability of field in case it is of integer and not number type and converts null to 0.
**What do you think is the correct solution to problem?**
If JSON Schema states that value can be either integer or null, and original value is null, it should stay null.
**Will you be able to implement it?**
Yes.

**Comment by epoberezkin** [comment]
> If JSON Schema states that value can be either numeric or null, and original value is null, it should stay null.

That is already the case. Schema `{"type": ["number", "null"]}` does not coerce `null` to `0`. Submit your example, current and the proposed result.

> For compatibility sake this behaviour probably should be configureable.

I disagree.

**Comment by igor-savin-ht** [comment]
@epoberezkin Huh, interesting, if it works that way, then it's great news. Is it a new behaviour, e. g. since version 6+ or 5.5.2 should already behave that way?

Well, alternative to configureable behaviour would be major version bump, I wonder if that is what already happened. Then the only missing thing would be documentation update, I guess, which I would gladly do.

**Comment by igor-savin-ht** [comment]
@epoberezkin I've figured out what's wrong, ajv works exactly as you have described when type 'number' is used; however, it is not working for 'integer' type, even though it most likely should. I'm trying to create a PR with failing test now.

**Comment by igor-savin-ht** [comment]
@epoberezkin Sorry for rushing to conclusions, it was an insane week and I should have done more through investigation before raising an issue. You were right, Ajv works flawlessly in this case, problem was due to Swagger 2.0 limitations, generated Swagger YAML files that were used for validations didn't have original multiple-value JSON schema. I will try to resolve the issue within https://github.com/idanto/express-ajv-swagger-validation/issues/21.
Thank you for most helpful response and sorry for the inconvenience.

**Comment by epoberezkin** [comment]
No worries, I’m glad it’s sorted.

**Comment by sparebytes** [comment]
Found a very similar situation when dealing with `anyOf`. The order of the `anyOf` is important. EG, null values will be coerced into 0 with the following schema:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/MyBox",
    "definitions": {
        "MyBox": {
            "type": "object",
            "properties": {
                "value": { "anyOf": [{ "$ref": "#/definitions/Int" }, { "type": "null" }] } }
            },
            "additionalProperties": false
        },
        "Int": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
        }
    }
}
```

but changing `anyOf` to `[{ "type": "null" }, { "$ref": "#/definitions/Int" }]` will leave nulls as-is.
