### ISSUE TITLE
trim, lowercase, ...

### ISSUE THREAD

**Issue by mathieug** [ajv-validator/ajv#705]
I'd like to modify (trim, lowercase, cast to ObjectId) some data after checking their type but before the format.
I've created few custom keywords:
**lowercase:**
```
{
  errors: false,
  compile: (schema, parentSchema) => {
    if (!schema) {
      return _.constant(true);
    }
    if (parentSchema.type !== 'string') {
      return _.constant(false);
    }
    return (value, objectKey, object, key) => {
      if (_.isString(object[key])) {
        object[key] = object[key].toLowerCase();
      }
      return true;
    };
  }
}
```

**trim:**
```
{
  errors: false,
  compile: (schema, parentSchema) => {
    if (!schema) {
      return _.constant(true);
    }
    if (parentSchema.type !== 'string') {
      return _.constant(false);
    }
    return (value, objectKey, object, key) => {
      if (_.isString(object[key])) {
        object[key] = object[key].trim();
      }
      return true;
    };
  }
}
```

It works but if I specify a format (email), the value is compared to the format before the trim/lowercase modification.

Here is my schema property: `"email": { "type": "string", "format": "email", "lowercase": true, "trim": true }`

**Comment by epoberezkin** [comment]
If you want to enforce a specific order of keywords execution, you need to use "allOf" keyword. In the same schema the standard keywords are always executed before custom keywords; making it configurable would introduce a lot of ambiguity.

So instead of your schema:

```json
{ "type": "string", "format": "email", "lowercase": true, "trim": true }
```

you need:

```json
{
  "type": "string",
  "allOf": [
    {"lowercase": true, "trim": true},
    {"format": "email"}
  ]
}
```

I think it could be useful for others to create one keyword that allows to define all string modifications and either make a separate package or add it to ajv-keywords, so you could:

```json
{
  "type": "string",
  "allOf": [
    {"text": ["lowercase", "trim"]},
    {"format": "email"}
  ]
}
```

**Comment by mathieug** [comment]
Thank you!
Do you have a sample of a keyword that could allow multiple modifications? I could make a PR on ajv-keywords ;)

**Comment by epoberezkin** [comment]
nope, but it should just compile into a series of calls to pre-defined functions (depending on the list of modification, or make it inline to have it faster).

**Comment by epoberezkin** [comment]
Also, when a keyword modifies data it needs `modifying: true` in its definition (or something like it, please check the docs), it won't work in all cases otherwise.

**Comment by mathieug** [comment]
Ok, I'll let you know for the keyword that would allow to define multiple string modifications.

It works with allOf and I've updated my keywords to a more concise way (validate instead of compile).

```
{
  type: 'string',
  errors: false,
  modifying: true,
  schema: false,
  validate: (value, dataPath, object, key) => {
    object[key] = _.toLower(value);

    return true;
  }
}
```

**Comment by epoberezkin** [comment]
You can also use `valid: true` in the definition, it makes the compiled code a bit more efficient (I think) and you don't need to return anything.

**Comment by mathieug** [comment]
Great to know! It's a lot of small things.

**trim:**
```
{
  type: 'string',
  errors: false,
  modifying: true,
  schema: false,
  valid: true,
  validate: (value, dataPath, object, key) => {
    object[key] = _.trim(value);
  }
}
```

Maybe you also got some tips for this keyword:
**objectid:**
```
{
  type: 'string',
  errors: false,
  modifying: true,
  schema: false,
  validate: (value, dataPath, object, key) => {
    if (!ObjectId.isValid(value)) {
      return false;
    }

    object[key] = new ObjectId(value);

    return true;
  }
}
```

**Comment by willfarrell** [comment]
@mathieug Checkout https://github.com/epoberezkin/ajv-keywords/pull/64
