### ISSUE TITLE
Dynamic schema

### ISSUE THREAD

**Issue by mathieug** [ajv-validator/ajv#706]
Is it possible to have a dynamic schema depending on a value given during the validation (so after the compilation)?

A sample schema:
```javascript
{
  "title": "Product",
  "type": "object",
  "additionalProperties": false,
  "required": ["name"],
  "properties": {
    "name": { "type": "string" },
    "companyId": { "type": "string" }
  }
}
```

I would like to require `companyId` depending on my logged user's role (admin or simple user).

I was thinking to a third parameter `extra` to method validate: `ajv.validate(schemaName, data, extra)`. I would have given `{ role: 'admininistrator' }` or `{ role: 'user' }` to this parameter.

I guess there is a way to achieve this without having to load multiple static schemas?

**Comment by mathieug** [comment]
Here is why I'm trying to achieve:
```javascript
function validateProductData(productData, currentUser) {
  const errors = {};

  if (!_.isString(productData.name)) {
    // Set error
  }

  if (currentUser.role === 'user') {
    if (!_.isString(productData.companyId)) {
      // Set error
    }
  } else {
    productData.companyId = currentUser.companyId; // I can do this myself after the validation
  }

  return errors;
}
```

**Comment by epoberezkin** [comment]
Did you see $data in docs? I think this is what you’re looking for

**Comment by mathieug** [comment]
It seems $data is a value coming from inside the object being validated?!
I would like to use a value coming from outside the object being validated (for example, coming from my Express request) when calling `ajv.validate()`. In my last message, the value is `currentUser.role`.

In my example, `companyId` is a property and required only when current user is administrator and must not exist when current user is not administrator. I'd like a way to avoid to have two schemas depending my current user's role., one schema when the user is administrator and an other when the user is not administrator:
```javascript
if (req.currentUser.type === 'administrator') {
  isValid = ajv.validate('product-admin', { name: 'Abc', companyId: '1a2b3c' });
  // Handle ajv.errors when user is admin
} else {
  isValid = ajv.validate('product-user', { name: 'Abc' });
  // Handle ajv.errors when user is not admin
}
```

**Comment by mathieug** [comment]
I'm reading your comment here: https://github.com/epoberezkin/ajv/issues/411#issuecomment-278762517
Maybe I could wrap my schema in an object with a required attribute schema and an optional attribute extraProperties?
```javascript
{
  "title": "Product",
  "type": "object",
  "additionalProperties": false,
  "required": ["schema"],
  "properties": {
    "schema": {
      "additionalProperties": false,
      "name": { "type": "string" },
      "companyId": { "type": "string" }
    },
    "extraProperties": {
      "additionalProperties": false,
      "currentUserRole": { "type": "string" }
    }
  }
}
```
I would have to find a trick to use $data to require and validate companyId depending value of extraProperties.currentUserRole.

What do you think?

**Comment by epoberezkin** [comment]
Yes, you can have indeed use your schema as part of a bigger schema and pass your data also wrapped. I would use other property names, something like "data" and "params", but the principle is the same. Then you can refer to values in params from the part of your schema in data with $data keyword.

A similar problem is described in https://github.com/epoberezkin/ajv/issues/398

**Comment by mathieug** [comment]
@epoberezkin How can I use $data to make a property required or not?

**Comment by epoberezkin** [comment]
`requried: {$data: 'json-pointer to the array of required properties}`

Or use custom keywords.

**Comment by mathieug** [comment]
Hm, I don't see how to make it dynamic.

Let's take a concrete example:
```json
{
  "title": "User",
  "description": "User",

  "type": "object",
  "additionalProperties": false,
  "required": ["data", "params"],
  "properties": {
    "data": {
      "type": "object",
      "additionalProperties": false,
      "required": ["email", "password"],
      "properties": {
        "companyId": { "type": "string", "objectid": true },
        "email": {
          "type": "string",
          "allOf": [
            { "lowercase": true, "trim": true },
            { "format": "email" }
          ]
        },
        "password": { "type": "string", "minLength": 6 }
      }
    },
    "params": {
      "type": "object",
      "additionalProperties": false,
      "required": ["role"],
      "properties": {
        "role": { "type": "string", "enum": ["administrator", "user"] }
      }
    }
  }
}
```

I don't see how to make data.companyId required if params.role is administrator.
If I can achieve that, I'd like companyId to not exist if params.role is user.

**Comment by mathieug** [comment]
Maybe with https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#ifthenelse but not sure if it works with $data?
