### ISSUE TITLE
regex flags in pattern should be allowed and used?

### ISSUE THREAD

**Issue by JaredCE** [ajv-validator/ajv#709]
Referring to this issue: https://github.com/epoberezkin/ajv/issues/101, I think https://github.com/json-schema/json-schema/issues/188 suggests that pattern should allow for and use flags.

**Comment by epoberezkin** [comment]
See https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/215#issuecomment-367418604
Closing it, as flags should not be supported
There is a custom keyword regexp in ajv-keywords that supports flags.
