### ISSUE TITLE
What about convertation\transformation?

### ISSUE THREAD

**Issue by Santinell** [ajv-validator/ajv#71]
What do you think about data convertation\transformation by `format` or by custom keyword?

Example sheme 1:

``` JSON
"queryParam": {
      "name": "query",
      "in": "query",
      "type": "string",
      "format": "json"
}
```

``` Javascript
ajv.addFormat('json', function(data, cb) {
   try {
     var obj = JSON.parse(data);
   } catch (err) {
     return cb(err);
   }
   cb(null, obj);
})
```

Example sheme 2:

``` JSON
"queryParam": {
      "name": "query",
      "in": "query",
      "type": "string",
      "x-transform": "json"
}
```

``` Javascript
ajv.addKeyword('x-transform', function(type, data, cb) {
   if (type === 'json') {
     try {
       var obj = JSON.parse(data);
     } catch (err) {
       return cb(err);
     }
     return cb(null, obj);
   }

   return cb('Transformation '+type+' not found');
})
```

**Comment by Santinell** [comment]
If use second variant we can wrote even something like:

``` JSON
      "x-transform": {
        "transformation": "json",
        "type": "object",
        "properties": {
          "field": {
            "type": "string"
          },
          "operation": {
            "type": "string"
          },
          "value": {
            "oneOf": [{
              "type": "string"
            }, {
              "type": "integer"
            }, {
              "type": "array"
            }]
          }
        }
      }
```

And validate it inside:

``` javascript
ajv.addKeyword('x-transform', function(opts, data, cb) {
   if (opts.transformation === 'json') {
     try {
       var obj = JSON.parse(data);
     } catch (err) {
       return cb(err);
     }
     return ajv.validate(opts, obj, cb);
   }
   cb('Transformation '+opts.transformation+' not found');
})
```

**Comment by epoberezkin** [comment]
Sorry, I don't think I understand what is the purpose... To use schema to modify the data being validated? Could you please explain a bit what is happening there?

**Comment by Santinell** [comment]
Эх...
Main purpose - is to give user a tool to modify data: sanitize, deserialize or prepare for next manipulating with them.
Example - library is not for json-schema, but have modificators ('trim', 'upper' rules):
https://github.com/Atinux/schema-inspector

**Comment by epoberezkin** [comment]
I see. I'll think about it. I still have to digest the idea of custom validation keywords... Custom transformations are the next step.

**Comment by Santinell** [comment]
tv4 not best example of json-schema validator, but can use custom validation keywords.
As can i see - the most fast way to make custom keywords - using rules, BUT - writing custom ".jst" templates is not best way IMHO. I think better make it simplier

**Comment by epoberezkin** [comment]
If I do custom keywords, they will be just functions, essentially interpreting their schema rather than compiling it. Given that the compiled schema is a single function in most cases allowing custom keywords that would participate in this compilation is a bit fragile. One can fork of course and implement the custom keywords in the repo with tests and such - don't think many people will go this way though.

**Comment by epoberezkin** [comment]
@Santinell custom keywords are available in [version 2.0](https://github.com/epoberezkin/ajv/tree/v2.0#defining-custom-keywords) (`npm install ajv@^2.0.0-beta` to use them). I guess you can use them for data transformations as well, with caution :)

**Comment by Santinell** [comment]
Cool :+1: 
Thanks!
testing, testing :)

**Comment by epoberezkin** [comment]
Just make sure you modify the same object instance if you want to change data. It won't be possible for scalar data of course.

For some more complex transformation inline keywords can be used where you can access the parent data or the whole data object.
