### ISSUE TITLE
allOf does not break

### ISSUE THREAD

**Issue by mathieug** [ajv-validator/ajv#711]
Schema:
```json
  "$async": true,
  "properties": {
    "companyId": {
      "type": "string",
      "allOf": [
        { "objectid": true },
        { "exists": { "collection": "companies", "attribute": "_id" } }
      ]
    }
```

objectid
```javascript
{
  errors: false,
  modifying: true,
  schema: false,
  validate: (value, dataPath, object, key) => {
    if (!ObjectId.isValid(value)) {
      return false;
    }

    object[key] = new ObjectId(value);

    return true;
  }
}
```

```javascript
{
  async: true,
  errors: false,
  schema: true,
  validate: (schema, data) => {
    const Model = modules[schema.collection].model;
    return Model.exists({ [schema.attribute]: data });
  }
}
```

Why is the validate function of my custom keyword `exists` called even when my custom keyword `objectid` fails?
I thought `allOf` stops at the first fail. Is it a bug with the async set to true?
Should async be true in `objectid`?

**Comment by mathieug** [comment]
I've tried without the async and ajv still tries to validate against all the allOf items.

**Comment by mathieug** [comment]
```json
    "companyId": {
      "type": "string",
      "if": { "objectid": true },
      "then": { "exists": { "collection": "companies", "attribute": "_id" } }
    }
```

This way there is no error message when objectid fails.

```json
    "companyId": {
      "type": "string",
      "if": { "objectid": true },
      "then": { "exists": { "collection": "companies", "attribute": "_id" } },
     "else": false
    }
```

And this way the error message when objectid fails is not explicit.

**Comment by mathieug** [comment]
How can I set breakOnError to true (https://github.com/epoberezkin/ajv/blob/master/lib/dot/allOf.jst#L26)?
Note that allErrors is set to true.

**Comment by epoberezkin** [comment]
`allErrors` option instructs ajv to collect all possible errors. To do it ajv will not short-circuit anything. Just don't use this option if you want to terminate as early as possible.

**Comment by epoberezkin** [comment]
`breakOnError` is always equal to `!allErrors`.
