### ISSUE TITLE
Enum works weird on arrays

### ISSUE THREAD

**Issue by droganov** [ajv-validator/ajv#712]
I need to check if array contains trusted values.

Normally it looks like I need to check `[1, 2, 3]` against `{enum: [1, 2, 3, 4, 5] }`.

But it doesn't work this way, I have to wrap it to `{ contains: {enum: [1, 2, 3, 4, 5] }}` which looks like an extra effort.

Also `contains` can't work with optional arrays.

**Comment by epoberezkin** [comment]
> Normally it looks like I need to check [1, 2, 3] against {enum: [1, 2, 3, 4, 5] }.

No, it is not correct. enum check for an individual value, not for array items.

If you need to check all items you need: 

```json
{"items": {"enum": [1, 2, 3, 4, 5]}}
```

`{ contains: {enum: [1, 2, 3, 4, 5] }}` checks that at least one item is from that list, it won't check all.

Please see JSON schema docs or https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md
