### ISSUE TITLE
Add "allowedValue" to error params of "const" keyword

### ISSUE THREAD

**Issue by marshall007** [ajv-validator/ajv#713]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`6.1.1`, yes.

**Ajv options object**

```javascript
{
  allErrors: true,
  useDefaults: true,
  removeAdditional: 'all',
  coerceTypes: 'array',
}
```

**JSON Schema**

```json
{
  "type": "string",
  "const": "EVENT",
  "default": "EVENT"
}
```

**Sample data**

```json
"FOO"
```

**Your code**

```javascript
ajv.validate({
  "type": "string",
  "const": "EVENT"
}, 'FOO');
```

**Validation result, data AFTER validation, error messages**

```json
[
  {
    "keyword": "const",
    "dataPath": "",
    "schemaPath": "#/const",
    "params": {},
    "message": "should be equal to constant"
  }
]
```

**What results did you expect?**

This issue is virtually identical to #282, i.e. that it would be nice if the error payload contained a reference to the required constant value.

**Are you going to resolve the issue?**

I would need to investigate the templating stuff before submitting a fix, but the issue should be resolved by adding `allowedValue` (or similar) [here](https://github.com/epoberezkin/ajv/blob/master/lib/dot/errors.def#L170).

**Comment by epoberezkin** [comment]
Yes, that’s ok, makes error reporting more consistent. Implementation should be quite straightforward, see the PR that closed the other issue.

**Comment by marshall007** [comment]
@epoberezkin great, I'll have a PR up in the next day or two.
