### ISSUE TITLE
[TS] Thenable vs. PromiseLike

### ISSUE THREAD

**Issue by krenor** [ajv-validator/ajv#717]
If I understand it correctly `Thenable` is nothing more than a disguised Promise, right? Is there a reason why some libraries use `Thenable` rather than the official typescript Promise declaration?

Using `Thenable` is not possible with native Promises.

```typescript
import * as Ajv from "ajv"

const foo: Ajv.Thenable<boolean> = new Promise<boolean>((resolve, reject) => {
  if ("condition")
    resolve(true)

  reject("Nope")
})
```

Will always compile with an error:

```
error TS2322: Type 'Promise<boolean>' is not assignable to type 'Thenable<boolean>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = boolean, TResult2 = never>(onfulfilled?: ((value: boolean) => TResult1 | PromiseLike<...' is not assignable to type '<U>(onFulfilled?: ((value: boolean) => U | Thenable<U>) | undefined, onRejected?: ((error: any) =...'.
      Types of parameters 'onfulfilled' and 'onFulfilled' are incompatible.
        Type '((value: boolean) => U | Thenable<U>) | undefined' is not assignable to type '((value: boolean) => U | PromiseLike<U>) | null | undefined'.
          Type '(value: boolean) => U | Thenable<U>' is not assignable to type '((value: boolean) => U | PromiseLike<U>) | null | undefined'.
            Type '(value: boolean) => U | Thenable<U>' is not assignable to type '(value: boolean) => U | PromiseLike<U>'.
              Type 'U | Thenable<U>' is not assignable to type 'U | PromiseLike<U>'.
                Type 'Thenable<U>' is not assignable to type 'U | PromiseLike<U>'.
                  Type 'Thenable<U>' is not assignable to type 'PromiseLike<U>'.
                    Types of property 'then' are incompatible.
                      Type '<U>(onFulfilled?: ((value: U) => U | Thenable<U>) | undefined, onRejected?: ((error: any) => U | ...' is not assignable to type '<TResult1 = U, TResult2 = never>(onfulfilled?: ((value: U) => TResult1 | PromiseLike<TResult1>) |...'.
                        Types of parameters 'onFulfilled' and 'onfulfilled' are incompatible.
                          Type '((value: U) => TResult1 | PromiseLike<TResult1>) | null | undefined' is not assignable to type '((value: U) => TResult2 | Thenable<TResult2>) | undefined'.
                            Type 'null' is not assignable to type '((value: U) => TResult2 | Thenable<TResult2>) | undefined'
```

Removing the `Thenable` Interface and replacing references with `PromiseLike` in the typings get rid of the error. Am I safe to provide a PR which does that or is there a reason behind `Thenable` I seem to miss?

/cc @blakeembrey

**Comment by Bgshanoams** [comment]
but,this make change,all.....

На 22.02.2018 г. 10:24 "Stan" <notifications@github.com> написа:

**Comment by Bgshanoams** [comment]
Send some card number....pls.Bro

На 22.02.2018 г. 19:57 "Ani Lukas" <6anoboyz80@gmail.com> написа:

**Comment by blakeembrey** [comment]
Sounds reasonable. There’s only two reasons for the custom promise to exist:

1. Supporting old TypeScript versions before the Promise type (like really old now)
2. Supporting ES5 compilation without requiring promises

**Comment by epoberezkin** [comment]
@blakeembrey thank you. Does it mean that should be a major version change?

**Comment by krenor** [comment]
@blakeembrey What exactly do you mean?
> with requiring promises

 I'm using TS most of the time compiling down to ES5 without any adjustments necessary to use Promises.

**Comment by blakeembrey** [comment]
@krenor Phone typo, sorry. Was meant to say without. But TypeScript ported `PromiseLike` to the old definitions without `Promise` a while back anyway to support some browser APIs IIRC (https://github.com/Microsoft/TypeScript/blob/32c63a26284c0fcf6dfbdce709f3da680c2940d9/lib/lib.es5.d.ts#L1298) so this isn't a concern, it's a good change since they did that.

@epoberezkin I don't think so. Pretty sure the version support is the same as other features your using, so all good.

**Comment by epoberezkin** [comment]
Released
