### ISSUE TITLE
Strange behaviour when checked variable is missing

### ISSUE THREAD

**Issue by abdallahkadour** [ajv-validator/ajv#724]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.1.1

**Ajv options object**

```javascript
var ajv = new Ajv({allErrors: true, validateSchema: true, $data: true})
```

**JSON Schema**

```js
var schema = {
  '$schema': 'http://json-schema.org/draft-07/schema#',
  '$id': 'schemaId',
  'type': 'object',
  'allOf': [
    {
      'if': {
        'properties': {
          'code': {
            'enum': ['01', '02']
          }
        }
      },
      'then': {
        'required': ['reason']
      }
    }
  ]
}

```

**Sample data**

```json
{
}

```

**Validation result, data AFTER validation, error messages**

```
[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/allOf/0/then/required',
    params: { missingProperty: 'reason' },
    message: 'should have required property \'reason\'' }]
```

**What results did you expect?**
If the variable `code` is missing, the object should be valid, and the variable `reason` should not be required.

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
The schema in "then" is applied because the data is valid against the schema in "if", so this is the correct behaviour.

**Comment by epoberezkin** [comment]
You don't need to put if/then inside allOf btw.

**Comment by abdallahkadour** [comment]
Yes I know, I have just removed the other if statement. But could you please explain me why the data is valid against the schema in if. Since the variable code !== ‘01’ or ‘02’.

**Comment by epoberezkin** [comment]
because property "code" is not required by the schema, so an empty object is valid.

**Comment by abdallahkadour** [comment]
That is the point. The empty object should be valid. But I get the error...

**Comment by epoberezkin** [comment]
an empty object is valid against the schema in "if", so "then" is applied and it is invalid against "then"

**Comment by abdallahkadour** [comment]
Since the variable code is not  ‘01’ the variable reason should not be required. But when the variable ‘code’ is missing, I expect that the variable reason should not be required.

**Comment by abdallahkadour** [comment]
Ok thank you.

**Comment by epoberezkin** [comment]
you need `required: 'code'` in "if"
