### ISSUE TITLE
"uniqueItems" limitations caused by performance optimisation

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#727]
**Affected versions**
6.x.x only, <= 5.x.x is ok

**Problem**
"uniqueItems" when item "type" is specified as array of types in "items" schema will coerce all items to string before comparison (so `"5"` will be considered equal to `5`, etc.). If one of allowed types in the list is "array" or "object", uniqueItems simply won't work correctly, as all objects will be coerced as well and considered equal.

**Solution**
Make generated code dependent on the list of allowed types.

Related to #725

**Comment by epoberezkin** [comment]
@domoritz please let me know if you’re interested to fix it, I can then explain the scenarios that should be supported. It’s seems to me a bit bigger problem than #725 introduced by that performance optimisation of uniqueItems. I guess heterogenous arrays aren’t that common - that’s why nobody caught it.

**Comment by domoritz** [comment]
I can't take on another project right now. Sorry!

**Comment by markchart** [comment]
Actually, I just caught it-- and then discovered that you fixed it.  Thanks!
