### ISSUE TITLE
Required validation for object in AJV doesn't work with empty value {}

### ISSUE THREAD

**Issue by chintankshah** [ajv-validator/ajv#728]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest version of AJV - 6.2.0

I'm using AJV for validating JSON schemas. I have a property of type object where certain fields are required. In below schema, name and email properties are required for person object. The validation works fine if one of name or email has a value. But when the object is empty {} it doesn't call it invalid and throw an error that I'd expect it to.

**AJV Options**

```js
ajvOptions: any = { allErrors: true, jsonPointers: true, unknownFormats: 'ignore' };
```

**JSON Schema**

```json
{
  "schema": {
    "type": "object",
    "properties": {
      "person": { 
        "type": "object",
        "required":["name", "email"],
        "properties": {
          "name": { "type": "string", "minLength": 1, "required": true },
          "email": { "type": "string","minLength": 1, "required": true }
        }
      }
    }
  }
}
```

**Sample data**

```json
{}
```

**Validation result, data AFTER validation, error messages**

When there's no data for this object set, it accepts the value and treats it as a valid form. 

**What results did you expect?**

I expected it to to throw required fields error as mentioned in documentation [here](https://epoberezkin.github.io/ajv/keywords.html#keywords-for-objects) which says {} is invalid.

**Comment by epoberezkin** [comment]
That is correct result, because to level property “person” is not required by the schema

**Comment by epoberezkin** [comment]
Also, not sure why do you need property “schema”, depending on what you pass to ajv, it may not work

**Comment by chintankshah** [comment]
Thanks @epoberezkin. I figured the same thing. Just had to add person to required in the schema object and it worked. Thanks for quick reply.

**Comment by rkma** [comment]
use javascript - ajv validaion - if i give a json as a string format - is AJV accepts,
And where parse json object to ajv if error in required condition ....is able to display which line error occured???
