### ISSUE TITLE
i want to validate against array with unique strings so i add custom keyword to trim string then use uniqueItems in array but not as i expected uniqueItems run before trim so are there way to control flow to make trim run first then uniqueItems ?

### ISSUE THREAD

**Issue by anas-hossam** [ajv-validator/ajv#733]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript


```

**JSON Schema**

```json


```

**Sample data**

```json


```

**Your code**
 uniqueItems: {
                    allOf: [
                        {
                            type: 'array',
                            minItems: 1,
                            uniqueItems: true,
                        },
                        { 
                            items: {
                                type: 'string',
                                minLength: 1,
                                trim: true,                    
                            },
                        },
                    ],
                }

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
You can control execution order using allOf
