### ISSUE TITLE
oneOf null, string with non-empty pattern coerces to empty string instead of null

### ISSUE THREAD

**Issue by kapouer** [ajv-validator/ajv#734]
ajv version: 6.2.1
```
var ajvApi = require('ajv')({
	coerceTypes: true
});

var vv = ajvApi.compile({
	properties: {
		test: {
			oneOf: [{type: "null"}, { type: "string", pattern: "^M+$"}]
		}
	}
});

var data = {test: ""};
vv(data);

console.log(JSON.stringify(data.test));
```

What is expected ? `data.test === null`.

**Comment by epoberezkin** [comment]
That’s an expected behaviour - oneOf has to validate against all schemas (to make sure only one passes), so it will coerce as neede to pass. You need to use anyOf in this case (and in all cases when the schemas are mutually exclusive).

**Comment by kapouer** [comment]
oh ! thank you for the explanation.

**Comment by thejuan** [comment]
anyOf seems to be doing the same

**Comment by kapouer** [comment]
@thejuan no it doesn't, unless you found some kind of bug, in which case you should document why you say that.

**Comment by thejuan** [comment]
I have coerceTypes enabled. I would expect AJV to try all types before trying coercion.

**Comment by epoberezkin** [comment]
You expect too much from it. It would try all types if you use `type: ['number', 'string']`; the way you have it, at the point when it validates the first type it doesn't know about the existence of another type in another branch.
