### ISSUE TITLE
Float64Array or Float32Array fail validation against "array" type

### ISSUE THREAD

**Issue by Nehon** [ajv-validator/ajv#735]
Hello I'm using ajv to validate user input for a 3D renderer and I have arrays that are actually Float64Array. they are declared as "array" in the Json Schema and I thought it would work.
Here is a simplified test case that demonstrates the issue: 

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.2.1

**Ajv options object**

```javascript
{ allErrors: true }
```

**JSON Schema**

```javascript

      var schema =  {
            type: 'object',
            properties: {
                vec3: {
                    type: 'array',
                    minItems: 3,
                    maxItems: 3,
                    items: { type: 'number' }
                }
            },
            required: ['vec3']
        };
```

**Sample data**

```javascript
       var obj = {
            vec3: new Float64Array(3)
        };

```

**Your code**

```javascript

        var validator = new Ajv({ allErrors: true }).compile(schema);
        var valid = validator(obj);
        if (!valid) {
            console.log(validator.errors, obj, schema);
        }
```

**Validation result, data AFTER validation, error messages**

```
{keyword: "type", dataPath: ".vec3", schemaPath: "#/properties/vec3/type", params: {…}, message: "should be array"}

```

**What results did you expect?**
I'm not sure if validating Float64Array or Float32Array against "array" is 100% valid with the Json Schema spec. But since there is no way to specify the specific type in the schema (or maybe there is?), I'd expect they'd be considered as arrays.

**Are you going to resolve the issue?**
For now my workaround is to ignore the error in my validation process, since I expect it, but it would be really nice that it works out of the box.

**Comment by Nehon** [comment]
Digging a bit more into it, it's seems not as straight forward as I thought.
'typeof' on a TypedArray return 'object' which with hindsight makes a lot of sense.
The only way I could check the type is using the "instanceof" keyword on the specific type (cannot test instanceof TypedArray).
So basically you'd have to check against all TypedArray sub types... 
I realise I could declare my arrays as objects in the Json Schema, but I feel like it'd become very cumbersome.

**Comment by epoberezkin** [comment]
Correct, they are not "arrays". typeof is "object" for all arrays, but the problem is that `Array.isArray(new Float64Array(3))` is false...

A custom keyword can be used to validate them.
