### ISSUE TITLE
Flag to trim or not string field values before validating

### ISSUE THREAD

**Issue by nbankin** [ajv-validator/ajv#741]
**What version of Ajv you are you using?**
"ajv": "5.5.2"

**What problem do you want to solve?**
When validating string values trailing or leading white spaces  should not be counted in the field length nor only white spaces should be accepted as a value in certain scenarios.

**What do you think is the correct solution to problem?**
Have a flag global for the validator instance and local on the single fields (for strings mainly) to trim or not the value before validating them against the other rules.

**Will you be able to implement it?**
No, at the moment.

**Comment by epoberezkin** [comment]
Changing the way the standard keywords work is a wrong approach, in the most cases. A better solution is to use a custom keyword, so your transformations are explicit. See https://github.com/epoberezkin/ajv/issues/705

**Comment by bankin** [comment]
I was thinking of introducing new keyword, not modify the current ones. For example when creating new instance of the validator pass a parameter like `trimValues: true` and have the same param which can be applied to fields.

My problem is that I have complex schema and having to apply this `allOf` to every string field will double or triple my schema code and will add tons of boilerplate. 

I was searching for a cleaner solution.

**Comment by nbankin** [comment]
I never intended to modify current flags/keywords. I was thinking of introducing a new one `trimValues` for example which can be applied to the Validator instance and will work for all string fields or be applied to specific fields if you want to enable/disable it for a particular field.

I saw #705 but I have complex scheme and adding `allOf` on every field will double or triple my schema and add a lot of boilerplate to it. I was searching for a simpler solution.

**Comment by willfarrell** [comment]
@nbankin Checkout https://github.com/epoberezkin/ajv-keywords/pull/64
