### ISSUE TITLE
Is it support convert letter to upper-case?

### ISSUE THREAD

**Issue by msforest** [ajv-validator/ajv#742]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v6.3.0

**Sample data**

```json
{
  test: 'test'
}

```

**What results did you expect?**
I expect that convert valut to upper-case
```
// output:
{
  test: 'TEST'
}
```

**Are you going to resolve the issue?**
no

**Comment by epoberezkin** [comment]
Almost a duplicate of https://github.com/epoberezkin/ajv/issues/705

**Comment by willfarrell** [comment]
@msforest Checkout https://github.com/epoberezkin/ajv-keywords/pull/64

**Comment by msforest** [comment]
@willfarrell thank you, I already have solved
