### ISSUE TITLE
additional properties are not filtered out in certain case

### ISSUE THREAD

**Issue by fogine** [ajv-validator/ajv#743]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`6.3.0`

**Ajv options object**
```javascript
{
    allErrors: false,
    additionalProperties: true,
    removeAdditional: true,
}
```

**JSON Schema**

```javascript
const schema = {
    type: 'object',
    additionalProperties: false,
    properties: {
        contributors: {
            type: "object",
            additionalProperties: false,
            properties: {
                a: { type: 'string' },
                b: { type: 'string' },
                c: { type: 'string' },
                d: { type: 'string' },
                e: { type: 'string' },
                f: { type: 'string' },
            }
        },
    }
};
```

**Sample data**

```javascript
let obj= Object.create(null);
obj.__proto__ = null; //should be filtered out, however in certain case tn is not
obj.invalid = 'is filterred out';
obj.a = 'valid';
obj.b = 'valid';

let data = {contributors: obj};
```

**Your code**

```javascript
let validator = new Ajv(options);
let result = validator.validate(schema, data)
```

**Validation result, data AFTER validation, error messages**

```
RESULT: true,
DATA AFTER VALIDATION:
{"contributors":{"__proto__":null,"a":"valid","b":"valid"}}
```

**What results did you expect?**
`__proto__` property (which is in this case a regular enumerable property) to not be present in the data object after validation.  

Please **NOTE** that if you remove any one of the properties listed in `schema#/properties/constributors/properties` so that overall number of defined properties is LESS than 6, the `__proto__` property will be correctly filtered out (deleted) from the data object (expected result).

**Comment by fogine** [comment]
Also this issue applies for dataset:

```javascript
let data = {
    contributors: JSON.parse(JSON.stringify(obj))
};

```

**Comment by epoberezkin** [comment]
The bug is here: https://github.com/epoberezkin/ajv/blob/master/lib/dot/properties.jst#L62
I believe it needs `=== undefined` in the end of the line to fix. Also it needs test if you do PR.

**Comment by epoberezkin** [comment]
actually it only happens in this edge case, it's not the bug I thought it is... Also when property has boolean schema `false` and there is > 5 properties in the schema, ajv will incorrectly see this property as additional.
