### ISSUE TITLE
Release notes missing for 6.2.1 and 6.3.0

### ISSUE THREAD

**Issue by edmorley** [ajv-validator/ajv#744]
Hi!

The last entry in the releases section is for 6.2.0, whereas the last release is 6.3.0:
https://github.com/epoberezkin/ajv/releases

Tools like [Renovate](https://renovateapp.com/) use the changelog/releases section to display the release notes in the PRs they open, so all entries being present is quite useful :-)

**Comment by epoberezkin** [comment]
Added 6.3.0
