### ISSUE TITLE
Accepts null input as valid.

### ISSUE THREAD

**Issue by ESRogs** [ajv-validator/ajv#745]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Version: 6.3.0

**Ajv options object**

{ allErrors: true }

**Your code**

```javascript
const ajv = require('ajv')({ allErrors: true });
const schema = {
  required: ['foo'],
  properties: { foo: { type: 'number' } },
};
const validate = ajv.compile(schema);
validate({foo:5}); // true, as expected
validate({foo:'bar'}); // false, as expected
validate({}); // false -- as expected

validate(null); // true -- not expected!
validate('bar'); // true -- not expected!
validate(0); // true -- not expected!

```

**What results did you expect?**

I expect the validation to return false and produce errors when a string, number, or null value is passed in instead of an object.

**Comment by epoberezkin** [comment]
The result is correct, schema doesn’t require a specific type. See https://github.com/epoberezkin/ajv/blob/master/FAQ.md

**Comment by ESRogs** [comment]
Hmm. I found this behavior very surprising, but it does seem to match this part of the spec, so I guess you're right.

> 3.2.1.  Assertions and Instance Primitive Types
> 
>    Most validation assertions only constrain values within a certain
>    primitive type.  When the type of the instance is not of the type
>    targeted by the keyword, the instance is considered to conform to the
>    assertion.

https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-3.2.1
