### ISSUE TITLE
Failed to minify the code from this file: URI-JS

### ISSUE THREAD

**Issue by debabrata100** [ajv-validator/ajv#749]
**ajv version: 6.4.0**
Hi,
 I am using Ajv in react-js.
When I start building my project its showing following error:

> Failed to minify the code from this file: 
> ./node_modules/uri-js/dist/esnext/uri.js:42 

Has anyone resolved this?
Plz help me...
Thanks in Advance...

**Comment by epoberezkin** [comment]
@debabrata100 please submit the issue either to uri-js or to react-js, if it's not submitted there already.

**Comment by debabrata100** [comment]
@epoberezkin Thanks for your reply. I got a solution for the issue.

**Comment by vankop** [comment]
I'm using create-react-app. [Problem with commonjs module described here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

**Comment by vankop** [comment]
find out problem in uri-js `package.json` in `module` section.

**UPDATE**: just seems like `UglifyJsPlugin` can not minimize es5 module
