### ISSUE TITLE
make option for format='email' to require top level domain

### ISSUE THREAD

**Issue by zsolt-dev** [ajv-validator/ajv#756]
Right now, this is considered valid email: john@doe

in 99% of use cases, email without dot/without top level domain, should not be accepted as valid.

it would be nice to have a config option to disallow emails like these.

Thank you

**Comment by epoberezkin** [comment]
It exists: https://runkit.com/esp/5ad26dff34cee100126093f2

**Comment by zsolt-dev** [comment]
Thank you.

was searching in the docu and issues menu for 30 minutes.

Thank you again
