### ISSUE TITLE
bootstrap 4 integration

### ISSUE THREAD

**Issue by Giancarlo1974** [ajv-validator/ajv#759]
**What version of Ajv you are you using?**

latest

**What problem do you want to solve?**

bootstrap 4 form integration
https://getbootstrap.com/docs/4.0/components/forms/#custom-styles

**What do you think is the correct solution to problem?**

you must implement a function for compile errors into form bootstrap

**Will you be able to implement it?**

No :-(

**Comment by epoberezkin** [comment]
That's out of scope of this package. You can do it your code or create a separate package.
