### ISSUE TITLE
Uncaught Error: Cannot find module "./refs/json-schema-draft-07.json"

### ISSUE THREAD

**Issue by Hsueh-Jen** [ajv-validator/ajv#762]
ajv verision I used was "^6.4.0"

I import ajv
```javascript
import Ajv from 'ajv';
```

and I use it in function, but I have error when I new Ajv()
```javascript
const ajv = new Ajv({ allErrors: true });
```
it shows `Uncaught Error: Cannot find module "./refs/json-schema-draft-07.json"`

error msg screen shot
 ![error msg screen shot](https://i.imgur.com/bE1NkZT.png)

I already npm install ajv. Why does it happen.

draft-07 exists
![draft-07](https://i.imgur.com/tSlXQ6u.png)

Does I do something wrong? I can use it when I use `new Ajv({meta: false });` before. But it can't works now even I use `new Ajv({meta: false, allErrors: true  });`. I don't know why.

Please help me. Thanks a lot.

**Comment by epoberezkin** [comment]
Assuming you are using Babel/webpack, you need to copy/include JSON files in your target folder/bundle

**Comment by Hsueh-Jen** [comment]
I change code of`webpack.base.babel.js` and it works.

I add `include: /node_modules/,` in json-loader config to solve this problem. Thank you.

```jsx
{
  test: /\.json$/,
  include: /node_modules/,
  loader: 'json-loader',
}
```
