### ISSUE TITLE
passContext is not used with "$ref" referenced schema

### ISSUE THREAD

**Issue by cvlab** [ajv-validator/ajv#768]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.4.0, yes

**Ajv options object**

```javascript
{ passContext: true }
```

**JSON Schema**

```json
{
	"$id": "https://www.example.com/schemas/resource.json",
	"type": "object",
	"properties": {
		"leaf": {
			"type": "string",
			"leaf": true
		},
		"resources": {
			"$ref": "resource.json"
		}
	}
}
```

**Sample data**

```json
{
	"leaf": "first",
	"resources": {
		"leaf": "second"
	}
}
```

**Your code**

```javascript
ajv.addKeyword('leaf', {
	type: 'string',
	validate: function(schema, data) {
	// for second leaf is false
        console.log(this && this.context === 'my-context')
        return true
    }
})

const validate = ajv.compile(schema)

validate.call({ context: 'my-context' }, {
    leaf: 'one',
    resources: {
        leaf: 'second'
    }
})

```

**What results did you expect?**

`this` from `validate.call(this, data)` === `this` from custom keyword function
in test is not true for schema referenced with `$ref`

**Are you going to resolve the issue?**
My guess is, in this line https://github.com/epoberezkin/ajv/blob/e88e5f53d71e11f94898fb9f7fe8bd0b0bd43692/lib/compile/index.js#L74

must be `this`, `var result = validate.apply(this, arguments);`

**Comment by epoberezkin** [comment]
Possibly depending on passContext option value? Also, there may a few other places like that.

**Comment by cvlab** [comment]
`callValidate` https://github.com/epoberezkin/ajv/blob/e88e5f53d71e11f94898fb9f7fe8bd0b0bd43692/lib/compile/index.js#L72

if `{ passContext: true }` `callValidate` is called as
`if (!refVal1.call(this, data.resources, ...`

if `{ passContext: false }` `callValidate` is called as
`if (!refVal1(data.resources, ...`

`callValidate` is always called in this way?

If yes, then inside `callValidate`, `this` is always undefined when `passContext` is false

my guess is safe to change `var result = validate.apply(null, arguments); ` to `var result = validate.apply(this, arguments); `, `null` or `undefined` is the same for `apply` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Parameters)

**Comment by epoberezkin** [comment]
Yes, seems so... Will you make PR with a failing test and the fix?

**Comment by cvlab** [comment]
Ok
