### ISSUE TITLE
If/then/else doesn't seem to work correctly

### ISSUE THREAD

**Issue by markcmueller** [ajv-validator/ajv#770]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.4.0

**Ajv options object**

**JSON Schema**
```json
{
  "id": "urn:json-schema:com.demo.Demo",
  "title": "Demo",
  "description": "A demo of if/then/else not working",
  "type": "object",
  "properties": {
    "method": {
      "enum": ["AA", "BB", "CC"]
    },
    "name": {
      "description": "Name of the product",
      "type": "string",
      "pattern": "^[a-zA-Z]{2}$"
    },
    "price": {
      "type": "string",
      "pattern": "^[0-9]{2}$"
    }
  },
  "allOf": [{
    "if": {
      "properties": {
        "method": {
          "enum": ["AA"]
        }
      }
    },
    "then": {
      "required": ["method", "name", "price"]
    },
    "else": {
      "required": ["method", "name"]
    }
  }]
}
```

**Sample data**
```
{
  "method": "AA",
  "product": "zs"
}
```

**Your code**

```javascript
  validateAgainstSchema() {
    const jsonString = this.state.value;
    const schema = require('./data/demo-schema.json');

    var Ajv = require('ajv');
    var ajv = new Ajv(); // options can be passed, e.g. {allErrors: true}
    ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-07.json'));
    var validate = ajv.compile(schema);

    let json;
    try {
      json = JSON.parse(jsonString);
    } catch (err) {
      alert('Invalid json: ' + err);
    }
    if ( json != null ) {
      var valid = validate(json);
      if (!valid) console.log(validate.errors);

      const message = (valid ? "It's good!" : "Not good: " + validate.errors);
      alert('Validation: ' + message);
    }
  }
}
```

**Validation result, data AFTER validation, error messages**

Validation: It's good!

**What results did you expect?**
expected error:   required key [price] not found
This is what the java library, everit-org/json-schema, returns.

**Are you going to resolve the issue?**
I don't have the expertise.

**Comment by epoberezkin** [comment]
See https://runkit.com/esp/5ae23d12d0320b001260cdb3

You must be running some old version that doesn't have if/then/else, as otherwise explicitly adding draft-07 meta-schema would throw an exception.

Also "id" should be "$id" in draft-07

**Comment by markcmueller** [comment]
Thanks for your help, Evgeny.  I can see that the code runs correctly in runkit.   Nevertheless the if/then/else logic is skill skipped when I run locally with an app I created using ‘npx create-react-app’.  Npm list shows only the latest version of ajv.



 npm list

/Users/Mark/React

├─┬ ajv@6.4.0

│ ├── fast-deep-equal@1.1.0

│ ├── fast-json-stable-stringify@2.0.0

│ ├── json-schema-traverse@0.3.1

│ └─┬ uri-js@3.0.2

│   └── punycode@2.1.0

├── json-loader@0.5.7

├─┬ json-pointer@0.6.0

│ └── foreach@2.0.5

├── json-schema@0.2.3

└── jsonschema@1.2.4



Off the top of your head can you think of anything that might be going wrong?   I’ve scoured the web for hours without finding a clue.



   Mark

**Comment by markcmueller** [comment]
FYI,


ajv test -s schema.json -d testjson.json –-invalid.   Works correctly.

Runkit works correctly.



But running using npm gives me:
Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"



Even though I can’t see how I could be getting the wrong version of ajv.



   Mark

**Comment by epoberezkin** [comment]
I suspect it may be related to https://github.com/epoberezkin/ajv/issues/708, which is npm issue with sub-dependencies. Maybe using yarn will help?

**Comment by epoberezkin** [comment]
Try this:

```javascript
require('ajv');
console.log(Object.keys(require.cache).filter(s => s.includes('ajv')))
```

After that you can check the version of Ajv in package.json in the folder where you get it from.

**Comment by epoberezkin** [comment]
Also, look at the full `npm ls` output - there can be two versions...

**Comment by markcmueller** [comment]
Thank you for all your help, Evgeney!   I have it working.  My problem was that I was using create-react-app and did not want to use yarn, but now it works.

   Mark
