### ISSUE TITLE
still problem with minifying uri-js

### ISSUE THREAD

**Issue by vankop** [ajv-validator/ajv#773]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.4.0

[Got same issue](https://github.com/epoberezkin/ajv/issues/749)

Any updates?

**Comment by vankop** [comment]
As described in [uri-js related issue](https://github.com/garycourt/uri-js/issues/24) you need to manually modify `node_modules/uri-js`. May be fix `uri-js` version will be good solution for now.

**Comment by epoberezkin** [comment]
See https://github.com/garycourt/uri-js/issues/24#issuecomment-377670307 for the workaround.

I don't see how it can be an issue that needs to be fixed here. The issue seems to be with the tooling that does minification, or, less likely, with uri-js.

**Comment by epoberezkin** [comment]
Duplicate of #749 - please add comments there instead of creating a new issue.
