### ISSUE TITLE
request: Way in which to force a property value

### ISSUE THREAD

**Issue by skn3** [ajv-validator/ajv#777]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.4.0

**JSON Schema**

```json

                "foo": {
                    "type": "string",
                    "set": "bar"
                },

```

In this example the value of property "foo" would always equal "bar".

I have created a custom keyword to achieve something similar, but as far as I can see there is no way to have this value always exist?

```javascript
    ajv.addKeyword('set', {
        type: ['number', 'integer', 'string', 'boolean', 'array', 'object', 'null'],
        compile: (schema, parentSchema) => {
            //set the value to whatever is specified in "schema". Warning: we have to "set" the property we are applying
            //this custom keyword to either required or have a default. If we dont do this then the value might not exist!
            //if the value does not exist exist, then we cant set it!
            return (data, dataPath, parentObject, propName, rootData) => {
                parentObject[propName] = schema;

                //always success
                return true;
            };
        },
        valid: true,
        errors: false,
        modifying: true,
    });
```

If in our schema we fail to make the property have a `default` or be `required` then the validation function (naturally) will never get called. In turn this means that the value wont be "set".

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv#assigning-defaults

**Comment by skn3** [comment]
Hey there thanks for replying. Although default value only works when the value does not already exist in the json. What if we want to override a value?

I could apply an enum to the property, but this will fail validation. What If I simply want to always force that property to be "1"?

Or does it fallback to default value when validation fails?

**Comment by skn3** [comment]
I have a use case where one might want this:

If property "mode" = "bad" then we force property "option" to "false".
else If property "mode" = "good" then we force property "option" to whatever is defined in json, or fallback to default "false".
