### ISSUE TITLE
throws instead of returning boolean

### ISSUE THREAD

**Issue by ORESoftware** [ajv-validator/ajv#779]
Honestly this is fairly unexpected..
I have this:

```js
try {
    const valid = ajv.validate(schema, data);
    console.log('is schema valid:', valid);
 }
 catch(err){
    console.error(err.message);
 }
```

looking the API, I didn't expect it to ever throw, only to return a boolean if the data matched the schema. If the schema is bad or data is bad it seems to throw.

So my question is, will `ajv.validate()` ever return false? When will it throw, and when will it return false? It makes no sense lol.

**Comment by epoberezkin** [comment]
ajv.validate will throw when the schema itself is invalid. It will return false when the data is invalid.

**Comment by ORESoftware** [comment]
tbh, perhaps a bad API decision, but it's too late, enjoying the library otherwise, thx

**Comment by epoberezkin** [comment]
The justification is the most common use case - server side validation with a set of static schemas. Invalid schemas should prevent application from starting - in the most common case you don't need to catch this exception.

**Comment by ORESoftware** [comment]
Got it, yeah I guess this usage is better:

```js
var ajv = new Ajv(); 
var validate = ajv.compile(schema);  // can throw
var valid = validate(data); // only returns boolean
```

as opposed to:

```js
var ajv = new Ajv(); 
ajv.validate(schema,data);
```
