### ISSUE TITLE
Assign default value when field type is invalid

### ISSUE THREAD

**Issue by gfirebasket** [ajv-validator/ajv#784]
Hi,

I'm trying to find the way to assign a default value when a field type is invalid.

var schema = {
  'type': 'object',
  'properties': {
		'foo': { 'type': 'string', 'default': '' },
		'zoo': { 'type': number, 'default': 0 }
  },
}

var data = { 'foo': 'test', 'zoo': 'test'}

var av = new Avj({ useDefaults: true });
var validate = av.compile(schema);
console.log(validate(data));  // false
console.log(data);  //  { 'foo': 'test', 'zoo': 'test'}

I want the result to be {'foo': 'test', 'zoo': 0}
the useDefaults: true option only works when the field is not there.

thanks,

**Comment by epoberezkin** [comment]
That’s how default is supposed to work, it will not change the existing property. You can achieve what you want with a custom keyword.
