### ISSUE TITLE
Hints for more complex custom keywords

### ISSUE THREAD

**Issue by niquola** [ajv-validator/ajv#79]
I would like to implement custom keyword, which allow to dispatch to different sub-schemas
based on value of some data attribute (for example data.type)

``` js
{schemaProperty: 'type',
 schemaMap: {
   Human: '#/definitions/Human',
   Hipster: '#/definitins/Hipster'}}
```

I've honestly spent half-day trying to do it by compile or inline, but definitely need your hints `how to make it work` :)

**Comment by epoberezkin** [comment]
Does `switch` from [v5 proposals](https://github.com/json-schema/json-schema/wiki/switch-%28v5-proposal%29) look like something that you need? Because it is coming soon :)

Otherwise you have two options. If you want to do with compiled keyword it is definitely simpler, the only downside is that you'll have functions calling functions... You simply need to compile subschemas into separate functions and conditionally call them. If you want to use inlined keyword that's more tough - you'll need to do the same as ajv does - recursively call code generator for each schema and inline this code in a switch. Not easy, but much faster validation.

The trick for compiling keyword here is in error reporting but all you have to do is to pass through dataPath that is passed as a second parameter to validating function (I need to document it probably)

The compile option is here:

```
ajv.addKeyword('schemaMap', {compile: function(schema, parentSchema) {
  var validators = {};
  // I am assuming there are schemas inside schemaMap,
  // if you need to pass refs just use `{$ref: "ref"}`
  for (var key in schema) validators[key] = ajv.compile(schema[key]);
  var keyProperty = parentSchema.schemaMapProperty; // up to you of course what to call it

  return function validate(data, dataPath) {
    var key = data[keyProperty];
    var v = validators[key];
    var valid = v ? v(data, dataPath) : true; // if no match, assume passed
    validate.errors = valid ? null : v.errors;
    return valid;
  };
}});
```

And it works: https://tonicdev.com/esp/56579a6ae505840c00c1953b

**Comment by epoberezkin** [comment]
I would say that your idea looks more like a JavaScript switch than v5 proposal

**Comment by niquola** [comment]
Thx, 

I've also terribly hacked it like:

``` js
inline: function (it, data){                                                                                                          
    var $data = 'data' + (it.dataLevel || '');                                                                                        
    var out = ""                                                                                                                      
    var pairs = []                                                                                                                    
    for(var k in data.schemas){                                                                                                       
        var $refVal = it.resolveRef(it.baseId, data.schemas[k], it.isRoot)                                                            
        $refVal =  $refVal.code || $refVal                                                                                            
        if ($refVal === undefined) {                                                                                                  
        throw new Error("Could not resolve" + data.schemas[k])                                                                        
        }                                                                                                                             
        pairs.push([k, $refVal])                                                                                                      
    }                                                                                                                                 
    var attrs = pairs.map(function(p){                                                                                                
        return p[0] + ':' + p[1];                                                                                                     
    }).join(',')                                                                                                                      
    return "(function(){ var ref = {" + attrs + "}[" + $data + ".resourceType]; "                                                     
        + " var res = ref("+ $data +", (dataPath || '')); "                                                                           
        + " vErrors = ref.errors;"                                                                                                    
        + " errors = ref.errors.lenght;"                                                                                              
        + " return true; })()" 
}
```

it's similar to v5/switch, but little narrowed :)
Is it good idea to submit it to v5 draft? Because, it looks useful.

**Comment by epoberezkin** [comment]
I think it should be a bit changed along the conventions... I'd put all the logic in one keyword and JSON pointer inside data instead of property name. E.g.:

```
{
    schemaSwitch: {
        switch: { $data: 'JSON pointer in data' },
        schemas: {
            Human: {...},
            Hipster: {...}
        }
    }
}
```

On the other hand it can be easily achieved with a combination of $data and $ref keywords so probably no need for this construct:

```
{
  id: 'http://myschemas.com/schema.json#',
  definitions: {
    schemas: {
      key1: { id: "key1", ...},
      key2: { id: "key2", ...}
    }
  }
  anyOf: [ { $ref: { $data: 'JSON path in data mapping to the key value } } ]
}
```

Although the first is clearer and will probably more efficiently compile.

**Comment by epoberezkin** [comment]
Re your inlined implementation, the whole point of it is to avoid using functions, you just have to use unique variable names...

**Comment by niquola** [comment]
Yes, $data would work.

Why not just

```
{
  id: 'http://myschemas.com/schema.json#',
  definitions: {
    schemas: {
      key1: { id: "key1", ...},
      key2: { id: "key2", ...}
    }
  }
  type: { $ref: { $data: 'JSON path in data mapping to the key value } 
}
```

?

**Comment by epoberezkin** [comment]
But type just checks type and this schema is invalid... You need to validate against schema.

**Comment by epoberezkin** [comment]
Actually the better way to express it without any custom keywords is:

```
{
  anyOf: [
    {
      properties: {type: {enum: ['Human'] }},
      ...
    },
    {
      properties: {type: {enum: ['Hipster'] }},
      ...
    }
  ]
}
```

**Comment by niquola** [comment]
In swagger spec i have found very similar idea:

`discriminator`     Adds support for polymorphism. The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. The property name used MUST be defined at this schema and it MUST be in the required property list. When used, the value MUST be the name of this schema or any schema that inherits it.
