### ISSUE TITLE
Duplicate required properties returns missing property error

### ISSUE THREAD

**Issue by swtarmey** [ajv-validator/ajv#795]
Using AJV 6.1.1

If I have the following schema:

```javascript
var loginSchema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "AuthenticationRequest",
  "title": "Authentication Request",
  "description": "Request body for an authentication request",
  "type": "object",
  "properties": {
    "provider": { "type": "string", "minLength": 2, "maxLength": 50 },
    "username": { "type": "string", "minLength": 2, "maxLength": 50 },
    "password": { "type": "string", "minLength": 7, "maxLength": 100 }
  },
  "required": ["provider", "username", "password"],
  "additionalProperties": false
};
var validateLoginSchema = ajv.compile(loginSchema);
```

if I send a body of the request with duplicate required properties:
```json
{
    "provider": "local",
    "username": "User A",
    "username": "User B",
    "username": "User C",
    "username": "User D",
    "username": "User E",
    "username": "User 1",
    "username": "User F",
    "username": "User G",
    "password": "password1"
}
```

The errors ajv gives back is:
```json
{
    "errors": [
        {
            "keyword": "required",
            "dataPath": "",
            "schemaPath": "#/required",
            "params": {
                "missingProperty": "provider"
            },
            "message": "should have required property 'provider'"
        },
        {
            "keyword": "required",
            "dataPath": "",
            "schemaPath": "#/required",
            "params": {
                "missingProperty": "username"
            },
            "message": "should have required property 'username'"
        },
        {
            "keyword": "required",
            "dataPath": "",
            "schemaPath": "#/required",
            "params": {
                "missingProperty": "password"
            },
            "message": "should have required property 'password'"
        }
    ]
}
```

I would expect an error stating something like duplicate required properties rather than missing properties as all the required properties actually are specified.

**Comment by epoberezkin** [comment]
There is no such thing as the duplicate properties in JS objects, later ones simply override previous property definitions. I think you may not be passing the object above to validateLoginSchema function, you may be passing something else. Could you please submit a working code sample to runkit.com?

**Comment by swtarmey** [comment]
Seems you are correct.  On runkit it works fine when I define the object passed to validate.  The only difference I see is that in my code I am passing req.body to the validate method that is coming on the post.  Thanks for the quick response.

**Comment by epoberezkin** [comment]
req.body can be an empty object - do you have a parser?

**Comment by swtarmey** [comment]
Should have done more investigating prior to posting here.  That specific API call mistakenly specified the body content as text instead of JSON.  That was the problem.  Sorry to waste your time man.
