### ISSUE TITLE
Caching limit and strategy

### ISSUE THREAD

**Issue by bugventure** [ajv-validator/ajv#8]
Hey, just wanted to say nice work on the performance improvements! It's great to see there's no upper limit in how fast a JSON validator for node can go. Caching the validator code internally is great and I guess does the trick for the benchmarks out there.

I was wondering, do you plan on introducing some caching configuration? A limit on the size/number of cached validator code, maybe together with some policy for purging stale validators (e.g. least recently used)? That would help a great deal in large-scale projects with lots of schemas, or when schemas are dynamically generated and can change a lot.

Keep up the good work!

**Comment by epoberezkin** [comment]
Thank you :) Your jsen was great help too - I've spend quite some time analysing and comparing the code generated by it and imjv.

You are right, there is still some potential for speeding it up, maybe +25-50% I guess. But each step gives less return and more risky. I think you know it first hand. I've found using regexp replaces with generated code for some last step optimisations quite efficient and easier than introducing more conditions in code generation.

Benchmarks are not affected by caching actually, they are using precompiled functions anyway.
I wasn't thinking about the setup with multiple dynamic schemas, I haven't encountered such a use case. Can be added as an option with some LRU eviction I think (or even using set-associative cache I did recently - https://github.com/epoberezkin/sacjs) :) Or at least as an api to purge a schema from the cache - if they are used in other schemas they are referenced internally anyway, so there is no risk removing it.

I was more concerned about correct handling of referenced schemas, resolution scope changes, inline resolutions - that was what prompted me to create ajv in the first place (before I got hooked into benchmarks :). I couldn't find the one that was correctly handling all the cases when I started working on this - https://github.com/JSONScript/jsonscript . Actually I still have two ref resolution issues to resolve - #1 and #2.

**Comment by bugventure** [comment]
Yeah, dereferencing and scope resolution is a pain. I guess there are several reasons this problem is not addressed in a good way in any of the high-profile JSON validators today:
1. The spec is vague, lacks detailed explanations and better use cases.
2. It kinda seem unintuitive to the average programmer who deals with schemas and JSON validation.
3. It's tightly coupled with remote reference fetching, a problem the bulk of JSON validators have put out of scope, as it deals with making HTTP requests.
4. I still haven't seen a viable real-world use case for scope dereferencing to date.

Actually, your current work seems to go as far as any JSON validator has gone in terms of proper scope resolution.

**Comment by epoberezkin** [comment]
Thanks :)

You are right - I also think that the resolution scope change is not really necessary - the spec could've been simpler by saying there is one id per file, all internal references should be JSON pointers. Spec has actually got decent examples of scope change and inline resolution, but it doesn't make it any simpler to implement, particularly for generated code.

On the other hand any complex and recursively defined data-structure (tree/graph) will lead to many interlinked schemas in multiple files. So maybe for these complex structures these features make it a bit easier.

By the way, I'd love to hear what you think about JSONScript when you have a moment.

**Comment by epoberezkin** [comment]
I think any specific caching strategy is out of scope, so I've implemented an option to pass an instance of any cache (see readme) and also `removeSchema` method.
