### ISSUE TITLE
how to use conditional

### ISSUE THREAD

**Issue by jhonny111s** [ajv-validator/ajv#800]
I have two properties if "A" exists requires "C" but if B === "Device2", C is not required. I'm confused since I do not know how to do a conditional without it being too big

**"ajv": "^6.0.0",**

```javascript
 allOf: [{
      if: {
        properties: {
          A: {
            const: 'device1',
          },
        },
      },
      then: {
          if: {
            properties: {
              B:{
                not: {
                  const: 'device2'
                }
              },
            },
          },
          then: {
            required: [
              'C',
            ],
          },
        },

    },
]

```

if there were another property on which c depends, this structure would not be readable.

which can be the best solution to use conditionals with the validator

**Comment by epoberezkin** [comment]
In this case you can merge both conditions into the same "if", but conditionals can indeed get bulky - so you can use $refs to put them in definitions. I'd say it's the question for StackOverflow or JSON-Schema org, as it's not ajv specific.
