### ISSUE TITLE
Support for v5 $data keyword

### ISSUE THREAD

**Issue by niquola** [ajv-validator/ajv#81]
:+1:

**Comment by epoberezkin** [comment]
One day... That's not trivial and will increase the code size twice. Not sure it's worth it, particularly for the browser. Probably should be a separate bundle with $data support. That $data is not a keyword, it's a part of data that can be used in place of any value/schema, so compiled code will have to interpret the schema in such places. A simple solution is to compile the whole schema every time if it has $data, but it's extremely inefficient.

**Comment by epoberezkin** [comment]
Given that there is no need to support `$data` for such keywords as `properties` and `items`, and wherever the schema is needed, it is quite easy actually.

`$data` will be supported for the following keywords:
- [x] multipleOf
- [x] maximum
- [x] exclusiveMaximum
- [x] minimum
- [x] exclusiveMinimum
- [x] maxLength
- [x] minLength
- [x] pattern
- [ ] additionalItems (boolean) - ?
- [x] maxItems
- [x] minItems
- [x] uniqueItems
- [x] maxProperties
- [x] minProperties
- [x] required
- [ ] additionalProperties (boolean) - ?
- [x] enum
- [x] format
- [x] formatMaximum
- [x] formatMinimum
- [x] exclusiveFormatMaximum
- [x] exclusiveFormatMinimum
- [ ] patternGroups maximum/minimum
- [x] constant

**Comment by naturalethic** [comment]
This does not appear to work with `constant`.  I'm using version 3.0.3.  My case is thus:

``` livescript
    secret:
      min-length: 6
      max-length: 64
    secret-repeat:
      constant:
        $data: '1/secret'
```

I receive no validation error if `secret-repeat` does not match `secret`.  There is no unit test that I can see for using `$data` with `constant`.

**Comment by epoberezkin** [comment]
That's the test: https://github.com/epoberezkin/ajv/blob/master/spec/v5/%24data/constant.json

I will have a look why it's not working

**Comment by epoberezkin** [comment]
1. Your schema is incomplete - they should be inside "properties". Maybe that's how you do it...
2. It's minLength and maxLength
3. Maybe you expect the value in "secret-repeat" to match the schema in "secret"? That's not how it works then. $data puts the value of secret into constant, so it only requires the properties to be equal in this case.
4. Do you use "v5" option?

That's the working example: https://tonicdev.com/esp/56840ca4b7ce7b0d00e6f573

**Comment by naturalethic** [comment]
First, thank you so much for the time spent on this.
1. Yes, that's just a snippet, it is under `properties`.
2. I'm using https://github.com/gkz/LiveScript
3. I meant they should have the same value, as your example demonstrates.
4. Nope!  Because the documentation here https://github.com/epoberezkin/ajv#options says it is defaulted true.

So, I turned that option on and my original code works without changes.

Again, thanks a ton for looking into it.  Does this project have a donation account I can put a couple dollars in?

**Comment by epoberezkin** [comment]
Indeed, in the defaults... It was never the intention. Thanks for spotting.

**Comment by epoberezkin** [comment]
@naturalethic if you're still interested to support ajv development :), there is a bounty to implement custom error reporting: https://www.bountysource.com/issues/30029477-custom-error-messages

**Comment by naturalethic** [comment]
Hey thanks.  Added $5.

**Comment by epoberezkin** [comment]
Thank you! I am hoping somebody will do it at some point :)
