### ISSUE TITLE
typings bug: TypeScript typings are off for ajv.compile()

### ISSUE THREAD

**Issue by ORESoftware** [ajv-validator/ajv#813]
I am following the basic example in README:

```js
var Ajv = require('ajv');
var ajv = new Ajv(); // options can be passed, e.g. {allErrors: true}
var validate = ajv.compile(schema);
var valid = validate(data);
```

I am seeing this error in my editor:

![screenshot from 2018-06-25 14-55-24](https://user-images.githubusercontent.com/11139560/41877907-dfcd0a7c-7887-11e8-9c90-4b71c46ff154.png)

**Comment by ORESoftware** [comment]
For reference here are the options that I do see:

![screenshot from 2018-06-25 14-58-55](https://user-images.githubusercontent.com/11139560/41878014-511d093e-7888-11e8-8805-13e8ea45dc69.png)

**Comment by ORESoftware** [comment]
crap, I forgot to create a new instance of `Ajv()`. my fault.
but perhaps `compile` can be a static method on `ajv`, idk.

**Comment by epoberezkin** [comment]
> but perhaps compile can be a static method on ajv, idk.

Only if some instance is pre-created, it needs options etc. that are per instance.
