### ISSUE TITLE
Pseudo error of missing required property.

### ISSUE THREAD

**Issue by Domvel** [ajv-validator/ajv#816]
### schema is invalid: data should have required property 'version', but version does exist.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.5.2

**JSON Schema**

```json
{
  "$id": "http://json-schema.org/draft-06/schema#",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "com.schema.example",
  "type": "object",
  "properties": {
    "version": {
      "title": "Version",
      "description": "File version.",
      "type": "string",
      "enum": ["1.0"]
    },
    "list": {
      "title": "List",
      "description": "Just a list.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/List"
      }
    }
  },
  "required": ["version"],
  "definitions": {
    "List": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "Just a name.",
          "type": "string"
        },
        "value": {
          "title": "Value",
          "description": "Just a value.",
          "type": "number"
        }
      },
      "required": ["name", "value"]
    }
  }
}
```

**Sample data**

```json
{
  "$schema": "./my-example.schema.json",
  "version": "1.0",
  "list": [{
    "name": "First item",
    "value": 123
  }, {
    "name": "Seconds item",
    "value": 456
  }]
}
```

**Your code**
Snippet of a async-function in typescript. 
`http` comes from `import { HttpClient } from '@angular/common/http';` and `get` returns a json object in this case.

```typescript
// Load
const config = await this.http.get('assets/data.json').toPromise();
const schema = await this.http.get('assets/data.schema.json').toPromise();

// Validate (important code)
const ajv = new Ajv();
const validate = ajv.compile(schema);
const valid = validate(config);

console.log(valid, validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
schema is invalid: data should have required property 'version'
```

**What results did you expect?**
`version` exists. What's the problem? It should work. VS Code and online validators validates this successfully to valid. The `required` field for the items of the list property works in ajv.
Also if I change `enum` by `const`, `required: ["version"]` does not work with ajv.

**Are you going to resolve the issue?**
When I remove the `required` property from the schema for the `version` property, it works.

**Setup**
Using ajv in typescript on ionic (angular).

**Comment by epoberezkin** [comment]
Could you please submit a minimal code sample without I/O to runkit.com? I believe the problem is not in ajv, but having it in runkit would help to isolate the issue.

**Comment by epoberezkin** [comment]
Ok, the problem is that you are not using $id and $schema correctly. The error you see is logged during ajv.compile call when the schema is validated against itself, it requires property version but doesn’t contain it. Confit never gets validated, because an invalid schema throws exception.

**Comment by Domvel** [comment]
@epoberezkin Thanks for your analysis. I added `$id` because ajv 6.x does not work without this property. In previous versions and all other for me known validators does not requires it. I expected that the `$schema` property is enough. 

If I remove `"required": ["version"]` from the schema, it works. This required field is for the data properties not for the scheme. I do not understand. And why is `$id` required?

**Comment by epoberezkin** [comment]
draft-06 meta-schema needs to be added separately - see the docs.

**Comment by epoberezkin** [comment]
@Domvel Please review JSON schema spec and ajv docs. $schema is the id of the meta-schema. When you add the schema that has the same $id as the $schema, it is validated as a document against itself - that's what meta-schema is. All you have to do is either to remove $schema (then it will be draft-07 by default), or change $schema to the URI of draft-07 meta-schema, or to add draft-06 meta-schema to ajv instance. It is explained in the docs on the very top of readme file.
