### ISSUE TITLE
Can ajv be used in frontend?

### ISSUE THREAD

**Issue by Nadav-Ruskin** [ajv-validator/ajv#817]
Howdy,

I want to verify a json produced by a form on the client side. When I try to load ajv I get "require is not defined" which as I understand means the  library is not meant to be run on the client side.

I thought of using djv, which does work on the browser, but its documentation seems lacking.

**Comment by epoberezkin** [comment]
Yes, it is can be used in the browser. You have to either bundle ajv together with your app (e.g. with webpack), or to use a supplied browser bundle either from npm package or via cdn.js The require will work, or you can use a global Ajv, if you use bundle.

**Comment by Nadav-Ruskin** [comment]
I kept getting errors trying to bundle the library. But a simple install using `npm` had a file ready at `dis\ajv.bundle.js`. I'm posting this for future users, this is probably the easiest way.
