### ISSUE TITLE
It's not possible to use a default metaschema with custom keywords

### ISSUE THREAD

**Issue by jonganc** [ajv-validator/ajv#819]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.5.2.

**Ajv options object, JSON Schema, Sample data**

See code example below.

**Your code**

```javascript
const _ = require('lodash');
const Ajv = require('ajv');
const jsonSchema = require('ajv/lib/refs/json-schema-draft-07.json');

const customMeta = _.cloneDeep(jsonSchema);
_.merge(customMeta, {
  $id: 'custom',
  $schema: 'custom',
  properties: {
    customKeyword: {
      debug: true
    }
  }
});

const ajv = Ajv({
  meta: customMeta // comment me out
});

ajv.addKeyword('debug', {
  validate() {
    console.log('Debug called');
    return true;
  }
});

// ajv.addMetaSchema(customMeta);

ajv.compile({
  $schema: 'custom',
  customKeyword: true,
});
```

**What results did you expect?**

Should print `Debug called`. If you comment out the line with `comment me out` and uncomment the commented line, `Debug called` is printed.

**Are you going to resolve the issue?**

Not sure. I don't have a good feeling for the architecture of the code and this seems like potentially a non-trivial issue.

**Possible workarounds**

One could always manually include `$schema` but this is non-optimal, especially since you would also have to include it in `macro` properties and maybe other places. Possibly monkey-patching `Ajv.compile` to include `$schema`?

**Use case**

I am using `removeAdditional`. I want to define keywords which test several properties, e.g. a keyword `dateRange` which looks at properties `start`, `end` and checks that `start` is before `end`. Ideally, I don't want to have to always to have to write `{ dateRange: true, properties: { start: {}, end: {} } }` since this is redundant. Thus, I would like to add a keyword to `dateRange` in the metaschema to add `start`, `end` to properties.

**Comment by jonganc** [comment]
It might be worth explaining the use case for this.

I am using `removeAdditional`. I want to define keywords which test several properties, e.g. a keyword `dateRange` which looks at properties `start`, `end` and checks that `start` is before `end`. 

Ideally, I don't want to have to always to have to write
```
{ 
    dateRange: true,
    properties: {
        start: {},
        end: {} 
    }
}
```
since this is redundant. Thus, we would like to add a keyword to `dateRange` in the metaschema to add `start`, `end` to properties.

It seems to work fine except for the issue with the default schema.

**Comment by epoberezkin** [comment]
Everything seems to be working ok, console.log will only execute when this keyword is used in validation, and in your example it is not - you don’t validate against a schema with a custom keyword (as meta-schema simply has schema for it and doesn’t use it as a keyword).

Also see hyper-schema for the example how meta-schema should be extended at the moment - simply adding it to properties of meta-schema is not enough (although it has nothing to do with what you see as a problem).

**Comment by jonganc** [comment]
I don't understand. If I define the metaschema after I've defined the custom keywords and then manually specify `$schema`, everything seems to work how I want. Am I going to run into some problem with this? (I can't find an example of hyper-schema that seems relevant).

In particular, because of how `removeAdditional` works (the ultimate use-case), this seems to be the only way to add automatically properties to schema.

**Comment by epoberezkin** [comment]
> I don't understand. 

Which part?

**Comment by epoberezkin** [comment]
Merging the property will work ok, it would still iterate subschemas. By hyper-schema I meant this: https://github.com/epoberezkin/ajv/blob/master/spec/remotes/hyper-schema.json

So please ignore the second part of what I wrote :) Did you understand the first one?

**Comment by jonsemail4** [comment]
I think so. I guess, because of how AJV (or JSON-schema?) is set up, it doesn't make sense to define the default meta-schema after custom keywords are defined, which would be necessary if you wanted it to obey those keywords.
So, I think I'll just add a shim to automatically specify my custom meta-schema when calling `compile`.

**Comment by jonganc** [comment]
I think so. I guess, because of how AJV (or JSON-schema?) is set up, it doesn't make sense to define the default meta-schema after custom keywords are defined, which would be necessary if you wanted it to obey those keywords.
So, I think I'll just add a shim to automatically specify my custom meta-schema when calling compile.

**Comment by epoberezkin** [comment]
Closing it - I understand there is no issue here.
