### ISSUE TITLE
if/then/else & error messages

### ISSUE THREAD

**Issue by delmu** [ajv-validator/ajv#820]
Hi experts,

I would like to customize some error message in the if/then/else logic. But it seems that ajv is not support that or I make some mistakes. Does anyone know how to do it? Thanks in advance.

Following is a example...

Example:

```javascript
const schema_motor = {
  if: {
    properties: {
      dad_phone_number: {
        type: 'number',
      }
    },
    errorMessage: {
      properties: {
        dad_phone_number: 'Dad\'s phone number is incorrect.'
      }
    }
  },
  then: true,
  else: {
    properties: {
      mum_phone_number: {
        type: 'number'
      }
    },
    errorMessage: {
      properties: {
        mum_phone_number: 'Mum\'s phone number is incorrect.'
      }
    }
  }
}
```

@epoberezkin

**Comment by epoberezkin** [comment]
@delmu sorry, I am not sure what code you run and what results you expect - could you please submit a working code sample to runkit.com together with the expected results in comments?

**Comment by epoberezkin** [comment]
Closing here, relates to custom keyword errorMessage defined in ajv-errors. If it’s still a problem it should be submitted with full code sample to ajv-errors repo.
