### ISSUE TITLE
enum can't be nullable?

### ISSUE THREAD

**Issue by jhonny111s** [ajv-validator/ajv#824]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
current ajv= 6.0.0 
last ajv= 6.5.0  same error

My error category can be null or one element of enum. why don't work correctly?

**JSON Schema**

```json
var schema = {
  "title": "test",
  "events": [
    "test",
  ],
  "properties": {
    "error_category": {
      "type": ["string", "null"],
      "enum": [
        "test1",
        "test2",
        "test3",
      ],
    },
}
```

**Sample data**

```json
data = {
"event": "test",
 "error_category": null
}

```

**Your code**

**Validation result, data AFTER validation, error messages**

```
ERROR: [ { keyword: 'enum',
    dataPath: '.error_category',
    schemaPath: '#/properties/error_category/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values' } ]

```

**What results did you expect?**
i expected an Ok status.

**Are you going to resolve the issue?**

i believe that works with bellow code but why not with above?:

```
error_category: {
      oneOf: [
        { type: 'null' },
        {
          type: 'string',
          enum: [
            'test1',
            'test2',
            'test3',
          ],
        },
      ],
    },
```

**Comment by epoberezkin** [comment]
> i believe that works with bellow code but why not with above?

Because they are not equivalent. Your second schema only applies “enum” when the data is a string, while the first one always applies “enum”, and null value is not in the list.

The values in “enum” can be anything, it is not limited to strings, so “enum” with `null` (value, not string) in it would work (and, strictly speaking, “type” would not be necessary).

**Comment by epoberezkin** [comment]
Also I’m not sure what `”events”:[“test”]` does in the schema.

**Comment by mnavon** [comment]
Tnx @epoberezkin 
Solution example:
` "error_category": {
      "type": ["string", "null"],
      "enum": [
        null,
        "test1",
        "test2",
        "test3",
      ],
    },`

**Comment by Bgshanoams** [comment]
Test4?

На нд, 8.11.2020 г., 20:04 ч. mnavon <notifications@github.com> написа:
