### ISSUE TITLE
minLength makes the property required

### ISSUE THREAD

**Issue by roccomuso** [ajv-validator/ajv#826]
```javascript
{
  '$id': '/mySchema',
  'type': 'object',
  'properties': {
    name: {type: 'string'},
    uri: {type: 'string', minLength: 15}
  },
  'required': ['name']
}
```
`uri` is required. (Getting error: `should NOT be shorter than 15 characters`)

Is this an intended behavior?

**Comment by epoberezkin** [comment]
I think the problem is somewhere else - could you please post the whole code sample to runkit.com?

See https://runkit.com/esp/5b5f5f9932208d0013b23b1d

My guess is that in your case property "uri" is present and is an empty string.

**Comment by roccomuso** [comment]
Yeah my fault.
It was an empty string.

Thanks
