### ISSUE TITLE
Don't validate or use `id` for compile

### ISSUE THREAD

**Issue by blakeembrey** [ajv-validator/ajv#83]
Probably a breaking change, so maybe just an option for now. Basically from https://github.com/mulesoft-labs/osprey-mock-service/issues/12, buggy JSON schema IDs cause issues and users think the tool is broken. Maybe have an option to skip unique validation and never register into AJV when using `compile`?

**Comment by epoberezkin** [comment]
Yes, let's do it. I suggest `duplicateIds` with the value `ignore` to log error instead of throwing exception. `compile`, `validate` and `validateSchema` should be affected, but not `addSchema`

**Comment by epoberezkin** [comment]
Not `validateSchema` of course, it doesn't do any checks on `id` field

**Comment by epoberezkin** [comment]
Added option `addUsedSchema` in c99d6751adca80869ae92567685e21e80cd4ea6e (3.3.0). It's `true` by default but I'll make it `false` by default in the next major version.
