### ISSUE TITLE
Attribute $id require URL with protocol part

### ISSUE THREAD

**Issue by kevin-leptons** [ajv-validator/ajv#830]
### Ajv version
6.5.2

### Problem

A JSON schema has attribute **$id**. ajv just works when **$id** is specifies by URL format such as `protocol://domain/path` . If protocol part is removed then ajv does not works, it always provide `can't resolve reference...`.

### Question

Why don't remove protocol part from **$id** attribute?. protocol part is unnecessary.

**Comment by epoberezkin** [comment]
@kevin-leptons could you please post a specific code sample that doesn't work as you expect (ideally please post it to runkit.com)?

**Comment by kevin-leptons** [comment]
Hello,

Sorry for delay. I have two examples

- [ajv-specifed-protocol](https://runkit.com/kevin-leptons/ajv-specified-protocol)
- [ajv-not-specified-protocol](https://runkit.com/kevin-leptons/ajv-does-not-specified-protocol)

First example specifics protocol part in URI of $id of schema. Ajv works as well. 
Second example does not specifics protocol part of $id of schema. Ajv will throw Error.

**Comment by epoberezkin** [comment]
You didn’t just remove the protocols, you replaced full URIs with relative paths.
see 
https://runkit.com/esp/5b6f190d26ab0400120a1cd9
