### ISSUE TITLE
Is there a way to generate a template object for the provided json schema?

### ISSUE THREAD

**Issue by AnirKulk** [ajv-validator/ajv#831]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript


```

**JSON Schema**

```json


```

**Sample data**

```json


```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
I think you want this: https://github.com/json-schema-faker/json-schema-faker
