### ISSUE TITLE
IPv4 address matches both `ipv4` and `hostname` formats

### ISSUE THREAD

**Issue by GochoMugo** [ajv-validator/ajv#832]
Please see this [SO answer](https://serverfault.com/a/638270) for more information.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.5.2, yes

**Ajv options object**

```javascript
{}
```

**JSON Schema**

```json
{
    "type": "object",
    "properties": {
        "host": {
            "type": "string",
            "oneOf": [
                { "format": "hostname" },
                { "format": "ipv4" }
            ]
        }
    }
}
```

**Sample data**

```json
{
    "host": "127.0.0.1"
}
```

**Your code**

* Gist: https://gist.github.com/GochoMugo/ee1363ca2274743ca612d2393819a723
* Runkit: https://runkit.com/gochomugo/ajv-issue/1.0.1

```javascript
var Ajv = require("ajv");

ajv = new Ajv({
});

var schema = {
    "type": "object",
    "properties": {
        "host": {
            "type": "string",
            "oneOf": [
                { "format": "hostname" },
                { "format": "ipv4" }
            ]
        }
    }
};

var data = {
    "host": "127.0.0.1"
};

var validate = ajv.compile(schema);

console.log(validate(data));
console.log(validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
false
[ { keyword: 'oneOf',
    dataPath: '.host',
    schemaPath: '#/properties/host/oneOf',
    params: { passingSchemas: [Array] },
    message: 'should match exactly one schema in oneOf' } ]
```

**What results did you expect?**

1. It only matches `ipv4` format, and **not** `hostname` format

**Are you going to resolve the issue?**

No, maybe. :man_shrugging:

**Comment by binarymist** [comment]
Same issue for me.

**Comment by sambauers** [comment]
Technically speaking, a relative (local network) hostname can be a number, e.g. `12004` might resolve to `12004.local`. But it would be fairly unusual (although not impossible or even invalid) for `1.2.3.4` to want to resolve to `1.2.3.4.local`.

This is a "hostname" format check, not a "fully qualified domain name" check. And since the RFC for hostname definition is pretty open, it could be argued that the current regex is too restrictive.

https://tools.ietf.org/html/rfc2181#section-11
> any binary string whatever can be used as the label of any resource record

**Comment by GochoMugo** [comment]
I agree with @sambauers. This is an issue about the semantics of `hostname` format.

| sample | `hostname` | `ipv4` |
| --- | --- | --- |
| `"example.com"` | yes | no |
| `"example"` | yes | no |
| `"127.0.0.1"` | yes | yes |
| `"127"` | yes | no |
