### ISSUE TITLE
exclusiveMinimum is supposed to be boolean. Error: "exclusiveMinimum should be number"

### ISSUE THREAD

**Issue by gaoxiaomumu** [ajv-validator/ajv#835]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript
6.5.2

```

**JSON Schema**

```json

var schema = {
  "type": "object",
  "title": "empty object",
  "properties": {
    "field_1": {
      "type": "integer",
      "minimum": 1,
      "maximum": 4,
      "exclusiveMinimum": true
    }
  }
}
```

**Sample data**

```json

var data = {
  "field_1": 2
}
```

**Your code**

```javascript
const Ajv = require('ajv');
var ajv = new Ajv({schemaId: 'auto'});
ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'));



```

**Validation result, data AFTER validation, error messages**

```
 else throw new Error(message);
         ^

Error: schema is invalid: data.properties['field_1'].exclusiveMinimum should be number

```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by head1328** [comment]
This error occurs if you try to validate an openapi v3 file using the boolean option exclusiveMinimum or exclusiveMinimum.

Tested with 6.10.0

**Comment by epoberezkin** [comment]
exclusiveMinimum must indeed be a number in draft7. If you want to use draft4, you need to explicitly specify meta schema
