### ISSUE TITLE
Property 'missingProperty' does not exist on type 'ErrorParameters'.

### ISSUE THREAD

**Issue by ionutmiftode** [ajv-validator/ajv#843]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

the latest version

**Ajv options object**

```javascript

const ajv = new Ajv({ allErrors: true });
```

**JSON Schema**

```json

{
  "$schema": "http://json-schema.org/draft-07/schema",
  "required": ["content", "className", "classNames"],
  "type": "object",
  "properties": {
    "content": {
      "name": "content",
      "type": "string",
      "title": "content",
      "description": "some content to render",
      "example": "content valid example"
    },
    "className": {
      "name": "className",
      "type": "string",
      "title": "className",
      "description": "some className content to render",
      "example": "className content valid example"
    },
    "classNames": {
      "name": "classNames",
      "type": "string",
      "title": "classNames",
      "description": "somed classNames content to render",
      "example": "classNames content valid example"
    }
  }
}
```

**Sample data**

```json
{"content": "some content"}

```

**Your code**

```javascript
const valid = ajv.validate(schema, parsedConfig);
            if (!valid && ajv.errors) {
                ajv.errors.forEach(err => {
                    const prop = err.params.missingProperty;
                    const schemaProp = schema[prop];
                    console.error(`required property "${prop}" is missing.
                    description: ${schemaProp.description}
                    example: ${schemaProp.example}`);
                });
            }

```

**Not reaching the validation, the build using typescript fails**

```
TS2339: Property 'missingProperty' does not exist on type 'ErrorParameters'.
  Property 'missingProperty' does not exist on type 'RefParams'.

```

**What results did you expect?**
the code should build with no errors.

**Are you going to resolve the issue?**
I can resolve it. the solution is to normalize all the interfaces used for `type ErrorParameters` e.g. `RefParams | LimitParams | AdditionalPropertiesParams | ...`.

Please let me know if I can submit a PR

**Comment by epoberezkin** [comment]
missingProperty is defined in some error types. What do you mean by “normalise”?

**Comment by epoberezkin** [comment]
@blakeembrey I would appreciate if you could help me understand the problem. This property is defined in [some of interfaces](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts#L280) and `error.params` is defined as ErrorParameters that is [defined as a union](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts#L261). Yet when I use `error.params.missingProperty` I get the same error too. Typescript version I have is 3.0.1.

**Comment by ionutmiftode** [comment]
Sorry for the late reply. by normalize I meant that each `ErrorParameters` interface e.g. `RefParams`, `LimitParams` etc should all have the same properties, but marked as optional which are not relevant.
A better solution should be to export all the `ErrorParameters` interfaces to use them as type guards.
https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by archfz** [comment]
I also have this issue. I had no choice but to force the type: (v.params as Ajv.RequiredParams)

**Comment by henit** [comment]
I have the same issue. Any suggestions?

**Comment by epoberezkin** [comment]
@henit I am probably going with the approach suggested in #1090 by @torifat, with local type Error parameter type definitions in each keyword source file.

**Comment by epoberezkin** [comment]
in v7-alpha
