### ISSUE TITLE
"No Error" error message when using schema with external $ref

### ISSUE THREAD

**Issue by hokiedsp** [ajv-validator/ajv#844]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v6.5.3

**Ajv options object**

```javascript
{ schemas: [optSchema, splitOptsSchema] }
```

**JSON Schema**
Schema 1: ```optSchema```
```json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://example.com/schemas/opt.json",
  "type": "string",
  "minLength": 1
}
```
Schema 2: ```splitOptsSchema```
```json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://example.com/schemas/opts.json",
  "type": "array",
  "items": {
    "$ref": "opt.json"
  }
```
Schema 3: ```singleOptsSchema```
```json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://example.com/schemas/optsOne.json",
  "definitions": {
    "opt": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "array",
  "items": {
    "$ref": "#/definitions/opt"
  }
```

**Sample data**

```json
["test", ""]
```
This data fails due to the empty 2nd element

**Your code**
```javascript
// Run validation with ```splitOptsSchema```
let valid = ajv.getSchema("https://example.com/schemas/opts.json")(data);
if (!valid) console.log("Split schema: ", ajv.errorsText());

// Run validation with ```singleOptsSchema```
valid = ajv.validate(singleOptsSchema, data);
if (!valid) console.log("Single schema: ", ajv.errorsText());
```

[Full script on runkit.com](https://runkit.com/hokiedsp/ajv-issue) (It does not run on runkit.com due to ajv missing a dependent package)
**Validation error messages**
```
Split schema:  No errors
Single schema:  data[1] should NOT be shorter than 1 characters
```

**What results did you expect?**
The split-file schema error should be exactly the same as the single-file schema

**Are you going to resolve the issue?**
I could, but I need some pointers as I'm not familiar with the innards of ajv.

**Comment by epoberezkin** [comment]
The problem is that you are using different validation API. ajv.validate assigns errors to ajv instance, using validation function does not (it assigns errors to a property of validation function, so you need to pass errors to ajv.errorsText explicitly).

https://runkit.com/esp/5b7a70d4405b650012ab4311

**Comment by hokiedsp** [comment]
Ah, I see. Thank you for the clarification.
