### ISSUE TITLE
Property "allowedValue" does not exist on type "ErrorParameters"

### ISSUE THREAD

**Issue by JaredProske** [ajv-validator/ajv#848]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
the latest version

**Ajv options object**
N/A since this is a types issue

**JSON Schema**
N/A since this is a types issue

**Sample data**
N/A since this is a types issue

**Your code**

```javascript
 private getExpectedConstant(error: Ajv.ErrorObject) {
    return error.params.allowedValue;
 }
```
**Error**
"allowedValue" does not exist on type "ErrorParameters"

**What results did you expect?**
There should be a ConstParams type that is included in the exported ErrorParameters type.
```
interface ConstParams {
    allowedValue: any;
 }
```
The readme explicitly states this exists and I see it in the raw results but I cannot compile my typescript that tries to access it.

```
const - property allowedValue pointing to the value (the schema of the keyword).
```

**Are you going to resolve the issue?**
If I have time I can submit a pull request

**Comment by epoberezkin** [comment]
Duplicate of #843

**Comment by JaredProske** [comment]
@epoberezkin I don't think this is an explicit duplicate of 843.  These are different interfaces.

**Comment by epoberezkin** [comment]
Different interface but the same problem. Any solution that is chosen for #843 would address this issue as well.
