### ISSUE TITLE
mon,js

### ISSUE THREAD

**Issue by HP41** [ajv-validator/ajv#853]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript


```

**JSON Schema**

```json


```

**Sample data**

```json


```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Please submit with all info
