### ISSUE TITLE
Remove unvalidated data

### ISSUE THREAD

**Issue by molteber** [ajv-validator/ajv#859]
Hello,
I'm trying to remove unvalidated properties from the data during validation.
See sample input, validation schema and expected output to grasp what I'm trying to do.
I can only get it to remove additional properties which is not listed in the schema, or failing validations, but not validations which is not run.

So, is it possible somehow? 

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v6.5.3

**Sample data**

```json
{
	"valid-field": true,
	"unvalidated-field": true
}
```

**Sample schema i've tried**

```json
{
	"type": "object",
	"properties": {
		"valid-field": {
			"type": "boolean"
		}
	},
	"required": ["valid-field"],
	"if": {
		"properties": {
			"valid-field": {
				"const": false
			}
		}
	},
	"then": {
		"properties": {
			"unvalidated-field": {
				"type": "boolean"
			}
		},
		"required": ["unvalidated-field"]
	}
}
```

**Validation result I'm trying to get**

```json
{
	"valid-field": true,
}
```

**Comment by epoberezkin** [comment]
you can use "else" branch and make it additional / failing there.

**Comment by molteber** [comment]
Hmm, tried this with `else` and `additionalProperties` which gives me the wanted result in the issue

```json
{
  "$id": "http://example.com/schema.json",
  "type": "object",
  "properties": {
    "valid": {
      "type": "boolean"
    }
  },
  "required": [
    "valid"
  ],
  "if": {
    "properties": {
      "valid": {
        "const": false
      }
    }
  },
  "then": {
    "properties": {
      "unvalid": {
        "type": "boolean"
      }
    },
    "required": [
      "unvalid"
    ]
  },
  "else": {
    "properties": {
      "valid": {}
    },
    "additionalProperties": false
  }
}
```

If I did not list `properties` inside `else`, it would remove all the fields. But if i listed the ones i wanted to keep they stayed. Is this the expected behavior, even if the property have been described outside the conditions?

**Comment by epoberezkin** [comment]
Yes, that’s how “additionalProperties” keyword defined in the spec - it is “shallow”.

**Comment by molteber** [comment]
Alright :+1: 
It sort of makes sense when you think about it, just needs to wrap your head around it.
Thanks for the quick feedback!
