### ISSUE TITLE
propertyNames with empty schema prevents validation of all keywords to be validated after it.

### ISSUE THREAD

**Issue by JasonCust** [ajv-validator/ajv#861]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v6.5.3

**Ajv options object**

```javascript
const options = {
  // allErrors: true,
  coerceTypes: 'array',
  ownProperties: true
};
```

**JSON Schema**

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "test.json",
  "type": "object",
  "additionalProperties": {
    "type": "array",
    "items": {"type": "string"},
    "uniqueItems": true
  },
  "propertyNames": {}
}
```

**Sample data**

```json
{"foo": "abc"}
```

**Your code**

https://runkit.com/embed/xz907r79pjza

```javascript
const Ajv = require('ajv');
const assert = require('assert').strict;
const ajv = new Ajv(options);
const validate = ajv.compile(schema);

test({foo: 'abc'}, {foo: ['abc']});

function test(data, expected) {
  const valid = validate(data);

  if (valid) {
    try {
      assert.deepStrictEqual(data, expected);
    } catch (e) {
      console.log(e);
    }
  }
}
```

**Validation result, data AFTER validation, error messages**

```
// Validation succeeds
{foo: 'abc'}
```

**What results did you expect?**
For the value to be coerced to an array. `{foo: ['abc']}`

It appears this issue only occurs if `propertyNames ` is an empty object. If anything is set (e.g. `{enum: ['foo']}`) then it will coerce the value to an array. OR another approach with the empty `propertyName` object is to enable the `allErrors` options.

**Are you going to resolve the issue?**
Not at this time.

**Comment by epoberezkin** [comment]
It's a wider issue - additionalProperties keyword is not validated at all in this case.
https://runkit.com/esp/5ba7615233bc340012478b31

And actually no other keywords after propertyNames as per https://github.com/epoberezkin/ajv/blob/master/lib/compile/rules.js#L16 are validated.
