### ISSUE TITLE
ajv string type | Question

### ISSUE THREAD

**Issue by seeden** [ajv-validator/ajv#869]
Hi 

I am trying to use custom error messages with ajv-errors.
Everything is working fine with errorMessage as string but when I try to replace it with String object I get this error message.

```
keyword schema is invalid: data/minLength should be string
```

Next code does not work
```js
const schema = {
      type: 'object',
      properties: {
        id: {
          type: 'integer',
          minLength: 1,
          errorMessage: {
            minLength: new String("test"),
          },
        },
    }
```

I know you will tell me that I need to use just "test" or String("test") instead of new String("test") but here is my use case:

I am using translated messages which are translated on the fly at the end of whole request and no during the validation process. I do not want to send locale as parameter to each function and I am not able to use global variable because I have multiple requests with different locales.
I want to do:

```js
class TranslateString extends String {
  constructor(message: string, params?: Object) {
    super(message);

    this.params = params;
  }

  translate(t): string {
    return t(this.message, this.params);
  }
}

const schema = {
      type: 'object',
      properties: {
        id: {
          type: 'integer',
          minLength: 1,
          errorMessage: {
            minLength: new TranslateString("Name {name} is too short.", { name: 'Adam' }),
          },
        },
    }
};
```

I am translating errors at the end of request and I need to know which message is translation string. Other standard "strings" I am not translating.

Let me know if it is possible somehow allow custom type for errorMessage. 
Thank you very much @epoberezkin

**Comment by seeden** [comment]
anyway I tried to override instanceof keyword but without any success. I have tried to override Error instead of String as well. Maybe this will be better idea. Allow string or Error object. I can create something like:

```js
class TranslateError extends Error {
  constructor(message: string, params?: Object) {
    super(message);

    this.params = params;
  }

  translate(t): string {
    return t(this.message, this.params);
  }
}

const schema = {
      type: 'object',
      properties: {
        id: {
          type: 'integer',
          minLength: 1,
          errorMessage: {
            minLength: new TranslateError("Name {name} is too short.", { name: 'Adam' }),
          },
        },
    }
};
```

**Comment by epoberezkin** [comment]
To me extending standard classes is not a JS way - JS was never good at supporting standard class extension. Also a string and an instance of String class are two different things in JS. Python can be more your thing tbh (I don’t try to be sarcastic, I just mean that it has much fewer quirks than JS). JS way would be to have a separate class hierarchy with some normal string property. I don’t think supporting Sting instances is something that any JS library should worry about...

**Comment by seeden** [comment]
Hi @epoberezkin.

Maybe there is some miss understanding. I totally understand difference between string and String class.
Actually I need to use different type in errorMessage instead of string and I am not able to do that.
Is it possible to use custom class or object instead of string as errorMessage?
If yes can you add some example? 

This questions is more related to ajv-errors.

Thanks
