### ISSUE TITLE
Validate only returning first error

### ISSUE THREAD

**Issue by myrddraall** [ajv-validator/ajv#870]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.5.4

**Ajv options object**

```javascript

```

**JSON Schema**

```json
{ 
   "properties": { 
       "email": { "type": "string" },
       "password": { "type": "string" },
        "firstName": { "type": "string" },
        "lastName": { "type": "string" } 
    },
   "required": [ "email", "password", "firstName", "lastName" ],
   "type": "object",
   "definitions": {} 
}
```

**Sample data**

```json
{}

```

**Your code**

[https://runkit.com/myrddraall/5bc4e37afa061f0012b5bf75](https://runkit.com/myrddraall/5bc4e37afa061f0012b5bf75)

```javascript
const ajv = new Ajv();
ajv.validate(schema, data);
console.log(ajv.errors);

```

**Validation result, data AFTER validation, error messages**

```
[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'email' },
    message: 'should have required property \'email\'' } ]
```

**What results did you expect?**

I would expect an error for each of the required fields rather than only email

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
That’s a feature, see options.
