### ISSUE TITLE
relative $ref not resolving

### ISSUE THREAD

**Issue by terazus** [ajv-validator/ajv#877]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.5.4
When trying to resolved relative $ref, the algorythm returns there error:
```
MissingRefError: can't resolve reference identifier_info_schema.json# from id https://w3id.org/dats/schema/person_schema.json#
```

**JSON Schema**

see: https://raw.githubusercontent.com/datatagsuite/schema/master/person_schema.json
the json input being a bit big, i don't want to overflow this thread

**Your code**

code is available here: https://runkit.com/terazus/5bdb2df069012300129cdc73

I'm either doing something wrong in my code, or in my schemas, i guess.

Ty

**Comment by epoberezkin** [comment]
I assume the expectation is that this this schema should be loaded from URL https://w3id.org/dats/schema/identifier_info_schema.json#? The standard usage is to add all necessary schemas using addSchema. Ajv does not do any I/O unless you use compileAsync method and loadSchema option (see https://github.com/epoberezkin/ajv#asynchronous-schema-compilation)
