### ISSUE TITLE
$data refrenece - how is it supposed to work?

### ISSUE THREAD

**Issue by rklueber** [ajv-validator/ajv#881]
Hello,

I try to use the data reference feature.

I started from a node:10 docker
Dockerfile
```
FROM node:10
WORKDIR /home
ADD *.json /home/
RUN apt-get update
CMD ["bash"]
```

started the docker and nstalled ajv-cli on the bash via

```
npm install -g epoberezkin/ajv-cli
...
+ ajv-cli@1.0.0
added 40 packages from 60 contributors in 8.285s
```

I have two jsons from the example

i.json
```
{
    "smaller": 5,
    "larger": 7
}
```

s.json
```
{
    "properties": {
        "smaller": {
        "type": "number",
        "maximum": { "$data": "1/larger" }
        },
        "larger": { "type": "number" }
    }
}
```

The schema seems not allowing the data reference.
```
# ajv -s s.json -d i.json
schema s.json is invalid
error: schema is invalid: data.properties['smaller'].maximum should be number
#
```

It seems the epoberezkin/ajv is not used when installing epoberezkin/ajv-cli.

Any hint anyone?

Thanks for your help.

Regards
Ralf

**Comment by epoberezkin** [comment]
You need $data option.

**Comment by rklueber** [comment]
Hello epoberezkin,

Thanks for the fast reply. I am really sorry to bother you. How do I pass the data option on the cli?

I tried all the following without success
```
ajv validate -s s.json -d i.json --data
ajv validate -s s.json -d i.json --$data
ajv validate -s s.json -d i.json --data true
ajv validate -s s.json -d i.json --$data true
```

I feel really silly, but I dont get it.

**Comment by epoberezkin** [comment]
@rklueber there is indeed a bug in ajv-cli that needs to be fixed - it is supposed to pass `--data` as `{$data: true}` to ajv and it does not

**Comment by duboislaurent** [comment]
Hello,

Is this issue resolved in the latest ajv-cli version available?

Thanks

**Comment by epoberezkin** [comment]
it's released in ajv-cli
