### ISSUE TITLE
required keyword for empty string

### ISSUE THREAD

**Issue by soulcm** [ajv-validator/ajv#885]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript
{
  allErrors: true,
  jsonPointers: false, 
  coerceTypes: true,
  validateSchema: false
}

```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "test": {
      "type": "string"
    }
  },
  "required": ["test"]
}

```

**Sample data**

```json
{
  "test": ""
}

```

**Your code**

```javascript
  ajv.validate(schema, data)
  console.log(ajv.errors)

```

**Validation result, data AFTER validation, error messages**

```
  the ajv.erros is null

```

**What results did you expect?**
 how can I validate the empty string to use required keyword, or another solution

**Comment by epoberezkin** [comment]
You can use other JSON schema keywords, e. g. minLength for strings.

**Comment by m-jahanbakhsh** [comment]
Unfortunately, if someone fills the field with spaces it will be valid because space counts as a character.
you can use addKeyword method for check isNotEmpty
