### ISSUE TITLE
Format: url doesn't validate urls containing double dashes

### ISSUE THREAD

**Issue by vlamic** [ajv-validator/ajv#886]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.5.4

**Ajv options object**

```javascript
{
        format: 'full',
        removeAdditional: 'all',
        coerceTypes: true
}
```

**JSON Schema**

```json
{
"type": "object",
"properties": {
    "url": { "type": "string", "format": "url" }
 }
}

```

**Sample data**

```json
{ "url": "https://g--t.com" }
```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```
            {
                "keyword": "format",
                "dataPath": ".url",
                "schemaPath": "#/properties/url/format",
                "params": {
                    "format": "url"
                },
                "message": "should match format \"url\""
            }
```

**What results did you expect?**
Valid URL

**Are you going to resolve the issue?**
No, sorry.

**Comment by epoberezkin** [comment]
@vlamic "url" format is not part of JSON schema spec, you could use "uri" instead, it passes: https://runkit.com/esp/5bff85e6b9b5eb001267e991

According to [these test cases](https://mathiasbynens.be/demo/url-regex) double-dash is supposed to fail - not quite sure why. @gajus?

**Comment by gajus** [comment]
https://stackoverflow.com/questions/16468309/can-domain-name-have-two-continuous-hyphens

> 4.2.3.1. Hyphen Restrictions
>
> The Unicode string MUST NOT contain "--" (two consecutive hyphens) in the third and fourth character positions and MUST NOT start or end with a "-" (hyphen).

However, it seems that you are able to register domain names such as http://a--a.com/

Related:

https://twitter.com/kuizinas/status/1068112490557595648

**Comment by vlamic** [comment]
BTW: The validator fails not only with double dashes in the domain name, but also in a subdomain. @gajus @epoberezkin

**Comment by gajus** [comment]
@epoberezkin This shouldn't be closed, though.

http://b--b.com/ is a valid domain name.

**Comment by epoberezkin** [comment]
Why it is marked as invalid in the test cases then I wonder?...

**Comment by gajus** [comment]
> Why it is marked as invalid in the test cases then I wonder?...

I think it is mistake. Let's see what Mathias replies to that tweet that I have shared.

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv/issues/898#issuecomment-447596417, #907
