### ISSUE TITLE
Add yup to performance charts

### ISSUE THREAD

**Issue by MeenaAlfons** [ajv-validator/ajv#888]
**What version of Ajv you are you using?**
6.5.5

**What problem do you want to solve?**
Add [yup](https://github.com/jquense/yup) to performance benchmark charts

**Will you be able to implement it?**
No

**Comment by krnik** [comment]
Yup is terribly slow, so it'd end up at the bottom of a chart anyways. Is there any reason to gather all slow libraries?

**Comment by epoberezkin** [comment]
It’s not a JSON schema validator; so it’s a wrong benchmark. Also the benchmark is maintained in json-schema-benchmark
