### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by mcollina** [ajv-validator/ajv#889]
In the last v6.6.0 release, there is a missing file:

``` 
Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/travis/build/fastify/fastify/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Module.replacementCompile (/home/travis/build/fastify/fastify/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.<anonymous> (/home/travis/build/fastify/fastify/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/travis/build/fastify/fastify/node_modules/table/src/makeConfig.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

See https://travis-ci.org/fastify/fastify/jobs/461147572
and https://github.com/fastify/fastify/issues/1281.

**Comment by dbenchi** [comment]
I have this issue when I do  `yarn install`. When I do `npm install` I do not have this issue

**Comment by dbenchi** [comment]
Other solution is to add a manual resolution in the package.json:
```
  "resolutions": {
    "ajv": "6.5.5"
  },
```

then you can use both `yarn` or `npm`

**Comment by epoberezkin** [comment]
So it appears that several libraries depended on an internal file that was not public (I think) and that became one-line wrapper around fast-deep-equal long time ago... Who would have thought :)

@mcollina @gajus could you please replace require(“ajv/lib/compile/equal”) with require(“fast-deep-equal”)? I won’t be able to revert for several hours I am afraid.

**Comment by epoberezkin** [comment]
Even if I do revert, it’s worth replacing anyway.

**Comment by ikobe-zz** [comment]
@epoberezkin just  revert it temporary

**Comment by csvan** [comment]
Temporary workaround for this is to add this to your `package.json`:

```
  "resolutions": {
    "ajv": "6.5.4"
  }
```

**Comment by ybiquitous** [comment]
Is this `resolutions` workaround for `yarn` only? Not `npm`?

**Comment by csvan** [comment]
@ybiquitous it works for both

**Comment by ybiquitous** [comment]
Is there `resolutions` description in NPM docs?
https://docs.npmjs.com/files/package.json

**Comment by whevether** [comment]
@mcollina 
The file was removed. Manual replacement
http://www.pike.com/node_modules/localtunnel/node_modules/ajv/lib/compile/equal.js

**Comment by ybiquitous** [comment]
I try `resolutions` via `npm` command:

`Dockerfile`:

```Dockerfile
FROM node:10

RUN apt-get -y update && apt-get -y install jq

RUN mkdir foo && \
	cd foo && \
	npm init -y && \
	cat package.json | jq '. + {resolutions: {ajv: "6.5.4"}}' > package.json.new && \
	mv package.json package.json.old && \
	mv package.json.new package.json && \
	cat package.json | jq . && \
	npm i stylelint && \
	echo '{}' > .stylelintrc && \
	echo 'a{}' > a.css

RUN npx stylelint a.css
```

Run `docker build .` command on terminal:

```
$ docker build .
...
{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "resolutions": {
    "ajv": "6.5.4"
  }
}
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ stylelint@9.9.0
added 369 packages from 202 contributors and audited 2446 packages in 12.956s
found 0 vulnerabilities

Removing intermediate container 4f7a327976d5
 ---> c5752e2203f1
Step 4/4 : RUN npx stylelint a.css
 ---> Running in 73ad541c7eff
npx: installed 369 in 5.828s
Cannot find module 'ajv/lib/compile/equal'
The command '/bin/sh -c npx stylelint a.css' returned a non-zero code: 1
```

The result fails. Is `npm` support `resolutions` really? Or my verification is bad something?

**Comment by xiaohuoni** [comment]
Temporary workaround for this is to add this to your package.json:
it works for  yarn and npm
```
  "resolutions": {
    "ajv": "@6.5.4"
  }
```

**Comment by patelmanjeet** [comment]
resolutions not support by npm.  

For npm you need to "ajv": "6.5.4" dependencies in package.json

**Comment by ybiquitous** [comment]
My final `Dockerfile`.

For `resolutions` approach `yarn` works, but `npm` does **NOT** work. 😢 

```Dockerfile
FROM node:10

RUN apt-get -y update && apt-get -y install jq

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN mkdir foo
WORKDIR foo

RUN npm init -y && \
	cat package.json | jq '. + {resolutions: {ajv: "6.5.4"}}' > package.json.new && \
	mv package.json package.json.old && \
	mv package.json.new package.json && \
	cat package.json | jq . && \
	npm install stylelint && \
	# yarn add stylelint && \    #<=== It works!
	npm ls ajv && \
	echo '{"rules":{}}' > .stylelintrc && \
	echo 'a{}' > a.css

RUN ./node_modules/.bin/stylelint a.css
```

### `npm` case:

![image](https://user-images.githubusercontent.com/473530/49214712-8ef3e900-f40a-11e8-84ed-788989253c53.png)

**Comment by ybiquitous** [comment]
### Temporary workaround summary

Add a below field to your `package.json`.

#### Yarn

```json
{
  "resolutions": {
    "ajv": "6.5.5"
  }
}
```

#### NPM

```json
{
  "dependencies": {
    "ajv": "6.5.5"
  }
}
```

**Comment by epoberezkin** [comment]
I will revert, it’ll go out in the next major version. Give me an hour - just landed :)

**Comment by epoberezkin** [comment]
Good old release and run routine...

**Comment by RomainMuller** [comment]
Yeah - I was looking at the problem in `table` (gajus/table#83), and it appears that this update _needs_ to be a major version, as it otherwise could break validators generated from previous versions of the library (using `ajv-cli`, in the case of `table`).

**Comment by hiendv** [comment]
@epoberezkin Publish v6.6.1 please.

**Comment by epoberezkin** [comment]
Yes, that’s why I probably kept it at the time... it’s published

**Comment by epoberezkin** [comment]
So “equal.js” is public as it turned out... 
https://github.com/epoberezkin/ajv/issues/889#issuecomment-442784790

Sorry

**Comment by hiendv** [comment]
Everyday we break semver :laughing: 
J/K

**Comment by ybiquitous** [comment]
@epoberezkin Thank you so much!
