### ISSUE TITLE
How can I use multiple types with refs? | Question

### ISSUE THREAD

**Issue by kostyazgara** [ajv-validator/ajv#892]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

Default from [fastify](https://www.fastify.io/)

**User JSON Schema**

```js
{
	$id: 'user',
	type: 'object',
	properties: {
		_id: { type: 'string' },
		email: {
			type: 'string',
			format: 'email',
		},
		firstName: { type: 'string' },
		lastName: { type: 'string' },
		avatar: {
			anyOf: [
				'photo#',
				{ type: 'string' }
			]
		},
	},
},
```
**Photo JSON Schema**
```js
{
	$id: 'photo',
	type: 'object',
	properties: {
		_id: { type: 'string' },
		type: { type: 'string' },
		src: { type: 'string' },
		description: { type: 'string' },
	},
},
```
**Sample data with avatar as string**

```js
{
  _id: '5c0071ce836313265b815dfc',
  email: 'test@test.com',
  firstName: 'testFirstName',
  lastName: 'testLastName',
  avatar: 'someId',
}

```

**Sample data with avatar as object**

```js
{
  _id: '5c0071ce836313265b815dfc',
  email: 'test@test.com',
  firstName: 'testFirstName',
  lastName: 'testLastName',
  avatar: {
    src: 'some source'
    type: 'image',
    description: 'some description'
  },
}

```
**Validation result, data AFTER validation, error messages**

```
{
   _id: '5c007471c8d84b3dcc49b629',
  email: 'test@test.com',
  firstName: 'testFirstName',
  lastName: 'testLastName',
  avatar: null,
}
```

**What results did you expect?**

I expect that my schema will validated as well, when I send a string he should return string, when I send object he should return object with validated properties

**Are you going to resolve the issue?**
Many various with anyOf, oneOf, allOf and type: ['string', 'object']

**Comment by epoberezkin** [comment]
It’s difficult to understand the issue without a self contained code sample, ideally without fastify. It can be worth submitting to fastify.
