### ISSUE TITLE
Failed url validation

### ISSUE THREAD

**Issue by janjilek** [ajv-validator/ajv#898]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.6.1, yes

**Ajv options object**

```javascript
{ allErrors: true, removeAdditional: true }
```

**JSON Schema**

```javascript
{
  type: "object",
  properties: {
    link: { type: "string", format: "url" } 
  }
}
```

**Sample data**

```javascript
{
  link: "http://test.com?ref=text"
}
```

**Validation result, data AFTER validation, error messages**

```
 { keyword: "format", dataPath: ".link", schemaPath: "#/properties/link/format", message: "should match format "url"" }
```

**What results did you expect?**
The url should pass.

**Comment by epoberezkin** [comment]
It looks like it wants it to be "http://test.com/?ref=text".
The format defined in JSON schema spec is "uri", not "url" by the way - it passes for `"http://test.com?ref=text"`:

https://runkit.com/esp/5c155fe539f6fa0013639b3f

**Comment by epoberezkin** [comment]
I think the correct approach is to deprecate "url" format in this package and remove it in the next major version, as it is not part of JSON schema spec.
Either "uri" or a custom definition of "url" format can be used.

**Comment by epoberezkin** [comment]
#907

**Comment by janjilek** [comment]
I know, that JSON schema spec is uri, but your library supports url as well. It's really hard to force people to add / to the url, if the url without / is perfectly valid. Uri format will pass quite a lot of cases and it's not suited well for urls. I would agree with removing url format from this packag, because it's really confusing. I am using custom url format definition right now.
