### ISSUE TITLE
Docs are not clear at all on how to create a schema

### ISSUE THREAD

**Issue by toymachiner62** [ajv-validator/ajv#901]
I'm just trying to get started with AJV. Was doing good until I looked for documentation on creating a schema. The docs are so unclear and all over the place when it comes to schema.

I looked in the table of contents for "schema", found nothing. 

Can you update the README so that it's much clearer on creating schema's?

**Comment by epoberezkin** [comment]
JSON Schema specification is out of scope of ajv docs, it has the reference of keywords though. There are links to the specification in readme https://json-schema.org

**Comment by toymachiner62** [comment]
Ok great links to annotations and https://json-schema.org.. what if someone is still trying to get started and doesn't know to click the links to figure it out? 

Someone told me to check out ajv for validating my api payloads and I did, got lost, made this suggestion, it got closed, i moved on from ajv.

One thing i learned a long time ago is to literally take a developer that doesn't know this space and watch them fumble through the docs. That will tell you how clear they are.
