### ISSUE TITLE
Set `mode` to handle `readOnly` and `writeOnly`

### ISSUE THREAD

**Issue by kromol** [ajv-validator/ajv#909]
**What version of Ajv you are you using?**
6.6.2

**What problem do you want to solve?**
I want to use the same schema for request and response by leveraging `readOnly`and `writeOnly` properties.

**What do you think is the correct solution to problem?**
One possible solution would be to add new configuration option `mode` that would set `Ajv` mode to either `DEFAULT` (like it works now) or `READ`(in this mode all `readOnly` items should be taken into account) or `WRITE`(should validate `writeOnly` stuff)

**Will you be able to implement it?**
Probably

**Comment by epoberezkin** [comment]
It is much easier to do with schema pre-processing step outside of ajv, when a single schema is used to construct READ, WRITE and DEFAULT schema.

**Comment by hildoer** [comment]
My mind is kind of blown that such an obviously good feature request for AJV has been dismissed with "it is much easier to [rebuild a substantial portion of AJV outside of AJV to apply a check on something AJV is almost nearly doing already.]"

🤷🏽‍♂️
