### ISSUE TITLE
Weird "constant" message

### ISSUE THREAD

**Issue by trikadin** [ajv-validator/ajv#91]
The message for "constant" keyword error is like `data.prop should be equal to one of values`. As I understand, it's because of enum-based nature of "constant")

**Comment by epoberezkin** [comment]
Yes, that's the reason. At the moment `constant` is defined as "macro" keyword, so it simply replaces `constant` with `enum`. I plan to re-write it as "inline" keyword.

**Comment by trikadin** [comment]
@epoberezkin I've seen [your proposition](https://github.com/json-schema/json-schema/wiki/Custom-error-messages-%28v5-proposal%29) about the "errors" keyword -- why you don't support it? Waiting for something?

**Comment by epoberezkin** [comment]
I've just added this idea yesterday if you've noticed :) I support it... To support it in ajv it has to become higher priority than other unsupported features - it will take some time.

The motivation for the keyword is that that many bug reports and feature requests I saw were related to people trying to generate custom error messages based on some information from the schema. So I thought that having errors explicitly defined in the schema would make their life much easier.

Some feedback from other people there would be useful too.

**Comment by trikadin** [comment]
> I've just added this idea yesterday if you've noticed :) 

Oh, sorry, I thought I didn't notice it before. 

> The motivation for the keyword is that that many bug reports and feature requests I saw were related to people trying to generate custom error messages based on some information from the schema. So I thought that having errors explicitly defined in the schema would make their life much easier.

Totally agree --  for example, "not" keyword, in fact, says nothing about the reason of fail)
