### ISSUE TITLE
issues using "if/then/else" to set dynamic type based on const

### ISSUE THREAD

**Issue by jabiinfante** [ajv-validator/ajv#910]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.6.2

**Ajv options object**
  schemaId: '$id',
  removeAdditional: 'all',
  useDefaults: true,
  allErrors: true

```javascript


```

**JSON Schema**

```json

const schema = {
  "type": "object",
  "properties": {
    "propType": {
      "enum": [
        "n",
        "s"
      ]
    },
    "prop": {
      "if": { "properties": {"propType": {"const": "n"}},
        "then": {
          "type":"number"
        },
        "else": {
          "type": "string"
        }
    },

    }
  },
  "required": [
    "propType",
    "prop"
  ]
};

```

**Sample data**

```json
{
  "badprop": 45,
  "propType": "n",
  "prop": "hi"
};

```

**Your code**

```javascript

var validate = ajv.compile(schema);
var valid = validate(data);
if (!valid) console.log(validate.errors);
else console.log('OK!');
console.log(data)

```

**Validation result, data AFTER validation, error messages**
I was expecting an error, everything was fine:

```
OK!
{ propType: 'n', prop: 'hi' }

```

**What results did you expect?**
[ { keyword: 'type',
    dataPath: '.prop',
    schemaPath: '#/properties/prop/type',
    params: { type: 'number' },
    message: 'should be number' } ]
{ propType: 'n', prop: 'hi' }

**Are you going to resolve the issue?**
I'll keep on trying, no success so far.

**Comment by epoberezkin** [comment]
`"if": { "properties": {"propType": {"const": "n"}}` applies to `data.prop. propType`, not to `data.propType` as you probably need.

**Comment by jabiinfante** [comment]
Yes, you are right @epoberezkin 

I finally got it working as I expected using this schema:

```json
{
  "type": "object",
  "properties": {
    "propType": {
      "enum": [
        "n",
        "s"
      ]
    },
    "prop": {}
  },
  "if": {
    "properties": { "propType": { "const": "s" } }
  },
  "then": {
    "properties": {
      "prop": {
        "type":"string"
      }
    }
  },
  "else": {
    "properties": {
      "prop": {
        "type": "number"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "propType",
    "prop"
  ]
};
```

Hope it helps someone!

Thanks for such an amazing software @epoberezkin :clap: :clap: :clap:
