### ISSUE TITLE
New option to enhance default functionality

### ISSUE THREAD

**Issue by B-Teague** [ajv-validator/ajv#912]
**What version of Ajv you are you using?**
6.6.1

**What problem do you want to solve?**
When submitting HTML forms, the url-encoded data will send empty strings for fields that are empty.  The joi library has functionality to default empty strings, and I would like to see this same functionality implemented in ajv.

> However, if you want to specify a default value in case of empty string you have to use a different pattern: Joi.string().empty('').default('default value').

**What do you think is the correct solution to problem?**
Maybe a new enum for the useDefaults option like "emptyValues".  The default logic needs to be modified to be executed for all properties regardless of the property's absence or current value if a default annotation is present in the schema for that property.  The default logic needs to mutate the data if the property is missing or has an "emptyValue" before being validated against the property format.

**Will you be able to implement it?**
Probably not, but I'd love to learn.

*Question*
Is it worth also enhancing defaults for null, empty array [], empty object {}, zero 0?

*Examples*
*Defaulting an empty string to a numeric value.*
```
{
   Product: "10mm Wood Screw",
   Quantity: ""
}
//Schema has default: 0 for Quantity
{
   Product: "10mm Wood Screw",
   Quantity: 0
}
```

*Defaulting a zero value to a different value*
```
{
   Model: "2018 Tesla Model S",
   BatteryCapacity: 0
}
//Default in schema is 85 kilowatt hours
{
   Model: "2018 Tesla"
   BatteryCapacity: 85
}
```

**Comment by B-Teague** [comment]
Also, what do you think about a new function that adds keywords to the default annotation to allow dynamic defaults?
addDefaultKeyword("_currentDate");

{
   Ticket: 12345,
   Date: ""
}

Date: {
   type: "string",
   format: "date",
   default: "_currentDate"
}

**Comment by epoberezkin** [comment]
Ok, so the option useDefaults should support the value “empty” to assign the default value to the property/item that is either absent (like it is now) or equal to an empty string, undefined or null.

I don’t think the use case justifies supporting any other values as “empty”. The change should be relatively straightforward, if you search for useDefaults you will see where it is used in code.

Types should be updated too.

There is dynamicDefaults is ajv-keywords already.
