### ISSUE TITLE
Error installing or unzipping data.js f on ajv package

### ISSUE THREAD

**Issue by dlokman** [ajv-validator/ajv#914]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6

**Ajv options object**

```javascript


```

**JSON Schema**

```json


```

**Sample data**

```json


```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**

Install ajv package from npm

**Are you going to resolve the issue?**

**Comment by dlokman** [comment]
Error installing or unzipping data.js from ajv package

**Comment by dlokman** [comment]
I get admin privileges error even though I’m a local admin

**Comment by dlokman** [comment]
I downloaded the ajv zip file from github and tried to unzip it but it fails due to data.js requiring admin privileges somehow

**Comment by epoberezkin** [comment]
There is not enough information to reproduce your issue. If anything, it may be a compatibility or installation issue - please resubmit using [installation template](https://github.com/epoberezkin/ajv/issues/new?template=installation.md).
