### ISSUE TITLE
coercion of nullable empty string

### ISSUE THREAD

**Issue by kapouer** [ajv-validator/ajv#919]
Using ajv 6.6.2, coerceType 'array'.

Schema:
```
type: 'string',
nullable: true,
format: 'a format that does not allow empty string, by the way'
```
What happens: Coercion rules keep the empty string.
What i'd like: Coercion rules converts empty string to null

However i totally understand that using anyOf[null, string] is a solution, but nullable documentation does not define coercion, so i suppose it's up to ajv to decide what's best, or even maybe to provide a coercion option (nullable first or last).

**Comment by epoberezkin** [comment]
Could you please post a minimal code sample, to runkit.com if possible? I don’t understand the issue.

**Comment by GUIEEN** [comment]
I had the exactly same issue like this

**Comment by epoberezkin** [comment]
I think I may understand the question. Coercion only changes the data in case it doesn’t pass validation with the type keyword. Empty string is a “string” - why it is expected that it would be coerced to null? Whether it passes validation is irrelevant from the point of view of this functionality.

Please bear in mind that type coercion is Ajv feature that is not part of JSON Schema spec.

**Comment by epoberezkin** [comment]
... nullable is also not part of JSON Schema spec - it’s an extension defined by OpenAPI spec, Ajv supports it for compatibility with OpenAPI tools. An equivalent JSON Schema syntax is `type: [‘string’, ‘null’]` (it wouldn’t trigger coercion too).

**Comment by kapouer** [comment]
I set up a format or a pattern that does not allow empty string,
so i expect the "" => null coercion to happen (because "" does not validate).
But as you state
> Coercion only changes the data in case it doesn’t pass validation with the type keyword

it cannot work like that.
Or could it, eventually ?

**Comment by epoberezkin** [comment]
Making coercion dependent on validation results is too complex (and even more indeterministic than it already is).

You need to use some compound JSON Schema keywords.

You may be able to achieve what you want with default: null and the option useDefaults: “empty”

**Comment by suryaabhi** [comment]
If it's not required to apply additional validations on an empty string, you can instead use `anyOf` along with `maxLength`

```javascript
{
    ....
    "anyOf": [ { "maxLength": 0 }, { "format": /*anything*/  } ],
    ....
}
```
