### ISSUE TITLE
Cannot find module './_limit'

### ISSUE THREAD

**Issue by woaixiangbao** [ajv-validator/ajv#921]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
My version of Ajv is 6.7.0.

In file node_modules/ajv/lib/dotjs/index.js

```javascript
  maximum: require('./_limit'),
  minimum: require('./_limit'),
```

but there is no _limit.js

so I had a error: (node:34683) UnhandledPromiseRejectionWarning: Error: Cannot find module './_limit'

**Comment by epoberezkin** [comment]
You probably installed from GitHub... Please resubmit the issue using installation template (the last one - it has suggestions how to resolve.
