### ISSUE TITLE
ajv Override Validation Functions

### ISSUE THREAD

**Issue by jaliph** [ajv-validator/ajv#926]
I have a requirement where I need to Override the String Validation Functions. I can't modify anything in the JSON Schema, as my product is dependant on it. 

Example, String can be null, but I can't add isNullable as a key in the JSONSchema as my product is dynamically generating it and using it. Is there a way where we can override the existing String Validation Function to accept String as Null also?? I'm sharing my current implementation.

Kindly help me on this. Excuse for my immaturity in raising this issue as I have some strict deadline to meet.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest version

**JSON Schema**

```json
"OriginalOrderId": {
      "title": "Order ID",
      "description": "Order ID",
      "display": {
        "name": "Original Order ID",
        "description": "Original Order ID",
        "required": false,
        "visible": true,
        "order": 6,
        "tags": [
          "OriginalOrderID",
          "originalorderid"
        ]
      },
      "type": "string"
    }
```

**Sample data**

```json

{ "OriginalOrderId": null }

```

**Your code**

```javascript
function validateString(str) {
  return _.isString(str) || str === null
}
ajv.addFormat('int32', validateString, ['string']);

var valid = ajv.validate(newSchema, value);
```

**Comment by epoberezkin** [comment]
This can (and should) be achieved by modifying the schema at any point (you could traverse the schema in code and replace all `type:'string'` with `type: ['string', 'null']` just before schema compilation)

**Comment by jaliph** [comment]
As already discussed, we are not able to modify the schema in any way. This is a crucial.

I know if we could modify the schema, it was straight forward, but could you help other wise in finding a solution.

**Comment by epoberezkin** [comment]
I am not sure why you are unable to modify the schema - it is a trivial thing to do in your code programmatically by traversing the schema and replacing each type:string with type:[string,null] - you could use JSON-schema-traverse (that ajv uses to traverse the schemas).

In any case, the logic of string validation will not be changed in ajv.

**Comment by jaliph** [comment]
As I had explained earlier, that we are consuming the JSONSchema in an intermediate step and can't modify that. Anyways thanks for this.

In case you find this relevant, and have a way in which we can override existing validation functions , it'll be of great help.
