### ISSUE TITLE
useDefaults: 'empty' for undefined values

### ISSUE THREAD

**Issue by akaNightmare** [ajv-validator/ajv#927]
**What version of Ajv you are you using?**
6.7.0
**What problem do you want to solve?**
According to the readme doc `With the option value "empty" properties and items equal to null or "" (empty string) will be considered missing and assigned defaults.` useDefaults: 'empty' should work only if value is `''` or `null`, but ajv creates a field/value even if in source object particular field does not exists
**What do you think is the correct solution to problem?**
do not create default value for undefined fields.

**Comment by epoberezkin** [comment]
It behaves as intended, the docs can be clarified a bit

**Comment by akaNightmare** [comment]
@epoberezkin is there any way to get behavior what is needed for me?

**Comment by epoberezkin** [comment]
You can probably prevent validation reaching default if the property is not present... Not sure I understand the use case. The idea of this option was to extend the previous “default” behaviour - I.e. treat property with empty string or null value as if this property not present.

**Comment by akaNightmare** [comment]
@epoberezkin the use case is:
```js
const Ajv = require('ajv');

const ajv = new Ajv({
    allErrors: true,
    coerceTypes: true,
    removeAdditional: false,
    useDefaults: 'empty',
});

const obj = { a: '' };

const comp = ajv.compile({
    type: 'object',
    properties: {
        a: { type: 'number', default: 0 },
        b: { type: 'number', default: 0 },
    },
});
comp(obj);
console.log(obj);
```

### Actual result:
`{ a: 0, b: 0 }`

### Expected result:
`{ a: 0 }` // b is absent in the source object and don't needed after validation

Thanks in advance

**Comment by epoberezkin** [comment]
I was asking about an actual use case, not about the code sample. The way `default: "empty"` is defined, it is useful as it can be used, e.g. both for form submissions when empty fields can be present as empty strings and for API calls when the properties will be absent. What is the use case of the above?

**Comment by akaNightmare** [comment]
@epoberezkin 
> API calls when the properties will be absent

I need to validate an object (from POST request). One thing what is needed to decline comparison with `undefined` properties only with `''` (empty string) and `null`. Why it's needed: in the code determined some business logic if one key is absent do not use another one, however, ajv creates a key with a default value, and it's to hard check if that key is passed through API or created by ajv.

**Comment by epoberezkin** [comment]
@akaNightmare you need to structure your schema differently to achieve it. The behaviour of the default keyword will not change to achieve what you describe.
