### ISSUE TITLE
dataPath is empty | version 2.5.0 | bug?

### ISSUE THREAD

**Issue by seeden** [ajv-validator/ajv#93]
Hi 

After validation each error has field named dataPath equal to empty string ('').
Is it feature or error ?

Thank you

**Comment by seeden** [comment]
I found the ans. 
It is feature. errorDataPath: 'property',

**Comment by epoberezkin** [comment]
`errorDataPath` option is created mainly for backwards compatibility, I wouldn't recommend using it for any other reason. Without it `dataPath` is the current level in data (`""` simply means top level). Depending on the keyword you are using you can get all the required information (missingProperty or additionalProperty) in `error.params`.

If you use `verbose` option there is also `error.data` that is the data currently validated. This `data` is consistent with `dataPath`. If you use option `errorDataPath: "property"` `data` and `dataPath` become inconsistent.

Will add it to readme...

**Comment by seeden** [comment]
Thank you for detailed explanation
