### ISSUE TITLE
When using compileAsync, only resolve $ref when needed.

### ISSUE THREAD

**Issue by svegalopez** [ajv-validator/ajv#938]
I am trying to use ajv as a validator of http request bodies.
The request body gets validated against a json-schema that has various NON-REQUIRED properties of type $ref. 
I would expect the validator to only resolve the $ref if the incoming http body has that property.
Otherwise it is making unnecessary requests to resolve the references because there is nothing to validate.

Example http body:
```javascript
{
  name: "samuel"
  email: "sam@email.com"
}
```

Example json-schema

```
{
  "id":"CreateUserRequest","
  type":"object","
  additionalProperties":false,
  "properties": {
      "name":{"type":"string"},
      "email":{"type":"string"},
      "roles":{"type":"array", "items":{"$ref":"Role"}}
      "labels":{"type":"array", "items":{"$ref":"Label"}}
      "tasks":{"type":"array", "items":{"$ref":"Taks"}}
      "teams":{"type":"array", "items":{"$ref":"Team"}}
  },
  "required":["name", "email"]
}
```
In this case I pass the loadSchema function to compileAsync.

```javascript
let ajv = new Ajv({ loadSchema: this.loadSchema });
```

and even though the input http body has none of the properties that need to be resolved, the loadSchema method gets called once for every $ref, even though its not necessary.

**Comment by epoberezkin** [comment]
Ajv compiles schema into javascript code that is executed during validation. So all schemas referenced in the schema you compile should be available at the time of schema compilation. For the most common use case of server side validation of API request bodies/parameters it give up to 100x performance and the schema needs to be compiled only once (that is if you don't create a new instance on every request, of course).

You could implement what you want by validating each property separately with a separate schema, in which case each schema would be compiled on demand. You can add all schemas to the instance with addSchema and retrieve them using getSchema - ajv compiles schemas lazily in this case, but each schema should be fully compiled - supporting partially compiled schemas would be very complex.

**Comment by svegalopez** [comment]
@epoberezkin  Thanks for the reply. Makes a lot of sense.
One more question if you don't mind.
If I use addSchema to add all referenced schemas, and I then use getSchema($id) to compile a validator lazily, will that validator get cached ? So If I then call getSchema for the same $id again, it wont compile it again ? 

Thanks for the great library!

**Comment by epoberezkin** [comment]
> If I use addSchema to add all referenced schemas, and I then I use getSchema($id) to compile a validator lazily, will that validator get cached ? So If I then call getSchema for the same $id again, it wont compile it again ?

Yes that is correct - it compiles only once - you can use Ajv instance to access all compiled validators.
