### ISSUE TITLE
Reduce ajv code / bundle size

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#940]
**What version of Ajv you are you using?**
6.8.1

**What problem do you want to solve?**
Browser bundle size

**What do you think is the correct solution to problem?**
Move functions/constants from shared template definitions into separate files (or reused templates)

**Plan**

- [x] Approve adding ajv-dist to cdnjs: https://github.com/cdnjs/cdnjs/issues/13315
- [x] Publish ajv-dist to npm
- [x] Submit PR  to update cdnjs to pull ajv bundles from ajv-dist https://github.com/cdnjs/cdnjs/pull/13316
- [x] Update ~~travis~~ script to publish ajv-dist to npm on every tag - done with GitHub action
- [x] Merge PR to update cdnjs to pull ajv bundles from ajv-dist https://github.com/cdnjs/cdnjs/pull/13316
- [x] Deprecate bundle (/dist) in this package
- [x] ~~Update docs with the new bundle URLs (or maybe the bundle URLs can stay? TBC - they will be the same)~~
- [x] in ajv 7.0 - remove bundles (/dist) from this package

**Comment by sindresorhus** [comment]
The install size is also bloated. Currently it's at 1.5 MB, which is a lot: https://packagephobia.now.sh/result?p=ajv

Users are complaining about it: https://github.com/sindresorhus/electron-store/issues/60

I'm not sure why `ajv` publishes both the lib and dist files, but that could probably be improved: https://github.com/epoberezkin/ajv/blob/d10720734d806fd25606dafd47b64e97ee7d1e7d/package.json#L8-L9

**Comment by epoberezkin** [comment]
@sindresorhus cdnjs.com makes bundles available via npm distribution... Probably the answer is to publish ajv-dist to cdnjs rather than ajv. It probably should be done in the next major version.

**Comment by epoberezkin** [comment]
See the TODO list above

**Comment by sindresorhus** [comment]
Thanks for the quick response. Your plan sound good to me. 👌

**Comment by epoberezkin** [comment]
v7-alpha has a smaller bundle size (120->100k minified)

**Comment by epoberezkin** [comment]
Ok, this is mostly done - bundles are now pushed to ajv-dist on releases, and ajv-dist to npm via workflows - as soon as cdnjs/cdnjs#13316 is merged (or maybe I need to create a new one) the bundles will be in cdnjs.

**Comment by epoberezkin** [comment]
The bundles for v7 are now available from cdnjs via ajv-dist
