### ISSUE TITLE
Run tests of some dependent packages against the new ajv tags

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#945]
E.g. ajv-keywords, webpack and eslint, to prevent issues like #941 or #889

**Comment by TheLarkInn** [comment]
@epoberezkin Appreciate it! If theres way's we can help also upstream provide support or feedback, please don't hesitate to do so!

**Comment by epoberezkin** [comment]
@TheLarkInn maybe you have any idea why it fails on `yarn unlink` on travis in this job (in the end of the log where it runs scripts/test-deps-release): https://travis-ci.org/epoberezkin/ajv/jobs/496636927

It does work locally.

Thank you!
