### ISSUE TITLE
Validate a part of the target document using a schema embedded in the target document

### ISSUE THREAD

**Issue by masaeedu** [ajv-validator/ajv#963]
Hello. I was trying to figure out whether I can model the following (simplification of my actual) use case with JSON schema:

schema.json

```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "input": { "$ref": "http://json-schema.org/draft-07/schema" },
    "defaults": { "$ref": { "$data": "1/input" } }
  }
}
```

In other words, I would like to validate a particular part of the target document against a schema that is defined in the target document. Is something like this possible in JSON schema or in the AJV extension of it?

**Comment by epoberezkin** [comment]
I don't understand sorry. How the document would look? What result would you expect? From the description it feels out of scope - you need to decompose it in your code.

**Comment by masaeedu** [comment]
The document would look like this:

```
{
  "input": { "type": "object", "properties": { "foo": { "type": "string" } } },
  "defaults": { "foo": 42 }
}
```

The result I expect when validating the document above would be for the `defaults` property to be rejected, since it does not conform to the schema in the `inputs` property (42 is not a string).

**Comment by epoberezkin** [comment]
I understand. It is not possible, as it would require dynamic schema compilation. You can implement it yourself, by extracting schema from the data, compiling it and validating another part of the data against it. It is quite an unusual thing to do, you need to be mindful of security implications: https://github.com/epoberezkin/ajv#security-considerations
