### ISSUE TITLE
Validate the schema 

### ISSUE THREAD

**Issue by cmaliwal** [ajv-validator/ajv#966]
How can I validate the written schema valid or not .

```
const schema = {
  "properties": {
    "foo": { "add": "string" , "minLenfeffgth": 3, "maxLefngth": 255 }
  }
};
```

above mention schema are valid schema according to  ajv.validateSchema() . 

like we validating the data , there is any function who validate the schema .

**Comment by epoberezkin** [comment]
It already happens when the schema is used with Ajv - see the docs
