### ISSUE TITLE
Feasibility of adding custom types

### ISSUE THREAD

**Issue by mycrl** [ajv-validator/ajv#967]
Adding custom validation now only implements format validation via ``addFormat``, whether to consider adding custom types for more convenient type definitions.

Use a custom type ``ObjectId``.
```json
{ _id:  { type: "ObjectId" } }
```

validation.
> this is mongodb Objectid.
```js
{ _id: xxx._id  }
```

This way to implement any type I want through a custom type.

**Comment by epoberezkin** [comment]
Sorry, it has been previously been proposed and it won’t be supported. Type is a special keyword in JSON Schema and Ajv processes it differently from other keywords, so redefining it would be very complex. Also I do think it’s a bad idea to redefine standard keywords - it is better to define new custom keywords via available extension mechanism.
