### ISSUE TITLE
additionalProperties: 'fail'

### ISSUE THREAD

**Issue by fogine** [ajv-validator/ajv#968]
**What version of Ajv you are you using?**

`6.9.2`

**What problem do you want to solve?**
```javascript
{
    type: 'object',
    additionalProperties: false,
    properties: {
        prop1: {type: 'string'}
    }
}
```

When accepting strict set of properties from insecure input, it would be handy if you could declare the schema so that on presence of any other additional property, validation would fail. Filtering out properties with `additionalProperties:false` is fine most of the time, however sometimes, when dealing with "sensitive" data, you want to explicitly reject the input.

**What do you think is the correct solution to problem?**

One solution would be to allow to set `additionalProperties` to `"fail"` in json-schema.

**Will you be able to implement it?**
not in the nearest future

**Comment by fogine** [comment]
Hmm, when thinking about it, it would be against `json-schema` specs to allow string value for `additionalProperties` keyword. Thats not acceptable.  
For the time being will solve it by custom keyword. Would be nice to have the functionality build-in though because it would not introduce hassle with wrapping schema into {allOf: []} to make sure custom keywords are run first.

**Comment by epoberezkin** [comment]
Sorry but what’s wrong with additionalProperties: false? Won’t it do exactly that?

**Comment by fogine** [comment]
My apologies, at first I didn't realize that described behavior applies when Ajv `removeAdditional=true` constructor option is set.  
One, not really sensible way to solve it is by creating another ajv instance with `removeAdditional=false` although in my case its not possible. I'm developing a plugin for a generic library which uses single `Ajv` instance for validation (makes sense). The plugin delegates validation to the parent library and in specific case I'd like to overwrite `removeAdditional=true` behavior so that it behaves like `removeAdditional=false`...  

I'm proposing a feature that would allow to set `removeAdditional=false` on schema level and overwrite validator instance default behavior.  

```javascript
const Validator = require('ajv');

const validator = new Validator({
    removeAdditional: true
})
const result = validator.validate({
    type: 'object',
    additionalProperties: false,
    removeAdditional: false,
    properties: {
        prop1: {type: 'string'}
    }
}, {prop2: 'val'});
``` 
the above example would fail with error 
> should NOT have additional properties

**Comment by epoberezkin** [comment]
Using multiple Ajv instances is the correct approach, overriding options on the schema level will not be supported
