### ISSUE TITLE
Get a schema part in a file with getSchema

### ISSUE THREAD

**Issue by goto100** [ajv-validator/ajv#97]
`getSchema` api just get the schema by name, but I want get a part schema in a file by passing property access notation.

when I run getSchema like this:

ajv.getSchem('xxx.json#/definitions/a')

I got nothing. How could it works?

**Comment by epoberezkin** [comment]
It's the same as #47 really (although not obvious from the title)...

The workaround is:

```
// assuming xxx.json is added
var validate = ajv.compile({ $ref: 'xxx.json#/definitions/a' });
```

**Comment by epoberezkin** [comment]
Closed as duplicate

**Comment by goto100** [comment]
Thanks.

but I think this is a hack way, isn't there a function called `getObjectByJsonPath` or something...

and I think it's impossible to get a part from current file like `$ref: '#/definitions/a'`, I got 

`can't resolve reference #/definitions/base from id #`

error

**Comment by goto100** [comment]
I found it, it's just stored in `refs` and `refVal`. sorry for bother you.

**Comment by epoberezkin** [comment]
Ah, you want to get some part of the actual schema, not a validation function that this part compiles to (that's what I thought)? There is no public api for that... getSchema always returns a function.

**Comment by epoberezkin** [comment]
>  I think it's impossible to get a part from current file like $ref: '#/definitions/a', I got can't resolve reference #/definitions/base from id #

Can you post the whole schema/code? Because that should be possible
