### ISSUE TITLE
removeAdditional does not work with dependencies

### ISSUE THREAD

**Issue by epicfaace** [ajv-validator/ajv#970]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest version

**Description:**
When I have a schema with dependencies, and set `removeAdditional` to `true`, then the extra fields added in the dependencies are always removed -- while I expect them to be kept in some cases.

**JSFiddle**:
https://jsfiddle.net/epicfaace/L3jf7uvy/

**Expected results**:
I expect the following to be console logged:
```
{name: "abc", credit_card: 123, billing_address: "abc"}
```

**Actual results**
The following is console logged:
```
{name: "abc", credit_card: 123}
```

**Comment by epicfaace** [comment]
Actually, it looks like this problem can be isolated to the following: if additionalProperties is false, then adding a new property using "dependencies" is not recognized.

(Sample JSFiddle: https://jsfiddle.net/epicfaace/y6ketmrp/)

Sample schema
```
{
  "type": "object",
  "additionalProperties": false,

  "properties": {
    "name": {
      "type": "string"
    },
    "credit_card": {
      "type": "number"
    }
  },

  "required": ["name"],

  "dependencies": {
    "credit_card": {
        "properties": {
          "credit_card": {
            "const": 123
          },
          "billing_address": {
            "type": "string"
          }
        },
        "required": ["billing_address"]
    }
  }

}
```

Sample data
```
{
  "name": "abc",
  "credit_card": 123,
  "billing_address": "abc"
}
```

I expect the data to be valid. However, the data is parsed as invalid.

Note that when I set `additionalProperties` to true, then the data becomes valid again.

**Comment by epoberezkin** [comment]
This is how removeAdditional is defined - see the docs. You may need to define a schema differently - please address the question to StackOverflow.

**Comment by epicfaace** [comment]
@epoberezkin this is particularly to solve https://github.com/mozilla-services/react-jsonschema-form/pull/1190 which is used in react-jsonschema-form -- we need to support schemas with the form `dependencies` and we can't really "define the schema differently." Is there any way to use ajv's removeAdditional functionality to support this?


See https://github.com/mozilla-services/react-jsonschema-form/pull/1190#issuecomment-471121231

**Comment by epicfaace** [comment]
@epoberezkin any thoughts on this?
