### ISSUE TITLE
return property of the failing validation

### ISSUE THREAD

**Issue by VMBindraban** [ajv-validator/ajv#974]
**What version of Ajv you are you using?**
5.5

**What problem do you want to solve?**
Getting the property that failed the validation from the validation error.

Example:
```
{
  type: 'object',
  properties: {
    lastName: {
      type: 'string',
    },
  },
  required: ['lastName'],
}
```

This returns:

```
{ 
keyword: 'required',
  dataPath: '',
  schemaPath: '#/required',
  params: { missingProperty: 'lastName' },
  message: "should have required property 'lastName'" 
}
```

Is there an option to get which property failed? e.g. `lastName`.

Using the `params` object doesn't always suffice e.g:

```
{ 
  keyword: 'type',
  dataPath: '.lastName',
  schemaPath: '#/properties/lastName/type',
  params: { type: 'integer' } 
  message: "some message"
}
```

**What do you think is the correct solution to problem?**
Returning something like:
```
{ 
  property: 'lastName',
  keyword: 'required',
  dataPath: '',
  schemaPath: '#/required',
  params: { missingProperty: 'lastName' },
  message: "should have required property 'lastName'" 
}
```
**Will you be able to implement it?**
Maybe

**Comment by VMBindraban** [comment]
Found a similar issue: https://github.com/epoberezkin/ajv/issues/255

Using `errorDataPath: 'property',` as option gives back the property in the `dataPath`.

**Comment by VMBindraban** [comment]
Just noticed that `errorDataPath` is deprecated. 
It does still work for me but is there an other way to get the property names?

**Comment by epoberezkin** [comment]
The possible approach is to have a code dependent on the keyword in the error message. dataPath defines the level in the data that has the problem - in case of “required” the error is in the object, not in the property.

This has been changed from draft-04 of JSON Schema specification, before that you needed to use `required: true` on the property level. You could submit this issue to https://github.com/epoberezkin/json-schema-usage-problems

**Comment by VMBindraban** [comment]
Is there any other way when using version 6?
