### ISSUE TITLE
Strict mode: Cannot assign to read only property 'constructor' of object 'Error'

### ISSUE THREAD

**Issue by whuntAffinipay** [ajv-validator/ajv#977]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

ajv@6.10.0, happens with the latest version

**Ajv options object**

No options set

No Options

**JSON Schema**

No Schema

**Sample data**

No Sample

**Your code**

Change lib/compile/error_classes.js so that strict mode will not throw errors

 function errorSubclass(Subclass) {
   Subclass.prototype = Object.create(Error.prototype);
\-  Subclass.prototype.constructor = Subclass;
\+  Object.defineProperty(Subclass, 'constructor', {
\+    enumerable: false,
\+    configurable: false,
\+    writable: false,
\+    value: Subclass
\+  });
\+
   return Subclass;
 }

**Validation result, data AFTER validation, error messages**
Strict mode no longer throws errors

**What results did you expect?**
Strict mode to not throw errors

**Are you going to resolve the issue?**
I have a branch

**Comment by epoberezkin** [comment]
Could you clarify what do you mean by strict mode? The file already has “use strict”, so it is in strict mode.

**Comment by epoberezkin** [comment]
closing
