### ISSUE TITLE
Ajv doesn't validate 2 schemas properties. 

### ISSUE THREAD

**Issue by oleksandr-maliarenko** [ajv-validator/ajv#982]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

The one that's integrated into Postman.

**Ajv options object**

```{allErrors: true, logger: console}```

**JSON Schema**

```
{
    "properties": {
        "id": {
            "type": "number"
        },
        "test": {
            "type": "string"
        },
    },
}
```

**Sample data**

```
{
        "id": 2,
        "name": "051"
    };
```

**Your code**

```
var Ajv = require('ajv'),
ajv = new Ajv({allErrors: true, logger: console}),
schema = {
    "properties": {
        "id": {
            "type": "number"
        },
        "test": {
            "type": "string"
        },
    },
},
testSchema = {
        "id": 2,
        "name": "051"
    };
var validate = ajv.compile(schema);
test(testSchema);

function test(data) {
  var valid = validate(data);
  console.log(valid)
  if (valid) console.log('Valid!');
  else console.log('Invalid: ' + ajv.errorsText(validate.errors));
}
```

**Validation result, data AFTER validation, error messages**

```
true
"Valid!"

```

**What results did you expect?**
An error should appear that shows that 2 objects are not similar, "test" property is absent on `testSchema` object. 

**Additional details** 
When I add `"required": ["id", "test"]` to `schema` variable - it throws an error: `"Invalid: data should have required property 'test'"`. But if I change type to `'number'` for `'test'` property - it won't validate it.

**Comment by epoberezkin** [comment]
> An error should appear that shows that 2 objects are not similar, "test" property is absent on testSchema object.

For it to happen, the schema should have "required" keyword - see JSON schema specification.

> When I add "required": ["id", "test"] to schema variable - it throws an error: "Invalid: data should have required property 'test'"

That is how it should be

> But if I change type to 'number' for 'test' property - it won't validate it.

I don't understand what you mean here - please submit a full example of the working code to runkit.com that you think behaves incorrectly. I believe that the behaviour is correct (according to JSON schema spec) but it can be unexpected.

**Comment by oleksandr-maliarenko** [comment]
@epoberezkin  

I didn't not compile schema as shown on Postman example but should have as it is shown on yours examples. 
My problem. 

Thanks.
