### ISSUE TITLE
any way to validate that an object is a buffer?

### ISSUE THREAD

**Issue by AVVS** [ajv-validator/ajv#99]
basically I'm speaking of a custom type, which might be useful as a built-in via `Buffer.isBuffer()` check in node.js env

**Comment by epoberezkin** [comment]
You need to define a [custom keyword](https://github.com/epoberezkin/ajv#defining-custom-keywords) for that.

**Comment by AVVS** [comment]
ok, ty.

**Comment by epoberezkin** [comment]
See `instanceof` keyword in [ajv-keywords](https://github.com/epoberezkin/ajv-keywords#instanceof)
