### ISSUE TITLE
validator returns true on string

### ISSUE THREAD

**Issue by dvvtms** [ajv-validator/ajv#999]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
yes

**Ajv options object**

```javascript

{}
```

**JSON Schema**

```javascript
var schema = {
  properties: {
    userId: {
      type: "integer",
      idExists: { table: "users" }
    },
    postId: {
      type: "integer",
      idExists: { table: "posts" }
    }
  }
};

```

**Sample data**

```javascript
const validData = "";

```

**Your code**

```javascript
const validData = "";
const Ajv = require("ajv");
var ajv = new Ajv();
console.log(ajv.validate(schema, validData)); //true

```

**What results did you expect?**
```
false

```

**Comment by afwn90cj93201nixr2e1re** [comment]
add `type:"object",` at the top.

@epoberezkin ajv'шкой можно валидировать jwt токен быстрее чем стандартным .match?
![image](https://user-images.githubusercontent.com/9306996/56598279-49c49380-6605-11e9-8769-21a28d75fb2a.png)

**Comment by epoberezkin** [comment]
Ajv uses .test for pattern keyword, not sure if it's faster.

**Comment by dvvtms** [comment]
@epoberezkin and my issue ? :) its correct behavior return true on empty string?

**Comment by afwn90cj93201nixr2e1re** [comment]
![image](https://user-images.githubusercontent.com/9306996/56647441-825e7e80-6692-11e9-8ad0-d55fa7baadb2.png)
